Repository pagopa/io-app, pull requests merged in 2020-03, with the labels that each got.

#1560 [#170928704] fix footer buttons fontSize
  ts/components/ui/FooterWithButtons.tsx
Labels: wip :hourglass:

#1592 [#171570702] Avoid to persist messages section
  ts/boot/configureStoreAndPersistor.ts
  ts/store/reducers/entities/index.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
Labels: to-be-tested

#1593 [#171600487] Add patch file to send mixpanel data to EU host
  ios/Podfile.lock
  package.json
  patches/react-native-mixpanel+1.1.1.patch
  patches/react-native-mixpanel+1.2.0.patch
  ts/@types/react-native-mixpanel.d.ts
  yarn.lock
Labels: to-be-tested

#1377 [#167319140]Added modal with a message to invite the user to update app
  .gitignore
  img/icons/update-icon.png
  img/icons/update-icon@2x.png
  img/icons/update-icon@3x.png
  locales/en/index.yml
  locales/it/index.yml
  mock-google-services.json
  package.json
  ts/RootContainer.tsx
  ts/UpdateAppModal.tsx
  ts/store/reducers/backendInfo.ts
  ts/utils/__tests__/appVersion.test.ts
  ts/utils/appVersion.ts
  yarn.lock
Labels: backend-block, on-hold :raised_hand:

#1584 [#171562237] Add download and delete user data requests
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/api/backend.ts
  ts/navigation/ProfileNavigator.ts
  ts/sagas/startup.ts
  ts/sagas/user/__test__/userDataProcessing.test.ts
  ts/sagas/user/userDataProcessing.ts
  ts/sagas/user/userMetadata.ts
  ts/screens/onboarding/TosScreen.tsx
  ts/screens/profile/PreferencesScreen.tsx
  ts/screens/profile/PrivacyMainScreen.tsx
  ts/screens/profile/PrivacyScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/store/actions/types.ts
  ts/store/actions/userDataProcessing.ts
  ts/store/reducers/emailValidation.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
  ts/store/reducers/userDataProcessing.ts
Labels: backend-block

#1538 [#170819000] fix payments screen
  ts/components/wallet/PaymentBannerComponent.tsx
  ts/screens/wallet/AddPaymentMethodScreen.tsx
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
  ts/utils/stringBuilder.ts
Labels: ready to go

#1573 [#171330968] Add a modal to handle backend systems failure
  .env.example
  .env.production
  img/servicesStatus/error-detail-icon.png
  img/servicesStatus/error-detail-icon@2x.png
  img/servicesStatus/error-detail-icon@3x.png
  locales/en/index.yml
  locales/it/index.yml
  ts/RootContainer.tsx
  ts/SystemOffModal.tsx
  ts/api/backendPublic.ts
  ts/config.ts
  ts/sagas/__tests__/backendServicesStatus.test.ts
  ts/sagas/backendInfo.ts
  ts/sagas/backendStatus.ts
  ts/sagas/index.ts
  ts/sagas/services/handleOrganizationNameUpdateSaga.ts
  ts/sagas/startup.ts
  ts/sagas/startup/loadSessionInformationSaga.ts
  ts/store/actions/backendStatus.ts
  ts/store/actions/types.ts
  ts/store/reducers/__tests__/backendStatus.test.ts
  ts/store/reducers/appState.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
Labels: ready to go

#1617 [#172000946] update preferences list items UI
  locales/en/index.yml
  locales/en/profile/profile_preferences_spid_email.md
  locales/it/index.yml
  locales/it/profile/profile_preferences_spid_email.md
  ts/screens/profile/PreferencesScreen.tsx
Labels: ready to go

#1608 [#171923601] update error management
  ts/sagas/backendInfo.ts
  ts/sagas/startup/loadSessionInformationSaga.ts
  ts/sagas/startup/watchLoadMessageWithRelationsSaga.ts
Labels: ready to go
