Repository pagopa/io-app, pull requests merged in 2020-04, with the labels that each got.

#1634 [#172085594] fix bottom space iphone x
  ts/theme/components/Content.ts
  ts/utils/constants.ts
Labels: wip :hourglass:

#1662 [#171742890] Fix ItemSeparatorComponent height
  ts/components/ItemSeparatorComponent.tsx
Labels: ready to go

#1653 [#172143512] Fixed profile upsert failure untracked on profile saga
  ts/sagas/profile.ts
Labels: ready to go

#1659 [#172205784] add ignored urls in Reactotron config
  ts/boot/configureRectotron.ts
Labels: ready to go

#1656 [#172059281] Bug service without mail display wrong text
  ts/screens/services/ServiceDetailsScreen.tsx
Labels: ready to go

#1657 [#172175144] Edit FAQ message
  locales/en/faq/faq55.md
  locales/it/faq/faq55.md
Labels: ready to go

#1649 [#172074952] avoid download delete profile data with unverified email
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/PrivacyMainScreen.tsx
Labels: ready to go

#1651 [#171994417] Reload profile on error
  package.json
  ts/sagas/profile.ts
Labels: backend-block, on-hold :raised_hand:

#1674 [#172275240] Support more than 10 transactions
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/api/pagopa.ts
  ts/components/wallet/TransactionsList.tsx
  ts/config.ts
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/wallet/TransactionsScreen.tsx
  ts/screens/wallet/WalletHomeScreen.tsx
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/store/actions/wallet/transactions.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/wallet/transactions.ts
Labels: to-be-tested

#1612 [#171865417] Enable shuffle pinpad only for payments
  .env.example
  .env.local
  .env.production
  ts/IdentificationModal.tsx
  ts/components/Pinpad/index.tsx
  ts/config.ts
  ts/sagas/identification.ts
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/store/actions/identification.ts
  ts/store/reducers/identification.ts
Labels: on-hold :raised_hand:

#1650 [#172173060] update payment success message
  locales/en/index.yml
  locales/it/index.yml
  ts/components/messages/MessageListItem.tsx
  ts/navigation/MainNavigator.tsx
  ts/navigation/WalletNavigator.ts
  ts/navigation/routes.ts
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/TransactionSuccessScreen.tsx
  ts/store/actions/navigation.ts
Labels: wip :hourglass:

#1628 [#172036343] update transaction summary
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/ListItemComponent.tsx
  ts/components/wallet/PaymentMethodsList.tsx
  ts/components/wallet/PaymentSummaryComponent.tsx
  ts/components/wallet/SlidedContentComponent.tsx
  ts/navigation/MainNavigator.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/screens/wallet/TransactionDetailsScreen.tsx
  ts/screens/wallet/payment/TransactionSuccessScreen.tsx
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
  ts/theme/components/Text.ts
  ts/theme/components/View.ts
  ts/theme/variables.ts
  ts/utils/strings.ts
Labels: wip :hourglass:
