Repository pagopa/io-app, pull requests merged in 2020-10, with the labels that each got.

#2248 fix(Bonus Vacanze): [#175058176] Fixes the color of bonus status badge text
  ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx
Labels: bonus-vacanze :surfer::snowboarder:

#2270 fix(Android): [#175090703] CTA text not aligned in the Android Bonus_Request_Information screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/common/components/BonusInformationComponent.tsx
Labels: android, ui-layout

#2280 chore: [#174966784] Update README
  README.md
Labels: documentation

#2297 feat: [#175228211] Update Internationalization section in README
  README.md
Labels: documentation
