Repository pagopa/io-app, pull requests merged in 2020-08, with the labels that each got.

#2125 [#174160605] Empty urls causes crash [Android]
  ts/components/RemindUpdatePagoPaVersionOverlay.tsx
  ts/components/ui/Markdown/handlers/link.ts
  ts/screens/modal/UpdateAppModal.tsx
  ts/utils/url.ts
Labels: android

#2129 [#174193291] Fixes the sticky headers on message deadlines component
  ts/components/messages/MessageAgenda.tsx
Labels: android

#2131 fix: [#173937093] Messages: refresh indicator not shown on iOS devices
  ts/components/messages/MessageList.tsx
Labels: ios

#2156 feat: [#174321085] Save Bonus Vacanze screenshot
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/it/pagopa/io/app/MainApplication.java
  android/settings.gradle
  ios/Podfile.lock
  jest.config.js
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/bonusVacanze/screens/ActiveBonusScreen.tsx
  ts/utils/permission.ts
  ts/utils/share.ts
  yarn.lock
Labels: bonus-vacanze :surfer::snowboarder:

#2168 fix: [#174160259] Switch label to change text on switch value change
  ts/screens/services/ServiceDetailsScreen.tsx
Labels: on-hold :raised_hand:
