Repository pagopa/io-app, pull requests merged in 2021-07, with the labels that each got.

#3180 feat(Redesign Servizi): [IARS-4,IARS-6] Implements footer component for ServicesHome screen to enable, disable all services
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/ServiceList.tsx
  ts/components/services/ServicePreferenceSummary.tsx
  ts/components/services/ServicesEnablingFooter.tsx
  ts/screens/services/ServicesHomeScreen.tsx
Labels: Redesign Servizi

#3165 chore(Redesign Servizi): [IARS-8] Adds the bottom sheet to confirm the manual option
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/screens/profile/components/services/ManualConfigBottomSheet.tsx
  ts/screens/profile/components/services/ServicesContactComponent.tsx
Labels: Redesign Servizi

#3182 chore(Redesign Servizi): [IARS-26] Preference summary is displayed only on national list as footer
  ts/components/core/typography/Link.tsx
  ts/components/services/ServiceList.tsx
  ts/components/services/ServicePreferenceSummary.tsx
  ts/screens/services/ServicesHomeScreen.tsx
Labels: Redesign Servizi

#3177 chore(Redesign Servizi): [IARS-20,IARS-21] Introduces networking types and store definition for services preference
  ts/sagas/services/servicePreference/handleGetServicePreferenceSaga.ts
  ts/sagas/services/servicePreference/handleUpsertServicePreferenceSaga.ts
  ts/sagas/services/watchLoadServicesSaga.ts
  ts/screens/services/ServicesHomeScreen.tsx
  ts/store/actions/services/index.ts
  ts/store/actions/services/servicePreference.ts
  ts/store/reducers/entities/services/__tests__/index.test.ts
  ts/store/reducers/entities/services/__tests__/servicePreference.test.ts
  ts/store/reducers/entities/services/currentService.ts
  ts/store/reducers/entities/services/index.ts
  ts/store/reducers/entities/services/servicePreference.ts
  ts/types/services/ServicePreferenceResponse.ts
Labels: Redesign Servizi

#3178 feat(Redesign Servizi): [IARS-13] Isolate toggle components for service contact preference handling
  ts/components/services/ContactPreferencesToggles/PreferenceToggleRow.tsx
  ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx
  ts/components/services/ContactPreferencesToggles/__test__/PreferenceToggleRow.test.tsx
  ts/components/services/ContactPreferencesToggles/__test__/__snapshots__/PreferenceToggleRow.test.tsx.snap
  ts/components/services/ContactPreferencesToggles/index.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
Labels: Redesign Servizi

#3189 fix(Redesign Servizi): [IARS-22] Implements accessibility on ServiceContactComponent
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/components/services/ServicesContactComponent.tsx
Labels: Redesign Servizi

#3184 chore(Redesign Servizi): [IARS-7] Introduces thank you page for service preference save
  locales/en/index.yml
  locales/it/index.yml
  ts/navigation/OnboardingNavigator.ts
  ts/navigation/routes.ts
  ts/sagas/services/servicesOptinSaga.ts
  ts/sagas/startup.ts
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/onboarding/ServicePreferenceCompleteScreen.tsx
  ts/screens/profile/components/services/ServicesContactComponent.tsx
  ts/store/actions/navigation.ts
Labels: Redesign Servizi

#3128 chore(Sicilia Vola): [IASV-7] Create SiciliaVola voucher generation workunit
  ts/features/bonus/siciliaVola/navigation/actions.ts
  ts/features/bonus/siciliaVola/navigation/navigator.ts
  ts/features/bonus/siciliaVola/navigation/routes.ts
  ts/features/bonus/siciliaVola/saga/index.ts
  ts/features/bonus/siciliaVola/saga/orchestration/voucherGeneration.ts
  ts/features/bonus/siciliaVola/screens/voucherGeneration/CheckStatusRouterScreen.tsx
  ts/features/bonus/siciliaVola/store/actions/voucherGeneration.ts
  ts/navigation/ServicesNavigator.ts
  ts/sagas/startup.ts
Labels: Sicilia Vola

#3187 chore(Redesign Servizi): [IARS-27] Removes the option to set Email forwarding preference by service
  ts/screens/profile/EmailForwardingScreen.tsx
Labels: Redesign Servizi

#3194 feat(Bonus Pagamenti Digitali): [IAC-96] Remove cashback item from FeaturedCardCarousel in wallet
  ts/features/wallet/component/__test__/FeaturedCardCarousel.test.tsx
  ts/features/wallet/component/card/FeaturedCardCarousel.tsx
Labels: Bonus Pagamenti Digitali

#3191 feat(Redesign Servizi): [IARS-24] Update profile services preference mode
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/__tests__/FiscalCodeLandscapeOverlay.test.tsx
  ts/components/services/ServicePreferenceSummary.tsx
  ts/components/services/ServicesEnablingFooter.tsx
  ts/features/bonus/bonusVacanze/store/reducers/__tests__/allActive.test.ts
  ts/features/bonus/cgn/components/detail/__test__/CgnCardComponent.test.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/__tests__/profile.test.ts
  ts/sagas/__tests__/watchEmailValidatedChangedSaga.test.ts
  ts/sagas/profile.ts
  ts/sagas/startup/__tests__/checkAcceptedTosSaga.test.ts
  ts/sagas/startup/__tests__/checkProfileEmailSaga.test.ts
  ts/sagas/startup/__tests__/checkProfileEnabledSaga.test.ts
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/PreferencesScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/screens/profile/components/services/ServicesContactComponent.tsx
  ts/store/reducers/__tests__/profile.test.ts
  ts/store/reducers/profile.ts
Labels: Redesign Servizi, dont-merge :raised_hand:

#3197 feat(Bonus Pagamenti Digitali): [IAC-97] Remote configuration for cashback enroll after add payment method
  ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.ts
  ts/features/bonus/bpd/saga/orchestration/activateBpdOnNewAddedPaymentMethods.ts
  ts/features/bonus/bpd/screens/details/components/summary/__test__/bpdSummaryComponent.test.tsx
  ts/features/bonus/bpd/screens/details/components/summary/ranking/SuperCashbackRankingSummary.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/wallet/privative/component/__tests__/PrivativeWalletPreview.test.tsx
  ts/sagas/wallet.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/__tests__/backendStatus.test.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/wallet/__mocks__/wallets.ts
  ts/types/backendStatus.ts
Labels: Bonus Pagamenti Digitali

#3196 chore(Redesign Servizi): [IARS-25] Add services preference mode opt-in on startup
  ts/sagas/services/servicesOptinSaga.ts
  ts/sagas/startup.ts
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/screens/profile/components/services/ServicesContactComponent.tsx
  ts/store/actions/navigation.ts
  ts/store/reducers/profile.ts
Labels: Redesign Servizi

#3199 feat(EU Covid Certificate): [IAGP-66] Export screenshot in PNG format
  ts/features/euCovidCert/screens/valid/EuCovidCertMarkdownDetailsScreen.tsx
  ts/features/euCovidCert/screens/valid/EuCovidCertValidScreen.tsx
  ts/features/euCovidCert/utils/screenshot.ts
Labels: EU Covid Certificate

#3186 chore(Redesign Servizi): [IARS-23] Introduces Service Preference API Saga and toggle component store linking
  locales/en/index.yml
  locales/it/index.yml
  ts/api/backend.ts
  ts/components/services/ContactPreferencesToggles/PreferenceToggleRow.tsx
  ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx
  ts/components/services/ContactPreferencesToggles/__test__/PreferenceToggleRow.test.tsx
  ts/components/services/ContactPreferencesToggles/__test__/__snapshots__/PreferenceToggleRow.test.tsx.snap
  ts/components/services/ContactPreferencesToggles/index.tsx
  ts/sagas/services/servicePreference/handleGetServicePreferenceSaga.ts
  ts/sagas/services/servicePreference/handleUpsertServicePreferenceSaga.ts
  ts/sagas/services/watchLoadServicesSaga.ts
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/store/actions/services/servicePreference.ts
  ts/store/reducers/entities/services/__tests__/servicePreference.test.ts
  ts/types/services/ServicePreferenceResponse.ts
Labels: Redesign Servizi

#3195 chore(Redesign Servizi): [IARS-29] Add mixpanel track for newly integrated service preference API
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/store/middlewares/analytics.ts
  ts/store/middlewares/serviceAnalytics.ts
Labels: Redesign Servizi

#3202 fix(Redesign Servizi): [IARS-30] Conditions to send event is never raised
  ts/screens/profile/ServicesPreferenceScreen.tsx
Labels: Redesign Servizi

#3207 fix(Redesign Servizi): [IARS-31] Items on service contact preference screen uses the device locale and not the app selected
  ts/screens/profile/components/services/ServicesContactComponent.tsx
Labels: Redesign Servizi

#3211 chore(Redesign Servizi): [IARS-34] Implements saga to handle profile preference upsert success action
  ts/sagas/profile.ts
  ts/sagas/startup/__tests__/checkProfileEnabledSaga.test.ts
  ts/sagas/wallet.ts
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/store/actions/profile.ts
  ts/store/reducers/profile.ts
Labels: Redesign Servizi

#3200 feat(Redesign Servizi): [IARS-14] TOS and info new section
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/TosAndPrivacyBox.tsx
  ts/components/services/__tests__/TosAndPrivacyBox.test.tsx
  ts/components/services/__tests__/__snapshots__/TosAndPrivacyBox.test.tsx.snap
  ts/screens/services/ServiceDetailsScreen.tsx
Labels: Redesign Servizi

#3214 fix(Redesign Servizi): [IARS-37] Fix disabled webhook flag when reactivating service communication
  ts/sagas/services/servicePreference/handleUpsertServicePreferenceSaga.ts
Labels: Redesign Servizi

#3215 chore(Redesign Servizi): [IARS-38] Removes the Enabling footer button from ServicesHomeScreen
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/ServiceList.tsx
  ts/components/services/ServicePreferenceSummary.tsx
  ts/components/services/ServicesEnablingFooter.tsx
  ts/screens/profile/PreferencesScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
Labels: Redesign Servizi

#3206 fix(Redesign Servizi): [IARS-32] Service item could appear disabled
  ts/components/services/NewServiceListItem.tsx
Labels: Redesign Servizi

#3216 fix(Redesign Servizi): [IARS-39] Fix services not selected from message detail screen
  ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx
  ts/components/services/ContactPreferencesToggles/index.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
Labels: Redesign Servizi

#3170 chore(Sicilia Vola): [IASV-22] Model SiciliaVola store and reducer
  ts/features/bonus/siciliaVola/store/actions/index.ts
  ts/features/bonus/siciliaVola/store/actions/voucherGeneration.ts
  ts/features/bonus/siciliaVola/store/actions/voucherList.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/availableDestinations.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/availableMunicipalities.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/availableProvinces.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/availableRegions.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/availableStates.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/voucherGenerated.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/voucherList.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/voucherRequest.test.ts
  ts/features/bonus/siciliaVola/store/reducers/availableDestinations.ts
  ts/features/bonus/siciliaVola/store/reducers/availableMunicipalities.ts
  ts/features/bonus/siciliaVola/store/reducers/availableProvinces.ts
  ts/features/bonus/siciliaVola/store/reducers/availableRegions.ts
  ts/features/bonus/siciliaVola/store/reducers/availableStates.ts
  ts/features/bonus/siciliaVola/store/reducers/index.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGenerated.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherList.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherRequest.ts
  ts/features/bonus/siciliaVola/types/SvVoucherRequest.ts
  ts/features/bonus/siciliaVola/types/svVoucher.ts
  ts/features/bonus/siciliaVola/types/svVoucherResponse.ts
Labels: Sicilia Vola

#3220 chore(Redesign Servizi): [IARS-28] Removes services redesign FF and cleanup dead code
  .env.local
  .env.production
  ts/components/services/NewServiceListItem.tsx
  ts/components/services/ServiceList.tsx
  ts/components/services/ServicesSearch.tsx
  ts/components/services/ServicesSectionsList.tsx
  ts/components/services/ServicesTab.tsx
  ts/config.ts
  ts/sagas/services/watchLoadServicesSaga.ts
  ts/sagas/startup.ts
  ts/screens/profile/EmailForwardingScreen.tsx
  ts/screens/profile/PreferencesScreen.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
Labels: Redesign Servizi

#3203 feat: [#174730105,IA-96] Add support to german language
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  scripts/make-locales.ts
  ts/boot/configureInstabug.ts
  ts/components/RegionServiceWebView.tsx
  ts/features/bonus/bonusVacanze/components/AvailableBonusItem.tsx
  ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
  ts/features/wallet/component/card/FeaturedCardCarousel.tsx
  ts/i18n.ts
  ts/store/reducers/content.ts
  ts/types/MessageCTA.ts
  ts/utils/__tests__/content.test.ts
  ts/utils/__tests__/locale.test.ts
  ts/utils/__tests__/messages.test.ts
  ts/utils/dates.ts
  ts/utils/locale.ts
  ts/utils/messages.ts
Labels: dont-merge :raised_hand:

#3229 fix(Redesign Servizi): [IARS-36] Android doesn't show activity indicator on service preference switches
  ts/components/services/ContactPreferencesToggles/PreferenceToggleRow.tsx
  ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx
  ts/components/ui/ActivityIndicator.tsx
  ts/components/ui/__test__/ActivityIndicator.test.tsx
  ts/components/ui/__test__/__snapshots__/ActivityIndicator.test.tsx.snap
  ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.ts
  ts/store/reducers/__mock__/backendStatus.ts
Labels: Redesign Servizi

#3219 chore(Redesign Servizi): [IARS-40] Removes the currentSelectedService reducer and action
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/store/actions/services/index.ts
  ts/store/reducers/entities/index.ts
  ts/store/reducers/entities/services/__tests__/index.test.ts
  ts/store/reducers/entities/services/currentService.ts
  ts/store/reducers/entities/services/index.ts
  ts/store/reducers/index.ts
Labels: Redesign Servizi

#3212 chore(Sicilia Vola): [IASV-6] Added screens layout, routing and navigation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/siciliaVola/components/AcceptTosComponent.tsx
  ts/features/bonus/siciliaVola/components/CheckResidenceComponent.tsx
  ts/features/bonus/siciliaVola/navigation/actions.ts
  ts/features/bonus/siciliaVola/navigation/navigator.ts
  ts/features/bonus/siciliaVola/navigation/placeholder
  ts/features/bonus/siciliaVola/navigation/routes.ts
  ts/features/bonus/siciliaVola/screens/placeholder
  ts/features/bonus/siciliaVola/screens/voucherGeneration/CheckStatusRouterScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/DisabledAdditionalInfoScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/SelectBeneficiaryCategoryScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/SelectFlightsDateScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/SickCheckIncomeScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/SickSelectDestinationScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/StudentSelectDestinationScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/SummaryScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/VoucherGeneratedScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/WorkerCheckIncomeScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/WorkerSelectDestinationScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/ko/SvCheckIncomeKoScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/ko/SvCheckResidenceKoScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/ko/SvGeneratedVoucherTimeoutScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/ko/SvSelectBeneficiaryCategoryKoScreen.tsx
  ts/features/bonus/siciliaVola/store/actions/activation.ts
  ts/features/bonus/siciliaVola/store/actions/index.ts
  ts/features/bonus/siciliaVola/store/reducers/activation.ts
  ts/features/bonus/siciliaVola/store/reducers/index.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherRequest.ts
Labels: Sicilia Vola

#3232 fix(Redesign Servizi): [IARS-42] Fix Summary component showing in the middle of the screen
  ts/screens/services/ServicesHomeScreen.tsx
Labels: Redesign Servizi

#3236 feat(Bonus Pagamenti Digitali): [IAC-100] Ask to enable cashback on a new onboarded payment method only if the cashback program is active
  ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.ts
  ts/features/bonus/bpd/saga/orchestration/activateBpdOnNewAddedPaymentMethods.ts
  ts/sagas/wallet.ts
Labels: Bonus Pagamenti Digitali

#3047 fix(Bonus Vacanze): [#178113212] Fix success saga on load all activation bonus flow
  ts/features/bonus/bonusVacanze/store/actions/bonusVacanze.ts
  ts/features/bonus/bonusVacanze/store/sagas/handleLoadAllBonusActivationSaga.ts
  ts/store/middlewares/analytics.ts
Labels: Bonus Vacanze

#3238 feat(Bonus Pagamenti Digitali): [IAC-101] Display cashback capability for a payment method only if the cashback program is active
  ts/features/bonus/bpd/components/BpdPaymentMethodCapability.tsx
  ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
  ts/features/wallet/bancomatpay/screen/BPayDetailScreen.tsx
  ts/features/wallet/cobadge/screen/CobadgeDetailScreen.tsx
  ts/features/wallet/component/PagoPaPaymentCapability.tsx
  ts/features/wallet/component/PaymentMethodCapabilities.tsx
  ts/features/wallet/component/__test__/PaymentMethodCapability.test.tsx
  ts/features/wallet/privative/screen/PrivativeDetailScreen.tsx
  ts/features/wallet/satispay/screen/SatispayDetailScreen.tsx
  ts/screens/wallet/PaymentMethodDetailScreen.tsx
  ts/store/reducers/backendStatus.ts
Labels: Bonus Pagamenti Digitali

#3225 feat(Redesign Servizi): [IARS-12,IARS-15] Metadata section in profile
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx
  ts/components/services/ContactPreferencesToggles/index.tsx
  ts/components/services/LinkRow.tsx
  ts/components/services/SectionHeader.tsx
  ts/components/services/ServiceMetadata/InformationRow.tsx
  ts/components/services/ServiceMetadata/__tests__/InformationRow.test.tsx
  ts/components/services/ServiceMetadata/__tests__/ServiceMetadata.test.tsx
  ts/components/services/ServiceMetadata/__tests__/__snapshots__/InformationRow.test.tsx.snap
  ts/components/services/ServiceMetadata/index.tsx
  ts/components/services/TosAndPrivacyBox.tsx
  ts/components/services/__tests__/LinkRow.test.tsx
  ts/components/services/__tests__/SectionHeader.test.tsx
  ts/components/services/__tests__/TosAndPrivacyBox.test.tsx
  ts/components/services/__tests__/__snapshots__/LinkRow.test.tsx.snap
  ts/components/services/__tests__/__snapshots__/SectionHeader.test.tsx.snap
  ts/components/services/__tests__/__snapshots__/TosAndPrivacyBox.test.tsx.snap
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/utils/__mocks__/platform.ts
Labels: Redesign Servizi

#3241 feat(Bonus Pagamenti Digitali): [IAC-102] Add support for expired cashback as listitem in available bonuses list
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/bonusVacanze/__mock__/availableBonuses.ts
  ts/features/bonus/bonusVacanze/components/AvailableBonusItem.tsx
  ts/features/bonus/bonusVacanze/screens/AvailableBonusScreen.tsx
  ts/features/bonus/bonusVacanze/screens/__tests__/AvailableBonusScreen.test.tsx
Labels: Bonus Pagamenti Digitali

#3251 feat(Bonus Pagamenti Digitali): [IAC-109] Disable cashback onboarding and edit IBAN from message CTA if the initiative is completed
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/bpd/screens/iban/IbanCTAEditScreen.tsx
  ts/features/bonus/bpd/screens/onboarding/BpdCTAStartOnboardingScreen.tsx
Labels: Bonus Pagamenti Digitali

#3257 feat(Sicilia Vola): [IASV-13] Add SiciliaVola entry point
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ui/Markdown/handlers/internalLink.ts
  ts/features/bonus/siciliaVola/navigation/actions.ts
  ts/features/bonus/siciliaVola/navigation/navigator.ts
  ts/features/bonus/siciliaVola/navigation/routes.ts
  ts/features/bonus/siciliaVola/screens/VoucherListScreen.tsx
Labels: Sicilia Vola

#3247 feat(Bonus Pagamenti Digitali): [IAC-108] Remove Add payment method CTA from cashback details screen
  ts/features/bonus/bpd/screens/details/components/paymentMethod/WalletPaymentMethodBpdList.tsx
Labels: Bonus Pagamenti Digitali
