Repository pagopa/io-app, pull requests merged in 2021-12, with the labels that each got.

#3532 chore(Messaggi a valore legale): [IAMVL-15] Add new scope "Messaggi a valore legale" to changelog and GitHub tag
  scripts/ts/danger/utils/changelog.ts
Labels: Messaggi a valore legale

#3533 chore(Messaggi a valore legale): [IAMVL-7] Add MVL feature flag and folder structure
  .env.local
  .env.production
  ts/config.ts
  ts/features/mvl/analytics/placeholder
  ts/features/mvl/api/placeholder
  ts/features/mvl/components/placeholder
  ts/features/mvl/navigatioon/placeholder
  ts/features/mvl/saga/placeholder
  ts/features/mvl/screens/placeholder
  ts/features/mvl/store/actions/placeholder
  ts/features/mvl/store/reducers/placeholder
  ts/features/mvl/types/placeholder
Labels: Messaggi a valore legale

#3527 chore: [IA-504] Sync Paypal PM spec
  assets/paymentManager/README.MD
  assets/paymentManager/spec.json
  locales/en/index.yml
  locales/it/index.yml
  ts/api/pagopa.ts
  ts/components/wallet/payment/PickNotAvailablePaymentMethodListItem.tsx
  ts/features/wallet/paypal/PayPalWalletPreview.tsx
  ts/features/wallet/paypal/PaypalCard.tsx
  ts/utils/__mocks__/paypalAccountPsp.ts
  ts/utils/__tests__/paypal.test.ts
  ts/utils/paymentMethod.ts
  ts/utils/paypal.ts
  ts/utils/stringBuilder.ts
Labels: paypal

#3508 chore(Zendesk): [ASZ-114] Add zendesk entrypoint
  jest.config.js
  package.json
  ts/__mocks__/io-react-native-zendesk.ts
  ts/components/ZendeskChatComponent.tsx
  ts/components/__tests__/ZendeskChatComponent.test.tsx
  ts/components/screens/BaseHeader.tsx
  ts/features/bonus/bpd/screens/details/transaction/__test__/TransactionsUnavailable.test.tsx
  ts/store/reducers/authentication.ts
  ts/utils/supportAssistance.ts
  ts/utils/testFaker.ts
Labels: Zendesk

#3525 feat: [IA-501] Add Paypal during a payment
  locales/en/index.yml
  locales/it/index.yml
  ts/components/wallet/PaymentMethodsList.tsx
  ts/features/wallet/onboarding/paypal/saga/orchestration/index.ts
  ts/features/wallet/onboarding/paypal/screen/PayPalOnboardingCompletedSuccessComponent.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalOnboardingCompletedSuccessComponent.test.tsx
  ts/features/wallet/onboarding/paypal/store/actions/index.ts
  ts/screens/wallet/AddPaymentMethodScreen.tsx
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
Labels: paypal

#3535 chore(Messaggi a valore legale): [IAMVL-8] Add types, actions, store, reducers & saga entrypoint
  scripts/check_urls/check_urls.py
  ts/features/common/store/reducers/index.ts
  ts/features/euCovidCert/saga/index.ts
  ts/features/mvl/saga/index.ts
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
  ts/features/mvl/saga/placeholder
  ts/features/mvl/store/actions/index.ts
  ts/features/mvl/store/actions/placeholder
  ts/features/mvl/store/reducers/__test__/byId.test.ts
  ts/features/mvl/store/reducers/byId.ts
  ts/features/mvl/store/reducers/index.ts
  ts/features/mvl/store/reducers/placeholder
  ts/features/mvl/types/__mock__/mvlMock.ts
  ts/features/mvl/types/mvlData.ts
  ts/features/mvl/types/placeholder
  ts/sagas/startup.ts
  ts/store/actions/types.ts
  ts/store/reducers/backoffError.ts
  ts/types/contentType.ts
  ts/types/digitalInformationUnit.ts
Labels: Messaggi a valore legale

#3545 chore(Messaggi a valore legale): [IAMVL-9] Stub screens and navigation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/mvl/navigation/actions.ts
  ts/features/mvl/navigation/navigator.ts
  ts/features/mvl/navigation/routes.ts
  ts/features/mvl/navigatioon/placeholder
  ts/features/mvl/screens/MvlDetailsScreen.tsx
  ts/features/mvl/screens/MvlLoadingScreen.tsx
  ts/features/mvl/screens/MvlRouterScreen.tsx
  ts/features/mvl/screens/__test__/MvlRouterScreen.test.tsx
  ts/features/mvl/screens/ko/MvlGenericErrorScreen.tsx
  ts/features/mvl/screens/metadata/MvlCertificatesScreen.tsx
  ts/features/mvl/screens/metadata/MvlRecipientsScreen.tsx
  ts/features/mvl/screens/metadata/MvlSignatureScreen.tsx
  ts/features/mvl/screens/placeholder
  ts/navigation/MessagesNavigator.ts
Labels: Messaggi a valore legale

#3534 feat: [IA-458] Pay with Paypal
  ts/sagas/wallet.ts
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/PaymentOutcomeCodeMessage.tsx
  ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
  ts/screens/wallet/payment/common.ts
  ts/store/actions/navigation.ts
  ts/store/actions/wallet/payment.ts
  ts/store/reducers/wallet/payment.ts
Labels: paypal

#3530 feat: [IA-174,IA-484] Handle new outcome error codes
  locales/en/index.yml
  locales/it/index.yml
  ts/store/reducers/wallet/outcomeCode.ts
  ts/types/outcomeCode.ts
Labels: paypal

#3555 chore(Messaggi a valore legale): [IAMVL-17] Refinement of MVL datamodel
  ts/__mocks__/messages.ts
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
  ts/features/mvl/screens/MvlRouterScreen.tsx
  ts/features/mvl/screens/__test__/MvlRouterScreen.test.tsx
  ts/features/mvl/screens/ko/MvlGenericErrorScreen.tsx
  ts/features/mvl/store/actions/index.ts
  ts/features/mvl/store/reducers/__test__/byId.test.ts
  ts/features/mvl/store/reducers/byId.ts
  ts/features/mvl/types/__mock__/mvlMock.ts
  ts/features/mvl/types/mvlData.ts
  ts/sagas/messages/__tests__/watchLoadMessageDetails.test.ts
  ts/screens/messages/paginated/MessageDetailScreen.tsx
  ts/store/actions/messages.ts
  ts/store/reducers/entities/messages/__tests__/detailsById.test.ts
  ts/store/reducers/entities/messages/transformers.ts
  ts/store/reducers/entities/messages/types.ts
Labels: Messaggi a valore legale

#3551 chore(Messaggi a valore legale): [IAMVL-16] Extract common components shared by MessageDetailsComponent and MVLDetailsScreen
  ts/components/messages/paginated/MessageDetail/DueDateBar.tsx
  ts/components/messages/paginated/MessageDetail/MedicalPrescriptionAttachments.tsx
  ts/components/messages/paginated/MessageDetail/__tests__/CtaBar.test.tsx
  ts/components/messages/paginated/MessageDetail/__tests__/DueDate.test.tsx
  ts/components/messages/paginated/MessageDetail/__tests__/__snapshots__/DueDate.test.tsx.snap
  ts/components/messages/paginated/MessageDetail/__tests__/__snapshots__/MedicalPrescriptionAttachments.test.tsx.snap
  ts/components/messages/paginated/MessageDetail/common/CtaBar.tsx
  ts/components/messages/paginated/MessageDetail/common/HeaderDueDateBar.tsx
  ts/components/messages/paginated/MessageDetail/common/MessageTitle.tsx
  ts/components/messages/paginated/MessageDetail/index.tsx
  ts/components/messages/paginated/__tests__/MessageDetail.test.tsx
  ts/screens/messages/paginated/MessageDetailScreen.tsx
Labels: Messaggi a valore legale

#3559 chore: [IA-550] Add Paypal checkout psp info banner
  locales/en/index.yml
  locales/it/index.yml
  ts/features/wallet/paypal/component/PayPalCheckoutPspComponent.tsx
  ts/features/wallet/paypal/component/__test__/PayPalCheckoutPspComponent.test.tsx
  ts/features/wallet/paypal/component/__test__/__snapshots__/PayPalCheckoutPspComponent.test.tsx.snap
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
Labels: paypal

#3544 chore: [IA-541] Add remote assistanceTool ff
  ts/components/ZendeskSupportComponent.tsx
  ts/components/screens/BaseScreenComponent/__tests__/BaseScreenComponent.test.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/features/bonus/bpd/screens/details/transaction/__test__/TransactionsUnavailable.test.tsx
  ts/navigation/AppNavigator.ts
  ts/sagas/startup.ts
  ts/store/reducers/backendStatus.ts
  ts/utils/supportAssistance.ts
Labels: Zendesk

#3561 chore: [IA-536] Add remote zendesk config
  ts/api/content.ts
  ts/features/zendesk/saga/index.ts
  ts/features/zendesk/saga/networking/handleGetZendeskConfig.ts
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/features/zendesk/store/actions/index.ts
  ts/features/zendesk/store/reducers/index.ts
  ts/features/zendesk/store/reducers/placeholder
  ts/store/actions/types.ts
  ts/store/reducers/assistanceTools.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
Labels: Zendesk

#3569 chore: set Paypal feature flag ON
  .circleci/config.yml
  .env.production
Labels: paypal

#3480 chore(Redesign Servizi): [IARS-44] Handles "Special" services category inside service detail screen
  ts/components/cta/ExtractedCTABar.tsx
  ts/components/messages/MessageDetailComponent.tsx
  ts/components/messages/MessageDetailData.tsx
  ts/components/messages/paginated/MessageDetail/common/CtaBar.tsx
  ts/components/messages/paginated/MessageDetail/index.tsx
  ts/components/services/ServiceMetadata/__tests__/ServiceMetadata.test.tsx
  ts/components/services/ServiceMetadata/index.tsx
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/screens/messages/MessageDetailScreen/MessageDetail.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/store/reducers/entities/services/__tests__/index.test.ts
  ts/store/reducers/entities/services/servicesById.ts
  ts/utils/__tests__/messages.test.ts
  ts/utils/messages.ts
  ts/utils/url.ts
Labels: Redesign Servizi

#3536 feat: [IA-301,IA-302,IA-479,IA-506] Track Paypal onboarding & payment events
  ts/features/wallet/onboarding/paypal/analytics/index.ts
  ts/features/wallet/onboarding/paypal/saga/networking/index.ts
  ts/features/wallet/onboarding/paypal/store/actions/index.ts
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/store/actions/wallet/outcomeCode.ts
  ts/store/actions/wallet/payment.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/payments/__tests__/history.test.ts
  ts/store/reducers/payments/history.ts
  ts/store/reducers/wallet/outcomeCode.ts
Labels: paypal, legal-compliance ⚖️

#3567 chore(Messaggi a valore legale): [IAMVL-18] MvlDetailsScreen layout and components placeholders
  img/features/mvl/attachment.svg
  img/features/mvl/legalMessage.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/components/messages/paginated/MessageDetail/__tests__/CtaBar.test.tsx
  ts/components/messages/paginated/MessageDetail/common/CtaBar.tsx
  ts/components/messages/paginated/MessageDetail/common/HeaderDueDateBar.tsx
  ts/components/messages/paginated/MessageDetail/index.tsx
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
  ts/features/mvl/screens/MvlDetailsScreen.tsx
  ts/features/mvl/screens/MvlRouterScreen.tsx
  ts/features/mvl/screens/details/MvlDetailsScreen.tsx
  ts/features/mvl/screens/details/components/MvlAttachments.tsx
  ts/features/mvl/screens/details/components/MvlBody.tsx
  ts/features/mvl/screens/details/components/MvlDetailsHeader.tsx
  ts/features/mvl/screens/details/components/MvlMetadata.tsx
  ts/features/mvl/screens/details/components/__test__/MvlDetailsHeader.test.tsx
  ts/store/reducers/entities/messages/transformers.ts
  ts/store/reducers/entities/messages/types.ts
  ts/theme/components/View.ts
Labels: Messaggi a valore legale

#3571 chore: [IA-532] Complete ZendeskSupportHelpCenter screen
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ContextualHelp/index.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/components/screens/BaseScreenComponent/utils.ts
  ts/components/screens/BaseScreenComponent/utils.tsx
  ts/features/zendesk/components/ZendeskSupportComponent.tsx
  ts/features/zendesk/components/__tests__/ZendeskSupportComponent.test.tsx
  ts/features/zendesk/navigation/navigator.tsx
  ts/features/zendesk/navigation/routes.ts
  ts/features/zendesk/saga/orchestration/index.ts
  ts/features/zendesk/screens/ZendeskPanicMode.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/features/zendesk/store/actions/index.ts
  ts/features/zendesk/store/actions/navigation.ts
  ts/store/reducers/content.ts
  ts/utils/supportAssistance.ts
Labels: Zendesk

#3557 chore: [IA-546] Paypal payment flow: fix and refinement
  assets/paymentManager/README.MD
  assets/paymentManager/spec.json
  ts/components/wallet/OutcomeCodeMessageComponent.tsx
  ts/features/wallet/onboarding/paypal/screen/PayPalOnboardingCheckoutCompletedScreen.tsx
Labels: paypal

#3572 feat: [IA-556,IA-511] Manage ask assistance entry point
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/features/zendesk/store/actions/index.ts
  ts/screens/modal/IdentificationModal.tsx
Labels: Zendesk

#3578 chore: [IA-552] Add Paypal banner
  package.json
  ts/features/wallet/onboarding/paypal/screen/PayPalStartOnboardingScreen.tsx
  ts/screens/wallet/AddPaymentMethodScreen.tsx
  ts/store/reducers/__mock__/backendStatus.ts
Labels: paypal

#3575 chore(Messaggi a valore legale): [IAMVL-23] Display plain and html message body
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/core/IORenderHtml.tsx
  ts/components/core/fonts.ts
  ts/components/core/typography/Body.tsx
  ts/components/core/typography/H1.tsx
  ts/components/core/typography/H2.tsx
  ts/components/core/typography/H3.tsx
  ts/components/core/typography/H4.tsx
  ts/components/core/typography/H5.tsx
  ts/components/core/typography/Link.tsx
  ts/features/mvl/screens/details/components/MvlBody.tsx
  ts/features/mvl/screens/details/components/__test__/MvlBody.test.tsx
  ts/features/mvl/types/__mock__/mvlMock.ts
  yarn.lock
Labels: Messaggi a valore legale

#3552 chore: [IA-533] Zendesk permission detail screen
  img/assistance/battery.svg
  img/assistance/email.svg
  img/assistance/fiscalCode.svg
  img/assistance/giacenza.svg
  img/assistance/info.svg
  img/assistance/ladybug.svg
  img/assistance/login.svg
  img/assistance/nameSurname.svg
  img/assistance/telefonia.svg
  img/assistance/website.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/BaseHeader.tsx
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/store/hooks.ts
  ts/store/reducers/authentication.ts
  ts/store/reducers/index.ts
  ts/store/reducers/profile.ts
  ts/utils/device.ts
Labels: Zendesk, legal-compliance ⚖️

#3581 chore: [IA-475] Show an alert when Paypal is already in the user wallet
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/wallet/AddPaymentMethodScreen.tsx
Labels: paypal

#3590 chore: [IA-578] Update Zendesk SDK configuration value
  ts/utils/supportAssistance.ts
Labels: Zendesk

#3573 fix: [IA-566] Fix entrypoints on error and attempt screens
  ts/components/FAQComponent.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/components/screens/BaseScreenComponent/utils.tsx
  ts/components/ui/Accordion.tsx
  ts/components/ui/Markdown/index.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/screens/wallet/PaymentHistoryDetailsScreen.tsx
  ts/screens/wallet/creditCardOnboardingAttempts/CreditCardOnboardingAttemptDetailScreen.tsx
  ts/screens/wallet/payment/TransactionErrorScreen.tsx
  ts/utils/supportAssistance.ts
Labels: Zendesk

#3589 feat: [IA-542] Open ticket without share data
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
Labels: Zendesk

#3577 chore(Carta Giovani Nazionale): [IOACGN-1] Fixes card and background color
  img/bonus/cgn/card_mask.png
  img/bonus/cgn/cgn-preview.png
  img/bonus/cgn/cgn_logo.png
  locales/en/index.yml
  locales/it/index.yml
  scripts/ts/danger/utils/changelog.ts
  ts/features/bonus/cgn/components/detail/CardSvgPayload.ts
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
Labels: Carta Giovani Nazionale

#3591 chore: [IA-579] Reset assistance data on logout/sessionExpired
  ios/Podfile.lock
  package.json
  ts/sagas/startup/watchLogoutSaga.ts
  ts/sagas/startup/watchSessionExpiredSaga.ts
  ts/utils/supportAssistance.ts
  yarn.lock
Labels: Zendesk

#3593 chore: [IA-575,IA-564] Add payment info
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/features/zendesk/components/ZendeskSupportComponent.tsx
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/features/zendesk/store/actions/index.ts
  ts/features/zendesk/store/actions/navigation.ts
  ts/screens/wallet/PaymentHistoryDetailsScreen.tsx
  ts/screens/wallet/creditCardOnboardingAttempts/CreditCardOnboardingAttemptDetailScreen.tsx
  ts/screens/wallet/payment/TransactionErrorScreen.tsx
  ts/utils/supportAssistance.ts
Labels: Zendesk

#3598 feat: [IA-514,IA-519] Update android color
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/styles.xml
Labels: Zendesk

#3595 chore: [IA-585] Send support information
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/features/zendesk/screens/ZendeskChooseCategory.tsx
  ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/IdpSelectionScreen.tsx
  ts/screens/authentication/cie/CieCardReaderScreen.tsx
  ts/screens/onboarding/PinScreen.tsx
  ts/utils/supportAssistance.ts
Labels: Zendesk

#3601 chore: [IA-587] Add Zendesk analytics
  ts/features/zendesk/analytics/index.ts
  ts/features/zendesk/saga/orchestration/index.ts
  ts/features/zendesk/screens/ZendeskChooseCategory.tsx
  ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/features/zendesk/store/actions/index.ts
  ts/store/middlewares/analytics.ts
Labels: Zendesk

#3600 chore: [IA-586] Hide zendesk if email not validated
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/features/bonus/bpd/screens/details/transaction/__test__/TransactionsUnavailable.test.tsx
  ts/screens/wallet/PaymentHistoryDetailsScreen.tsx
  ts/screens/wallet/creditCardOnboardingAttempts/CreditCardOnboardingAttemptDetailScreen.tsx
  ts/screens/wallet/payment/TransactionErrorScreen.tsx
  ts/store/reducers/assistanceTools.ts
  ts/utils/supportAssistance.ts
Labels: Zendesk

#3608 Revert "chore: Disable android release (#3606)"
  .circleci/config.yml
Labels: dont-merge :raised_hand:

#3583 chore(Messaggi a valore legale): [IAMVL-19] Display legal message attachments
  img/features/mvl/attachmentsIcon/default.svg
  img/features/mvl/attachmentsIcon/pdf.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/features/mvl/screens/__test__/MvlRouterScreen.test.tsx
  ts/features/mvl/screens/details/MvlDetailsScreen.tsx
  ts/features/mvl/screens/details/components/MvlAttachments.tsx
  ts/features/mvl/screens/details/components/attachment/DownloadAttachmentConfirmationBottomSheet.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachments.tsx
  ts/features/mvl/screens/details/components/attachment/__test__/MvlAttachments.test.tsx
  ts/features/mvl/types/__mock__/mvlMock.ts
  ts/features/mvl/types/mvlData.ts
  ts/types/__tests__/digitalInformationUnit.test.ts
  ts/types/digitalInformationUnit.ts
Labels: Messaggi a valore legale

#3609 chore(Messaggi a valore legale): [IAMVL-32] Add get legal message API
  package.json
  ts/features/mvl/api/backendMvl.ts
  ts/features/mvl/api/placeholder
  ts/features/mvl/saga/index.ts
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
  ts/store/reducers/entities/messages/transformers.ts
Labels: Messaggi a valore legale

#3611 chore(Carta Giovani Nazionale): [IOACGN-11] Fixes API specs
  package.json
Labels: Carta Giovani Nazionale

#3610 fix: [IA-598] Fix wrong name surname value in ZendeskAskPermissions screen
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
Labels: Zendesk

#3612 chore(Messaggi a valore legale): [IAMVL-33] Update legal message error screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/mvl/screens/ko/MvlGenericErrorScreen.tsx
Labels: Messaggi a valore legale

#3615 fix: [IA-599] Fix wrong icons
  img/assistance/email.svg
  img/assistance/history.svg
  img/assistance/info.svg
  img/assistance/ladybug.svg
  img/assistance/telefonia.svg
  img/assistance/website.svg
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
Labels: Zendesk

#3599 chore(Messaggi a valore legale): [IAMVL-13] Identify MVL in the list
  ts/components/messages/paginated/MessageList/Item.tsx
  ts/components/messages/paginated/MessageList/__tests__/Item.test.tsx
  ts/components/messages/paginated/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
Labels: Messaggi a valore legale

#3549 chore: [IA-505] Copy changes related to PayPal
  locales/en/index.yml
  locales/it/index.yml
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PayPalOnboardingCompletedSuccessComponent.test.tsx.snap
Labels: paypal

#3596 chore(Messaggi a valore legale): [IAMVL-20] Display legal message metadata
  jest.config.js
  jestGlobalSetup.js
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/core/accordion/IOAccordion.tsx
  ts/components/core/accordion/RawAccordion.tsx
  ts/components/core/accordion/__test__/RawAccordion.test.tsx
  ts/components/messages/paginated/MessageDetail/__tests__/__snapshots__/Content.test.tsx.snap
  ts/components/ui/Accordion.tsx
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
  ts/features/mvl/screens/details/MvlDetailsScreen.tsx
  ts/features/mvl/screens/details/components/MvlDetailsHeader.tsx
  ts/features/mvl/screens/details/components/MvlMetadata.tsx
  ts/features/mvl/screens/details/components/__test__/MvlDetailsHeader.test.tsx
  ts/features/mvl/screens/details/components/__test__/MvlMetadata.test.tsx
  ts/features/mvl/types/__mock__/mvlMock.ts
  ts/features/mvl/types/mvlData.ts
  ts/screens/showroom/OthersShowroom.tsx
Labels: Messaggi a valore legale

#3622 chore(Carta Giovani Nazionale): [IOACGN-15] Update CGN specs endpoint
  package.json
Labels: Carta Giovani Nazionale

#3621 feat(Messaggi a valore legale): [IAMVL-21] Read status for MVL
  ts/features/mvl/screens/MvlRouterScreen.tsx
  ts/features/mvl/screens/__test__/MvlRouterScreen.test.tsx
Labels: Messaggi a valore legale

#3618 chore(Messaggi a valore legale): [IAMVL-27,IAMVL-34] Download attachments
  ios/Podfile.lock
  jestSetup.js
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
  ts/features/mvl/screens/details/components/attachment/DownloadAttachmentConfirmationBottomSheet.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachments.tsx
  ts/features/mvl/screens/details/components/attachment/__test__/MvlAttachments.test.tsx
  ts/features/mvl/types/__mock__/mvlMock.ts
  ts/features/mvl/types/mvlData.ts
  ts/features/mvl/utils.ts
  ts/store/reducers/authentication.ts
  ts/types/contentType.ts
  yarn.lock
Labels: Messaggi a valore legale

#3623 chore(Messaggi a valore legale): [IAMVL-36] Fetch service if not present
  ts/features/mvl/screens/details/MvlDetailsScreen.tsx
Labels: Messaggi a valore legale

#3624 chore(Messaggi a valore legale): [IAMVL-44] Activate FF and comment Android release out
  .circleci/config.yml
  .env.production
Labels: Messaggi a valore legale

#3626 chore(Messaggi a valore legale): [IAMVL-44] Activate FF and comment Android release out"
  .circleci/config.yml
  .env.production
Labels: Messaggi a valore legale

#3597 fix(Carta Giovani Nazionale): [IOACGN-6] Fix blocking error when merchants search API responds with errors
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
Labels: Carta Giovani Nazionale

#3629 chore: [IA-480] Handle back on Paypal onboarding
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/features/wallet/onboarding/paypal/screen/PayPalOnboardingCheckoutScreen.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalOnboardingCheckoutScreen.test.tsx
Labels: paypal
