Repository pagopa/io-app, pull requests merged in 2021-05, with the labels that each got.

#3013 feat(Bonus Pagamenti Digitali): [#175741773] Update Mastercard circuit to "Mastercard / Maestro" for cashback transaction detail
  ts/features/bonus/bpd/components/transactionItem/__test__/BdpTransactionItem.test.tsx
  ts/features/bonus/bpd/saga/networking/transactions.ts
  ts/features/bonus/bpd/screens/details/transaction/detail/__test__/BdpTransactionDetailComponent.test.tsx
  ts/features/bonus/bpd/store/actions/transactions.ts
Labels: Bonus Pagamenti Digitali

#3002 chore(Carta Giovani Nazionale): [#177367462] Implements tests on Eyca Activation worker
  ts/__mocks__/react-native-background-timer.ts
  ts/features/bonus/cgn/saga/__tests__/orchestration/eyca/activation/eycaActivationSaga.test.ts
  ts/features/bonus/cgn/saga/orchestration/eyca/eycaActivationSaga.ts
Labels: Carta Giovani Nazionale

#2995 feat(Bonus Pagamenti Digitali): [#177544049,#177852497] Added paginated loading for cashback transactions
  locales/en/index.yml
  locales/it/index.yml
  ts/components/error/WorkunitGenericFailure.tsx
  ts/features/bonus/bpd/components/BaseDailyTransactionHeader.tsx
  ts/features/bonus/bpd/components/transactionItem/BaseBpdTransactionItem.tsx
  ts/features/bonus/bpd/navigation/navigator.ts
  ts/features/bonus/bpd/saga/index.ts
  ts/features/bonus/bpd/saga/networking/loadBpdData.ts
  ts/features/bonus/bpd/saga/networking/ranking.ts
  ts/features/bonus/bpd/saga/networking/transactions.ts
  ts/features/bonus/bpd/saga/networking/winning-transactions/loadTransactionsRequiredData.ts
  ts/features/bonus/bpd/saga/networking/winning-transactions/transactionsPage.ts
  ts/features/bonus/bpd/screens/details/transaction/BpdAvailableTransactionsScreen.tsx
  ts/features/bonus/bpd/screens/details/transaction/BpdEmptyTransactionsList.tsx
  ts/features/bonus/bpd/screens/details/transaction/BpdTransactionsScreen.tsx
  ts/features/bonus/bpd/screens/details/transaction/TransactionsUnavailable.tsx
  ts/features/bonus/bpd/screens/details/transaction/__test__/BpdTransactionsScreen.test.tsx
  ts/features/bonus/bpd/screens/details/transaction/detail/BpdTransactionDetailComponent.tsx
  ts/features/bonus/bpd/screens/details/transaction/v2/BpdAvailableTransactionsScreenV2.tsx
  ts/features/bonus/bpd/screens/details/transaction/v2/BpdTransactionsRouterScreen.tsx
  ts/features/bonus/bpd/screens/details/transaction/v2/TransactionsSectionList.tsx
  ts/features/bonus/bpd/screens/details/transaction/v2/TransactionsUnavailableV2.tsx
  ts/features/bonus/bpd/screens/details/transaction/v2/__test__/BpdTransactionsRouterScreen.test.tsx
  ts/features/bonus/bpd/screens/details/transaction/v2/__test__/TransactionsSectionList.test.tsx
  ts/features/bonus/bpd/store/actions/transactions.ts
  ts/features/bonus/bpd/store/reducers/details/combiner.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/__test__/transactions.test.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/daysInfo.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/entities.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/ui.ts
  ts/store/reducers/backoffError.ts
Labels: Bonus Pagamenti Digitali

#3010 feat(Bonus Pagamenti Digitali): [#177965778] Change "last valid transition" to "last update" in transactions screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/bpd/screens/details/transaction/v2/TransactionsSectionList.tsx
Labels: Bonus Pagamenti Digitali

#3018 feat(Bonus Pagamenti Digitali): [#176997427] Added V-PAY logo
  ts/components/wallet/card/Logo.tsx
  ts/features/wallet/component/card/CardLogoPreview.tsx
Labels: Bonus Pagamenti Digitali

#3012 feat(Bonus Pagamenti Digitali): [#177544138] Add mixpanel tracking for paginated transaction
  ts/features/bonus/bpd/analytics/index.ts
  ts/features/bonus/bpd/saga/networking/winning-transactions/countByDay.ts
  ts/features/bonus/bpd/saga/networking/winning-transactions/transactionsPage.ts
  ts/features/bonus/bpd/screens/details/transaction/v2/BpdTransactionsRouterScreen.tsx
Labels: Bonus Pagamenti Digitali

#3024 feat(Carta Giovani Nazionale): [#178020445] Implements Tabs for CGN merchant list to show online and places merchants
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
  ts/features/bonus/cgn/navigation/actions.ts
  ts/features/bonus/cgn/navigation/navigator.ts
  ts/features/bonus/cgn/navigation/routes.ts
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsTabsScreen.tsx
  ts/store/reducers/__mock__/backendStatus.ts
  ts/types/backendStatus.ts
Labels: Carta Giovani Nazionale

#3030 fix(Payments): [#176919872] Dismiss keyboard on create credit card
  ts/screens/wallet/AddCardScreen.tsx
Labels: Payments

#3034 feat(Bonus Pagamenti Digitali): [#176801780] Avoid Android hardware go back on add payment method
  ts/features/wallet/onboarding/bancomat/screens/searchBancomat/SearchAvailableUserBancomatScreen.tsx
  ts/features/wallet/onboarding/bancomatPay/screens/searchBPay/SearchAvailableUserBPayScreen.tsx
  ts/features/wallet/onboarding/cobadge/screens/search/SearchAvailableCoBadgeScreen.tsx
  ts/features/wallet/onboarding/satispay/screens/search/SearchSatispayManagerScreen.tsx
  ts/utils/avoidHardwareBackButton.ts
Labels: Bonus Pagamenti Digitali

#3050 chore(Bonus Pagamenti Digitali): [IAC-62] Add changelog scope for cashback jira project
  scripts/ts/danger/utils/changelog.ts
Labels: Bonus Pagamenti Digitali

#3049 fix(Bonus Pagamenti Digitali): [IAC-57] Privative displayed as incoming when adding a new payment method during a payment
  ts/screens/wallet/AddPaymentMethodScreen.tsx
Labels: Bonus Pagamenti Digitali

#3055 chore(Bonus Pagamenti Digitali): [IAC-64] Disable paginated transaction feature flag
  .env.production
Labels: Bonus Pagamenti Digitali

#3056 chore(Sicilia Vola): [IASV-1] Add Sicilia Vola Id for title generation and changelog
  scripts/ts/danger/utils/changelog.ts
Labels: Sicilia Vola

#3061 fix(Bonus Pagamenti Digitali): [IAC-66] Wrong normalization of cashback amount when the pivot transaction is in a different day but in the same page
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/__test__/normalization.test.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/entities.ts
Labels: Bonus Pagamenti Digitali

#3063 chore(Bonus Pagamenti Digitali): [IAC-70] Write-off copy update
  locales/en/index.yml
  locales/it/index.yml
Labels: Bonus Pagamenti Digitali

#3033 feat(Carta Giovani Nazionale): [#178020526] Implements components to filter on merchants search
  CHANGELOG.md
  android/app/src/main/assets/fonts/io-icon-font.ttf
  android/link-assets-manifest.json
  assets/fonts/io-icon-font/io-icon-font.ttf
  ios/Podfile.lock
  ios/link-assets-manifest.json
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/core/typography/H5.tsx
  ts/components/core/variables/IOColors.ts
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/BaseScreenComponent.tsx
  ts/components/screens/TopScreenComponent.tsx
  ts/components/search/SearchButton.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsFilters.tsx
  ts/features/bonus/cgn/components/merchants/search/CategoryCheckbox.tsx
  ts/features/bonus/cgn/components/merchants/search/DistanceSlider.tsx
  ts/features/bonus/cgn/components/merchants/search/OrderOption.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsTabsScreen.tsx
  ts/features/bonus/cgn/utils/filters.ts
  ts/screens/messages/MessagesHomeScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
  ts/store/reducers/wallet/creditCard.ts
  ts/theme/font-icons/io-icon-font/selection.json
  ts/utils/SessionManager.ts
  yarn.lock
Labels: Carta Giovani Nazionale

#3066 chore(Green Pass): [IAGP-1] Add "Green Pass" to changelog scope
  scripts/ts/danger/utils/changelog.ts
Labels: Green Pass

#3071 chore(EU Covid Certificate): [IAGP-4] Add EU covid certificate feature flag
  .env.example
  .env.local
  .env.production
  README.md
  scripts/ts/danger/utils/changelog.ts
  ts/config.ts
Labels: EU Covid Certificate

#3073 feat(EU Covid Certificate): [IAGP-36] Add euCovidCert as new section status
  scripts/ts/common/ticket/jira/types.ts
  scripts/ts/common/ticket/types.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/types/backendStatus.ts
Labels: EU Covid Certificate

#3042 chore(Carta Giovani Nazionale): [#178127305] Adds Department name and Eyca Logo on card component
  img/bonus/cgn/eyca_logo.png
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/detail/CardSvgPayload.ts
  ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx
  ts/features/bonus/cgn/components/detail/DepartmentLabel.tsx
  ts/features/bonus/cgn/components/detail/__test__/CgnCardComponent.test.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/utils/eyca.ts
Labels: Carta Giovani Nazionale
