Repository pagopa/io-app, pull requests merged in 2021-04, with the labels that each got.

#2956 fix(Carta Giovani Nazionale): [#177490914] Discount bottom sheet title doesn't break line
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
Labels: Carta Giovani Nazionale

#2957 fix(Carta Giovani Nazionale): [#177485208] Hardware back button doesn't work on CGN Detail screen
  ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
Labels: Carta Giovani Nazionale

#2958 feat(Payments): [#177548187] Add credit card / payment webview closing reason
  ts/components/wallet/PayWebViewModal.tsx
  ts/store/reducers/payments/history.ts
  ts/store/reducers/wallet/creditCard.ts
  ts/utils/payment.ts
Labels: Payments

#2961 chore(Bonus Pagamenti Digitali): [#177542266] Add technical iban feature flag
  .env.example
  .env.local
  .env.production
  ts/config.ts
Labels: Bonus Pagamenti Digitali

#2952 feat(Bonus Pagamenti Digitali): [#176925463] Tracks action to notify the possibility to add a co-badge to the user
  ts/features/wallet/onboarding/cobadge/analytics/index.ts
  ts/sagas/wallet.ts
  ts/sagas/wallet/__tests__/cobadgeRemainder.test.ts
  ts/sagas/wallet/cobadgeReminder.ts
  ts/screens/wallet/WalletHomeScreen.tsx
  ts/store/actions/wallet/wallets.ts
Labels: Bonus Pagamenti Digitali

#2940 feat(Bonus Pagamenti Digitali): [#176781159] Manage error and loading state for the abi list when start co-badge onboarding workflow
  ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
  ts/features/wallet/onboarding/cobadge/saga/orchestration/addCoBadgeToWallet.ts
  ts/features/wallet/onboarding/cobadge/screens/start/CoBadgeChosenBankScreen.tsx
  ts/features/wallet/onboarding/cobadge/screens/start/__test__/CoBadgeStartScreen.test.tsx
  ts/features/wallet/onboarding/common/searchBank/SearchStartComponent.tsx
  ts/features/wallet/onboarding/common/searchBank/SearchStartScreen.tsx
Labels: Bonus Pagamenti Digitali

#2948 chore: [#177560562] Close NFC dialog when card is successfully read
  package.json
  yarn.lock
Labels: ios

#2960 feat(Carta Giovani Nazionale): [#177458070] Bonuses Available list now follows the same logic of bonuses in carousel
  ts/features/bonus/bonusVacanze/screens/AvailableBonusScreen.tsx
  ts/features/bonus/bonusVacanze/store/reducers/availableBonusesTypes.ts
Labels: Carta Giovani Nazionale

#2968 feat(Bonus Pagamenti Digitali): [#177542335,#177543882] Add code generation for citizen and winning_transaction v2 api
  package.json
Labels: Bonus Pagamenti Digitali

#2955 fix(Carta Giovani Nazionale): [#177481627] In case of EYCA Activation status is in final status activation doesn't start
  ts/features/bonus/cgn/saga/networking/eyca/activation/getEycaActivationSaga.ts
  ts/features/bonus/cgn/saga/orchestration/eyca/eycaActivationSaga.ts
  ts/features/bonus/cgn/screens/eyca/activation/EycaActivationLoading.tsx
Labels: Carta Giovani Nazionale

#2970 chore(Carta Giovani Nazionale): [#177441837,#177322409] Implements Unit tests on EycaDetailComponent and CgnCardComponent
  ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx
  ts/features/bonus/cgn/components/detail/__test__/CgnCardComponent.test.tsx
  ts/features/bonus/cgn/components/detail/__test__/CgnStatusDetail.test.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaErrorComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaPendingComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaStatusDetailsComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/__test__/EycaDetailComponent.test.tsx
Labels: Carta Giovani Nazionale

#2969 feat(Bonus Pagamenti Digitali): [#177542335] Citizen v2 api integration
  ts/features/bonus/bpd/api/backendBpdClient.ts
  ts/features/bonus/bpd/api/patchedTypes.ts
  ts/features/bonus/bpd/saga/index.ts
  ts/features/bonus/bpd/saga/networking/index.ts
  ts/features/bonus/bpd/store/actions/details.ts
  ts/features/bonus/bpd/store/reducers/details/activation/index.ts
  ts/features/bonus/bpd/store/reducers/details/activation/technicalAccount.ts
Labels: Bonus Pagamenti Digitali

#2974 feat(Bonus Pagamenti Digitali): [#177542840] Show technical IBAN information
  ts/features/bonus/bpd/screens/details/components/iban/BaseIbanInformationComponent.tsx
  ts/features/bonus/bpd/screens/details/components/iban/IbanInformationComponent.tsx
  ts/features/bonus/bpd/store/reducers/details/activation/technicalAccount.ts
Labels: Bonus Pagamenti Digitali

#2972 feat(Bonus Pagamenti Digitali): [#177740790] Actions & store definiton for paginated transactions
  ts/features/bonus/bpd/store/actions/transactions.ts
  ts/features/bonus/bpd/store/reducers/details/index.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/__mock__/transactions.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/__test__/normalization.test.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/__test__/transactions.test.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/daysInfo.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/entities.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/index.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/ui.ts
Labels: Bonus Pagamenti Digitali

#2978 feat(Bonus Pagamenti Digitali): [#177542720] Add technical iban information to mixpanel
  ts/features/bonus/bpd/analytics/index.ts
Labels: Bonus Pagamenti Digitali

#2977 feat(Bonus Pagamenti Digitali): [#177543245] Manage pre-compiled IBAN in technical IBAN case
  ts/features/bonus/bpd/store/reducers/details/activation/index.ts
Labels: Bonus Pagamenti Digitali

#2992 fix(Carta Giovani Nazionale): [#177777595] Accessibility improvements on CGN screens and bottomsheets
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/detail/eyca/EycaInformationComponent.tsx
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/components/otp/OtpCodeComponent.tsx
  ts/features/bonus/cgn/components/otp/OtpNotWorking.tsx
  ts/features/bonus/cgn/screens/CgnOtpScreen.tsx
Labels: Carta Giovani Nazionale

#2983 feat(Bonus Pagamenti Digitali): [#177543882] Add paginated transactions networking logic
  ts/features/bonus/bpd/api/award-period/v1.ts
  ts/features/bonus/bpd/api/backendBpdClient.ts
  ts/features/bonus/bpd/api/citizen/v1.ts
  ts/features/bonus/bpd/api/citizen/v2.ts
  ts/features/bonus/bpd/api/common.ts
  ts/features/bonus/bpd/api/payment-instrument/v1.ts
  ts/features/bonus/bpd/api/winning-transactions/patchedWinningTransactionPageResource.ts
  ts/features/bonus/bpd/api/winning-transactions/v1.ts
  ts/features/bonus/bpd/api/winning-transactions/v2.ts
  ts/features/bonus/bpd/saga/index.ts
  ts/features/bonus/bpd/saga/networking/__test__/loadPeriodsAmount.test.ts
  ts/features/bonus/bpd/saga/networking/loadPeriodsWithInfo.ts
  ts/features/bonus/bpd/saga/networking/ranking.ts
  ts/features/bonus/bpd/saga/networking/transactions.ts
  ts/features/bonus/bpd/saga/networking/winning-transactions/countByDay.ts
  ts/features/bonus/bpd/saga/networking/winning-transactions/transactionsPage.ts
  ts/features/bonus/bpd/store/actions/transactions.ts
  ts/features/bonus/bpd/store/reducers/details/periods.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/__test__/normalization.test.ts
  ts/features/bonus/bpd/store/reducers/details/transactionsv2/entities.ts
Labels: Bonus Pagamenti Digitali

#3003 chore(Bonus Pagamenti Digitali): [#176314517] Refactoring: backoff reducer
  ts/features/bonus/bpd/saga/networking/loadBpdData.ts
  ts/sagas/wallet.ts
  ts/store/reducers/__tests__/backoffError.ts
  ts/store/reducers/backoffError.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
  ts/store/reducers/wallet/index.ts
  ts/utils/backoffError.ts
  ts/utils/saga.ts
Labels: Bonus Pagamenti Digitali
