Repository pagopa/io-app, pull requests merged in 2021-02, with the labels that each got.

#2754 chore: [#176614756] Use @pagopa packages from npm registry
  .npmrc
  README.md
  package.json
  yarn.lock
Labels: to-be-tested

#2833 feat: [#176980827] Don't allow user to add a credit card when insert a cardholder with accented characters
  locales/en/index.yml
  locales/it/index.yml
  ts/components/LabelledItem.tsx
  ts/components/core/typography/H5.tsx
  ts/screens/wallet/AddCardScreen.tsx
  ts/screens/wallet/__tests__/AddCardScreen.test.tsx
  ts/utils/__tests__/input.test.ts
  ts/utils/input.ts
Labels: 3DS2

#2832 feat: [#176983293] Add a WebView component to support payments 3DS2
  ts/components/wallet/PayWebViewModal.tsx
  ts/components/wallet/__test__/PayWebViewModal.test.tsx
  ts/screens/modal/Checkout3DsModal.tsx
Labels: 3DS2

#2842 feat: [#176981284,#176981509] Show the webview outcome message for the add credit card or payment operation
  img/pictograms/payment-completed-2x.png
  img/pictograms/payment-completed.png
  img/pictograms/payment-completed.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/components/SectionStatusComponent.tsx
  ts/components/wallet/OutcomeCodeMessageComponent.tsx
  ts/components/wallet/PaymentMethodsList.tsx
  ts/navigation/WalletNavigator.ts
  ts/navigation/routes.ts
  ts/screens/wallet/AddCreditCardOutcomeCodeMessage.tsx
  ts/screens/wallet/payment/PaymentOutcomeCodeMessage.tsx
  ts/store/actions/navigation.ts
  ts/store/actions/types.ts
  ts/store/actions/wallet/outcomeCode.ts
  ts/store/reducers/wallet/index.ts
  ts/store/reducers/wallet/outcomeCode.ts
  ts/types/outcomeCode.ts
  ts/utils/locale.ts
Labels: 3DS2

#2837 feat: [#176981421,#176983158] Make payment compliant with 3DS2
  locales/en/index.yml
  locales/it/index.yml
  ts/api/pagopa.ts
  ts/components/wallet/PayWebViewModal.tsx
  ts/sagas/wallet.ts
  ts/sagas/wallet/__tests__/pagopaApisPaymentStartRequest.test.ts
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
  ts/store/actions/wallet/payment.ts
  ts/store/actions/wallet/transactions.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/wallet/payment.ts
Labels: 3DS2

#2831 feat: [#176981563] Update MAESTRO from arriving payment method to valid payment method
  ts/features/wallet/component/__test__/PagoPaPaymentCapability.test.tsx
  ts/utils/__tests__/paymentMethodCapabilities.test.ts
  ts/utils/paymentMethodCapabilities.ts
Labels: 3DS2, on-hold :raised_hand:

#2845 feat: [#177066306] Handle and show details about payment outcome
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/PaymentOutcomeCodeMessage.tsx
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
  ts/store/actions/wallet/payment.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/entities/payments.ts
  ts/store/reducers/wallet/outcomeCode.ts
  ts/types/outcomeCode.ts
  ts/utils/payment.ts
Labels: 3DS2

#2846 chore: [#176983007] Restore payment attempt saving
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/wallet/PaymentHistoryDetailsScreen.tsx
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/store/actions/wallet/payment.ts
  ts/store/reducers/__tests__/paymentsHistory.test.ts
  ts/store/reducers/entities/payments.ts
  ts/store/reducers/payments/history.ts
  ts/store/reducers/wallet/outcomeCode.ts
  ts/utils/payment.ts
Labels: 3DS2

#2849 chore: [#177035521] Track new events about payment flow 3DS2
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/store/actions/wallet/payment.ts
  ts/store/middlewares/analytics.ts
Labels: 3DS2

#2848 chore: [#176981159,#177092221] Make credit card onboarding compliant with 3DS2 and track onboarding events
  locales/en/index.yml
  locales/it/index.yml
  ts/components/wallet/OutcomeCodeMessageComponent.tsx
  ts/components/wallet/PayWebViewModal.tsx
  ts/sagas/__tests__/wallet.test.ts
  ts/sagas/wallet.ts
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/modal/Checkout3DsModal.tsx
  ts/screens/wallet/AddCreditCardOutcomeCodeMessage.tsx
  ts/screens/wallet/ConfirmCardDetailsScreen.tsx
  ts/screens/wallet/__tests__/ConfirmCardDetailScreen.test.tsx
  ts/store/actions/wallet/wallets.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/wallet/creditCard.ts
  ts/store/reducers/wallet/payment.ts
  ts/store/reducers/wallet/wallets.ts
Labels: 3DS2
