Repository pagopa/io-app, pull requests merged in 2021-09, with the labels that each got.

#3313 fix(EU Covid Certificate): [IAGP-68] When the app changes the brighness to the max and the user close the app or changes the current active app, the device brightness always remains at maximum
  ts/components/__tests__/FiscalCodeLandscapeOverlay.test.tsx
  ts/utils/brightness.ts
Labels: EU Covid Certificate

#3344 chore: [IAI-25] Replaces biometric library to support more devices biometric options
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/it/pagopa/io/app/MainApplication.java
  android/settings.gradle
  ios/Podfile.lock
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  package.json
  patches/patches.md
  patches/react-native-touch-id+4.4.1.patch
  ts/@types/react-native-touch-id.d.ts
  ts/components/Pinpad/index.tsx
  ts/sagas/startup/checkAcknowledgedFingerprintSaga.ts
  ts/screens/modal/IdentificationModal.tsx
  ts/screens/onboarding/FingerprintScreen.tsx
  ts/screens/profile/SecurityScreen.tsx
  ts/utils/biometric.ts
  yarn.lock
Labels: dont-merge :raised_hand:

#3352 chore: [IAI-30] Remove unused dependencies
  package.json
  yarn.lock
Labels: dependencies

#3379 chore(Sicilia Vola): [IASV-44] Qr barcode component
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx
  ts/features/bonus/siciliaVola/components/VoucherInformationComponent.tsx
  ts/features/euCovidCert/screens/valid/EuCovidCertQrCodeFullScreen.tsx
  ts/features/euCovidCert/screens/valid/EuCovidCertValidScreen.tsx
  ts/utils/image.ts
Labels: Sicilia Vola

#3388 chore(Bonus Pagamenti Digitali): [IAC-114] Update BPD API endpoints
  .env.local
  .env.production
Labels: Bonus Pagamenti Digitali

#3361 feat(Sicilia Vola): [IASV-14,IASV-15] Voucher list screen with filters
  assets/SiciliaVola.yml
  img/bonus/siciliaVola/emptyVoucherList.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/siciliaVola/api/backendSiciliaVola.ts
  ts/features/bonus/siciliaVola/components/SvVoucherListFilters.tsx
  ts/features/bonus/siciliaVola/navigation/navigator.ts
  ts/features/bonus/siciliaVola/saga/index.ts
  ts/features/bonus/siciliaVola/saga/networking/handleGetVoucherBeneficiario.ts
  ts/features/bonus/siciliaVola/saga/networking/handleGetVoucherStati.ts
  ts/features/bonus/siciliaVola/screens/VoucherListScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/SelectBeneficiaryCategoryScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/SickCheckIncomeScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/SickSelectDestinationScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/StudentSelectDestinationScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/WorkerCheckIncomeScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherGeneration/WorkerSelectDestinationScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherList/VoucherListScreen.tsx
  ts/features/bonus/siciliaVola/store/actions/voucherList.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/voucherList.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/voucherRequest.test.ts
  ts/features/bonus/siciliaVola/store/reducers/__test__/vouchers.test.ts
  ts/features/bonus/siciliaVola/store/reducers/index.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration/availableDestinations.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration/availableMunicipalities.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration/availableProvinces.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration/availableRegions.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration/availableStates.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration/voucherGenerated.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration/voucherGeneration.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherGeneration/voucherRequest.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherList.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherList/filters.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherList/possibleVoucherState.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherList/ui.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherList/voucherList.ts
  ts/features/bonus/siciliaVola/store/reducers/voucherList/vouchers.ts
  ts/navigation/ServicesNavigator.ts
  ts/store/reducers/backoffError.ts
Labels: Sicilia Vola

#3400 feat(Sicilia Vola): [IASV-42,IASV-43] Voucher details screen
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ui/BlockButtons.tsx
  ts/components/ui/Markdown/handlers/internalLink.ts
  ts/features/bonus/siciliaVola/components/VoucherDetailBottomsheet.tsx
  ts/features/bonus/siciliaVola/navigation/actions.ts
  ts/features/bonus/siciliaVola/navigation/navigator.ts
  ts/features/bonus/siciliaVola/navigation/routes.ts
  ts/features/bonus/siciliaVola/saga/networking/handleGetDettaglioVoucher.ts
  ts/features/bonus/siciliaVola/screens/voucherList/VoucherDetailsScreen.tsx
  ts/features/bonus/siciliaVola/screens/voucherList/VoucherListScreen.tsx
  ts/features/bonus/siciliaVola/store/actions/voucherList.ts
  ts/features/bonus/siciliaVola/store/reducers/selectedVoucher.ts
  ts/features/bonus/siciliaVola/types/SvVoucher.ts
  ts/features/bonus/siciliaVola/utils.ts
  ts/navigation/ServicesNavigator.ts
Labels: Sicilia Vola
