Repository pagopa/io-app, pull requests merged in 2022-06, with the labels that each got.

#3991 chore(Carta Giovani Nazionale): [IOACGN-73] Adds event tracing for CGN
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/components/merchants/__test__/CgnDiscountDetail.test.tsx
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnOTPCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnStaticCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/__test__/CgnDiscountCodeComponent.test.tsx
  ts/features/bonus/cgn/hooks/useCgnDiscountDetailBottomSheet.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
  ts/features/bonus/cgn/utils/__test__/dates.test.ts
  ts/features/bonus/cgn/utils/dates.ts
Labels: Carta Giovani Nazionale, legal-approved ⚖️ ✅

#3994 chore(Carta della cultura): [AP-38] Restore swipe back for cdc navigator
  ts/features/bonus/cdc/navigation/CdcStackNavigator.tsx
Labels: Carta della cultura

#4003 fix(Carta Giovani Nazionale): [IOACGN-75] Fixes discount code not showing on discount detail
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
Labels: Carta Giovani Nazionale

#3985 chore(Carta della cultura): [AP-37] Update outcome message on CDC partially success screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cdc/components/CdcRequestPartiallySuccess.tsx
  ts/features/bonus/cdc/components/__test__/CdcRequestPartiallySuccess.test.ts
Labels: Carta della cultura

#4013 chore(Carta Giovani Nazionale): [IOACGN-78] Fixes landing page to open automatically media playback
  ts/components/WebviewComponent.tsx
  ts/components/__tests__/__snapshots__/WebviewComponent.test.tsx.snap
Labels: Carta Giovani Nazionale

#4025 chore: [IA-855] Remove the Premium Messages Opt-In/Out placeholder screens
  ts/navigation/OnboardingNavigator.ts
  ts/navigation/ProfileNavigator.ts
  ts/navigation/params/OnboardingParamsList.ts
  ts/navigation/routes.ts
  ts/sagas/__tests__/premiumMessages.test.ts
  ts/sagas/premiumMessages.ts
  ts/sagas/startup.ts
  ts/screens/onboarding/premiumMessages/PremiumMessagesOptInOutScreen.tsx
  ts/screens/profile/PrivacyMainScreen.tsx
  ts/screens/profile/premiumMessages/PremiumMessagesOptInOutProfileScreen.tsx
Labels: Messaggi Premium Opt-In/Out

#4012 chore(Carta Giovani Nazionale): [IOACGN-77] Support the direct linking to CGN categories list and category merchant list screen
  ts/features/bonus/cgn/navigation/navigator.ts
  ts/features/bonus/cgn/navigation/params.ts
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
Labels: Carta Giovani Nazionale
