Repository pagopa/io-app, pull requests merged in 2022-07, with the labels that each got.

#4024 chore: [IA-875] Latest app version upsert
  package.json
  ts/sagas/__tests__/profile.test.ts
  ts/sagas/profile.ts
  ts/sagas/startup.ts
Labels: Messaggi Premium Opt-In/Out

#4010 feat(Piattaforma Notifiche): [IAMVL-77] Show an icon in messages list to identify a message from PN
  package.json
  ts/components/messages/paginated/MessageList/Item.tsx
  ts/components/messages/paginated/MessageList/__tests__/Item.test.tsx
  ts/components/messages/paginated/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
Labels: Piattaforma Notifiche

#4032 chore: [IA-905] Enable the local feature flag for the Premium Messages Opt-out
  .env.local
  .env.production
Labels: Messaggi Premium Opt-In/Out

#4033 feat(Piattaforma Notifiche): [IAMVL-78] Show a disclaimer to the user before opening a message from PN
  locales/en/index.yml
  locales/en/pn/message_open_warning.html
  locales/it/index.yml
  locales/it/pn/message_open_warning.html
  ts/components/messages/paginated/MessageList/Item.tsx
  ts/components/messages/paginated/hooks/useMessageOpening.tsx
  ts/features/pn/components/PnOpenConfirmationBottomSheet.tsx
  ts/screens/messages/paginated/MessagesHomeScreen.tsx
  ts/screens/messages/paginated/__tests__/MessagesHomeScreen.test.tsx
Labels: Piattaforma Notifiche

#4048 chore: [IA-906] Update `tosVersion` to `4.0`
  ts/config.ts
Labels: Messaggi Premium Opt-In/Out

#4036 feat(Piattaforma Notifiche): [IAMVL-81] Let the user disable the disclaimer before opening a message from PN
  ts/components/messages/paginated/MessagesInbox.tsx
  ts/components/messages/paginated/hooks/useMessageOpening.tsx
  ts/features/common/store/reducers/index.ts
  ts/features/pn/components/PnOpenConfirmationBottomSheet.tsx
  ts/features/pn/index.ts
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/reducers/__test__/preferences.test.ts
  ts/features/pn/store/reducers/index.ts
  ts/features/pn/store/reducers/preferences.ts
  ts/screens/messages/paginated/MessagesHomeScreen.tsx
  ts/screens/messages/paginated/__tests__/MessagesHomeScreen.test.tsx
  ts/store/actions/types.ts
Labels: Piattaforma Notifiche

#4054 fix(Carta Giovani Nazionale): [IOACGN-81] Fixes userAgeRange calculus
  ts/features/bonus/cgn/utils/__test__/dates.test.ts
  ts/features/bonus/cgn/utils/dates.ts
Labels: Carta Giovani Nazionale

#4043 feat(Piattaforma Notifiche): [IAMVL-79] Fetch and show PN message details
  locales/en/index.yml
  locales/it/index.yml
  ts/api/backend.ts
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/features/messages/components/MessageLoading.tsx
  ts/features/messages/store/actions/index.ts
  ts/features/mvl/screens/MvlLoadingScreen.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessageDetailsContent.tsx
  ts/features/pn/components/PnMessageDetailsError.tsx
  ts/features/pn/components/PnMessageDetailsHeader.tsx
  ts/features/pn/components/PnMessageDetailsSection.tsx
  ts/features/pn/navigation/actions.ts
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/navigation/params.ts
  ts/features/pn/navigation/routes.ts
  ts/features/pn/screens/PnMessageDetailsScreen.tsx
  ts/features/pn/store/reducers/index.ts
  ts/features/pn/store/types/transformers.ts
  ts/features/pn/store/types/types.ts
  ts/navigation/MessagesNavigator.tsx
  ts/navigation/params/MessagesParamsList.ts
  ts/sagas/messages/watchThirdPartyMessageSaga.ts
  ts/sagas/startup.ts
  ts/screens/messages/paginated/MessageRouterScreen.tsx
  ts/screens/wallet/payment/NewTransactionSummaryScreen.tsx
  ts/screens/wallet/payment/components/TransactionSummary.tsx
  ts/screens/wallet/payment/components/TransactionSummaryErrorDetails.tsx
  ts/store/actions/messages.ts
  ts/store/reducers/entities/messages/index.ts
  ts/store/reducers/entities/messages/thirdPartyById.ts
Labels: Piattaforma Notifiche

#4064 fix(Carta Giovani Nazionale): [IOACGN-82] Shows merchants CTA only for card Activated
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
Labels: Carta Giovani Nazionale

#4047 feat(Piattaforma Notifiche): [IAMVL-82] Handle attachments from PN message
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/MessageAttachmentPreview.tsx
  ts/features/messages/saga/attachments.ts
  ts/features/mvl/saga/index.ts
  ts/features/mvl/screens/details/MvlDetailsScreen.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachmentDownload.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachmentPreview.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachments.tsx
  ts/features/mvl/screens/details/components/attachment/__test__/MvlAttachments.test.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/navigation/params.ts
  ts/features/pn/navigation/routes.ts
  ts/features/pn/screens/PnAttachmentPreview.tsx
  ts/features/pn/store/types/transformers.ts
  ts/features/pn/store/types/types.ts
  ts/sagas/startup.ts
Labels: Piattaforma Notifiche

#4066 feat: [IIP-83] Prevent user from disabling the warning when opening a PN message
  ts/components/messages/paginated/hooks/useMessageOpening.tsx
  ts/features/pn/components/PnOpenConfirmationBottomSheet.tsx
  ts/screens/messages/paginated/__tests__/MessagesHomeScreen.test.tsx
Labels: Piattaforma Notifiche

#4061 feat(Piattaforma Notifiche): [IAMVL-83] Show the timeline in a PN message
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessageDetailsSection.tsx
  ts/features/pn/components/PnMessageTimeline.tsx
  ts/features/pn/store/types/types.ts
  ts/features/pn/utils/dates.ts
  ts/features/pn/utils/index.ts
Labels: Piattaforma Notifiche

#4069 feat(Piattaforma Notifiche): [IAMVL-84] Add support for PN custom activation flow
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/features/pn/api/backendPn.ts
  ts/features/pn/components/PnServiceCTA.tsx
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/actions/service.ts
  ts/features/pn/store/reducers/activation.ts
  ts/features/pn/store/reducers/index.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/sagas/startup.ts
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/persistedPreferences.ts
Labels: Piattaforma Notifiche

#4070 feat(Piattaforma Notifiche): [IAMVL-85] Add an internal link for activating PN from a CTA
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/features/bonus/bonusVacanze/screens/AvailableBonusScreen.tsx
  ts/features/pn/components/PnServiceCTA.tsx
  ts/features/wallet/component/card/FeaturedCardCarousel.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/screens/messages/MessageDetailScreen/index.tsx
  ts/screens/messages/paginated/MessageDetailScreen.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
  ts/screens/services/__tests__/ServiceDetailsScreen.test.tsx
Labels: Piattaforma Notifiche

#4072 chore(Piattaforma Notifiche): [IAMVL-87] Enable the feature flag for PN
  .env.production
Labels: Piattaforma Notifiche

#4079 chore(Piattaforma Notifiche): [IAMVL-93] Update type for parse third party data from PN
  ts/features/pn/store/types/types.ts
Labels: Piattaforma Notifiche

#4078 fix(Piattaforma Notifiche): [IAMVL-92] PN message details is blank if abstract is empty
  ts/features/pn/components/PnMessageDetailsContent.tsx
Labels: Piattaforma Notifiche

#4086 chore(Piattaforma Notifiche): [IAMVL-88] Update copy of the PN message opening alert
  img/features/pn/pn_alert_header.svg
  img/features/pn/pn_message_badge.svg
  locales/en/pn/message_open_warning.html
  locales/it/pn/message_open_warning.html
  ts/components/messages/paginated/MessageList/Item.tsx
  ts/features/pn/components/PnOpenConfirmationBottomSheet.tsx
Labels: Piattaforma Notifiche

#4046 chore: [IA-907] Improved manual configuration disclaimer
  locales/en/index.yml
  locales/it/index.yml
Labels: legal-approved ⚖️ ✅

#4083 chore(Piattaforma Notifiche): [IAMVL-90] Use PN remote config
  package.json
  ts/components/messages/paginated/hooks/useMessageOpening.tsx
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/navigation/MessagesNavigator.tsx
  ts/screens/messages/paginated/MessageRouterScreen.tsx
  ts/screens/messages/paginated/__tests__/MessagesHomeScreen.test.tsx
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: Piattaforma Notifiche

#4085 fix(Piattaforma Notifiche): [IAMVL-95] Fix PN service activation from CTA in message
  ts/navigation/AppStackNavigator.tsx
Labels: Piattaforma Notifiche

#4090 chore(Piattaforma Notifiche): [IAMVL-96] Disable PN feature flag
  .env.production
Labels: Piattaforma Notifiche
