Repository pagopa/io-app, pull requests merged in 2022-01, with the labels that each got.

#3497 chore(Redesign Servizi): [IARS-45] Disables contact switch on special services
  ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx
  ts/components/services/ContactPreferencesToggles/index.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
Labels: Redesign Servizi

#3635 chore(Carta Giovani Nazionale): [IOACGN-13] Implements action/reducer/saga for code from bucket consuption
  ts/features/bonus/cgn/saga/index.ts
  ts/features/bonus/cgn/saga/networking/bucket/index.ts
  ts/features/bonus/cgn/store/actions/bucket.ts
  ts/features/bonus/cgn/store/actions/index.ts
  ts/features/bonus/cgn/store/reducers/bucket.ts
  ts/features/bonus/cgn/store/reducers/index.ts
Labels: Carta Giovani Nazionale

#3594 chore(Carta Giovani Nazionale): [IOACGN-2] Moves OTP Generation inside the discount bottomsheet
  img/icons/Eye.svg
  ts/features/bonus/cgn/__mock__/discount.ts
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/components/merchants/__test__/CgnDiscountDetail.test.tsx
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnOTPCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnStaticCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/__test__/CgnDiscountCodeComponent.test.tsx
  ts/features/bonus/cgn/components/merchants/discount/__test__/__snapshots__/CgnDiscountCodeComponent.test.tsx.snap
  ts/features/bonus/cgn/components/otp/OtpCodeComponent.tsx
  ts/features/bonus/cgn/hooks/useCgnDiscountDetailBottomSheet.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
  ts/features/bonus/cgn/store/actions/otp.ts
  ts/features/bonus/cgn/store/reducers/merchants.ts
  ts/features/bonus/cgn/store/reducers/otp.ts
Labels: Carta Giovani Nazionale

#3641 chore(Carta Giovani Nazionale): [IOACGN-14] Implements component to display a code from a bucket for
  ts/features/bonus/cgn/components/merchants/__test__/CgnDiscountDetail.test.tsx
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountCodeComponent.tsx
Labels: Carta Giovani Nazionale

#3634 feat: [IA-612] Activate Paypal from remote feature flag
  .env.local
  .env.production
  package.json
  ts/config.ts
  ts/features/wallet/component/card/WalletV2PreviewCards.tsx
  ts/features/wallet/onboarding/DigitalMethodsList.tsx
  ts/features/wallet/onboarding/paypal/analytics/index.ts
  ts/navigation/WalletNavigator.ts
  ts/sagas/wallet.ts
  ts/screens/wallet/AddPaymentMethodScreen.tsx
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: paypal

#3644 fix(Carta Giovani Nazionale): [IOACGN-16] Fixes cropped icons on android
  img/bonus/cgn/categories/sport.svg
  img/bonus/cgn/categories/telefonia.svg
  img/bonus/cgn/categories/theater.svg
  img/bonus/cgn/categories/travel.svg
  img/bonus/cgn/categories/wellness.svg
  img/icons/Eye.svg
Labels: Carta Giovani Nazionale

#3649 chore: [IA-627] Integrate Zendesk analytics
  ts/features/zendesk/components/ZendeskSupportComponent.tsx
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/features/zendesk/screens/ZendeskChooseCategory.tsx
  ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx
Labels: Zendesk

#3639 chore(Carta Giovani Nazionale): [IOACGN-7] Implements CGN Special Service CTA
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/ContactPreferencesToggles/index.tsx
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/features/bonus/cgn/components/CgnServiceCTA.tsx
  ts/features/bonus/cgn/saga/orchestration/activation/activationSaga.ts
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/activation/CgnActivationCompletedScreen.tsx
  ts/features/bonus/cgn/screens/activation/CgnCTAStartActivationScreen.tsx
  ts/navigation/AppNavigator.ts
  ts/navigation/WalletNavigator.ts
  ts/screens/services/ServiceDetailsScreen.tsx
Labels: Carta Giovani Nazionale

#3648 chore(Carta Giovani Nazionale): [IOACGN-17] Moves CGN FF on remote
  .env.local
  .env.production
  package.json
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/components/ui/Markdown/handlers/internalLink.ts
  ts/components/wallet/PaymentMethodsList.tsx
  ts/config.ts
  ts/features/bonus/bonusVacanze/screens/AvailableBonusScreen.tsx
  ts/features/bonus/bonusVacanze/store/reducers/availableBonusesTypes.ts
  ts/features/bonus/cgn/analytics/index.ts
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/activation/CgnCTAStartActivationScreen.tsx
  ts/features/wallet/component/card/FeaturedCardCarousel.tsx
  ts/navigation/AppNavigator.ts
  ts/sagas/contentLoaders.ts
  ts/sagas/startup.ts
  ts/screens/wallet/WalletHomeScreen.tsx
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: Carta Giovani Nazionale

#3651 chore(Carta Giovani Nazionale): [IOACGN-12] Introduces API to load a discount code from a bucket for cgn merchants
  package.json
  ts/features/bonus/cgn/__mock__/discount.ts
  ts/features/bonus/cgn/api/backendCgnMerchants.ts
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnOTPCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnStaticCodeComponent.tsx
  ts/features/bonus/cgn/saga/index.ts
  ts/features/bonus/cgn/saga/networking/bucket/index.ts
  ts/features/bonus/cgn/store/actions/bucket.ts
  ts/features/bonus/cgn/store/reducers/bucket.ts
Labels: Carta Giovani Nazionale

#3654 chore(Carta Giovani Nazionale): [IOACGN-21] Implements error handling on bucket code visualization
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
  ts/features/bonus/cgn/saga/networking/bucket/index.ts
  ts/features/bonus/cgn/store/actions/bucket.ts
  ts/features/bonus/cgn/store/reducers/bucket.ts
  ts/features/bonus/cgn/types/DiscountBucketCodeResponse.ts
Labels: Carta Giovani Nazionale

#3657 feat(EU Covid Certificate): [IAGP-69] Update revoked body text
  locales/en/index.yml
  locales/it/index.yml
Labels: EU Covid Certificate

#3664 chore(Carta Giovani Nazionale): [IOACGN-26] Updates CGN merchants API path
  ts/features/bonus/cgn/api/backendCgnMerchants.ts
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
Labels: Carta Giovani Nazionale

#3660 chore(Carta Giovani Nazionale): [IOACGN-18] Integrate tracking for missing CGN Actions
  ts/features/bonus/cgn/analytics/index.ts
Labels: Carta Giovani Nazionale, legal-compliance ⚖️

#3652 chore(Carta Giovani Nazionale): [IOACGN-22] Properly handles networking errors on UI
  ts/features/bonus/cgn/components/merchants/discount/CgnOTPCodeComponent.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
Labels: Carta Giovani Nazionale

#3659 chore(Carta Giovani Nazionale): [IOACGN-24] Implements UI component for CGN Buckets errors
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
Labels: Carta Giovani Nazionale

#3666 feat(EU Covid Certificate): [IAGP-70] Show certificate header_info in header component
  ts/features/euCovidCert/components/EuCovidCertHeader.tsx
  ts/features/euCovidCert/components/__test__/EuCovidCertHeader.test.tsx
  ts/features/euCovidCert/components/__test__/__snapshots__/EuCovidCertHeader.test.tsx.snap
  ts/features/euCovidCert/saga/networking/__tests__/handleGetEuCovidCertificate.test.ts
  ts/features/euCovidCert/saga/networking/handleGetEuCovidCertificate.ts
  ts/features/euCovidCert/screens/BaseEuCovidCertificateLayout.tsx
  ts/features/euCovidCert/screens/EuCovidCertExpiredScreen.tsx
  ts/features/euCovidCert/screens/EuCovidCertRevokedScreen.tsx
  ts/features/euCovidCert/screens/EuCovidCertificateRouterScreen.tsx
  ts/features/euCovidCert/screens/__test__/EUCovidCertExpiredScreen.test.tsx
  ts/features/euCovidCert/screens/__test__/EUCovidCertRevokedScreen.test.tsx
  ts/features/euCovidCert/screens/__test__/EUCovidCertValidScreen.test.tsx
  ts/features/euCovidCert/screens/valid/EuCovidCertValidScreen.tsx
  ts/features/euCovidCert/types/EUCovidCertificate.ts
  ts/features/euCovidCert/types/__mock__/EUCovidCertificate.mock.ts
Labels: EU Covid Certificate

#3663 chore(Messaggi a valore legale): [IAMVL-37] Hide html selector when no html is present in the body
  ts/features/mvl/screens/details/components/MvlBody.tsx
  ts/features/mvl/screens/details/components/__test__/MvlBody.test.tsx
Labels: Messaggi a valore legale

#3656 feat(Carta Giovani Nazionale): [IOACGN-9] Impelements CGN unsubscription flow
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/core/typography/Link.tsx
  ts/components/ui/Markdown/handlers/internalLink.ts
  ts/features/bonus/cgn/analytics/index.ts
  ts/features/bonus/cgn/api/backendCgn.ts
  ts/features/bonus/cgn/components/CgnServiceCTA.tsx
  ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx
  ts/features/bonus/cgn/components/detail/CgnUnsubscribe.tsx
  ts/features/bonus/cgn/saga/index.ts
  ts/features/bonus/cgn/saga/networking/unsubscribe/index.ts
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/store/actions/index.ts
  ts/features/bonus/cgn/store/actions/unsubscribe.ts
  ts/features/bonus/cgn/store/reducers/details.ts
  ts/features/bonus/cgn/store/reducers/index.ts
  ts/features/bonus/cgn/store/reducers/unsubscribe.ts
  ts/sagas/profile.ts
  ts/screens/profile/RemoveAccountDetailsScreen.tsx
Labels: Carta Giovani Nazionale, legal-compliance ⚖️

#3677 chore(Carta Giovani Nazionale): [IOACGN-31] Re-enables CGN remote FF
  ts/store/reducers/backendStatus.ts
Labels: Carta Giovani Nazionale

#3679 fix: [IA-637] Update PayPal logo
  img/wallet/payment-methods/paypal/paypal_logo.svg
Labels: paypal

#3693 [IAMVL-63] Use message ID to retrieve the attachment
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
Labels: Messaggi a valore legale

#3674 chore: [IA-634] Add Zendesk tests
  ts/__mocks__/io-react-native-zendesk.ts
  ts/features/zendesk/components/__tests__/ZendeskSupportComponent.test.tsx
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/features/zendesk/screens/ZendeskChooseCategory.tsx
  ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx
  ts/features/zendesk/screens/ZendeskPanicMode.tsx
  ts/features/zendesk/screens/__tests__/ZendeskAskPermissions.test.tsx
  ts/features/zendesk/screens/__tests__/ZendeskChooseCategory.test.tsx
  ts/features/zendesk/screens/__tests__/ZendeskChooseSubCategory.test.tsx
  ts/features/zendesk/screens/__tests__/ZendeskPanicMode.test.tsx
  ts/features/zendesk/screens/__tests__/ZendeskSupportHelpCenter.test.tsx
  ts/features/zendesk/store/reducers/__tests__/index.test.ts
Labels: Zendesk

#3681 chore(Messaggi a valore legale): [IAMVL-26] Persist attachments preferences for MVL
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/__tests__/persistedStore.test.ts
  ts/boot/configureStoreAndPersistor.ts
  ts/features/common/store/reducers/index.ts
  ts/features/mvl/index.ts
  ts/features/mvl/screens/details/components/attachment/DownloadAttachmentConfirmationBottomSheet.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachments.tsx
  ts/features/mvl/screens/details/components/attachment/__test__/MvlAttachments.test.tsx
  ts/features/mvl/store/actions/index.ts
  ts/features/mvl/store/reducers/__test__/preferences.test.ts
  ts/features/mvl/store/reducers/index.ts
  ts/features/mvl/store/reducers/preferences.ts
  ts/screens/profile/ProfileMainScreen.tsx
  ts/store/reducers/entities/index.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
Labels: Messaggi a valore legale

#3689 chore: [IA-432] Trace message read with message type
  ts/features/euCovidCert/screens/EuCovidCertificateRouterScreen.tsx
  ts/features/mvl/screens/MvlRouterScreen.tsx
  ts/features/mvl/screens/__test__/MvlRouterScreen.test.tsx
  ts/screens/messages/MessageDetailScreen/index.tsx
  ts/screens/messages/paginated/MessageDetailScreen.tsx
  ts/store/actions/messages.ts
  ts/store/reducers/entities/__tests__/messagesStatus.test.ts
  ts/utils/messages.ts
Labels: legal-compliance ⚖️

#3699 chore(Carta Giovani Nazionale): [IOACGN-32] Handles new ProductCategories for CGN
  img/bonus/cgn/categories/culture.svg
  img/bonus/cgn/categories/financialServices.svg
  img/bonus/cgn/categories/home.svg
  img/bonus/cgn/categories/job.svg
  img/bonus/cgn/categories/learning.svg
  img/bonus/cgn/categories/shopping.svg
  img/bonus/cgn/categories/sport.svg
  img/bonus/cgn/categories/sustainableMobility.svg
  img/bonus/cgn/categories/telefonia.svg
  img/bonus/cgn/categories/telephoneInternet.svg
  img/bonus/cgn/categories/travel.svg
  img/bonus/cgn/categories/wellness.svg
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantListItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnStaticCodeComponent.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsTabsScreen.tsx
  ts/features/bonus/cgn/utils/filters.ts
Labels: Carta Giovani Nazionale

#3697 chore(Bonus Pagamenti Digitali): [IAC-132] Opt-in payment feature flag
  .env.local
  .env.production
  package.json
  ts/config.ts
  ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.ts
  ts/store/reducers/__mock__/backendStatus.ts
Labels: Bonus Pagamenti Digitali

#3698 chore(Messaggi a valore legale): [IAMVL-46] Disable Android, enable MVL and pagination
  .circleci/config.yml
  .env.production
Labels: Messaggi a valore legale
