Repository pagopa/io-app, pull requests merged in 2022-09, with the labels that each got.

#4111 feat(Piattaforma Notifiche): [IAMVL-97] Track PN events to Mixpanel
  ts/features/messages/components/MessageAttachmentPreview.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachmentDownload.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessageTimelineCTA.tsx
  ts/features/pn/components/PnOpenConfirmationBottomSheet.tsx
  ts/features/pn/components/PnServiceCTA.tsx
  ts/features/pn/screens/PnAttachmentPreview.tsx
  ts/sagas/messages/watchThirdPartyMessageSaga.ts
  ts/screens/messages/paginated/MessageRouterScreen.tsx
Labels: legal-approved ⚖️ ✅, Piattaforma Notifiche

#4119 fix(Piattaforma Notifiche): [IAMVL-99] Attachment ID might not be unique per user
  ts/features/messages/components/MessageAttachmentPreview.tsx
  ts/features/mvl/index.ts
  ts/features/mvl/saga/networking/downloadMvlAttachment.ts
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
  ts/features/mvl/screens/details/MvlDetailsScreen.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachmentDownload.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachmentPreview.tsx
  ts/features/mvl/screens/details/components/attachment/__test__/MvlAttachments.test.tsx
  ts/features/mvl/store/actions/downloads.ts
  ts/features/mvl/store/reducers/__test__/downloads.test.ts
  ts/features/mvl/store/reducers/downloads.ts
  ts/features/mvl/types/__mock__/mvlMock.ts
  ts/features/mvl/types/mvlData.ts
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/screens/PnAttachmentPreview.tsx
  ts/features/pn/store/types/transformers.ts
Labels: Piattaforma Notifiche

#4120 chore: [IA-927] Allow to filter PSPs on poste_datamatrix_scan payment origin
  package.json
  ts/config.ts
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/wallet/payment/ScanQrCodeScreen.tsx
  ts/screens/wallet/payment/__tests__/commons.test.ts
  ts/screens/wallet/payment/common.ts
  ts/store/actions/wallet/payment.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/wallet/payment.ts
  ts/types/comma-separated-list.ts
Labels: Payments
