Repository pagopa/io-app, pull requests merged in 2022-02, with the labels that each got.

#3701 chore(Bonus Pagamenti Digitali): [IAC-126] Create payments methods opt-in workunit
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/bpd/navigation/navigator.ts
  ts/features/bonus/bpd/navigation/routes.ts
  ts/features/bonus/bpd/saga/index.ts
  ts/features/bonus/bpd/saga/orchestration/optInPaymentMethodsHandler.ts
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsCashbackUpdateScreen.tsx
  ts/features/bonus/bpd/store/actions/index.ts
  ts/features/bonus/bpd/store/actions/optInPaymentMethods.ts
  ts/navigation/WalletNavigator.ts
Labels: Bonus Pagamenti Digitali

#3712 chore(Messaggi a valore legale): [IAMVL-46] Disable Android, enable MVL and pagination"
  .circleci/config.yml
  .env.production
Labels: Messaggi a valore legale

#3688 fix: [IA-642] Onboarding success screen says to continue the payment even when the user starts from wallet
  ts/features/wallet/onboarding/paypal/screen/PayPalOnboardingCheckoutCompletedScreen.tsx
  ts/features/wallet/onboarding/paypal/screen/PayPalOnboardingCompletedSuccessComponent.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalOnboardingCompletedSuccessComponent.test.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PayPalOnboardingCompletedSuccessComponent.test.tsx.snap
  ts/features/wallet/onboarding/paypal/store/reducers/__test__/onOboardingCompleted.test.ts
  ts/features/wallet/onboarding/paypal/store/reducers/index.ts
  ts/features/wallet/onboarding/paypal/store/reducers/onOboardingCompleted.ts
  ts/features/wallet/onboarding/paypal/store/reducers/outcomeCode.ts
Labels: paypal

#3709 chore(Bonus Pagamenti Digitali): [IAC-134] Hide cashback card
  ts/screens/wallet/WalletHomeScreen.tsx
Labels: Bonus Pagamenti Digitali

#3719 fix: [IA-244] Remove `reason` field from tracking `CTA_FRONT_MATTER_DECODING_ERROR` event
  ts/utils/messages.ts
Labels: legal-approved ⚖️ ✅

#3710 chore(Carta Giovani Nazionale): [IOACGN-34] UI Improvements on CGN components and labels
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/__test__/__snapshots__/CgnDiscountCodeComponent.test.tsx.snap
  ts/features/bonus/cgn/hooks/useCgnDiscountDetailBottomSheet.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
Labels: Carta Giovani Nazionale

#3722 chore(Carta Giovani Nazionale): [IOACGN-36] Temporary ignore CGN FF for production release
  ts/store/reducers/backendStatus.ts
Labels: Carta Giovani Nazionale

#3687 chore(Messaggi a valore legale): [IAMVL-51] Support two lines filename and preserve extension
  ts/features/mvl/saga/networking/handleGetMvlDetails.ts
  ts/features/mvl/screens/details/components/attachment/MvlAttachments.tsx
Labels: Messaggi a valore legale

#3732 chore: [IA-657] Track screen lock availability
  ts/mixpanel.ts
  ts/utils/device.ts
Labels: legal-approved ⚖️ ✅

#3726 chore(Bonus Pagamenti Digitali): [IAC-137] Add `optInStatus` field in citizenV2 model
  package.json
  ts/features/bonus/bpd/api/citizen/v2.ts
  ts/features/bonus/bpd/api/patchedTypes.ts
  ts/features/bonus/bpd/saga/index.ts
  ts/features/bonus/bpd/saga/networking/index.ts
  ts/features/bonus/bpd/store/actions/details.ts
  ts/features/bonus/bpd/store/actions/onboarding.ts
  ts/features/bonus/bpd/store/reducers/details/activation/index.ts
Labels: Bonus Pagamenti Digitali

#3706 chore(Messaggi a valore legale): [IAMVL-66] Add loader and error management to the bottom sheet for attachments
  locales/en/index.yml
  locales/it/index.yml
  ts/features/mvl/__tests__/utils.test.ts
  ts/features/mvl/screens/details/components/attachment/DownloadAttachmentConfirmationBottomSheet.tsx
  ts/features/mvl/screens/details/components/attachment/MvlAttachments.tsx
  ts/features/mvl/screens/details/components/attachment/__test__/MvlAttachments.test.tsx
  ts/features/mvl/utils.ts
Labels: Messaggi a valore legale

#3749 chore(Carta Giovani Nazionale): [IOACGN-35] Removes unused components for CGN otp dedicated screen
  ts/features/bonus/cgn/components/__test__/OtpCodeRefreshComponent.test.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnOTPCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/OtpCodeComponent.tsx
  ts/features/bonus/cgn/components/otp/OtpNotWorking.tsx
  ts/features/bonus/cgn/screens/CgnOtpScreen.tsx
Labels: Carta Giovani Nazionale

#3744 chore(Bonus Pagamenti Digitali): [IAC-130] Add bottom sheet to display the payment method to delete
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/bpd/components/__test__/BottomSheetMethodsToDelete.test.tsx
  ts/features/bonus/bpd/components/optInStatus/BottomSheetMethodsToDelete.tsx
  ts/store/reducers/wallet/wallets.ts
Labels: Bonus Pagamenti Digitali

#3725 chore(Bonus Pagamenti Digitali): [IAC-128] Opt-in payment method cashback update screen
  locales/en/bonus/bpd/optInPaymentMethods.md
  locales/en/index.yml
  locales/it/bonus/bpd/optInPaymentMethods.md
  locales/it/index.yml
  ts/components/core/IORenderHtml.tsx
  ts/features/bonus/bpd/navigation/actions.ts
  ts/features/bonus/bpd/navigation/navigator.ts
  ts/features/bonus/bpd/navigation/routes.ts
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsCashbackUpdateScreen.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsChoiceScreen.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/__tests__/OptInPaymentMethodsCashbackUpdateScreen.test.tsx
Labels: Bonus Pagamenti Digitali

#3738 chore(Carta Giovani Nazionale): [IOACGN-40] List available CGN operators selecting a category
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/merchants/CgnMerchantCategoryItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantListItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
  ts/features/bonus/cgn/navigation/navigator.ts
  ts/features/bonus/cgn/navigation/routes.ts
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/bonus/cgn/store/actions/categories.ts
  ts/features/bonus/cgn/store/actions/index.ts
  ts/features/bonus/cgn/store/reducers/categories.ts
  ts/features/bonus/cgn/store/reducers/index.ts
  ts/features/bonus/cgn/utils/filters.ts
Labels: Carta Giovani Nazionale

#3740 chore(Carta Giovani Nazionale): [IOACGN-39] CGN Merchants categories store structure
  ts/features/bonus/cgn/analytics/index.ts
  ts/features/bonus/cgn/saga/index.ts
  ts/features/bonus/cgn/saga/networking/categories/cgnCategoriesSaga.ts
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/store/actions/categories.ts
  ts/features/bonus/cgn/store/reducers/categories.ts
Labels: Carta Giovani Nazionale, legal-approved ⚖️ ✅

#3751 chore(Carta Giovani Nazionale): [IOACGN-38] Introduces API to retrieve the list of available categories
  package.json
  ts/features/bonus/cgn/api/backendCgnMerchants.ts
  ts/features/bonus/cgn/saga/index.ts
  ts/features/bonus/cgn/saga/networking/categories/cgnCategoriesSaga.ts
Labels: Carta Giovani Nazionale

#3767 chore(Carta Giovani Nazionale): [IOACGN-58] Updates finance category label
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/utils/__test__/filters.test.ts
Labels: Carta Giovani Nazionale

#3764 chore(Messaggi a valore legale): [IAMVL-72] Upgrade fs, blob-utils, share
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Messaggi a valore legale

#3768 fix(Carta Giovani Nazionale): [IOACGN-59] Fixes offline-operators API request has a prefixed coordinates
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/detail/eyca/EycaInformationComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaPendingComponent.tsx
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
Labels: Carta Giovani Nazionale

#3763 chore(Bonus Pagamenti Digitali): [IAC-131] Add thank you page and retry page
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/bpd/components/optInPaymentMethods/RetryAfterDeletionFailsComponent.tsx
  ts/features/bonus/bpd/components/optInPaymentMethods/ThankYouSuccessComponent.tsx
  ts/features/bonus/bpd/components/optInPaymentMethods/__tests__/RetryAfterDeletionFailsComponent.test.ts
  ts/features/bonus/bpd/components/optInPaymentMethods/__tests__/ThankYouSuccessComponent.test.ts
  ts/features/bonus/bpd/navigation/actions.ts
  ts/features/bonus/bpd/navigation/navigator.ts
  ts/features/bonus/bpd/navigation/routes.ts
  ts/features/bonus/bpd/saga/index.ts
  ts/features/bonus/bpd/saga/networking/index.ts
  ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/__tests__/optInDeletionChoiceHandler.test.ts
  ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/optInDeletionChoiceHandler.ts
  ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/optInPaymentMethodsHandler.ts
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsThankYouDeleteMethodsScreen.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsThankYouKeepMethodsScreen.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/__tests__/OptInPaymentMethodsThankYouDeleteMethodsScreen.test.ts
  ts/features/bonus/bpd/screens/optInPaymentMethods/__tests__/OptInPaymentMethodsThankYouKeepMethodsScreen.test.ts
  ts/features/bonus/bpd/store/actions/optInPaymentMethods.ts
  ts/features/bonus/bpd/store/reducers/details/activation/index.ts
  ts/store/reducers/wallet/wallets.ts
Labels: Bonus Pagamenti Digitali

#3773 chore(Bonus Pagamenti Digitali): [IAC-129] Implemented payment methods selection screen
  locales/en/index.yml
  locales/it/index.yml
  ts/components/core/IOBadge.tsx
  ts/components/core/selection/RadioButtonList.tsx
  ts/components/core/typography/Body.tsx
  ts/components/core/typography/LabelSmall.tsx
  ts/features/bonus/bonusVacanze/components/buttons/ButtonConfigurations.ts
  ts/features/bonus/bpd/components/optInStatus/BottomSheetMethodsToDelete.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsChoiceScreen.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/__tests__/OptInPaymentMethodsChoiceScreen.test.tsx
Labels: Bonus Pagamenti Digitali

#3777 legal design copy update
  locales/en/bonus/bpd/optInPaymentMethods.md
Labels: legal-approved ⚖️ ✅

#3774 chore(Messaggi a valore legale): [IAMVL-68] Preview MVL attachments on IOS
  android/app/build.gradle
  ios/Podfile.lock
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/mvl/__tests__/utils.test.ts
  ts/features/mvl/screens/details/components/attachment/DownloadAttachmentConfirmationBottomSheet.tsx
  ts/features/mvl/screens/details/components/attachment/PdfPreview.tsx
  ts/features/mvl/utils.ts
  yarn.lock
Labels: Messaggi a valore legale

#3789 fix(Bonus Pagamenti Digitali): [IAC-142] Fix wrong translation in OptInPaymentMethodsChoiceScreen
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsChoiceScreen.tsx
Labels: Bonus Pagamenti Digitali

#3781 chore(Carta Giovani Nazionale): [IOACGN-60] Implements new CGN Landing page Playground for tests purposes
  ts/navigation/ProfileNavigator.ts
  ts/navigation/routes.ts
  ts/screens/profile/CgnLandingPlayground.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: Carta Giovani Nazionale

#3792 fix(Carta Giovani Nazionale): [IOACGN-61] Fixes the bug that prevents to send Referer header for CGN landing page Discount
  ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
  ts/screens/profile/CgnLandingPlayground.tsx
Labels: Carta Giovani Nazionale
