Repository pagopa/io-app, pull requests merged in 2022-10, with the labels that each got.

#4063 feat(Firma con IO): [SFEQS-884] Add FCI local feature flag
  .env.local
  .env.production
  scripts/ts/danger/utils/changelog.ts
  ts/config.ts
Labels: Firma con IO

#4144 chore: [IOAPPCIT-6] Add event to track the Rooted device information modal
  ts/screens/authentication/LandingScreen.tsx
Labels: legal-approved ⚖️ ✅

#4075 chore: [IAI-232] Remove/Update references to color values
  ts/components/ExperimentalFeaturesBanner.tsx
  ts/components/Pinpad/KeyPad.tsx
  ts/components/RegionServiceWebView.tsx
  ts/components/RemindEmailValidationOverlay.tsx
  ts/components/core/variables/IOColors.ts
  ts/components/infoScreen/imageRendering.tsx
  ts/components/messages/MessageDueDateBar.tsx
  ts/components/messages/paginated/MessageDetail/DueDateBar.tsx
  ts/components/messages/paginated/MessageDetail/__tests__/__snapshots__/MedicalPrescriptionDueDateBar.test.tsx.snap
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/BetaBannerComponent.tsx
  ts/components/ui/Switch.tsx
  ts/components/ui/__test__/__snapshots__/ActivityIndicator.test.tsx.snap
  ts/components/ui/__test__/__snapshots__/CustomBadge.test.tsx.snap
  ts/components/wallet/PaymentsHistoryList.tsx
  ts/components/wallet/card/SectionCardComponent.tsx
  ts/features/bonus/bonusVacanze/components/ActiveBonus.tsx
  ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx
  ts/features/bonus/bonusVacanze/screens/activation/request/ActivateBonusDiscrepancies.tsx
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/components/merchants/CgnDiscountValueBox.tsx
  ts/features/fims/components/SuccessContent.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/ingress/CheckBox.tsx
  ts/theme/components/Button.ts
  ts/theme/variables.ts
Labels: Design System
