Repository pagopa/io-app, pull requests merged in 2022-03, with the labels that each got.

#3718 feat: [IA-653] Update psp on payment checkout
  ts/features/wallet/onboarding/paypal/saga/networking/index.ts
  ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalPspUpdateScreen.test.tsx
  ts/features/wallet/onboarding/paypal/store/transformers.ts
  ts/features/wallet/paypal/component/PayPalCheckoutPspComponent.tsx
  ts/features/wallet/paypal/component/__test__/PayPalCheckoutPspComponent.test.tsx
  ts/features/wallet/paypal/component/__test__/__snapshots__/PayPalCheckoutPspComponent.test.tsx.snap
  ts/features/wallet/paypal/screen/PayPalPspUpdateScreen.tsx
  ts/navigation/WalletNavigator.ts
  ts/navigation/routes.ts
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
  ts/store/actions/navigation.ts
  ts/store/actions/wallet/payment.ts
  ts/store/reducers/wallet/payment.ts
Labels: paypal

#3785 chore(Bonus Pagamenti Digitali): [IAC-140] Starts opt-in payment methods workunit
  ts/features/bonus/bpd/components/optInPaymentMethods/BpdOptInPaymentMethodsContainer.tsx
  ts/features/bonus/bpd/components/walletCardContainer/BpdCardsInWalletComponent.tsx
  ts/features/bonus/bpd/saga/index.ts
  ts/features/bonus/bpd/saga/networking/__test__/loadBpdData.test.ts
  ts/features/bonus/bpd/saga/networking/index.ts
  ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/__tests__/optInShouldShowChoiceHandler.test.ts
  ts/features/bonus/bpd/saga/orchestration/optInPaymentMethods/optInShouldShowChoiceHandler.ts
  ts/features/bonus/bpd/store/actions/details.ts
  ts/features/bonus/bpd/store/actions/optInPaymentMethods.ts
  ts/features/bonus/bpd/store/reducers/details/activation/index.ts
  ts/features/bonus/bpd/store/reducers/details/activation/ui.ts
  ts/features/wallet/component/__test__/FeaturedCardCarousel.test.tsx
  ts/screens/wallet/WalletHomeScreen.tsx
Labels: Bonus Pagamenti Digitali

#3817 chore(Carta Giovani Nazionale): [IOACGN-63] Prevents the possibility to open media on full screen for CGN merchants landing page
  ts/components/WebviewComponent.tsx
  ts/components/__tests__/__snapshots__/WebviewComponent.test.tsx.snap
Labels: Carta Giovani Nazionale

#3786 chore(Bonus Pagamenti Digitali): [IAC-136] Opt-in analytics
  ts/features/bonus/bpd/analytics/index.ts
Labels: Bonus Pagamenti Digitali, legal-approved ⚖️ ✅

#3821 chore: [IA-701] Implements analytics on ua donations
  ts/features/uaDonations/components/UaDonationsBanner.tsx
  ts/features/uaDonations/screens/UAWebViewScreen.tsx
Labels: legal-approved ⚖️ ✅

#3834 chore(Federated Identity Management System): [IAFIMS-1] Adds Remote and Local feature flag for FIMS feature
  .env.local
  .env.production
  package.json
  scripts/ts/danger/utils/changelog.ts
  ts/config.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: Federated Identity Management System

#3849 chore(Carta Giovani Nazionale): [IOACGN-68] Refactors bucket code request component to avoid huge bucket consuption
  ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
  ts/features/bonus/cgn/store/actions/bucket.ts
  ts/features/bonus/cgn/store/reducers/bucket.ts
Labels: Carta Giovani Nazionale

#3865 chore: [IA-754] Track migration events
  ts/store/middlewares/analytics.ts
Labels: legal-approved ⚖️ ✅

#3842 chore(Carta Giovani Nazionale): [IOACGN-65] Implements event tracking for landing page error events
  ts/components/WebviewComponent.tsx
Labels: Carta Giovani Nazionale, legal-approved ⚖️ ✅
