Repository pagopa/io-app, pull requests merged in 2022-12, with the labels that each got.

#4216 chore(IDPay): [IODPAY-65] Add IDPay Onboarding machine error handling and back navigation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/onboarding/components/FailureMessage.tsx
  ts/features/idpay/onboarding/navigation/navigator.tsx
  ts/features/idpay/onboarding/screens/CompletionScreen.tsx
  ts/features/idpay/onboarding/screens/FailureScreen.tsx
  ts/features/idpay/onboarding/screens/InitiativeDetailsScreen.tsx
  ts/features/idpay/onboarding/screens/InitiativeSelfDeclarationsScreen.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts
  ts/features/idpay/onboarding/xstate/actions.ts
  ts/features/idpay/onboarding/xstate/failure.ts
  ts/features/idpay/onboarding/xstate/machine.ts
  ts/features/idpay/onboarding/xstate/provider.tsx
  ts/features/idpay/onboarding/xstate/services.ts
  ts/screens/profile/playgrounds/IDPayOnboardingPlayground.tsx
Labels: IDPay

#4217 feat(IDPay): [IODPAY-60] UI Refinements to Interop requirements' page + Add new outline button
  ios/Podfile.lock
  ts/components/core/typography/Body.tsx
  ts/components/core/typography/H4.tsx
  ts/components/core/typography/__test__/__snapshots__/typography.test.tsx.snap
  ts/components/core/variables/IOAnimations.ts
  ts/components/services/ContactPreferencesToggles/__test__/__snapshots__/PreferenceToggleRow.test.tsx.snap
  ts/components/services/ServiceMetadata/__tests__/__snapshots__/InformationRow.test.tsx.snap
  ts/components/ui/ButtonExtendedOutline.tsx
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/DocumentsNavigationBar.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/SignatureFieldItem.test.tsx.snap
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PayPalOnboardingCompletedSuccessComponent.test.tsx.snap
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PspRadioItem.test.tsx.snap
  ts/screens/showroom/ButtonsShowroom.tsx
  ts/screens/showroom/Showroom.tsx
Labels: Design System, IDPay

#4221 fix: [IABT-1421] Remove BPay bank references from the payment flow
  ts/components/wallet/payment/PickAvailablePaymentMethodListItem.tsx
Labels: enhancement, bancomatPay

#4227 feat(IDPay): [IODPAY-66] Added padding between items in PDNDPrerequisites page
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
Labels: IDPay

#4222 feat(Firma con IO): [SFEQS-1060] Add qtsp clauses and document preview screens
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fci/components/DocumentViewer.tsx
  ts/features/fci/components/LinkedText.tsx
  ts/features/fci/components/QtspClauseListItem.tsx
  ts/features/fci/components/__tests__/LinkedText.test.tsx
  ts/features/fci/components/__tests__/QtspClauseListItem.test.tsx
  ts/features/fci/components/__tests__/__snapshots__/LinkedText.test.tsx.snap
  ts/features/fci/navigation/FciStackNavigator.tsx
  ts/features/fci/navigation/params.ts
  ts/features/fci/navigation/routes.ts
  ts/features/fci/saga/index.ts
  ts/features/fci/saga/networking/__tests__/handleDownloadDocument.test.ts
  ts/features/fci/saga/networking/handleDownloadDocument.ts
  ts/features/fci/screens/__tests__/FciQtspClausesScreen.test.tsx
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/store/actions/index.ts
  ts/features/fci/store/reducers/__tests__/fciDownloadPreview.test.ts
  ts/features/fci/store/reducers/fciDownloadPreview.ts
  ts/features/fci/store/reducers/fciQtspClauses.ts
  ts/features/fci/store/reducers/fciQtspFilledDocument.ts
  ts/features/fci/store/reducers/index.ts
  ts/features/fci/types/__mocks__/QtspClausesMetadata.mock.ts
Labels: Firma con IO

#4239 feat(Firma con IO): [SFEQS-1165] Add signing request with identification screen and thank you page
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/fci/api/backendFci.ts
  ts/features/fci/components/DocumentViewer.tsx
  ts/features/fci/components/ErrorComponent.tsx
  ts/features/fci/components/GenericErrorComponent.tsx
  ts/features/fci/components/LinkedText.tsx
  ts/features/fci/components/SuccessComponent.tsx
  ts/features/fci/components/__tests__/ErrorComponent.test.tsx
  ts/features/fci/components/__tests__/SuccessComponent.test.tsx
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/fci/navigation/FciStackNavigator.tsx
  ts/features/fci/navigation/params.ts
  ts/features/fci/saga/index.ts
  ts/features/fci/saga/networking/__tests__/handleCreateFilledDocument.test.ts
  ts/features/fci/saga/networking/__tests__/handleGetQtspMetadata.test.ts
  ts/features/fci/saga/networking/handleCreateFilledDocument.ts
  ts/features/fci/saga/networking/handleCreateSignature.ts
  ts/features/fci/saga/networking/handleDownloadDocument.ts
  ts/features/fci/saga/networking/handleGetQtspMetadata.ts
  ts/features/fci/saga/networking/handleGetSignatureRequestById.ts
  ts/features/fci/screens/FciRouterScreen.tsx
  ts/features/fci/screens/__tests__/FciSignatureFieldsScreen.test.tsx
  ts/features/fci/screens/__tests__/FciThankyouScreen.test.tsx
  ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
  ts/features/fci/screens/valid/FciThankyouScreen.tsx
  ts/features/fci/store/actions/index.ts
  ts/features/fci/store/reducers/__tests__/fciDocumentSignatures.test.ts
  ts/features/fci/store/reducers/__tests__/fciQtspClauses.test.ts
  ts/features/fci/store/reducers/__tests__/fciQtspFilledDocument.test.ts
  ts/features/fci/store/reducers/__tests__/fciSignature.test.ts
  ts/features/fci/store/reducers/__tests__/fciSignatureRequest.test.ts
  ts/features/fci/store/reducers/fciDocumentSignatures.ts
  ts/features/fci/store/reducers/fciDownloadPreview.ts
  ts/features/fci/store/reducers/fciQtspClauses.ts
  ts/features/fci/store/reducers/fciQtspFilledDocument.ts
  ts/features/fci/store/reducers/fciSignature.ts
  ts/features/fci/store/reducers/fciSignatureRequest.ts
  ts/features/fci/types/__mocks__/CreateFilledDocumentBody.mock.ts
  ts/features/fci/types/__mocks__/CreateSignatureBody.mock.ts
  ts/features/fci/types/__mocks__/QtspClausesMetadata.mock.ts
  ts/features/fci/types/__mocks__/SignatureDetailView.mock.ts
  ts/features/fci/types/__mocks__/SignatureRequestDetailView.mock.ts
  ts/features/fci/utils/__tests__/signatureFields.test.ts
  ts/navigation/AppStackNavigator.tsx
Labels: Firma con IO

#4243 feat(IDPay): [IODPAY-71] Add client and API definition for IDPay IBAN endpoints
  package.json
  ts/features/idpay/initiative/configuration/api/client.ts
Labels: IDPay

#4219 chore: [IA-854] Added translations to jailbreak and root messages
  locales/de/index.yml
  locales/de/jailbroken_body.md
  locales/de/rooted_body.md
  locales/en/jailbroken_body.md
  locales/en/rooted_body.md
Labels: legal-approved ⚖️ ✅

#4240 chore(IDPay): IDPay initiative configuration machine refactoring
  ts/features/idpay/initiative/configuration/navigation/navigator.tsx
  ts/features/idpay/initiative/configuration/screens/InitiativeConfigurationIntroScreen.tsx
  ts/features/idpay/initiative/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/initiative/configuration/xstate/actions.ts
  ts/features/idpay/initiative/configuration/xstate/context.ts
  ts/features/idpay/initiative/configuration/xstate/events.ts
  ts/features/idpay/initiative/configuration/xstate/machine.ts
  ts/features/idpay/initiative/configuration/xstate/selectors.ts
  ts/features/idpay/initiative/configuration/xstate/services.ts
  ts/features/idpay/initiative/details/components/InitiativeSettingsComponent.tsx
  ts/features/idpay/initiative/details/components/InitiativeTimelineComponent.tsx
  ts/features/idpay/initiative/details/components/PaymentDataComponent.tsx
  ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
Labels: IDPay

#4248 chore: [IAI-254] Toast notifications' inventory
  ts/screens/showroom/Showroom.tsx
  ts/screens/showroom/core/ToastNotificationsShowroom.tsx
Labels: Design System

#4250 chore: [IAI-219] Text fields' inventory
  ts/screens/showroom/Showroom.tsx
  ts/screens/showroom/core/TextFieldsShowroom.tsx
Labels: Design System

#4241 chore: [IAI-252] Buttons' inventory
  ts/components/ButtonWithImage.tsx
  ts/components/core/variables/IOAnimations.ts
  ts/screens/showroom/ButtonsShowroom.tsx
  ts/screens/showroom/Showroom.tsx
  ts/screens/showroom/components/ComponentViewerBox.tsx
  ts/screens/showroom/core/ButtonsShowroom.tsx
  ts/screens/showroom/core/OthersShowroom.tsx
Labels: Design System

#4249 fix(Firma con IO): [SFEQS-1264] Update subtitle in data sharing screen
  locales/en/index.yml
  locales/it/index.yml
Labels: Firma con IO

#4251 chore(Firma con IO): [SFEQS-1230] Add a new privacy tag link to support privacy url
  ts/features/fci/components/LinkedText.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/store/reducers/fciQtspClauses.ts
Labels: Firma con IO

#4258 fix(Firma con IO): [SFEQS-1267] Update copy in the bottom sheet buttons when canceling the signature flow
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
Labels: Firma con IO
