Repository pagopa/io-app, pull requests merged in 2022-04, with the labels that each got.

#3883 chore(Carta della cultura): [AP-2] Add CDC local feature flag
  .env.local
  .env.production
  scripts/ts/danger/utils/changelog.ts
  ts/config.ts
Labels: Carta della cultura

#3884 chore: [IA-806] Show BPay in checkout payment screen
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/__tests__/ConfirmPaymentMethodScreen.test.tsx
Labels: bancomatPay

#3888 chore(Carta della cultura): [AP-3] Add remote carta della cultura feature flag
  package.json
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: Carta della cultura

#3895 chore(Federated Identity Management System): [IAFIMS-10] Upgrade io-services-metadata specifications
  package.json
  ts/store/reducers/__mock__/backendStatus.ts
Labels: Federated Identity Management System

#3914 chore(Carta Giovani Nazionale): [IOACGN-70] Changes on the Merchant detail screen and Discount display
  img/icons/openweburl.svg
  ts/components/core/typography/Label.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
Labels: Carta Giovani Nazionale

#3907 chore(Carta della cultura): [AP-7] Model types, actions and reducers of carta della cultura
  ts/features/bonus/bonusVacanze/store/reducers/index.ts
  ts/features/bonus/cdc/analytics/placeholder
  ts/features/bonus/cdc/components/placeholder
  ts/features/bonus/cdc/navigation/placeholder
  ts/features/bonus/cdc/saga/placeholder
  ts/features/bonus/cdc/screens/placeholder
  ts/features/bonus/cdc/store/actions/cdcBonusRequest.ts
  ts/features/bonus/cdc/store/actions/index.ts
  ts/features/bonus/cdc/store/reducers/__test__/cdcBonusRequest.test.ts
  ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
  ts/features/bonus/cdc/store/reducers/index.ts
  ts/features/bonus/cdc/types/CdcBonusRequest.ts
  ts/store/actions/types.ts
Labels: Carta della cultura

#3898 chore(Carta Giovani Nazionale): [IOACGN-69] Implements e2e tests for CGN activation flows
  scripts/api-config.json
  ts/components/services/NewServiceListItem.tsx
  ts/features/bonus/cgn/__e2e__/cgn.e2e.ts
  ts/features/bonus/cgn/components/CgnCardInWalletComponent.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
Labels: Carta Giovani Nazionale

#3916 chore(Carta della cultura): [AP-11] Carta della cultura ToS screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cdc/screens/CdcBonusRequestInformationTos.tsx
  ts/features/bonus/cdc/screens/placeholder
Labels: Carta della cultura

#3911 chore(Carta della cultura): [AP-6,AP-9] Add carta della cultura navigation and workunit
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cdc/navigation/CdcStackNavigator.tsx
  ts/features/bonus/cdc/navigation/params.ts
  ts/features/bonus/cdc/navigation/routes.ts
  ts/features/bonus/cdc/screens/CdcBonusRequestBonusRequested.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestInformationTos.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectResidence.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectYear.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/store/reducers/backendStatus.ts
Labels: Carta della cultura

#3875 chore: [IA-787,IA-789,IA-835] Upgrade psp list and update wallet API from v1 to v2
  assets/paymentManager/spec.json
  img/wallet/payment-methods/bpay.png
  img/wallet/payment-methods/paypal.png
  locales/en/index.yml
  locales/it/index.yml
  ts/api/pagopa.ts
  ts/components/__tests__/PspComponent.test.tsx
  ts/components/wallet/payment/PickAvailablePaymentMethodListItem.tsx
  ts/components/wallet/payment/PickNotAvailablePaymentMethodListItem.tsx
  ts/components/wallet/payment/PspComponent.tsx
  ts/features/wallet/bancomatpay/screen/BPayDetailScreen.tsx
  ts/features/wallet/onboarding/paypal/components/PspInfoBottomSheet.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/PayPalPspUpdateScreen.test.tsx
  ts/features/wallet/onboarding/paypal/store/transformers.ts
  ts/features/wallet/onboarding/paypal/types/index.ts
  ts/navigation/WalletNavigator.ts
  ts/sagas/wallet.ts
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/wallet/AddPaymentMethodScreen.tsx
  ts/screens/wallet/ConfirmCardDetailsScreen.tsx
  ts/screens/wallet/__tests__/AddCardScreen.test.tsx
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
  ts/screens/wallet/payment/PickPspScreen.tsx
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
  ts/screens/wallet/payment/__tests__/ConfirmPaymentMethodScreen.test.tsx
  ts/screens/wallet/payment/__tests__/PickPaymentMethodScreen.test.tsx
  ts/screens/wallet/payment/common.ts
  ts/store/actions/wallet/payment.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/wallet/payment.ts
  ts/utils/payment.ts
  ts/utils/paymentMethod.ts
Labels: bancomatPay

#3850 chore(Federated Identity Management System): [IAFIMS-6] Implements FIMS webview component and screens
  ts/components/ui/Markdown/handlers/internalLink.ts
  ts/features/fims/components/CommonContent.tsx
  ts/features/fims/components/ErrorContent.tsx
  ts/features/fims/components/FimsWebView.tsx
  ts/features/fims/components/SuccessContent.tsx
  ts/features/fims/components/WebviewErrorComponent.tsx
  ts/features/fims/navigation/navigator.tsx
  ts/features/fims/navigation/params.ts
  ts/features/fims/navigation/routes.ts
  ts/features/fims/screens/FimsWebviewScreen.tsx
  ts/features/fims/types/FimsWebviewParams.ts
  ts/features/fims/utils/placeholder
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/utils/cookieManager.ts
Labels: Federated Identity Management System
