Repository pagopa/io-app, pull requests merged in 2022-05, with the labels that each got.

#3925 feat(Messaggi a valore legale): [IAMVL-67] Android menu
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/mvl/screens/details/components/attachment/PdfPreview.tsx
  ts/features/mvl/utils.ts
  yarn.lock
Labels: Messaggi a valore legale

#3940 chore: [LB-348] Change italian root/jailbreak message
  locales/it/jailbroken_body.md
  locales/it/rooted_body.md
  ts/screens/modal/RootedDeviceModal.tsx
Labels: legal-approved ⚖️ ✅

#3887 chore: [IA-764] Premium Messages Opt-In/Out profile stub screen
  ts/navigation/ProfileNavigator.ts
  ts/navigation/routes.ts
  ts/screens/profile/PrivacyMainScreen.tsx
  ts/screens/profile/premiumMessages/PremiumMessagesOptInOutProfileScreen.tsx
Labels: Messaggi Premium Opt-In/Out

#3935 chore: [IA-851] Refresh users's wallet when visit payment section
  ts/screens/wallet/WalletHomeScreen.tsx
Labels: bancomatPay

#3929 chore: [IA-831] Activate disabled payment methods just before payment checkout
  locales/en/index.yml
  locales/it/index.yml
  ts/components/wallet/payment/PickAvailablePaymentMethodListItem.tsx
  ts/components/wallet/payment/PickPaymentMethodBaseListItem.tsx
  ts/features/wallet/component/__test__/PagoPaPaymentCapability.test.tsx
  ts/features/wallet/component/features/PaymentMethodSettings.tsx
  ts/screens/wallet/payment/ManualDataInsertionScreen.tsx
  ts/screens/wallet/payment/PickPaymentMethodScreen.tsx
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
  ts/screens/wallet/payment/__tests__/PickPaymentMethodScreen.test.tsx
  ts/store/reducers/wallet/__tests__/wallets.test.ts
  ts/store/reducers/wallet/wallets.ts
  ts/utils/__tests__/paymentMethodCapabilities.test.ts
  ts/utils/paymentMethodCapabilities.ts
Labels: bancomatPay

#3937 chore: [IA-845] Update BancomatPay privacy url
  ts/features/wallet/onboarding/bancomatPay/screens/search/BPaySearchStartScreen.tsx
Labels: bancomatPay

#3917 chore(Carta della cultura): [AP-12] Ask residence screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cdc/navigation/placeholder
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectResidence.tsx
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectResidence.test.ts
Labels: Carta della cultura

#3927 chore(Carta della cultura): [AP-15] Carta della cultura networking
  assets/CdcSwagger.yml
  package.json
  ts/features/bonus/cdc/api/backendCdc.ts
  ts/features/bonus/cdc/saga/index.ts
  ts/features/bonus/cdc/saga/networking/__test__/handleGetStatoBeneficiario.test.ts
  ts/features/bonus/cdc/saga/networking/__test__/handlePostRegistraBeneficiario.test.ts
  ts/features/bonus/cdc/saga/networking/handleGetStatoBeneficiario.ts
  ts/features/bonus/cdc/saga/networking/handlePostRegistraBeneficiario.ts
  ts/features/bonus/cdc/saga/placeholder
  ts/features/bonus/cdc/store/actions/cdcBonusRequest.ts
  ts/features/bonus/cdc/store/reducers/__test__/cdcBonusRequest.test.ts
  ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
  ts/features/bonus/cdc/types/CdcBonusRequest.ts
  ts/sagas/startup.ts
Labels: Carta della cultura

#3924 chore: [IA-796] BPay tracking events
  ts/screens/wallet/payment/ConfirmPaymentMethodScreen.tsx
  ts/store/actions/wallet/payment.ts
Labels: legal-approved ⚖️ ✅, bancomatPay

#3942 chore(Carta della cultura): [AP-23] Select year screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectResidence.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectYear.tsx
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectResidence.test.ts
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectYear.test.ts
  ts/features/bonus/cdc/store/actions/cdcBonusRequest.ts
  ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
Labels: Carta della cultura

#3921 chore(Carta della cultura): [AP-10] Create carta della cultura entry point on service card
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
  ts/features/bonus/cdc/components/__test__/CdcServiceCTA.test.ts
  ts/features/bonus/cdc/components/placeholder
Labels: Carta della cultura

#3949 chore(Carta della cultura): [AP-24] Update select residence screen
  img/features/cdc/bonus.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/components/core/selection/RadioButtonList.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectResidence.tsx
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectResidence.test.ts
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectYear.test.ts
  ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
Labels: Carta della cultura

#3948 chore(Carta Giovani Nazionale): [IOACGN-71] Adds news badge for CGN discounts on category list, merchants list and discount items
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/core/IOBadge.tsx
  ts/components/core/typography/LabelSmall.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsChoiceScreen.tsx
  ts/features/bonus/cgn/api/backendCgnMerchants.ts
  ts/features/bonus/cgn/components/merchants/CgnMerchantListItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
  ts/features/bonus/cgn/saga/networking/categories/cgnCategoriesSaga.ts
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/bonus/cgn/store/actions/categories.ts
  ts/features/bonus/cgn/store/reducers/categories.ts
  ts/features/bonus/cgn/utils/__test__/filters.test.ts
  ts/features/bonus/cgn/utils/filters.ts
  ts/features/bonus/cgn/utils/merchants.ts
Labels: Carta Giovani Nazionale

#3960 chore(Carta della cultura): [AP-26] Update cdc service CTA action
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
Labels: Carta della cultura

#3959 chore(Carta della cultura): [AP-21] Add cdc status bar
  package.json
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
Labels: Carta della cultura

#3958 chore(Carta della cultura): [AP-5] Add cdc bonus entry points
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/bonusVacanze/screens/AvailableBonusScreen.tsx
  ts/features/bonus/bonusVacanze/store/reducers/availableBonusesTypes.ts
  ts/features/bonus/bonusVacanze/utils/bonus.ts
  ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
  ts/features/wallet/component/__test__/FeaturedCardCarousel.test.tsx
  ts/features/wallet/component/card/FeaturedCardCarousel.tsx
Labels: Carta della cultura

#3955 chore(Carta della cultura): [AP-28] Update select residence screen logic
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectResidence.tsx
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectResidence.test.ts
  ts/features/bonus/cdc/store/actions/cdcBonusRequest.ts
  ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
  ts/features/bonus/cdc/types/CdcBonusRequest.ts
Labels: Carta della cultura

#3967 chore(Carta della cultura): [AP-33] Update cdc swagger
  assets/CdcSwagger.yml
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
  ts/features/bonus/cdc/components/__test__/CdcServiceCTA.test.ts
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectYear.tsx
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectYear.test.ts
  ts/features/bonus/cdc/store/reducers/__test__/cdcBonusRequest.test.ts
  ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
Labels: Carta della cultura

#3965 chore(Carta della cultura): [AP-27] Update url path
  ts/features/bonus/cdc/api/backendCdc.ts
  ts/features/bonus/cdc/components/CdcRequestPartiallySuccess.tsx
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
Labels: Carta della cultura

#3970 chore(Carta della cultura): [AP-34] Update cdc bonus description screen
  ts/features/bonus/bonusVacanze/store/reducers/availableBonusesTypes.ts
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
  ts/features/bonus/cdc/components/__test__/CdcServiceCTA.test.ts
  ts/features/bonus/cdc/screens/CdcBonusRequestInformationTos.tsx
  ts/features/wallet/component/card/FeaturedCardCarousel.tsx
Labels: Carta della cultura

#3966 chore(Carta della cultura): [AP-14] Cdc monitoring
  ts/features/bonus/cdc/analytics/index.ts
  ts/features/bonus/cdc/analytics/placeholder
  ts/store/middlewares/analytics.ts
Labels: legal-approved ⚖️ ✅, Carta della cultura

#3984 chore(Piattaforma Notifiche): [IAMVL-80] Fix scope of IAMVL project in danger bot
  scripts/ts/danger/utils/changelog.ts
Labels: Piattaforma Notifiche

#3983 feat(Piattaforma Notifiche): [IAMVL-76] Add the local feature flag for PN
  .env.local
  .env.production
  ts/config.ts
Labels: Piattaforma Notifiche

#3977 chore: [IA-867] Add monitoring events for the Poste Data Matrix
  ts/screens/wallet/payment/ScanQrCodeScreen.tsx
Labels: legal-approved ⚖️ ✅
