Repository pagopa/io-app, pull requests merged in 2023-12, with the labels that each got.

#5275 chore(IT Wallet): [SIW-658] Remove legacy components
  ts/components/screens/BaseHeader.tsx
  ts/features/it-wallet/components/ItwFooterInfoBox.tsx
  ts/features/it-wallet/components/ItwLoadingSpinner.tsx
  ts/features/it-wallet/components/ItwLoadingSpinnerOverlay.tsx
  ts/features/it-wallet/components/__tests__/ItwLoadingSpinner.test.tsx
  ts/features/it-wallet/components/design/BadgeButton.tsx
  ts/features/it-wallet/components/design/NewH3.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/presentation/ItwPrProximityQrCodeScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrCredentialDataScreen.tsx
Labels: IT Wallet

#5277 chore(IT Wallet): [SIW-605] Rename remaning screens with new schema
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwIssuingCredentialAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwIssuingCredentialCatalogScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwIssuingCredentialChecksScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwIssuingCredentialPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwIssuingPidAddingScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwIssuingPidAuthInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwIssuingPidAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwIssuingPidInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwIssuingPidRequestScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrRemoteCredentialChecksScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrRemoteCredentialDataScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrRemoteCredentialResultScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrRemotePidChecksScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrRemotePidDataScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrRemotePidResultScreen.tsx
Labels: IT Wallet

#5258 fix(IT Wallet): [SIW-483] Presentation with disabled wallet
  locales/en/index.yml
  locales/it/index.yml
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/it-wallet/saga/itwRpInitializationSaga.ts
  ts/features/it-wallet/saga/new/itwPresentationSaga.ts
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrRemoteCredentialChecksScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrRemotePidChecksScreen.tsx
  ts/features/it-wallet/utils/itwErrorsUtils.ts
Labels: IT Wallet

#5290 chore(IT Wallet): [SIW-727] Reset wallet migration
  ts/features/it-wallet/store/reducers/index.ts
Labels: IT Wallet

#5283 chore(IT Wallet): [SIW-716] Add issued by claim for PID
  ts/features/it-wallet/components/ItwPidClaimsList.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/presentation/ItwPrPidDetails.tsx
  ts/features/it-wallet/utils/pid.ts
  ts/features/it-wallet/utils/types.ts
Labels: IT Wallet

#5300 fix(IT Wallet): [SIW-730] Fix credential issuance error not shown
  ts/features/it-wallet/saga/new/itwIssuanceSaga.ts
Labels: IT Wallet

#5301 chore(IT Wallet): [SIW-722] Reintroduce CIE login bypass
  ts/features/it-wallet/components/ItwContinueView.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwIssuingPidAuthInfoScreen.tsx
Labels: IT Wallet

#5304 chore(IT Wallet): [SIW-739] Fix error in check organization EN locale
  locales/en/index.yml
Labels: IT Wallet

#5305 chore(IT Wallet): [SIW-738] Enable Zendesk FF in production
  .env.production
Labels: IT Wallet

#5303 chore(IT Wallet): [SIW-737] Update io-react-native-jwt library to 1.1.0
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IT Wallet

#5256 fix: [IABT-1502] Force light mode on iOS
  ios/ItaliaApp/Info.plist
Labels: Dark mode 🌝

#5292 feat: [IOCOM-689] Move Third Part Data retrieval before Message Details screen
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/components/messages/MessageDetail/index.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/messages/actions/index.ts
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/messages/saga/handleLoadMessageData.ts
  ts/features/messages/saga/index.ts
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/navigation/actions.ts
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/navigation/MessagesNavigator.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
  ts/screens/messages/MessageDetailScreen.tsx
  ts/screens/messages/MessageRouterScreen.tsx
  ts/screens/messages/__tests__/MessageRouterScreen.test.tsx
  ts/screens/messages/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/store/actions/messages.ts
  ts/store/reducers/entities/messages/__tests__/messageGetStatus.test.ts
  ts/store/reducers/entities/messages/detailsById.ts
  ts/store/reducers/entities/messages/index.ts
  ts/store/reducers/entities/messages/messageGetStatus.ts
  ts/store/reducers/entities/services/servicesById.ts
Labels: IO-Comunicazione

#5294 feat: [IOCOM-699] Add remote content banner
  locales/en/index.yml
  locales/it/index.yml
  ts/components/SectionStatus/StatusContent.tsx
  ts/components/SectionStatus/__tests__/SectionStatusContent.test.tsx
  ts/components/SectionStatus/index.tsx
  ts/components/core/typography/Label.tsx
  ts/components/messages/MessageDetail/common/RemoteContentBanner.tsx
  ts/components/messages/MessageDetail/index.tsx
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
  ts/features/design-system/core/DSAlert.tsx
  ts/features/pn/components/MessageDetails.tsx
  ts/screens/wallet/payment/components/TransactionSummaryStatus.tsx
Labels: IO-Comunicazione

#5299 feat: [IOCOM-690] Move third party data request into its saga for SEND messages
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/messages/saga/handleLoadMessageData.ts
  ts/features/pn/components/MessageDetailsError.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
Labels: IO-Comunicazione

#5298 feat: [IOCOM-698] Add bottom sheet to `RemoteContentBanner` component
  locales/en/index.yml
  locales/it/index.yml
  ts/components/messages/MessageDetail/common/RemoteContentBanner.tsx
Labels: IO-Comunicazione

#5308 feat: [IOCOM-692] Tech analytics events for remote content messages
  ts/features/messages/actions/index.ts
  ts/features/messages/analytics/index.ts
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/messages/saga/handleLoadMessageData.ts
  ts/features/messages/store/actions/index.ts
  ts/sagas/messages/watchThirdPartyMessageSaga.ts
  ts/screens/messages/MessageRouterScreen.tsx
  ts/screens/messages/__tests__/MessageRouterScreen.test.tsx
  ts/store/reducers/entities/messages/__tests__/messageGetStatus.test.ts
  ts/store/reducers/entities/messages/__tests__/thirdPartyById.test.ts
  ts/store/reducers/entities/messages/thirdPartyById.ts
Labels: legal-approved ⚖️ ✅, IO-Comunicazione

#4924 chore: [IOPID-503] Mixpanel events LV
  ts/components/HorizontalScroll.tsx
  ts/components/NewRemindEmailValidationOverlay.tsx
  ts/components/PinCreationForm.tsx
  ts/components/PinSelectionComponent.tsx
  ts/components/__tests__/NewRemindEmailValidationOverlay.test.tsx
  ts/components/__tests__/PinCreationForm.test.tsx
  ts/features/fastLogin/analytics/index.ts
  ts/features/fastLogin/analytics/optinAnalytics.ts
  ts/features/whatsnew/analytics/index.ts
  ts/navigation/OnboardingNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/OnboardingParamsList.ts
  ts/navigation/params/ProfileParamsList.ts
  ts/sagas/startup/__tests__/authenticationSaga.test.ts
  ts/sagas/startup/authenticationSaga.ts
  ts/sagas/startup/watchAbortOnboardingSaga.ts
  ts/screens/analytics/emailAnalytics.ts
  ts/screens/authentication/IdpSelectionScreen.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/NewOptInScreen.tsx
  ts/screens/authentication/analytics/carouselAnalytics.ts
  ts/screens/authentication/analytics/cieAnalytics.ts
  ts/screens/authentication/analytics/index.ts
  ts/screens/authentication/analytics/spidAnalytics.ts
  ts/screens/authentication/cie/CieCardReaderScreen.tsx
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  ts/screens/modal/RootModal.tsx
  ts/screens/modal/RootedDeviceModal.tsx
  ts/screens/modal/UpdateAppModal.tsx
  ts/screens/modal/analytics/index.ts
  ts/screens/onboarding/OnboardingCompletedScreen.tsx
  ts/screens/onboarding/OnboardingEmailInsertScreen.tsx
  ts/screens/onboarding/OnboardingNotificationsPreferencesScreen.tsx
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/onboarding/OnboardingShareDataScreen.tsx
  ts/screens/onboarding/OnboardingTosScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/FingerprintScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/MissingDeviceBiometricScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/MissingDevicePinScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/analytics/index.ts
  ts/screens/profile/CduEmailInsertScreen.tsx
  ts/screens/profile/EmailInsertScreen.tsx
  ts/screens/profile/NotificationsPreferencesScreen.tsx
  ts/screens/profile/SecurityScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/screens/profile/ShareDataScreen.tsx
  ts/screens/profile/TosScreen.tsx
  ts/screens/profile/analytics/index.ts
  ts/screens/profile/analytics/mixpanel/mixpanelAnalytics.ts
  ts/screens/profile/mailCheck/EmailAlreadyTakenScreen.tsx
  ts/screens/profile/mailCheck/ValidateEmailScreen.tsx
  ts/store/middlewares/analytics.ts
  ts/utils/analytics.ts
  ts/utils/login.ts
Labels: IO-A&I

#5306 chore: [IOPID-1165] Mixpanel super and profile properties upgrade
  ts/features/fastLogin/analytics/optinAnalytics.ts
  ts/features/fastLogin/store/selectors/index.ts
  ts/mixpanel.ts
  ts/mixpanelConfig/mixpanelPropertyUtils.ts
  ts/mixpanelConfig/profileProperties.ts
  ts/mixpanelConfig/superProperties.ts
  ts/sagas/mixpanel.ts
  ts/sagas/profile.ts
  ts/screens/authentication/IdpSelectionScreen.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/NewOptInScreen.tsx
  ts/screens/authentication/analytics/index.ts
  ts/screens/authentication/analytics/spidAnalytics.ts
  ts/screens/onboarding/OnboardingNotificationsPreferencesScreen.tsx
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/onboarding/OnboardingTosScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/screens/profile/analytics/index.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/profile.ts
Labels: IO-A&I

#5312 feat: [IOBP-453] Addition of barcode regeneration screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/barcode/components/BarcodeExpirationProgressBar.tsx
  ts/features/idpay/barcode/screens/IdPayBarcodeResultScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5318 feat: [IOCOM-717] Update error message in the `MessageRouterScreen`
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/GenericErrorComponent.tsx
  ts/sagas/messages/watchThirdPartyMessageSaga.ts
  ts/screens/messages/MessageRouterScreen.tsx
  ts/screens/messages/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
  ts/store/reducers/entities/messages/messageGetStatus.ts
Labels: IO-Comunicazione

#5280 chore: [IOAPPFD0-196] Add `LargeHeader` header style to Privacy Policy main screen (Profile)
  ts/components/ui/RNavScreenWithLargeHeader.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/screens/profile/PrivacyMainScreen.tsx
Labels: enhancement

#5224 chore: [IOBP-404] Update ID Pay API definitions for new exceptions
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/screens/OperationResultScreenContent.tsx
  ts/components/screens/__tests__/OperationResultScreenContent.test.tsx
  ts/features/idpay/onboarding/screens/FailureScreen.tsx
  ts/features/idpay/onboarding/types/OnboardingFailure.ts
  ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts
  ts/features/idpay/onboarding/xstate/__tests__/services.test.ts
  ts/features/idpay/onboarding/xstate/machine.ts
  ts/features/idpay/onboarding/xstate/services.ts
  ts/features/idpay/payment/screens/IDPayPaymentResultScreen.tsx
  ts/features/idpay/payment/screens/__tests__/IDPayPaymentResultScreen.test.tsx
  ts/features/idpay/payment/types/PaymentFailure.ts
  ts/features/idpay/payment/xstate/__tests__/machine.test.ts
  ts/features/idpay/payment/xstate/__tests__/services.test.ts
  ts/features/idpay/payment/xstate/context.ts
  ts/features/idpay/payment/xstate/machine.ts
  ts/features/idpay/payment/xstate/services.ts
  ts/screens/profile/playgrounds/IdPayOnboardingPlayground.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5269 feat: [IOBP-421] Added additional outcome screen for already added methods
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/onboarding/types/index.ts
  ts/features/walletV3/onboarding/utils/index.ts
Labels: IO-Bonus e pagamenti

#5320 fix: [IOBP-444,IOBP-445] Update `rn-qr-generator` to 1.4.0
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IO-Bonus e pagamenti

#5325 chore: [IOAPPFD0-199] Refactor Profile main screen using `ListItemNav` and `FlatList`
  ts/screens/profile/ProfileMainScreen.tsx
Labels: enhancement, NativeBase dismissal 🥷🏼

#5288 chore: [IOPID-1181] Add email uniqueness validation FF
  package.json
  ts/components/helpers/withValidatedEmail.tsx
  ts/features/fastLogin/store/selectors/__tests__/emailUniquenessValidation.test.ts
  ts/features/fastLogin/store/selectors/index.ts
  ts/navigation/OnboardingNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/sagas/startup/__tests__/checkProfileEmailSaga.test.tsx
  ts/sagas/startup/checkAcknowledgedEmailSaga.ts
  ts/sagas/startup/checkEmailSaga.ts
  ts/screens/profile/CduEmailInsertScreen.tsx
  ts/screens/profile/ProfileDataScreen.tsx
Labels: IO-A&I

#5330 chore: [IOBP-176] Add new pictograms in ID Pay onboarding failure screen
  package.json
  ts/features/idpay/onboarding/screens/FailureScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentResultScreen.tsx
  yarn.lock
Labels: IDPay, IO-Bonus e pagamenti

#5297 chore: [IOPID-1186] Add bottomsheet logic for security suggestion acknowledged
  locales/en/index.yml
  locales/it/index.yml
  ts/components/FiscalCodeComponent.tsx
  ts/features/fastLogin/components/SecuritySuggestions.tsx
  ts/features/fastLogin/store/actions/index.ts
  ts/features/fastLogin/store/actions/securityAdviceActions.ts
  ts/features/fastLogin/store/reducers/index.ts
  ts/features/fastLogin/store/reducers/optInReducer.ts
  ts/features/fastLogin/store/reducers/securityAdviceReducer.ts
  ts/features/fastLogin/store/selectors/index.ts
  ts/hooks/useSecuritySuggestionBottomSheet.tsx
  ts/sagas/__tests__/profile.test.ts
  ts/sagas/profile.ts
  ts/sagas/startup.ts
  ts/screens/authentication/NewOptInScreen.tsx
  ts/screens/authentication/__tests__/NewOptInScreen.test.tsx
  ts/screens/messages/MessagesHomeScreen.tsx
  ts/screens/onboarding/UnlockAccessScreen.tsx
  ts/store/actions/crossSessions.ts
  ts/store/reducers/index.ts
  ts/utils/analytics.ts
Labels: IO-A&I

#5336 fix: [IOCOM-737] Update the display rule of the RemoteContentBanner component
  package.json
  ts/components/messages/MessageDetail/index.tsx
  ts/store/reducers/entities/messages/transformers.ts
  ts/store/reducers/entities/messages/types.ts
Labels: IO-Comunicazione

#5315 feat(IT Wallet): [SIW-681] Health card issuance
  ts/features/it-wallet/assets/img/credentials/cards/europeanHealthInsuranceCardFront.png
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#5323 feat(IT Wallet): [SIW-729] Add mobile driving license issuing
  ts/features/it-wallet/saga/new/itwIssuanceSaga.ts
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#5338 fix: [IOPID-1257] Fix: no-mail user onboarding
  locales/en/index.yml
  locales/it/index.yml
  ts/sagas/startup.ts
  ts/sagas/startup/checkAcknowledgedEmailSaga.ts
Labels: IO-A&I

#5341 feat: [IOCOM-740] Update `tosVersion` to 4.7
  ts/config.ts
Labels: IO-Comunicazione

#5335 fix: [IOCOM-736] Message retrieval fix for fast login
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/features/messages/saga/handleLoadMessageData.ts
  ts/features/messages/saga/index.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
  ts/screens/messages/__tests__/MessageRouterScreen.test.tsx
  ts/store/reducers/entities/messages/__tests__/messageGetStatus.test.ts
  ts/store/reducers/entities/messages/messageGetStatus.ts
Labels: IO-Comunicazione

#5291 feat: [IOBP-442] New wallet payment details screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/barcode/screens/WalletBarcodeScanScreen.tsx
  ts/features/walletV3/payment/navigation/navigator.tsx
  ts/features/walletV3/payment/screens/WalletPaymentDetailScreen.tsx
  ts/screens/profile/playgrounds/WalletPlayground.tsx
Labels: IO-Bonus e pagamenti

#5310 chore(IT Wallet): [SIW-722] Add verifyAndParseCredential phase to credential issuing
  package.json
  ts/features/it-wallet/components/ItwCredentialCard.tsx
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
  ts/features/it-wallet/saga/new/itwIssuanceSaga.ts
  ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts
  ts/features/it-wallet/utils/pid.ts
  ts/features/it-wallet/utils/types.ts
  yarn.lock
Labels: IT Wallet

#5321 chore(IT Wallet): [SIW-740] Refactor claims list
  ios/Podfile.lock
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ItwCredentialClaim.tsx
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
  ts/features/it-wallet/utils/__tests__/itwClaimsUtilsTest.ts
  ts/features/it-wallet/utils/itwClaimsUtils.ts
  ts/features/it-wallet/utils/locales.ts
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#5349 chore: [IOBP-457] Old wallet LV integration
  ts/sagas/wallet/pagopaApis.ts
Labels: IO-Bonus e pagamenti

#5351 fix: [IOPID-1267] Chore: fix toast
  ts/screens/profile/CduEmailInsertScreen.tsx
Labels: IO-A&I

#5352 chore(IT Wallet): [SIW-772] Add `BLE` permissions for `iOS` and `Android`
  android/app/src/main/AndroidManifest.xml
  ios/ItaliaApp/Info.plist
  ios/ItaliaApp/it.lproj/InfoPlist.strings
Labels: IT Wallet

#5353 chore: [IOPID-1182] Chore: enable all FL related local FF in production
  .env.production
Labels: IO-A&I

#5354 chore(IT Wallet): [SIW-773] Add patch to `cipher-base` package
  patches/cipher-base+1.0.4.patch
Labels: IT Wallet

#5359 chore(IT Wallet): [SIW-778] Add actions and reducer for proximity flow
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/actions/itwProximityActions.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwProximityReducer.ts
Labels: IT Wallet

#5360 fix(IT Wallet): [SIW-779,SIW-781] Add proximity saga
  jest.config.js
  jestSetup.js
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/saga/itwProximitySaga.ts
  ts/features/it-wallet/store/actions/itwProximityActions.ts
  ts/features/it-wallet/store/reducers/itwProximityReducer.ts
  ts/features/it-wallet/utils/itwErrorsUtils.ts
Labels: IT Wallet

#5361 chore(IT Wallet): [SIW-780] Update `ItwPrProximityQrCodeScreen` with proximity saga
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/it-wallet/saga/itwProximitySaga.ts
  ts/features/it-wallet/screens/presentation/ItwPrProximityQrCodeScreen.tsx
  ts/features/it-wallet/store/actions/itwProximityActions.ts
  ts/features/it-wallet/utils/mocks.ts
  yarn.lock
Labels: IT Wallet
