Repository pagopa/io-app, pull requests merged in 2023-07, with the labels that each got.

#4724 feat(IT Wallet): [SIW-206,SIW-217] Add new tab navigator
  locales/en/index.yml
  locales/it/index.yml
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/IconMultiCoggles.tsx
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/components/screens/TopScreenComponent.tsx
  ts/features/it-wallet/screens/NotAvailableScreen.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/params/MainTabParamsList.ts
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/messages/MessagesHomeScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: IT Wallet

#4714 feat(IT Wallet): [SIW-182] Update app icon
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-1024.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-120.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-152.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-167.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-180.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-20.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-29.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-40.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-58.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-60.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-76.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-80.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/icon-87.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-1024.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-30.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-57.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-57@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-60@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-60@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-76.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-76@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-83.5@2x.png
Labels: IT Wallet

#4735 feat(IT Wallet): [SIW-251] Init itw main saga and activation base screen
  ts/features/it-wallet/components/ItwActionBanner.tsx
  ts/features/it-wallet/navigation/.placeholder
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/navigation/routes.ts
  ts/features/it-wallet/saga/.placeholder
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/screens/.placeholder
  ts/features/it-wallet/screens/ItwActivationDetailsScreen.tsx
  ts/features/it-wallet/store/.placeholder
  ts/features/it-wallet/store/actions/index.ts
  ts/sagas/startup.ts
Labels: IT Wallet

#4727 feat(IT Wallet): [SIW-206,SIW-248] Refactor base header
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/components/screens/TopScreenComponent.tsx
  ts/components/search/SearchButton.tsx
  ts/features/it-wallet/components/design/NewH3.tsx
  ts/screens/messages/MessagesHomeScreen.tsx
Labels: IT Wallet

#4683 chore: [IOAPPFD0-114] Add screen archetypes for testing purposes
  ts/components/VersionInfoOverlay.tsx
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/core/DSEdgeToEdgeArea.tsx
  ts/features/design-system/core/DSSafeArea.tsx
  ts/features/design-system/core/DSSafeAreaCentered.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
Labels: Design System

#4710 chore: [IOBP-74] Transaction list item redesign
  locales/en/index.yml
  locales/it/index.yml
  ts/components/core/Badge.tsx
  ts/components/ui/ListItemTransaction.tsx
  ts/components/ui/baseComponents/PressableListItemBase.tsx
  ts/components/ui/hooks/useListItemSpringAnimation.ts
  ts/features/design-system/core/DSListItems.tsx
Labels: Design System

#4725 chore: [IOAPPFD0-118] Add the new `ListItemIDP` component
  ts/components/IdpsGridRevamp.tsx
  ts/components/core/variables/IOShapes.ts
  ts/components/core/variables/IOSpacing.ts
  ts/components/ui/ListItemIDP.tsx
  ts/features/design-system/core/DSListItems.tsx
Labels: Design System

#4738 feat(IT Wallet): [SIW-258] Fix iOS build
  ios/Gemfile
  ios/Gemfile.lock
Labels: IT Wallet

#4736 feat(IT Wallet): [SIW-253] Fix Android build
  android/app/BUCK
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/MainActivity.java
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/MainApplication.java
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  mock-google-services.json
Labels: IT Wallet

#4737 chore: [IOBP-77] Remove entry point of PagoBANCOMAT flow
  ts/screens/wallet/AddPaymentMethodScreen.tsx
Labels: IO-B&P

#4741 feat(IT Wallet): [SIW-252] Add activation screen
  img/features/it-wallet/wallet-cards.png
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ItwTos.tsx
  ts/features/it-wallet/screens/ItwActivationDetailsScreen.tsx
Labels: IT Wallet

#4746 fix: [IOPID-377] iOS crash while reading CIE with NFC
  ts/components/cie/CieNotSupported.tsx
  ts/components/cie/CieRequestAuthenticationOverlay.tsx
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
Labels: IO-A&I

#4742 feat: [IOCOM-345] Updated header for FIMS screen
  ts/features/fims/components/WebviewErrorComponent.tsx
  ts/features/fims/screens/FimsWebviewScreen.tsx
Labels: IO-Comunicazione

#4750 feat(IT Wallet): [SIW-268] Update applicationId to fix Android deployment
  android/app/proguard-rules.pro
  android/app/src/debug/java/it/pagopa/io/app/poc/itwallet/ReactNativeFlipper.java
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/MainApplication.java
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/it/pagopa/io/app/poc/itwallet/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/fastlane/Appfile
Labels: IT Wallet

#4747 feat(IT Wallet): [SIW-221] Add home screen scaffold
  locales/en/index.yml
  locales/it/index.yml
  ts/components/messages/MessagesInbox.tsx
  ts/features/it-wallet/components/ItwActionBanner.tsx
  ts/features/it-wallet/components/design/BadgeButton.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/navigation/TabNavigator.tsx
Labels: IT Wallet

#4751 chore: [IOAPPFD0-123] Update payment logos
  ts/components/core/logos/svg/LogoPaymentExtMaestro.tsx
  ts/components/core/logos/svg/LogoPaymentExtMastercard.tsx
  ts/components/core/logos/svg/LogoPaymentExtPayPal.tsx
  ts/components/core/logos/svg/LogoPaymentMaestro.tsx
  ts/components/core/logos/svg/LogoPaymentMastercard.tsx
  ts/components/core/logos/svg/LogoPaymentPayPal.tsx
  ts/components/core/logos/svg/originals/LogoPaymentExtMaestro.svg
  ts/components/core/logos/svg/originals/LogoPaymentExtMastercard.svg
  ts/components/core/logos/svg/originals/LogoPaymentExtPayPal.svg
  ts/components/core/logos/svg/originals/LogoPaymentMaestro.svg
  ts/components/core/logos/svg/originals/LogoPaymentMastercard.svg
  ts/components/core/logos/svg/originals/LogoPaymentPayPal.svg
Labels: Design System

#4744 feat: [IOCOM-346] Handling of setTitle event emitted by the FIMS WebView
  ts/features/fims/components/FimsWebView.tsx
  ts/features/fims/screens/FimsWebviewScreen.tsx
  ts/types/WebviewMessage.ts
  ts/types/__tests__/webviewMessage.test.ts
  ts/utils/webview.ts
Labels: IO-Comunicazione

#4749 feat: [IOCOM-347] Handling of events emitted by the FIMS WebView
  ts/features/fims/components/CommonContent.tsx
  ts/features/fims/components/ErrorContent.tsx
  ts/features/fims/components/FimsWebView.tsx
  ts/features/fims/components/SuccessContent.tsx
  ts/types/WebviewMessage.ts
  ts/types/__tests__/webviewMessage.test.ts
  ts/utils/webview.ts
Labels: IO-Comunicazione

#4743 chore: [IOBP-101] Remove co-badge cards entry points
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/wallet/AddCardScreen.tsx
Labels: IO-B&P

#4754 fix: [IOPID-388] Shared data security info URL is broken
  ts/screens/profile/components/ShareDataComponent.tsx
Labels: IO-A&I

#4753 chore(IT Wallet): [SIW-270] Bypass version supported
  ts/screens/modal/RootModal.tsx
  ts/utils/appVersion.ts
Labels: IT Wallet

#4755 fix: [IOPID-389] Clear session cookies at CIE login start on Android
  ts/components/cie/CieRequestAuthenticationOverlay.tsx
Labels: IO-A&I

#4748 chore: [IOAPPFD0-122] Remove legacy icons from the main header
  ts/components/ChooserListContainer.tsx
  ts/components/ContextualInfo.tsx
  ts/components/GoBackButton.tsx
  ts/components/RemindEmailValidationOverlay.tsx
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/LegIconChevronLeft.tsx
  ts/components/core/icons/svg/LegIconSearch.tsx
  ts/components/core/icons/svg/originals/LegIconChevronLeft.svg
  ts/components/core/icons/svg/originals/LegIconSearch.svg
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/TopScreenComponent.tsx
  ts/components/search/SearchButton.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
  ts/features/fci/components/DocumentWithSignature.tsx
  ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
  ts/features/fims/screens/FimsWebviewScreen.tsx
  ts/features/idpay/initiative/details/components/InitiativeDetailsBaseScreenComponent.tsx
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/InitiativeDetailsBaseScreenComponent.test.tsx.snap
  ts/features/idpay/unsubscription/screens/UnsubscriptionConfirmationScreen.tsx
  ts/screens/profile/FiscalCodeScreen.tsx
  ts/theme/components/Header.ts
Labels: Design System

#4731 feat: [IOPID-316] FL Refinement
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fastLogin/actions/index.ts
  ts/features/fastLogin/saga/pendingActionsSaga.ts
  ts/features/fastLogin/saga/tokenRefreshSaga.ts
  ts/features/fastLogin/saga/utils/index.ts
  ts/features/fastLogin/screens/AskUserInterarctionScreen.tsx
  ts/features/fastLogin/screens/RefreshTokenLoadingScreen.tsx
  ts/features/fastLogin/screens/__tests__/AskUserToContinueScreen.test.tsx
  ts/features/fastLogin/store/actions/index.ts
  ts/features/fastLogin/store/reducers/index.ts
  ts/features/fastLogin/store/selectors/index.ts
  ts/features/lollipop/utils/fetch.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/identification.ts
  ts/sagas/index.ts
  ts/sagas/startup.ts
  ts/screens/modal/RootModal.tsx
  ts/store/actions/application.ts
  ts/store/actions/authentication.ts
  ts/store/actions/types.ts
  ts/store/reducers/authentication.ts
Labels: IO-A&I

#4756 chore: [IOAPPFD0-124] Add fullscreen modal presentation screen
  ts/components/core/variables/IOStyles.ts
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/components/DesignSystemScreen.tsx
  ts/features/design-system/core/DSBadges.tsx
  ts/features/design-system/core/DSColors.tsx
  ts/features/design-system/core/DSFullScreenModal.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
Labels: Design System

#4764 feat(IT Wallet): [SIW-209,SIW-255] Cie pid issuing
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/cie/CieNfcOverlay.tsx
  ts/features/it-wallet/components/cie/CieReadingCardAnimation.tsx
  ts/features/it-wallet/components/cie/CieRequestAuthenticationOverlay.tsx
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/navigation/routes.ts
  ts/features/it-wallet/saga/__tests__/handleRequirementsCheck.ts
  ts/features/it-wallet/saga/authenticationSaga.ts
  ts/features/it-wallet/saga/cie.ts
  ts/features/it-wallet/saga/handleRequirementsCheck.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieCardReaderScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieConsentDataUsageScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieExpiredOrInvalidScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CiePinLockedTemporarilyScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CiePinScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieWrongCiePinScreen.tsx
  ts/features/it-wallet/store/actions/cie.ts
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/reducers/cie.ts
  ts/features/it-wallet/store/reducers/index.ts
Labels: IT Wallet

#4763 chore: [IOPID-417] Disable getNonce in production (not yet implemented)
  .env.local
  .env.production
  ts/config.ts
  ts/features/fastLogin/saga/tokenRefreshSaga.ts
Labels: IO-A&I

#4766 chore: [IOBP-121] CGN Card bottom white border glitch
  ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx
Labels: Carta Giovani Nazionale

#4779 fix: [IOPID-422,IOPID-435] First onboarding bug/FastLogin what's new
  ts/components/IdpsGrid.tsx
  ts/features/bonus/bpd/screens/details/components/summary/__test__/bpdSummaryComponent.test.tsx
  ts/features/bonus/bpd/screens/details/components/summary/__test__/rankingNotReady.test.tsx
  ts/features/bonus/cgn/components/detail/eyca/__test__/EycaDetailComponent.test.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/PspRadioItem.test.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PspRadioItem.test.tsx.snap
  ts/features/whatsnew/hook/useWhatsNew.tsx
  ts/features/whatsnew/screen/FastLoginWhatsNew.tsx
  ts/features/whatsnew/store/reducers/index.ts
  ts/features/whatsnew/versions.ts
  ts/sagas/startup.ts
  ts/screens/authentication/IdpSelectionScreen.tsx
  ts/utils/hooks/bottomSheet.tsx
Labels: IO-A&I

#4773 feat(IT Wallet): [SIW-281] Animated loading spinner overlay
  ts/features/it-wallet/components/ItwLoadingSpinner.tsx
  ts/features/it-wallet/components/ItwLoadingSpinnerOverlay.tsx
  ts/features/it-wallet/components/__tests__/ItwLoadingSpinner.test.tsx
Labels: IT Wallet

#4775 feat(IT Wallet): [SIW-213] Add issuing thank you page screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ItwActionCompleted.tsx
  ts/features/it-wallet/components/ItwLoadingSpinner.tsx
  ts/features/it-wallet/components/__tests__/ItwActionCompleted.test.tsx
  ts/features/it-wallet/components/__tests__/__snapshots__/ItwActionCompleted.test.tsx.snap
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/navigation/routes.ts
  ts/features/it-wallet/screens/issuing/ItwActivationTypScreen.tsx
Labels: IT Wallet

#4778 chore: [IOBP-123] New list item transaction into IDPay timeline
  locales/en/index.yml
  locales/it/index.yml
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/IconCheckTic.tsx
  ts/components/core/icons/svg/IconMerchant.tsx
  ts/components/core/icons/svg/originals/IconCheckTic.svg
  ts/components/core/icons/svg/originals/IconMerchant.svg
  ts/components/ui/ListItemTransaction.tsx
  ts/features/idpay/initiative/details/components/InitiativeTimelineComponent.tsx
  ts/features/idpay/initiative/details/components/TimelineOperationListItem.tsx
  ts/features/idpay/initiative/details/screens/OperationsListScreen.tsx
Labels: IO-B&P

#4786 feat(IT Wallet): [SIW-211] Add PID preview and addition
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/configureStoreAndPersistor.ts
  ts/components/messages/MessagesInbox.tsx
  ts/features/common/store/reducers/index.ts
  ts/features/it-wallet/assets/img/pidCard/pidCardFront.png
  ts/features/it-wallet/components/ClaimsList.tsx
  ts/features/it-wallet/components/PidCredential.tsx
  ts/features/it-wallet/hooks/.placeholder
  ts/features/it-wallet/hooks/useItwAbortFlow.tsx
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/navigation/routes.ts
  ts/features/it-wallet/saga/handleCredentials.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwActivationTypScreen.tsx
  ts/features/it-wallet/screens/issuing/PidActivationScreen.tsx
  ts/features/it-wallet/screens/issuing/PidPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieConsentDataUsageScreen.tsx
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwCredentials.ts
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#4788 chore: [IOPID-417] Enable FL production FF"
  .env.production
Labels: IO-A&I

#4767 feat: [IOBP-119] Add global barcode scan screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/barcode/components/BarcodeCameraMarker.tsx
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
  ts/features/barcode/components/BottomTabNavigation.tsx
  ts/features/barcode/components/CameraPermissionView.tsx
  ts/features/barcode/components/__tests__/BarcodeScanBaseScreenComponent.test.tsx
  ts/features/barcode/hooks/__tests__/useIOBarcodeScanner.test.tsx
  ts/features/barcode/hooks/useIOBarcodeFileReader.tsx
  ts/features/barcode/hooks/useIOBarcodeScanner.tsx
  ts/features/barcode/index.ts
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/barcode/types/IOBarcode.ts
  ts/features/barcode/types/__tests__/decoders.test.ts
  ts/features/barcode/types/decoders.ts
  ts/features/barcode/types/failure.ts
  ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
  ts/features/idpay/payment/components/Barcode/index.ts
  ts/features/idpay/payment/navigation/navigator.tsx
  ts/features/idpay/payment/screens/IDPayPaymentCodeInputScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentCodeScanScreen.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/navigation/routes.ts
Labels: IO-B&P

#4789 feat: [IOCOM-363] Add Mixpanel PN events
  .env.local
  .env.production
  package.json
  ts/boot/configurePushNotification.ts
  ts/components/cta/ExtractedCTABar.tsx
  ts/components/messages/MessageDetail/common/CtaBar.tsx
  ts/components/services/ContactPreferencesToggles/index.tsx
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/config.ts
  ts/features/messages/analytics/index.ts
  ts/features/messages/hooks/useAttachmentDownload.tsx
  ts/features/messages/hooks/useMessageOpening.tsx
  ts/features/pn/analytics/index.ts
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnServiceCTA.tsx
  ts/features/pn/screens/PnAttachmentPreview.tsx
  ts/features/pn/screens/PnMessageDetailsScreen.tsx
  ts/features/pn/utils/__tests__/index.test.ts
  ts/features/pn/utils/index.ts
  ts/sagas/messages/__tests__/watchMessagePrecondition.test.ts
  ts/sagas/messages/watchMessagePrecondition.ts
  ts/screens/messages/MessageRouterScreen.tsx
  ts/screens/profile/playgrounds/MarkdownPlayground.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
  ts/store/actions/messages.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/entities/messages/__tests__/messagePrecondition.test.ts
  ts/store/reducers/entities/messages/messagePrecondition.ts
  ts/utils/__tests__/analytics.test.ts
  ts/utils/__tests__/internalLink.test.ts
  ts/utils/__tests__/messages.test.ts
  ts/utils/analytics.ts
  ts/utils/internalLink.ts
  ts/utils/messages.ts
Labels: dont-merge :raised_hand:, legal-approved ⚖️ ✅, IO-Comunicazione

#4757 feat: [IOCOM-270] FIMS cookie clearing when leaving the FIMS webview
  ts/features/fims/screens/FimsWebviewScreen.tsx
  ts/utils/cookieManager.ts
Labels: IO-Comunicazione

#4794 fix: [IOPID-473] Fix CTA position in the `FingerprintScreen` component
  ts/screens/onboarding/FingerprintScreen.tsx
Labels: IO-A&I

#4796 fix: [IOPID-485] Fix nested `ScrollView` error in the `IdpSelectionScreen`
  ts/components/IdpsGrid.tsx
  ts/screens/authentication/IdpSelectionScreen.tsx
Labels: IO-A&I

#4790 feat(IT Wallet): [SIW-214] Add PID to wallet
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ClaimsList.tsx
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/navigation/routes.ts
  ts/features/it-wallet/screens/ItwCredentialDetails.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/issuing/PidPreviewScreen.tsx
  ts/features/it-wallet/store/reducers/itwCredentials.ts
Labels: IT Wallet

#4781 chore: [IOBP-111,IOBP-116] Addition of LogoPaymentHuge and usage in new Cards components
  img/wallet/payment-methods/bpay_logo_full.svg
  ts/components/ui/LogoPaymentExtended.tsx
  ts/components/ui/cards/payment/PaymentCardBig.tsx
  ts/components/ui/cards/payment/PaymentCardsCarousel.tsx
  ts/components/ui/cards/payment/__test__/__snapshots__/PaymentCards.test.tsx.snap
  ts/components/ui/utils/baseComponents/BankLogoOrLoadingSkeleton.tsx
  ts/components/ui/utils/generateFlatListItemLayout.ts
  ts/components/ui/utils/strings.ts
  ts/features/design-system/core/DSCards.tsx
  ts/features/design-system/core/DSLogos.tsx
Labels: Design System

#4798 feat: [IOBP-137] Add barcode scan camera marker animation
  img/camera-marker-corner.svg
  img/camera-marker-line.svg
  img/camera-scan-marker.svg
  ts/components/ui/utils/hooks/useSineWaveAnimation.ts
  ts/features/barcode/components/AnimatedCameraMarker.tsx
  ts/features/barcode/components/BarcodeCameraMarker.tsx
  ts/features/barcode/hooks/useIOBarcodeScanner.tsx
Labels: IO-B&P

#4801 chore: [IOAPPFD0-128] Add `action` prop to the `SwitchListItem`
  ts/components/core/variables/IOStyles.ts
  ts/components/ui/SwitchListItem.tsx
  ts/features/design-system/core/DSSelection.tsx
Labels: Design System

#4803 feat: [IOCOM-383] Add system icons
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/IconSystemAppsAndroid.tsx
  ts/components/core/icons/svg/IconSystemNotificationsInstructions.tsx
  ts/components/core/icons/svg/IconSystemSettingsAndroid.tsx
  ts/components/core/icons/svg/IconSystemSettingsiOS.tsx
  ts/components/core/icons/svg/IconSystemToggleInstructions.tsx
  ts/components/core/icons/svg/originals/IconSystemAppsAndroid.svg
  ts/components/core/icons/svg/originals/IconSystemNotificationsInstructions.svg
  ts/components/core/icons/svg/originals/IconSystemSettingsAndroid.svg
  ts/components/core/icons/svg/originals/IconSystemSettingsiOS.svg
  ts/components/core/icons/svg/originals/IconSystemToggleInstructions.svg
  ts/features/design-system/core/DSIcons.tsx
Labels: Design System, IO-Comunicazione

#4809 chore: [IOAPPFD0-129] Remove extra space from `ListItem…` components
  ts/components/core/variables/IOStyles.ts
  ts/components/ui/ListItemInfo.tsx
  ts/components/ui/ListItemInfoCopy.tsx
  ts/components/ui/ListItemNav.tsx
  ts/components/ui/ListItemNavAlert.tsx
  ts/components/ui/ListItemTransaction.tsx
Labels: Design System

#4813 chore(IT Wallet): [SIW-300] Add wallet reset
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/hooks/useItwResetFlow.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/reducers/itwCredentials.ts
Labels: IT Wallet

#4804 chore: Add bundleInDebug gradle parameter
  android/app/build.gradle
Labels: IO-A&I

#4811 fix(IT Wallet): [SIW-316] Refactor pid activation and preview screen
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/screens/issuing/ItwPidActivationScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
Labels: IT Wallet

#4799 feat: [IOPID-442,IOPID-443,IOPID-481,IOPID-482,IOPID-483,IOPID-484] FL follow up
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fastLogin/saga/tokenRefreshSaga.ts
  ts/features/fastLogin/saga/utils/index.ts
  ts/features/fastLogin/screens/RefreshTokenLoadingScreen.tsx
  ts/features/fastLogin/store/actions/index.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/index.ts
  ts/sagas/startup.ts
  ts/sagas/startup/watchApplicationActivitySaga.ts
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: IO-A&I

#4815 feat(IT Wallet): [SIW-319] Add profile button to main screens
  ts/components/screens/DarkLayout.tsx
  ts/components/wallet/WalletLayout.tsx
  ts/screens/services/ServicesHomeScreen.tsx
  ts/screens/wallet/WalletHomeScreen.tsx
Labels: IT Wallet

#4816 feat(IT Wallet): [SIW-321] Fix conventional commit scope in release scripts
  .github/workflows/release-it-wallet.yml
  package.json
Labels: IT Wallet

#4814 chore: [PE-442] Change CGN details text labels
  locales/en/index.yml
  locales/it/index.yml
Labels: Carta Giovani Nazionale

#4820 fix(IT Wallet): [SIW-322] Add vertical spacer in discovery screens
  ts/features/it-wallet/screens/discovery/ItwActivationDetailsScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
Labels: IT Wallet

#4819 feat(IT Wallet): [SIW-324] Add `io-react-native-wallet` package
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IT Wallet

#4826 fix: [IOBP-145] Fix navigation after IDPay transaction authorization
  ts/features/idpay/payment/xstate/actions.ts
Labels: IDPay, IO-Bonus e pagamenti

#4823 fix: [IOPID-498] Added function to set language on startup
  ts/sagas/preferences.ts
  ts/sagas/startup.ts
Labels: IO-A&I

#4829 chore: [IOPID-517] Fix what's new persistence
  ts/features/whatsnew/store/reducers/index.ts
Labels: IO-A&I

#4807 feat: [IOCOM-375] Add `android.permission.POST_NOTIFICATIONS` permission
  android/app/src/main/AndroidManifest.xml
  package.json
  patches/@types+react-native+0.69.6.patch
  patches/patches.md
  patches/react-native+0.69.9.patch
  yarn.lock
Labels: IO-Comunicazione

#4800 chore: [IOBP-140] Fix fruition and onboarding status dates in IDPay initiative details screen
  package.json
  ts/features/idpay/initiative/details/components/BeneficiaryDetailsContent.tsx
  ts/features/idpay/initiative/details/components/__tests__/BeneficiaryDetailsContent.test.tsx
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/BeneficiaryDetailsContent.test.tsx.snap
  ts/features/idpay/initiative/details/saga/handleGetOnboardingStatus.ts
  ts/features/idpay/initiative/details/saga/index.ts
  ts/features/idpay/initiative/details/screens/BeneficiaryDetailsScreen.tsx
  ts/features/idpay/initiative/details/store/actions/index.ts
  ts/features/idpay/initiative/details/store/index.ts
  ts/features/idpay/onboarding/xstate/__tests__/services.test.ts
Labels: IDPay, IO-Bonus e pagamenti

#4791 chore: [IOAPPFD0-127] Add new toast notification component
  ts/App.tsx
  ts/components/CalendarsListContainer.tsx
  ts/components/IdpSuccessfulAuthentication.tsx
  ts/components/Toast/ToastNotification.tsx
  ts/components/Toast/ToastProvider.tsx
  ts/components/Toast/__tests__/ToastNotification.test.tsx
  ts/components/Toast/__tests__/__snapshots__/ToastNotification.test.tsx.snap
  ts/components/Toast/context.ts
  ts/components/Toast/index.ts
  ts/components/Toast/types.ts
  ts/components/Toast/useIOToast.ts
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/IconCheckTick.tsx
  ts/components/core/icons/svg/IconCheckTickBig.tsx
  ts/components/core/icons/svg/originals/IconCheckTick.svg
  ts/components/core/icons/svg/originals/IconCheckTickBig.svg
  ts/components/core/selection/checkbox/RawCheckBox.tsx
  ts/components/core/typography/CTA.tsx
  ts/components/messages/MessageDetail/common/CalendarEventButton.tsx
  ts/components/ui/Dismissable.tsx
  ts/components/ui/__test__/Dismissable.test.tsx
  ts/components/wallet/CameraMarker.tsx
  ts/features/bonus/bpd/components/bpdCardComponent/BpdCardComponent.tsx
  ts/features/design-system/core/DSButtons.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/features/design-system/core/DSToastNotifications.tsx
  ts/features/idpay/initiative/details/components/TimelineOperationListItem.tsx
  ts/screens/ingress/CheckBox.tsx
  ts/screens/profile/LanguagesPreferencesScreen.tsx
  ts/utils/showToast.ts
Labels: Design System

#4827 chore: [IOBP-142] Removal of NativeBase in InitiativeSettings
  ts/components/ui/ListItemNav.tsx
  ts/components/ui/ListItemTransaction.tsx
  ts/features/idpay/initiative/details/components/InitiativeSettingsComponent.tsx
Labels: Design System, NativeBase dismissal 🥷🏼, IO-Bonus e pagamenti

#4822 chore: [IOBP-143] Add new `TabItem` component
  ts/components/core/typography/LabelHeader.tsx
  ts/components/ui/TabItem.tsx
  ts/components/ui/__test__/TabItem.test.tsx
  ts/components/ui/__test__/__snapshots__/TabItem.test.tsx.snap
  ts/components/ui/cards/payment/PaymentCardSmall.tsx
  ts/components/ui/utils/baseComponents/PressableListItemBase.tsx
  ts/components/ui/utils/hooks/useBaseSpringAnimation.ts
  ts/components/ui/utils/hooks/useListItemBaseSpringAnimation.ts
  ts/components/ui/utils/hooks/useSpringPressProgressValue.ts
  ts/components/ui/utils/hooks/useSpringPressScaleAnimation.ts
  ts/features/design-system/core/DSTabNavigation.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
Labels: Design System

#4836 feat(IT Wallet): [SIW-326] Add WIA issuing flow
  .env.local
  .env.production
  package.json
  ts/config.ts
  ts/features/it-wallet/saga/__tests__/handleRequirementsCheck.ts
  ts/features/it-wallet/saga/__tests__/handleWiaRequest.ts
  ts/features/it-wallet/saga/handleRequirementsCheck.ts
  ts/features/it-wallet/saga/handleWiaRequest.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwWia.ts
  ts/features/it-wallet/utils/errors/itwErrors.ts
  ts/features/it-wallet/utils/wia.ts
  yarn.lock
Labels: IT Wallet

#4832 feat: [IOCOM-378] Update of the instruction list in the `OnboardingNotificationsInfoScreenConsent`
  img/onboarding/ios-notifications-icon.svg
  img/onboarding/ios-notifications-toggle-icon.svg
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/onboarding/OnboardingNotificationsInfoScreenConsent.tsx
Labels: IO-Comunicazione

#4839 chore: [IOBP-130] A11y for transactions with negative amount
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ui/ListItemTransaction.tsx
  ts/utils/accessibility.ts
Labels: a11y, IO-Bonus e pagamenti

#4768 chore: [IOAPPFD0-125] Fix `Divider` rendering issue on Android devices
  ts/components/core/Divider/index.tsx
  ts/components/core/variables/IOColors.ts
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/BeneficiaryDetailsContent.test.tsx.snap
Labels: enhancement, Design System

#4840 fix: [IOBP-98] Add barcode scan result feedback
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
  ts/features/barcode/hooks/useIOBarcodeFileReader.tsx
  ts/features/barcode/hooks/useIOBarcodeScanner.tsx
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/barcode/types/IOBarcode.ts
  ts/features/barcode/types/__tests__/decoders.test.ts
  ts/features/barcode/types/decoders.ts
  ts/features/idpay/payment/screens/IDPayPaymentCodeScanScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#4834 feat: [IOCOM-380] Update mixpanel opt-in events
  ts/screens/onboarding/OnboardingNotificationsInfoScreenConsent.tsx
  ts/utils/analytics.ts
Labels: legal-approved ⚖️ ✅, IO-Comunicazione

#4843 fix: [IOBP-156] Fix bug in initiative details screen
  ts/features/idpay/initiative/details/components/InitiativeSettingsComponent.tsx
  ts/features/idpay/initiative/details/components/__tests__/InitiativeSettingsComponent.test.tsx
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/InitiativeSettingsComponent.test.tsx.snap
Labels: Bug 🐞, IDPay, IO-Bonus e pagamenti

#4828 chore: [IOBP-144] Add new `TabNavigation` component
  ts/components/ui/TabItem.tsx
  ts/components/ui/TabNavigation.tsx
  ts/features/design-system/core/DSTabNavigation.tsx
Labels: Design System

#4841 chore: [IOBP-97] Add `TabNavigation` component to barcode scan screen
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
  ts/features/barcode/components/BottomTabNavigation.tsx
Labels: IDPay, IO-Bonus e pagamenti

#4810 chore: [IOBP-139,IOBP-135] New wallet onboarding webview handling
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/config.ts
  ts/features/common/store/reducers/index.ts
  ts/features/walletV3/common/api/client.ts
  ts/features/walletV3/common/components/GenericErrorComponent.tsx
  ts/features/walletV3/common/saga/index.ts
  ts/features/walletV3/common/store/actions/index.ts
  ts/features/walletV3/common/store/reducers/index.ts
  ts/features/walletV3/onboarding/components/WalletOnboardingError.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingSuccess.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingWebView.tsx
  ts/features/walletV3/onboarding/navigation/navigator.tsx
  ts/features/walletV3/onboarding/saga/handleStartWalletOnboarding.ts
  ts/features/walletV3/onboarding/saga/index.ts
  ts/features/walletV3/onboarding/screens/WalletOnboardingStartScreen.tsx
  ts/features/walletV3/onboarding/store/actions/index.ts
  ts/features/walletV3/onboarding/store/index.ts
  ts/features/walletV3/onboarding/types/index.ts
  ts/features/walletV3/onboarding/utils/index.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/sagas/startup.ts
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/profile/playgrounds/WalletPlayground.tsx
  ts/store/actions/types.ts
Labels: IO-Bonus e pagamenti

#4818 fix: [PE-443] Hide address copy button for merchant with allNationalAddresses
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
Labels: Carta Giovani Nazionale

#4817 chore: [IOPID-516] FL deploy workflow
  .github/workflows/release-fl.yml
  CHANGELOG.md
  android/app/build.gradle
  android/fastlane/Fastfile
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/Info.plist
  ios/ItaliaAppTests/Info.plist
  ios/fastlane/Fastfile
  package.json
  publiccode.yml
Labels: IO-A&I

#4844 feat: [IOCOM-381,IOCOM-366] Update mixpanel third-party events
  ts/features/messages/analytics/index.ts
Labels: legal-approved ⚖️ ✅, IO-Comunicazione

#4850 Fix: Remove native login comment
  ts/screens/authentication/idpAuthSessionHandler.tsx
Labels: IO-A&I

#4848 feat(IT Wallet): [SIW-334] Add PID issuing flow
  .env.local
  .env.production
  package.json
  ts/components/messages/MessagesInbox.tsx
  ts/config.ts
  ts/features/it-wallet/components/ClaimsList.tsx
  ts/features/it-wallet/hooks/useItwResetFlow.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/saga/__tests__/handleWiaRequest.ts
  ts/features/it-wallet/saga/credentials.ts
  ts/features/it-wallet/saga/handleCredentials.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/saga/pid.ts
  ts/features/it-wallet/saga/wia.ts
  ts/features/it-wallet/screens/ItwCredentialDetails.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidActivationScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/store/actions/credentials.ts
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwCredentials.ts
  ts/features/it-wallet/store/reducers/itwLifecycle.ts
  ts/features/it-wallet/store/reducers/itwPid.ts
  ts/features/it-wallet/store/reducers/itwWia.ts
  ts/features/it-wallet/store/storages/credentialsKeychain.ts
  ts/features/it-wallet/utils/errors/itwErrors.ts
  ts/features/it-wallet/utils/keychain.ts
  ts/features/it-wallet/utils/pid.ts
  ts/features/it-wallet/utils/wia.ts
  yarn.lock
Labels: IT Wallet

#4849 feat(IT Wallet): [SIW-212] Add pid issuing identification screen
  ts/features/it-wallet/saga/credentials.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/screens/issuing/ItwPidActivationScreen.tsx
  ts/features/it-wallet/store/actions/credentials.ts
  ts/features/it-wallet/store/reducers/itwCredentials.ts
Labels: IT Wallet

#4852 feat: [IOCOM-396] Update `README.md`
  README.md
Labels: IO-Comunicazione

#4847 feat(IT Wallet): [SIW-343] Update pid issuing to use `io-react-native-cie-pid`
  ts/features/it-wallet/components/cie/CieNfcOverlay.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/saga/__tests__/handleWiaRequest.ts
  ts/features/it-wallet/saga/cie.ts
  ts/features/it-wallet/saga/pid.ts
  ts/features/it-wallet/saga/wia.ts
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieCardReaderScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieConsentDataUsageScreen.tsx
  ts/features/it-wallet/store/actions/credentials.ts
  ts/features/it-wallet/utils/cie.ts
  ts/features/it-wallet/utils/mocks.ts
  ts/features/it-wallet/utils/pid.ts
Labels: IT Wallet

#4777 chore: [IOAPPFD0-126] Add the new `GradientScrollView` and `GradientBottomActions` components
  ts/components/core/variables/IOColors.ts
  ts/components/core/variables/IOSpacing.ts
  ts/components/core/variables/IOStyles.ts
  ts/components/ui/GradientBottomActions.tsx
  ts/components/ui/GradientScrollView.tsx
  ts/features/design-system/core/DSGradientScroll.tsx
  ts/features/design-system/core/DSSafeAreaCentered.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
Labels: Design System

#4821 chore: [IOAPPFD0-130] Add `AnimatedMessageCheckbox`
  ts/components/core/selection/checkbox/AnimatedMessageCheckbox.tsx
  ts/components/ui/ButtonLink.tsx
  ts/features/design-system/core/DSSelection.tsx
Labels: Design System
