Repository pagopa/io-app, pull requests merged in 2023-06, with the labels that each got.

#4659 feat: [IOCOM-253,IOCOM-259] Refactor `lollipopFetch` to extract and export the signature creation
  ts/features/lollipop/utils/__tests__/lollipopRequestInit.test.ts
  ts/features/lollipop/utils/fetch.ts
Labels: IO-Comunicazione

#4665 fix: [IOAPPFD0-109] Fix UI regression of the `Paid` badge in the message list
  ts/components/messages/MessageDetail/__tests__/__snapshots__/MedicalPrescriptionDueDateBar.test.tsx.snap
  ts/components/messages/MessageDetail/common/CalendarEventButton.tsx
  ts/components/messages/MessageList/Item.tsx
  ts/components/messages/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
Labels: Bug 🐞, NativeBase dismissal 🥷🏼

#4668 feat: [IOCOM-253,IOCOM-261] Lollipop signature on attachment download endpoint
  ts/features/messages/saga/__test__/attachments.test.ts
  ts/features/messages/saga/networking/__test__/downloadAttachment.test.ts
  ts/features/messages/saga/networking/downloadAttachment.ts
Labels: IO-Comunicazione

#4667 chore: [IOAPPFD0-108] Add the new `Avatar` component
  ts/components/core/ContentWrapper/index.tsx
  ts/components/core/variables/IOStyles.ts
  ts/components/ui/Avatar.tsx
  ts/features/design-system/core/DSLogos.tsx
  ts/features/idpay/payment/screens/IDPayPaymentCodeInputScreen.tsx
  ts/utils/hooks/bottomSheet.tsx
Labels: Design System

#4678 fix: [IOAPPFD0-113] Removal of detrimental style from ListItem
  ts/components/core/variables/IOStyles.ts
Labels: Bug 🐞, Design System

#4650 chore: [IOAPPFD0-102] Add new `AnimatedCheckbox`, `CheckboxLabel` and `CheckboxListItem` components
  ts/components/core/selection/checkbox/AnimatedCheckbox.tsx
  ts/components/core/selection/checkbox/CheckboxLabel.tsx
  ts/components/core/typography/LabelSmall.tsx
  ts/components/core/typography/NewH6.tsx
  ts/components/core/typography/__test__/__snapshots__/typography.test.tsx.snap
  ts/components/core/variables/IOAnimations.ts
  ts/components/core/variables/IOStyles.ts
  ts/components/ui/CheckboxListItem.tsx
  ts/components/ui/ListItemNav.tsx
  ts/features/design-system/core/DSSelection.tsx
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/BeneficiaryDetailsContent.test.tsx.snap
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/InitiativeBonusCounter.test.tsx.snap
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/InitiativeDetailsBaseScreenComponent.test.tsx.snap
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/InitiativeStatusLabel.test.tsx.snap
Labels: Design System

#4677 fix(Firma con IO): [SFEQS-1568] Clear FCI state when user reset pin during signing flow
  ts/features/fci/saga/index.ts
Labels: Firma con IO

#4657 chore: [IOAPPFD0-105] Add the new `focused` state icons to the main navbar
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/components/MessagesTabIcon.tsx
  ts/components/ProfileTabIcon.tsx
  ts/components/ScanTabIcon.tsx
  ts/components/ServiceTabIcon.tsx
  ts/components/WalletTabIcon.tsx
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/IconInfo.tsx
  ts/components/core/icons/svg/IconLightbulb.tsx
  ts/components/core/icons/svg/IconNavMessagesFocused.tsx
  ts/components/core/icons/svg/IconNavProfileFocused.tsx
  ts/components/core/icons/svg/IconNavServicesFocused.tsx
  ts/components/core/icons/svg/IconNavWalletFocused.tsx
  ts/components/core/icons/svg/IconProductIOAppBlueBg.tsx
  ts/components/core/icons/svg/originals/IconInfo.svg
  ts/components/core/icons/svg/originals/IconLightbulb.svg
  ts/components/core/icons/svg/originals/IconNavMessagesFocused.svg
  ts/components/core/icons/svg/originals/IconNavProfileFocused.svg
  ts/components/core/icons/svg/originals/IconNavServicesFocused.svg
  ts/components/core/icons/svg/originals/IconNavWalletFocused.svg
  ts/components/core/icons/svg/originals/IconProductIOAppBlueBg.svg
  ts/components/ui/TabIconComponent.tsx
  ts/features/idpay/initiative/details/components/TimelineOperationListItem.tsx
  ts/features/idpay/initiative/details/components/__tests__/__snapshots__/InitiativeDetailsBaseScreenComponent.test.tsx.snap
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PspRadioItem.test.tsx.snap
  ts/navigation/TabNavigator.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/persistedPreferences.ts
Labels: enhancement, Design System

#4690 fix(Firma con IO): [SFEQS-1258] Disable PDF annotation
  ts/features/fci/components/DocumentViewer.tsx
  ts/features/fci/components/DocumentWithSignature.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
Labels: Firma con IO

#4676 chore: [IOAPPFD0-111] Visual improvements to the bottom sheet
  ts/components/ContextualInfo.tsx
  ts/components/FiscalCodeLandscapeOverlay.tsx
  ts/components/RegionServiceWebView.tsx
  ts/components/RemindEmailValidationOverlay.tsx
  ts/components/bottomSheet/BlurredBackgroundComponent.tsx
  ts/components/bottomSheet/BottomSheetHeader.tsx
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/IconCloseLarge.tsx
  ts/components/core/icons/svg/IconCloseMedium.tsx
  ts/components/core/icons/svg/originals/IconCloseLarge.svg
  ts/components/core/icons/svg/originals/IconCloseMedium.svg
  ts/components/core/variables/IOShapes.ts
  ts/components/ui/TextboxWithSuggestion.tsx
  ts/components/wallet/CameraMarker.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsFilters.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
  ts/features/bonus/common/components/TosBonusComponent.tsx
  ts/features/bonus/siciliaVola/components/SvVoucherListFilters.tsx
  ts/features/design-system/core/DSBottomSheet.tsx
  ts/features/fims/components/CommonContent.tsx
  ts/features/idpay/initiative/configuration/screens/InitiativeConfigurationIntroScreen.tsx
  ts/features/idpay/initiative/timeline/components/TimelineRefundDetailsComponent.tsx
  ts/features/wallet/component/features/PaymentStatusSwitch.tsx
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PspRadioItem.test.tsx.snap
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/screens/wallet/payment/CodesPositionManualPaymentModal.tsx
  ts/utils/hooks/bottomSheet.tsx
Labels: enhancement, Design System

#4689 feat: [PE-413] Add icon button to copy EYCA card number and change of EYCA refs website
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/detail/eyca/EycaInformationComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaPendingComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaStatusDetailsComponent.tsx
  ts/features/bonus/cgn/utils/constants.ts
Labels: Carta Giovani Nazionale

#4663 feat(Firma con IO): [SFEQS-1684] Add cancelled FCI request screen
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/fci/components/SuccessComponent.tsx
  ts/features/fci/components/__tests__/SuccessComponent.test.tsx
Labels: Firma con IO

#4701 feat: [IOCOM-329] FIMS cookie
  package.json
  ts/features/fims/screens/FimsWebviewScreen.tsx
  ts/store/reducers/authentication.ts
  ts/utils/cookieManager.ts
  yarn.lock
Labels: IO-Comunicazione

#4684 fix: [IOAPPFD0-115] Fix UI regression of `IOBadge` in payment capability screen
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsChoiceScreen.tsx
  ts/features/wallet/component/features/PagoPaPaymentCapability.tsx
Labels: Bug 🐞, NativeBase dismissal 🥷🏼

#4709 fix: [IOCOM-326] PN copy changes
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Comunicazione

#4708 feat(IT Wallet): [SIW-239] Add danger it wallet project scope
  scripts/ts/danger/utils/changelog.ts
Labels: IT Wallet

#4703 feat(IT Wallet): [SIW-228] Add IT Wallet feat flag
  .env.local
  .env.production
  ts/config.ts
Labels: IT Wallet

#4672 chore: [IOAPPFD0-110] Add the new `NativeSwitch` and relative `SwitchListItem` components
  ts/components/core/selection/checkbox/AnimatedSwitch.tsx
  ts/components/core/selection/checkbox/NativeSwitch.tsx
  ts/components/core/selection/checkbox/SwitchLabel.tsx
  ts/components/core/variables/IOStyles.ts
  ts/components/ui/SwitchListItem.tsx
  ts/features/design-system/core/DSSelection.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: Design System

#4717 feat(IT Wallet): [SIW-243] Add it-wallet directories and placeholders
  ts/features/it-wallet/api/.placeholder
  ts/features/it-wallet/components/.placeholder
  ts/features/it-wallet/hooks/.placeholder
  ts/features/it-wallet/navigation/.placeholder
  ts/features/it-wallet/saga/.placeholder
  ts/features/it-wallet/screens/.placeholder
  ts/features/it-wallet/store/.placeholder
Labels: IT Wallet

#4715 chore: [IOAPPFD0-117] Add the new `Badge` component
  ts/components/core/Badge.tsx
  ts/components/core/IOBadge.tsx
  ts/components/core/variables/IOColors.ts
  ts/components/core/variables/IOShapes.ts
  ts/components/core/variables/IOSpacing.ts
  ts/features/design-system/core/DSBadges.tsx
Labels: Design System

#4722 feat(IT Wallet): [SIW-222] ITW stack navigator initialization
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/navigation/routes.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
Labels: IT Wallet

#4716 chore: [IOAPPFD0-112] Fix `Banner` spacing of the smaller size
  ts/components/Banner/index.tsx
  ts/components/core/variables/IOSpacing.ts
  ts/features/design-system/core/DSAdvice.tsx
Labels: Design System

#4698 chore: [IOBP-73] Addition of payment survey banner
  locales/en/index.yml
  locales/it/index.yml
  ts/components/core/pictograms/Pictogram.tsx
  ts/components/core/pictograms/svg/PictogramFeedback.tsx
  ts/components/core/pictograms/svg/originals/PictogramFeedback.svg
  ts/screens/wallet/payment/PaymentOutcomeCodeMessage.tsx
Labels: legal-approved ⚖️ ✅

#4723 fix: [IOAPPFD0-119] Turn off the dark mode, except in the Design System section
  ts/App.tsx
  ts/components/core/variables/IOColors.ts
Labels: Bug 🐞, Design System, Dark mode 🌝

#4693 chore: [IOAPPFD0-116] Add the new `Tag` component
  ts/components/core/Tag.tsx
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/IconLegalValue.tsx
  ts/components/core/icons/svg/originals/IconLegalValue.svg
  ts/components/core/variables/IOShapes.ts
  ts/components/core/variables/IOSpacing.ts
  ts/features/design-system/core/DSBadges.tsx
  ts/features/design-system/navigation/routes.ts
Labels: Design System

#4713 feat: [IOPID-287] Add fast login server specs
  package.json
  ts/features/fastLogin/backend/index.ts
  ts/features/fastLogin/backend/mockedClients.ts
  ts/features/fastLogin/backend/mockedFunctionsAndTypes.ts
  ts/features/fastLogin/saga/tokenRefreshSaga.ts
Labels: IO-A&I

#4720 chore: [IOPID-359] First onboarding refactor
  ts/sagas/profile.ts
  ts/sagas/startup/__tests__/checkAcceptedTosSaga.test.tsx
  ts/sagas/startup/__tests__/checkProfileEmailSaga.test.tsx
  ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx
  ts/store/reducers/__tests__/profile.test.ts
  ts/store/reducers/profile.ts
  ts/utils/__tests__/content.test.ts
Labels: IO-A&I
