Repository pagopa/io-app, pull requests merged in 2023-09, with the labels that each got.

#4936 chore: [IOBP-187,IOBP-188,IOBP-189,IOBP-190,IOBP-191] A11y fixes in payment method details
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ui/LogoPaymentExtended.tsx
  ts/components/ui/cards/payment/PaymentCardBig.tsx
  ts/components/ui/cards/payment/__test__/__snapshots__/PaymentCards.test.tsx.snap
  ts/components/ui/utils/components/BankLogoOrLoadingSkeleton.tsx
  ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
  ts/features/wallet/bancomatpay/screen/BPayDetailScreen.tsx
  ts/features/wallet/cobadge/screen/CobadgeDetailScreen.tsx
  ts/features/wallet/common/BasePaymentMethodScreen.tsx
  ts/features/wallet/creditCard/screen/CreditCardDetailScreen.tsx
  ts/features/wallet/paypal/screen/PaypalDetailScreen.tsx
Labels: IO-Bonus e pagamenti

#4941 feat: [IOCOM-447] Add local feature flag for the redesign of the PN message detail
  .env.local
  .env.production
  ts/config.ts
  ts/features/pn/components/LegacyPnMessageDetails.tsx
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/screens/LegacyPnMessageDetailsScreen.tsx
Labels: IO-Comunicazione

#4942 chore: [IOPID-444] Updated fast login what's new
  ts/features/whatsnew/screen/FastLoginWhatsNew.tsx
Labels: IO-A&I

#4911 fix: [IOCOM-411] Fix overflowing text in notification preview in opt-in screen
  img/onboarding/notification_blue.png
  img/onboarding/notification_blue@2x.png
  img/onboarding/notification_blue@3x.png
  img/onboarding/notification_icon.png
  img/onboarding/notification_icon@2x.png
  img/onboarding/notification_icon@3x.png
  img/onboarding/notification_icon@4x.png
  img/onboarding/notification_white.png
  img/onboarding/notification_white@2x.png
  img/onboarding/notification_white@3x.png
  img/onboarding/notifications_background.svg
  img/onboarding/notifications_background_blue.svg
  ts/screens/onboarding/components/NotificationPreviewSample.tsx
  ts/screens/onboarding/components/NotificationsPreferencesPreview.tsx
  ts/screens/onboarding/components/__tests__/NotificationPreviewSample.test.tsx
Labels: IO-Comunicazione

#4902 fix: [IOCOM-395] Proper handling of NOTIFICATION_MESSAGE_TAP analytics' event
  ts/boot/configurePushNotification.ts
  ts/features/messages/analytics/index.ts
  ts/sagas/__tests__/notifications.test.ts
  ts/sagas/identification.ts
  ts/sagas/notifications.ts
  ts/sagas/startup.ts
  ts/sagas/startup/__tests__/watchNotificationSaga.test.ts
  ts/sagas/startup/watchApplicationActivitySaga.ts
  ts/sagas/startup/watchNotificationSaga.ts
  ts/store/actions/notifications.ts
  ts/store/reducers/notifications/pendingMessage.ts
Labels: IO-Comunicazione

#4948 chore: [IOPID-670,IOPID-714] Fix EIC login flow + EIC dev server login local FF
  .env.local
  .env.production
  ts/components/cie/CieRequestAuthenticationOverlay.tsx
  ts/config.ts
  ts/features/cieLogin/utils/index.ts
  ts/features/lollipop/hooks/useLollipopLoginSource.tsx
  ts/features/lollipop/index.ts
  ts/features/lollipop/utils/login.ts
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  ts/screens/onboarding/OnboardingEmailInsertScreen.tsx
Labels: IO-A&I

#4945 chore: [IOBP-208] Removal of pagoBancomat onboarding
  ts/components/__tests__/PspComponent.test.tsx
  ts/components/wallet/payment/PspComponent.tsx
  ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.tsx
  ts/features/bonus/bpd/saga/orchestration/activateBpdOnNewAddedPaymentMethods.ts
  ts/features/wallet/bancomat/component/BancomatWalletPreview.tsx
  ts/features/wallet/bancomat/component/bancomatCard/BaseBancomatCard.tsx
  ts/features/wallet/bancomatpay/component/__test__/BPayCard.test.tsx
  ts/features/wallet/bancomatpay/component/__test__/BPayWalletPreview.test.tsx
  ts/features/wallet/cobadge/component/BaseCoBadgeCard.tsx
  ts/features/wallet/cobadge/component/CobadgeWalletPreview.tsx
  ts/features/wallet/cobadge/component/__tests__/BaseCobadgeCard.test.tsx
  ts/features/wallet/cobadge/component/__tests__/CobadgeWalletPreview.test.tsx
  ts/features/wallet/onboarding/bancomat/analytics/index.ts
  ts/features/wallet/onboarding/bancomat/components/BankPreviewItem.tsx
  ts/features/wallet/onboarding/bancomat/hooks/useImageResize.ts
  ts/features/wallet/onboarding/bancomat/navigation/action.ts
  ts/features/wallet/onboarding/bancomat/navigation/navigator.ts
  ts/features/wallet/onboarding/bancomat/navigation/params.ts
  ts/features/wallet/onboarding/bancomat/navigation/routes.ts
  ts/features/wallet/onboarding/bancomat/saga/orchestration/addBancomatToWallet.ts
  ts/features/wallet/onboarding/bancomat/screens/ActivateBpdOnNewBancomatScreen.tsx
  ts/features/wallet/onboarding/bancomat/screens/add-pans/AddBancomatComponent.tsx
  ts/features/wallet/onboarding/bancomat/screens/add-pans/AddBancomatScreen.tsx
  ts/features/wallet/onboarding/bancomat/screens/add-pans/LoadAddBancomatComponent.tsx
  ts/features/wallet/onboarding/bancomat/screens/search/BancomatSearchBankScreen.tsx
  ts/features/wallet/onboarding/bancomat/screens/search/BancomatSearchStartScreen.tsx
  ts/features/wallet/onboarding/bancomat/screens/searchBancomat/BancomatKoNotFound.tsx
  ts/features/wallet/onboarding/bancomat/screens/searchBancomat/BancomatKoServicesError.tsx
  ts/features/wallet/onboarding/bancomat/screens/searchBancomat/BancomatKoSingleBankNotFound.tsx
  ts/features/wallet/onboarding/bancomat/screens/searchBancomat/BancomatKoTimeout.tsx
  ts/features/wallet/onboarding/bancomat/screens/searchBancomat/LoadBancomatSearch.tsx
  ts/features/wallet/onboarding/bancomat/screens/searchBancomat/SearchAvailableUserBancomatScreen.tsx
  ts/features/wallet/onboarding/common/screens/bpd/ActivateBpdOnNewCreditCardScreen.tsx
  ts/features/wallet/onboarding/paypal/components/PspRadioItem.tsx
  ts/features/wallet/paypal/screen/PayPalPspUpdateScreen.tsx
  ts/navigation/WalletNavigator.tsx
  ts/navigation/params/WalletParamsList.ts
  ts/sagas/wallet.ts
  ts/store/middlewares/analytics.ts
Labels: 💀 Dead code

#4944 chore: [IOAPPFD0-140] Remove `PictogramSection` from the codebase
  package.json
  ts/components/ScreenHeader.tsx
  ts/components/core/README.md
  ts/components/core/pictograms/Pictogram.tsx
  ts/components/core/pictograms/PictogramSection.tsx
  ts/components/core/pictograms/README.md
  ts/components/core/pictograms/SectionPictogram.tsx
  ts/components/core/pictograms/index.tsx
  ts/components/core/pictograms/svg/PictogramMessages.tsx
  ts/components/core/pictograms/svg/PictogramSectionDocuments.tsx
  ts/components/core/pictograms/svg/PictogramSectionMessages.tsx
  ts/components/core/pictograms/svg/PictogramSectionPayments.tsx
  ts/components/core/pictograms/svg/PictogramSectionProfile.tsx
  ts/components/core/pictograms/svg/PictogramSectionServices.tsx
  ts/components/core/pictograms/svg/PictogramSectionSettings.tsx
  ts/components/core/pictograms/svg/SectionPictogramDocuments.tsx
  ts/components/core/pictograms/svg/SectionPictogramPayments.tsx
  ts/components/core/pictograms/svg/SectionPictogramProfile.tsx
  ts/components/core/pictograms/svg/SectionPictogramServices.tsx
  ts/components/core/pictograms/svg/SectionPictogramSettings.tsx
  ts/components/core/pictograms/svg/SectionPictogramSmile.tsx
  ts/components/core/pictograms/svg/originals/PictogramMessages.svg
  ts/components/core/pictograms/svg/originals/SearchPictogram.svg
  ts/components/core/pictograms/svg/originals/SectionPictogramDocuments.svg
  ts/components/core/pictograms/svg/originals/SectionPictogramPayments.svg
  ts/components/core/pictograms/svg/originals/SectionPictogramProfile.svg
  ts/components/core/pictograms/svg/originals/SectionPictogramServices.svg
  ts/components/core/pictograms/svg/originals/SectionPictogramSettings.svg
  ts/components/screens/ScreenContentHeader.tsx
  ts/features/design-system/core/DSPictograms.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingSuccess.tsx
  yarn.lock
Labels: Design System, 💀 Dead code

#4955 chore: [IOBP-195] Dynamic padding to bottom sheet into PDNDAcceptance screen
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
Labels: Bug 🐞, IO-Bonus e pagamenti

#4949 chore(IT Wallet): [SIW-426] Update wallet library dependencies
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  ts/features/barcode/types/__tests__/decoders.test.ts
  ts/features/it-wallet/saga/itwRpInitialization.ts
  ts/features/it-wallet/saga/itwRpPresentation.ts
  yarn.lock
Labels: IT Wallet

#4943 feat(IT Wallet): [SIW-196] Add features info screen to select provider for wallet activation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwRoutes.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/screens/discovery/ItwDiscoveryInfoScreen.tsx
  ts/features/it-wallet/screens/discovery/ItwDiscoveryProviderInfoScreen.tsx
Labels: IT Wallet

#4906 feat(IT Wallet): [SIW-232] Add RP initialization screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwRoutes.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/saga/itwPidSaga.ts
  ts/features/it-wallet/saga/itwRpInitialization.ts
  ts/features/it-wallet/saga/itwRpInitializationSaga.ts
  ts/features/it-wallet/saga/itwRpPresentationSaga.ts
  ts/features/it-wallet/saga/itwRpSaga.ts
  ts/features/it-wallet/screens/presentation/crossdevice/ItwRpInitScreen.tsx
  ts/features/it-wallet/store/actions/itwRpActions.ts
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#4954 fix: [IOBP-211] Infinite loader if list of initiatives is an error
  ts/features/idpay/wallet/store/reducers/index.ts
Labels: Bug 🐞, IO-Bonus e pagamenti

#4932 feat(IT Wallet): [SIW-246] Add RP presentation screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwRoutes.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/saga/itwRpPresentationSaga.ts
  ts/features/it-wallet/screens/presentation/crossdevice/ItwRpInitScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/ItwRpPresentationScreen.tsx
  ts/features/it-wallet/store/actions/itwRpActions.ts
  ts/features/it-wallet/store/reducers/itwRpPresentationReducer.ts
  ts/features/it-wallet/utils/navigation.ts
Labels: IT Wallet

#4962 fix(IT Wallet): [SIW-445] Fix components not showing text with dark mode
  ts/App.tsx
  ts/components/core/Divider/index.tsx
  ts/features/design-system/components/DSIconViewerBox.tsx
  ts/features/design-system/components/DSSpacerViewerBox.tsx
  ts/features/design-system/components/DesignSystemScreen.tsx
  ts/features/design-system/core/DSBottomSheet.tsx
  ts/features/design-system/core/DSHapticFeedback.tsx
  ts/features/design-system/core/DSIcons.tsx
  ts/features/design-system/core/DSLayout.tsx
  ts/features/design-system/core/DSListItems.tsx
Labels: IT Wallet

#4947 feat: [IOCOM-448] Add Module payment notice
  locales/en/index.yml
  locales/it/index.yml
  ts/components/core/IOBadge.tsx
  ts/components/ui/ModulePaymentNotice.tsx
  ts/features/design-system/core/DSModules.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
Labels: Design System, IO-Comunicazione

#4960 fix: [IOBP-219] Initiative list into card details
  ts/features/idpay/wallet/store/reducers/index.ts
Labels: Bug 🐞, IO-Bonus e pagamenti

#4964 fix(IT Wallet): [SIW-471] Move loading animation to native thread
  ts/features/it-wallet/components/ItwLoadingSpinner.tsx
Labels: IT Wallet

#4958 chore: [IOPID-654] Change insert new email screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/onboarding/NewOnboardingEmailInsertScreen.tsx
  ts/screens/onboarding/__tests__/NewOnboardingEmailInsertScreen.test.tsx
Labels: IO-A&I

#4952 chore: [IOAPPFD0-141] Update `README` to include `io-app-design-system` reference
  README.md
Labels: Design System

#4972 chore: [IOAPPFD0-145] Add the new `PictogramBleed` component
  package.json
  ts/components/Banner/index.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/design-system/components/DSAssetViewerBox.tsx
  ts/features/design-system/core/DSAdvice.tsx
  ts/features/design-system/core/DSPictograms.tsx
  ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
  ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
  ts/features/wallet/cobadge/screen/CobadgeDetailScreen.tsx
  yarn.lock
Labels: Design System

#4970 feat: [IOCOM-497] PN cancelled message UI
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/MessageAttachments.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/__test__/PnMessageDetails.test.tsx
Labels: IO-Comunicazione

#4975 feat: [IOCOM-528] Add check on minimum app version for PN
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/messages/MessageList/Item.tsx
  ts/components/messages/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/config.ts
  ts/features/messages/components/MessageFeedback.tsx
  ts/features/messages/components/PreconditionBottomSheet/PreconditionContent.tsx
  ts/features/messages/components/PreconditionBottomSheet/PreconditionFooter.tsx
  ts/features/messages/components/PreconditionBottomSheet/PreconditionHeader.tsx
  ts/features/messages/hooks/useMessageOpening.tsx
  ts/features/pn/components/LegacyPnMessageDetails.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/sagas/startup.ts
  ts/screens/messages/__tests__/MessagesHomeScreen.test.tsx
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: IO-Comunicazione

#4963 fix: [IOCOM-480] Various fixes for reported anomalies on PN mixpanel events
  ts/components/cta/ExtractedCTABar.tsx
  ts/features/pn/components/LegacyPnMessageDetails.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessageTimeline.tsx
  ts/features/pn/components/PnServiceCTA.tsx
  ts/features/pn/components/__test__/PnMessageDetails.test.tsx
  ts/features/pn/screens/LegacyPnMessageDetailsScreen.tsx
  ts/features/pn/screens/PnMessageDetailsScreen.tsx
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/pn/utils/index.ts
  ts/features/pn/utils/rptId.ts
  ts/screens/messages/MessageRouterScreen.tsx
Labels: IO-Comunicazione

#4985 chore(IT Wallet): [SIW-487] Update io-react-native-wallet to 0.4.1
  package.json
  yarn.lock
Labels: IT Wallet

#4968 feat: [IOPID-666] FL missing pin logout flow
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fastLogin/saga/tokenRefreshSaga.ts
  ts/features/fastLogin/screens/FastLoginModals.tsx
  ts/features/fastLogin/store/actions/index.ts
  ts/features/fastLogin/store/reducers/index.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/profile.ts
  ts/sagas/startup.ts
  ts/screens/modal/RootModal.tsx
Labels: IO-A&I

#4977 feat: [IOCOM-498] Payment UI on a PN cancelled message
  locales/en/index.yml
  locales/it/index.yml
  ts/components/box/InfoBox.tsx
  ts/features/messages/components/MessageAttachments.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessageDetailsSection.tsx
  ts/features/pn/components/PnMessagePayment.tsx
  ts/features/pn/components/__test__/PnMessagePayment.test.tsx
Labels: IO-Comunicazione

#4987 feat: [IOCOM-522] Paid payments details' screen for a cancelled PN message
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessagePayment.tsx
  ts/features/pn/components/__test__/PnMessagePayment.test.tsx
  ts/features/pn/navigation/actions.ts
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/navigation/params.ts
  ts/features/pn/navigation/routes.ts
  ts/features/pn/screens/PnPaidPaymentScreen.tsx
  ts/features/pn/screens/__test__/PnPaidPaymentScreen.test.tsx
  ts/features/pn/screens/__test__/__snapshots__/PnPaidPaymentScreen.test.tsx.snap
Labels: IO-Comunicazione

#4953 feat: [IOPID-686] EmailAlreadyUsed Modal
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/modal/mailCheck/EmailAlreadyUsedModal.tsx
Labels: IO-A&I

#4971 feat: [IOPID-652] Biometric educational
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/__e2e__/utils.ts
  ts/navigation/OnboardingNavigator.tsx
  ts/navigation/params/OnboardingParamsList.ts
  ts/navigation/routes.ts
  ts/sagas/startup.ts
  ts/sagas/startup/checkAcknowledgedFingerprintSaga.ts
  ts/sagas/startup/onboarding/biometric/biometricStateSagas.ts
  ts/sagas/startup/onboarding/biometric/checkAcknowledgedFingerprintSaga.ts
  ts/screens/onboarding/FingerprintScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/FingerprintScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/MissingDeviceBiometricScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/MissingDevicePinScreen.tsx
  ts/store/actions/navigation.ts
  ts/store/actions/onboarding.ts
  ts/store/reducers/onboarding.ts
  ts/utils/biometrics.ts
Labels: IO-A&I

#4935 feat(Firma con IO): [SFEQS-1976] Handle 401 status code adding fast login wrapper
  ts/features/fci/saga/networking/__tests__/handleCreateFilledDocument.test.ts
  ts/features/fci/saga/networking/__tests__/handleGetMetadata.test.ts
  ts/features/fci/saga/networking/__tests__/handleGetQtspMetadata.test.ts
  ts/features/fci/saga/networking/__tests__/handleGetSignatureRequestById.test.ts
  ts/features/fci/saga/networking/__tests__/handleGetSignatureRequests.test.ts
  ts/features/fci/saga/networking/handleCreateFilledDocument.ts
  ts/features/fci/saga/networking/handleCreateSignature.ts
  ts/features/fci/saga/networking/handleGetMetadata.ts
  ts/features/fci/saga/networking/handleGetQtspMetadata.ts
  ts/features/fci/saga/networking/handleGetSignatureRequestById.ts
  ts/features/fci/saga/networking/handleGetSignatureRequests.ts
Labels: Firma con IO

#4978 chore: [IOAPPFD0-146] Add the new `IODSExperimentalContextProvider` to the main app, remove local `Button…` components
  ts/App.tsx
  ts/components/Banner/index.tsx
  ts/components/IdpsGridRevamp.tsx
  ts/components/PinCreationForm.tsx
  ts/components/ui/ButtonLink.tsx
  ts/components/ui/ButtonOutline.tsx
  ts/components/ui/ButtonSolid.tsx
  ts/components/ui/ModuleIDP.tsx
  ts/features/barcode/components/CameraPermissionView.tsx
  ts/features/design-system/components/DSComponentViewerBox.tsx
  ts/features/design-system/core/DSBottomSheet.tsx
  ts/features/design-system/core/DSButtons.tsx
  ts/features/design-system/core/DSGradientScroll.tsx
  ts/features/design-system/core/DSHapticFeedback.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/features/design-system/core/DSModules.tsx
  ts/features/design-system/core/DSToastNotifications.tsx
  ts/features/fastLogin/screens/AskUserInterarctionScreen.tsx
  ts/features/idpay/configuration/screens/IbanConfigurationLandingScreen.tsx
  ts/features/idpay/details/components/InitiativeRulesInfoBox.tsx
  ts/features/idpay/details/screens/InitiativeDetailsScreen.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/idpay/timeline/components/TimelineDetailsBottomSheet.tsx
  ts/features/idpay/unsubscription/screens/UnsubscriptionResultScreen.tsx
  ts/features/lollipop/playgrounds/LollipopPlaygroundContent.tsx
  ts/features/wallet/onboarding/paypal/components/PspRadioItem.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingSuccess.tsx
  ts/screens/authentication/IdpSelectionScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/profile/components/DSEnableSwitch.tsx
Labels: Design System

#4993 feat(IT Wallet): [SIW-497] Add ListItemItw component
  ts/features/design-system/core/DSListItems.tsx
  ts/features/it-wallet/components/ListItemItw.tsx
Labels: IT Wallet

#4967 chore: [IOBP-215] Unused locales scripts
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  package.json
  scripts/remove-unused-locales.ts
  scripts/remove_empty_i18n_keys.sh
Labels: i18n, 💀 Dead code

#4991 chore(IT Wallet): [SIW-486] Add incoming badge to spid item into info provider screen
  ts/features/it-wallet/screens/discovery/ItwDiscoveryProviderInfoScreen.tsx
Labels: IT Wallet

#4973 feat(Firma con IO): [SFEQS-1894] Add signature field static info tooltip with the definition of unfair clause
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fci/hooks/useFciSignatureFieldInfo.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
Labels: Firma con IO

#4996 fix(IT Wallet): [SIW-419] Fix scroll issue on some info screen
  ts/features/it-wallet/screens/discovery/ItwDiscoveryInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidAuthInfoScreen.tsx
Labels: IT Wallet

#4999 chore: [IOAPPFD0-153] Remove `@react-navigation/drawer` dependency
  package.json
  yarn.lock
Labels: dependencies, 💀 Dead code

#5002 feat(IT Wallet): [SIW-501] Disable experimental design system by default
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/components/ui/cards/payment/__test__/__snapshots__/PaymentCards.test.tsx.snap
  ts/features/idpay/details/components/__tests__/__snapshots__/InitiativeSettingsComponent.test.tsx.snap
  ts/store/reducers/persistedPreferences.ts
Labels: IT Wallet

#5004 chore(IT Wallet): [SIW-502] Update io-react-native-wallet to 0.4.3
  package.json
  yarn.lock
Labels: IT Wallet

#5006 chore: [IOBP-150] Add identification request in IdPay transaction authorization
  ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5009 feat(IT Wallet): [SIW-508] Update design system to 1.9.0
  package.json
  ts/components/FeatureInfo/index.tsx
  ts/components/core/typography/NewLink.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/components/ui/ModuleIDP.tsx
  ts/components/ui/SwitchListItem.tsx
  ts/features/design-system/core/DSAdvice.tsx
  ts/features/design-system/core/DSButtons.tsx
  ts/features/it-wallet/components/ListItemItw.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/ItwRpInitScreen.tsx
  ts/features/pn/components/PnMessagePayment.tsx
  yarn.lock
Labels: IT Wallet

#5010 feat(IT Wallet): [SIW-506] Add ITW experimental feature flag
  .env.local
  .env.production
  ts/config.ts
Labels: IT Wallet

#4988 chore: [IOAPPFD0-149] Add full dark mode support to the DS section
  ts/components/messages/MessageDetail/__tests__/__snapshots__/CtaBar.test.tsx.snap
  ts/components/messages/MessageDetail/__tests__/__snapshots__/MedicalPrescriptionDueDateBar.test.tsx.snap
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/components/ui/cards/payment/__test__/__snapshots__/PaymentCards.test.tsx.snap
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/components/DSComponentViewerBox.tsx
  ts/features/design-system/components/DSLogoPaymentViewerBox.tsx
  ts/features/design-system/components/DesignSystemScreen.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/idpay/details/components/__tests__/__snapshots__/InitiativeDetailsBaseScreenComponent.test.tsx.snap
  ts/features/idpay/details/components/__tests__/__snapshots__/InitiativeSettingsComponent.test.tsx.snap
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PayPalOnboardingCompletedSuccessComponent.test.tsx.snap
  ts/navigation/AppStackNavigator.tsx
Labels: Dark mode 🌝

#5015 chore(IT Wallet): [SIW-510] Make ItwActionBanner component non dismissible
  ts/components/messages/MessagesInbox.tsx
  ts/features/it-wallet/components/ItwActionBanner.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
Labels: IT Wallet

#5017 chore(IT Wallet): [SIW-519] Remove AdviceComponent from ITW CIE pin screen
  ts/features/it-wallet/screens/issuing/cie/ItwCiePinScreen.tsx
Labels: IT Wallet

#5018 chore(IT Wallet): [SIW-511] Change payments screen title
  locales/en/index.yml
  locales/it/index.yml
Labels: IT Wallet

#5011 feat: [IOBP-264] Addition of idpay code regeneration screen and beginning of flow
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/code/screens/IdPayCodeRenewScreen.tsx
  ts/screens/profile/playgrounds/IDPayCodePlayground.tsx
Labels: IDPay, IO-Bonus e pagamenti

#4992 feat: [IOBP-235] Addition of idpay code display screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/code/onboarding/screens/IdPayCodeDisplayScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5016 feat: [IOCOM-548] Tracking properties on PN_UX_SUCCESS event to track cancelled PN notification
  ts/features/pn/analytics/index.ts
  ts/features/pn/screens/LegacyPnMessageDetailsScreen.tsx
  ts/features/pn/screens/PnMessageDetailsScreen.tsx
  ts/features/pn/utils/index.ts
Labels: IO-Comunicazione

#5023 chore: [IOAPPFD0-155] Add color mode support to the pictograms
  package.json
  ts/components/messages/__tests__/__snapshots__/EmptyListComponent.test.tsx.snap
  ts/features/bonus/cgn/components/detail/eyca/EycaStatusDetailsComponent.tsx
  ts/features/design-system/core/DSPictograms.tsx
  ts/features/idpay/configuration/screens/IbanConfigurationLandingScreen.tsx
  ts/features/idpay/wallet/components/IDPayInitiativesListComponents.tsx
  ts/features/wallet/common/BasePaymentMethodScreen.tsx
  ts/features/wallet/component/features/PaymentMethodSettings.tsx
  ts/screens/onboarding/components/NotificationPreviewSample.tsx
  yarn.lock
Labels: Design System, Dark mode 🌝

#5008 feat: [IOCOM-512] Add the `OPEN_MESSAGE` mixpanel event
  ts/features/messages/analytics/index.ts
  ts/screens/messages/MessageRouterScreen.tsx
  ts/utils/analytics.ts
Labels: IO-Comunicazione

#5024 feat: [IOCOM-555] Replace `FullReceivedNotification` with the autogenerated one
  package.json
  ts/features/pn/analytics/index.ts
  ts/features/pn/components/LegacyPnMessageDetails.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessagePayment.tsx
  ts/features/pn/components/__test__/PnMessageDetails.test.tsx
  ts/features/pn/components/__test__/PnMessagePayment.test.tsx
  ts/features/pn/screens/LegacyPnMessageDetailsScreen.tsx
  ts/features/pn/screens/PnMessageDetailsScreen.tsx
  ts/features/pn/store/types/__test__/types.test.ts
  ts/features/pn/store/types/transformers.ts
  ts/features/pn/store/types/types.ts
  ts/features/pn/utils/index.ts
  ts/features/pn/utils/rptId.ts
Labels: IO-Comunicazione

#4982 chore: [IOBP-236] IDPay CIE how it works bottom sheet
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/code/components/IdPayInfoCieBottomSheet.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5003 chore: [IOCOM-549] Display the `dueDate` in the transaction summary
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/wallet/payment/components/TransactionSummary.tsx
Labels: IO-Comunicazione

#5022 chore(IT Wallet): [SIW-529] Remove tab navigator right horizontal padding in ITW home screen
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
Labels: IT Wallet

#5025 chore: [IOAPPFD0-144] Add `IconContained` example to DS
  ts/features/design-system/core/DSIcons.tsx
Labels: Design System

#5019 chore(IT Wallet): [SIW-514] Update copy in ITW_DISCOVERY_INFO screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/screens/discovery/ItwDiscoveryInfoScreen.tsx
Labels: IT Wallet

#5020 chore(IT Wallet): [SIW-520] Remove CIE info usage screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwRoutes.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieInfoUsageScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCiePinScreen.tsx
Labels: IT Wallet

#5030 chore(IT Wallet): [SIW-524] Update ITW home screen navbar labels
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
Labels: IT Wallet

#5026 chore: [IOBP-266] IDPay configuration wallet instruments filter
  ts/features/idpay/configuration/xstate/services.ts
Labels: IDPay, IO-Bonus e pagamenti

#5013 feat(IT Wallet): [SIW-442] Add credentials catalog screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ItwSearchBar.tsx
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwRoutes.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/screens/ItwCredentialsCatalogScreen.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#5031 feat(IT Wallet): [SIW-482] Update `io-react-native-wallet` version
  .env.local
  .env.production
  package.json
  ts/features/it-wallet/saga/itwRpInitializationSaga.ts
  ts/features/it-wallet/saga/itwRpPresentationSaga.ts
  ts/features/it-wallet/store/actions/itwCredentialsActions.ts
  ts/features/it-wallet/store/actions/itwRpActions.ts
  ts/features/it-wallet/store/reducers/itwRpInitializationReducer.ts
  ts/features/it-wallet/utils/pid.ts
  ts/features/it-wallet/utils/wia.ts
  yarn.lock
Labels: IT Wallet

#5032 chore(IT Wallet): [SIW-512] Update navigator scan qr code label
  locales/en/index.yml
  locales/it/index.yml
Labels: IT Wallet

#5037 feat: [IOCOM-559] Enable the PN flag for cancelled notification's handling
  .env.production
  ts/features/pn/components/PnMessageDetails.tsx
Labels: IO-Comunicazione

#5012 chore: [IOBP-267] Remove native-base from IdPay components
  package.json
  ts/components/ui/SwitchListItem.tsx
  ts/features/idpay/configuration/components/InstrumentEnrollmentSwitch.tsx
  ts/features/idpay/configuration/screens/ConfigurationSuccessScreen.tsx
  ts/features/idpay/configuration/screens/InitiativeConfigurationIntroScreen.tsx
  ts/features/idpay/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/onboarding/screens/FailureScreen.tsx
  ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
  ts/features/idpay/unsubscription/components/UnsubscriptionCheckListItem.tsx
  ts/features/idpay/unsubscription/screens/UnsubscriptionResultScreen.tsx
  ts/screens/profile/playgrounds/IDPayOnboardingPlayground.tsx
  yarn.lock
Labels: IDPay, NativeBase dismissal 🥷🏼, IO-Bonus e pagamenti

#5033 chore(IT Wallet): [SIW-515] Add link to terms and privacy policy
  locales/en/index.yml
  locales/it/index.yml
Labels: IT Wallet

#5034 chore: [IOBP-277] ListItemAction update in codeRenewScreen
  ts/features/idpay/code/screens/IdPayCodeRenewScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5038 chore: [IOAPPFD0-158] Remove local `ModuleIDP` and `ModulePaymentNotice` components
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/IdpsGridRevamp.tsx
  ts/components/ui/ModulePaymentNotice.tsx
  ts/features/design-system/core/DSModules.tsx
  ts/features/messages/utils/strings.ts
  ts/features/pn/components/PnMessagePayment.tsx
  yarn.lock
Labels: Design System

#4994 chore: [IOBP-262] Update IdPay API definitions
  package.json
  ts/features/idpay/common/api/__mocks__/client.ts
  ts/features/idpay/configuration/xstate/__mocks__/services.ts
  ts/features/idpay/payment/xstate/services.ts
Labels: IDPay, IO-Bonus e pagamenti

#4995 chore: [IOBP-256] Implements IdPay code flow with redux-saga
  ts/features/idpay/code/navigation/navigator.tsx
  ts/features/idpay/code/navigation/params.ts
  ts/features/idpay/code/navigation/routes.ts
  ts/features/idpay/code/onboarding/screens/IdPayCodeDisplayScreen.tsx
  ts/features/idpay/code/saga/handleIdPayEnrollCode.ts
  ts/features/idpay/code/saga/handleIdPayGenerateCode.ts
  ts/features/idpay/code/saga/handleIdPayGetCodeStatus.ts
  ts/features/idpay/code/saga/index.ts
  ts/features/idpay/code/screens/IdPayCodeDisplayScreen.tsx
  ts/features/idpay/code/screens/IdPayCodeOnboardingScreen.tsx
  ts/features/idpay/code/screens/IdPayCodeRenewScreen.tsx
  ts/features/idpay/code/screens/IdPayCodeResultScreen.tsx
  ts/features/idpay/code/screens/IdPayResultScreen.tsx
  ts/features/idpay/code/store/actions/index.ts
  ts/features/idpay/code/store/reducers/index.ts
  ts/features/idpay/code/store/selectors/index.ts
  ts/features/idpay/common/actions/index.ts
  ts/features/idpay/common/saga/index.ts
  ts/features/idpay/common/store/actions/index.ts
  ts/features/idpay/common/store/reducers/index.ts
  ts/features/idpay/configuration/xstate/__mocks__/services.ts
  ts/features/idpay/details/store/actions/index.ts
  ts/features/idpay/details/store/index.ts
  ts/features/idpay/timeline/store/actions/index.ts
  ts/features/idpay/timeline/store/index.ts
  ts/features/idpay/wallet/store/actions/index.ts
  ts/features/idpay/wallet/store/reducers/index.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/screens/profile/playgrounds/IDPayCodePlayground.tsx
  ts/screens/profile/playgrounds/IdPayCodePlayground.tsx
  ts/screens/profile/playgrounds/IdPayOnboardingPlayground.tsx
  ts/store/actions/types.ts
Labels: IDPay, IO-Bonus e pagamenti

#5001 feat: [IOBP-234,IOBP-233] IdPay code onboarding screen
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/WizardScreen.tsx
  ts/features/design-system/core/DSWizardScreen.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/features/idpay/code/screens/IdPayCodeOnboardingScreen.tsx
  ts/features/idpay/code/screens/IdPayCodeResultScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5048 fix(IT Wallet): [SIW-558] Fix camera crash on iPhone 15
  patches/react-native-vision-camera+2.15.4.patch
Labels: IT Wallet

#5036 chore: [IOPID-882] MP initialization refactoring
  ts/mixpanel.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/mixpanel.ts
  ts/sagas/startup.ts
  ts/sagas/startup/watchLogoutSaga.ts
Labels: IO-A&I
