Repository pagopa/io-app, pull requests merged in 2023-05, with the labels that each got.

#4575 chore(IDPay): [IODPAY-221] Update IDPay API definition to v2.52.1
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/idpay/onboarding/xstate/__tests__/machine.test.ts
  ts/features/idpay/onboarding/xstate/__tests__/services.test.ts
Labels: IDPay

#4570 feat(Firma con IO): [SFEQS-800] Add mixpanel FCI events
  ts/features/fci/analytics/index.ts
  ts/features/fci/components/SuccessComponent.tsx
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/fci/hooks/useFciCheckService.tsx
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
  ts/features/fci/screens/valid/FciThankyouScreen.tsx
  ts/features/fci/utils/__tests__/signatureFields.test.ts
  ts/features/fci/utils/signatureFields.ts
  ts/store/middlewares/analytics.ts
Labels: legal-approved ⚖️ ✅, Firma con IO

#4580 fix(Firma con IO): [SFEQS-1635] Fix mixpanel events action
  ts/features/fci/analytics/index.ts
Labels: Firma con IO

#4581 chore(IDPay): [IODPAY-223] Initiative details screen refactoring
  ts/features/idpay/initiative/details/components/InitiativeCardComponent.tsx
  ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
Labels: IDPay

#4554 chore(IDPay): [IODPAY-195] New IDPay bonus card in wallet
  img/features/idpay/bonus_logo.png
  img/features/idpay/bonus_logo@2x.png
  img/features/idpay/bonus_logo@3x.png
  img/features/idpay/initiative_preview_bg.png
  img/features/idpay/wallet_card.png
  img/features/idpay/wallet_card@2x.png
  img/features/idpay/wallet_card@3x.png
  ts/features/idpay/initiative/details/components/InitiativeCardComponent.tsx
  ts/features/idpay/wallet/components/IDPayCardPreviewComponent.tsx
  ts/features/idpay/wallet/components/IDPayCardsInWalletContainer.tsx
Labels: IDPay

#4558 chore: [IODPAY-216] Add onboarding PDND criteria values
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/idpay/onboarding/utils/__tests__/strings.test.ts
  ts/features/idpay/onboarding/utils/strings.ts
Labels: IDPay

#4586 fix: [IAI-277] Fix text alignment of the Messages' empty state component
  ts/components/LoadingSpinnerOverlay.tsx
  ts/components/__tests__/__snapshots__/WebviewComponent.test.tsx.snap
  ts/components/messages/EmptyListComponent.tsx
  ts/components/messages/MessagesArchive.tsx
  ts/components/messages/MessagesInbox.tsx
  ts/components/messages/__tests__/EmptyListComponent.test.tsx
  ts/components/messages/__tests__/__snapshots__/EmptyListComponent.test.tsx.snap
Labels: Bug 🐞

#4337 chore: [IAI-265] Refactor `IOBadge` with new variants · Remove the NativeBase `Badge`
  ts/components/DetailedlistItemComponent.tsx
  ts/components/core/IOBadge.tsx
  ts/components/messages/MessageList/Item.tsx
  ts/components/messages/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
  ts/components/screens/ListItemComponent.tsx
  ts/components/ui/CustomBadge.tsx
  ts/components/ui/__test__/__snapshots__/CustomBadge.test.tsx.snap
  ts/components/wallet/PaymentMethodsList.tsx
  ts/components/wallet/card/SectionCardComponent.tsx
  ts/features/bonus/bonusVacanze/components/AvailableBonusItem.tsx
  ts/features/bonus/bonusVacanze/components/BonusCardComponent.tsx
  ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx
  ts/features/bonus/bpd/components/bpdCardComponent/BpdCardComponent.tsx
  ts/features/bonus/bpd/components/superCashbackRanking/RankPositionItem.tsx
  ts/features/bonus/bpd/components/superCashbackRanking/SuperCashbackHeader.tsx
  ts/features/bonus/bpd/screens/details/transaction/detail/BpdTransactionDetailComponent.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsChoiceScreen.tsx
  ts/features/bonus/cgn/components/detail/CgnStatusDetail.tsx
  ts/features/bonus/cgn/components/detail/__test__/CgnStatusDetail.test.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaStatusDetailsComponent.tsx
  ts/features/bonus/cgn/components/merchants/CgnDiscountValueBox.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantListItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/design-system/core/DSBadges.tsx
  ts/features/fci/components/SignatureRequestItem.tsx
  ts/features/idpay/initiative/configuration/components/InstrumentEnrollmentSwitch.tsx
  ts/features/idpay/initiative/details/components/InitiativeStatusLabel.tsx
  ts/features/idpay/initiative/timeline/components/TimelineRefundDetailsComponent.tsx
  ts/features/wallet/bancomat/component/bancomatCard/BaseBancomatCard.tsx
  ts/features/wallet/cobadge/component/BaseCoBadgeCard.tsx
  ts/features/wallet/component/card/FeaturedCard.tsx
  ts/features/wallet/component/features/PagoPaPaymentCapability.tsx
  ts/features/wallet/privative/component/card/BasePrivativeCard.tsx
  ts/screens/onboarding/OnboardingNotificationsPreferencesScreen.tsx
  ts/screens/profile/components/services/ServicesContactComponent.tsx
  ts/screens/wallet/payment/components/TransactionSummary.tsx
Labels: a11y, Design System, NativeBase dismissal 🥷🏼

#4553 chore: [IOAPPFD0-85] Add the new `ButtonLink` component
  ts/components/core/variables/IOStyles.ts
  ts/components/ui/ButtonLink.tsx
  ts/components/ui/ButtonOutline.tsx
  ts/features/design-system/core/DSButtons.tsx
  ts/features/lollipop/playgrounds/LollipopPlaygroundContent.tsx
Labels: Design System

#4587 chore: [IODPAY-207] Move initiatives from instrument refresh logic in saga
  ts/features/idpay/wallet/hooks/useIDPayInitiativesFromInstrument.ts
  ts/features/idpay/wallet/saga/handleGetIDPayInitiativesFromInstrument.ts
  ts/features/idpay/wallet/saga/index.ts
  ts/features/idpay/wallet/screens/AvailableInitiativesListScreen.tsx
  ts/features/idpay/wallet/store/actions/index.ts
  ts/features/idpay/wallet/store/reducers/__test__/reducer.test.ts
  ts/features/idpay/wallet/store/reducers/index.ts
  ts/features/wallet/component/features/PaymentMethodInitiatives.tsx
  ts/features/wallet/creditCard/screen/__tests__/CreditCardDetailScreen.test.tsx
Labels: IDPay

#4576 chore: [IOAPPFD0-93] Add the new `FeatureInfo` component
  ts/components/FeatureInfo/index.tsx
  ts/components/InfoAltScreenComponent/InfoAltScreenComponent.tsx
  ts/components/core/pictograms/Pictogram.tsx
  ts/components/core/pictograms/SectionPictogram.tsx
  ts/components/core/pictograms/svg/PictogramFollowMessage.tsx
  ts/components/core/pictograms/svg/PictogramManual.tsx
  ts/components/core/pictograms/svg/originals/PictogramFollowMessage.svg
  ts/components/core/pictograms/svg/originals/PictogramManual.svg
  ts/components/core/typography/NewLink.tsx
  ts/components/core/variables/IOColors.ts
  ts/components/messages/EmptyListComponent.tsx
  ts/features/design-system/core/DSAdvice.tsx
  ts/features/design-system/core/DSAlert.tsx
  ts/features/design-system/core/DSPictograms.tsx
  ts/features/design-system/navigation/routes.ts
  ts/features/idpay/onboarding/screens/FailureScreen.tsx
  ts/features/idpay/unsubscription/screens/UnsubscriptionResultScreen.tsx
  ts/screens/wallet/payment/TransactionErrorScreen.tsx
Labels: Design System

#4590 feat(Firma con IO): [SFEQS-1326] Update copy data sharing screen
  locales/en/index.yml
  locales/it/index.yml
Labels: Firma con IO

#4604 feat(Firma con IO): [SFEQS-1661] Edit signature fields order
  ts/features/fci/screens/__tests__/FciSignatureFieldsScreen.test.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
  ts/features/fci/utils/__tests__/signatureFields.test.ts
  ts/features/fci/utils/signatureFields.ts
Labels: Firma con IO

#4594 chore(Firma con IO): [SFEQS-1650] Remove unused action
  ts/features/fci/analytics/index.ts
  ts/features/fci/saga/index.ts
  ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
  ts/features/fci/store/actions/index.ts
Labels: Firma con IO

#4599 chore(Firma con IO): [SFEQS-1648] Refactor FCI polling action
  ts/features/fci/analytics/index.ts
  ts/features/fci/saga/networking/handleCreateFilledDocument.ts
  ts/features/fci/store/actions/index.ts
  ts/features/fci/store/reducers/__tests__/fciPollFilledDocument.test.ts
  ts/features/fci/store/reducers/fciPollFilledDocument.ts
Labels: Firma con IO

#4603 fix(Firma con IO): [SFEQS-1342] Update abort signature flow bottom sheet copy
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/fci/store/reducers/fciSignatureRequest.ts
Labels: Firma con IO

#4551 chore: [IOAPPFD0-83] Add the new `ListItemNav` and `ListItemNavAlert` components
  ts/components/FeatureInfo/index.tsx
  ts/components/core/ContentWrapper/index.tsx
  ts/components/core/icons/Icon.tsx
  ts/components/core/typography/NewH6.tsx
  ts/components/core/variables/IOColors.ts
  ts/components/core/variables/IOSpacing.ts
  ts/components/core/variables/IOStyles.ts
  ts/components/screens/ListItemComponent.tsx
  ts/components/ui/ListItemNav.tsx
  ts/components/ui/ListItemNavAlert.tsx
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/core/DSIcons.tsx
  ts/features/design-system/core/DSLayout.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/features/idpay/common/components/CardLogo.tsx
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: Design System, Dark mode 🌝

#4573 chore: [IOAPPFD0-92] Add the new icons to the main Navbar
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ProfileTabIcon.tsx
  ts/components/ScanTabIcon.tsx
  ts/components/core/icons/Icon.tsx
  ts/components/core/icons/svg/IconNavDocuments.tsx
  ts/components/core/icons/svg/IconNavMessages.tsx
  ts/components/core/icons/svg/IconNavProfile.tsx
  ts/components/core/icons/svg/IconNavScan.tsx
  ts/components/core/icons/svg/IconNavServices.tsx
  ts/components/core/icons/svg/IconNavWallet.tsx
  ts/components/core/icons/svg/originals/IconNavDocuments.svg
  ts/components/core/icons/svg/originals/IconNavMessages.svg
  ts/components/core/icons/svg/originals/IconNavProfile.svg
  ts/components/core/icons/svg/originals/IconNavScan.svg
  ts/components/core/icons/svg/originals/IconNavServices.svg
  ts/components/core/icons/svg/originals/IconNavWallet.svg
  ts/components/ui/TabIconComponent.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/params/MainTabParamsList.ts
Labels: enhancement, Design System

#4597 chore: [IOAPPFD0-96] Update typographic styles of the new `Alert` component
  ts/components/Alert/index.tsx
  ts/components/core/IOBadge.tsx
  ts/components/core/typography/NewH4.tsx
  ts/components/ui/ButtonLink.tsx
  ts/features/design-system/core/DSButtons.tsx
  ts/features/idpay/initiative/timeline/components/TimelineRefundDetailsComponent.tsx
Labels: Design System

#4622 fix(Firma con IO): [SFEQS-1672] Fix analytics event category and type
  ts/features/fci/analytics/index.ts
Labels: Firma con IO

#4632 chore: [IOAPPFD0-100] Add the new generic `ListItemInfo` component
  ts/components/ui/ListItemInfo.tsx
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/core/DSListItems.tsx
Labels: Design System

#4623 feat: [IOCOM-174] Grouping of messages, PN and service/notification analytics events
  ts/boot/configurePushNotification.ts
  ts/components/messages/hooks/useMessageOpening.tsx
  ts/features/messages/analytics/index.ts
  ts/features/messages/hooks/useAttachmentDownload.tsx
  ts/features/messages/saga/networking/downloadAttachment.ts
  ts/features/pn/analytics/index.ts
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessageTimelineCTA.tsx
  ts/features/pn/components/PnServiceCTA.tsx
  ts/features/pn/screens/PnAttachmentPreview.tsx
  ts/sagas/messages/watchThirdPartyMessageSaga.ts
  ts/sagas/notifications.ts
  ts/sagas/startup/loadServiceDetailRequestHandler.ts
  ts/screens/messages/MessageAttachment.tsx
  ts/screens/messages/MessageRouterScreen.tsx
  ts/screens/wallet/payment/NewTransactionSummaryScreen.tsx
  ts/utils/analytics.ts
  ts/utils/messages.ts
Labels: IO-Comunicazione

#4640 fix: [IOBP-53] Fix IDPay initiative bonus counters
  ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
Labels: IDPay

#4608 feat(Firma con IO): [SFEQS-1265] Add the signing flow without signature fields
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fci/hooks/useFciNoSignatureFields.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/utils/__tests__/signatureFields.test.ts
  ts/features/fci/utils/signatureFields.ts
Labels: Firma con IO

#4637 fix: [IOBP-31] Fix privacy button in IDPay beneficiary details screen
  package.json
  ts/features/design-system/core/DSListItems.tsx
  ts/features/idpay/initiative/details/components/BeneficiaryDetailsContent.tsx
  ts/features/idpay/initiative/details/saga/__test__/handleGetTimelinePage.test.ts
  ts/features/idpay/initiative/details/screens/BeneficiaryDetailsScreen.tsx
  ts/features/idpay/initiative/details/store/__test__/store.test.ts
  ts/features/idpay/initiative/timeline/saga/__tests__/handleGetTimelineDetails.test.ts
  ts/features/idpay/initiative/timeline/store/__test__/store.test.ts
  ts/features/idpay/onboarding/xstate/services.ts
Labels: IDPay

#4644 chore: [IOAPPFD0-103] Focus of `ListItemNav` when touch ends
  ts/components/ui/ListItemNav.tsx
Labels: Bug 🐞, Design System

#4621 fix: [IABT-1478] Fix visual regression of the `CgnMerchantsDiscountItem` component
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
Labels: Bug 🐞, Carta Giovani Nazionale

#4635 feat(Firma con IO): [SFEQS-1630] Add context based assistance
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
Labels: Firma con IO

#4634 chore: [IOAPPFD0-101] Add the new `ListItemAction` component
  ts/components/ui/ListItemAction.tsx
  ts/features/design-system/core/DSListItems.tsx
Labels: Design System, Dark mode 🌝

#4583 fix(Firma con IO): [SFEQS-1638] Fix json parse error unmanaged
  ts/features/fci/screens/FciRouterScreen.tsx
Labels: Firma con IO

#4660 chore: [IOAPPFD0-106] Add the new `emptyArchive` and `umbrellaNew` pictograms
  ts/components/core/pictograms/Pictogram.tsx
  ts/components/core/pictograms/svg/PictogramEmptyArchive.tsx
  ts/components/core/pictograms/svg/PictogramUmbrellaNew.tsx
  ts/components/core/pictograms/svg/originals/PictogramEmptyArchive.svg
  ts/components/core/pictograms/svg/originals/PictogramUmbrellaNew.svg
Labels: Design System

#4661 chore: [IOAPPFD0-107] Update main app grid with new side margin
  ts/components/core/variables/IOSpacing.ts
Labels: Design System

#4616 chore: [IOAPPFD0-99] Make the entire `Alert` pressable when `action` is set
  ts/components/Alert/index.tsx
  ts/components/ui/ButtonLink.tsx
  ts/features/design-system/core/DSButtons.tsx
Labels: Design System

#4662 feat: [IOCOM-257] Added lollipop headers to third-party endpoints
  ts/api/backend.ts
  ts/sagas/messages/watchMessagePrecondition.ts
  ts/sagas/messages/watchThirdPartyMessageSaga.ts
Labels: IO-Comunicazione

#4666 chore(Firma con IO): [SFEQS-1706] Refactor ErrorComponent to use pictograms
  ts/features/fci/components/ErrorComponent.tsx
  ts/features/fci/components/GenericErrorComponent.tsx
  ts/features/fci/components/SuccessComponent.tsx
  ts/features/fci/components/__tests__/ErrorComponent.test.tsx
  ts/features/fci/screens/FciRouterScreen.tsx
Labels: Firma con IO
