Repository pagopa/io-app, pull requests merged in 2023-01, with the labels that each got.

#4256 chore: [IAI-255] Advice & Banners' inventory
  ts/components/AdviceComponent.tsx
  ts/components/ExperimentalFeaturesBanner.tsx
  ts/components/SectionStatus/index.tsx
  ts/components/box/InfoBox.tsx
  ts/components/screens/BetaBannerComponent.tsx
  ts/screens/showroom/Showroom.tsx
  ts/screens/showroom/components/FullWidthComponent.tsx
  ts/screens/showroom/components/ShowroomSection.tsx
  ts/screens/showroom/core/AdviceShowroom.tsx
  ts/screens/showroom/core/OthersShowroom.tsx
Labels: Design System

#4270 feat(IDPay): [IODPAY-70] Introduction of "add new iban" IDPAY pages
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/initiative/configuration/iban/api/client.ts
  ts/features/idpay/initiative/configuration/iban/screens/IbanConfigurationLandingScreen.tsx
  ts/features/idpay/initiative/configuration/iban/screens/IbanOnboardingScreen.tsx
  ts/features/idpay/initiative/configuration/navigation/navigator.tsx
  ts/features/idpay/initiative/configuration/xstate/actions.ts
  ts/features/idpay/initiative/configuration/xstate/context.ts
  ts/features/idpay/initiative/configuration/xstate/events.ts
  ts/features/idpay/initiative/configuration/xstate/machine.ts
  ts/features/idpay/initiative/configuration/xstate/provider.tsx
  ts/features/idpay/initiative/configuration/xstate/services.ts
Labels: IDPay

#4247 feat(IDPay): [IODPAY-67] Add IBAN enrollment to IDPay initiative configuration
  ts/features/idpay/initiative/configuration/iban/screens/IbanEnrollmentScreen.tsx
  ts/features/idpay/initiative/configuration/navigation/navigator.tsx
  ts/features/idpay/initiative/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/initiative/configuration/xstate/actions.ts
  ts/features/idpay/initiative/configuration/xstate/context.ts
  ts/features/idpay/initiative/configuration/xstate/events.ts
  ts/features/idpay/initiative/configuration/xstate/machine.ts
  ts/features/idpay/initiative/configuration/xstate/selectors.ts
  ts/features/idpay/initiative/configuration/xstate/services.ts
  ts/features/idpay/initiative/details/components/InitiativeSettingsComponent.tsx
Labels: IDPay

#4262 fix(Firma con IO): [SFEQS-1274] Add padding between signature field title and related checkbox
  ts/features/fci/components/SignatureFieldItem.tsx
  ts/features/fci/components/__tests__/__snapshots__/SignatureFieldItem.test.tsx.snap
Labels: Firma con IO

#4246 chore: [IAI-253] List items' inventory
  ts/screens/showroom/Showroom.tsx
  ts/screens/showroom/core/ListItemsShowroom.tsx
  ts/screens/showroom/core/PictogramsShowroom.tsx
Labels: Design System

#4277 chore(IDPay): [IODPAY-72] Add IDPay onboarding deeplink handling
  ts/features/idpay/onboarding/navigation/navigator.tsx
  ts/navigation/AppStackNavigator.tsx
Labels: IDPay

#4285 chore: [IAI-259] Remove width limit applied to the text in the Services' metadata
  ts/components/services/ServiceMetadata/InformationRow.tsx
  ts/components/services/ServiceMetadata/__tests__/__snapshots__/InformationRow.test.tsx.snap
  ts/components/services/ServiceMetadata/index.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
Labels: enhancement, Design System

#4282 feat(IDPay): [IODPAY-74] Add ability to remove payment instruments from an IDPay initiative
  ts/features/idpay/initiative/configuration/components/InstrumentEnrollmentSwitch.tsx
  ts/features/idpay/initiative/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/initiative/configuration/xstate/events.ts
  ts/features/idpay/initiative/configuration/xstate/machine.ts
  ts/features/idpay/initiative/configuration/xstate/selectors.ts
  ts/features/idpay/initiative/configuration/xstate/services.ts
Labels: IDPay

#4275 chore: [IAI-221] Add sublevel navigation to `Design System` page (former `UI Showroom`)
  README.md
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/core/icons/README.md
  ts/components/core/logos/README.md
  ts/components/core/pictograms/README.md
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/components/DSAssetViewerBox.tsx
  ts/features/design-system/components/DSComponentViewerBox.tsx
  ts/features/design-system/components/DSFullWidthComponent.tsx
  ts/features/design-system/components/DSIconViewerBox.tsx
  ts/features/design-system/components/DSLogoPaymentViewerBox.tsx
  ts/features/design-system/components/DesignSystemScreen.tsx
  ts/features/design-system/components/DesignSystemSection.tsx
  ts/features/design-system/core/DSAccordion.tsx
  ts/features/design-system/core/DSAdvice.tsx
  ts/features/design-system/core/DSButtons.tsx
  ts/features/design-system/core/DSColors.tsx
  ts/features/design-system/core/DSIcons.tsx
  ts/features/design-system/core/DSLegacyIllustrations.tsx
  ts/features/design-system/core/DSLegacyPictograms.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/features/design-system/core/DSLogos.tsx
  ts/features/design-system/core/DSPictograms.tsx
  ts/features/design-system/core/DSSelection.tsx
  ts/features/design-system/core/DSTextFields.tsx
  ts/features/design-system/core/DSToastNotifications.tsx
  ts/features/design-system/core/DSTypography.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/showroom/Showroom.tsx
  ts/screens/showroom/core/PictogramsShowroom.tsx
Labels: enhancement, Design System

#4268 Update index.yml 🇩🇪
  locales/de/index.yml
Labels: German 🇩🇪

#4263 Update index.yml 🇩🇪
  locales/de/index.yml
Labels: German 🇩🇪

#4264 Update index.yml 🇩🇪
  locales/de/index.yml
Labels: German 🇩🇪

#4265 Update index.yml 🇩🇪
  locales/de/index.yml
Labels: German 🇩🇪

#4266 Update index.yml 🇩🇪
  locales/de/index.yml
Labels: German 🇩🇪

#4287 Update index.yml 🇩🇪
  locales/de/index.yml
Labels: German 🇩🇪

#4300 chore(IDPay): [IODPAY-88] Add I18n for card activation status
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/common/labels.ts
Labels: IDPay

#4301 fix(IDPay): [IODPAY-89] Updated iban yaml version
  package.json
Labels: IDPay

#4260 fix(Firma con IO): [SFEQS-1271] Introducing URL polling to wait availability of filled document
  ts/features/fci/saga/index.ts
  ts/features/fci/saga/networking/__tests__/handleCreateFilledDocument.test.ts
  ts/features/fci/saga/networking/handleCreateFilledDocument.ts
  ts/features/fci/screens/__tests__/FciQtspClausesScreen.test.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/store/actions/index.ts
  ts/features/fci/store/reducers/__tests__/fciPollFilledDocument.test.ts
  ts/features/fci/store/reducers/fciPollFilledDocument.ts
  ts/features/fci/store/reducers/index.ts
Labels: Firma con IO

#4291 feat(Firma con IO): [SFEQS-1301] Using a new remote flag based on min app version supported by the feature
  package.json
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: Firma con IO

#4295 chore: [IOAPPCIT-24] Add a crypto key pair generation test at application startup.
  .circleci/config.yml
  .node-version
  android/build.gradle
  ios/Podfile.lock
  package.json
  ts/sagas/startup.ts
  ts/sagas/startup/generateCryptoKeyPair.ts
  ts/store/reducers/backendStatus.ts
  ts/utils/crypto.ts
  yarn.lock
Labels: legal-approved ⚖️ ✅

#4305 chore(IDPay): [IODPAY-90] Add `IdPayConfig` remote feature flag
  package.json
  ts/navigation/AppStackNavigator.tsx
  ts/screens/wallet/WalletHomeScreen.tsx
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: IDPay

#4292 chore: [IAI-261] Add new `Spacer` component
  ts/components/core/spacer/Spacer.tsx
  ts/components/core/variables/IOSpacing.ts
  ts/features/design-system/components/DSSpacerViewerBox.tsx
  ts/features/design-system/core/DSSpacing.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
Labels: enhancement, Design System

#4297 fix(Firma con IO): [SFEQS-1252] Update section header component in signature section list
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
Labels: Firma con IO

#4273 fix(Firma con IO): [SFEQS-1281] Add a flag to track PDF load completion
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/screens/valid/FciThankyouScreen.tsx
Labels: Firma con IO

#4294 feat(IDPay): [IODPAY-77] Addition of paginated operation list
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSListItems.tsx
  ts/features/idpay/initiative/configuration/xstate/actions.ts
  ts/features/idpay/initiative/details/components/InitiativeTimelineComponent.tsx
  ts/features/idpay/initiative/details/components/TimelineOperationListItem.tsx
  ts/features/idpay/initiative/details/components/TimelineTransactionCards.tsx
  ts/features/idpay/initiative/details/navigation/index.tsx
  ts/features/idpay/initiative/details/saga/__test__/handleGetTimelinePage.test.ts
  ts/features/idpay/initiative/details/saga/handleGetTimelinePage.ts
  ts/features/idpay/initiative/details/saga/index.ts
  ts/features/idpay/initiative/details/screens/InitiativeDetailsScreen.tsx
  ts/features/idpay/initiative/details/screens/OperationsListScreen.tsx
  ts/features/idpay/initiative/details/store/__test__/store.test.ts
  ts/features/idpay/initiative/details/store/actions/index.ts
  ts/features/idpay/initiative/details/store/index.ts
  ts/features/idpay/initiative/details/utils/hooks.ts
  ts/features/idpay/wallet/components/IDPayCardsInWalletContainer.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/navigation/routes.ts
Labels: IDPay

#4315 Update index.yml
  locales/de/index.yml
Labels: German 🇩🇪

#4316 feat(IDPay): [IODPAY-83] Revert instrument state if enrollment modal is dismissed
  ts/features/idpay/initiative/configuration/screens/InstrumentsEnrollmentScreen.tsx
Labels: IDPay

#4293 chore: [IOAPPCOM-42] Add mixpanel events for Premium
  ts/boot/configurePushNotification.ts
  ts/sagas/startup/checkNotificationsPreferencesSaga.ts
  ts/screens/messages/MessageRouterScreen.tsx
  ts/screens/onboarding/OnboardingNotificationsInfoScreenConsent.tsx
  ts/screens/profile/NotificationsPreferencesScreen.tsx
  ts/utils/analytics.ts
Labels: legal-approved ⚖️ ✅

#4314 feat: [IOAPPCIT-33] Refactor `IdpsGrid` to enable TeamSystem ID
  ts/components/IdpsGrid.tsx
  ts/components/core/pictograms/PictogramSection.tsx
  ts/components/core/pictograms/svg/PictogramSectionSmile.tsx
  ts/components/core/pictograms/svg/originals/SectionPictogramSmile.svg
  ts/components/core/variables/IOStyles.ts
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PspRadioItem.test.tsx.snap
  ts/screens/authentication/IdpSelectionScreen.tsx
  ts/utils/idps.ts
Labels: enhancement

#4329 feat(IDPay): [IODPAY-95] Add IDPay test/env switch
  .env.local
  .env.production
  ts/config.ts
  ts/features/idpay/initiative/configuration/xstate/provider.tsx
  ts/features/idpay/initiative/details/saga/index.ts
  ts/features/idpay/onboarding/xstate/provider.tsx
  ts/features/idpay/wallet/saga/index.ts
Labels: IDPay

#4313 feat(IDPay): [IODPAY-78] Show operation details bottom sheet in initiative timeline
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/idpay/initiative/details/components/InitiativeTimelineComponent.tsx
  ts/features/idpay/initiative/details/components/TimelineDetailsBottomSheet.tsx
  ts/features/idpay/initiative/details/components/TimelineOperationListItem.tsx
  ts/features/idpay/initiative/details/saga/__test__/handleGetTimelineDetails.test.ts
  ts/features/idpay/initiative/details/saga/handleGetTimelineDetails.ts
  ts/features/idpay/initiative/details/saga/index.ts
  ts/features/idpay/initiative/details/screens/OperationsListScreen.tsx
  ts/features/idpay/initiative/details/store/__test__/store.test.ts
  ts/features/idpay/initiative/details/store/actions/index.ts
  ts/features/idpay/initiative/details/store/index.ts
Labels: IDPay

#4324 fix(IDPay): [IODPAY-94] Addition of error handling for instruments and iban list load failure
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/initiative/configuration/components/InstrumentEnrollmentSwitch.tsx
  ts/features/idpay/initiative/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/initiative/configuration/xstate/actions.ts
  ts/features/idpay/initiative/configuration/xstate/context.ts
  ts/features/idpay/initiative/configuration/xstate/failure.ts
  ts/features/idpay/initiative/configuration/xstate/machine.ts
  ts/features/idpay/initiative/configuration/xstate/selectors.ts
  ts/features/idpay/initiative/configuration/xstate/services.ts
Labels: IDPay

#4290 feat(IDPay): [IODPAY-79] Add instruments list check in IDPay initiative configuration
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/common/labels.ts
  ts/features/idpay/initiative/configuration/navigation/navigator.tsx
  ts/features/idpay/initiative/configuration/screens/ConfigurationSuccessScreen.tsx
  ts/features/idpay/initiative/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/initiative/configuration/xstate/actions.ts
  ts/features/idpay/initiative/configuration/xstate/context.ts
  ts/features/idpay/initiative/configuration/xstate/events.ts
  ts/features/idpay/initiative/configuration/xstate/machine.ts
  ts/features/idpay/initiative/configuration/xstate/selectors.ts
Labels: IDPay

#4330 feat(Firma con IO): [SFEQS-1330] Update copy in QTSP clauses screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
Labels: Firma con IO
