Repository pagopa/io-app, pull requests merged in 2023-11, with the labels that each got.

#5176 feat: [IOCOM-499] SEND selected payment update after selection
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePaymentItem.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/reducers/payments.ts
  ts/features/pn/utils/index.ts
Labels: IO-Comunicazione

#5164 chore(IT Wallet): [SIW-432] Update `ItwDiscoveryInfoScreen` with new DS
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/assets/discovery/itw_card.png
  ts/features/it-wallet/assets/discovery/itw_card@2x.png
  ts/features/it-wallet/assets/discovery/itw_card@3x.png
  ts/features/it-wallet/assets/discovery/itw_hero.png
  ts/features/it-wallet/assets/discovery/itw_hero@2x.png
  ts/features/it-wallet/assets/discovery/itw_hero@3x.png
  ts/features/it-wallet/components/ItwActionBanner.tsx
  ts/features/it-wallet/components/ItwFooterVerticalButtons.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/credentials/ItwCredentialIssuingInfoScreen.tsx
  ts/features/it-wallet/screens/discovery/ItwDiscoveryInfoScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationDataScreen.tsx
Labels: IT Wallet

#5177 feat: [IOCOM-642] Handle of ONGOING status on SEND's payments
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/utils/strings.ts
  ts/features/pn/components/MessagePaymentItem.tsx
Labels: IO-Comunicazione

#5157 chore: [IOPID-897] Change IDP screen visualization
  ts/screens/authentication/IdpSelectionScreen.tsx
Labels: IO-A&I

#5182 feat: [IOCOM-643] Back to SEND message screen upon successful payment completion
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePaymentItem.tsx
  ts/features/pn/utils/index.ts
  ts/screens/wallet/payment/PaymentOutcomeCodeMessage.tsx
Labels: IO-Comunicazione

#5167 feat: [IOCOM-457] Navigate to the attachment preview screen
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageF24.tsx
  ts/features/pn/components/__test__/MessageF24.test.tsx
  ts/features/pn/hooks/useF24BottomSheet.tsx
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/navigation/params.ts
  ts/features/pn/screens/AttachmentPreviewScreen.tsx
Labels: IO-Comunicazione

#5179 feat(Firma con IO): [SFEQS-1058] Update `io-backend` definitions to `v13.19.1`
  package.json
Labels: Firma con IO

#5186 fix: [IOBP-384] Header transaction summary safe area view
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
Labels: Bug 🐞, IO-Bonus e pagamenti

#5185 fix: [IOBP-386, IOBP-374] CTA transaction summary padding on Android
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
Labels: Bug 🐞, IO-Bonus e pagamenti

#5190 feat: [IOCOM-657] Remove payments' bottom sheet reference in cancelled SEND message
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessagePaymentBottomSheet.tsx
  ts/features/pn/components/MessagePayments.tsx
Labels: IO-Comunicazione

#5191 feat: [IOCOM-658] Remove the F24 section on cancelled SEND message
  ts/features/pn/components/MessageDetails.tsx
Labels: IO-Comunicazione

#5188 fix: [IOBP-332] Add correct pictograms to camera permission view in barcode scan screen
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
  ts/features/barcode/components/CameraPermissionView.tsx
Labels: IO-Bonus e pagamenti

#5136 chore: [IOBP-341] Update IDPayPaymentCodeInputScreen to use new DS components
  ts/features/design-system/core/DSLogos.tsx
  ts/features/design-system/core/DSModules.tsx
  ts/features/idpay/payment/screens/IDPayPaymentCodeInputScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5171 feat: [IOPID-1062] Change copy
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-A&I

#5193 feat: [IOCOM-461] Add F24 Mixpanel events
  ts/features/messages/components/MessageAttachmentPreview.tsx
  ts/features/messages/hooks/useAttachmentDownload.tsx
  ts/features/pn/analytics/index.ts
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageF24.tsx
  ts/features/pn/screens/AttachmentPreviewScreen.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/screens/PnAttachmentPreview.tsx
  ts/features/pn/utils/index.ts
Labels: IO-Comunicazione

#5198 feat: [IOCOM-460] Analytics events for PN multiple payments
  ts/features/pn/analytics/index.ts
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/sagas/watchPaymentStatusSaga.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/pn/utils/index.ts
  ts/utils/payment.ts
Labels: IO-Comunicazione

#5196 feat: [IOPID-296] Update the generate nonce and set it as mandatory
  .env.local
  .env.production
  package.json
  ts/config.ts
  ts/features/fastLogin/backend/index.ts
  ts/features/fastLogin/backend/mockedClients.ts
  ts/features/fastLogin/saga/tokenRefreshSaga.ts
  ts/screens/profile/ProfileMainScreen.tsx
Labels: IO-A&I

#5155 feat: [IOBP-201,IOBP-284] New wallet success outcome handling
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/common/components/GenericErrorComponent.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingSuccess.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingWebView.tsx
  ts/features/walletV3/onboarding/screens/WalletOnboardingStartScreen.tsx
  ts/features/walletV3/onboarding/types/index.ts
  ts/features/walletV3/onboarding/utils/index.ts
Labels: IO-Bonus e pagamenti

#5172 chore: [IOPID-1075] Remove what's new bottomsheet
  ts/features/whatsnew/hook/useWhatsNew.tsx
  ts/features/whatsnew/screen/FastLoginWhatsNew.tsx
  ts/features/whatsnew/store/actions/index.ts
  ts/features/whatsnew/store/reducers/index.ts
  ts/features/whatsnew/versions.ts
  ts/sagas/startup.ts
  ts/sagas/startup/checkAcceptedTosSaga.ts
  ts/screens/messages/MessagesHomeScreen.tsx
  ts/screens/onboarding/OnboardingTosScreen.tsx
Labels: IO-A&I

#5028 feat: [IOPLT-136] `HeaderSecondLevel` integration through react-navigation
  ts/components/ui/HeaderSecondLevel.tsx
  ts/features/design-system/core/DSHeaderSecondLevel.tsx
  ts/features/design-system/core/DSHeaderSecondLevelWithSectionTitle.tsx
  ts/hooks/useHeaderSecondLevel.tsx
  ts/hooks/useStartSupportRequest.ts
  ts/navigation/ProfileNavigator.tsx
  ts/screens/profile/PrivacyMainScreen.tsx
  ts/screens/profile/TosScreen.tsx
  ts/screens/profile/__test__/TosScreen.test.tsx
Labels: keep open, Design System

#5205 fix: [IOBP-397] CGN e2e tests
  ts/features/bonus/cgn/screens/activation/CgnActivationCompletedScreen.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
Labels: Bug 🐞, Carta Giovani Nazionale

#5204 feat: [IOPLT-224,IOPLT-231] Upgrades to latest DS library version and migrates components affected
  package.json
  ts/components/screens/OperationResultScreenContent.tsx
  ts/components/screens/WizardScreen.tsx
  ts/components/ui/GradientBottomActions.tsx
  ts/components/ui/GradientScrollView.tsx
  ts/features/design-system/core/DSGradientScroll.tsx
  ts/features/design-system/core/DSIcons.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/features/idpay/details/components/__tests__/__snapshots__/InitiativeDetailsBaseScreenComponent.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/PnPaidPaymentScreen.test.tsx.snap
  ts/screens/authentication/NewOptInScreen.tsx
  ts/screens/onboarding/UnlockAccessScreen.tsx
  ts/screens/wallet/payment/components/TransactionSummary.tsx
  yarn.lock
Labels: Design System

#5194 chore: [IOBP-334] Add `productPagoPA` icon to pagoPA notice pay action in barcode scan screen
  ts/features/barcode/screens/BarcodeScanScreen.tsx
Labels: IO-Bonus e pagamenti

#5202 feat: [IOCOM-571] Remove `pnNoticesF24Enabled` feature flag
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/SpecialServices/SpecialServicesCTA.tsx
  ts/config.ts
  ts/features/pn/analytics/index.ts
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageDetailsContent.tsx
  ts/features/pn/components/MessageDetailsError.tsx
  ts/features/pn/components/MessageDetailsHeader.tsx
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePaymentBottomSheet.tsx
  ts/features/pn/components/MessagePaymentItem.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/components/MessageTimeline.tsx
  ts/features/pn/components/MessageTimelineCTA.tsx
  ts/features/pn/components/PnMessageDetails.tsx
  ts/features/pn/components/PnMessageDetailsSection.tsx
  ts/features/pn/components/PnMessagePayment.tsx
  ts/features/pn/components/ServiceCTA.tsx
  ts/features/pn/components/__test__/PnMessageDetails.test.tsx
  ts/features/pn/components/__test__/PnMessagePayment.test.tsx
  ts/features/pn/navigation/actions.ts
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/navigation/params.ts
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/screens/PaidPaymentScreen.tsx
  ts/features/pn/screens/PnAttachmentPreview.tsx
  ts/features/pn/screens/PnMessageDetailsScreen.tsx
  ts/features/pn/screens/__test__/PaidPaymentScreen.test.tsx
  ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
  ts/features/pn/store/reducers/payments.ts
  ts/features/pn/store/sagas/watchPaymentUpdateRequests.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/pn/utils/index.ts
  ts/features/pn/utils/rptId.ts
Labels: IO-Comunicazione

#5208 feat: [IOPID-987] Add contextual help content
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/authentication/NewOptInScreen.tsx
Labels: IO-A&I

#5183 fix: [IOPID-878] Provide a more meaningful feedback on IdPs' 403 HTTP error
  ts/screens/authentication/IdpLoginScreen.tsx
Labels: IO-A&I

#5213 feat(IT Wallet): [SIW-623] Add credential issuance
  jest.config.js
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/it-wallet/assets/img/credentials/cards/default.png
  ts/features/it-wallet/components/ItwCredentialCard.tsx
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwRoutes.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/saga/__tests__/itwWiaSaga.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/saga/itwCredentialsSaga.ts
  ts/features/it-wallet/saga/itwPidSaga.ts
  ts/features/it-wallet/saga/new/itwIssuanceSaga.ts
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/credential/ItwPidDetails.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialAuthScreen.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialChecksScreen.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialPreviewScreen.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialsCatalogScreen.tsx
  ts/features/it-wallet/screens/credentials/ItwAddCredentialsCheckScreen.tsx
  ts/features/it-wallet/screens/credentials/ItwCredentialIssuingInfoScreen.tsx
  ts/features/it-wallet/screens/credentials/ItwCredentialPreviewScreen.tsx
  ts/features/it-wallet/screens/credentials/ItwCredentialsCatalogScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationDataScreen.tsx
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/actions/itwCredentialsActions.ts
  ts/features/it-wallet/store/actions/new/itwIssuanceActions.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwCredentialsChecksReducer.ts
  ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts
  ts/features/it-wallet/store/reducers/new/itwIssuanceReducer.ts
  ts/features/it-wallet/utils/errors/itwErrors.ts
  ts/features/it-wallet/utils/locales.ts
  ts/features/it-wallet/utils/mocks.ts
  ts/features/it-wallet/utils/types.ts
  yarn.lock
Labels: IT Wallet

#5214 feat(IT Wallet): [SIW-361] Store reset migration
  ts/features/it-wallet/store/reducers/index.ts
Labels: IT Wallet

#5215 fix(IT Wallet): [SIW-663] Update `itwTextInfo` component
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ItwTextInfo.tsx
Labels: IT Wallet

#5219 feat(IT Wallet): [SIW-667] Add details screen for an issued credential
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwRoutes.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/credential/ItwCredentialDetailsScreen.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialPreviewScreen.tsx
Labels: IT Wallet

#5221 chore(IT Wallet): [SIW-670] Add issuer name in credential preview
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
Labels: IT Wallet

#5220 chore(IT Wallet): [SIW-661] Mock claims order
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#5218 chore(IT Wallet): [SIW-664] Format date in credentials claims list
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
  ts/features/it-wallet/utils/locales.ts
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#5217 chore(IT Wallet): [SIW-666] Enable experimental design system by default
  ts/navigation/AppStackNavigator.tsx
Labels: IT Wallet

#5223 feat: [IOCOM-667] Failure logging for messages' sagas
  ts/features/messages/analytics/index.ts
  ts/features/messages/utils/index.ts
  ts/sagas/messages/watchLoadMessageById.ts
  ts/sagas/messages/watchLoadMessageDetails.ts
  ts/sagas/messages/watchLoadNextPageMessages.ts
  ts/sagas/messages/watchLoadPreviousPageMessages.ts
  ts/sagas/messages/watchReloadAllMessages.ts
  ts/sagas/messages/watchUpsertMessageStatusAttribues.ts
Labels: IO-Comunicazione

#5197 chore(IT Wallet): [SIW-636] Update provider list screen with new DS
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ListItems/ListItemItw.tsx
  ts/features/it-wallet/screens/discovery/ItwDiscoveryProviderInfoScreen.tsx
Labels: IT Wallet

#5141 chore: [IOPID-1015] Biometric refinement
  ts/sagas/startup/onboarding/biometric/checkAcknowledgedFingerprintSaga.ts
  ts/screens/onboarding/biometric&securityChecks/FingerprintScreen.tsx
  ts/screens/profile/SecurityScreen.tsx
  ts/store/reducers/index.ts
  ts/store/reducers/onboarding.ts
  ts/store/reducers/persistedPreferences.ts
  ts/utils/__tests__/biometrics.test.ts
  ts/utils/biometrics.ts
Labels: IO-A&I

#5222 chore(IT Wallet): [SIW-660] Force scroll to bottom in credential preview
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialPreviewScreen.tsx
Labels: IT Wallet

#5210 fix: [PE-494] CGN test ids for e2e tests
  ts/features/bonus/cgn/screens/activation/CgnAlreadyActiveScreen.tsx
Labels: Bug 🐞, Carta Giovani Nazionale

#5192 feat: [IOBP-375] New wallet onboarding error outcome handling
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/walletV3/common/components/GenericErrorComponent.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingError.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingWebView.tsx
  ts/features/walletV3/onboarding/screens/WalletOnboardingStartScreen.tsx
  ts/features/walletV3/onboarding/types/index.ts
  ts/features/walletV3/onboarding/utils/index.ts
Labels: IO-Bonus e pagamenti

#5200 chore: [IOBP-392] Refactor `TimelineOperationListItem` component
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/common/utils/strings.ts
  ts/features/idpay/details/components/InitiativeTimelineComponent.tsx
  ts/features/idpay/details/components/TimelineOperationListItem.tsx
  ts/features/idpay/details/components/__tests__/TimelineOperationListItem.test.tsx
  ts/features/idpay/details/screens/OperationsListScreen.tsx
  ts/features/idpay/timeline/components/TimelineDetailsBottomSheet.tsx
  ts/features/idpay/timeline/components/TimelineRefundDetailsComponent.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5230 chore(IT Wallet): [SIW-676] Add released by claim for credentials
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
  ts/features/it-wallet/saga/new/itwIssuanceSaga.ts
  ts/features/it-wallet/screens/credential/ItwCredentialDetailsScreen.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialPreviewScreen.tsx
  ts/features/it-wallet/store/actions/new/itwIssuanceActions.ts
  ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts
  ts/features/it-wallet/store/reducers/new/itwIssuanceReducer.ts
Labels: IT Wallet

#5227 fix(IT Wallet): [SIW-674] Untranslated mock data
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/credential/ItwPidDetails.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialsCatalogScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationChecksScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationDataScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationResultScreen.tsx
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#5228 chore(IT Wallet): [SIW-624] Add navigation to missing feature screen
  ts/features/it-wallet/screens/credential/ItwCredentialDetailsScreen.tsx
  ts/features/it-wallet/screens/credential/ItwPidDetails.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
Labels: IT Wallet

#5231 chore(IT Wallet): [SIW-673] Update credential details screen
  ts/features/it-wallet/components/ItwClaimsWrapper.tsx
  ts/features/it-wallet/screens/credential/ItwCredentialDetailsScreen.tsx
  ts/features/it-wallet/screens/credential/ItwPidDetails.tsx
Labels: IT Wallet

#5233 fix(IT Wallet): [SIW-689] Add bottom padding in continue view
  ts/features/it-wallet/components/ItwContinueView.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialChecksScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/ItwRpInitScreen.tsx
  ts/features/it-wallet/screens/presentation/crossdevice/new/ItwPresentationChecksScreen.tsx
Labels: IT Wallet

#5146 feat: [IOBP-348] Addition of bottomSheet in idPay discount initiative CTA
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/details/hooks/useIdPayDiscountDetailsBottomSheet.tsx
  ts/features/idpay/details/hooks/useInitiativeTimelineFetcher.tsx
  ts/features/idpay/details/screens/InitiativeDetailsScreen.tsx
  ts/features/idpay/details/screens/OperationsListScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#5235 chore(IT Wallet): [SIW-696] Update `io-react-native-wallet`
  package.json
  yarn.lock
Labels: IT Wallet

#5234 feat: [IOCOM-662] Add unit tests for F24 feature
  ts/features/messages/components/__test__/MessageAttachmentPreview.test.tsx
  ts/features/messages/components/__test__/MessageAttachments.test.tsx
  ts/features/pn/components/__test__/MessageDetails.test.tsx
  ts/features/pn/components/__test__/MessageF24.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageF24.test.tsx.snap
Labels: IO-Comunicazione

#5178 chore: [IOPID-740] Zendesk token refresh handling
  package.json
  ts/features/fastLogin/saga/tokenRefreshSaga.ts
  ts/features/zendesk/saga/index.ts
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/features/zendesk/screens/ZendeskSeeReportsRouters.tsx
  ts/features/zendesk/store/actions/index.ts
  ts/features/zendesk/store/reducers/index.ts
  ts/sagas/startup.ts
  ts/utils/supportAssistance.ts
  yarn.lock
Labels: IO-A&I

#5241 chore(IT Wallet): [SIW-706] Prettier after rebase
  ts/features/it-wallet/saga/itwCieSaga.ts
Labels: IT Wallet

#5240 chore(IT Wallet): [SIW-703] Update enable DS by default workaround
  ts/navigation/AppStackNavigator.tsx
Labels: IT Wallet

#5246 chore(IT Wallet): [SIW-662] Remove legacy useItwDataProcessing hook
  ts/features/it-wallet/hooks/useItwDataProcessing.tsx
  ts/features/it-wallet/screens/credential/issuing/ItwCredentialAuthScreen.tsx
Labels: IT Wallet

#5245 chore(IT Wallet): [SIW-604] Refactor screens directory structure
  ts/features/it-wallet/assets/img/issuing/itw_card.png
  ts/features/it-wallet/assets/img/issuing/itw_card@2x.png
  ts/features/it-wallet/assets/img/issuing/itw_card@3x.png
  ts/features/it-wallet/assets/img/issuing/itw_hero.png
  ts/features/it-wallet/assets/img/issuing/itw_hero@2x.png
  ts/features/it-wallet/assets/img/issuing/itw_hero@3x.png
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/screens/generic/ItwGenericNotAvailableScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwCredentialAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwCredentialCatalogScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwCredentialChecksScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwCredentialPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidAddingScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidAuthInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidRequestScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCieCardReaderScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCieConsentDataUsageScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCieExpiredOrInvalidScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCiePinLockedTemporarilyScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCiePinScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCieWrongPinScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/presentation/ItwPrCredentialDetails.tsx
  ts/features/it-wallet/screens/presentation/ItwPrPidDetails.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrCredentialChecksScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrCredentialDataScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrCredentialResultScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrPidChecksScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrPidDataScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrPidResultScreen.tsx
Labels: IT Wallet

#5248 chore(IT Wallet): [SIW-693,SIW-691] Add released by and issued by claims bottom sheet
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwCredentialPreviewScreen.tsx
Labels: IT Wallet

#5251 fix(IT Wallet): [SIW-697] Update credential issuer in issuing auth screen
  ts/features/it-wallet/screens/issuing/credential/ItwCredentialAuthScreen.tsx
Labels: IT Wallet

#5247 chore(IT Wallet): [SIW-677] Refactor ITW reset
  ts/features/it-wallet/hooks/useItwResetFlow.tsx
  ts/features/it-wallet/store/actions/itwLifecycleActions.ts
  ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts
  ts/features/it-wallet/store/reducers/itwPidDecodeReducer.ts
  ts/features/it-wallet/store/reducers/itwWiaReducer.ts
Labels: IT Wallet

#5189 feat: [IOBP-373] New wallet details screen adaption
  .env.local
  .env.production
  package.json
  ts/features/walletV3/common/api/client.ts
  ts/features/walletV3/common/components/WalletDetailsPagoPaPaymentCapability.tsx
  ts/features/walletV3/common/components/WalletDetailsPaymentMethodFeatures.tsx
  ts/features/walletV3/common/components/WalletDetailsPaymentMethodInitiatives.tsx
  ts/features/walletV3/common/components/WalletDetailsPaymentMethodSettings.tsx
  ts/features/walletV3/common/saga/index.ts
  ts/features/walletV3/common/store/actions/index.ts
  ts/features/walletV3/common/store/reducers/index.ts
  ts/features/walletV3/common/utils/index.ts
  ts/features/walletV3/details/components/WalletDetailsPaymentMethodScreen.tsx
  ts/features/walletV3/details/navigation/navigator.tsx
  ts/features/walletV3/details/saga/handleDeleteWalletDetails.ts
  ts/features/walletV3/details/saga/handleGetWalletDetails.ts
  ts/features/walletV3/details/saga/index.ts
  ts/features/walletV3/details/screens/WalletDetailsScreen.tsx
  ts/features/walletV3/details/store/actions/index.ts
  ts/features/walletV3/details/store/index.ts
  ts/features/walletV3/onboarding/components/WalletOnboardingPaymentMethodsList.tsx
  ts/features/walletV3/onboarding/screens/WalletOnboardingStartScreen.tsx
  ts/features/walletV3/onboarding/utils/index.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/utils/dates.ts
Labels: IO-Bonus e pagamenti

#5088 feat: [IOPLT-184] Base Screen component wrapper header with animated title
  ts/components/ui/RNavScreenWithLargeHeader.tsx
  ts/features/design-system/core/DSHeaderSecondLevel.tsx
  ts/hooks/useHeaderProps.tsx
Labels: Design System

#5113 feat: [IOPLT-162] `HeaderFirstLevel` integration
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/components/screens/DarkLayout.tsx
  ts/components/screens/TopScreenComponent.tsx
  ts/components/search/SearchButton.tsx
  ts/components/wallet/WalletHomeHeader.tsx
  ts/components/wallet/WalletLayout.tsx
  ts/hooks/useStartSupportRequest.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/screens/messages/MessagesHomeScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
  ts/screens/wallet/WalletHomeScreen.tsx
Labels: Design System

#5119 chore: [IOAPPFD0-175] Restore inertial scrolling in the `Wallet` and `Profile` main screens (iOS)
  img/icons/profile-illustration.png
  img/icons/profile-illustration@2x.png
  img/icons/profile-illustration@3x.png
  ts/components/FiscalCodeComponent.tsx
  ts/components/wallet/WalletLayout.tsx
  ts/features/design-system/core/DSLegacyPictograms.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: enhancement

#5255 chore(IT Wallet): [SIW-692] Add PIN auth during presentation
  ts/features/it-wallet/saga/itwPidSaga.ts
  ts/features/it-wallet/saga/itwRpPresentationSaga.ts
  ts/features/it-wallet/saga/itwSagaUtils.ts
  ts/features/it-wallet/saga/new/itwIssuanceSaga.ts
  ts/features/it-wallet/saga/new/itwPresentationSaga.ts
Labels: IT Wallet

#5250 fix(IT Wallet): [SIW-699] Credential image disappearing from wallet
  ts/features/it-wallet/components/ItwClaimsWrapper.tsx
  ts/features/it-wallet/components/ItwCredentialCard.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwCredentialPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/presentation/ItwPrCredentialDetails.tsx
  ts/features/it-wallet/screens/presentation/ItwPrPidDetails.tsx
  ts/features/it-wallet/utils/mocks.ts
Labels: IT Wallet

#5253 feat: [IOCOM-661] Tests for SEND multiple payments
  ts/features/pn/components/__test__/MessagePaymentItem.test.tsx
  ts/features/pn/components/__test__/MessagePayments.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessagePaymentItem.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessagePayments.test.tsx.snap
  ts/features/pn/store/reducers/__tests__/payments.test.ts
Labels: IO-Comunicazione

#5249 chore: [IOPID-1135] Fix fast-login and getNonce timeout and retry policy
  ts/features/fastLogin/backend/index.ts
  ts/features/lollipop/utils/fetch.ts
Labels: IO-A&I

#5206 chore: [IOPID-991] Integration of email validation logic in the onboarding flow and profile preferences flow
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/__mocks__/initializedProfile.ts
  ts/components/NewRemindEmailValidationOverlay.tsx
  ts/components/messages/__tests__/PaymentButton.test.tsx
  ts/hooks/useValidateEmailModal.tsx
  ts/navigation/OnboardingNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/sagas/profile.ts
  ts/screens/authentication/NewOptInScreen.tsx
  ts/screens/onboarding/NewOnboardingEmailInsertScreen.tsx
  ts/screens/profile/NewEmailInsertScreen.tsx
  ts/screens/profile/ProfileDataScreen.tsx
  ts/store/actions/profile.ts
  ts/store/reducers/profile.ts
  ts/store/reducers/profileErrorType.ts
Labels: IO-A&I

#5272 fix: [PE-498] CGN OTP code timer issue
  ts/features/bonus/cgn/components/merchants/discount/OtpCodeComponent.tsx
Labels: Bug 🐞, Carta Giovani Nazionale

#5211 chore(IT Wallet): [SIW-433] Update PID issuing flow with new design system components
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ItwActionCompleted.tsx
  ts/features/it-wallet/components/ItwErrorView.tsx
  ts/features/it-wallet/components/ItwPidClaimsList.tsx
  ts/features/it-wallet/components/__tests__/ItwActionCompleted.test.tsx
  ts/features/it-wallet/components/__tests__/__snapshots__/ItwActionCompleted.test.tsx.snap
  ts/features/it-wallet/components/cie/CieNfcOverlay.tsx
  ts/features/it-wallet/components/cie/CiePinpad/index.tsx
  ts/features/it-wallet/components/cie/CieReadingCardAnimation.tsx
  ts/features/it-wallet/components/cie/Pinpad/InputPlaceholder.tsx
  ts/features/it-wallet/components/cie/Pinpad/KeyPad.tsx
  ts/features/it-wallet/components/cie/Pinpad/Placeholders.tsx
  ts/features/it-wallet/components/cie/Pinpad/index.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidAddingScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidAuthInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidRequestScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCieCardReaderScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCieConsentDataUsageScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCieExpiredOrInvalidScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCiePinLockedTemporarilyScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCiePinScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwCieWrongPinScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/cie/ItwPidPreviewScreen.tsx
Labels: IT Wallet

#5257 chore: [IOAPPFD0-191] Update DS section with new components just released
  package.json
  ts/components/PreferencesListItem.tsx
  ts/components/bottomSheet/BottomSheetHeader.tsx
  ts/components/core/typography/NewH3.tsx
  ts/components/core/typography/NewH4.tsx
  ts/components/core/typography/NewH6.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/components/ui/HeaderFirstLevel.tsx
  ts/components/ui/cards/payment/PaymentCardBig.tsx
  ts/components/ui/cards/payment/PaymentCardSmall.tsx
  ts/components/ui/cards/payment/__test__/__snapshots__/PaymentCards.test.tsx.snap
  ts/features/bonus/common/components/TosBonusComponent.tsx
  ts/features/design-system/core/DSHeaderSecondLevelWithSectionTitle.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/features/design-system/core/DSModules.tsx
  ts/features/design-system/core/DSSelection.tsx
  ts/features/design-system/core/DSTextFields.tsx
  ts/features/idpay/code/components/IdPayInfoCieBottomSheet.tsx
  ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageF24.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessagePaymentItem.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessagePayments.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
  ts/features/wallet/component/features/PaymentMethodInitiatives.tsx
  ts/features/wallet/component/features/PaymentMethodSettings.tsx
  ts/features/walletV3/common/components/WalletDetailsPaymentMethodInitiatives.tsx
  yarn.lock
Labels: Design System

#5265 chore: [IOAPPFD0-193] Add `NumberPad` + `CodeInput` screen to DS
  package.json
  ts/features/design-system/core/DSNumberPad.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  yarn.lock
Labels: Design System

#5260 chore(IT Wallet): [SIW-714] Remove extra padding from PID data presentation screen
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrPidDataScreen.tsx
Labels: IT Wallet

#5259 fix(IT Wallet): [SIW-570] Blocking error screen in wallet home screen
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
Labels: IT Wallet

#5243 feat: [IOBP-408] New wallet onboarding with custom webview
  ts/features/walletV3/details/components/WalletDetailsPaymentMethodScreen.tsx
  ts/features/walletV3/onboarding/components/WalletOnboardingWebView.tsx
  ts/features/walletV3/onboarding/hooks/useWalletOnboardingWebView.tsx
  ts/features/walletV3/onboarding/navigation/navigator.tsx
  ts/features/walletV3/onboarding/screens/WalletOnboardingFeedbackScreen.tsx
  ts/features/walletV3/onboarding/screens/WalletOnboardingSelectPaymentMethodScreen.tsx
  ts/features/walletV3/onboarding/utils/index.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
Labels: IO-Bonus e pagamenti
