Repository pagopa/io-app, pull requests merged in 2023-08, with the labels that each got.

#4842 feat: [IOPID-440] Add IPZS UAT Switch
  ios/Podfile.lock
  package.json
  ts/components/CiePinpad/index.tsx
  ts/components/cie/CieRequestAuthenticationOverlay.tsx
  ts/features/cieLogin/components/screens/CieLoginConfigScreen.tsx
  ts/features/cieLogin/components/screens/CieLoginConfigScreenContent.tsx
  ts/features/cieLogin/store/actions/index.ts
  ts/features/cieLogin/store/reducers/index.ts
  ts/features/cieLogin/store/selectors/index.ts
  ts/features/cieLogin/utils/endpoints.ts
  ts/features/common/store/reducers/index.ts
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/routes.ts
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/cie/CieCardReaderScreen.tsx
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  ts/utils/strings.ts
  yarn.lock
Labels: IO-A&I

#4862 chore(IT Wallet): [SIW-347] Update io-react-native-wallet
  package.json
  ts/features/it-wallet/components/ClaimsList.tsx
  ts/features/it-wallet/screens/ItwCredentialDetails.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/store/actions/credentials.ts
  ts/features/it-wallet/store/reducers/itwPid.ts
  yarn.lock
Labels: IT Wallet

#4863 fix(IT Wallet): [SIW-358] Update injected JS code in data usage screen
  ts/features/it-wallet/screens/issuing/cie/CieConsentDataUsageScreen.tsx
Labels: IT Wallet

#4864 fix(IT Wallet): [SIW-360] Update saga to handle authentication stop
  ts/features/it-wallet/hooks/useItwAbortFlow.tsx
  ts/features/it-wallet/saga/authenticationSaga.ts
  ts/features/it-wallet/saga/cie.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/screens/discovery/ItwActivationDetailsScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidActivationScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieInfoUsageScreen.tsx
  ts/features/it-wallet/store/actions/index.ts
Labels: IT Wallet

#4851 feat: [IOPLT-108] Migrating typography components from Design System
  package.json
  ts/components/core/typography/H3.tsx
  ts/components/core/typography/H4.tsx
  ts/components/core/typography/Link.tsx
  ts/components/core/typography/NewH3.tsx
  ts/components/core/typography/NewH4.tsx
  ts/components/core/typography/NewH6.tsx
  ts/components/core/typography/NewLink.tsx
  yarn.lock
Labels: Design System

#4869 feat: [IOPLT-117] Migrating buttons components from design system
  package.json
  ts/components/ui/ButtonExtendedOutline.tsx
  ts/components/ui/ButtonLink.tsx
  ts/components/ui/ButtonOutline.tsx
  ts/components/ui/ButtonSolid.tsx
  ts/components/ui/IconButton.tsx
  ts/components/ui/IconButtonContained.tsx
  ts/components/ui/IconButtonSolid.tsx
  yarn.lock
Labels: Design System

#4860 feat: [IOCOM-364,IOCOM-234] Optimisations on multiple renderings of messages' section
  ts/components/messages/MessageList/Item.tsx
  ts/components/messages/MessageList/__tests__/Item.test.tsx
  ts/components/messages/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
  ts/components/messages/MessageList/helpers.tsx
  ts/components/messages/MessageList/index.tsx
  ts/screens/messages/MessageDetailScreen.tsx
  ts/screens/messages/MessagesHomeScreen.tsx
  ts/store/actions/messages.ts
  ts/store/reducers/entities/messages/allPaginated.ts
  ts/store/reducers/entities/payments.ts
Labels: IO-Comunicazione

#4872 Test Android FL Deploy on custom closed channel (FL)
  CHANGELOG.md
  android/app/build.gradle
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/Info.plist
  ios/ItaliaAppTests/Info.plist
  package.json
  publiccode.yml
Labels: IO-A&I

#4874 feat: [IOPLT-120] Migrates Badges and tags component to `@pagopa/io-app-design-system` library
  ts/components/core/Badge.tsx
  ts/components/core/Tag.tsx
  ts/components/ui/ListItemTransaction.tsx
  ts/features/design-system/core/DSBadges.tsx
Labels: Design System

#4882 chore(IT Wallet): [SIW-366] Bypass with CTA on iOS
  ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
Labels: IT Wallet

#4884 chore(IT Wallet): [SIW-370] Remove E2E tests from workflow
  .github/workflows/test-e2e-it-wallet.yml
Labels: IT Wallet

#4879 chore(IT Wallet): [SIW-346] Refactor PID decode
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/navigation/routes.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/saga/pid.ts
  ts/features/it-wallet/screens/ItwCredentialDetails.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwActivationInfoAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidRequestScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/CieConsentDataUsageScreen.tsx
  ts/features/it-wallet/store/actions/credentials.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwPid.ts
  ts/features/it-wallet/store/reducers/itwPidDecode.ts
Labels: IT Wallet

#4887 fix: [IOCOM-472] Fix canOpenUrl on Android which was not taking the host parameter into account
  android/app/src/main/AndroidManifest.xml
Labels: IO-Comunicazione

#4888 fix(IT Wallet): [SIW-371] Update CIE uri string
  ts/features/it-wallet/screens/issuing/cie/CieConsentDataUsageScreen.tsx
Labels: IT Wallet

#4870 feat: [IOPLT-118] Migrating Alert from Design System
  package.json
  ts/components/Alert/index.tsx
  yarn.lock
Labels: Design System

#4877 feat: [IOPLT-119] Migrating list item components
  ts/components/ui/CheckboxListItem.tsx
  ts/components/ui/ListItemAction.tsx
  ts/components/ui/ListItemIDP.tsx
  ts/components/ui/ListItemInfo.tsx
  ts/components/ui/ListItemInfoCopy.tsx
  ts/components/ui/ListItemNav.tsx
  ts/components/ui/ListItemNavAlert.tsx
  ts/components/ui/ListItemTransaction.tsx
  ts/components/ui/RadioListItem.tsx
  ts/components/ui/SwitchListItem.tsx
  ts/components/ui/utils/baseComponents/PressableListItemBase.tsx
Labels: Design System

#4878 feat: [IOPLT-121] Migrating Radio, Switch and Checkbox components from Design System
  ts/components/core/selection/AnimatedTick.tsx
  ts/components/core/selection/RadioGroup.tsx
  ts/components/core/selection/checkbox/AnimatedCheckbox.tsx
  ts/components/core/selection/checkbox/AnimatedMessageCheckbox.tsx
  ts/components/core/selection/checkbox/AnimatedRadio.tsx
  ts/components/core/selection/checkbox/AnimatedSwitch.tsx
  ts/components/core/selection/checkbox/CheckboxLabel.tsx
  ts/components/core/selection/checkbox/NativeSwitch.tsx
  ts/components/core/selection/checkbox/SwitchLabel.tsx
Labels: Design System

#4891 chore(IT Wallet): [SIW-348] Screen naming convention refactor
  ts/features/it-wallet/components/cie/CieNfcOverlay.tsx
  ts/features/it-wallet/navigation/ItwParamsList.ts
  ts/features/it-wallet/navigation/ItwRoutes.ts
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/navigation/params.ts
  ts/features/it-wallet/navigation/routes.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/ItwNotAvailableScreen.tsx
  ts/features/it-wallet/screens/credentials/ItwPidDetails.tsx
  ts/features/it-wallet/screens/discovery/ItwDiscoveryInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidAddingScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidAuthInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidRequestScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieCardReaderScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieConsentDataUsageScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieExpiredOrInvalidScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieInfoUsageScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCiePinLockedTemporarilyScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCiePinScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieWrongPinScreen.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/navigation/params/AuthenticationParamsList.ts
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
Labels: IT Wallet

#4896 chore(IT Wallet): [SIW-365] Remove hardcoded strings from info screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/screens/issuing/ItwPidAuthInfoScreen.tsx
Labels: IT Wallet

#4895 chore(IT Wallet): [SIW-363] Add main banner translation
  locales/en/index.yml
Labels: IT Wallet

#4892 chore(IT Wallet): [SIW-349] Refactor state structure
  ts/components/messages/MessagesInbox.tsx
  ts/features/it-wallet/components/ItwActionBanner.tsx
  ts/features/it-wallet/hooks/useItwAbortFlow.tsx
  ts/features/it-wallet/hooks/useItwResetFlow.tsx
  ts/features/it-wallet/saga/__tests__/itwWiaSaga.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/saga/itwActivationSaga.ts
  ts/features/it-wallet/saga/itwAuthenticationSaga.ts
  ts/features/it-wallet/saga/itwCieSaga.ts
  ts/features/it-wallet/saga/itwCredentialsSaga.ts
  ts/features/it-wallet/saga/itwPidSaga.ts
  ts/features/it-wallet/saga/itwWiaSaga.ts
  ts/features/it-wallet/screens/ItwCredentialDetails.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/credentials/ItwPidDetails.tsx
  ts/features/it-wallet/screens/discovery/ItwDiscoveryInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidActivationScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidAddingScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidAuthInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidRequestScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieCardReaderScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieConsentDataUsageScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCieInfoUsageScreen.tsx
  ts/features/it-wallet/screens/issuing/cie/ItwCiePinScreen.tsx
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/actions/itwActivationActions.ts
  ts/features/it-wallet/store/actions/itwCieActions.ts
  ts/features/it-wallet/store/actions/itwCredentialsActions.ts
  ts/features/it-wallet/store/actions/itwLifecycleActions.ts
  ts/features/it-wallet/store/actions/itwWiaActions.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwCieReducer.ts
  ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts
  ts/features/it-wallet/store/reducers/itwLifecycleReducer.ts
  ts/features/it-wallet/store/reducers/itwPidDecodeReducer.ts
  ts/features/it-wallet/store/reducers/itwPidReducer.ts
  ts/features/it-wallet/store/reducers/itwWiaReducer.ts
Labels: IT Wallet

#4889 feat(IT Wallet): [SIW-364] Add generic error and loading screens
  ts/features/it-wallet/components/ItwErrorView.tsx
  ts/features/it-wallet/screens/ItwCredentialDetails.tsx
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/credentials/ItwPidDetails.tsx
  ts/features/it-wallet/screens/issuing/ItwPidActivationScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidAuthInfoScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidRequestScreen.tsx
  ts/features/it-wallet/utils/errors/itwErrorsMapping.ts
  ts/features/it-wallet/utils/itwButtonsUtils.tsx
Labels: IT Wallet

#4867 chore: [IOBP-160] New design for credit card detail screen
  ts/components/PreferencesListItem.tsx
  ts/components/core/logos/LogoPayment.tsx
  ts/components/ui/ListItemTransaction.tsx
  ts/components/ui/LogoPaymentExtended.tsx
  ts/components/ui/cards/payment/PaymentCardBig.tsx
  ts/components/ui/cards/payment/PaymentCardSmall.tsx
  ts/components/ui/cards/payment/__test__/__snapshots__/PaymentCards.test.tsx.snap
  ts/components/ui/utils/baseComponents/LogoPaymentOrDefaultIcon.tsx
  ts/components/ui/utils/components/BankLogoOrLoadingSkeleton.tsx
  ts/components/ui/utils/components/LogoPaymentWithFallback.tsx
  ts/components/ui/utils/components/PressableListItemBase.tsx
  ts/features/idpay/common/components/CardLogo.tsx
  ts/features/idpay/initiative/timeline/components/TimelineTransactionDetailsComponent.tsx
  ts/features/idpay/wallet/components/IDPayInitiativesListComponents.tsx
  ts/features/wallet/common/BasePaymentMethodScreen.tsx
  ts/features/wallet/component/features/PaymentMethodFeatures.tsx
  ts/features/wallet/component/features/PaymentMethodInitiatives.tsx
  ts/features/wallet/component/features/PaymentMethodSettings.tsx
  ts/features/wallet/creditCard/component/CreditCardComponent.tsx
  ts/features/wallet/creditCard/screen/CreditCardDetailScreen.tsx
  ts/utils/object.ts
Labels: IO-Bonus e pagamenti

#4903 fix: [IOCOM-479] Strings for NSPhotoLibraryAddUsageDescription permission
  ios/ItaliaApp/Info.plist
  ios/ItaliaApp/it.lproj/InfoPlist.strings
Labels: IO-Comunicazione

#4897 feat(IT Wallet): [SIW-231] Add decoder type to support itw qrcode
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/barcode/types/__tests__/decoders.test.ts
  ts/features/barcode/types/decoders.ts
Labels: IT Wallet

#4900 feat(IT Wallet): [SIW-390] Generalize PID claims list component
  locales/en/index.yml
  locales/it/index.yml
  ts/features/it-wallet/components/ClaimsList.tsx
  ts/features/it-wallet/components/ItwPidClaimsList.tsx
  ts/features/it-wallet/screens/credentials/ItwPidDetails.tsx
  ts/features/it-wallet/screens/issuing/ItwPidPreviewScreen.tsx
Labels: IT Wallet

#4907 fix(IT Wallet): [SIW-393] PID details footer scrolling with the content view
  ts/features/it-wallet/screens/credentials/ItwPidDetails.tsx
Labels: IT Wallet

#4914 feat(IT Wallet): [SIW-403] Add navigation to qrcode tab bar button
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/params/MainTabParamsList.ts
Labels: IT Wallet

#4909 feat(IT Wallet): [SIW-379] Update`io-react-native-wallet` package
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IT Wallet

#4910 feat(IT Wallet): [SIW-380] Add Relying Party actions and reducers
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/actions/itwRpActions.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwRpReducer.ts
Labels: IT Wallet

#4912 feat(IT Wallet): [SIW-381] Add Relying Party saga
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/saga/itwRpInitialization.ts
  ts/features/it-wallet/saga/itwRpPresentation.ts
  ts/features/it-wallet/saga/itwRpSaga.ts
  ts/features/it-wallet/store/actions/itwRpActions.ts
  ts/features/it-wallet/utils/errors/itwErrors.ts
Labels: IT Wallet

#4901 chore: [IOAPPFD0-135] Completely remove `dynamicSubHeader` reference from `DarkLayout`
  ts/components/screens/AnimatedScreenContent.tsx
  ts/components/screens/DarkLayout.tsx
  ts/components/wallet/WalletLayout.tsx
  ts/screens/wallet/WalletHomeScreen.tsx
Labels: 💀 Dead code

#4916 chore: [IOAPPFD0-136] Remove dead assets
  assets/fonts/Ionicons/Ionicons.ttf
  img/bonus/cgn/categories/books.svg
  img/bonus/cgn/categories/hotel.svg
  img/bonus/cgn/categories/restaurant.svg
  img/bonus/cgn/categories/shopping.svg
  img/bonus/cgn/categories/theater.svg
  img/icons/digital-id@3x.png
  img/icons/gears.png
  img/icons/gears@2x.png
  img/icons/gears@3x.png
  img/icons/message-icon@1x.png
  img/icons/message-icon@2x.png
  img/icons/message-icon@3x.png
  img/icons/service-icon.png
  img/icons/service-icon@2x.png
  img/icons/service-icon@3x.png
  img/icons/services-icon.png
  img/icons/services-icon@2x.png
  img/icons/services-icon@3x.png
  img/messages/empty-archive-list-icon.png
  img/messages/empty-archive-list-icon@2x.png
  img/messages/empty-archive-list-icon@3x.png
  img/messages/qr-code.svg
  img/pictograms/payment-unrecognized.png
  img/pictograms/payment-unrecognized@2x.png
  img/pictograms/payment-unrecognized@3x.png
  img/search/beer-mug.svg
  img/search/search-icon.svg
  img/services/icon-loading-services.svg
  img/services/icon-no-places.png
  img/services/icon-no-places.svg
  img/services/icon-no-places@2x.png
  img/services/icon-no-places@3x.png
  img/services/icon-places.png
  img/services/icon-places.svg
  img/services/icon-places@2x.png
  img/services/icon-places@3x.png
  img/test/alphaChannel.svg
  img/test/analytics.svg
  img/test/faceID.svg
  ios/ItaliaApp/Info.plist
  react-native.config.js
  ts/components/messages/MessageList/Item.tsx
  ts/components/messages/MessageList/__tests__/__snapshots__/Item.test.tsx.snap
  ts/features/design-system/core/DSAccordion.tsx
  ts/features/design-system/core/DSLegacyPictograms.tsx
  ts/features/design-system/core/DSListItems.tsx
Labels: 💀 Dead code

#4871 chore: [IOBP-168,IOBP-167] Toasts messages and native alert for delete payment method confirmation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/wallet/common/BasePaymentMethodScreen.tsx
  ts/features/wallet/component/RemovePaymentMethod.tsx
  ts/features/wallet/component/features/PaymentStatusSwitch.tsx
  ts/sagas/wallet/pagopaApis.ts
Labels: IO-Bonus e pagamenti

#4913 chore: [IOPID-599] Change text and image of onboarding thankyou page
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/onboarding/OnboardingCompletedScreen.tsx
Labels: IO-A&I

#4873 chore: [IOBP-166] Add `Alert` feedback into expired payment methods detail
  locales/en/index.yml
  locales/it/index.yml
  ts/features/wallet/component/features/PaymentMethodFeatures.tsx
  ts/store/reducers/wallet/__mocks__/wallets.ts
Labels: IO-Bonus e pagamenti

#4918 chore: [IOAPPFD0-137] Remove unused `Chooser…` components
  ts/components/ChooserList.tsx
  ts/components/ChooserListItem.tsx
  ts/components/ChooserListSearch.tsx
Labels: 💀 Dead code

#4893 chore: [IOPID-361] Delete isLollipopEnabledSelector
  ts/features/fci/components/SuccessComponent.tsx
  ts/features/lollipop/hooks/useLollipopLoginSource.tsx
  ts/features/lollipop/store/reducers/__tests__/lollipop.test.ts
  ts/screens/messages/MessagesHomeScreen.tsx
  ts/store/reducers/backendStatus.ts
Labels: IO-A&I

#4921 fix: [IABT-1488] Fix crash on Android 6 when checking for notifications' permission
  ts/utils/notification.ts
Labels: IO-Comunicazione, IO-A&I

#4908 fix: [IOPLT-131] Fixes the problem on dark mode for components
  ts/App.tsx
  ts/components/core/Divider/index.tsx
  ts/features/design-system/components/DSIconViewerBox.tsx
  ts/features/design-system/components/DSSpacerViewerBox.tsx
  ts/features/design-system/components/DesignSystemScreen.tsx
  ts/features/design-system/core/DSBottomSheet.tsx
  ts/features/design-system/core/DSHapticFeedback.tsx
  ts/features/design-system/core/DSIcons.tsx
  ts/features/design-system/core/DSLayout.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/features/design-system/navigation/navigator.tsx
Labels: Design System, Dark mode 🌝

#4928 chore(IT Wallet): [SIW-407] Add PID decode to RP initialization saga
  ts/features/it-wallet/saga/itwRpSaga.ts
Labels: IT Wallet

#4925 fix(IT Wallet): [SIW-405] Fix JWT library crash
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IT Wallet

#4923 chore: [IOBP-178,IOBP-184] Native Base dismissal into `IDPayInitiativesListComponents`
  locales/en/index.yml
  locales/it/index.yml
  ts/components/PreferencesListItem.tsx
  ts/features/idpay/wallet/components/IDPayInitiativesListComponents.tsx
  ts/features/idpay/wallet/store/reducers/index.ts
Labels: NativeBase dismissal 🥷🏼, IO-Bonus e pagamenti

#4919 chore: [IAI-279] Completely remove `IconFont` references from the codebase
  android/app/src/main/assets/fonts/Ionicons.ttf
  android/app/src/main/assets/fonts/io-icon-font.ttf
  android/link-assets-manifest.json
  assets/fonts/io-icon-font/io-icon-font.ttf
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/Info.plist
  ios/Podfile.lock
  ios/link-assets-manifest.json
  package.json
  react-native.config.js
  ts/@types/react-native-vector-icons.d.ts
  ts/components/LabelledItem/LabelledItemIconOrImage.tsx
  ts/components/LabelledItem/__tests__/LabelledItem.test.tsx
  ts/components/LabelledItem/index.tsx
  ts/components/PinCreationForm.tsx
  ts/components/ScreenHeader.tsx
  ts/components/__tests__/ContextualInfo.test.tsx
  ts/components/cie/CieNfcOverlay.tsx
  ts/components/screens/DarkLayout.tsx
  ts/components/screens/EmailCallCTA.tsx
  ts/components/screens/ScreenContent.tsx
  ts/components/screens/ScreenContentHeader.tsx
  ts/components/search/SearchButton.tsx
  ts/components/ui/BlockButtons.tsx
  ts/components/ui/IconFont.tsx
  ts/components/ui/Markdown/index.tsx
  ts/components/wallet/WalletLayout.tsx
  ts/features/bonus/bonusVacanze/components/buttons/ButtonConfigurations.ts
  ts/features/bonus/bonusVacanze/components/buttons/FooterStackButtons.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsFilters.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/bonus/siciliaVola/components/SvVoucherListFilters.tsx
  ts/features/design-system/components/DSAssetViewerBox.tsx
  ts/features/design-system/core/DSLegacyPictograms.tsx
  ts/features/design-system/core/DSTextFields.tsx
  ts/features/wallet/bancomat/screen/BancomatInformation.tsx
  ts/features/wallet/bancomat/screen/__tests__/BancomatInformation.test.tsx
  ts/features/wallet/onboarding/common/searchBank/SearchBankComponent.tsx
  ts/screens/authentication/TestAuthenticationScreen.tsx
  ts/screens/authentication/cie/CiePinLockedTemporarilyScreen.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  ts/screens/messages/MessagesHomeScreen.tsx
  ts/screens/onboarding/FingerprintScreen.tsx
  ts/screens/onboarding/OnboardingEmailInsertScreen.tsx
  ts/screens/onboarding/OnboardingNotificationsPreferencesScreen.tsx
  ts/screens/profile/EmailInsertScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/wallet/AddCardScreen.tsx
  ts/screens/wallet/payment/components/TransactionSummaryButtonConfigurations.ts
  ts/theme/components/Button.ts
  ts/theme/components/Header.ts
  ts/theme/components/IconFont.ts
  ts/theme/components/PreferenceItem.ts
  ts/theme/font-icons/io-icon-font/index.ts
  ts/theme/font-icons/io-icon-font/selection.json
  ts/theme/index.ts
  ts/theme/variables.ts
  ts/utils/constants.ts
  ts/utils/creditCard.ts
  yarn.lock
Labels: Design System, NativeBase dismissal 🥷🏼, 💀 Dead code

#4922 chore: [IOAPPFD0-138] Enable higher refresh rates on ProMotion displays (iOS)
  ios/ItaliaApp/Info.plist
  ts/components/ui/GradientScrollView.tsx
  ts/features/design-system/core/DSHeaderSecondLevel.tsx
  ts/features/design-system/core/DSHeaderSecondLevelWithSectionTitle.tsx
Labels: Design System

#4933 chore: [IOBP-155] Change title typography into legacy `ListItemTransaction`
  package.json
  ts/components/ui/ListItemTransaction.tsx
  ts/features/design-system/core/DSListItems.tsx
  yarn.lock
Labels: IO-Bonus e pagamenti

#4938 chore: [IOAPPFD0-134] Add the new `AccordionItem` to the Design System playground
  ts/features/design-system/core/DSAccordion.tsx
Labels: Design System

#4937 chore(IT Wallet): [SIW-375] Refactor credentials state
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/saga/itwCredentialsSaga.ts
  ts/features/it-wallet/screens/issuing/ItwPidActivationScreen.tsx
  ts/features/it-wallet/screens/issuing/ItwPidAddingScreen.tsx
  ts/features/it-wallet/store/actions/itwCredentialsActions.ts
  ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts
  ts/features/it-wallet/utils/errors/itwErrors.ts
Labels: IT Wallet
