Repository pagopa/io-app, pull requests merged in 2024-10, with the labels that each got.

#6123 chore(Cross): [IOAPPX-343,IOAPPX-311] Add `react-native-skia` library + Dynamic header background (under the new Experimental Lab category)
  ios/Podfile.lock
  jest-e2e.config.js
  jest.config.js
  jest.config.no.timezone.js
  package.json
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/core/DSDynamicBackground.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  yarn.lock
Labels: Cross, code review needed 💻📱

#6211 chore: [IOCOM-1740] Push Notification Data
  ios/Podfile.lock
  package.json
  ts/boot/__tests__/persistedStore.test.ts
  ts/boot/configureStoreAndPersistor.ts
  ts/features/pushNotifications/analytics/__tests__/index.test.ts
  ts/features/pushNotifications/analytics/index.ts
  ts/features/pushNotifications/sagas/__tests__/common.test.ts
  ts/features/pushNotifications/sagas/__tests__/notificationPermissionsListener.test.ts
  ts/features/pushNotifications/sagas/__tests__/notifications.test.ts
  ts/features/pushNotifications/sagas/__tests__/profileAndSystemNotificationsPermissions.test.tsx
  ts/features/pushNotifications/sagas/__tests__/pushNotificationTokenUpload.test.ts
  ts/features/pushNotifications/sagas/common.ts
  ts/features/pushNotifications/sagas/notificationPermissionsListener.ts
  ts/features/pushNotifications/sagas/notifications.ts
  ts/features/pushNotifications/sagas/profileAndSystemNotificationsPermissions.ts
  ts/features/pushNotifications/sagas/pushNotificationTokenUpload.ts
  ts/features/pushNotifications/screens/OnboardingNotificationsInfoScreenConsent.tsx
  ts/features/pushNotifications/screens/__tests__/OnboardingNotificationsInfoScreenConsent.test.tsx
  ts/features/pushNotifications/screens/__tests__/__snapshots__/OnboardingNotificationsInfoScreenConsent.test.tsx.snap
  ts/features/pushNotifications/store/actions/__tests__/installation.test.ts
  ts/features/pushNotifications/store/actions/__tests__/pendingMessage.test.ts
  ts/features/pushNotifications/store/actions/__tests__/permissions.test.ts
  ts/features/pushNotifications/store/actions/__tests__/profileNotificationPermissions.test.ts
  ts/features/pushNotifications/store/actions/installation.ts
  ts/features/pushNotifications/store/actions/notifications.ts
  ts/features/pushNotifications/store/actions/pendingMessage.ts
  ts/features/pushNotifications/store/actions/permissions.ts
  ts/features/pushNotifications/store/actions/profileNotificationPermissions.ts
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/permissions.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/index.test.ts
  ts/features/pushNotifications/store/reducers/__tests__/permissions.test.ts
  ts/features/pushNotifications/store/reducers/index.ts
  ts/features/pushNotifications/store/reducers/installation.ts
  ts/features/pushNotifications/store/reducers/pendingMessage.ts
  ts/features/pushNotifications/store/reducers/permissions.ts
  ts/features/pushNotifications/utils/__tests__/configurePushNotification.test.ts
  ts/features/pushNotifications/utils/__tests__/index.test.ts
  ts/features/pushNotifications/utils/configurePushNotification.ts
  ts/features/pushNotifications/utils/index.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/identification.ts
  ts/sagas/startup.ts
  ts/sagas/startup/watchApplicationActivitySaga.ts
  ts/store/actions/types.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
  ts/utils/appSettings.ts
  yarn.lock
Labels: IO-Comunicazione

#6212 chore: [IOBP-893] Adapted new IDPay amount with cents
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
  ts/features/idpay/onboarding/utils/__tests__/strings.test.ts
  ts/features/idpay/timeline/components/TimelineRefundDetailsComponent.tsx
  ts/features/idpay/timeline/components/TimelineTransactionDetailsComponent.tsx
  ts/features/idpay/wallet/components/IDPayCardPreviewComponent.tsx
  ts/features/idpay/wallet/components/IdPayCard.tsx
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap
Labels: IDPay, IO-Bonus e pagamenti

#6224 chore: [iOBP-898] Change payment outcome 17 copy message
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#6232 fix: [IOCOM-1808] Update io-react-native-login-utils
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IO-Comunicazione

#6209 feat(IT Wallet): [SIW-1559,SIW-1637] Resume async credential issuance from deep link
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/navigation/AppStackNavigator.tsx
Labels: IT Wallet

#6214 chore(IT Wallet): [SIW-1665] Hide eID card in wallet
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/design-system/core/DSWallet.tsx
  ts/features/itwallet/common/components/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/ItwEidInfoBottomSheetContent.tsx
  ts/features/itwallet/common/components/ItwWalletReadyBanner.tsx
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/store/reducers/migrations.ts
  ts/features/itwallet/common/utils/__tests__/itwCredentialStatusAttestationUtils.test.ts
  ts/features/itwallet/common/utils/itwCredentialIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
  ts/features/itwallet/credentials/saga/handleItwCredentialsStoreSaga.ts
  ts/features/itwallet/credentials/saga/handleWalletCredentialsRehydration.ts
  ts/features/itwallet/credentials/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/components/__tests__/WalletCardsContainer.test.tsx
  yarn.lock
Labels: IT Wallet

#6217 fix(IT Wallet): [SIW-1526] Wrong date claim with different timezone
  jest.config.no.timezone.js
  package.json
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
  ts/utils/__tests__/dates.test.ts
  ts/utils/dates.ts
Labels: IT Wallet

#6221 chore(IT Wallet): [SIW-1666] Add category filter tabs to the wallet screen
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/components/WalletCategoryFilterTabs.tsx
  ts/features/newWallet/components/__tests__/WalletCategoryFilterTabs.test.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/store/actions/preferences.ts
  ts/features/newWallet/store/reducers/preferences.ts
  ts/features/newWallet/store/selectors/index.ts
  ts/features/newWallet/types/index.ts
Labels: IT Wallet

#6236 chore(IT Wallet): [SIW-1709] Update trustmark env URL
  .env.local
  .env.production
Labels: IT Wallet

#6229 chore: [IOCOM-1741] Notification engament modal - Phase 1
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/__tests__/persistedStore.test.ts
  ts/components/screens/WizardScreen.tsx
  ts/features/messages/screens/MessagesHomeScreen.tsx
  ts/features/messages/screens/__tests__/MessagesHomeScreen.test.tsx
  ts/features/pushNotifications/hooks/__tests__/useEngagementScreen.test.tsx
  ts/features/pushNotifications/hooks/useEngagementScreen.tsx
  ts/features/pushNotifications/navigation/__tests__/routes.test.ts
  ts/features/pushNotifications/navigation/routes.ts
  ts/features/pushNotifications/sagas/__tests__/common.test.ts
  ts/features/pushNotifications/sagas/common.ts
  ts/features/pushNotifications/screens/SystemNotificationPermissionsScreen.tsx
  ts/features/pushNotifications/screens/__tests__/OnboardingNotificationsInfoScreenConsent.test.tsx
  ts/features/pushNotifications/screens/__tests__/SystemNotificationPermissionsScreen.test.tsx
  ts/features/pushNotifications/screens/__tests__/__snapshots__/OnboardingNotificationsInfoScreenConsent.test.tsx.snap
  ts/features/pushNotifications/screens/__tests__/__snapshots__/SystemNotificationPermissionsScreen.test.tsx.snap
  ts/features/pushNotifications/store/actions/__tests__/permissions.test.ts
  ts/features/pushNotifications/store/actions/__tests__/userBehaviour.test.ts
  ts/features/pushNotifications/store/actions/environment.ts
  ts/features/pushNotifications/store/actions/userBehaviour.ts
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/environment.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/permissions.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/userBehaviour.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/environment.test.ts
  ts/features/pushNotifications/store/reducers/__tests__/index.test.ts
  ts/features/pushNotifications/store/reducers/__tests__/permissions.test.ts
  ts/features/pushNotifications/store/reducers/__tests__/userBehaviour.test.ts
  ts/features/pushNotifications/store/reducers/environment.ts
  ts/features/pushNotifications/store/reducers/index.ts
  ts/features/pushNotifications/store/reducers/permissions.ts
  ts/features/pushNotifications/store/reducers/userBehaviour.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/store/actions/application.ts
  ts/store/actions/types.ts
Labels: IO-Comunicazione

#6228 chore(IT Wallet): [SIW-1702] Add automatic subscription to the ITW trial system
  locales/en/index.yml
  locales/it/index.yml
  ts/__mocks__/react-native-config.ts
  ts/features/itwallet/common/saga/__tests__/index.test.ts
  ts/features/itwallet/common/saga/index.ts
  ts/features/trialSystem/store/sagas/watchTrialSystemSaga.ts
Labels: IT Wallet

#6240 chore(Cross): [IOAPPX-387] Bump fastlane to version `2.223.1`
  Gemfile
  Gemfile.lock
Labels: Cross

#6241 fix: [PE-699] CGN detail header title on scroll
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
Labels: Carta Giovani Nazionale

#6220 fix: [PE-605] CGN category list unnecessary loading animation
  ts/features/bonus/cgn/components/merchants/CgnMerchantListSkeleton.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
Labels: Carta Giovani Nazionale

#6223 chore: [IOBP-897] Fetch payment methods only the first time when opening the Wallet section
  ts/features/newWallet/hooks/useOnWalletUserSessionRefresh.ts
  ts/features/newWallet/screens/WalletHomeScreen.tsx
Labels: IO-Bonus e pagamenti

#6242 fix: [IOBP-908] Timeline amount format in cents
  ts/features/idpay/common/utils/strings.ts
  ts/features/idpay/details/components/TimelineOperationListItem.tsx
  ts/features/idpay/details/components/__tests__/TimelineOperationListItem.test.tsx
Labels: IDPay, IO-Bonus e pagamenti

#6243 chore: [IOCOM-1847] New labels on notification engagement modal
  locales/en/index.yml
  locales/it/index.yml
  ts/features/pushNotifications/screens/__tests__/__snapshots__/SystemNotificationPermissionsScreen.test.tsx.snap
Labels: IO-Comunicazione

#6227 fix(IT Wallet): [SIW-1660,SIW-1689] Copy review
  img/features/itWallet/cards/dc.png
  img/features/itWallet/cards/dc@2x.png
  img/features/itWallet/cards/dc@3x.png
  img/features/itWallet/cards/mdl.png
  img/features/itWallet/cards/mdl@2x.png
  img/features/itWallet/cards/mdl@3x.png
  img/features/itWallet/cards/ts.png
  img/features/itWallet/cards/ts@2x.png
  img/features/itWallet/cards/ts@3x.png
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSWallet.tsx
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwDigitalVersionBadge.tsx
  ts/features/itwallet/common/components/ItwUpcomingWalletBanner.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
  ts/features/itwallet/issuance/components/ItwCredentialPreviewClaimsList.tsx
  ts/features/itwallet/issuance/components/__tests__/__snapshots__/ItwCredentialPreviewClaimsList.test.tsx.snap
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/presentation/components/ItwCredentialTrustmark.tsx
  ts/features/itwallet/presentation/components/ItwPresentationAlertsSection.tsx
  ts/features/itwallet/presentation/components/ItwPresentationClaimsSection.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailsFooter.tsx
  ts/features/itwallet/presentation/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
  ts/features/newWallet/components/WalletCardsContainer.tsx
Labels: IT Wallet

#6244 chore: [IOCOM-1749] Analytics events for notification permission engagement modal, phase 1
  ts/features/pushNotifications/analytics/__tests__/index.test.ts
  ts/features/pushNotifications/analytics/index.ts
  ts/features/pushNotifications/sagas/__tests__/common.test.ts
  ts/features/pushNotifications/sagas/__tests__/notificationPermissionsListener.test.ts
  ts/features/pushNotifications/sagas/common.ts
  ts/features/pushNotifications/sagas/notificationPermissionsListener.ts
  ts/features/pushNotifications/screens/SystemNotificationPermissionsScreen.tsx
  ts/features/pushNotifications/screens/__tests__/SystemNotificationPermissionsScreen.test.tsx
Labels: IO-Comunicazione

#6218 chore: [IOCOM-1684] New FIMS IAB error and error handling structure
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/singleSignOn/components/FimsErrorScreens.tsx
  ts/features/fims/singleSignOn/components/FimsFullScreenErrors.tsx
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/fims/singleSignOn/store/selectors/index.ts
Labels: IO-Comunicazione

#6238 chore(IT Wallet): [SIW-1573] Map integrity errors from wallet provider in eID issuance flow
  package.json
  ts/features/itwallet/machine/eid/failure.ts
  ts/features/itwallet/machine/eid/machine.ts
  yarn.lock
Labels: IT Wallet

#6246 fix: [PE-700] CGN detail fix missing swipe back gesture
  ts/navigation/AuthenticatedStackNavigator.tsx
Labels: Carta Giovani Nazionale

#6204 fix: [PE-638] Remove CGN card from wallet screen when unsubscribed
  ts/features/bonus/cgn/hooks/useCgnUnsubscribe.tsx
  ts/features/bonus/cgn/saga/networking/unsubscribe/index.ts
Labels: Carta Giovani Nazionale

#6239 fix(IT Wallet): [SIW-1715] TS credential barcode format
  ts/features/itwallet/presentation/components/ItwPresentationFiscalCode.tsx
Labels: IT Wallet

#6207 chore: Add auto commenting and uncommenting script for lollipop checks
  README.md
  package.json
  scripts/toggle-comments-on-lollipop-checks.sh
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: Cross

#6230 chore: [IOPID-2305] Bump ToS version from `4.9` a `4.91`
  ts/features/tos/store/selectors/index.ts
Labels: IO-A&I

#6206 chore: [PE-565] Adapt `CgnCTAStartActivationScreen` to use the new DS components
  ts/features/bonus/cgn/screens/activation/CgnCTAStartActivationScreen.tsx
Labels: Carta Giovani Nazionale, Design System

#6205 fix: [PE-606] Add Divider into CGN footer list screen
  ts/features/bonus/cgn/screens/merchants/CgnMerchantCategoriesListScreen.tsx
Labels: Carta Giovani Nazionale

#6247 chore(Cross): [IOAPPX-388] Remove Slack message on E2E failure
  .github/workflows/test-e2e.yml
Labels: Cross

#6251 chore(Cross): [IOAPPX-384] Remove uaDonations features
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/__mocks__/react-native-config.ts
  ts/config.ts
  ts/features/uaDonations/analytics/.placeholder
  ts/features/uaDonations/api/.placeholder
  ts/features/uaDonations/components/UaDonationsBanner.tsx
  ts/features/uaDonations/components/__test__/UaDonationsBanner.test.tsx
  ts/features/uaDonations/navigation/routes.ts
  ts/features/uaDonations/saga/.placeholder
  ts/features/uaDonations/screens/UAWebViewScreen.tsx
  ts/features/uaDonations/store/.placeholder
  ts/features/uaDonations/types/__test__/index.test.ts
  ts/features/uaDonations/types/index.ts
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/__tests__/backendStatus.test.ts
  ts/store/reducers/backendStatus.ts
  ts/urls.ts
  ts/utils/internalLink.ts
Labels: Cross

#6203 chore(Cross): [IOAPPX-374, IOCOM-1850] `ScreenWithListItems` → `IOScrollViewWithListItems`, `WizardScreen` → `IOScrollViewCentredContent`
  ts/components/screens/CustomWizardScreen.tsx
  ts/components/screens/ScreenWithListItems.tsx
  ts/components/screens/WizardScreen.tsx
  ts/components/screens/__tests__/WizardScreen.test.tsx
  ts/components/ui/IOScrollView.tsx
  ts/components/ui/IOScrollViewCentredContent.tsx
  ts/components/ui/IOScrollViewWithListItems.tsx
  ts/components/ui/__test__/IOScrollViewCentredContent.test.tsx
  ts/components/ui/__test__/IOScrollViewWithListItems.test.tsx
  ts/components/ui/__test__/__snapshots__/IOScrollViewCentredContent.test.tsx.snap
  ts/components/ui/__test__/__snapshots__/IOScrollViewWithListItems.test.tsx.snap
  ts/features/cie/__tests__/__snapshots__/wizards.test.tsx.snap
  ts/features/design-system/core/DSIOScrollViewCentredContent.tsx
  ts/features/design-system/core/DSIOScrollViewWithListItems.tsx
  ts/features/design-system/core/DSWizardScreen.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/features/idpay/code/screens/IdPayCodeOnboardingScreen.tsx
  ts/features/idpay/code/screens/__tests__/IdPayCodeOnboardingScreen.test.tsx
  ts/features/pushNotifications/screens/SystemNotificationPermissionsScreen.tsx
  ts/features/pushNotifications/screens/__tests__/SystemNotificationPermissionsScreen.test.tsx
  ts/features/pushNotifications/screens/__tests__/__snapshots__/SystemNotificationPermissionsScreen.test.tsx.snap
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/screens/authentication/__tests__/cie/__snapshots__/ActivateNfcScreen.test.tsx.snap
  ts/screens/authentication/cie/ActivateNfcScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/MissingDeviceBiometricScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/MissingDevicePinScreen.tsx
  ts/screens/profile/__test__/__snapshots__/LanguagesPreferencesScreen.test.tsx.snap
  ts/screens/profile/__test__/__snapshots__/NotificationsPreferencesScreen.test.tsx.snap
Labels: enhancement, Design System, Cross

#6225 chore(IT Wallet): [SIW-1634] Persist WIA across both eID and credential issuance flows
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/store/storages/itwSecureStorage.ts
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwCredentialIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwCryptoContextUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/credentials/store/reducers/index.ts
  ts/features/itwallet/credentials/store/reducers/migrations.ts
  ts/features/itwallet/discovery/screens/__tests__/ItwDiscoveryInfoScreen.test.tsx
  ts/features/itwallet/issuance/screens/__tests__/ItwIssuanceCredentialAuthScreen.test.tsx
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/actors.ts
  ts/features/itwallet/machine/credential/context.ts
  ts/features/itwallet/machine/credential/guards.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/__tests__/__snapshots__/machine.test.ts.snap
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/guards.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/provider.tsx
  ts/features/itwallet/onboarding/screens/__tests__/WalletCardOnboardingScreen.test.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationAlertsSection.test.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationDetailFooter.test.tsx
  ts/features/itwallet/walletInstance/store/actions/index.ts
  ts/features/itwallet/walletInstance/store/reducers/index.ts
Labels: IT Wallet

#6258 chore: [IOCOM-1809] Move FIMs history entry to Access and Security section
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/history/store/selectors/__tests__/index.test.ts
  ts/screens/profile/PrivacyMainScreen.tsx
  ts/screens/profile/SecurityScreen.tsx
  ts/screens/profile/__test__/SecurityScreen.test.tsx
  ts/screens/profile/__test__/__snapshots__/SecurityScreen.test.tsx.snap
Labels: IO-Comunicazione

#6262 chore: [IOCOM-1818] Add test for FIMS common reducer
  ts/features/fims/common/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/fims/common/store/__tests__/reducer.test.ts
Labels: IO-Comunicazione

#6269 chore(Cross): [IOAPPX-392] Set `largeHeap=true`
  android/app/src/main/AndroidManifest.xml
Labels: Cross

#6265 chore(Cross): [IOAPPX-390] Device-info patch version upgrade
  patches/react-native-device-info+10.8.0.patch
Labels: dependencies, Cross

#6267 chore(IT Wallet): [SIW-1728] Wallet instance activation copy review
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
Labels: IT Wallet

#6261 chore(IT Wallet): [SIW-1725] Add activation from internal navigation
  ts/components/SectionStatus/__tests__/index.test.tsx
  ts/components/screens/BaseScreenComponent/__tests__/BaseScreenComponent.test.tsx
  ts/features/itwallet/navigation/useItwLinkingOptions.tsx
  ts/features/pn/components/__test__/TimelineListItem.test.tsx
  ts/features/wallet/bancomatpay/component/__test__/BPayWalletPreview.test.tsx
  ts/features/wallet/cobadge/component/__tests__/CobadgeWalletPreview.test.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx
  ts/screens/profile/__test__/TosScreen.test.tsx
Labels: IT Wallet

#6254 chore: [IOCOM-1742,IOCOM-1756] Disabled notifications banner in profile/settings home
  locales/en/index.yml
  locales/it/index.yml
  ts/features/profileSettings/store/selectors/__tests__/index.test.ts
  ts/features/profileSettings/store/selectors/index.ts
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/profile/ProfileMainScreenTopBanner.tsx
  ts/screens/profile/__test__/ProfileMainScreenTopBanner.test.tsx
  ts/screens/profile/__test__/__snapshots__/ProfileMainScreenTopBanner.test.tsx.snap
Labels: IO-Comunicazione

#6087 feat: [PE-553] CGN discount screen revamp
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/LegacyCgnServiceCTA.tsx
  ts/features/bonus/cgn/components/__test__/CgnCard.test.tsx
  ts/features/bonus/cgn/components/__test__/OtpCodeRefreshComponent.test.tsx
  ts/features/bonus/cgn/components/__test__/__snapshots__/CgnCard.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnModuleDiscount.tsx
  ts/features/bonus/cgn/components/merchants/__test__/CgnDiscountDetail.test.tsx
  ts/features/bonus/cgn/components/merchants/__test__/__snapshots__/CgnDiscountDetail.test.tsx.snap
  ts/features/bonus/cgn/components/merchants/discount/CgnBucketCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountContent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountExpireProgressBar.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountHeader.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnOTPCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnStaticCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/OtpCodeComponent.tsx
  ts/features/bonus/cgn/components/merchants/discount/__test__/CgnDiscountCodeComponent.test.tsx
  ts/features/bonus/cgn/components/merchants/discount/__test__/__snapshots__/CgnDiscountCodeComponent.test.tsx.snap
  ts/features/bonus/cgn/hooks/useCgnDiscountDetailBottomSheet.tsx
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/cgn/navigation/params.ts
  ts/features/bonus/cgn/navigation/routes.ts
  ts/features/bonus/cgn/saga/networking/bucket/index.ts
  ts/features/bonus/cgn/saga/networking/otp/index.ts
  ts/features/bonus/cgn/screens/discount/CgnDiscountCodeScreen.tsx
  ts/features/bonus/cgn/screens/discount/CgnDiscountDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
  ts/features/bonus/cgn/store/actions/bucket.ts
  ts/features/bonus/cgn/store/actions/merchants.ts
  ts/features/bonus/cgn/store/actions/otp.ts
  ts/features/bonus/cgn/store/reducers/__test__/otp.test.ts
  ts/features/bonus/cgn/store/reducers/merchants.ts
  ts/features/design-system/core/DSListItems.tsx
Labels: Carta Giovani Nazionale

#6216 fix: [IOBP-879,IOBP-880] Upgrade `react-native-vision-camera` to version `4.3.1`
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: dependencies, IO-Bonus e pagamenti

#6272 fix(Cross): [IOAPPX-391] Move `watchZendeskSupportSaga` to `root` saga
  ts/sagas/index.ts
  ts/sagas/startup.ts
Labels: IO-A&I, Cross

#6255 chore: [IOPID-2160] Delete local and remote FF of session refresh
  ts/features/fastLogin/store/actions/sessionRefreshActions.ts
  ts/features/fastLogin/store/reducers/sessionRefreshReducer.ts
  ts/features/fastLogin/store/selectors/index.ts
  ts/sagas/startup/watchApplicationActivitySaga.ts
  ts/screens/modal/IdentificationModal.tsx
  ts/screens/profile/DeveloperModeSection.tsx
Labels: IO-A&I

#6273 chore: [IOPID-2341] Delete deprecated getSupportToken API
  ts/api/backend.ts
  ts/features/zendesk/saga/index.ts
  ts/features/zendesk/screens/RequestZandeskTokenErrorScreen.tsx
  ts/sagas/startup.ts
  ts/sagas/startup/watchCheckSessionSaga.ts
  ts/store/actions/authentication.ts
  ts/store/reducers/authentication.ts
Labels: IO-A&I

#6245 fix: [IOBP-869] Disable layout animation on Android into Wallet screen due reanimated issue
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
Labels: IO-Bonus e pagamenti

#6234 feat: [IOBP-687,IOBP-885] Add recently used payment method from the payment flow
  package.json
  ts/features/payments/checkout/components/CheckoutPaymentMethodsList.tsx
  ts/features/payments/checkout/saga/index.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetRecentMethod.ts
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/store/__tests__/store.test.ts
  ts/features/payments/checkout/store/actions/networking.ts
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
  ts/features/payments/checkout/utils/index.ts
Labels: IO-Bonus e pagamenti

#6280 fix: [IOBP-915] Error toast message when download receipt is failed due left response
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactionReceipt.ts
Labels: IO-Bonus e pagamenti

#6266 fix(IT Wallet): [SIW-1724] Add code 12 in skeumorphic mdl card if present
  ts/features/itwallet/__mocks__/mdl.json
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardData.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
Labels: IT Wallet

#6278 chore: [IOBP-913] Map correct `payment_phase` attribute into mixpanel event when generic error shows
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentCreateTransaction.test.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/store/__tests__/store.test.ts
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/utils/index.ts
Labels: IO-Bonus e pagamenti

#6248 fix(IT Wallet): [SIW-1595] Fix IT Wallet a11y issues
  ts/components/AnimatedImage.tsx
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwReleaserName.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimLabel.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
  ts/features/itwallet/presentation/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
Labels: IT Wallet

#6252 feat(IT Wallet): [SIW-1574] Add wallet instance revocation
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/itwallet/common/components/ItwEidInfoBottomSheetContent.tsx
  ts/features/itwallet/common/utils/itwRevocationUtils.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/lifecycle/screens/ItwLifecycleWalletRevocationScreen.tsx
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/failure.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/newWallet/components/WalletCardsContainer.tsx
  yarn.lock
Labels: IT Wallet

#6268 chore: [IOCOM-1816] Add tests for FIMS analytics events
  ts/features/fims/common/analytics/__tests__/index.test.ts
  ts/features/fims/common/analytics/index.ts
  ts/features/fims/common/utils/index.ts
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
Labels: IO-Comunicazione

#6271 chore: [IOCOM-1815] Add test for common FIMS saga
  ts/features/fims/common/saga/__tests__/index.test.ts
  ts/features/fims/common/saga/index.ts
Labels: IO-Comunicazione

#6233 chore: [IOPID-2329] Improve `Keychain` errors also leveraging Sentry
  ts/App.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
  ts/store/storages/keychain.ts
  ts/utils/analytics.ts
Labels: legal-approved ⚖️ ✅, IO-A&I

#6263 chore(Cross): [IOAPPX-354] Add the new `FooterActionsInline` component from `io-app-design-system`
  package.json
  ts/components/BonusCard/BonusCardScreenComponent.tsx
  ts/components/ui/FooterActions.tsx
  ts/components/ui/IOScrollViewWithLargeHeader.tsx
  ts/components/ui/RNavScreenWithLargeHeader.tsx
  ts/features/design-system/core/DSFooterActions.tsx
  ts/features/design-system/core/DSFooterActionsInline.tsx
  ts/features/design-system/core/DSFooterActionsInlineNotFixed.tsx
  ts/features/design-system/core/DSFooterActionsNotFixed.tsx
  ts/features/design-system/core/DSFooterActionsSticky.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/features/fims/common/components/FimsUpdateAppAlert.tsx
  ts/features/payments/checkout/components/WalletPaymentHeader.tsx
  ts/features/services/home/components/__tests__/__snapshots__/FeaturedServiceCard.test.tsx.snap
  ts/hooks/useHeaderProps.tsx
  ts/hooks/useHeaderSecondLevel.tsx
  ts/hooks/useScreenEndMargin.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  yarn.lock
Labels: Design System, Cross

#6259 fix: [IOBP-910] PSP Sorting by onUs, fee amount and psp name ascending
  ts/features/payments/common/utils/index.ts
Labels: IO-Bonus e pagamenti

#6257 chore: [IOBP-906] Add interrupted payment screen outcome
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/types/PaymentOutcomeEnum.ts
Labels: IO-Bonus e pagamenti

#6282 fix(IT Wallet): [SIW-1754] Missing contextual help inside identification mode screen
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
Labels: IT Wallet

#6287 chore(Cross): [IOAPPX-401] Update JDK version in release workflow
  .github/workflows/release.yml
Labels: Cross

#6159 feat: [IOBP-840] Add payment tracking property `organization_fiscal_code`
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
Labels: IO-Bonus e pagamenti

#6289 fix: [IOCOM-1881] Push notification status on Android 12 or less
  ts/features/pushNotifications/utils/index.ts
Labels: IO-Comunicazione

#6288 fix: [IOPID-2389] - Fix login CieID
  ts/hooks/useNavigateToLoginMethod.tsx
  ts/screens/profile/PrivacyMainScreen.tsx
Labels: Bug 🐞, IO-A&I

#6290 chore(IT Wallet): [SIW-1756] Prepare integrity service at startup
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/machine/eid/actors.ts
Labels: IT Wallet

#6292 fix(IT Wallet): [SIW-1761] Crash when integrity service is not available
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
Labels: IT Wallet

#6187 feat: [IOBP-873,IOBP-775] Adapted new biz events definitions API
  package.json
  ts/components/ui/IOScrollView.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsListItemTransaction.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactionDetails.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactionReceipt.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactions.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetLatestBizEventsTransactions.ts
  ts/features/payments/bizEventsTransaction/saga/index.ts
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsPreviewScreen.tsx
  ts/features/payments/bizEventsTransaction/store/actions/index.ts
  ts/features/payments/bizEventsTransaction/store/reducers/index.ts
  ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
  ts/features/payments/bizEventsTransaction/utils/types.ts
  ts/features/payments/common/api/client.ts
  ts/features/payments/common/utils/index.ts
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/features/payments/home/screens/__tests__/PaymentsHomeScreen.test.tsx
Labels: IO-Bonus e pagamenti

#6072 feat: [IOBP-619,IOBP-805] Add payment feedback banner feature flag and remote configuration
  package.json
  ts/features/payments/checkout/components/WalletPaymentFeedbackBanner.tsx
  ts/store/reducers/backendStatus.ts
Labels: IO-Bonus e pagamenti

#6215 chore: [IOBP-852] Add FCI redirect support from barcode scan screen
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/barcode/types/decoders.ts
Labels: Firma con IO, IO-Bonus e pagamenti

#6235 chore(IT Wallet): [SIW-1648] Mixpanel events new features
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/common/components/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/ItwEidInfoBottomSheetContent.tsx
  ts/features/itwallet/common/components/ItwReleaserName.tsx
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/lifecycle/screens/ItwIdentityNotMatchingScreen.tsx
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/presentation/components/ItwCredentialTrustmark.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailsFooter.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialAttachmentScreen.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/newWallet/components/WalletCategoryFilterTabs.tsx
  ts/features/newWallet/components/WalletEmptyScreenContent.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/mixpanelConfig/profileProperties.ts
  ts/mixpanelConfig/superProperties.ts
Labels: IT Wallet

#6270 feat(IT Wallet): [SIW-1584] Add IPZS privacy screen
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/itwallet/discovery/components/ItwPrivacyWebViewComponent.tsx
  ts/features/itwallet/discovery/screens/ItwIpzsPrivacyScreen.tsx
  ts/features/itwallet/discovery/screens/__tests__/ItwIpzsPrivacyScreen.test.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
Labels: IT Wallet

#6294 feat(IT Wallet): [SIW-1742] Display credentials authentic source
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/itwallet/common/components/ItwIssuanceMetadata.tsx
  ts/features/itwallet/common/components/ItwReleaserName.tsx
  ts/features/itwallet/issuance/components/ItwCredentialPreviewClaimsList.tsx
  ts/features/itwallet/presentation/components/ItwPresentationClaimsSection.tsx
  ts/features/itwallet/presentation/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
  yarn.lock
Labels: IT Wallet

#6188 feat: [IOBP-782] Add biz events receipt migration banner info
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsDetailsScreen.tsx
Labels: IO-Bonus e pagamenti

#6283 chore(IT Wallet): [SIW-1743] Display upcoming ITWallet banner for users not yet enabled
  ts/features/itwallet/common/components/ItwUpcomingWalletBanner.tsx
  ts/features/itwallet/common/components/__tests__/ItwUpcomingWalletBanner.test.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
Labels: IT Wallet

#6303 chore(IT Wallet): [SIW-1765] Remove secondary CTA on integrity error
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
Labels: IT Wallet

#6301 chore(IT Wallet): [SIW-1764] Add ipzs privacy policy link inside credential details bottomSheet
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwIssuanceMetadata.tsx
  ts/features/itwallet/common/hooks/useItwInfoBottomSheet.tsx
  ts/features/itwallet/issuance/components/__tests__/__snapshots__/ItwCredentialPreviewClaimsList.test.tsx.snap
  ts/features/itwallet/presentation/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
Labels: IT Wallet

#6305 fix(IT Wallet): [SIW-1766] Enable banners with empty wallet
  ts/features/newWallet/components/WalletCardsContainer.tsx
Labels: IT Wallet

#6302 chore(IT Wallet): [SIW-1745] IT Wallet copy review
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
Labels: IT Wallet

#6307 fix: [PE-726] CGN camelize department title
  locales/en/index.yml
  locales/it/index.yml
Labels: Carta Giovani Nazionale

#6279 chore(Cross): [IOAPPX-394] Replace `GradientScrollView` with `IOScrollView` in the Wallet home screen
  ts/features/newWallet/screens/WalletHomeScreen.tsx
Labels: Design System, Dark mode 🌝, Cross

#6317 fix: [IOBP-900] Remove parenthesis from tax code in payment screen
  ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#6213 feat: [IOBP-834] Add pull to refresh into transactions list screen
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
Labels: IO-Bonus e pagamenti

#6318 fix: [IOBP-901] Missing header in payment methods
  ts/features/payments/details/screens/PaymentsMethodDetailsScreen.tsx
Labels: IO-Bonus e pagamenti

#6316 feat: [IOBP-930] Remove payments redirect banner from wallet
  ts/boot/configureStoreAndPersistor.ts
  ts/features/newWallet/components/WalletPaymentsRedirectBanner.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/screens/__tests__/WalletHomeScreen.test.tsx
  ts/features/newWallet/store/actions/preferences.ts
  ts/features/newWallet/store/reducers/preferences.ts
  ts/features/newWallet/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#6313 fix: [PE-725] CGN merchant categories list details transition header
  ts/features/bonus/cgn/components/merchants/CgnMerchantListSkeleton.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantCategoriesListScreen.tsx
Labels: Carta Giovani Nazionale

#6314 chore: [IOBP-753] Add error backoff retry handling into payments domain
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ui/BannerErrorState.tsx
  ts/features/payments/bizEventsTransaction/store/reducers/index.ts
  ts/features/payments/common/hooks/usePaymentsBackoffRetry.tsx
  ts/features/payments/common/saga/handlePaymentsSessionToken.ts
  ts/features/payments/common/store/actions/index.ts
  ts/features/payments/common/store/reducers/index.ts
  ts/features/payments/common/store/reducers/paymentsBackoffRetryReducer.ts
  ts/features/payments/common/store/selectors/index.ts
  ts/features/payments/common/types/PaymentsBackoffRetry.ts
  ts/features/payments/common/utils/__tests__/backoffRetry.test.ts
  ts/features/payments/common/utils/backoffRetry.ts
  ts/features/payments/common/utils/types.ts
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
Labels: IO-Bonus e pagamenti

#6322 chore: [IOBP-925] Add amount parameter when requesting list of all payment methods
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentGetAllMethods.test.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetAllMethods.ts
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/store/actions/networking.ts
Labels: IO-Bonus e pagamenti

#6320 chore: [IOBP-933] Add exponential backoff retry into wallet section screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/saga/networking/details/getCgnInformationSaga.ts
  ts/features/bonus/cgn/store/actions/details.ts
  ts/features/bonus/cgn/store/reducers/details.ts
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
  ts/features/newWallet/components/WalletCardsCategoryRetryErrorBanner.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/payments/common/types/PaymentsBackoffRetry.ts
Labels: IO-Bonus e pagamenti

#6331 chore(IT Wallet): [SIW-1784] Typo in identification mode selection screen
  locales/en/index.yml
  locales/it/index.yml
Labels: IT Wallet

#6329 fix: [PE-688] CGN activation images
  ts/features/bonus/common/components/BonusInformationComponent.tsx
Labels: Carta Giovani Nazionale

#6325 fix: [IOPID-2423] Add logic to get the zendesk token in payments and others flow
  ts/features/zendesk/saga/index.ts
  ts/features/zendesk/saga/orchestration/index.ts
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
Labels: Bug 🐞, IO-A&I

#6333 chore(IT Wallet): [SIW-1716] Add action to ITWallet upcoming banner
  .env.local
  .env.production
  ts/config.ts
  ts/features/itwallet/common/components/ItwUpcomingWalletBanner.tsx
Labels: IT Wallet

#6276 fix(IT Wallet): [SIW-1733] Disable wallet activation from async credential link when the user is not enabled
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
  ts/features/itwallet/issuance/screens/__tests__/ItwIssuanceCredentialAsyncContinuationScreen.test.tsx
  ts/features/itwallet/issuance/screens/__tests__/__snapshots__/ItwIssuanceCredentialAsyncContinuationScreen.test.tsx.snap
  ts/features/itwallet/navigation/useItwLinkingOptions.tsx
Labels: IT Wallet

#6306 feat: [IOPID-2322] - CieID Error handling
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/cie/__tests__/CieIdErrorScreen.test.tsx
  ts/features/cie/__tests__/__snapshots__/wizards.test.tsx.snap
  ts/features/cie/screens/errors/CieIdErrorScreen.tsx
  ts/features/cieLogin/__tests__/utils.test.ts
  ts/features/cieLogin/components/CieIdLoginWebView.tsx
  ts/features/cieLogin/utils/index.ts
  ts/hooks/useNavigateToLoginMethod.tsx
  ts/screens/authentication/AuthErrorScreen.tsx
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/components/AuthErrorComponent.tsx
  ts/screens/authentication/idpAuthSessionHandler.tsx
Labels: IO-A&I

#6339 chore: [IOPID-2359] Delete sessionRefresh FF reference
  package.json
Labels: IO-A&I

#6335 Add collaboratos as codeowners
  CODEOWNERS
Labels: code review needed 💻📱

#6345 fix: [IOBP-902] Payment header opacity on scroll
  ts/features/payments/details/components/PaymentsMethodDetailsBaseScreenComponent.tsx
Labels: IO-Bonus e pagamenti

#6337 chore: [IOBP-938] Add `singleTop` as launchMode into AndroidManifest.xml to better manage Custom Tabs
  android/app/src/main/AndroidManifest.xml
Labels: dont-merge :raised_hand:, IO-Bonus e pagamenti

#6332 chore(IT Wallet): [SIW-1773] Copy errors inside error screens
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6321 fix(IT Wallet): [SIW-1772] Mixpanel properties and events tracking issues
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/common/components/ItwEidInfoBottomSheetContent.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/lifecycle/saga/handleWalletInstanceResetSaga.ts
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/newWallet/components/WalletEmptyScreenContent.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/mixpanelConfig/profileProperties.ts
  ts/mixpanelConfig/superProperties.ts
Labels: IT Wallet

#6344 chore(IT Wallet): [SIW-1769] Reintroduce integrity check KO message
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
Labels: IT Wallet

#6343 fix(IT Wallet): [SIW-1798] Removes unnecessary rendering of failure screens during issuance flows
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/machine/eid/selectors.ts
Labels: IT Wallet

#6355 chore: [IOBP-940] Map payment outcome 19 in the mixpanel events
  ts/features/payments/checkout/analytics/index.ts
Labels: IO-Bonus e pagamenti

#6354 chore: [IOBP-837] Add payee name as header title into transaction details
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsDetailsScreen.tsx
Labels: IO-Bonus e pagamenti

#6353 feat: [IOBP-801] Add transactions category tab filters
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsFadeInOutAnimationView.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsFilterTabs.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsListItemTransaction.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionLoadingList.tsx
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactions.ts
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
  ts/features/payments/bizEventsTransaction/store/actions/index.ts
  ts/features/payments/bizEventsTransaction/store/reducers/index.ts
  ts/features/payments/bizEventsTransaction/types/index.ts
  ts/features/payments/bizEventsTransaction/utils/types.ts
Labels: IO-Bonus e pagamenti

#6356 chore: [IOBP-948] Remove transaction details screen title
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
Labels: IO-Bonus e pagamenti

#6338 chore(IT Wallet): [SIW-1780] Use errors in `issuance_errors_supported` when issuing credentials
  package.json
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/machine/credential/failure.ts
  yarn.lock
Labels: IT Wallet
