Repository pagopa/io-app, pull requests merged in 2024-03, with the labels that each got.

#5559 fix: [IOCOM-1154] Fix for double navigation bar on message details
  ts/features/messages/navigation/MessagesNavigator.tsx
Labels: IO-Comunicazione

#5542 chore: [IOBP-569] Removed expiry date from payment summary module checkout
  ts/features/payments/payment/components/WalletPaymentConfirmContent.tsx
Labels: IO-Bonus e pagamenti

#5563 fix: [IOCOM-1154] Fix for `undefined` value on `isDesignSystemEnabled` (and double navigation bar)
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/store/reducers/persistedPreferences.ts
Labels: IO-Comunicazione

#5552 chore(Cross): [IOAPPX-254] Add iOS smooth corners to specific components
  ts/components/ui/cards/payment/PaymentCardBig.tsx
  ts/components/ui/cards/payment/PaymentCardSmall.tsx
  ts/components/ui/cards/payment/__test__/__snapshots__/PaymentCards.test.tsx.snap
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PspRadioItem.test.tsx.snap
  ts/utils/hooks/bottomSheet.tsx
Labels: Design System, Cross, :nail_care: Visual tweaks

#5560 feat: [IOCOM-853] Add footer component to MessageDetailsScreen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/MessageDetail/MessageDetailsFooter.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsFooter.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsFooter.test.tsx.snap
  ts/features/messages/screens/LegacyMessageDetailScreen.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/screens/services/ServicesWebviewScreen.tsx
  ts/store/reducers/entities/services/servicesById.ts
Labels: IO-Comunicazione

#5565 feat: [IOCOM-855] Add bottom sheet to display message extra data
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/MessageDetail/MessageDetailsFooter.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsFooter.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsFooter.test.tsx.snap
  ts/features/messages/hooks/useMessageMoreDataBottomSheet.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
Labels: IO-Comunicazione

#5566 chore(Cross): [IOAPPX-259] Upgrade `io-app-design-system` to `v.1.25.1`
  package.json
  ts/features/fci/components/SignatureFieldItem.tsx
  ts/features/fci/components/__tests__/__snapshots__/SignatureFieldItem.test.tsx.snap
  yarn.lock
Labels: Cross

#5567 feat: [IOCOM-858] Generic payment update for messages
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/features/messages/saga/handlePaymentUpdateRequests.ts
  ts/features/messages/saga/index.ts
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/__tests__/payments.test.ts
  ts/features/messages/store/reducers/index.ts
  ts/features/messages/store/reducers/payments.ts
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePaymentBottomSheet.tsx
  ts/features/pn/components/MessagePaymentItem.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/components/__test__/MessagePaymentItem.test.tsx
  ts/features/pn/components/__test__/MessagePayments.test.tsx
  ts/features/pn/screens/LegacyMessageDetailsScreen.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/reducers/index.ts
  ts/features/pn/store/sagas/watchPaymentStatusSaga.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/pn/utils/index.ts
  ts/sagas/startup.ts
Labels: IO-Comunicazione

#5548 feat: [IOPID-1500] Adopt the new DS to `IngressScreen`
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/navigation/AppStackNavigator.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/carousel/Carousel.tsx
  ts/screens/ingress/CheckBox.tsx
  ts/screens/ingress/IngressScreen.tsx
  ts/screens/profile/analytics/index.ts
Labels: IO-A&I

#5572 fix: [IOBP-582] Behavior of the new payment go back with only one PSP
  ts/features/payments/payment/components/WalletPaymentConfirmContent.tsx
  ts/features/payments/payment/components/WalletPaymentHeader.tsx
  ts/features/payments/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/payment/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/payment/store/__tests__/store.test.ts
  ts/features/payments/payment/store/actions/orchestration.ts
  ts/features/payments/payment/store/reducers/index.ts
  ts/features/payments/payment/types/index.ts
Labels: IO-Bonus e pagamenti

#5562 feat: [IOPID-1512] New DS on onboarding finished thank you page
  ts/screens/onboarding/OnboardingCompletedScreen.tsx
  ts/screens/onboarding/__tests__/OnboardingCompletedScreen.test.tsx
Labels: IO-A&I

#5547 feat: [IOPID-1504] Adopt the new DS to `IdpSuccessfulAuthentication`
  locales/en/index.yml
  locales/it/index.yml
  ts/components/IdpSuccessfulAuthentication.tsx
  ts/screens/authentication/idpAuthSessionHandler.tsx
  ts/screens/profile/analytics/index.ts
  ts/store/reducers/authentication.ts
Labels: IO-A&I

#5554 feat: [IOPID-1499] Adopt the new DS layout to splash screens
  android/app/build.gradle
  android/app/src/main/res/drawable/eu_next_logo.xml
  android/app/src/main/res/drawable/logo_io.xml
  android/app/src/main/res/drawable/logo_pagopa.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/eu_next_logo.png
  android/app/src/main/res/mipmap-hdpi/logo_io.png
  android/app/src/main/res/mipmap-hdpi/logo_pagopa.png
  android/app/src/main/res/mipmap-mdpi/eu_next_logo.png
  android/app/src/main/res/mipmap-mdpi/logo_io.png
  android/app/src/main/res/mipmap-mdpi/logo_pagopa.png
  android/app/src/main/res/mipmap-xhdpi/eu_next_logo.png
  android/app/src/main/res/mipmap-xhdpi/logo_io.png
  android/app/src/main/res/mipmap-xhdpi/logo_pagopa.png
  android/app/src/main/res/mipmap-xxhdpi/eu_next_logo.png
  android/app/src/main/res/mipmap-xxhdpi/logo_io.png
  android/app/src/main/res/mipmap-xxhdpi/logo_pagopa.png
  android/app/src/main/res/mipmap-xxxhdpi/eu_next_logo.png
  android/app/src/main/res/mipmap-xxxhdpi/logo_io.png
  android/app/src/main/res/mipmap-xxxhdpi/logo_pagopa.png
  ios/ItaliaApp/Images.xcassets/euNextLogo.imageset/Contents.json
  ios/ItaliaApp/Images.xcassets/euNextLogo.imageset/IT Finanziato dall'Unione europea 1.svg
  ios/ItaliaApp/Images.xcassets/euNextLogo.imageset/IT Finanziato dall'Unione europea 2.svg
  ios/ItaliaApp/Images.xcassets/euNextLogo.imageset/IT Finanziato dall'Unione europea.svg
  ios/ItaliaApp/Images.xcassets/euNextLogo.imageset/eu_next_logo.svg
  ios/ItaliaApp/Images.xcassets/logo_consiglio_ministri.imageset/Contents.json
  ios/ItaliaApp/Images.xcassets/logo_consiglio_ministri.imageset/logo ConsiglioMInistri@2x.png
  ios/ItaliaApp/Images.xcassets/logo_consiglio_ministri.imageset/logo ConsiglioMInistri@3x.png
  ios/ItaliaApp/Images.xcassets/logo_consiglio_ministri.imageset/logo_ConsiglioMInistri.png
  ios/ItaliaApp/Images.xcassets/logo_consiglio_ministri.imageset/logo_consiglio_ministri.svg
  ios/ItaliaApp/Images.xcassets/logo_io.imageset/Contents.json
  ios/ItaliaApp/Images.xcassets/logo_io.imageset/io-app-logo.png
  ios/ItaliaApp/Images.xcassets/logo_io.imageset/io-app-logo@2x.png
  ios/ItaliaApp/Images.xcassets/logo_io.imageset/io-app-logo@3x.png
  ios/ItaliaApp/Images.xcassets/logo_io.imageset/logo_io.svg
  ios/ItaliaApp/Images.xcassets/logo_pagopa.imageset/Contents.json
  ios/ItaliaApp/Images.xcassets/logo_pagopa.imageset/logo_pagopa.png
  ios/ItaliaApp/Images.xcassets/logo_pagopa.imageset/logo_pagopa.svg
  ios/ItaliaApp/Images.xcassets/logo_pagopa.imageset/pagopa - logo -  darkbg - grayscale - transparency@2x.png
  ios/ItaliaApp/Images.xcassets/logo_pagopa.imageset/pagopa - logo -  darkbg - grayscale - transparency@3x.png
  ios/ItaliaApp/LaunchScreen.storyboard
Labels: IO-A&I

#5573 chore: [IOBP-581] Changed text into payment cancelled by user outcome screen
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#5570 feat: [IOCOM-854] Add bottom sheet to display message contacts
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/MessageDetail/ContactsListItem.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsFooter.tsx
  ts/features/messages/components/MessageDetail/ShowMoreListItem.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsFooter.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsFooter.test.tsx.snap
  ts/features/messages/hooks/useMessageMoreDataBottomSheet.tsx
Labels: IO-Comunicazione

#5575 feat: [IOCOM-857] Payment data on message details
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/common/versionInfo/store/reducers/versionInfo.ts
  ts/features/messages/components/MessageDetail/MessageDetailsPayment.tsx
  ts/features/messages/components/MessageDetail/MessagePaymentItem.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsPayment.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessagePaymentItem.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsPayment.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessagePaymentItem.test.tsx.snap
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/__tests__/detailsById.test.ts
  ts/features/messages/store/reducers/__tests__/payments.test.ts
  ts/features/messages/store/reducers/detailsById.ts
  ts/features/messages/store/reducers/index.ts
  ts/features/messages/store/reducers/payments.ts
  ts/features/messages/utils/__tests__/index.test.ts
  ts/features/messages/utils/index.ts
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePaymentBottomSheet.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/components/__test__/MessageFooter.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageFooter.test.tsx.snap
  ts/features/pn/screens/LegacyMessageDetailsScreen.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/store/reducers/__test__/index.test.ts
  ts/features/pn/store/reducers/index.ts
  ts/features/pn/utils/index.ts
  ts/store/reducers/__tests__/profile.test.ts
  ts/store/reducers/profile.ts
Labels: IO-Comunicazione

#5512 chore(Cross): [IOAPPX-249] Update `build.gradle`
  android/build.gradle
Labels: Cross

#5546 chore: [IOBP-574] Adds `success` flag to payment's Zendesk support payload
  ts/features/payments/history/store/__tests__/store.test.ts
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/history/types/index.ts
  ts/features/payments/payment/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/payments/payment/screens/WalletPaymentConfirmScreen.tsx
Labels: IO-Bonus e pagamenti

#5587 chore(IT Wallet): [SIW-941] Update Pr title with SIW id
  scripts/ts/danger/updatePrTitle.tsx
Labels: IT Wallet

#5582 feat: [IOCOM-856] Add CTAs to `MessageDetailsScreen`
  ts/components/cta/ExtractedCTABar.tsx
  ts/components/cta/ExtractedCTAs.tsx
  ts/features/messages/components/MessageDetail/CtaBar.tsx
  ts/features/messages/components/MessageDetail/FooterCTAs.tsx
  ts/features/messages/hooks/usePNOptInMessage.ts
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/utils/messages.ts
  ts/features/pn/utils/__tests__/index.test.ts
  ts/features/pn/utils/index.ts
Labels: IO-Comunicazione

#5590 chore(Cross): [IOAPPX-261] Add the new `contrast` variant to `ButtonLink` in the DS section
  ts/features/design-system/core/DSButtons.tsx
Labels: Design System, Cross

#5588 chore(IT Wallet): [SIW-940] Add new wallet section screen with empty state
  locales/en/index.yml
  locales/it/index.yml
  ts/features/newWallet/components/WalletEmptyScreenContent.tsx
  ts/features/newWallet/components/__tests__/WalletEmptyScreenContent.test.tsx
  ts/features/newWallet/components/__tests__/__snapshots__/WalletEmptyScreenContent.test.tsx.snap
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
Labels: IT Wallet

#5589 chore(IT Wallet): [SIW-942] Add payments section redirect banner within wallet section
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/configureStoreAndPersistor.ts
  ts/features/common/store/reducers/index.ts
  ts/features/newWallet/components/WalletPaymentsRedirectBanner.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/store/actions/index.ts
  ts/features/newWallet/store/actions/preferences.ts
  ts/features/newWallet/store/reducers/index.ts
  ts/features/newWallet/store/reducers/preferences.ts
  ts/features/newWallet/store/selectors/index.ts
  ts/store/actions/types.ts
Labels: IT Wallet

#5583 feat: [IOCOM-859] New DS payment button on standard message details
  locales/en/index.yml
  locales/it/index.yml
  ts/components/cta/CTAsBar.tsx
  ts/components/cta/__test__/CTAsBar.test.tsx
  ts/components/cta/__test__/__snapshots__/CTAsBar.test.tsx.snap
  ts/features/messages/components/MessageDetail/FooterCTAs.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsScrollViewAdditionalSpace.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsStickyFooter.tsx
  ts/features/messages/components/MessageDetail/MessagePaymentItem.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsScrollViewAdditionalSpace.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsStickyFooter.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsScrollViewAdditionalSpace.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsStickyFooter.test.tsx.snap
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/store/reducers/__tests__/payments.test.ts
  ts/features/messages/store/reducers/payments.ts
  ts/features/messages/utils/__tests__/index.test.ts
  ts/features/messages/utils/index.ts
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/components/__test__/MessageFooter.test.tsx
  ts/features/pn/hooks/usePNOptInMessage.ts
  ts/features/pn/store/reducers/__test__/payments.test.ts
  ts/features/pn/store/reducers/payments.ts
Labels: IO-Comunicazione

#5580 chore(IT Wallet): [SIW-907] Add StrongBox Mixpanel tracking for Lollipop keys
  ios/Podfile.lock
  package.json
  ts/features/lollipop/utils/crypto.ts
  ts/sagas/startup.ts
  ts/utils/analytics.ts
  yarn.lock
Labels: legal-approved ⚖️ ✅, IT Wallet

#5594 fix: [IOBP-596] Fix unexpected behavior in wallet onboarding Webview on Android devices
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/onboarding/components/WalletOnboardingError.tsx
  ts/features/payments/onboarding/components/WalletOnboardingSuccess.tsx
  ts/features/payments/onboarding/hooks/useWalletOnboardingWebView.tsx
  ts/features/payments/onboarding/screens/WalletOnboardingFeedbackScreen.tsx
  ts/features/payments/onboarding/screens/WalletOnboardingSelectPaymentMethodScreen.tsx
  ts/features/payments/onboarding/types/OnboardingOutcomeEnum.ts
  ts/features/payments/onboarding/types/index.ts
  ts/features/payments/onboarding/utils/index.ts
Labels: IO-Bonus e pagamenti

#5604 chore(IT Wallet): [SIW-948] Add reducers and selectors for cards in the new wallet section
  ts/features/newWallet/store/__tests__/cards.test.ts
  ts/features/newWallet/store/actions/cards.ts
  ts/features/newWallet/store/actions/index.ts
  ts/features/newWallet/store/reducers/cards.ts
  ts/features/newWallet/store/reducers/index.ts
  ts/features/newWallet/store/selectors/index.ts
  ts/features/newWallet/types/index.ts
Labels: IT Wallet

#5568 fix: [IABT-1540] Fix expired session handling in payment flow
  ts/features/fastLogin/saga/pendingActionsSaga.ts
  ts/sagas/startup.ts
  ts/sagas/wallet.ts
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
  ts/screens/wallet/payment/hooks/useStartOrResumePayment.ts
  ts/store/actions/wallet/payment.ts
Labels: IO-Bonus e pagamenti

#5593 chore: [IOBP-589] Adapted new payment flow with new swagger definitions
  package.json
  ts/features/payments/common/utils/index.ts
  ts/features/payments/details/saga/handleTogglePagoPaCapability.ts
  ts/features/payments/details/saga/index.ts
  ts/features/payments/details/screens/WalletDetailsScreen.tsx
  ts/features/payments/details/store/index.ts
  ts/features/payments/onboarding/saga/handleStartWalletOnboarding.ts
  ts/features/payments/payment/components/WalletPaymentConfirmContent.tsx
  ts/features/payments/payment/screens/WalletPaymentPickMethodScreen.tsx
Labels: IO-Bonus e pagamenti

#5544 feat: [IOPID-1511] [IOPID-1529] Add new DS in Services Preference Screen (Profile and Onboarding)
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ui/RNavScreenWithLargeHeader.tsx
  ts/features/design-system/core/DSSelection.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/screens/profile/components/services/ManualConfigBottomSheet.tsx
  ts/screens/profile/components/services/ServicesContactComponent.tsx
Labels: IO-A&I

#5600 fix(Cross): [IOAPPX-263] IOS crash during root modal hiding
  patches/patches.md
  patches/react-native-reanimated+2.10.0.patch
Labels: Cross

#5608 chore: [IOBP-597] Add new payment card component
  img/wallet/payment-methods/paypal/paypal_logo_ext.svg
  ts/components/ui/cards/payment/PaymentCardsCarousel.tsx
  ts/features/design-system/core/DSCards.tsx
  ts/features/payments/common/components/PaymentCard.tsx
  ts/features/payments/common/components/PaymentCardBankLogo.tsx
  ts/features/payments/common/components/__tests__/PaymentCard.test.tsx
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCard.test.tsx.snap
  ts/features/payments/details/components/WalletDetailsPagoPaPaymentCapability.tsx
  ts/features/payments/details/components/WalletDetailsPaymentMethodFeatures.tsx
  ts/features/payments/details/components/WalletDetailsPaymentMethodInitiatives.tsx
  ts/features/payments/details/components/WalletDetailsPaymentMethodSettings.tsx
  ts/features/payments/details/screens/WalletDetailsScreen.tsx
  ts/features/payments/onboarding/components/WalletOnboardingPaymentMethodsList.tsx
  ts/features/payments/onboarding/components/WalletPaymentMethodItemSkeleton.tsx
Labels: IT Wallet, IO-Bonus e pagamenti

#5610 chore(IT Wallet): [SIW-957] Add wallet card component for IdPay initiatives
  ts/features/design-system/core/DSCards.tsx
  ts/features/idpay/wallet/components/IdPayWalletCard.tsx
  ts/features/idpay/wallet/components/__tests__/IdPayWalletCard.test.tsx
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayWalletCard.test.tsx.snap
Labels: IT Wallet

#5599 feat(Firma con IO): [SFEQS-2137] Make PDF annotations read-only on iOS
  patches/patches.md
  patches/react-native-pdf+6.4.0.patch
  ts/features/fci/components/DocumentViewer.tsx
  ts/features/fci/components/DocumentWithSignature.tsx
  ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
Labels: Firma con IO

#5615 chore: [IOBP-568] Add email to payment outcome 17 description
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/payment/screens/WalletPaymentOutcomeScreen.tsx
Labels: IO-Bonus e pagamenti

#5612 chore: [IOBP-578,IOBP-577] Add dynamic payment method logos
  package.json
  ts/features/payments/details/store/index.ts
  ts/features/payments/onboarding/components/WalletOnboardingPaymentMethodsList.tsx
  ts/features/payments/payment/saga/networking/__tests__/handleWalletPaymentCalculateFees.test.ts
  ts/features/payments/payment/saga/networking/__tests__/handleWalletPaymentGetUserWallets.test.ts
  ts/features/payments/payment/screens/WalletPaymentPickMethodScreen.tsx
  yarn.lock
Labels: IO-Bonus e pagamenti

#5603 feat: [IOCOM-879] Bottom sheet for SEND's F24 with the new DS
  ts/features/messages/components/MessageDetail/MessageDetailsAttachmentItem.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsPayment.tsx
  ts/features/messages/hooks/useAttachmentDownload.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/pn/components/F24ListBottomSheetLink.tsx
  ts/features/pn/components/F24Section.tsx
  ts/features/pn/components/LegacyMessageAttachments.tsx
  ts/features/pn/components/LegacyMessageDetails.tsx
  ts/features/pn/components/LegacyMessageF24.tsx
  ts/features/pn/components/__test__/F24ListBottomSheetLink.test.tsx
  ts/features/pn/components/__test__/LegacyMessageAttachments.test.tsx
  ts/features/pn/components/__test__/__snapshots__/F24ListBottomSheetLink.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/F24Section.test.tsx.snap
  ts/features/pn/hooks/useF24BottomSheet.tsx
Labels: IO-Comunicazione

#5605 chore: [IOPAE-1058] Add services local feature flag
  .env.local
  .env.production
  ts/config.ts
Labels: Redesign Servizi

#5618 chore: [IOBP-592] Updated wallet and e-commerce definitions
  package.json
  ts/features/payments/payment/saga/networking/__tests__/handleWalletPaymentGetUserWallets.test.ts
Labels: IO-Bonus e pagamenti

#5557 chore(Cross): [IOAPPX-256] Remove local ToastProvider
  ts/App.tsx
  ts/components/NewRemindEmailValidationOverlay.tsx
  ts/components/Toast/ToastNotification.tsx
  ts/components/Toast/ToastProvider.tsx
  ts/components/Toast/__tests__/ToastNotification.test.tsx
  ts/components/Toast/__tests__/__snapshots__/ToastNotification.test.tsx.snap
  ts/components/Toast/context.ts
  ts/components/Toast/index.ts
  ts/components/Toast/types.ts
  ts/components/Toast/useIOToast.ts
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/bonus/cgn/components/detail/CgnUnsubscribe.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaInformationComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaPendingComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaStatusDetailsComponent.tsx
  ts/features/bonus/cgn/components/merchants/CgnDiscountDetail.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/design-system/core/DSToastNotifications.tsx
  ts/features/idpay/configuration/xstate/__tests__/actions.test.ts
  ts/features/idpay/configuration/xstate/actions.ts
  ts/features/idpay/details/screens/IdPayOperationsListScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentCodeScanScreen.tsx
  ts/features/messages/components/MessageAttachment/MessageAttachment.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsStickyFooter.tsx
  ts/features/messages/components/MessageDetail/MessagePaymentItem.tsx
  ts/features/messages/hooks/useAttachmentDownload.tsx
  ts/features/messages/hooks/useMessageCalendar.ts
  ts/features/payments/barcode/screens/WalletBarcodeScanScreen.tsx
  ts/features/payments/details/components/WalletDetailsPagoPaPaymentCapability.tsx
  ts/features/payments/details/components/WalletDetailsPaymentMethodScreen.tsx
  ts/features/pn/components/MessageFooter.tsx
  ts/features/wallet/common/BasePaymentMethodScreen.tsx
  ts/features/wallet/component/features/PaymentStatusSwitch.tsx
  ts/sagas/wallet/pagopaApis.ts
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/DownloadProfileDataScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/screens/profile/ShareDataScreen.tsx
  ts/screens/profile/WebPlayground.tsx
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
  ts/utils/clipboard.ts
Labels: Cross

#5581 feat: [IOPID-1540] Adopt the new DS to `IdentificationModal`
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/Pinpad/KeyPad.tsx
  ts/components/Pinpad/index.tsx
  ts/components/core/variables/IOStyleVariables.ts
  ts/screens/authentication/carousel/Carousel.tsx
  ts/screens/modal/IdentificationLockModal.tsx
  ts/screens/modal/IdentificationModal.tsx
  ts/screens/modal/components/IdentificationNumberPad.tsx
  ts/store/actions/identification.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/__tests__/identification.test.ts
  ts/store/reducers/__tests__/identificationStateMigration.test.ts
  ts/store/reducers/identification.ts
  ts/store/reducers/index.ts
  ts/utils/hooks/theme/index.ts
  ts/utils/hooks/useBiometricType.ts
  ts/utils/identification/index.tsx
Labels: IO-A&I

#5614 feat: [IOPID-1566,IOPID-1567,IOPID-1570] Adopt the new DS to FL modals
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fastLogin/screens/AskUserInteractionScreen.tsx
  ts/features/fastLogin/screens/AskUserInterarctionScreen.tsx
  ts/features/fastLogin/screens/FastLoginModals.tsx
  ts/features/fastLogin/screens/__tests__/AskUserToContinueScreen.test.tsx
Labels: IO-A&I

#5619 chore(IT Wallet): [SIW-954] Add new wallet base UI components
  ts/features/design-system/core/DSCards.tsx
  ts/features/design-system/core/DSWallet.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/features/idpay/wallet/components/IdPayCard.tsx
  ts/features/idpay/wallet/components/IdPayWalletCard.tsx
  ts/features/idpay/wallet/components/__tests__/IdPayCard.test.tsx
  ts/features/idpay/wallet/components/__tests__/IdPayWalletCard.test.tsx
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayWalletCard.test.tsx.snap
  ts/features/newWallet/components/WalletCardBaseComponent.tsx
  ts/features/newWallet/components/WalletCardCategoryContainer.tsx
  ts/features/newWallet/components/WalletCardSkeleton.tsx
  ts/features/newWallet/components/__tests__/WalletCardBaseComponent.test.tsx
  ts/features/newWallet/store/__tests__/cards.test.ts
  ts/features/newWallet/store/selectors/index.ts
  ts/features/newWallet/types/index.ts
  ts/features/payments/common/components/PaymentCard.tsx
  ts/features/payments/common/components/PaymentWalletCard.tsx
Labels: IT Wallet

#5637 chore(Cross): [IOAPPX-270] Update `io-app-design-system` to `1.31.0`
  package.json
  ts/components/cta/__test__/__snapshots__/CTAsBar.test.tsx.snap
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/QtspClauseListItem.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/SignatureFieldItem.test.tsx.snap
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsStickyFooter.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/OrganizationHeader.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/newWallet/components/__tests__/__snapshots__/WalletEmptyScreenContent.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageFooter.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  yarn.lock
Labels: a11y, Design System, Cross

#5634 fix: [IOBP-593] Fix back button in PSP selection screen during payment
  ts/features/payments/payment/components/WalletPaymentHeader.tsx
Labels: IO-Bonus e pagamenti

#5625 chore(IT Wallet): [SIW-950] Add ID Pay initiatives cards in new wallet section
  img/features/idpay/wallet_card.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSWallet.tsx
  ts/features/idpay/wallet/components/IdPayCard.tsx
  ts/features/idpay/wallet/components/__tests__/IdPayCard.test.tsx
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap
  ts/features/idpay/wallet/saga/__test__/handleGetWallet.test.ts
  ts/features/idpay/wallet/saga/handleGetWallet.ts
  ts/features/newWallet/components/WalletCardBaseComponent.tsx
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/components/__tests__/WalletCardsCategoryContainer.test.tsx
  ts/features/newWallet/components/__tests__/WalletCardsContainer.test.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/types/index.ts
Labels: IT Wallet

#5635 chore: [IOBP-606] Add new payments section
  locales/en/index.yml
  locales/it/index.yml
  ts/features/newWallet/components/WalletPaymentsRedirectBanner.tsx
  ts/features/payments/home/components/PaymentsHomeScreenHistorySection.tsx
  ts/features/payments/home/components/PaymentsHomeScreenMethodsSection.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/navigation/params/MainTabParamsList.ts
  ts/navigation/params/ProfileParamsList.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/reducers/persistedPreferences.ts
Labels: IO-Bonus e pagamenti

#5632 feat: [IOPID-1509,IOPID-1484] Integrate new DS on email insert/validation in onboarding flow and integrate new MP events
  .env.local
  .env.production
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/EmailReadComponent.tsx
  ts/components/NewRemindEmailValidationOverlay.tsx
  ts/components/RemindEmailValidationOverlay.tsx
  ts/components/__tests__/NewRemindEmailValidationOverlay.test.tsx
  ts/components/countdown/CountdownProvider.tsx
  ts/components/ui/LoadingIndicator.tsx
  ts/components/ui/ProgressIndicator.tsx
  ts/config.ts
  ts/features/fastLogin/store/selectors/__tests__/emailUniquenessValidation.test.ts
  ts/features/fastLogin/store/selectors/index.ts
  ts/features/fci/components/__tests__/__snapshots__/LoadingComponent.test.tsx.snap
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/zendesk/components/ZendeskSupportComponent.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/navigation/OnboardingNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/OnboardingParamsList.ts
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/sagas/startup.ts
  ts/sagas/startup/__tests__/checkProfileEmailSaga.test.tsx
  ts/sagas/startup/checkAcknowledgedEmailSaga.ts
  ts/sagas/startup/checkEmailSaga.ts
  ts/screens/analytics/emailAnalytics.ts
  ts/screens/authentication/carousel/Carousel.tsx
  ts/screens/modal/IdentificationLockModal.tsx
  ts/screens/modal/IdentificationModal.tsx
  ts/screens/onboarding/OnboardingEmailInsertScreen.tsx
  ts/screens/onboarding/OnboardingEmailReadScreen.tsx
  ts/screens/onboarding/__tests__/EmailInsertScreen.test.tsx
  ts/screens/profile/CduEmailInsertScreen.tsx
  ts/screens/profile/EmailInsertScreen.tsx
  ts/screens/profile/EmailReadScreen.tsx
  ts/screens/profile/EmailValidationSendEmailScreen.tsx
  ts/screens/profile/ProfileDataScreen.tsx
  ts/screens/profile/__test__/ProfileDataScreen.test.tsx
  ts/screens/profile/components/CountdownComponent.tsx
  ts/screens/profile/mailCheck/EmailAlreadyTakenScreen.tsx
  ts/screens/profile/mailCheck/ValidateEmailScreen.tsx
  ts/store/actions/profile.ts
  ts/store/reducers/emailValidation.ts
  ts/store/reducers/profile.ts
  ts/store/sagas/emailValidationPollingSaga.ts
  ts/utils/hooks/theme/index.ts
Labels: IO-A&I

#5626 chore(IT Wallet): [SIW-952] Add CGN card in new wallet section
  img/features/cgn/cgn_card.svg
  ts/features/bonus/cgn/components/CgnCard.tsx
  ts/features/bonus/cgn/components/CgnWalletCard.tsx
  ts/features/bonus/cgn/components/__test__/CgnCard.test.tsx
  ts/features/bonus/cgn/components/__test__/__snapshots__/CgnCard.test.tsx.snap
  ts/features/bonus/cgn/saga/networking/details/getCgnInformationSaga.ts
  ts/features/design-system/core/DSCards.tsx
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/types/index.ts
Labels: IT Wallet

#5607 chore: [IOPAE-1045] Add new service details base screen
  ts/components/NavBarLabel.tsx
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/idpay/details/components/BeneficiaryDetailsContent.tsx
  ts/features/messages/utils/messages.ts
  ts/features/services/navigation/navigator.tsx
  ts/features/services/navigation/params.ts
  ts/features/services/navigation/routes.ts
  ts/features/services/screens/ServiceDetailsScreen.tsx
  ts/features/wallet/component/card/FeaturedCardCarousel.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/ServicesNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/navigation/params/AppParamsList.ts
  ts/navigation/params/MainTabParamsList.ts
  ts/navigation/params/ServicesParamsList.ts
  ts/navigation/routes.ts
  ts/screens/services/LegacyServiceDetailsScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
  ts/screens/services/ServicesLocalScreen.tsx
  ts/screens/services/ServicesNationalScreen.tsx
  ts/screens/services/__tests__/ServiceDetailsScreen.test.tsx
  ts/store/actions/navigation.ts
  ts/store/reducers/entities/services/servicesById.ts
  ts/utils/internalLink.ts
Labels: Redesign Servizi

#5645 chore(IT Wallet): [SIW-962] Add cards onboarding CTA in the new wallet section
  locales/en/index.yml
  locales/it/index.yml
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/components/WalletEmptyScreenContent.tsx
  ts/features/newWallet/components/WalletPaymentsRedirectBanner.tsx
  ts/features/newWallet/components/__tests__/__snapshots__/WalletEmptyScreenContent.test.tsx.snap
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/screens/__tests__/WalletHomeScreen.test.tsx
Labels: IT Wallet

#5641 feat: [IOPID-1541,IOPID-1542] Adopt the new DS to `RootedModal`
  img/rooted/broken-phone.png
  img/rooted/broken-phone@2x.png
  img/rooted/broken-phone@3x.png
  locales/de/jailbroken_body.md
  locales/de/rooted_body.md
  locales/en/index.yml
  locales/en/jailbroken_body.md
  locales/en/rooted_body.md
  locales/it/index.yml
  locales/it/jailbroken_body.md
  locales/it/rooted_body.md
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/routes.ts
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/modal/RootedDeviceModal.tsx
Labels: IO-A&I

#5613 feat: [IOCOM-1172] Update business logic for payment reminder on a message details screen with the new DS
  ts/features/messages/components/MessageDetail/MessageDetailsReminder.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsReminderExpired.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsReminderExpiring.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsReminder.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsReminderExpired.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsReminderExpiring.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminder.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpired.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpiring.test.tsx.snap
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/screens/__tests__/MessageDetailsScreen.test.tsx
  ts/features/messages/store/reducers/__tests__/payments.test.ts
  ts/features/messages/store/reducers/payments.ts
Labels: IO-Comunicazione

#5647 feat: [IOPID-1611] Adopt new DS on CIE not supported modal
  locales/de/index.yml
  locales/en/cie/cieNotSupported.md
  locales/en/index.yml
  locales/it/cie/cieNotSupported.md
  locales/it/index.yml
  ts/components/cie/CieNotSupported.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/components/CloseButton.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/routes.ts
  ts/screens/authentication/LandingScreen.tsx
Labels: IO-A&I

#5652 feat: [IOPID-1611] Add en copy on modal cie not supported
  locales/en/index.yml
Labels: IO-A&I
