Repository pagopa/io-app, pull requests merged in 2024-04, with the labels that each got.

#5621 feat: [IOCOM-882] New DS on a paid payment screen for a cancelled PN message
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/screens/LegacyPaidPaymentScreen.tsx
  ts/features/pn/screens/PaidPaymentScreen.tsx
  ts/features/pn/screens/__test__/LegacyPaidPaymentScreen.test.tsx
  ts/features/pn/screens/__test__/PaidPaymentScreen.test.tsx
  ts/features/pn/screens/__test__/__snapshots__/LegacyPaidPaymentScreen.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
Labels: IO-Comunicazione

#5643 feat: [IOCOM-873] IUN code on SEND message details with new DS
  locales/en/index.yml
  locales/it/index.yml
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageInfo.tsx
  ts/features/pn/components/__test__/MessageInfo.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageInfo.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
Labels: IO-Comunicazione

#5633 chore: [IOPAE-1046] Add Service header to `ServiceDetailsScreen`
  ts/features/services/components/ServiceDetailsHeader.tsx
  ts/features/services/components/__tests__/ServiceDetailsHeader.test.tsx
  ts/features/services/components/__tests__/__snapshots__/ServiceDetailsHeader.test.tsx.snap
  ts/features/services/screens/ServiceDetailsScreen.tsx
Labels: Redesign Servizi

#5656 chore: [IOBP-607] Fix payments landing screen scrollview behavior
  ts/features/payments/home/components/PaymentsHomeListItemTransaction.tsx
  ts/features/payments/home/components/PaymentsHomeScreenHistorySection.tsx
  ts/features/payments/home/components/PaymentsHomeTransactionList.tsx
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/features/payments/home/store/selectors.ts
  ts/features/payments/home/utils/hooks/useTransactionHistory.ts
  ts/features/payments/home/utils/paymentsHomeScreenHistoryGenerator.tsx
Labels: IO-Bonus e pagamenti

#5642 chore: [IOPAE-1066] Service details failure state
  locales/en/index.yml
  locales/it/index.yml
  ts/features/services/components/ServiceDetailsFailure.tsx
  ts/features/services/screens/ServiceDetailsScreen.tsx
Labels: Redesign Servizi

#5660 fix: [IOPID-1714] IOS crashes on EIC malformed URLs
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/LoadingSpinnerOverlay.tsx
  ts/screens/authentication/cie/CieCardReaderScreen.tsx
  yarn.lock
Labels: IO-A&I

#5639 chore(IT Wallet): [SIW-951] Add user payment methods in new wallet section
  img/features/cgn/cgn_card.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/wallet/components/IdPayCard.tsx
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/store/selectors/index.ts
  ts/features/newWallet/types/index.ts
  ts/features/payments/checkout/components/WalletPaymentConfirmContent.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/store/__tests__/store.test.ts
  ts/features/payments/checkout/store/selectors/index.ts
  ts/features/payments/common/components/PaymentCard.tsx
  ts/features/payments/common/components/__tests__/PaymentCard.test.tsx
  ts/features/payments/common/components/__tests__/PaymentCardBig.test.tsx
  ts/features/payments/common/components/__tests__/PaymentCardSmall.test.tsx
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCard.test.tsx.snap
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardBig.test.tsx.snap
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardSmall.test.tsx.snap
  ts/features/payments/common/saga/index.ts
  ts/features/payments/common/store/actions/index.ts
  ts/features/payments/common/store/reducers/index.ts
  ts/features/payments/common/types/UIWalletInfoDetails.ts
  ts/features/payments/common/utils/index.ts
  ts/features/payments/details/screens/PaymentsMethodDetailsScreen.tsx
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
  ts/features/payments/wallet/components/PaymentWalletCard.tsx
  ts/features/payments/wallet/saga/__tests__/handleGetPaymentsWalletUserMethods.test.ts
  ts/features/payments/wallet/saga/handleGetPaymentsWalletUserMethods.ts
  ts/features/payments/wallet/saga/index.ts
  ts/features/payments/wallet/store/actions/index.ts
  ts/features/payments/wallet/store/reducers/index.ts
Labels: IT Wallet

#5636 feat: [IOCOM-1199] Vertically ordered CTAs and Payment button on new DS message details screen
  ts/components/cta/CTAsBar.tsx
  ts/components/cta/ExtractedCTABar.tsx
  ts/components/cta/__test__/CTAsBar.test.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsPaymentButton.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsScrollViewAdditionalSpace.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsStickyFooter.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsPaymentButton.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsScrollViewAdditionalSpace.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsStickyFooter.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsPaymentButton.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsScrollViewAdditionalSpace.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsStickyFooter.test.tsx.snap
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/utils/index.ts
  ts/features/pn/hooks/usePNOptInMessage.ts
  ts/features/pn/utils/__tests__/index.test.ts
  ts/features/pn/utils/index.ts
Labels: IO-Comunicazione

#5666 chore: [IOPID-1720] Add features to OperationResultScreenContent
  ts/components/screens/OperationResultScreenContent.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/design-system/core/DSScreenOperationResult.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
Labels: Design System, IO-A&I

#5665 chore: [IOBP-615] Add new `paymentCard` component to `PaymentsMethodDetailsScreen`
  ts/features/payments/common/components/PaymentCard.tsx
  ts/features/payments/common/components/PaymentCardBig.tsx
  ts/features/payments/details/components/PaymentsMethodDetailsBaseScreenComponent.tsx
  ts/features/payments/details/components/PaymentsMethodDetailsDeleteButton.tsx
  ts/features/payments/details/components/PaymentsMethodDetailsErrorContent.tsx
  ts/features/payments/details/components/WalletDetailsPaymentMethodInitiatives.tsx
  ts/features/payments/details/components/WalletDetailsPaymentMethodScreen.tsx
  ts/features/payments/details/navigation/navigator.tsx
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/payments/details/screens/PaymentsMethodDetailsScreen.tsx
  ts/features/payments/details/store/reducers/index.ts
  ts/features/payments/wallet/saga/__tests__/handleGetPaymentsWalletUserMethods.test.ts
  ts/features/payments/wallet/saga/handleGetPaymentsWalletUserMethods.ts
  ts/utils/dates.ts
Labels: IO-Bonus e pagamenti

#5648 chore(IT Wallet): [SIW-963] Add wallet cards onboarding screen
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/bonus/cgn/saga/orchestration/activation/activationSaga.ts
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/OrganizationHeader.test.tsx.snap
  ts/features/newWallet/components/WalletEmptyScreenContent.tsx
  ts/features/newWallet/components/__tests__/WalletEmptyScreenContent.test.tsx
  ts/features/newWallet/components/__tests__/__snapshots__/WalletEmptyScreenContent.test.tsx.snap
  ts/features/newWallet/navigation/index.tsx
  ts/features/newWallet/navigation/params.ts
  ts/features/newWallet/navigation/routes.ts
  ts/features/newWallet/screens/WalletCardOnboardingScreen.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/payments/onboarding/components/WalletOnboardingPaymentMethodsList.tsx
  ts/features/payments/onboarding/navigation/navigator.tsx
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
  ts/features/payments/onboarding/screens/PaymentsOnboardingSelectMethodScreen.tsx
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/features/services/components/__tests__/__snapshots__/ServiceDetailsHeader.test.tsx.snap
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  yarn.lock
Labels: IT Wallet

#5669 chore(IT Wallet): [SIW-998] Add new element added toast notification in new wallet screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/saga/orchestration/activation/activationSaga.ts
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/screens/__tests__/WalletHomeScreen.test.tsx
  ts/features/payments/common/utils/wallet.ts
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/payments/details/saga/handleGetWalletDetails.ts
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
  ts/features/payments/wallet/saga/handleGetPaymentsWalletUserMethods.ts
Labels: IT Wallet

#5657 chore(Cross): [IOAPPX-273] Fix UI regressions in the Developer section
  ts/features/design-system/core/DSLogos.tsx
  ts/screens/profile/DeveloperModeSection.tsx
Labels: Cross

#5658 chore: [IOPAE-1050] Add service preferences to `ServiceDetailsScreen`
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/ContactPreferencesToggles/__test__/ContactPreferencesToggles.test.tsx
  ts/components/services/ContactPreferencesToggles/index.tsx
  ts/components/services/LocalServicesWebView.tsx
  ts/features/bonus/cgn/components/CgnServiceCTA.tsx
  ts/features/bonus/common/store/selectors/index.ts
  ts/features/fci/hooks/useFciCheckService.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsFooter.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/messages/saga/handleLoadMessageData.ts
  ts/features/messages/screens/LegacyMessageDetailScreen.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/ServiceCTA.tsx
  ts/features/pn/screens/LegacyMessageDetailsScreen.tsx
  ts/features/pn/store/reducers/activation.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/services/common/hooks/useFirstEffect.ts
  ts/features/services/components/ServiceDetailsHeader.tsx
  ts/features/services/components/ServiceDetailsPreferences.tsx
  ts/features/services/components/__tests__/__snapshots__/ServiceDetailsHeader.test.tsx.snap
  ts/features/services/saga/handleGetServicePreference.ts
  ts/features/services/saga/handleUpsertServicePreference.ts
  ts/features/services/screens/ServiceDetailsScreen.tsx
  ts/features/services/store/actions/index.ts
  ts/features/services/store/reducers/__tests__/servicePreference.test.ts
  ts/features/services/store/reducers/__tests__/servicesById.test.ts
  ts/features/services/store/reducers/servicePreference.ts
  ts/features/services/store/reducers/servicesById.ts
  ts/features/services/types/ServicePreferenceResponse.ts
  ts/sagas/services/__tests__/refreshStoredServices.test.ts
  ts/sagas/services/refreshStoredServices.ts
  ts/sagas/services/removeUnusedStoredServices.ts
  ts/sagas/services/watchLoadServicesSaga.ts
  ts/screens/services/LegacyServiceDetailsScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
  ts/screens/services/ServicesWebviewScreen.tsx
  ts/store/actions/services/index.ts
  ts/store/middlewares/serviceAnalytics.ts
  ts/store/reducers/entities/services/__tests__/index.test.ts
  ts/store/reducers/entities/services/__tests__/servicePreference.test.ts
  ts/store/reducers/entities/services/__tests__/servicesById.test.ts
  ts/store/reducers/entities/services/index.ts
  ts/store/reducers/entities/services/servicePreference.ts
Labels: Redesign Servizi

#5671 chore: [IOPID-1721] Delete header on email validation and validation success screen
  ts/navigation/OnboardingNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/screens/profile/EmailValidationSendEmailScreen.tsx
Labels: IO-A&I

#5670 feat: [IOPID-1569] Add new DS to EmailAlreadyTakenScreen
  locales/de/index.yml
  locales/it/index.yml
  ts/components/screens/OperationResultScreenContent.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
  ts/navigation/CheckEmailNavigator.tsx
  ts/screens/profile/mailCheck/EmailAlreadyTakenScreen.tsx
Labels: IO-A&I

#5675 chore: [IOBP-614] Temporarily remove thank you page feedback banner
  ts/features/payments/checkout/components/WalletPaymentFeedbackBanner.tsx
Labels: IO-Bonus e pagamenti

#5659 chore: [IOBP-611] Fix navigation on payment success
  ts/features/payments/barcode/screens/PaymentsBarcodeChoiceScreen.tsx
  ts/features/payments/barcode/screens/PaymentsBarcodeScanScreen.tsx
  ts/features/payments/checkout/hooks/usePagoPaPayment.ts
  ts/features/payments/checkout/hooks/useWalletPaymentGoBackHandler.tsx
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentInputFiscalCodeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentMakeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/checkout/store/actions/orchestration.ts
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/store/selectors/index.ts
  ts/features/payments/checkout/types/index.ts
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
Labels: IO-Bonus e pagamenti

#5424 chore(Cross): [IOAPPX-217] Add `NativeStackNavigator` to the Design System section
  ios/Podfile.lock
  package.json
  ts/components/DebugInfoOverlay.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/core/DSNumberPad.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/fci/components/__tests__/__snapshots__/QtspClauseListItem.test.tsx.snap
  ts/features/fci/hooks/useFciNoSignatureFields.tsx
  ts/features/fci/navigation/FciStackNavigator.tsx
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/CtaBar.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsAttachmentItem.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsAttachments.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsFooter.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsPayment.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsPaymentButton.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminder.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpired.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpiring.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsScrollViewAdditionalSpace.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsStickyFooter.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessagePaymentItem.test.tsx.snap
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/messages/screens/LegacyMessageDetailScreen.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
  ts/features/newWallet/components/__tests__/__snapshots__/WalletEmptyScreenContent.test.tsx.snap
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardBig.test.tsx.snap
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardSmall.test.tsx.snap
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/__test__/__snapshots__/F24ListBottomSheetLink.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/F24Section.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/LegacyMessageF24.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/LegacyMessageFooter.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/LegacyMessagePayments.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageFooter.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageInfo.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessagePayments.test.tsx.snap
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/screens/__test__/__snapshots__/LegacyPaidPaymentScreen.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PayPalOnboardingCompletedSuccessComponent.test.tsx.snap
  ts/sagas/startup/__tests__/checkProfileEmailSaga.test.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  yarn.lock
Labels: keep open, Design System, Cross

#5534 fix(Cross): [IOAPPX-253] Wrong Danger messages in case of error
  scripts/ts/common/jiraTicket/index.ts
Labels: Cross

#5673 feat: [IOPID-1568] Integrate new DS on email validation block screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/navigation/CheckEmailNavigator.tsx
  ts/screens/profile/mailCheck/ValidateEmailScreen.tsx
Labels: IO-A&I

#5682 chore(IT Wallet): [SIW-1011] Add test toggle in user profile screen with playground entry
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IT Wallet

#5662 chore(Cross): [IOAPPX-277] Update check_urls script blacklist
  scripts/check_urls/check_urls.py
Labels: Cross

#5672 chore(IT Wallet): [SIW-999] Add category filter tabs to the new wallet screen
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/newWallet/components/WalletCardBaseComponent.tsx
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/components/WalletCategoryFilterTabs.tsx
  ts/features/newWallet/components/__tests__/WalletCardsCategoryContainer.test.tsx
  ts/features/newWallet/components/__tests__/WalletCardsContainer.test.tsx
  ts/features/newWallet/components/__tests__/WalletCategoryFilterTabs.test.tsx
  ts/features/newWallet/components/__tests__/WalletEmptyScreenContent.test.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/screens/__tests__/WalletHomeScreen.test.tsx
  ts/features/newWallet/store/actions/preferences.ts
  ts/features/newWallet/store/reducers/preferences.ts
  ts/features/newWallet/store/selectors/index.ts
  ts/features/newWallet/utils/index.tsx
  yarn.lock
Labels: IT Wallet

#5677 chore: [IOPAE-1048,IOPAE-1049,IOPAE-1051] Adopt the new DS on `ServiceDetailsScreen`
  locales/en/index.yml
  locales/it/index.yml
  ts/components/services/SpecialServices/LegacySpecialServicesCTA.tsx
  ts/features/bonus/cgn/__e2e__/utils.ts
  ts/features/bonus/cgn/components/CgnServiceCTA.tsx
  ts/features/bonus/cgn/components/LegacyCgnServiceCTA.tsx
  ts/features/bonus/cgn/components/detail/CgnUnsubscribe.tsx
  ts/features/pn/components/LegacyServiceCTA.tsx
  ts/features/pn/components/ServiceCTA.tsx
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/reducers/activation.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/services/components/ServiceDetailsMetadata.tsx
  ts/features/services/components/ServiceDetailsPreferences.tsx
  ts/features/services/components/ServiceDetailsScreenComponent.tsx
  ts/features/services/components/ServiceDetailsTosAndPrivacy.tsx
  ts/features/services/components/ServiceSpecialAction.tsx
  ts/features/services/screens/ServiceDetailsScreen.tsx
  ts/features/services/store/reducers/servicePreference.ts
  ts/features/services/store/reducers/servicesById.ts
  ts/features/services/types/ServiceMetadataInfo.ts
  ts/screens/services/LegacyServiceDetailsScreen.tsx
Labels: Redesign Servizi

#5663 [IOBP-563, IOBP-612] Add empty states and navigation events to `PaymentsHomeScreen`
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/configureStoreAndPersistor.ts
  ts/components/ui/utils/generateFlatListItemLayout.ts
  ts/features/design-system/core/DSCards.tsx
  ts/features/payments/common/components/PaymentCardPressableBase.tsx
  ts/features/payments/common/components/PaymentCardSmall.tsx
  ts/features/payments/common/components/PaymentCardsCarousel.tsx
  ts/features/payments/common/components/__tests__/PaymentCardSmall.test.tsx
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardSmall.test.tsx.snap
  ts/features/payments/common/store/actions/index.ts
  ts/features/payments/common/store/reducers/index.ts
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/payments/details/store/actions/index.ts
  ts/features/payments/home/components/PaymentsCardsCarousel.tsx
  ts/features/payments/home/components/PaymentsHomeEmptyScreenContent.tsx
  ts/features/payments/home/components/PaymentsHomeTransactionList.tsx
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
  ts/features/payments/home/components/PaymentsListItemTransaction.tsx
  ts/features/payments/home/components/__tests__/PaymentCardsCarousel.test.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/features/payments/home/screens/__tests__/PaymentsHomeScreen.test.tsx
  ts/features/payments/home/store/actions/index.ts
  ts/features/payments/home/store/reducers/index.ts
  ts/features/payments/home/store/selectors/index.ts
  ts/features/payments/wallet/components/PaymentWalletCard.tsx
  ts/features/payments/wallet/store/reducers/index.ts
  ts/features/payments/wallet/store/selectors/index.ts
  ts/navigation/components/HeaderFirstLevelHandler.tsx
Labels: IO-Bonus e pagamenti

#5683 chore(IT Wallet): [SIW-1012] Add playground screen for IT-Wallet flows
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/playgrounds/ItwPlayground.tsx
Labels: IT Wallet

#5667 chore: [IOBP-616] Add missing parameters to payment's `calculateFees` request payload
  package.json
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/wallet/saga/__tests__/handleGetPaymentsWalletUserMethods.test.ts
Labels: IO-Bonus e pagamenti

#5687 revert(Cross): [IOAPPX-217] Add NativeStackNavigator to the Design System section
  ios/Podfile.lock
  package.json
  ts/components/DebugInfoOverlay.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/core/DSNumberPad.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/fci/components/__tests__/__snapshots__/QtspClauseListItem.test.tsx.snap
  ts/features/fci/hooks/useFciNoSignatureFields.tsx
  ts/features/fci/navigation/FciStackNavigator.tsx
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/CtaBar.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsAttachmentItem.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsAttachments.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsFooter.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsPayment.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsPaymentButton.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminder.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpired.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpiring.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsScrollViewAdditionalSpace.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsStickyFooter.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessagePaymentItem.test.tsx.snap
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/messages/screens/LegacyMessageDetailScreen.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
  ts/features/newWallet/components/__tests__/__snapshots__/WalletEmptyScreenContent.test.tsx.snap
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardBig.test.tsx.snap
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardSmall.test.tsx.snap
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/__test__/__snapshots__/F24ListBottomSheetLink.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/F24Section.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/LegacyMessageF24.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/LegacyMessageFooter.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/LegacyMessagePayments.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageFooter.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageInfo.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessagePayments.test.tsx.snap
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/screens/__test__/__snapshots__/LegacyPaidPaymentScreen.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
  ts/features/wallet/onboarding/paypal/screen/__tests__/__snapshots__/PayPalOnboardingCompletedSuccessComponent.test.tsx.snap
  ts/sagas/startup/__tests__/checkProfileEmailSaga.test.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  yarn.lock
Labels: Cross

#5691 chore(Cross): [IOAPPX-282] Move Mixpanel URL into env file
  .env.local
  .env.production
  ts/config.ts
  ts/mixpanel.ts
Labels: Cross

#5676 chore: [IOPID-1502], [IOPID-1459] New DS on idp selection page
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/api/content.ts
  ts/components/IdpsGrid.tsx
  ts/components/IdpsGridRevamp.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/screens/authentication/IdpSelectionScreen.tsx
  ts/store/reducers/content.ts
Labels: IO-A&I

#5692 chore: [IOBP-627] Remove Payments playgrounds
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/playgrounds/WalletPaymentPlayground.tsx
  ts/screens/profile/playgrounds/WalletPlayground.tsx
Labels: IO-Bonus e pagamenti

#5685 chore(Cross): [IOAPPX-286] Fix wrong typographic style in the `IdentificationModal` screen + Fix wrong StatusBar style in iOS
  ts/screens/modal/IdentificationModal.tsx
  ts/screens/modal/components/IdentificationNumberPad.tsx
  ts/utils/identification/index.tsx
Labels: Cross

#5680 chore: [IOBP-620] Add `ONBOARDABLE` filter to onboarding payment methods
  package.json
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentGetUserWallets.test.ts
  ts/features/payments/common/utils/wallet.ts
  ts/features/payments/onboarding/screens/PaymentsOnboardingSelectMethodScreen.tsx
  ts/features/payments/onboarding/store/reducers/index.ts
  ts/features/payments/onboarding/store/selectors/index.ts
  ts/features/payments/wallet/saga/__tests__/handleGetPaymentsWalletUserMethods.test.ts
Labels: IO-Bonus e pagamenti

#5688 chore(IT Wallet): [SIW-1010] Add component to translate markdown into react node
  package.json
  ts/features/itwallet/components/ItwMarkdown.tsx
  ts/screens/profile/playgrounds/ItwPlayground.tsx
  yarn.lock
Labels: IT Wallet

#5679 chore(Cross): [IOAPPX-278] Add privacy manifest for iOS
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/PrivacyInfo.xcprivacy
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/utils/__tests__/string.test.ts
  ts/utils/device.ts
  ts/utils/strings.ts
Labels: dont-merge :raised_hand:, legal-review-needed ⚖️ ⛔, Cross

#5661 feat: [IOCOM-878] SEND payments bottom sheet with new DS
  ts/features/pn/components/LegacyMessagePayments.tsx
  ts/features/pn/components/MessageBottomMenu.tsx
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessagePaymentBottomSheet.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/components/__test__/MessageBottomMenu.test.tsx
  ts/features/pn/components/__test__/MessagePaymentBottomSheet.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageBottomMenu.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessagePaymentBottomSheet.test.tsx.snap
  ts/features/pn/utils/__tests__/index.test.ts
  ts/features/pn/utils/index.ts
Labels: IO-Comunicazione

#5698 chore(IT Wallet): [SIW-1046] Persist wallet cards count by category
  ts/boot/configureStoreAndPersistor.ts
  ts/features/newWallet/store/__tests__/cards.test.ts
  ts/features/newWallet/store/__tests__/placeholders.test.ts
  ts/features/newWallet/store/reducers/index.ts
  ts/features/newWallet/store/reducers/placeholders.ts
  ts/features/newWallet/store/selectors/placeholders.ts
Labels: IT Wallet

#5681 chore: [IOBP-622] Update `PaymentCard` components
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSCards.tsx
  ts/features/design-system/core/DSWallet.tsx
  ts/features/newWallet/components/WalletCardBaseComponent.tsx
  ts/features/newWallet/components/__tests__/WalletCardBaseComponent.test.tsx
  ts/features/payments/common/components/PaymentCard.tsx
  ts/features/payments/common/components/PaymentCardSmall.tsx
  ts/features/payments/common/components/__tests__/PaymentCard.test.tsx
  ts/features/payments/common/components/__tests__/PaymentCardSmall.test.tsx
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCard.test.tsx.snap
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardSmall.test.tsx.snap
  ts/features/payments/common/utils/__tests__/index.test.ts
  ts/features/payments/common/utils/index.ts
  ts/features/payments/common/utils/wallet.ts
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/payments/details/saga/handleGetWalletDetails.ts
  ts/features/payments/details/screens/PaymentsMethodDetailsScreen.tsx
  ts/features/payments/home/components/__tests__/PaymentCardsCarousel.test.tsx
  ts/features/payments/wallet/saga/__tests__/handleGetPaymentsWalletUserMethods.test.ts
  ts/features/payments/wallet/saga/handleGetPaymentsWalletUserMethods.ts
Labels: IO-Bonus e pagamenti

#5694 chore: [IOBP-564] Update payment's validation failure mapping
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/types/WalletPaymentFailure.ts
Labels: IO-Bonus e pagamenti

#5695 feat: [IOCOM-1207] Payment data on the "More info" bottom sheet
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/MessageDetail/MessageDetailsFooter.tsx
  ts/features/messages/components/MessageDetail/MessagePaymentItem.tsx
  ts/features/messages/components/MessageDetail/ShowMoreListItem.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsFooter.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/ShowMoreListItem.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsFooter.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/ShowMoreListItem.test.tsx.snap
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/payments/checkout/hooks/usePaymentFailureSupportModal.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/common/utils/__test__/index.test.ts
  ts/features/payments/common/utils/index.ts
  ts/features/pn/screens/LegacyPaidPaymentScreen.tsx
  ts/screens/wallet/payment/components/TransactionSummary.tsx
Labels: IO-Comunicazione

#5700 feat: [IOCOM-877] More Info on SEND message
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/MessageDetail/MessageDetailsFooter.tsx
  ts/features/messages/components/MessageDetail/ShowMoreListItem.tsx
  ts/features/messages/components/MessageDetail/__tests__/ShowMoreListItem.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/ShowMoreListItem.test.tsx.snap
  ts/features/pn/components/MessageBottomMenu.tsx
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/__test__/MessageBottomMenu.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageBottomMenu.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
Labels: IO-Comunicazione

#5697 feat: [IOPID-1537] Integrate new DS on Unsupported Device Screen
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/lollipop/screens/UnsupportedDeviceScreen.tsx
Labels: IO-A&I

#5686 chore: [IOBP-625] Add guest payment flow to the new wallet section
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/payments/barcode/screens/PaymentsBarcodeScanScreen.tsx
  ts/features/payments/checkout/components/CheckoutPaymentMethodsList.tsx
  ts/features/payments/checkout/components/WalletPaymentConfirmContent.tsx
  ts/features/payments/checkout/components/WalletPaymentHeader.tsx
  ts/features/payments/checkout/components/WalletPaymentMissingMethodsError.tsx
  ts/features/payments/checkout/hooks/useOnTransactionActivationEffect.tsx
  ts/features/payments/checkout/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/payments/checkout/hooks/useWalletPaymentGoBackHandler.tsx
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentAuthorization.test.ts
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentCalculateFees.test.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentAuthorization.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/checkout/store/__tests__/store.test.ts
  ts/features/payments/checkout/store/actions/networking.ts
  ts/features/payments/checkout/store/actions/orchestration.ts
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/store/selectors/index.ts
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
  ts/features/payments/checkout/store/selectors/psps.ts
  ts/features/payments/checkout/store/selectors/transaction.ts
  ts/features/payments/common/utils/index.ts
  ts/features/payments/history/store/actions/index.ts
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
  ts/features/pn/components/__test__/__snapshots__/MessagePaymentBottomSheet.test.tsx.snap
  yarn.lock
Labels: IO-Bonus e pagamenti

#5712 chore(Cross): [IOAPPX-287] Improve current visual hierarchy in the `MessageMarkdown` component
  ts/features/messages/components/MessageDetail/MessageMarkdown.tsx
  ts/screens/profile/playgrounds/MarkdownPlayground.tsx
Labels: Design System, Cross

#5701 chore: [IOPAE-1098] Add reducer and selectors for the list of institutions in the services section
  package.json
  ts/features/common/store/reducers/index.ts
  ts/features/services/common/store/actions/index.ts
  ts/features/services/common/store/reducers/index.ts
  ts/features/services/home/store/actions/index.ts
  ts/features/services/home/store/reducers/__tests__/store.test.ts
  ts/features/services/home/store/reducers/index.ts
Labels: IO - Enti & Servizi

#5702 chore: [IOPAE-1090] Add `handleFindInstitutions` saga
  ts/features/services/common/api/__mocks__/client.ts
  ts/features/services/common/api/client.ts
  ts/features/services/common/saga/index.ts
  ts/features/services/home/saga/__tests__/handleFindInstitutions.test.ts
  ts/features/services/home/saga/handleFindInstitutions.ts
  ts/features/services/home/saga/index.ts
  ts/features/services/home/store/actions/index.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: IO - Enti & Servizi

#5709 chore: [IOPAE-1091] Add the new list of national institutions
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/services/home/components/InstitutionListItemSkeleton.tsx
  ts/features/services/home/components/ServicesHomeIntitutionList.tsx
  ts/features/services/home/hooks/useInstitutionsFetcher.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/home/store/reducers/__tests__/store.test.ts
  ts/features/services/home/store/reducers/index.ts
  ts/features/services/home/utils/index.ts
  ts/navigation/TabNavigator.tsx
  yarn.lock
Labels: IO - Enti & Servizi

#5703 feat: [IOPID-1538] Integrate new DS in SystemOffModal and update it to functional component
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/modal/SystemOffModal.tsx
  ts/store/reducers/backendStatus.ts
Labels: IO-A&I

#5706 feat: [IOCOM-875] SEND Timeline with new DS
  locales/en/index.yml
  locales/it/index.yml
  ts/features/pn/components/MessageBottomMenu.tsx
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/Timeline.tsx
  ts/features/pn/components/TimelineListItem.tsx
  ts/features/pn/components/__test__/MessageBottomMenu.test.tsx
  ts/features/pn/components/__test__/Timeline.test.tsx
  ts/features/pn/components/__test__/TimelineListItem.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageBottomMenu.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/Timeline.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/TimelineListItem.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/features/pn/utils/__tests__/index.test.ts
  ts/features/pn/utils/index.ts
Labels: IO-Comunicazione

#5717 chore: [IOBP-630] Changed label from CheckoutPaymentMethodList
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#5696 chore(IT Wallet): [SIW-1018] Add discovery info activation screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/FooterStackButton.tsx
  ts/features/itwallet/discovery/components/ItwMarkdown.tsx
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/discovery/screens/__tests__/ItwDiscoveryInfoScreen.test.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/screens/profile/playgrounds/ItwPlayground.tsx
Labels: IT Wallet

#5718 fix: restore `backendStatus` previous selector
  ts/screens/modal/SystemOffModal.tsx
  ts/store/reducers/backendStatus.ts
Labels: IO-A&I

#5720 fix: [IOPAE-1125] Wrong margins in `ServiceDetailsScreen`
  ts/features/services/details/components/ServiceDetailsMetadata.tsx
  ts/features/services/details/components/ServiceDetailsPreferences.tsx
  ts/features/services/details/components/ServiceDetailsTosAndPrivacy.tsx
  ts/features/services/details/screens/ServiceDetailsScreen.tsx
Labels: IO - Enti & Servizi

#5716 chore: [IOBP-591] Removed 401 failure handlers to the payments requests features
  ts/features/payments/checkout/saga/networking/handleWalletPaymentAuthorization.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentDeleteTransaction.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetTransactionInfo.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentNewSessionToken.ts
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/payments/details/saga/handleGetWalletDetails.ts
  ts/features/payments/onboarding/saga/handleGetPaymentMethods.ts
  ts/features/payments/onboarding/saga/handleStartWalletOnboarding.ts
  ts/features/payments/wallet/saga/handleGetPaymentsWalletUserMethods.ts
Labels: IO-Bonus e pagamenti

#5723 chore: [IOBP-586] Replaced `LoadingSpinner` with `LoadingIndicator` into payments folder
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
Labels: IO-Bonus e pagamenti

#5705 feat: [IOPID-1503] Adopt the new DS on `CiePinScreen`
  locales/de/bottomsheets/ciePin.md
  locales/en/bottomsheets/ciePin.md
  locales/it/bottomsheets/ciePin.md
  locales/it/index.yml
  package.json
  ts/components/CiePinpad/index.tsx
  ts/features/cieLogin/components/screens/CieLoginConfigScreen.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  yarn.lock
Labels: IO-A&I

#5713 chore(IT Wallet): [SIW-1056] Add wallet placeholders timeout
  ts/features/newWallet/saga/__tests__/handleWalletLoadingPlaceholdersTimeout.test.ts
  ts/features/newWallet/saga/__tests__/handleWalletLoadingStateSaga.test.ts
  ts/features/newWallet/saga/handleWalletLoadingPlaceholdersTimeout.ts
  ts/features/newWallet/saga/handleWalletLoadingStateSaga.ts
  ts/features/newWallet/saga/index.ts
  ts/features/newWallet/store/actions/placeholders.ts
  ts/features/newWallet/store/reducers/placeholders.ts
Labels: IT Wallet

#5725 chore: [IOBP-588] Add radio group into PSP sorting bottom sheet
  ts/features/payments/checkout/hooks/useSortPspBottomSheet.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
Labels: IO-Bonus e pagamenti

#5620 chore: [PE-563] Apply new DS to CgnActivationLoading screen
  ts/features/bonus/cgn/screens/activation/CgnActivationLoadingScreen.tsx
Labels: Carta Giovani Nazionale
