Repository pagopa/io-app, pull requests merged in 2024-12, with the labels that each got.

#6475 chore(Cross): [IOAPPX-444] Remove legacy components from the DS
  ts/components/CopyButtonComponent.tsx
  ts/components/SectionStatus/StatusContent.tsx
  ts/components/SectionStatus/__tests__/SectionStatusContent.test.tsx
  ts/components/SectionStatus/__tests__/__snapshots__/SectionStatusContent.test.tsx.snap
  ts/components/core/IOBadge.tsx
  ts/components/screens/ListItemComponent.tsx
  ts/components/ui/CustomBadge.tsx
  ts/components/ui/TabIconComponent.tsx
  ts/components/ui/__test__/CustomBadge.test.tsx
  ts/components/ui/__test__/__snapshots__/CustomBadge.test.tsx.snap
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
  ts/features/bonus/cdc/components/__test__/CdcServiceCTA.test.ts
  ts/features/bonus/cgn/components/merchants/CgnDiscountValueBox.tsx
  ts/features/bonus/common/components/AvailableBonusItem.tsx
  ts/features/design-system/core/DSLegacyAlert.tsx
  ts/features/design-system/core/DSLegacyBadges.tsx
  ts/features/design-system/core/DSLegacyButtons.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/idpay/timeline/components/TimelineDiscountTransactionDetailsComponent.tsx
  ts/features/idpay/timeline/components/TimelineRefundDetailsComponent.tsx
  ts/features/idpay/timeline/components/TimelineTransactionDetailsComponent.tsx
Labels: Design System, 💀 Dead matter, Cross

#6469 fix: [PE-845] CGN Replace legacy error screen
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6465 chore: [IOBP-1028] Mixpanel tracking onboarding card methods events on failure
  ts/features/payments/onboarding/analytics/index.ts
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
Labels: IO-Bonus e pagamenti

#6484 fix: [IOBP-1037] Remove asterisks from card transaction info
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#6479 fix: [IOBP-961] Missing German key for FAQ
  package.json
  ts/features/zendesk/screens/__tests__/ZendeskAskPermissions.test.tsx
  ts/features/zendesk/screens/__tests__/ZendeskChooseCategory.test.tsx
  ts/features/zendesk/screens/__tests__/ZendeskChooseSubCategory.test.tsx
  ts/features/zendesk/store/reducers/__tests__/index.test.ts
  ts/store/reducers/content.ts
  ts/utils/__tests__/content.test.ts
  ts/utils/supportAssistance.ts
Labels: IO-Bonus e pagamenti

#6478 fix: [IOBP-1021] Show retry banner when all the other cards fetch fails
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/saga/__tests__/handleWalletLoadingPlaceholdersTimeout.test.ts
  ts/features/newWallet/saga/handleWalletLoadingPlaceholdersTimeout.ts
  ts/features/newWallet/screens/__tests__/WalletHomeScreen.test.tsx
Labels: IO-Bonus e pagamenti

#6470 chore: [PE-803] CGN discount outcome screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/cgn/navigation/params.ts
  ts/features/bonus/cgn/navigation/routes.ts
  ts/features/bonus/cgn/screens/discount/CGNDiscountExpiredScreen.tsx
  ts/features/bonus/cgn/screens/discount/CgnDiscountCodeScreen.tsx
  ts/features/bonus/cgn/screens/discount/CgnDiscountDetailScreen.tsx
  ts/features/bonus/cgn/screens/discount/___tests___/CGNDiscountExpiredScreen.test.tsx
  ts/features/bonus/cgn/screens/discount/___tests___/CgnDiscountCodeScreen.test.tsx
  ts/features/bonus/cgn/screens/discount/___tests___/CgnDiscountDetailScreen.test.tsx
  ts/features/bonus/cgn/screens/discount/___tests___/__snapshots__/CGNDiscountExpiredScreen.test.tsx.snap
  ts/features/bonus/cgn/screens/discount/___tests___/__snapshots__/CgnDiscountCodeScreen.test.tsx.snap
  ts/features/bonus/cgn/screens/discount/___tests___/__snapshots__/CgnDiscountDetailScreen.test.tsx.snap
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6485 chore: [IOBP-1040] Update the latest receipt list everytime the user closes the success outcome
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/___tests___/WalletPaymentOutcomeScreen.test.tsx
  ts/features/payments/checkout/screens/___tests___/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
Labels: IO-Bonus e pagamenti

#6490 chore(IT Wallet): [SIW-1889] Rename `newWallet` feature to `wallet`
  ts/features/bonus/cgn/components/CgnWalletCard.tsx
  ts/features/bonus/cgn/saga/networking/details/getCgnInformationSaga.ts
  ts/features/bonus/cgn/saga/networking/unsubscribe/index.ts
  ts/features/common/store/reducers/index.ts
  ts/features/design-system/core/DSWallet.tsx
  ts/features/idpay/wallet/components/IdPayWalletCard.tsx
  ts/features/idpay/wallet/saga/__test__/handleGetWallet.test.ts
  ts/features/idpay/wallet/saga/handleGetWallet.ts
  ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
  ts/features/itwallet/credentials/saga/handleItwCredentialsRemoveSaga.ts
  ts/features/itwallet/credentials/saga/handleItwCredentialsStoreSaga.ts
  ts/features/itwallet/credentials/saga/handleWalletCredentialsRehydration.ts
  ts/features/itwallet/lifecycle/saga/handleWalletInstanceResetSaga.ts
  ts/features/itwallet/wallet/components/ItwCredentialWalletCard.tsx
  ts/features/payments/common/components/PaymentCardSmall.tsx
  ts/features/payments/common/utils/index.ts
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/payments/details/saga/handleGetWalletDetails.ts
  ts/features/payments/wallet/components/PaymentWalletCard.tsx
  ts/features/payments/wallet/saga/__tests__/handleGetPaymentsWalletUserMethods.test.ts
  ts/features/payments/wallet/saga/handleGetPaymentsWalletUserMethods.ts
  ts/features/wallet/components/WalletCardBaseComponent.tsx
  ts/features/wallet/components/WalletCardPressableBase.tsx
  ts/features/wallet/components/WalletCardSkeleton.tsx
  ts/features/wallet/components/WalletCardsCategoryContainer.tsx
  ts/features/wallet/components/WalletCardsCategoryRetryErrorBanner.tsx
  ts/features/wallet/components/WalletCardsContainer.tsx
  ts/features/wallet/components/WalletCategoryFilterTabs.tsx
  ts/features/wallet/components/WalletEmptyScreenContent.tsx
  ts/features/wallet/components/__tests__/WalletCardBaseComponent.test.tsx
  ts/features/wallet/components/__tests__/WalletCardsCategoryContainer.test.tsx
  ts/features/wallet/components/__tests__/WalletCardsContainer.test.tsx
  ts/features/wallet/components/__tests__/WalletCategoryFilterTabs.test.tsx
  ts/features/wallet/components/__tests__/WalletEmptyScreenContent.test.tsx
  ts/features/wallet/components/__tests__/__snapshots__/WalletEmptyScreenContent.test.tsx.snap
  ts/features/wallet/saga/__tests__/handleWalletLoadingPlaceholdersTimeout.test.ts
  ts/features/wallet/saga/__tests__/handleWalletLoadingStateSaga.test.ts
  ts/features/wallet/saga/handleWalletLoadingPlaceholdersTimeout.ts
  ts/features/wallet/saga/handleWalletLoadingStateSaga.ts
  ts/features/wallet/saga/index.ts
  ts/features/wallet/screens/WalletHomeScreen.tsx
  ts/features/wallet/screens/__tests__/WalletHomeScreen.test.tsx
  ts/features/wallet/store/__tests__/cards.test.ts
  ts/features/wallet/store/__tests__/placeholders.test.ts
  ts/features/wallet/store/actions/cards.ts
  ts/features/wallet/store/actions/index.ts
  ts/features/wallet/store/actions/placeholders.ts
  ts/features/wallet/store/actions/preferences.ts
  ts/features/wallet/store/reducers/cards.ts
  ts/features/wallet/store/reducers/index.ts
  ts/features/wallet/store/reducers/placeholders.ts
  ts/features/wallet/store/reducers/preferences.ts
  ts/features/wallet/store/selectors/index.ts
  ts/features/wallet/types/index.ts
  ts/features/wallet/utils/index.tsx
  ts/mixpanelConfig/mixpanelPropertyUtils.ts
  ts/navigation/TabNavigator.tsx
  ts/navigation/params/MainTabParamsList.ts
  ts/sagas/startup.ts
  ts/store/actions/types.ts
Labels: IT Wallet

#6483 chore: [IOPID-2538] Fix `LOGIN_CIEID_SELECTED` event delay
  ts/features/cie/analytics/index.ts
  ts/screens/authentication/analytics/index.ts
Labels: IO-A&I

#6474 feat(IT Wallet): [SIW-1789,SIW-1790] Always fetch the latest wallet instance status at app startup
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
Labels: IT Wallet

#6488 chore: [IOBP-1049] Edit insufficient availability error outcome title
  ios/ItaliaApp/Info.plist
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/screens/___tests___/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
Labels: IO-Bonus e pagamenti

#6487 chore(IT Wallet): [SIW-1848] Remove IT Wallet trial system
  .env.local
  .env.production
  ts/__mocks__/react-native-config.ts
  ts/components/SectionStatus/__tests__/index.test.tsx
  ts/config.ts
  ts/features/itwallet/common/components/ItwUpcomingWalletBanner.tsx
  ts/features/itwallet/common/components/__tests__/ItwUpcomingWalletBanner.test.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/ItwDiscoveryBanner.test.tsx
  ts/features/itwallet/common/saga/__tests__/index.test.ts
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/itwallet/navigation/useItwLinkingOptions.tsx
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/onboarding/screens/__tests__/WalletCardOnboardingScreen.test.tsx
  ts/features/itwallet/playgrounds/components/ItwTrialSystemSection.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/trialSystem/store/reducers/index.ts
  ts/features/wallet/components/WalletCardsContainer.tsx
  ts/features/wallet/components/__tests__/WalletCardsContainer.test.tsx
Labels: IT Wallet

#6489 fix: [IOBP-1038] Update default transaction header on different psp/fee cases
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionCartList.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionFeeAmountSection.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionLoadingList.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionTotalAmount.tsx
  ts/features/payments/bizEventsTransaction/components/___tests___/PaymentsBizEventsFilterTabs.test.tsx
  ts/features/payments/bizEventsTransaction/components/___tests___/PaymentsBizEventsTransactionCartList.test.tsx
  ts/features/payments/bizEventsTransaction/components/___tests___/PaymentsBizEventsTransactionFeeAmountSection.test.tsx
  ts/features/payments/bizEventsTransaction/components/___tests___/PaymentsBizEventsTransactionHeadingSection.test.tsx
  ts/features/payments/bizEventsTransaction/components/___tests___/PaymentsBizEventsTransactionInfoSection.test.tsx
  ts/features/payments/bizEventsTransaction/components/___tests___/PaymentsBizEventsTransactionLoadingList.test.tsx
  ts/features/payments/bizEventsTransaction/components/___tests___/PaymentsBizEventsTransactionTotalAmount.test.tsx
  ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#6491 fix(IT Wallet): [SIW-1734] Add "back to top" in the wallet home screen
  ts/features/wallet/screens/WalletHomeScreen.tsx
Labels: IT Wallet

#6481 fix: [IOCOM-1994,IOCOM-1995] Fix for back behaviours on FIMS Auth
  ts/features/fims/singleSignOn/components/FimsFullScreenErrors.tsx
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
Labels: IO-Comunicazione

#6497 chore: [IOCOM-2001] Revert label content for empty FIMS history
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Comunicazione

#6505 chore: [IOCOM-1949] FIMS `iossoapi` protocol
  ios/Podfile.lock
  package.json
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  yarn.lock
Labels: IO-Comunicazione

#6494 chore: [IOBP-1048] Delete transaction when interrupting a payment
  ts/features/payments/checkout/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/payments/checkout/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#6446 chore: [IOBP-1020] Using optimistic UI for remove payment method action
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/wallet/components/__tests__/WalletCardsContainer.test.tsx
  ts/features/wallet/store/__tests__/cards.test.ts
  ts/features/wallet/store/reducers/cards.ts
  ts/features/wallet/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#6310 chore(Cross): [IOAPPX-347] Remove react-native-text-input-mask build phase script on iOS
  ios/ItaliaApp.xcodeproj/project.pbxproj
Labels: Cross

#6493 chore(IT Wallet): [SIW-1878] Loader before SPID Login Webview
  ts/features/itwallet/identification/screens/spid/ItwSpidIdpLoginScreen.tsx
Labels: IT Wallet

#6506 chore(IT Wallet): [SIW-1807] Change privacy in ITWallet Discovery
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
Labels: IT Wallet

#6499 feat(IT Wallet): [SIW-1852] Hide discovery banner after close
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerStandalone.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/ItwDiscoveryBanner.test.tsx
  ts/features/itwallet/common/store/actions/preferences.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/wallet/components/WalletCardsContainer.tsx
Labels: IT Wallet

#6515 fix: [IOPID-2543] Add logic to merge data during zendesk polling
  ts/features/zendesk/saga/index.ts
  ts/sagas/startup/__tests__/watchCheckSessionSaga.test.ts
  ts/sagas/startup/watchCheckSessionSaga.ts
Labels: Bug 🐞, IO-A&I

#6514 chore: [IOBP-1044,IOBP-1054] Add missing outcome screen into payment onboarding
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/hooks/usePaymentFailureSupportModal.tsx
  ts/features/payments/onboarding/analytics/__tests__/index.test.ts
  ts/features/payments/onboarding/analytics/index.ts
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
  ts/features/payments/onboarding/screens/__tests__/PaymentsOnboardingFeedbackScreen.test.tsx
  ts/features/payments/onboarding/types/OnboardingOutcomeEnum.ts
Labels: IO-Bonus e pagamenti

#6517 fix(IT Wallet): [SIW-1899] Fix filter tabs padding within wallet home screen
  ts/features/wallet/components/WalletCategoryFilterTabs.tsx
Labels: IT Wallet

#6508 chore(IT Wallet): [SIW-1404] Move CIE/NFC logic to XState
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/identification/saga/__tests__/handleNfcEnabledSaga.test.ts
  ts/features/itwallet/identification/saga/handleCieSupportedSaga.ts
  ts/features/itwallet/identification/saga/handleNfcEnabledSaga.ts
  ts/features/itwallet/identification/saga/index.ts
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/__tests__/ItwIdentificationModeSelectionScreen.test.tsx
  ts/features/itwallet/identification/screens/cie/ItwCiePinScreen.tsx
  ts/features/itwallet/identification/store/actions/index.ts
  ts/features/itwallet/identification/store/reducers/index.ts
  ts/features/itwallet/identification/store/selectors/index.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/eid/selectors.ts
  ts/store/reducers/index.ts
Labels: IT Wallet

#6527 chore: [IOBP-1071] Payment onboarding bottom sheet text
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#6477 chore(Cross): [IOAPPX-445] Replace legacy `FooterWithButtons` with a mix of `FooterActions` and `FooterActionsInline`
  ts/components/FooterTopShadow.tsx
  ts/components/TosWebviewErrorComponent.tsx
  ts/components/__tests__/TosWebviewComponent.test.tsx
  ts/components/buttons/FooterStackButtons.tsx
  ts/components/error/WorkunitGenericFailure.tsx
  ts/components/screens/GenericErrorComponent.tsx
  ts/features/bonus/cdc/components/CdcRequirementsError.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestInformationTos.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectResidence.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectYear.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsFilters.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsTabsScreen.tsx
  ts/features/bonus/common/components/TosBonusComponent.tsx
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/fci/components/DocumentViewer.tsx
  ts/features/fci/components/DocumentWithSignature.tsx
  ts/features/fci/components/__tests__/DocumentWithSignature.test.tsx
  ts/features/fci/hooks/useFciCheckService.tsx
  ts/features/fci/hooks/useFciNoSignatureFields.tsx
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
  ts/features/fci/screens/valid/FciThankyouScreen.tsx
  ts/features/idpay/configuration/screens/IbanEnrollmentScreen.tsx
  ts/features/idpay/configuration/screens/IbanOnboardingScreen.tsx
  ts/features/idpay/configuration/screens/InitiativeConfigurationIntroScreen.tsx
  ts/features/idpay/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/onboarding/screens/BoolValuePrerequisitesScreen.tsx
  ts/features/idpay/onboarding/screens/CompletionScreen.tsx
  ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentCodeInputScreen.tsx
  ts/features/idpay/unsubscription/screens/UnsubscriptionConfirmationScreen.tsx
  ts/features/messages/components/MessageAttachment/MessageAttachment.tsx
  ts/features/messages/screens/MessageCalendarScreen.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/pushNotifications/screens/OnboardingNotificationsInfoScreenConsent.tsx
  ts/features/pushNotifications/screens/__tests__/__snapshots__/OnboardingNotificationsInfoScreenConsent.test.tsx.snap
  ts/screens/authentication/cie/CieAuthorizeDataUsageScreen.tsx
  ts/screens/profile/components/services/ManualConfigBottomSheet.tsx
Labels: Design System, 💀 Dead matter, Cross

#6531 chore: [PE-868] CGN Update cta when card is expired
  locales/de/index.yml
  locales/it/index.yml
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6516 feat(IT Wallet): [SIW-1900] Add feedback for deferred credentials issuance
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/actions/preferences.ts
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/events.ts
  ts/features/itwallet/machine/credential/failure.ts
  ts/features/itwallet/machine/credential/guards.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/onboarding/components/ItwOnboardingModuleCredential.tsx
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialStatusAlert.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialVerificationExpired.tsx
  yarn.lock
Labels: IT Wallet

#6534 fix(IT Wallet): [SIW-1913] Fix regression on font weight in skeumorphic cards
  ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimLabel.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
Labels: IT Wallet

#6511 fix(IT Wallet): [SIW-1827] Accessibility improvements
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/__mocks__/ts.json
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardClaim.tsx
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
  ts/features/itwallet/issuance/components/__tests__/__snapshots__/ItwCredentialPreviewClaimsList.test.tsx.snap
  ts/features/itwallet/presentation/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
Labels: IT Wallet

#6530 chore: [IOCOM-2018] FIMS authentication flow support for Internal Relying Party
  ts/features/fims/common/analytics/index.ts
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/fims/singleSignOn/saga/handleFIMSAcceptedConsents.ts
  ts/features/fims/singleSignOn/saga/handleFimsAbortOrCancel.ts
  ts/features/fims/singleSignOn/saga/handleFimsAuthorizationOrImplicitCodeFlow.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsResourcesDeallocation.ts
  ts/features/fims/singleSignOn/saga/index.ts
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/singleSignOn/store/actions/index.ts
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IO-Comunicazione

#6539 fix(IT Wallet): [SIW-1880] Change attestation key access policy
  ios/Podfile.lock
  package.json
  ts/features/itwallet/common/store/storages/itwSecureStorage.ts
  ts/features/itwallet/common/utils/itwIntegrityUtils.ts
  yarn.lock
Labels: IT Wallet

#6538 feat(IT Wallet): [SIW-1915] Add discovery banner in wallet onboarding screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerOnboarding.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/ItwDiscoveryBannerOnboarding.test.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerOnboarding.test.tsx.snap
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
Labels: IT Wallet

#6521 feat(IT Wallet): [SIW-1853] Ipatente routing with IT Wallet
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwCredentialNotFound.tsx
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/useItwLinkingOptions.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
Labels: IT Wallet

#6532 fix(IT Wallet): [SIW-1806] Fix state inconsistencies in wallet home screen
  ts/features/itwallet/common/components/ItwEidLifecycleAlert.tsx
  ts/features/itwallet/common/components/ItwWalletReadyBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerStandalone.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/ItwDiscoveryBannerStandalone.test.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/wallet/components/WalletCardsCategoryRetryErrorBanner.tsx
  ts/features/wallet/components/WalletCardsContainer.tsx
  ts/features/wallet/components/WalletCategoryFilterTabs.tsx
  ts/features/wallet/components/__tests__/WalletCardsCategoryRetryErrorBanner.test.tsx
  ts/features/wallet/components/__tests__/WalletCardsContainer.test.tsx
  ts/features/wallet/components/__tests__/WalletCategoryFilterTabs.test.tsx
  ts/features/wallet/screens/WalletHomeScreen.tsx
  ts/features/wallet/store/__tests__/cards.test.ts
  ts/features/wallet/store/__tests__/placeholders.test.ts
  ts/features/wallet/store/actions/cards.ts
  ts/features/wallet/store/reducers/__tests__/cards.test.ts
  ts/features/wallet/store/reducers/__tests__/placeholders.test.ts
  ts/features/wallet/store/reducers/__tests__/preferences.test.ts
  ts/features/wallet/store/reducers/cards.ts
  ts/features/wallet/store/reducers/placeholders.ts
  ts/features/wallet/store/selectors/__tests__/index.test.ts
  ts/features/wallet/store/selectors/index.ts
  ts/features/wallet/types/index.ts
Labels: IT Wallet

#6526 fix: [IOPID-2169] Fix toast messages behavior in the `PrivacyMainScreen`
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/PrivacyMainScreen.tsx
  ts/screens/profile/__test__/PrivacyMainScreen.test.tsx
Labels: Bug 🐞, IO-A&I

#6544 fix(IT Wallet): [SIW-1917] Fix crash in credentials onboarding screen
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/common/store/reducers/index.ts
Labels: IT Wallet

#6546 fix: [IOBP-1082] Typo in Zendesk assistance json remote path
  ts/api/content.ts
  ts/features/payments/checkout/hooks/usePaymentFailureSupportModal.tsx
Labels: IO-Bonus e pagamenti

#6054 chore(Cross): [IOAPPX-356] Add divider to first level sections when the user scrolls + Add `useHeaderFirstLevel` hook
  jestSetup.js
  ts/components/ui/HeaderFirstLevel.tsx
  ts/components/ui/IOScrollView.tsx
  ts/features/design-system/core/DSHeaderFirstLevel.tsx
  ts/features/design-system/core/DSHeaderSecondLevel.tsx
  ts/features/design-system/core/DSHeaderSecondLevelWithSectionTitle.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/messages/screens/MessagesHomeScreen.tsx
  ts/features/messages/screens/__tests__/MessagesHomeScreen.test.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessagesHomeScreen.test.tsx.snap
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/features/payments/home/screens/__tests__/PaymentsHomeScreen.test.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/wallet/screens/WalletHomeScreen.tsx
  ts/features/wallet/screens/__tests__/WalletHomeScreen.test.tsx
  ts/hooks/useHeaderFirstLevel.tsx
  ts/hooks/useHeaderFirstLevelActionPropHelp.ts
  ts/hooks/useHeaderFirstLevelActionPropSettings.ts
  ts/hooks/useTabItemPressWhenScreenActive.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: Design System, Cross, :nail_care: Visual tweaks

#6503 chore: [IOCOM-1761] Push notification reminder banner BS and logic
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/__tests__/persistedStore.test.ts
  ts/features/pushNotifications/components/PushNotificationsBanner.tsx
  ts/features/pushNotifications/components/__tests__/PushNotificationsBanner.test.tsx
  ts/features/pushNotifications/components/__tests__/__snapshots__/PushNotificationsBanner.test.tsx.snap
  ts/features/pushNotifications/store/actions/__tests__/userBehaviour.test.ts
  ts/features/pushNotifications/store/actions/userBehaviour.ts
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/userBehaviour.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/index.test.ts
  ts/features/pushNotifications/store/reducers/__tests__/userBehaviour.test.ts
  ts/features/pushNotifications/store/reducers/index.ts
  ts/features/pushNotifications/store/reducers/userBehaviour.ts
  ts/features/pushNotifications/store/selectors/__tests__/index.test.ts
  ts/features/pushNotifications/store/selectors/__tests__/notificationsBannerDismissed.test.ts
  ts/features/pushNotifications/store/selectors/index.ts
  ts/features/pushNotifications/store/selectors/notificationsBannerDismissed.ts
  ts/utils/testWrapper.tsx
Labels: IO-Comunicazione

#6548 chore: [IOBP-1083] Update `IN_APP_BROWSER_CLOSED_BY_USER` outcome text
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/screens/___tests___/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
Labels: IO-Bonus e pagamenti

#6543 fix(IT Wallet): [SIW-1902] Wallet accessibility improvements
  ts/features/wallet/components/WalletCardsContainer.tsx
Labels: IT Wallet

#6464 chore: [IOCOM-1763] Refactor of push notification engagement screen display logic
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/landingScreenMultiBanner/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/pushNotifications/screens/SystemNotificationPermissionsScreen.tsx
  ts/features/pushNotifications/screens/__tests__/SystemNotificationPermissionsScreen.test.tsx
  ts/features/pushNotifications/store/actions/__tests__/environment.test.ts
  ts/features/pushNotifications/store/actions/__tests__/userBehaviour.test.ts
  ts/features/pushNotifications/store/actions/environment.ts
  ts/features/pushNotifications/store/actions/userBehaviour.ts
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/environment.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/userBehaviour.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/environment.test.ts
  ts/features/pushNotifications/store/reducers/__tests__/index.test.ts
  ts/features/pushNotifications/store/reducers/__tests__/userBehaviour.test.ts
  ts/features/pushNotifications/store/reducers/environment.ts
  ts/features/pushNotifications/store/reducers/index.ts
  ts/features/pushNotifications/store/reducers/userBehaviour.ts
  ts/features/pushNotifications/store/selectors/__tests__/notificationsBannerDismissed.test.ts
  ts/features/pushNotifications/store/selectors/index.ts
  ts/features/pushNotifications/store/selectors/notificationsBannerDismissed.ts
Labels: IO-Comunicazione

#6535 chore: [IOBP-1064] Add payment auth error mixpanel event
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/onboarding/analytics/__tests__/index.test.ts
  ts/features/payments/onboarding/analytics/index.ts
Labels: IO-Bonus e pagamenti

#6553 chore: [IOBP-1085] Removed delete transaction API request when closing in-app browser
  ts/features/payments/checkout/hooks/useWalletPaymentAuthorizationModal.tsx
Labels: IO-Bonus e pagamenti

#6473 chore(Cross): [IOAPPX-442] Fix dark mode text on light backgrounds + Fix overflow text on cards + Extend dark mode support
  package.json
  ts/features/bonus/cgn/components/CgnCard.tsx
  ts/features/design-system/components/DSSpacerViewerBox.tsx
  ts/features/design-system/core/DSCards.tsx
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwDigitalVersionBadge.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimLabel.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
  ts/features/itwallet/common/components/__tests__/ItwCredentialCard.test.tsx
  ts/features/itwallet/common/components/__tests__/ItwDigitalVersionBadge.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwDigitalVersionBadge.test.tsx.snap
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwFeedbackBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerOnboarding.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/SecuritySuggestions.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/RemoteContentBanner.test.tsx.snap
  ts/features/payments/common/components/PaymentCard.tsx
  ts/features/payments/common/components/PaymentCardBig.tsx
  ts/features/payments/common/components/__tests__/PaymentCardBig.test.tsx
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardBig.test.tsx.snap
  ts/features/pushNotifications/components/__tests__/__snapshots__/PushNotificationsBanner.test.tsx.snap
  ts/screens/authentication/__tests__/__snapshots__/LandingScreen.test.tsx.snap
  ts/screens/profile/__test__/__snapshots__/ProfileMainScreenTopBanner.test.tsx.snap
  ts/screens/profile/components/__test__/__snapshots__/SettingsDiscoveryBanner.test.tsx.snap
  yarn.lock
Labels: Design System, Dark mode 🌝, Cross

#6556 chore(IT Wallet): [SIW-1927] Add pull-to-refresh to the wallet screen
  ts/components/ui/IOScrollView.tsx
  ts/features/wallet/saga/handleWalletAnalyticsSaga.ts
  ts/features/wallet/saga/handleWalletUpdateSaga.ts
  ts/features/wallet/saga/index.ts
  ts/features/wallet/screens/WalletHomeScreen.tsx
  ts/features/wallet/store/actions/index.ts
  ts/features/wallet/store/reducers/cards.ts
  ts/features/wallet/store/selectors/index.ts
  ts/features/wallet/utils/index.tsx
Labels: IT Wallet

#6434 chore(Cross): [IOAPPX-437] Add support for Material You by adding a new adaptive launcher icon for Android
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/res/drawable/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/io_app_icon_foreground.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values/ic_launcher_background.xml
Labels: Design System, Cross

#5715 chore(Cross): [IOAPPX-206] Add dynamic card effect based on device rotation
  img/dynamicCardRotation/driver-license-background.png
  ts/features/design-system/core/DSDynamicCardRotation.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
Labels: Design System, Cross, Experimental lab ✨

#6555 chore: [IOBP-1076] FAQ without CTA with sticky buttons
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
Labels: IO-Bonus e pagamenti

#6554 fix: [IOPID-2547] Fix unhandled error on `Linking.openUrl`
  locales/en/index.yml
  locales/it/index.yml
  ts/features/cie/__tests__/CieIdNotInstalled.test.tsx
  ts/features/cie/components/CieIdNotInstalled.tsx
Labels: IO-A&I

#6416 chore(Cross): [IOAPPX-432] Development Push notifications for Android
  google-services-dev.json
  mock-google-services.json
  scripts/generate-api-models.sh
  ts/features/pushNotifications/utils/configurePushNotification.ts
Labels: IO-Comunicazione, Cross

#6547 feat(IT Wallet): [SIW-1824] Show alert if wallet instance is revoked
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/trustmark/machine/actions.ts
  ts/features/itwallet/walletInstance/hook/useItwWalletInstanceRevocationAlert.ts
  ts/features/itwallet/walletInstance/store/actions/index.ts
  ts/features/itwallet/walletInstance/store/reducers/index.ts
  ts/features/itwallet/walletInstance/store/selectors/index.ts
  ts/features/wallet/components/WalletCardsContainer.tsx
  ts/features/wallet/components/__tests__/WalletCardsContainer.test.tsx
Labels: IT Wallet

#6569 fix(IT Wallet): [SIW-1934] Cleanup the integrityKeyTag if getWalletAttestation throws an error
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6575 refactor: [IOBP-1091] Paid in app empty state screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/receipts/screens/ReceiptListScreen.tsx
Labels: IO-Bonus e pagamenti
