Repository pagopa/io-app, pull requests merged in 2024-09, with the labels that each got.

#6140 fix: [IOPID-2168] Go back using iOS gesture from settings section
  ts/navigation/AuthenticatedStackNavigator.tsx
Labels: Bug 🐞, IO-A&I

#6128 chore(IT Wallet): [SIW-1506] Update `io-react-native-wallet` to 0.16.2
  package.json
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwCredentialIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwCryptoContextUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/__tests__/machine.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/machine.ts
  yarn.lock
Labels: IT Wallet

#6102 chore: [IOPID-2150] Migrate to the new `SessionManager` specifications
  package.json
  ts/api/backend.ts
  ts/api/backendPublic.ts
  ts/features/idpay/configuration/xstate/provider.tsx
  ts/features/idpay/onboarding/xstate/provider.tsx
  ts/features/idpay/payment/xstate/provider.tsx
  ts/features/idpay/unsubscription/xstate/provider.tsx
  ts/features/lollipop/__tests__/login.test.ts
  ts/features/lollipop/saga/index.ts
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
  ts/sagas/startup/__tests__/loadSessionInformationSaga.test.ts
  ts/sagas/startup/__tests__/watchCheckSessionSaga.test.ts
  ts/sagas/startup/loadSessionInformationSaga.ts
  ts/sagas/startup/watchCheckSessionSaga.ts
  ts/sagas/testLoginSaga.ts
  ts/screens/authentication/TestAuthenticationScreen.tsx
  ts/screens/authentication/__tests__/TestAuthenticationScreen.test.tsx
  ts/store/actions/authentication.ts
  ts/store/reducers/authentication.ts
Labels: IO-A&I

#6074 chore(IT Wallet): [SIW-1440] Add Disability Card credential issuance
  locales/en/index.yml
  locales/it/index.yml
  ts/components/QrCodeImage.tsx
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwCredentialClaimList.tsx
  ts/features/itwallet/common/components/ItwGenericErrorContent.tsx
  ts/features/itwallet/common/components/ItwQrCodeClaimImage.tsx
  ts/features/itwallet/common/components/__tests__/ItwCredentialClaimsSection.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialClaimsSection.test.tsx.snap
  ts/features/itwallet/common/hooks/useItwDisableGestureNavigation.ts
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/debug.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwCredentialIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwErrorsUtils.ts
  ts/features/itwallet/identification/hooks/useItwIdpIdentification.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/components/ItwClaimsSections.tsx
  ts/features/itwallet/presentation/components/ItwPresentationClaimsSection.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationAlertsSection.test.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationClaimsSection.test.tsx
  ts/features/itwallet/presentation/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
Labels: IT Wallet

#6129 chore: [IOCOM-1095] FIMS analytics events
  ts/features/fims/common/analytics/index.ts
  ts/features/fims/common/utils/index.ts
  ts/features/fims/history/hooks/useFimsHistoryResultToasts.tsx
  ts/features/fims/history/saga/handleExportFimsHistorySaga.ts
  ts/features/fims/history/saga/handleGetFimsHistorySaga.ts
  ts/features/fims/history/screens/HistoryScreen.tsx
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/fims/singleSignOn/saga/handleFimsAbortOrCancel.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/singleSignOn/saga/index.ts
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/singleSignOn/store/actions/index.ts
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/fims/singleSignOn/store/selectors/index.ts
  ts/features/messages/components/MessageDetail/MessageDetailsStickyFooter.tsx
  ts/features/messages/components/MessageDetail/detailsUtils.ts
  ts/features/messages/utils/messages.ts
  ts/features/services/details/screens/ServiceDetailsScreen.tsx
Labels: IO-Comunicazione

#6141 chore: [IOCOM-1679] FIMS consents screen: fast Login handling on service retrieval
  ts/features/fims/singleSignOn/utils/index.ts
Labels: IO-Comunicazione

#6112 feat(IT Wallet): [SIW-1470] Add IT Wallet skeumorphic credential cards
  img/features/itWallet/credential/mdl_back.png
  img/features/itWallet/credential/mdl_back.svg
  img/features/itWallet/credential/mdl_back@2x.png
  img/features/itWallet/credential/mdl_front.png
  img/features/itWallet/credential/mdl_front.svg
  img/features/itWallet/credential/mdl_front@2x.png
  ts/features/itwallet/__mocks__/mdl.json
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardBackground.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardClaim.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardData.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimLabel.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/DigitalVersionBadge.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/FlippableCard.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/CardClaim.test.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/CardData.test.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
  ts/features/itwallet/common/components/ItwSkeumorphicCard/index.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/types.ts
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/playgrounds/components/ItwSkeumorphicCredentialSection.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/types/helpers.ts
Labels: IT Wallet

#6081 chore(IT Wallet): [SIW-1441] Add Disability Card to credentials catalog
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/onboarding/screens/__tests__/WalletCardOnboardingScreen.test.tsx
Labels: IT Wallet

#6118 chore(IT Wallet): [SIW-1474] Rename "IT Wallet" to "Documenti su IO"
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSCards.tsx
  ts/features/design-system/core/DSWallet.tsx
  ts/screens/profile/DeveloperModeSection.tsx
Labels: IT Wallet

#6113 feat(IT Wallet): [SIW-1501] Add credential issuance machine unit tests
  ts/features/itwallet/common/utils/itwCredentialIssuanceUtils.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/context.ts
  ts/features/itwallet/machine/credential/events.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
Labels: IT Wallet

#6117 chore: [IOPID-2107,IOPID-2108] - A11Y adjust onboarding email insertion screen
  jestSetup.js
  package.json
  ts/components/DebugInfoOverlay.tsx
  ts/components/debug/DebugDataIndicator.tsx
  ts/components/screens/__tests__/__snapshots__/ScreenWithListItems.test.tsx.snap
  ts/features/idpay/details/screens/__tests__/IdPayInitiativeDetailsScreen.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
  ts/features/itwallet/presentation/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsAttachmentItem.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsPayment.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessagePaymentItem.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/F24ListBottomSheetLink.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/F24Section.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessagePaymentBottomSheet.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessagePayments.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/features/pushNotifications/screens/__tests__/__snapshots__/OnboardingNotificationsInfoScreenConsent.test.tsx.snap
  ts/features/services/home/components/__tests__/__snapshots__/FeaturedServiceCard.test.tsx.snap
  ts/screens/authentication/__tests__/cie/__snapshots__/ActivateNfcScreen.test.tsx.snap
  ts/screens/profile/EmailInsertScreen.tsx
  yarn.lock
Labels: a11y, IO-A&I

#6137 feat: [IOPID-2064] IOMarkdown improvements
  ts/components/IOMarkdown/markdownRenderer.ts
  ts/components/IOMarkdown/renderRules.tsx
  ts/components/__tests__/__snapshots__/IOMarkdown.test.tsx.snap
Labels: Cross

#6133 fix(IT Wallet): [SIW-1409] Set maximum length for text claims
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
Labels: IT Wallet

#6138 chore(IT Wallet): [SIW-1299] Credentials status attestation at app startup
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/__mocks__/statusAttestation.json
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwCredentialClaimList.tsx
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/utils/__tests__/itwCredentialStatusAttestationUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwCredentialStatusAttestationUtils.ts
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
  ts/features/itwallet/credentials/saga/handleWalletCredentialsRehydration.ts
  ts/features/itwallet/credentials/store/actions/index.ts
  ts/features/itwallet/credentials/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/credentials/store/reducers/index.ts
  ts/features/itwallet/presentation/components/ItwPresentationAlertsSection.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
Labels: IT Wallet

#6145 chore: [IOPID-2163] Delete local FF to activate new scan and settings sections
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IO-A&I

#6147 fix: [IOBP-847] Navigate to the new payment flow from scan notice qr-code
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/payments/barcode/screens/PaymentsBarcodeChoiceScreen.tsx
Labels: Bug 🐞, Help Wanted 🚨

#6146 fix(IT Wallet): [SIW-1537] Duplicate fiscal code in trust issuer screen
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
Labels: IT Wallet

#6148 chore(IT Wallet): [SIW-1538] Add navigation on credential renewal
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/events.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/credential/selectors.ts
  ts/features/itwallet/machine/tags.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/components/ItwPresentationAlertsSection.tsx
Labels: IT Wallet

#6099 chore: [IOCOM-1672] InApp Browser checking on FIMS
  ios/Podfile.lock
  package.json
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  yarn.lock
Labels: IO-Comunicazione

#6151 chore: [IOCOM-1580] Fims auth missing service data error case
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/common/utils/hooks.tsx
  ts/features/fims/history/components/FimsHistoryListItem.tsx
  ts/features/fims/singleSignOn/components/FimsClaims.tsx
  ts/features/fims/singleSignOn/components/FimsErrorScreens.tsx
  ts/features/fims/singleSignOn/components/FimsPrivacyInfo.tsx
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
Labels: IO-Comunicazione

#6156 fix(IT Wallet): [SIW-1548] Error screen instead of loading screen while issuing credential
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
Labels: IT Wallet

#6143 chore: [IOCOM-1666] Proper labels on FIMS abort screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
Labels: IO-Comunicazione

#6155 chore: [IOPID-2196] Revert old PR to delete local FF to activate new scan and settings sections
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IO-A&I

#6149 fix(IT Wallet): [SIW-1535] Credential duplication after renewal
  ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
  ts/features/itwallet/credentials/saga/handleItwCredentialsRemoveSaga.ts
  ts/features/itwallet/credentials/saga/handleItwCredentialsStoreSaga.ts
  ts/features/itwallet/credentials/saga/handleWalletCredentialsRehydration.ts
  ts/features/itwallet/credentials/store/actions/index.ts
  ts/features/itwallet/credentials/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/credentials/store/reducers/index.ts
  ts/features/itwallet/lifecycle/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/eid/actions.ts
Labels: IT Wallet

#6150 chore(IT Wallet): [SIW-1541] Add status attestation for any credential
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
Labels: IT Wallet

#6158 fix(IT Wallet): [SIW-1549] Update copy for credential issuance generic error message
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
Labels: IT Wallet

#6160 fix: [IOBP-853] Receipt Share & Save button feature
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsPreviewScreen.tsx
Labels: Bug 🐞, IO-Bonus e pagamenti

#6105 chore(IT Wallet): [SIW-1447] Allow user to cancel CieID identification
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/issuance/components/ItwIssuanceLoadingScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/guards.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/eid/selectors.ts
Labels: IT Wallet

#5989 feat: [PE-614] CGN landing page new copy
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/screens/activation/CgnInformationScreen.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
Labels: Carta Giovani Nazionale

#6042 fix: [IOBP-793] Unauthorized status mapping from checkout APIs
  package.json
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetAllMethods.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetDetails.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetUserWallets.ts
  ts/features/payments/wallet/saga/handleGetPaymentsWalletUserMethods.ts
Labels: Bug 🐞, IO-Bonus e pagamenti

#6144 chore(IT Wallet): [SIW-1536] Add skeumorphic card in MDL details screen
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/design-system/core/DSCards.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardBackground.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  yarn.lock
Labels: IT Wallet

#6097 feat: [PE-610] CGN detail screen new card appearance
  img/bonus/cgn/card_mask.png
  img/bonus/cgn/eyca_logo.png
  ts/components/BonusCard/BonusCard.tsx
  ts/components/BonusCard/BonusCardScreenComponent.tsx
  ts/components/BonusCard/BonusCardShape.tsx
  ts/components/BonusCard/BonusCardStatus.tsx
  ts/components/BonusCard/__tests__/BonusCard.test.tsx
  ts/components/BonusCard/__tests__/BonusCardStatus.test.tsx
  ts/features/bonus/cgn/components/CgnAnimatedBackground.tsx
  ts/features/bonus/cgn/components/CgnCardStatus.tsx
  ts/features/bonus/cgn/components/detail/CardSvgPayload.ts
  ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx
  ts/features/bonus/cgn/components/detail/__test__/CgnCardComponent.test.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/design-system/core/DSBonusCardScreen.tsx
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
Labels: Carta Giovani Nazionale

#6170 chore(Cross): [IOAPPX-369] Add support for `enableDiscreteTransition` to the `useHeaderSecondLevel` hook
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsPreviewScreen.tsx
  ts/features/payments/transaction/screens/PaymentsTransactionListScreen.tsx
  ts/hooks/useHeaderSecondLevel.tsx
  ts/screens/authentication/TestAuthenticationScreen.tsx
  ts/screens/profile/TrialSystemPlayground.tsx
Labels: Design System, Cross

#6139 chore(IT Wallet): [SIW-1509] Add European Health Insurance Card credential issuance
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
Labels: IT Wallet

#6172 fix: [PE-588] Cgn card detail capitalize user name surname
  ts/features/bonus/cgn/components/detail/CgnOwnershipInformation.tsx
Labels: Carta Giovani Nazionale

#6173 fix(IT Wallet): [SIW-1587] Use the status attestation info to get the status in `ItwPresentationCredentialCard`
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
Labels: IT Wallet

#6177 chore: [IOCOM-1691] Update I18n in Fims auth screen
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Comunicazione

#6174 chore: [IOCOM-1625] FIMS history screen UI revamp
  ts/features/fims/history/components/FimsHistoryListItem.tsx
  ts/features/fims/history/components/FimsHistoryLoaders.tsx
  ts/features/fims/history/components/FimsHistoryNonEmptyContent.tsx
  ts/features/fims/history/utils/styles.ts
Labels: IO-Comunicazione

#6175 fix: [IOBP-867] Regression of generic error page into verify payment screen
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetDetails.ts
Labels: Bug 🐞, IO-Bonus e pagamenti

#6165 fix: [IOBP-836] Remove assistance for FCI into payments zendesk modal
  ts/features/payments/checkout/hooks/usePaymentFailureSupportModal.tsx
Labels: IO-Bonus e pagamenti

#6108 feat: [IOBP-634] Add pull to refresh in payments home screen
  ts/components/ui/IOScrollView.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/details/components/PaymentsMethodDetailsDeleteButton.tsx
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/features/payments/home/store/selectors/index.ts
  ts/features/payments/wallet/store/reducers/index.ts
Labels: Help Wanted 🚨, IO-Bonus e pagamenti

#6185 fix: [PE-681] CGN hide discount badge if 0
  ts/features/bonus/cgn/components/merchants/CgnModuleDiscount.tsx
Labels: Carta Giovani Nazionale

#6181 chore: [PE-683] CGN detail screen change labels
  locales/en/index.yml
  locales/it/index.yml
Labels: Carta Giovani Nazionale

#6189 chore: [IOBP-860] Preserve `flow` in custom properties for Mixpanel event tracking
  ts/utils/analytics.ts
Labels: IO-Bonus e pagamenti

#6162 feat(IT Wallet): [SIW-1522] Get credential status attestation after issuance
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/actors.ts
  ts/features/itwallet/machine/credential/machine.ts
Labels: IT Wallet

#6182 chore: [PE-684] CGN update eyca label
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
Labels: Carta Giovani Nazionale

#6163 chore(IT Wallet): [SIW-1510] Add European Health Insurance Card to the credential list
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
Labels: IT Wallet

#6191 feat(IT Wallet): [SIW-1594] Add official Driving License credential assets
  img/features/itWallet/credential/mdl_back.png
  img/features/itWallet/credential/mdl_back@2x.png
  img/features/itWallet/credential/mdl_front.png
  img/features/itWallet/credential/mdl_front@2x.png
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwDigitalVersionBadge.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardClaim.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardData.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimLabel.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
  ts/features/itwallet/common/components/ItwSkeumorphicCard/index.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
Labels: IT Wallet

#6190 chore(IT Wallet): [SIW-1567] Not entitled credential error
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/machine/credential/failure.ts
  ts/features/itwallet/machine/credential/machine.ts
  yarn.lock
Labels: IT Wallet

#6195 chore(IT Wallet): [SIW-1657] Change trustmark verifier base URL
  .env.local
  .env.production
Labels: IT Wallet

#6161 chore(IT Wallet): [SIW-1550] Add CTA to view/download PDF in the European Health Insurance card's details screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/presentation/components/ItwPresentationDetailsHeader.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailsScreenBase.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialAttachmentScreen.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
Labels: IT Wallet

#6197 fix(IT Wallet): [SIW-1609] Persisted credentials after uninstalling app on iOS
  ts/features/itwallet/machine/eid/actors.ts
Labels: IT Wallet

#6201 fix: [IABT-1527,IOBP-877] Translated "Rimuovi" into delete payment method button in english
  locales/en/index.yml
Labels: IO-Bonus e pagamenti

#6194 fix: [IOBP-839] Hide gradient if no payment method selected
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
Labels: IO-Bonus e pagamenti

#6186 chore(IT Wallet): [SIW-1438,SIW-1147] Add Mixpanel event tracking
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/common/components/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/ItwMarkdown.tsx
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationIdpSelectionScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwActivateNfcScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieExpiredOrInvalidScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCiePinScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieUnexpectedErrorScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieWrongCiePinScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/lifecycle/screens/ItwIdentityNotMatchingScreen.tsx
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/selectors.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/newWallet/components/WalletEmptyScreenContent.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/mixpanelConfig/profileProperties.ts
Labels: IT Wallet

#5926 chore: [IOBP-553] IDPay definitions adaption
  package.json
  ts/features/idpay/details/components/BeneficiaryDetailsContent.tsx
  ts/features/idpay/details/components/TimelineOperationListItem.tsx
  ts/features/idpay/details/components/__tests__/BeneficiaryDetailsContent.test.tsx
  ts/features/idpay/details/components/__tests__/TimelineOperationListItem.test.tsx
  ts/features/idpay/details/saga/__test__/handleGetTimelinePage.test.ts
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
  ts/features/idpay/details/store/__test__/store.test.ts
  ts/features/idpay/onboarding/xstate/__tests__/services.test.ts
  ts/features/idpay/onboarding/xstate/services.ts
  ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
  ts/features/idpay/timeline/components/TimelineDiscountTransactionDetailsComponent.tsx
  ts/features/idpay/timeline/components/TimelineRefundDetailsComponent.tsx
  ts/features/idpay/timeline/components/TimelineTransactionDetailsComponent.tsx
  ts/features/idpay/timeline/saga/__tests__/handleGetTimelineDetails.test.ts
  ts/features/idpay/timeline/store/__test__/store.test.ts
  ts/features/idpay/timeline/utils/__tests__/strings.tests.ts
  ts/features/idpay/wallet/components/IDPayCardsInWalletContainer.tsx
  ts/features/idpay/wallet/saga/handleGetWallet.ts
Labels: IDPay, IO-Bonus e pagamenti

#6198 chore: [IOPID-2275] Settings Section Communication Banner & delete locale FF to activate new scan and settings sections
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/features/itwallet/common/components/ItwDiscoveryBanner.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/profileSettings/store/actions/index.ts
  ts/features/profileSettings/store/reducers/index.ts
  ts/features/profileSettings/store/selectors/index.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/components/SettingsDiscoveryBanner.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/index.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IO-A&I

#6202 fix(IT Wallet): [SIW-1658] Remove digital version badge from eID card
  ts/features/itwallet/common/components/ItwDigitalVersionBadge.tsx
  ts/features/itwallet/common/components/__tests__/ItwCredentialCard.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
Labels: IT Wallet

#6193 chore(Cross): [IOAPPX-373] Update Sentry dependencies to support Xcode 16
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Cross

#6171 chore(Cross): [IOAPPX-370] Enable discrete transition in the `BonusCardScreenComponent`
  ts/components/BonusCard/BonusCardScreenComponent.tsx
  ts/components/BonusCard/BonusCardShape.tsx
  ts/components/ui/IOScrollView.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/design-system/core/DSBonusCardScreen.tsx
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
Labels: Design System, Cross, code review needed 💻📱

#6200 chore(IT Wallet): [SIW-1636] Handle the initial phase of async credential issuance
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/events.ts
  ts/features/itwallet/machine/credential/failure.ts
  yarn.lock
Labels: IT Wallet

#6192 feat: [IOPID-2263] Cie ID Error screens
  locales/en/index.yml
  locales/it/index.yml
  ts/features/cie/__tests__/CieIdErrorScreen.test.tsx
  ts/features/cie/__tests__/__snapshots__/CieIdErrorScreen.test.tsx.snap
  ts/features/cie/__tests__/wizards.test.tsx
  ts/features/cie/screens/errors/CieIdErrorScreen.tsx
  ts/features/cie/screens/wizards/CieIdWizard.tsx
  ts/features/cie/screens/wizards/CiePinWizard.tsx
  ts/features/cie/screens/wizards/IDActivationWizard.tsx
  ts/features/cie/screens/wizards/SpidWizard.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/routes.ts
Labels: IO-A&I

#6152 chore: [IOBP-841,IOBP-842] Edit new payment flow mixpanel property values
  ts/features/payments/barcode/screens/PaymentsBarcodeChoiceScreen.tsx
  ts/features/payments/barcode/screens/PaymentsBarcodeScanScreen.tsx
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/hooks/useWalletPaymentGoBackHandler.tsx
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/mixpanelConfig/profileProperties.ts
Labels: IO-Bonus e pagamenti

#6167 fix: [IOBP-808] Add trim notice code workaround if pasted
  ts/features/payments/checkout/screens/WalletPaymentInputNoticeNumberScreen.tsx
  ts/features/payments/checkout/utils/__tests__/index.test.ts
  ts/features/payments/checkout/utils/index.ts
Labels: IO-Bonus e pagamenti

#6180 chore: [IOBP-854] Add payment mixpanel event property for the `selected_psp_flag`
  ts/features/payments/history/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#6208 feat: [IOBP-766] Add payments section mixpanel events
  ts/features/payments/bizEventsTransaction/analytics/index.ts
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsCartItemDetailsScreen.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsDetailsScreen.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsPreviewScreen.tsx
  ts/features/payments/bizEventsTransaction/store/actions/index.ts
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/utils/index.ts
  ts/features/payments/common/types/PaymentAnalytics.ts
  ts/features/payments/history/store/__tests__/store.test.ts
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/home/analytics/index.ts
  ts/features/payments/home/components/PaymentsHomeEmptyScreenContent.tsx
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/features/payments/transaction/analytics/index.ts
  ts/features/payments/transaction/screens/PaymentsTransactionListScreen.tsx
  ts/store/transforms/setTransform.ts
Labels: IO-Bonus e pagamenti

#6219 fix(IT Wallet): [SIW-1681] Authorization with CIE L3 to obtain an eID
  package.json
  yarn.lock
Labels: IT Wallet

#5869 chore(Cross): [IOAPPX-322] Update the entire `Assistance` section with the new DS components
  ts/components/FAQComponent.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/components/screens/BaseScreenComponent/utils.tsx
  ts/components/screens/IdpCustomContextualHelpContent.tsx
  ts/components/ui/IOScrollView.tsx
  ts/components/ui/IOScrollViewWithLargeHeader.tsx
  ts/features/design-system/core/DSLegacyListItems.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/zendesk/components/ZendeskEmptyTicketsComponent.tsx
  ts/features/zendesk/components/ZendeskItemPermissionComponent.tsx
  ts/features/zendesk/components/ZendeskSupportComponent.tsx
  ts/features/zendesk/components/__tests__/ZendeskSupportComponent.test.tsx
  ts/features/zendesk/navigation/navigator.tsx
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/features/zendesk/screens/ZendeskAskSeeReportsPermissions.tsx
  ts/features/zendesk/screens/ZendeskChooseCategory.tsx
  ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx
  ts/features/zendesk/screens/ZendeskPanicMode.tsx
  ts/features/zendesk/screens/ZendeskSeeReportsRouters.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/features/zendesk/screens/__tests__/ZendeskChooseCategory.test.tsx
  ts/features/zendesk/screens/__tests__/ZendeskChooseSubCategory.test.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/NotAuthenticatedStackNavigator.tsx
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/idpAuthSessionHandler.tsx
  ts/utils/emptyContextualHelp.tsx
Labels: Design System, Cross

#6199 feat: [IOPID-2176,IOPID-2177,IOPID-2178,IOPID-2179] Ingress screen evolutionary
  ios/Podfile.lock
  jestSetup.js
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/SectionStatus/modal/index.tsx
  ts/components/screens/LoadingScreenContent.tsx
  ts/features/common/store/reducers/index.ts
  ts/features/ingress/__test__/IngressScreen.test.tsx
  ts/features/ingress/__test__/__snapshots__/IngressScreen.test.tsx.snap
  ts/features/ingress/analytics/index.ts
  ts/features/ingress/screens/IngressScreen.tsx
  ts/features/ingress/store/actions/index.ts
  ts/features/ingress/store/reducer/index.ts
  ts/features/ingress/store/selectors/index.ts
  ts/features/mixpanel/store/actions/index.ts
  ts/features/mixpanel/store/reducer/index.ts
  ts/features/mixpanel/store/selectors/index.ts
  ts/mixpanel.ts
  ts/navigation/AppStackNavigator.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/mixpanel.ts
  ts/sagas/startup.ts
  ts/screens/ingress/IngressScreen.tsx
  ts/store/actions/types.ts
  ts/store/reducers/backendStatus.ts
  yarn.lock
Labels: IO-A&I
