Repository pagopa/io-app, pull requests merged in 2024-01, with the labels that each got.

#5372 fix: [IOCOM-759] Remove the section title if there are no attachments
  ts/components/messages/MessageDetail/index.tsx
Labels: IO-Comunicazione

#5368 fix: [IOCOM-761] Text wrapping for precondition's title text
  ts/features/messages/components/PreconditionBottomSheet/PreconditionHeader.tsx
Labels: IO-Comunicazione

#5374 fix(IT Wallet): [SIW-786] Fix CGN test
  ts/features/bonus/cgn/utils/__test__/dates.test.ts
Labels: IT Wallet

#5302 feat: [IOBP-313] New wallet payment pick PSP
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/design-system/core/DSSelection.tsx
  ts/features/walletV3/common/utils/index.ts
  ts/features/walletV3/payment/components/WalletPspListSkeleton.tsx
  ts/features/walletV3/payment/hooks/useSortPspBottomSheet.tsx
  ts/features/walletV3/payment/navigation/navigator.tsx
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentCalculateFees.test.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/walletV3/payment/screens/WalletPaymentPickPspScreen.tsx
  ts/features/walletV3/payment/store/actions/orchestration.ts
  ts/features/walletV3/payment/store/reducers/index.ts
  ts/features/walletV3/payment/types/index.ts
  ts/hooks/useHeaderProps.tsx
  yarn.lock
Labels: IO-Bonus e pagamenti

#5344 feat: [IOBP-314] Wallet payment confirm screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/common/utils/index.ts
  ts/features/walletV3/payment/components/WalletPaymentConfirmContent.tsx
  ts/features/walletV3/payment/components/WalletPaymentTotalAmount.tsx
  ts/features/walletV3/payment/navigation/navigator.tsx
  ts/features/walletV3/payment/screens/WalletPaymentConfirmScreen.tsx
Labels: IO-Bonus e pagamenti

#5373 chore(IT Wallet): [SIW-709] Update PID issuing saga to match a generic credential
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/it-wallet/components/ItwCredentialCard.tsx
  ts/features/it-wallet/components/ItwCredentialClaim.tsx
  ts/features/it-wallet/components/ItwCredentialClaimsList.tsx
  ts/features/it-wallet/components/ItwPidClaimsList.tsx
  ts/features/it-wallet/navigation/ItwStackNavigator.tsx
  ts/features/it-wallet/saga/__tests__/itwWiaSaga.ts
  ts/features/it-wallet/saga/index.ts
  ts/features/it-wallet/saga/itwPidIssuanceSaga.ts
  ts/features/it-wallet/saga/itwPidSaga.ts
  ts/features/it-wallet/saga/itwRpInitializationSaga.ts
  ts/features/it-wallet/saga/itwRpPresentationSaga.ts
  ts/features/it-wallet/saga/itwWiaSaga.ts
  ts/features/it-wallet/saga/new/itwIssuanceSaga.ts
  ts/features/it-wallet/saga/new/itwPresentationSaga.ts
  ts/features/it-wallet/screens/ItwHomeScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwIssuingCredentialAuthScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwIssuingCredentialCatalogScreen.tsx
  ts/features/it-wallet/screens/issuing/credential/ItwIssuingCredentialPreviewScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwIssuingPidRequestScreen.tsx
  ts/features/it-wallet/screens/issuing/pid/ItwPidPreviewScreen.tsx
  ts/features/it-wallet/screens/presentation/ItwPrCredentialDetails.tsx
  ts/features/it-wallet/screens/presentation/ItwPrPidDetails.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrRemoteCredentialChecksScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrRemoteCredentialDataScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/credential/ItwPrRemoteCredentialResultScreen.tsx
  ts/features/it-wallet/screens/presentation/remote/pid/ItwPrRemotePidDataScreen.tsx
  ts/features/it-wallet/store/actions/index.ts
  ts/features/it-wallet/store/actions/itwCredentialsActions.ts
  ts/features/it-wallet/store/actions/itwIssuanceActions.ts
  ts/features/it-wallet/store/actions/itwPresentationActions.ts
  ts/features/it-wallet/store/reducers/index.ts
  ts/features/it-wallet/store/reducers/itwCredentialsReducer.ts
  ts/features/it-wallet/store/reducers/itwPidDecodeReducer.ts
  ts/features/it-wallet/store/reducers/itwPidReducer.ts
  ts/features/it-wallet/store/reducers/new/itwIssuanceReducer.ts
  ts/features/it-wallet/store/reducers/new/itwPresentationReducer.ts
  ts/features/it-wallet/utils/itwClaimsUtils.ts
  ts/features/it-wallet/utils/itwSecureStorageUtils.ts
  ts/features/it-wallet/utils/mocks.ts
  ts/features/it-wallet/utils/pid.ts
  ts/features/it-wallet/utils/types.ts
  ts/features/it-wallet/utils/wia.ts
  ts/sagas/startup.ts
Labels: IT Wallet

#5159 feat(Firma con IO): [SFEQS-1892] Add environment to Mixpanel events
  ts/features/fci/analytics/index.ts
  ts/features/fci/components/SuccessComponent.tsx
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/fci/hooks/useFciCheckService.tsx
  ts/features/fci/hooks/useFciNoSignatureFields.tsx
  ts/features/fci/saga/networking/__tests__/handleGetSignatureRequestById.test.ts
  ts/features/fci/saga/networking/handleGetSignatureRequestById.ts
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
  ts/features/fci/screens/valid/FciThankyouScreen.tsx
  ts/features/fci/store/actions/index.ts
  ts/features/fci/store/reducers/__tests__/fciEnvironment.test.ts
  ts/features/fci/store/reducers/fciEnvironment.ts
  ts/features/fci/store/reducers/fciSignatureRequest.ts
  ts/features/fci/store/reducers/index.ts
  ts/features/fci/utils/fciHeaders.ts
  ts/store/middlewares/analytics.ts
Labels: Firma con IO

#5381 fix: [IOPID-1297] Fix: the navigation object hasn't been initialized yet
  ts/features/fastLogin/screens/FastLoginModals.tsx
  ts/features/fastLogin/store/actions/tokenRefreshActions.ts
  ts/features/fastLogin/store/reducers/tokenRefreshReducer.ts
  ts/sagas/startup.ts
Labels: IO-A&I

#5366 chore: [IOAPPFD0-205] Remove `profileAlt` icon reference from the codebase
  ts/components/PinCreationForm.tsx
  ts/features/bonus/bonusVacanze/screens/activation/request/ActivateBonusReminder.tsx
  ts/features/design-system/core/DSAdvice.tsx
  ts/features/idpay/configuration/screens/IbanEnrollmentScreen.tsx
  ts/features/idpay/configuration/screens/IbanOnboardingScreen.tsx
  ts/screens/onboarding/OnboardingShareDataScreen.tsx
Labels: Design System

#5350 feat: [IOBP-311,IOBP-317] New wallet payment method selection screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/payment/components/WalletPaymentConfirmContent.tsx
  ts/features/walletV3/payment/navigation/navigator.tsx
  ts/features/walletV3/payment/navigation/params.ts
  ts/features/walletV3/payment/screens/WalletPaymentConfirmScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickPspScreen.tsx
  ts/features/walletV3/payment/store/actions/orchestration.ts
  ts/features/walletV3/payment/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5387 feat: [IOBP-480] Remove holder name from wallet payment confirm screen
  ts/features/walletV3/payment/components/WalletPaymentConfirmContent.tsx
Labels: IO-Bonus e pagamenti

#5324 chore: [IOAPPFD0-198] Redesign of the developer section with better organization
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/profile/playgrounds/WalletPlayground.tsx
  ts/store/reducers/authentication.ts
Labels: enhancement

#5388 fix: [IOBP-482] Adapted actual payment transaction apis with LV
  ts/sagas/wallet/pagopaApis.ts
Labels: IO-Bonus e pagamenti

#5391 chore: [IOPID-1301] Bump ToS version from 4.7 to 4.8"
  ts/config.ts
Labels: IO-A&I

#5379 chore: [IOBP-438] Add abort dialog for payment flow
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/payment/hooks/useWalletPaymentGoBackHandler.tsx
  ts/features/walletV3/payment/saga/index.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentDeleteTransaction.ts
  ts/features/walletV3/payment/screens/WalletPaymentConfirmScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentDetailScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/walletV3/payment/store/actions/networking.ts
  ts/features/walletV3/payment/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#5378 feat: [IOBP-309, IOBP-312] Add error handling for payment verification and activation requests
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/OperationResultScreenContent.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/walletV3/payment/components/WalletPaymentFailureDetail.tsx
  ts/features/walletV3/payment/hooks/usePaymentFailureSupportModal.tsx
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetDetails.ts
  ts/features/walletV3/payment/screens/WalletPaymentDetailScreen.tsx
  ts/features/walletV3/payment/store/actions/networking.ts
  ts/features/walletV3/payment/store/reducers/index.ts
  ts/features/walletV3/payment/types/failure.ts
  ts/utils/supportAssistance.ts
Labels: IO-Bonus e pagamenti

#5333 chore: [IOAPPFD0-201] Update some Profile screens with the new DS components
  package.json
  ts/components/ui/RNavScreenWithLargeHeader.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/screens/profile/CalendarsPreferencesScreen.tsx
  ts/screens/profile/LanguagesPreferencesScreen.tsx
  ts/screens/profile/NotificationsPreferencesScreen.tsx
  ts/screens/profile/PreferencesScreen.tsx
  ts/screens/profile/PrivacyMainScreen.tsx
  ts/screens/profile/ProfileDataScreen.tsx
  ts/screens/profile/RemoveAccountInfoScreen.tsx
  ts/screens/profile/SecurityScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
  ts/screens/profile/ShareDataScreen.tsx
  ts/screens/profile/components/ShareDataComponent.tsx
  ts/screens/profile/components/services/ServicesContactComponent.tsx
  yarn.lock
Labels: enhancement, Design System

#5394 chore: [IOBP-479] Add temporary missing methods error in method selection screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/payment/components/WalletPaymentMissingMethodsError.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/walletV3/payment/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5392 fix: [IOPID-1287] Change fingerprint icon and fix typo
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fastLogin/components/SecuritySuggestions.tsx
Labels: IO-A&I

#5390 feat: [IOBP-437] Add new wallet payment outcome error handling
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/payment/components/WalletPaymentFailureDetail.tsx
  ts/features/walletV3/payment/components/WalletPaymentFeedbackBanner.tsx
  ts/features/walletV3/payment/hooks/usePaymentFailureSupportModal.tsx
  ts/features/walletV3/payment/screens/WalletPaymentDetailScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/walletV3/payment/store/reducers/index.ts
  ts/features/walletV3/payment/store/selectors/index.ts
  ts/features/walletV3/payment/types/PaymentOutcomeEnum.ts
Labels: IO-Bonus e pagamenti

#5395 chore: [IOBP-486] Add hardware button back navigation in Barcode scan screen for Android devices
  ts/features/barcode/screens/BarcodeScanScreen.tsx
Labels: IO-Bonus e pagamenti

#5396 chore: [IOPID-1227] Fix bottomsheet error 1002
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/onboarding/UnlockAccessScreen.tsx
Labels: IO-A&I

#5363 chore: [PE-510] Integration of LV for CGN flows
  package.json
  ts/features/bonus/cgn/saga/networking/__test__/getEycaStatus.test.ts
  ts/features/bonus/cgn/saga/networking/bucket/index.ts
  ts/features/bonus/cgn/saga/networking/categories/cgnCategoriesSaga.ts
  ts/features/bonus/cgn/saga/networking/details/getCgnInformationSaga.ts
  ts/features/bonus/cgn/saga/networking/eyca/activation/getEycaActivationSaga.ts
  ts/features/bonus/cgn/saga/networking/eyca/details/getEycaStatus.ts
  ts/features/bonus/cgn/saga/networking/merchants/cgnMerchantsSaga.ts
  ts/features/bonus/cgn/saga/networking/otp/index.ts
  ts/features/bonus/cgn/saga/networking/unsubscribe/index.ts
Labels: Carta Giovani Nazionale

#5393 fix: [IOBP-462] Missing transaction details data
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/transaction/components/WalletTransactionHeadingSection.tsx
  ts/features/walletV3/transaction/screens/WalletTransactionDetailsScreen.tsx
  ts/features/walletV3/transaction/store/index.ts
Labels: IO-Bonus e pagamenti

#5398 fix: [IOBP-501] Wallet token into new wallet flows
  ts/features/walletV3/common/saga/index.ts
  ts/sagas/startup.ts
Labels: IO-Bonus e pagamenti

#5369 chore: [IOBP-478] Update ID Pay definitions for IBAN and onboarding exceptions
  package.json
Labels: IDPay, IO-Bonus e pagamenti

#5334 chore: [IOBP-466] Add gallery permission request in barcode scan screen for iOS devices
  ios/Podfile
  ios/Podfile.lock
  jestSetup.js
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  package.json
  patches/@types+react-native+0.69.6.patch
  patches/patches.md
  patches/react-native+0.69.9.patch
  ts/features/barcode/hooks/useIOBarcodeFileReader.tsx
  ts/features/messages/components/MessageDetail/CalendarEventButton.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/navigation/routes.ts
  ts/screens/misc/AndroidMediaPermissionRequestScreen.tsx
  ts/screens/misc/GalleryPermissionInstructionsScreen.tsx
  ts/screens/profile/PreferencesScreen.tsx
  ts/utils/permission.ts
  ts/utils/share.ts
  yarn.lock
Labels: IO-Bonus e pagamenti

#5404 fix: [IOCOM-645,IABT-1485] Fix an Android crash when dealing with calendar events
  patches/patches.md
  patches/react-native-calendar-events+2.2.0.patch
Labels: IO-Comunicazione

#5403 feat: [IOCOM-793] Rename the sagas in the `features/messages/saga` folder
  ts/api/__mocks__/backend.ts
  ts/features/messages/saga/__test__/handleLoadMessageDetails.test.ts
  ts/features/messages/saga/__test__/handleLoadNextPageMessages.test.ts
  ts/features/messages/saga/__test__/handleLoadPreviousPageMessages.test.ts
  ts/features/messages/saga/__test__/handleMessagePrecondition.test.ts
  ts/features/messages/saga/__test__/handleReloadAllMessages.test.ts
  ts/features/messages/saga/__test__/handleUpsertMessageStatusAttribues.test.ts
  ts/features/messages/saga/handleLoadMessageById.ts
  ts/features/messages/saga/handleLoadMessageDetails.ts
  ts/features/messages/saga/handleLoadNextPageMessages.ts
  ts/features/messages/saga/handleLoadPreviousPageMessages.ts
  ts/features/messages/saga/handleMessagePrecondition.ts
  ts/features/messages/saga/handleMigrateToPagination.ts
  ts/features/messages/saga/handleReloadAllMessages.ts
  ts/features/messages/saga/handleThirdPartyMessage.ts
  ts/features/messages/saga/handleUpsertMessageStatusAttribues.ts
  ts/features/messages/saga/index.ts
  ts/features/messages/saga/watchLoadMessageDetails.ts
  ts/features/messages/saga/watchLoadNextPageMessages.ts
  ts/features/messages/saga/watchLoadPreviousPageMessages.ts
  ts/features/messages/saga/watchMigrateToPagination.ts
  ts/features/messages/saga/watchReloadAllMessages.ts
  ts/features/messages/saga/watchUpsertMessageStatusAttribues.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: IO-Comunicazione

#5408 chore: [IOBP-455] Removal of BonusVacanze references across the app
  ts/components/wallet/WalletHomeHeader.tsx
  ts/config.ts
  ts/features/bonus/__mock__/availableBonuses.ts
  ts/features/bonus/bonusVacanze/components/RequestBonus.tsx
  ts/features/bonus/bonusVacanze/navigation/action.ts
  ts/features/bonus/bonusVacanze/navigation/navigator.tsx
  ts/features/bonus/bonusVacanze/navigation/params.ts
  ts/features/bonus/bonusVacanze/navigation/routes.ts
  ts/features/bonus/bonusVacanze/screens/ActiveBonusScreen.tsx
  ts/features/bonus/bonusVacanze/screens/__tests__/AvailableBonusScreen.test.tsx
  ts/features/bonus/bonusVacanze/store/sagas/bonusSaga.ts
  ts/features/bonus/cgn/saga/orchestration/activation/activationSaga.ts
  ts/features/bonus/common/navigation/actions.tsx
  ts/features/bonus/common/navigation/navigator.tsx
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/bonus/common/screens/BonusInformationScreen.tsx
  ts/features/bonus/common/store/reducers/__tests__/availableBonusesTypes.test.ts
  ts/features/bonus/common/store/reducers/availableBonusesTypes.ts
  ts/features/bonus/common/store/sagas/bonusSaga.ts
  ts/features/bonus/common/store/selectors/index.ts
  ts/features/bonus/common/utils/backend.ts
  ts/features/bonus/common/utils/index.ts
  ts/features/wallet/component/__test__/FeaturedCardCarousel.test.tsx
  ts/navigation/WalletNavigator.tsx
  ts/navigation/params/WalletParamsList.ts
  ts/sagas/startup.ts
  ts/screens/wallet/WalletHomeScreen.tsx
  ts/store/reducers/__tests__/allowedSnapshotScreens.test.ts
Labels: Bonus Vacanze, IO-Bonus e pagamenti, 💀 Dead code

#5407 feat: [IOCOM-922] Remove medical prescription
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  scripts/api-config.json
  ts/features/messages/__mocks__/message.ts
  ts/features/messages/components/MessageDetail/CtaBar.tsx
  ts/features/messages/components/MessageDetail/HeaderDueDateBar.tsx
  ts/features/messages/components/MessageDetail/MedicalPrescriptionAttachments.tsx
  ts/features/messages/components/MessageDetail/MedicalPrescriptionDueDateBar.tsx
  ts/features/messages/components/MessageDetail/MedicalPrescriptionIdentifiersComponent.tsx
  ts/features/messages/components/MessageDetail/MessageTitle.tsx
  ts/features/messages/components/MessageDetail/__tests__/MedicalPrescriptionAttachments.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MedicalPrescriptionDueDateBar.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MedicalPrescriptionAttachments.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MedicalPrescriptionDueDateBar.test.tsx.snap
  ts/features/messages/components/MessageDetail/index.tsx
  ts/features/messages/components/__test__/MessageDetail.test.tsx
  ts/features/messages/store/reducers/transformers.ts
  ts/features/messages/types/index.ts
  ts/features/messages/utils/messages.ts
Labels: IO-Comunicazione

#5405 chore: [IOPID-1318] Fix MP events
  ts/components/NewRemindEmailValidationOverlay.tsx
  ts/features/fastLogin/components/SecuritySuggestions.tsx
  ts/features/whatsnew/analytics/index.ts
  ts/screens/authentication/analytics/index.ts
  ts/screens/authentication/cie/CieCardReaderScreen.tsx
  ts/screens/onboarding/OnboardingCompletedScreen.tsx
Labels: IO-A&I

#5414 fix: [IOPID-1359] Fix missing email on validation blocking screen
  ts/navigation/params/CheckEmailParamsList.ts
  ts/sagas/startup/checkEmailSaga.ts
  ts/screens/profile/mailCheck/ValidateEmailScreen.tsx
Labels: IO-A&I

#5412 chore: [IOBP-510] Add `UIWalletDetailsInfo` to bypass `WalletDetailsInfo`'s `type` enum.
  package.json
  ts/features/walletV3/common/components/WalletDetailsPaymentMethodFeatures.tsx
  ts/features/walletV3/common/utils/index.ts
  ts/features/walletV3/details/screens/WalletDetailsScreen.tsx
  ts/features/walletV3/details/types/UIWalletInfoDetails.ts
  ts/features/walletV3/payment/components/WalletPaymentConfirmContent.tsx
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentAuthorization.ts
  ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
Labels: IO-Bonus e pagamenti

#5418 fix: [IOBP-515] Expiry date into new wallet details screen
  ts/features/walletV3/details/screens/WalletDetailsScreen.tsx
  ts/utils/dates.ts
Labels: IO-Bonus e pagamenti

#5402 chore: [IOPID-1301] Bump ToS version from 4.7 to 4.8""
  ts/config.ts
Labels: IO-A&I

#5417 feat: [IOPID-1391] Fix tablet compatibility alert displaying
  ts/navigation/AuthenticationNavigator.tsx
  ts/screens/authentication/LandingScreen.tsx
Labels: IO-A&I

#5420 chore: [IOPID-1298,IOPID-1396] `Main` stack navigator - `startup` saga synch
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/NavigationService.ts
  ts/sagas/startup.ts
Labels: legal-approved ⚖️ ✅, IO-A&I

#5427 fix: [IOBP-512] Wallet details with new generic error screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/details/screens/WalletDetailsScreen.tsx
Labels: IO-Bonus e pagamenti

#5399 chore: [IOBP-316] Add return to origin page after payment flow completion
  ts/features/walletV3/payment/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/walletV3/payment/store/actions/orchestration.ts
  ts/features/walletV3/payment/store/reducers/index.ts
  ts/features/walletV3/payment/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5430 fix: [IOPID-1408] Fix cdu email insert screen logic
  ts/screens/profile/CduEmailInsertScreen.tsx
Labels: Bug 🐞, IO-A&I

#5419 feat: [IOBP-514] Move authorization creation request upon payment method selection
  package.json
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentCalculateFees.test.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/walletV3/payment/screens/WalletPaymentConfirmScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickPspScreen.tsx
  ts/features/walletV3/payment/store/actions/networking.ts
  ts/features/walletV3/payment/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5423 [IOBP-518, IOBP-519] Handle payment dismissal after authorization request
  ts/features/walletV3/payment/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/walletV3/payment/screens/WalletPaymentConfirmScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickPspScreen.tsx
Labels: IO-Bonus e pagamenti

#5326 chore: [IOAPPFD0-200] Add the new Profile `About IO App` screen, remove the contextual modal
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/ProfileAboutApp.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: enhancement

#5434 feat: [IOBP-502] Disable swipe back while payment outcome showed
  ts/features/walletV3/payment/screens/WalletPaymentOutcomeScreen.tsx
Labels: IO-Bonus e pagamenti

#5421 chore: [IOBP-489] Removal of BPD references around the app
  .env.local
  .env.production
  jestGlobalExtendExpectImport.ts
  ts/config.ts
  ts/features/bonus/__mock__/availableBonuses.ts
  ts/features/bonus/bpd/analytics/index.ts
  ts/features/bonus/bpd/components/optInPaymentMethods/BpdOptInPaymentMethodsContainer.tsx
  ts/features/bonus/bpd/components/walletCardContainer/BpdCardsInWalletComponent.tsx
  ts/features/bonus/bpd/navigation/actions.ts
  ts/features/bonus/bpd/navigation/navigator.tsx
  ts/features/bonus/bpd/navigation/params.ts
  ts/features/bonus/bpd/navigation/routes.ts
  ts/features/bonus/bpd/saga/__tests__/onboarding/startOnboarding.test.ts
  ts/features/bonus/bpd/saga/index.ts
  ts/features/bonus/bpd/saga/orchestration/__tests__/activateBpdOnNewPaymentMethods.test.tsx
  ts/features/bonus/bpd/saga/orchestration/activateBpdOnNewAddedPaymentMethods.ts
  ts/features/bonus/bpd/saga/orchestration/insertIban.ts
  ts/features/bonus/bpd/saga/orchestration/onboarding/enrollToBpd.ts
  ts/features/bonus/bpd/saga/orchestration/onboarding/startOnboarding.ts
  ts/features/bonus/bpd/screens/details/BpdDetailsScreen.tsx
  ts/features/bonus/bpd/screens/details/components/summary/TransactionsGraphicalSummary.tsx
  ts/features/bonus/bpd/screens/details/components/summary/__test__/bpdSummaryComponent.test.tsx
  ts/features/bonus/bpd/screens/details/components/summary/__test__/rankingNotReady.test.tsx
  ts/features/bonus/bpd/screens/details/components/summary/ranking/SuperCashbackRankingSummary.tsx
  ts/features/bonus/bpd/screens/details/transaction/__test__/BpdTransactionsScreen.test.tsx
  ts/features/bonus/bpd/screens/details/transaction/__test__/LoadTransactions.test.tsx
  ts/features/bonus/bpd/screens/details/transaction/__test__/TransactionsUnavailable.test.tsx
  ts/features/bonus/bpd/screens/details/transaction/v2/__test__/BpdTransactionsRouterScreen.test.tsx
  ts/features/bonus/bpd/screens/details/transaction/v2/__test__/TransactionsSectionList.test.tsx
  ts/features/bonus/bpd/screens/iban/IbanCTAEditScreen.tsx
  ts/features/bonus/bpd/screens/onboarding/BpdCTAStartOnboardingScreen.tsx
  ts/features/bonus/bpd/screens/onboarding/BpdInformationScreen.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsCashbackUpdateScreen.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/OptInPaymentMethodsChoiceScreen.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/__tests__/OptInPaymentMethodsCashbackUpdateScreen.test.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/__tests__/OptInPaymentMethodsChoiceScreen.test.tsx
  ts/features/bonus/bpd/screens/optInPaymentMethods/__tests__/OptInPaymentMethodsThankYouDeleteMethodsScreen.test.ts
  ts/features/bonus/bpd/screens/optInPaymentMethods/__tests__/OptInPaymentMethodsThankYouKeepMethodsScreen.test.ts
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/bonus/common/store/reducers/__tests__/availableBonusesTypes.test.ts
  ts/features/bonus/common/store/selectors/index.ts
  ts/features/bonus/common/utils/index.ts
  ts/features/wallet/component/__test__/FeaturedCardCarousel.test.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/WalletNavigator.tsx
  ts/navigation/params/WalletParamsList.ts
  ts/sagas/startup.ts
  ts/sagas/wallet.ts
  ts/screens/wallet/WalletHomeScreen.tsx
  ts/store/middlewares/analytics.ts
  ts/store/reducers/__tests__/backendStatus.test.ts
  ts/store/reducers/backendStatus.ts
  ts/utils/internalLink.ts
Labels: Bonus Pagamenti Digitali, IO-Bonus e pagamenti

#5439 chore: [IOBP-520] Add session token request in wallet payment flow
  ts/features/walletV3/payment/api/client.ts
  ts/features/walletV3/payment/saga/index.ts
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentAuthorization.test.ts
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentCalculateFees.test.ts
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentCreateTransaction.test.ts
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentGetDetails.test.ts
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentNewSessionToken.test.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentAuthorization.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentDeleteTransaction.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetAllMethods.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetDetails.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetUserWallets.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentNewSessionToken.ts
  ts/features/walletV3/payment/store/__tests__/store.test.ts
  ts/features/walletV3/payment/store/actions/networking.ts
  ts/features/walletV3/payment/store/reducers/index.ts
  ts/features/walletV3/payment/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5444 chore: [IOBP-517] Remove unnecessary gallery permission on iOS
  ts/utils/permission.ts
Labels: IO-Bonus e pagamenti

#5426 feat: [IOCOM-980] Add `Timeline` component
  ts/features/pn/components/Timeline.tsx
  ts/features/pn/components/__test__/Timeline.test.tsx
  ts/features/pn/components/__test__/__snapshots__/Timeline.test.tsx.snap
Labels: IO-Comunicazione

#5443 chore: [IOBP-521] Add transaction status polling before PSP selection screen
  ts/features/walletV3/payment/hooks/useOnTransactionActivationEffect.tsx
  ts/features/walletV3/payment/saga/index.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetTransactionInfo.ts
  ts/features/walletV3/payment/screens/WalletPaymentConfirmScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickPspScreen.tsx
  ts/features/walletV3/payment/store/actions/networking.ts
  ts/features/walletV3/payment/store/reducers/index.ts
  ts/features/walletV3/payment/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5440 feat: [IOCOM-866] Display tags in the header of a SEND message
  locales/en/index.yml
  locales/it/index.yml
  ts/features/pn/__mocks__/message.ts
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/__test__/MessageDetails.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
Labels: IO-Comunicazione

#5436 chore: [IOAPPX-219] Remove unused types dependencies
  package.json
  yarn.lock
Labels: 💀 Dead code

#5447 chore: [IOAPPX-227] Remove abort-controller dependency
  package.json
  yarn.lock
Labels: 💀 Dead code

#5460 chore: [IOBP-481] Remove DS feature flag to show new barcode scan screen
  ts/screens/wallet/WalletHomeScreen.tsx
Labels: IO-Bonus e pagamenti

#5445 chore: [IOPID-1395] Update FeatureInfo font size
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/screens/authentication/NewOptInScreen.tsx
  ts/screens/onboarding/UnlockAccessScreen.tsx
  yarn.lock
Labels: IO-A&I

#5471 chore: [IOAPPX-240] Replace legacy `FooterWithButtons` in the `ShareDataScreen`
  ts/screens/profile/ShareDataScreen.tsx
Labels: Design System

#5442 chore: [IOBP-493,IOBP-491] Cleanup after BPD and BV removal
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/config.ts
  ts/features/bonus/__mock__/mockData.ts
  ts/features/bonus/cdc/saga/index.ts
  ts/features/bonus/common/store/actions/availableBonusesTypes.ts
  ts/features/bonus/common/store/sagas/bonusSaga.ts
  ts/features/bonus/common/store/sagas/handleLoadAllBonusActivationSaga.ts
  ts/features/bonus/common/utils/backend.ts
  ts/sagas/startup.ts
  ts/sagas/wallet.ts
Labels: Bonus Pagamenti Digitali, Bonus Vacanze, IO-Bonus e pagamenti, 💀 Dead code

#5422 chore(Cross): [IOAPPX-213] Remove pivotal from danger and changelog scripts
  Dangerfile.ts
  package.json
  patches/danger-plugin-digitalcitizenship+0.3.1.patch
  patches/patches.md
  scripts/changelog/add_jira_stories.js
  scripts/ts/common/jiraTicket/index.ts
  scripts/ts/common/jiraTicket/types.ts
  scripts/ts/common/ticket/pivotal/types.d.ts
  scripts/ts/common/ticket/types.ts
  scripts/ts/danger/__mocks__/genericTicket.ts
  scripts/ts/danger/__tests__/updatePrTitle.test.ts
  scripts/ts/danger/commentPr.ts
  scripts/ts/danger/updatePrTitle.tsx
  scripts/ts/danger/updatePrTitleForChangelog.tsx
  scripts/ts/danger/utils/__mocks__/storyMock.ts
  scripts/ts/danger/utils/__tests__/changelog.test.ts
  scripts/ts/danger/utils/changelog.ts
  scripts/ts/danger/utils/titleParser.tsx
  yarn.lock
Labels: 💀 Dead code, Cross

#5446 chore: [IOPID-1372,IOPID-1373] Add remote ToS management
  package.json
  ts/config.ts
  ts/features/tos/index.ts
  ts/features/tos/store/selectors/__tests__/index.ts
  ts/features/tos/store/selectors/index.ts
  ts/sagas/profile.ts
  ts/sagas/startup/__tests__/checkAcceptedTosSaga.test.tsx
  ts/sagas/startup/checkAcceptedTosSaga.ts
  ts/screens/onboarding/OnboardingTosScreen.tsx
  ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx
  ts/screens/profile/__test__/TosScreen.test.tsx
  ts/store/reducers/__mock__/backendStatus.ts
Labels: IO-A&I
