Repository pagopa/io-app, pull requests merged in 2024-08, with the labels that each got.

#6080 fix(Cross): [IOAPPX-361] Runtime crash on Android devices without custom tabs support
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Cross

#6073 fix(IT Wallet): [SIW-1443] Reset persisted ITW store after logout
  ts/boot/configureStoreAndPersistor.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/credentials/store/reducers/index.ts
  ts/features/itwallet/identification/store/reducers/index.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/lifecycle/store/reducers/index.ts
  ts/store/reducers/index.ts
Labels: IT Wallet

#6075 fix(Cross): [IOAPPX-363] Discard activity state persistence in Android
  android/app/src/main/java/it/pagopa/io/app/MainActivity.java
Labels: Cross

#6059 fix: [IOBP-796] Payment method details scroll with new header second level
  ts/features/payments/details/components/PaymentsMethodDetailsBaseScreenComponent.tsx
  ts/features/payments/details/navigation/navigator.tsx
Labels: IO-Bonus e pagamenti

#6069 fix: CTA bottom margin inside `RemoveAccountDetailScreen`
  ts/screens/profile/RemoveAccountDetailsScreen.tsx
Labels: IO-A&I

#6061 feat: [IOPAE-1311] Bottom sheet displayed when the user taps on the settings icon in the services section
  locales/en/index.yml
  locales/it/index.yml
  ts/features/services/home/hooks/useServicesHomeBottomSheet.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
Labels: IO - Enti & Servizi

#6041 chore: [IOCOM-1628] FIMS FastLogin handling
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/singleSignOn/saga/handleFimsAbortOrCancel.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/singleSignOn/saga/handleFimsResourcesDeallocation.ts
  ts/features/fims/singleSignOn/saga/index.ts
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/fims/singleSignOn/store/selectors/index.ts
  ts/features/fims/singleSignOn/utils/index.ts
Labels: IO-Comunicazione

#6083 FIMS verbose debug errorScreen
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/singleSignOn/store/actions/index.ts
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/fims/singleSignOn/store/selectors/index.ts
Labels: IO-Comunicazione

#6084 fix(IT Wallet): [SIW-1459] Issuer name and logo in trust issuer screen
  img/features/itWallet/issuer/IPZS.png
  img/features/itWallet/issuer/IPZS@2x.png
  img/features/itWallet/issuer/IPZS@3x.png
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
Labels: IT Wallet

#6070 fix: [IOBP-797] Hide total amount label if total amount not present
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
  ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#6071 chore(IT Wallet): [SIW-1427] Filter empty claims when displaying a credential
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
Labels: IT Wallet

#6077 chore(IT Wallet): [SIW-1350] Handle refresh token during API calls to `io-backend`
  ts/features/itwallet/api/client.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/guards.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6089 chore: [IOPID-2067,IOPID-2068] Cie Accessibility fix
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/authentication/cie/CiePinScreen.tsx
Labels: a11y, IO-A&I

#6090 chore(Cross): update `codiceIPA` from `PCM` to `5N2TR557`
  publiccode.yml
Labels: Cross

#6092 chore: [IOPID-2007] Edit latest copy referred to profile
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/sagas/startup.ts
Labels: IO-A&I

#6093 fix: [IOBP-811] Payment manual input a11y focus crash on android
  ts/features/payments/checkout/screens/WalletPaymentInputFiscalCodeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentInputNoticeNumberScreen.tsx
Labels: IO-Bonus e pagamenti

#6094 [IOCOM-1675, IOCOM-1677] Handling of required App Update for FIMS
  package.json
  ts/features/fims/history/screens/HistoryScreen.tsx
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/store/reducers/backendStatus.ts
Labels: IO-Comunicazione

#5954 chore(Cross): [IOAPPX-343,IOAPPX-311] Add `react-native-skia` library + Dynamic header background (under the new Experimental Lab category)
  ios/Podfile.lock
  jest-e2e.config.js
  jest.config.js
  jest.config.no.timezone.js
  package.json
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/core/DSDynamicBackground.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  yarn.lock
Labels: Design System, Cross, Experimental lab ✨, code review needed 💻📱

#6103 chore(Cross): [IOAPPX-343,IOAPPX-311] Add `react-native-skia` library + Dynamic header background (under the new Experimental Lab category)"
  ios/Podfile.lock
  jest-e2e.config.js
  jest.config.js
  jest.config.no.timezone.js
  package.json
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/core/DSDynamicBackground.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  yarn.lock
Labels: Cross

#6098 fix: [IOPID-2132] Centring the name of the user in the identification modal
  ts/screens/modal/IdentificationModal.tsx
Labels: Bug 🐞, IO-A&I

#5973 feat: [PE-616] Change labels in CGN Partner list screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
Labels: Carta Giovani Nazionale

#5991 feat: [PE-622] Change labels in CGN KO pages
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/screens/activation/CgnActivationLoadingScreen.tsx
Labels: Carta Giovani Nazionale

#6104 chore(IT Wallet): [SIW-1341] Add eID issuance machine unit tests
  ts/features/itwallet/machine/eid/__tests__/machine.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6085 chore(IT Wallet): [SIW-1465] Fix header in eID preview screen
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
Labels: IT Wallet

#5992 feat: [PE-628] CGN - deactivate button on expired card detail screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/detail/CgnUnsubscribe.tsx
  ts/features/bonus/cgn/hooks/useCgnUnsubscribe.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
Labels: Carta Giovani Nazionale

#6115 feat: [IOCOM-1110] Home messages analytics events
  ts/features/messages/__mocks__/messages.ts
  ts/features/messages/analytics/index.ts
  ts/features/messages/components/Home/EmptyList.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/PagerViewContainer.tsx
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__tests__/EmptyList.test.tsx
  ts/features/messages/components/Home/__tests__/MessageList.test.tsx
  ts/features/messages/components/Home/__tests__/PagerViewContainer.test.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/saga/handleLoadNextPageMessages.ts
  ts/features/messages/saga/handleLoadPreviousPageMessages.ts
  ts/features/messages/saga/handleReloadAllMessages.ts
  ts/features/messages/saga/handleUpsertMessageStatusAttributes.ts
  ts/features/messages/screens/MessagesSearchScreen.tsx
  ts/features/messages/screens/searchUtils.ts
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/__tests__/messageGetStatus.test.ts
  ts/features/messages/store/reducers/__tests__/payments.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
  ts/features/pushNotifications/utils/configurePushNotification.ts
  ts/store/middlewares/analytics.ts
Labels: IO-Comunicazione

#6116 feat: [IOCOM-1169,IOCOM-1601] Message details analytics events
  ts/features/messages/analytics/index.ts
  ts/features/messages/components/MessageDetail/MessageDetailsPayment.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsPaymentButton.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsStickyFooter.tsx
  ts/features/messages/components/MessageDetail/MessagePaymentItem.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsPayment.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsPaymentButton.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsStickyFooter.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessagePaymentItem.test.tsx
  ts/features/messages/components/MessageDetail/detailsUtils.ts
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/messages/saga/handleLoadMessageData.ts
  ts/features/messages/saga/handlePaymentStatusForAnalyticsTracking.ts
  ts/features/messages/saga/handlePaymentUpdateRequests.ts
  ts/features/messages/saga/handleThirdPartyMessage.ts
  ts/features/messages/saga/index.ts
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/screens/MessageRouterScreen.tsx
  ts/features/messages/screens/__tests__/MessageRouterScreen.test.tsx
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/__tests__/messageGetStatus.test.ts
  ts/features/messages/store/reducers/__tests__/payments.test.ts
  ts/features/messages/store/reducers/messageGetStatus.ts
  ts/features/messages/utils/__tests__/index.test.ts
  ts/features/messages/utils/index.ts
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePaymentBottomSheet.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/features/pn/components/__test__/MessageFooter.test.tsx
  ts/features/pn/components/__test__/MessagePaymentBottomSheet.test.tsx
  ts/features/pn/components/__test__/MessagePayments.test.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/reducers/__test__/payments.test.ts
  ts/features/pn/store/sagas/watchPaymentStatusSaga.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/pn/utils/__tests__/index.test.ts
  ts/features/pn/utils/index.ts
Labels: IO-Comunicazione

#6121 fix: [IOCOM-1687] Fix a race condition on message details loading
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/store/reducers/archiving.ts
Labels: IO-Comunicazione

#6057 chore: [IOBP-800] Replace from ultra wide camera to wide camera in barcode screen
  ts/features/barcode/hooks/useIOBarcodeCameraScanner.tsx
Labels: IO-Bonus e pagamenti

#6109 fix: [IOBP-810] Map event tracking payment outcome unhandled
  ts/features/payments/checkout/analytics/index.ts
Labels: IO-Bonus e pagamenti

#6124 fix: [IOPID-2151] Fix session refresh
  ts/features/fastLogin/store/actions/sessionRefreshActions.ts
  ts/features/fastLogin/store/reducers/sessionRefreshReducer.ts
  ts/features/fastLogin/store/selectors/index.ts
  ts/features/payments/onboarding/components/WalletOnboardingPaymentMethodsList.tsx
  ts/sagas/startup/refreshSessionTokenAfterIdentificationSuccessSaga.ts
  ts/sagas/startup/watchApplicationActivitySaga.ts
  ts/screens/modal/IdentificationModal.tsx
Labels: IO-A&I

#6056 chore: [IOBP-795] Add payment method onboarding contextual help
  ts/features/payments/onboarding/screens/PaymentsOnboardingSelectMethodScreen.tsx
Labels: IO-Bonus e pagamenti

#6100 chore: [IOBP-828] Receipts Micro-copy improvements
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#6106 fix: [IOBP-798,IOBP-824] Show back button and rename tracking events for no payments method available screen
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
Labels: IO-Bonus e pagamenti

#6127 feat: [IOPLT-380] Create release from tag and upload artifacts
  .github/workflows/release.yml
Labels: code review needed 💻📱

#6131 chore: Fix for failing Android build on react-native-fingerprint-scanner dependency
  package.json
  patches/patches.md
  patches/react-native-fingerprint-scanner+6.0.0.patch
  yarn.lock
Labels: IO-Comunicazione

#6130 chore: [IOCOM-1671,IOCOM-1670,IOCOM-1688] Fims history screen error handling
  assets/FimsSwager.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/history/components/FimsHistoryEmptyContent.tsx
  ts/features/fims/history/components/FimsHistoryHeaderComponent.tsx
  ts/features/fims/history/components/FimsHistoryKoScreen.tsx
  ts/features/fims/history/components/FimsHistoryNonEmptyContent.tsx
  ts/features/fims/history/saga/handleGetFimsHistorySaga.ts
  ts/features/fims/history/screens/HistoryScreen.tsx
  ts/features/fims/history/store/actions/index.ts
  ts/features/fims/history/store/reducer/index.ts
  ts/features/fims/history/store/selectors/index.ts
Labels: IO-Comunicazione

#6119 feat: [IOPAE-1316] Display an informative message if the search does not return results
  locales/en/index.yml
  locales/it/index.yml
  ts/features/services/common/components/EmptyState.tsx
  ts/features/services/search/screens/SearchScreen.tsx
Labels: IO-Enti e Servizi

#6101 feat(IT Wallet): [SIW-1458] Persist Wallet Instance after logout
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/configureStoreAndPersistor.ts
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/credentials/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/credentials/store/reducers/index.ts
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/issuance/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/lifecycle/saga/handleWalletInstanceResetSaga.ts
  ts/features/itwallet/lifecycle/saga/index.ts
  ts/features/itwallet/lifecycle/screens/ItwIdentityNotMatchingScreen.tsx
  ts/features/itwallet/lifecycle/store/actions/index.ts
  ts/features/itwallet/lifecycle/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/lifecycle/store/reducers/index.ts
  ts/features/itwallet/machine/eid/guards.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/playgrounds/components/ItwLifecycleSection.tsx
  ts/sagas/startup.ts
  ts/sagas/startup/checkItWalletIdentitySaga.ts
  ts/store/reducers/index.ts
Labels: IT Wallet

#6136 chore: [IOCOM-1678] FIMS history single listItem error state
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/history/components/FimsHistoryListItem.tsx
Labels: IO-Comunicazione

#6079 chore: [IOCOM-1642] Remove legacy FIMS code
  .env.local
  .env.production
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/fimsLegacy/components/FimsWebView.tsx
  ts/features/fimsLegacy/components/WebviewErrorComponent.tsx
  ts/features/fimsLegacy/navigation/navigator.tsx
  ts/features/fimsLegacy/navigation/params.ts
  ts/features/fimsLegacy/navigation/routes.ts
  ts/features/fimsLegacy/screens/FimsWebviewScreen.tsx
  ts/features/fimsLegacy/types/FimsWebviewParams.ts
  ts/features/fimsLegacy/utils/placeholder
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/store/reducers/backendStatus.ts
  ts/types/WebviewMessage.ts
  ts/types/__tests__/webviewMessage.test.ts
  ts/utils/cookieManager.ts
  ts/utils/internalLink.ts
  ts/utils/webview.ts
Labels: IO-Comunicazione

#6027 chore(Cross): [IOAPPX-353] Add deprecation note to all the legacy typographic styles
  ts/components/core/fonts.ts
  ts/components/core/typography/BaseTypography.tsx
  ts/components/core/typography/Body.tsx
  ts/components/core/typography/Factory.tsx
  ts/components/core/typography/H1.tsx
  ts/components/core/typography/H2.tsx
  ts/components/core/typography/H3.tsx
  ts/components/core/typography/H4.tsx
  ts/components/core/typography/H5.tsx
  ts/components/core/typography/Label.tsx
  ts/components/core/typography/LabelHeader.tsx
  ts/components/core/typography/LabelSmall.tsx
  ts/components/core/typography/Link.tsx
  ts/components/core/typography/Monospace.tsx
  ts/components/ui/TabItem.tsx
  ts/components/ui/__test__/TabItem.test.tsx
  ts/components/ui/__test__/__snapshots__/TabItem.test.tsx.snap
Labels: Design System, Cross, code review needed 💻📱
