Repository pagopa/io-app, pull requests merged in 2024-05, with the labels that each got.

#5710 feat: [IOPID-1539,IOPID-1784] - Integrate new DS in UpdateAppModal
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/OperationResultScreenContent.tsx
  ts/screens/modal/UpdateAppModal.tsx
Labels: IO-A&I

#5730 fix: [IOBP-554] Removed A11y override into transaction operation details
  ts/features/payments/transaction/screens/PaymentsTransactionOperationDetails.tsx
Labels: a11y, IO-Bonus e pagamenti

#5731 chore: [IOPAE-1119] Institution's services: actions, reducer, selectors and saga
  ts/features/services/common/api/__mocks__/client.ts
  ts/features/services/common/saga/index.ts
  ts/features/services/common/store/actions/index.ts
  ts/features/services/common/store/reducers/index.ts
  ts/features/services/institution/saga/__tests__/handleFindServices.test.ts
  ts/features/services/institution/saga/handleFindServices.ts
  ts/features/services/institution/saga/index.ts
  ts/features/services/institution/store/actions/index.ts
  ts/features/services/institution/store/reducers/__tests__/store.test.ts
  ts/features/services/institution/store/reducers/index.ts
Labels: IO - Enti & Servizi

#5726 fix: [IOPID-1810] Email validation edge case on onboarding flow
  ts/sagas/startup/__tests__/checkProfileEmailSaga.test.tsx
  ts/sagas/startup/checkAcknowledgedEmailSaga.ts
Labels: IO-A&I

#5714 feat: [IOPID-1505,IOPID-1776] New DS on ToS screen and add MP events
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/TosWebviewComponent.tsx
  ts/components/TosWebviewErrorComponent.tsx
  ts/components/__tests__/TosWebviewComponent.test.tsx
  ts/components/__tests__/__snapshots__/TosWebviewComponent.test.tsx.snap
  ts/navigation/OnboardingNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/screens/authentication/analytics/index.ts
  ts/screens/onboarding/OnboardingTosScreen.tsx
  ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx
  ts/screens/profile/TosScreen.tsx
Labels: IO-A&I

#5719 chore: [IOPID-1743] Change CDN urls
  scripts/check_urls/check_urls.py
  ts/config.ts
  ts/features/design-system/core/DSListItems.tsx
  ts/features/design-system/core/DSLogos.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
Labels: help wanted

#5736 chore: [IOPAE-1104] Featured Items: actions, reducer, selectors and saga
  ts/features/services/common/api/__mocks__/client.ts
  ts/features/services/home/saga/__tests__/handleGetFeaturedItems.test.ts
  ts/features/services/home/saga/handleGetFeaturedItems.ts
  ts/features/services/home/saga/index.ts
  ts/features/services/home/store/actions/index.ts
  ts/features/services/home/store/reducers/__tests__/store.test.ts
  ts/features/services/home/store/reducers/index.ts
Labels: IO - Enti & Servizi

#5722 chore: [IOBP-629] Add onboarding payment method when not found any
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/components/CheckoutPaymentMethodsList.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
  ts/features/payments/checkout/types/PaymentOutcomeEnum.ts
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
  ts/features/payments/onboarding/store/actions/index.ts
  ts/features/payments/onboarding/store/reducers/index.ts
  ts/features/payments/onboarding/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5740 feat: [IOPID-1505] Add title in profile ToS screen
  ts/screens/profile/TosScreen.tsx
Labels: IO-A&I

#5721 feat: [IOCOM-1285] Remote content banner, new DS
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/core/typography/ComposedBodyFromArray.tsx
  ts/components/core/typography/__test__/ComposedBodyFromArray.test.tsx
  ts/components/core/typography/__test__/__snapshots__/ComposedBodyFromArray.test.tsx.snap
  ts/components/screens/OperationResultScreenContent.tsx
  ts/features/design-system/core/DSScreenOperationResult.tsx
  ts/features/messages/components/MessageDetail/LegacyRemoteContentBanner.tsx
  ts/features/messages/components/MessageDetail/RemoteContentBanner.tsx
  ts/features/messages/components/MessageDetail/__tests__/RemoteContentBanner.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/RemoteContentBanner.test.tsx.snap
  ts/features/messages/components/MessageDetail/index.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/screens/profile/mailCheck/EmailAlreadyTakenScreen.tsx
  ts/screens/profile/mailCheck/ValidateEmailScreen.tsx
  yarn.lock
Labels: IO-Comunicazione

#5735 feat: [IOPID-1812] Remove the CTA from `CiePinScreen`
  package.json
  ts/screens/authentication/cie/CiePinScreen.tsx
  yarn.lock
Labels: IO-A&I

#5727 feat: [IOCOM-884] Green pass relevant screens, new DS
  ts/components/ui/Markdown/LoadingSkeleton.tsx
  ts/components/ui/Markdown/Markdown.tsx
  ts/features/euCovidCert/components/EUCovidContext.tsx
  ts/features/euCovidCert/components/EuCovidCertHeader.tsx
  ts/features/euCovidCert/components/EuCovidCertLearnMoreLink.tsx
  ts/features/euCovidCert/components/MarkdownHandleCustomLink.tsx
  ts/features/euCovidCert/components/__test__/__snapshots__/EuCovidCertHeader.test.tsx.snap
  ts/features/euCovidCert/navigation/navigator.tsx
  ts/features/euCovidCert/screens/BaseEuCovidCertificateLayout.tsx
  ts/features/euCovidCert/screens/EuCovidCertExpiredScreen.tsx
  ts/features/euCovidCert/screens/EuCovidCertLoadingScreen.tsx
  ts/features/euCovidCert/screens/EuCovidCertRevokedScreen.tsx
  ts/features/euCovidCert/screens/EuCovidCertificateRouterScreen.tsx
  ts/features/euCovidCert/screens/__test__/EUCovidCertExpiredScreen.test.tsx
  ts/features/euCovidCert/screens/__test__/EUCovidCertRevokedScreen.test.tsx
  ts/features/euCovidCert/screens/__test__/EUCovidCertValidScreen.test.tsx
  ts/features/euCovidCert/screens/__test__/EuCovidCertificateRouterScreen.test.tsx
  ts/features/euCovidCert/screens/ko/EuCovidCertGenericErrorKoScreen.tsx
  ts/features/euCovidCert/screens/ko/EuCovidCertNotFoundKoScreen.tsx
  ts/features/euCovidCert/screens/ko/EuCovidCertNotOperationalKoScreen.tsx
  ts/features/euCovidCert/screens/ko/EuCovidCertTemporarilyNotAvailableKoScreen.tsx
  ts/features/euCovidCert/screens/ko/EuCovidCertWrongFormatKoScreen.tsx
  ts/features/euCovidCert/screens/ko/__tests__/EuCovidCertNotFoundKoScreen.test.tsx
  ts/features/euCovidCert/screens/ko/__tests__/EuCovidCertWrongFormatKoScreen.test.tsx
  ts/features/euCovidCert/screens/valid/EuCovidCertMarkdownDetailsScreen.tsx
  ts/features/euCovidCert/screens/valid/EuCovidCertQrCodeFullScreen.tsx
  ts/features/euCovidCert/screens/valid/EuCovidCertValidScreen.tsx
  ts/features/messages/components/MessageDetail/OrganizationHeader.tsx
  ts/features/messages/store/reducers/paginatedById.ts
Labels: IO-Comunicazione

#5668 feat: [PE-550] Revamp CGN Categories/All merchants screen with new DS
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
  ts/features/bonus/cgn/navigation/actions.ts
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/cgn/navigation/params.ts
  ts/features/bonus/cgn/navigation/routes.ts
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantCategoriesListScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
Labels: Carta Giovani Nazionale

#5617 chore: [PE-562] Refactor bonus information screen to use new DS components
  package.json
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
Labels: Carta Giovani Nazionale

#5741 chore: [IOPID-1828] Update DS version and idp list fallback
  package.json
  ts/utils/idps.ts
  yarn.lock
Labels: IO-A&I

#5693 feat: [PE-551] Category detail screen
  ts/features/bonus/cgn/components/merchants/CgnMerchantCategoryItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsTabsScreen.tsx
  ts/features/bonus/cgn/utils/filters.ts
Labels: Carta Giovani Nazionale

#5729 feat(IT Wallet): [SIW-979] Add issuing authentication mode selection screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/screens/profile/playgrounds/ItwPlayground.tsx
Labels: IT Wallet

#5739 chore: [IOPAE-1120] Add Institution Services screen
  locales/en/index.yml
  locales/it/index.yml
  ts/components/RegionServiceWebView.tsx
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/services/common/components/ServicesHeader.tsx
  ts/features/services/common/components/ServicesHeaderSection.tsx
  ts/features/services/common/components/__tests__/ServicesHeader.test.tsx
  ts/features/services/common/components/__tests__/ServicesHeaderSection.test.tsx
  ts/features/services/common/components/__tests__/__snapshots__/ServicesHeader.test.tsx.snap
  ts/features/services/common/components/__tests__/__snapshots__/ServicesHeaderSection.test.tsx.snap
  ts/features/services/common/navigation/navigator.tsx
  ts/features/services/common/navigation/params.ts
  ts/features/services/common/navigation/routes.ts
  ts/features/services/common/utils/index.ts
  ts/features/services/details/components/ServiceDetailsMetadata.tsx
  ts/features/services/details/components/ServiceDetailsPreferences.tsx
  ts/features/services/details/components/ServiceDetailsTosAndPrivacy.tsx
  ts/features/services/details/screens/ServiceDetailsScreen.tsx
  ts/features/services/home/components/ServicesHomeIntitutionList.tsx
  ts/features/services/institution/components/InstitutionServicesScreenComponent.tsx
  ts/features/services/institution/components/ServiceListItemSkeleton.tsx
  ts/features/services/institution/hooks/useServicesFetcher.tsx
  ts/features/services/institution/saga/__tests__/handleFindInstitutionServices.test.ts
  ts/features/services/institution/saga/handleFindInstitutionServices.ts
  ts/features/services/institution/saga/index.ts
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
  ts/features/services/institution/screens/__tests__/InstitutionServicesScreen.test.tsx
  ts/screens/services/LegacyServiceDetailsScreen.tsx
  ts/screens/services/ServicesHomeScreen.tsx
  ts/screens/services/ServicesWebviewScreen.tsx
  ts/store/actions/navigation.ts
  ts/store/reducers/authentication.ts
Labels: IO - Enti & Servizi

#5742 fix(Cross): [IOAPPX-290] Fix `detox` iOS 17 regression
  patches/detox+19.13.0.patch
  patches/patches.md
Labels: Cross

#5738 feat: [PE-552] Revamp CGN merchant details screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx
  ts/features/bonus/cgn/components/merchants/CgnAddressListItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsDiscountItem.tsx
  ts/features/bonus/cgn/components/merchants/CgnModuleDiscount.tsx
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
Labels: Carta Giovani Nazionale

#5745 chore(IT Wallet): [SIW-1089] Add NFC enable state check saga
  ts/features/common/store/reducers/index.ts
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/identification/saga/__tests__/handleNfcEnabledSaga.test.ts
  ts/features/itwallet/identification/saga/handleNfcEnabledSaga.ts
  ts/features/itwallet/identification/saga/index.ts
  ts/features/itwallet/identification/store/actions/index.ts
  ts/features/itwallet/identification/store/reducers/index.ts
  ts/features/itwallet/identification/store/selectors/index.ts
  ts/sagas/startup.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/types.ts
Labels: IT Wallet

#5651 feat: [PE-549] Adopt DS on CGN detail screen
  img/bonus/cgn/card_mask.png
  img/bonus/cgn/cgn_logo.png
  img/bonus/cgn/eyca_logo.png
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/detail/CardSvgPayload.ts
  ts/features/bonus/cgn/components/detail/CgnCardComponent.tsx
  ts/features/bonus/cgn/components/detail/CgnOwnershipInformation.tsx
  ts/features/bonus/cgn/components/detail/CgnStatusDetail.tsx
  ts/features/bonus/cgn/components/detail/CgnUnsubscribe.tsx
  ts/features/bonus/cgn/components/detail/__test__/CgnCardComponent.test.tsx
  ts/features/bonus/cgn/components/detail/__test__/CgnStatusDetail.test.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaDetailComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaErrorComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaInformationComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaPendingComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaStatusDetailsComponent.tsx
  ts/features/bonus/cgn/components/detail/eyca/__test__/EycaDetailComponent.test.tsx
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
Labels: Carta Giovani Nazionale

#5743 chore(Cross): [IOAPPX-289] Update DS with new components
  ts/components/LabelledItem/index.tsx
  ts/components/Pinpad/InputPlaceholder.tsx
  ts/components/Pinpad/Placeholders.tsx
  ts/components/wallet/PaymentsHistoryList.tsx
  ts/components/wallet/SlidedContentComponent.tsx
  ts/features/design-system/components/DSAssetViewerBox.tsx
  ts/features/design-system/core/DSBadges.tsx
  ts/features/design-system/core/DSLoaders.tsx
  ts/features/design-system/core/DSModules.tsx
  ts/features/design-system/core/DSOTPInput.tsx
  ts/features/design-system/core/DSStepper.tsx
  ts/features/design-system/core/DSTabNavigation.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/screens/authentication/InvalidNfcConnectionScreen.tsx
Labels: Design System, Cross

#5733 feat(IT Wallet): [SIW-1090] Add NFC enable instructions screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationNfcInstructionsScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
Labels: IT Wallet

#5759 chore: [IOBP-630] Changed `bundleName` to `pspBusinessName` from the new payment flow
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/common/utils/index.ts
Labels: IO-Bonus e pagamenti

#5761 chore: [PE-596] Changed CGN locales from categories list and merchant details screen
  locales/en/index.yml
  locales/it/index.yml
Labels: Carta Giovani Nazionale

#5762 chore: [IOPID-1829] Change button on ToS screen
  ts/components/TosWebviewComponent.tsx
  ts/components/TosWebviewErrorComponent.tsx
  ts/screens/onboarding/OnboardingTosScreen.tsx
  ts/screens/profile/TosScreen.tsx
Labels: IO-A&I

#5765 chore: [IOPAE-1144] Featured Institutions, Featured Services: actions, reducer, selectors and saga
  ts/features/services/common/api/__mocks__/client.ts
  ts/features/services/home/saga/__tests__/handleGetFeaturedInstitutions.test.ts
  ts/features/services/home/saga/__tests__/handleGetFeaturedServices.test.ts
  ts/features/services/home/saga/handleGetFeaturedInstitutions.ts
  ts/features/services/home/saga/handleGetFeaturedServices.ts
  ts/features/services/home/saga/index.ts
  ts/features/services/home/store/actions/index.ts
  ts/features/services/home/store/reducers/__tests__/store.test.ts
  ts/features/services/home/store/reducers/index.ts
Labels: IO - Enti & Servizi

#5764 chore: [IOPAE-1146] Search institutions: actions, reducer, selectors and saga
  ts/features/services/common/saga/index.ts
  ts/features/services/common/store/actions/index.ts
  ts/features/services/common/store/reducers/index.ts
  ts/features/services/search/saga/__tests__/handleFindInstitutions.test.ts
  ts/features/services/search/saga/handleFindInstitutions.ts
  ts/features/services/search/saga/index.ts
  ts/features/services/search/store/actions/index.ts
  ts/features/services/search/store/reducers/__tests__/store.test.ts
  ts/features/services/search/store/reducers/index.ts
Labels: IO - Enti & Servizi

#5748 feat: [IOPID-1723] Revamp EIC PIN Errors with the new DS
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/navigation/AuthenticationNavigator.tsx
  ts/screens/authentication/__tests__/cie/CieWrongCiePinScreen.test.tsx
  ts/screens/authentication/cie/CieCardReaderScreen.tsx
  ts/screens/authentication/cie/CiePinLockedTemporarilyScreen.tsx
  ts/screens/authentication/cie/CieWrongCiePinScreen.tsx
Labels: IO-A&I

#5754 fix: [PE-587,PE-589,PE-591] CGN revamp fixes
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantCategoriesListScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
Labels: Bug 🐞, Carta Giovani Nazionale

#5767 chore: [IOCOM-1357] Entry point, structure and first half of saga for FIMS implementation
  ts/features/common/store/reducers/index.ts
  ts/features/fims/__mocks__/mockFIMSCallbacks.ts
  ts/features/fims/__mocks__/mockFIMSSaga.ts
  ts/features/fims/navigation/index.tsx
  ts/features/fims/navigation/navigator.tsx
  ts/features/fims/navigation/params.ts
  ts/features/fims/navigation/routes.ts
  ts/features/fims/saga/index.tsx
  ts/features/fims/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/store/actions/index.ts
  ts/features/fims/store/reducers/index.ts
  ts/features/fimsLegacy/components/FimsWebView.tsx
  ts/features/fimsLegacy/components/WebviewErrorComponent.tsx
  ts/features/fimsLegacy/navigation/navigator.tsx
  ts/features/fimsLegacy/navigation/params.ts
  ts/features/fimsLegacy/navigation/routes.ts
  ts/features/fimsLegacy/screens/FimsWebviewScreen.tsx
  ts/features/fimsLegacy/types/FimsWebviewParams.ts
  ts/features/fimsLegacy/utils/placeholder
  ts/features/messages/utils/messages.ts
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
  ts/store/actions/types.ts
  ts/utils/internalLink.ts
Labels: IO-Comunicazione

#5623 chore(Cross): [IOAPPX-265] Add a new debug screen with the sticky behaviour of the action block
  ts/features/design-system/core/DSStickyMessageCTAs.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
Labels: Design System, Cross

#5758 fix: [IOBP-638] Add nested scroll enabled flag on the current payment webview modal
  ts/components/wallet/PayWebViewModal.tsx
Labels: Bug 🐞, IO-Bonus e pagamenti

#5766 feat: [IOCOM-1391] Flag to enable Messages Home with the new DS
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/features/messages/screens/LegacyMessagesHomeScreen.tsx
  ts/features/messages/screens/MessagesHomeScreen.tsx
  ts/features/messages/screens/__tests__/LegacyMessagesHomeScreen.test.tsx
  ts/features/messages/store/reducers/messagesStatus.ts
  ts/navigation/TabNavigator.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IO-Comunicazione

#5774 fix: [IOPAE-1164] Fix infinite scroll in `InstitutionServicesScreen`
  ts/features/services/institution/components/InstitutionServicesScreenComponent.tsx
  ts/features/services/institution/components/ServiceListItemSkeleton.tsx
  ts/features/services/institution/components/ServiceListSkeleton.tsx
  ts/features/services/institution/hooks/useServicesFetcher.tsx
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
Labels: Bug 🐞, IO - Enti & Servizi

#5752 feat(IT Wallet): [SIW-980] Add eID issuing IDP selection screen
  ts/features/itwallet/identification/screens/ItwIdentificationIdpSelectionScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
Labels: IT Wallet

#5763 chore(Cross): [IOAPPX-295] Remove nested navigator from DS section
  ts/components/DebugInfoOverlay.tsx
  ts/components/ui/AlertModal.tsx
  ts/features/design-system/components/DesignSystemScreen.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
Labels: Design System, Cross

#5757 [IOCOM-1370, IOCOM-1371] Selectable service name in message details (both standard and SEND), new DS
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/components/MessageDetail/OrganizationHeader.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsHeader.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/OrganizationHeader.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/OrganizationHeader.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
Labels: IO-Comunicazione

#5775 feat: [IOPID-1725] New DS on CIE certificates KO screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/navigation/AuthenticationNavigator.tsx
  ts/screens/authentication/cie/CieExpiredOrInvalidScreen.tsx
Labels: IO-A&I

#5770 feat: [IOCOM-823] Chips for Inbox and Archived messages on new DS Messages' Home
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/PagerViewContainer.tsx
  ts/features/messages/components/Home/TabNavigationContainer.tsx
  ts/features/messages/components/Home/__tests__/Item.test.tsx
  ts/features/messages/components/Home/__tests__/TabNavigationContainer.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/Item.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/TabNavigationContainer.test.tsx.snap
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/components/Home/legacy/EmptyListComponent.tsx
  ts/features/messages/components/Home/legacy/ErrorLoadingComponent.tsx
  ts/features/messages/components/Home/legacy/Item.tsx
  ts/features/messages/components/Home/legacy/ListSelectionBar.tsx
  ts/features/messages/components/Home/legacy/MessageFeedback.tsx
  ts/features/messages/components/Home/legacy/MessagesArchive.tsx
  ts/features/messages/components/Home/legacy/MessagesInbox.tsx
  ts/features/messages/components/Home/legacy/MessagesSearch.tsx
  ts/features/messages/components/Home/legacy/helpers.tsx
  ts/features/messages/components/Home/legacy/index.tsx
  ts/features/messages/components/__test__/EmptyListComponent.test.tsx
  ts/features/messages/components/__test__/ListSelectionBar.test.tsx
  ts/features/messages/components/__test__/MessageList.test.tsx
  ts/features/messages/components/__test__/MessagesInbox.test.tsx
  ts/features/messages/components/__test__/MessagesSearch.test.tsx
  ts/features/messages/hooks/useMessageOpening.tsx
  ts/features/messages/navigation/MessagesHomeTabNavigator.tsx
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/messages/screens/MessagesHomeScreen.tsx
  ts/features/messages/screens/__tests__/LegacyMessagesHomeScreen.test.tsx
  ts/features/messages/screens/legacy/LegacyMessageAttachment.tsx
  ts/features/messages/screens/legacy/LegacyMessageDetailScreen.tsx
  ts/features/messages/screens/legacy/LegacyMessagesHomeScreen.tsx
  ts/features/messages/screens/legacy/MessageListScreen.tsx
  ts/features/messages/screens/legacy/MigratingMessage.tsx
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
  ts/navigation/TabNavigator.tsx
Labels: IO-Comunicazione

#5704 chore(Cross): [IOAPPX-283] Add `IOScrollView` (next iteration of `GradientScroll`, now deprecated) + `IOScrollViewWithLargeHeader`
  package.json
  ts/components/ui/IOScrollView.tsx
  ts/components/ui/IOScrollViewWithLargeHeader.tsx
  ts/components/ui/RNavScreenWithLargeHeader.tsx
  ts/features/design-system/core/DSIOScrollView.tsx
  ts/features/design-system/core/DSIOScrollViewWithLargeHeader.tsx
  ts/features/design-system/core/DSIOScrollViewWithoutActions.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/features/euCovidCert/components/__test__/__snapshots__/EuCovidCertHeader.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/LinkedText.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/QtspClauseListItem.test.tsx.snap
  yarn.lock
Labels: Design System, Dark mode 🌝, Cross

#5755 [IOCOM-905, IOCOM-906] New DS on Message Router
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/LoadingScreenContent.tsx
  ts/components/screens/__tests__/LoadingScreenContent.test.tsx
  ts/components/screens/__tests__/__snapshots__/LoadingScreenContent.test.tsx.snap
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/messages/screens/MessageRouterScreen.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
Labels: IO-Comunicazione

#5771 chore: [IOPAE-1145] Add FeaturedInstitution and FeaturedService carousel/card layout
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSCards.tsx
  ts/features/services/home/components/FeaturedInstitutionCard.tsx
  ts/features/services/home/components/FeaturedInstitutionsCarousel.tsx
  ts/features/services/home/components/FeaturedServiceCard.tsx
  ts/features/services/home/components/FeaturedServicesCarousel.tsx
  ts/features/services/home/components/OrganizationNameLabel.tsx
  ts/features/services/home/utils/index.ts
Labels: IO - Enti & Servizi

#5772 chore(IT Wallet): [SIW-1128] Add `EidCard` and `EidCardPreview` components
  img/features/itWallet/eid_card.svg
  img/features/itWallet/eid_card_invalid.svg
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSCards.tsx
  ts/features/itwallet/common/components/EidCard.tsx
  ts/features/itwallet/common/components/EidCardPreview.tsx
  ts/features/itwallet/common/components/__tests__/EidCard.test.tsx
  ts/features/itwallet/common/components/__tests__/EidCardPreview.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/EidCard.test.tsx.snap
  ts/features/itwallet/common/components/__tests__/__snapshots__/EidCardPreview.test.tsx.snap
Labels: IT Wallet

#5781 fix: [IOPAE-1129] Service Details bottom gradient displayed only with CTAs
  ts/features/services/details/components/ServiceDetailsScreenComponent.tsx
Labels: IO - Enti & Servizi

#5786 chore: [IOBP-575] Removed seconds from a11y label transaction detail date
  ts/features/payments/transaction/components/WalletTransactionInfoSection.tsx
Labels: a11y, IO-Bonus e pagamenti

#5789 fix: `LandingScreen`'s `Carousel` translations
  ts/screens/authentication/LandingScreen.tsx
Labels: IO-A&I

#5750 feat: [IOPID-1548] DS add new cie errors
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/CustomWizardScreen.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/routes.ts
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/UnlockAccessComponent.tsx
  ts/screens/authentication/UnlockAccessScreen.tsx
  ts/screens/authentication/__tests__/UnlockAccessComponent.test.tsx
  ts/screens/authentication/__tests__/UnlockAccessScreen.test.tsx
  ts/screens/authentication/cie/CieAuthErrorScreen.tsx
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
  ts/screens/authentication/cie/__test__/AuthErrorScreen.test.tsx
  ts/screens/authentication/cie/components/AuthErrorScreen.tsx
  ts/screens/onboarding/__tests__/UnlockAccessScreen.test.tsx
Labels: IO-A&I

#5788 chore: change EIC login flow with the dev server to navigate to `CieConsentDataUsageScreen`
  ts/screens/authentication/cie/CiePinScreen.tsx
Labels: IO-A&I

#5793 chore: [IOPAE-1142] Added featured carousels in `ServicesHomeScreen`
  locales/en/index.yml
  locales/it/index.yml
  ts/features/services/common/components/CardPressableBase.tsx
  ts/features/services/common/components/InstitutionListSkeleton.tsx
  ts/features/services/home/components/FeaturedInstitutionCard.tsx
  ts/features/services/home/components/FeaturedInstitutionList.tsx
  ts/features/services/home/components/FeaturedServiceCard.tsx
  ts/features/services/home/components/FeaturedServiceList.tsx
  ts/features/services/home/components/ServicesHomeIntitutionList.tsx
  ts/features/services/home/components/__tests__/FeaturedInstitutionCard.test.tsx
  ts/features/services/home/components/__tests__/FeaturedServiceCard.test.tsx
  ts/features/services/home/components/__tests__/__snapshots__/FeaturedInstitutionCard.test.tsx.snap
  ts/features/services/home/components/__tests__/__snapshots__/FeaturedServiceCard.test.tsx.snap
  ts/features/services/home/hooks/useInstitutionsFetcher.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/home/store/reducers/__tests__/store.test.ts
  ts/features/services/home/store/reducers/index.ts
Labels: IO - Enti & Servizi

#5749 chore: [IOCOM-1354] `NOTIFICATION_PERMISSION` super and profile property
  ts/features/pushNotifications/sagas/__tests__/checkNotificationsPreferencesSaga.test.tsx
  ts/features/pushNotifications/sagas/checkNotificationsPreferencesSaga.ts
  ts/features/pushNotifications/screens/OnboardingNotificationsInfoScreenConsent.tsx
  ts/mixpanelConfig/profileProperties.ts
  ts/mixpanelConfig/superProperties.ts
  ts/screens/profile/analytics/index.ts
Labels: IO-Comunicazione

#5795 chore: [IOPAE-1185] Add `headerShown` prop to `useHeaderSecondLevel`
  ts/features/services/institution/components/InstitutionServicesFailure.tsx
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
  ts/hooks/useHeaderSecondLevel.tsx
Labels: IO - Enti & Servizi

#5782 chore: [IOCOM-1358] FIMS flow IAB saga
  package.json
  ts/features/fims/__mocks__/mockFIMSCallbacks.ts
  ts/features/fims/__mocks__/mockFIMSSaga.ts
  ts/features/fims/saga/index.tsx
  ts/features/fims/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/store/actions/index.ts
  ts/features/fims/store/reducers/index.ts
Labels: IO-Comunicazione

#5787 chore(Cross): [IOAPPX-300] Add `FooterActions` that replaces `FooterWithButtons`
  CODEOWNERS
  ts/components/ui/FooterActions.tsx
  ts/components/ui/IOScrollView.tsx
  ts/features/design-system/core/DSFooterActions.tsx
  ts/features/design-system/core/DSFooterActionsNotFixed.tsx
  ts/features/design-system/core/DSFooterActionsSticky.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/screens/profile/DeveloperModeSection.tsx
Labels: Design System, Dark mode 🌝, Cross

#5799 chore: [IOCOM-1464] Latest HTTP Client package
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IO-Comunicazione

#5778 feat: [IOPID-1521,IOPID-1522,IOPID-1523] Integrate new DS in Profile section
  img/fiscalCode/fiscalCodeBack.png
  img/fiscalCode/fiscalCodeFront.png
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/@types/react-native-barcode-builder.d.ts
  ts/components/FiscalCodeComponent.tsx
  ts/components/FiscalCodeLandscapeOverlay.tsx
  ts/components/__tests__/FiscalCodeComponent.test.tsx
  ts/components/ui/IOScrollViewWithLargeHeader.tsx
  ts/features/common/store/reducers/index.ts
  ts/features/profileSettings/store/actions/index.ts
  ts/features/profileSettings/store/reducers/index.ts
  ts/features/profileSettings/store/selectors/index.ts
  ts/hooks/useLoadMunicipality.ts
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/screens/profile/FiscalCodeScreen.tsx
  ts/screens/profile/ProfileDataScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/screens/profile/__test__/FiscalCodeScreen.test.tsx
  ts/screens/profile/__test__/ProfileDataScreen.test.tsx
  ts/screens/profile/__test__/ProfileMainScreen.test.tsx
  ts/store/actions/types.ts
  ts/store/reducers/index.ts
Labels: IO-A&I

#5800 chore: [IOCOM-1384] FIMS flow error handling/native client
  ios/Podfile.lock
  package.json
  ts/features/fims/__mocks__/mockFIMSCallbacks.ts
  ts/features/fims/__mocks__/mockFIMSSaga.ts
  ts/features/fims/saga/index.tsx
  ts/features/fims/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/store/actions/index.ts
  ts/features/fims/store/reducers/index.ts
  ts/features/fims/types/index.ts
  yarn.lock
Labels: IO-Comunicazione

#5783 feat: [IOBP-647] Latest used method pre-selection
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/components/CheckoutPaymentMethodsList.tsx
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
Labels: IO-Bonus e pagamenti

#5785 chore: [IOBP-644] Add other onboardable method filters
  package.json
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
  ts/features/payments/checkout/utils/index.ts
  ts/features/payments/home/screens/__tests__/PaymentsHomeScreen.test.tsx
  ts/features/payments/onboarding/store/selectors/index.ts
  ts/features/payments/onboarding/utils/index.ts
  ts/features/payments/wallet/saga/__tests__/handleGetPaymentsWalletUserMethods.test.ts
Labels: IO-Bonus e pagamenti

#5798 chore: [IOBP-659] Add remote feature flag to the new payment section
  package.json
  ts/features/payments/checkout/hooks/usePagoPaPayment.ts
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: IO-Bonus e pagamenti

#5790 feat: [IOPID-1855] Add new DS on Activate NFC screen and create generic component
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/cie/CieNfcOverlay.tsx
  ts/components/screens/ScreenWithListItems.tsx
  ts/components/screens/__tests__/ScreenWithListItems.test.tsx
  ts/components/screens/__tests__/__snapshots__/ScreenWithListItems.test.tsx.snap
  ts/features/design-system/core/DSListItemScreen.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/routes.ts
  ts/screens/authentication/cie/ActivateNfcScreen.tsx
  ts/screens/authentication/cie/CieCardReaderScreen.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  ts/screens/authentication/cie/__test__/ActivateNfcScreen.test.tsx
  ts/screens/authentication/cie/__test__/__snapshots__/ActivateNfcScreen.test.tsx.snap
Labels: IO-A&I

#5784 feat: [IOCOM-824,IOCOM-825] Loading and loaded message list adapted to the new DS
  ts/features/messages/components/Home/DS/CustomPressableListItemBase.tsx
  ts/features/messages/components/Home/DS/MessageListItem.tsx
  ts/features/messages/components/Home/DS/MessageListItemSkeleton.tsx
  ts/features/messages/components/Home/DS/useListItemSpringAnimation.ts
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
  ts/features/messages/utils/__tests__/index.test.ts
  ts/features/messages/utils/index.ts
  ts/utils/__tests__/pot.test.ts
  ts/utils/pot.ts
Labels: IO-Comunicazione

#5780 feat(IT Wallet): [SIW-1021] Add IT Wallet eID preview screen
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ui/IOScrollView.tsx
  ts/components/ui/IOScrollViewWithLargeHeader.tsx
  ts/features/common/store/reducers/index.ts
  ts/features/itwallet/__mocks__/dc.json
  ts/features/itwallet/__mocks__/eid.json
  ts/features/itwallet/__mocks__/mdl.json
  ts/features/itwallet/__mocks__/ts.json
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/identification/screens/ItwIdentificationIdpSelectionScreen.tsx
  ts/features/itwallet/identification/store/selectors/index.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
Labels: IT Wallet
