Repository pagopa/io-app, pull requests merged in 2024-11, with the labels that each got.

#6297 fix(IT Wallet): [SIW-1751] Auto subscription to trial system at startup
  ts/features/itwallet/common/saga/__tests__/index.test.ts
  ts/features/itwallet/common/saga/index.ts
  ts/features/trialSystem/store/actions/index.ts
  ts/features/trialSystem/store/reducers/index.ts
  ts/features/trialSystem/store/sagas/watchTrialSystemSaga.ts
  ts/features/trialSystem/utils/error.ts
Labels: IT Wallet

#6352 chore(IT Wallet): [SIW-1794] Add info box within European Disability Card details screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/presentation/components/ItwCredentialTrustmark.tsx
  ts/features/itwallet/presentation/components/ItwPresentationAlertsSection.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationAlertsSection.test.tsx
Labels: IT Wallet

#6358 chore: [IOBP-935] Standardize error handling for user payment cancellation
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/types/PaymentGenericErrorAfterUserCancellationProblemJson.ts
  ts/features/payments/checkout/types/WalletPaymentFailure.ts
Labels: IO-Bonus e pagamenti

#6357 fix: [PE-732] CGN header snap point on scroll
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
Labels: Carta Giovani Nazionale

#6362 chore: [IOBP-757] Apply info copy component into transaction details screen
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsCartItemDetailsScreen.tsx
  ts/features/payments/transaction/screens/PaymentsTransactionOperationDetails.tsx
Labels: IO-Bonus e pagamenti

#6364 chore: [IOBP-954] Edit filter notice tab label
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#6363 fix: [IOBP-950] Filter tabs behavior into biz events notices list
  ts/features/payments/bizEventsTransaction/components/PaymentBizEventsSectionListHeader.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsFilterTabs.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
Labels: IO-Bonus e pagamenti

#6365 fix: [IOBP-953] Capitalize transaction fields
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
  ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#6368 chore(IT Wallet): [SIW-1819] Update `io-react-native-jwt` and `io-react-native-wallet` dependencies
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IT Wallet

#6370 chore: [IOBP-522] Disable back gesture for outcome screens
  ts/features/payments/checkout/navigation/navigator.tsx
Labels: IO-Bonus e pagamenti

#6372 chore: [IOBP-717] Rename payments checkout summary route
  ts/features/payments/checkout/hooks/usePagoPaPayment.ts
  ts/features/payments/checkout/navigation/navigator.tsx
  ts/features/payments/checkout/navigation/params.ts
  ts/features/payments/checkout/navigation/routes.ts
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/tempWorkaround/pagoPaPaymentWorkaround.ts
Labels: IO-Bonus e pagamenti

#6309 fix(IT Wallet): [SIW-1723] Cards and documents not always stacked
  ts/features/design-system/core/DSWallet.tsx
  ts/features/newWallet/components/WalletCardBaseComponent.tsx
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
Labels: IT Wallet

#6349 feat(IT Wallet): [SIW-1797,SIW-1608] Handle all credential statuses for the physical and digital document
  img/features/itWallet/cards/dc_off.png
  img/features/itWallet/cards/dc_off@2x.png
  img/features/itWallet/cards/dc_off@3x.png
  img/features/itWallet/cards/eid.png
  img/features/itWallet/cards/eid@2x.png
  img/features/itWallet/cards/eid@3x.png
  img/features/itWallet/cards/eid_off.png
  img/features/itWallet/cards/eid_off@2x.png
  img/features/itWallet/cards/eid_off@3x.png
  img/features/itWallet/cards/mdl_off.png
  img/features/itWallet/cards/mdl_off@2x.png
  img/features/itWallet/cards/mdl_off@3x.png
  img/features/itWallet/cards/ts_off.png
  img/features/itWallet/cards/ts_off@2x.png
  img/features/itWallet/cards/ts_off@3x.png
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSCards.tsx
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwDigitalVersionBadge.tsx
  ts/features/itwallet/common/components/ItwEidLifecycleAlert.tsx
  ts/features/itwallet/common/components/ItwWalletReadyBanner.tsx
  ts/features/itwallet/common/components/__tests__/ItwCredentialCard.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/issuance/screens/__tests__/ItwIssuanceCredentialAsyncContinuationScreen.test.tsx
  ts/features/itwallet/presentation/components/ItwPresentationAlertsSection.tsx
  ts/features/itwallet/presentation/components/ItwPresentationClaimsSection.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialInfoAlert.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialStatusAlert.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialVerificationExpired.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationAlertsSection.test.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationClaimsSection.test.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/components/__tests__/WalletCardsContainer.test.tsx
Labels: IT Wallet

#6360 chore(IT Wallet): [SIW-1814] Show invalid, expired, expiring status in skeuomorphic credential
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/index.tsx
  ts/features/itwallet/common/utils/itwCredentialUtils.ts
Labels: IT Wallet

#6291 chore: [IOCOM-1817] Add test for common FIMS hook
  ts/features/fims/common/hooks/__tests__/index.test.tsx
  ts/features/fims/common/hooks/index.tsx
  ts/features/fims/history/components/FimsHistoryListItem.tsx
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
Labels: IO-Comunicazione

#6369 chore: [IOPID-2409] Add new animated pictogram on Ingress screen
  assets/animated-pictograms/Waiting.json
  ts/components/screens/LoadingScreenContent.tsx
  ts/components/screens/__tests__/__snapshots__/LoadingScreenContent.test.tsx.snap
  ts/components/ui/AnimatedPictogramComponent.tsx
  ts/features/design-system/core/DSAnimatedPictograms.tsx
  ts/features/ingress/__test__/__snapshots__/IngressScreen.test.tsx.snap
  ts/features/ingress/screens/IngressScreen.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
Labels: IO-A&I

#6381 fix: [IOBP-962] Remove native header into payment method details error
  ts/features/payments/details/components/PaymentsMethodDetailsErrorContent.tsx
  ts/features/payments/details/navigation/navigator.tsx
Labels: IO-Bonus e pagamenti

#6380 chore(IT Wallet): [SIW-1783] Update ToS fallback to version 5.0
  ts/features/tos/store/selectors/index.ts
Labels: IT Wallet

#6308 chore: [IOCOM-1814] Add tests for `FimsUpdateAppAlert`
  ts/features/fims/common/components/FimsUpdateAppAlert.tsx
  ts/features/fims/common/components/__tests__/FimsUpdateAppAlert.test.tsx
  ts/features/fims/common/components/__tests__/__snapshots__/FimsUpdateAppAlert.test.tsx.snap
  ts/features/fims/common/navigation/__tests__/__snapshots__/index.test.ts.snap
  ts/features/fims/common/navigation/__tests__/index.test.ts
Labels: IO-Comunicazione

#6330 feat: [IOCOM-1660] FIMS SSO autogenerated specs
  package.json
  ts/features/fims/history/api/client.ts
  ts/features/fims/history/components/FimsHistoryListItem.tsx
  ts/features/fims/history/components/FimsHistoryNonEmptyContent.tsx
  ts/features/fims/history/store/actions/index.ts
  ts/features/fims/history/store/reducer/index.ts
  ts/features/fims/singleSignOn/components/FimsClaims.tsx
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/store/actions/index.ts
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/fims/singleSignOn/store/selectors/index.ts
  ts/features/fims/singleSignOn/types/index.ts
  yarn.lock
Labels: IO-Comunicazione

#6383 fix: add collaborators as codeowners
  CODEOWNERS
Labels: code review needed 💻📱

#6376 chore(IT Wallet): [SIW-1804] Already activated wallet screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/discovery/screens/ItwAlreadyActiveScreen.tsx
  ts/features/itwallet/discovery/screens/__tests__/ItwAlreadyActiveScreen.test.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/navigation/useItwLinkingOptions.tsx
Labels: IT Wallet

#6315 chore: [IOCOM-1759] Landing screen multiBanner feature
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/common/store/reducers/__tests__/index.test.ts
  ts/features/common/store/reducers/index.ts
  ts/features/itwallet/common/components/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerStandalone.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/ItwDiscoveryBanner.test.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
  ts/features/itwallet/common/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/landingScreenMultiBanner/components/LandingScreenBannerPicker.tsx
  ts/features/landingScreenMultiBanner/components/__mocks__/LandingScreenBannerPicker.tsx
  ts/features/landingScreenMultiBanner/components/__tests__/LandingScreenBannerPicker.test.tsx
  ts/features/landingScreenMultiBanner/components/__tests__/__snapshots__/LandingScreenBannerPicker.test.tsx.snap
  ts/features/landingScreenMultiBanner/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/landingScreenMultiBanner/store/__tests__/actions.test.ts
  ts/features/landingScreenMultiBanner/store/__tests__/reducer.test.ts
  ts/features/landingScreenMultiBanner/store/__tests__/selectors.test.tsx
  ts/features/landingScreenMultiBanner/store/actions.ts
  ts/features/landingScreenMultiBanner/store/reducer.ts
  ts/features/landingScreenMultiBanner/store/selectors.ts
  ts/features/landingScreenMultiBanner/utils/__tests__/index.test.ts
  ts/features/landingScreenMultiBanner/utils/index.ts
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/screens/profile/components/SettingsDiscoveryBanner.tsx
  ts/screens/profile/components/__test__/SettingsDiscoveryBanner.test.tsx
  ts/screens/profile/components/__test__/__snapshots__/SettingsDiscoveryBanner.test.tsx.snap
  ts/store/actions/types.ts
  ts/store/reducers/backendStatus/__tests__/remoteConfig.test.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IO-Comunicazione, code review needed 💻📱

#6351 feat: [IOCOM-1665] FIMS Authentication proper UI
  locales/en/index.yml
  locales/it/index.yml
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/fims/common/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/fims/singleSignOn/components/FimsFullScreenErrors.tsx
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/fims/singleSignOn/store/selectors/index.ts
  ts/features/fims/singleSignOn/utils/index.ts
Labels: IO-Comunicazione

#6334 feat: [IOBP-838] Remove receipt from list
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsHideReceiptButton.tsx
  ts/features/payments/bizEventsTransaction/navigation/navigator.tsx
  ts/features/payments/bizEventsTransaction/navigation/params.ts
  ts/features/payments/bizEventsTransaction/navigation/routes.ts
  ts/features/payments/bizEventsTransaction/saga/handleDisableBizEventsTransactionReceipt.ts
  ts/features/payments/bizEventsTransaction/saga/index.ts
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsDetailsScreen.tsx
  ts/features/payments/bizEventsTransaction/store/actions/index.ts
  ts/features/payments/bizEventsTransaction/store/reducers/index.ts
  ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#6386 chore: [IOBP-951] Add payment verify generic error custom screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/components/__tests__/WalletPaymentFailureDetail.test.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentFailureScreen.tsx
  ts/features/payments/checkout/screens/__tests__/WalletPaymentDetailScreen.test.tsx
  ts/features/payments/checkout/types/PaymentVerifyGenericErrorProblemJson.ts
  ts/features/payments/checkout/types/WalletPaymentFailure.ts
Labels: IO-Bonus e pagamenti

#6359 feat: [IOCOM-1819] Tests for API and utils on FIMS history
  ts/features/fims/history/api/__tests__/client.test.ts
  ts/features/fims/history/utils/__tests__/__snapshots__/styles.test.ts.snap
  ts/features/fims/history/utils/__tests__/styles.test.ts
Labels: IO-Comunicazione

#6371 fix(IT Wallet): [SIW-1778] Handle 401 status code during Wallet Instance revocation within eID issuance
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6367 feat: [IOPID-2456] Test CieID flow
  ts/__mocks__/@gorhom/bottom-sheet.ts
  ts/features/cie/__tests__/CieIdNotInstalled.test.tsx
  ts/features/cie/__tests__/CieIdNotInstalledScreen.test.tsx
  ts/features/cie/__tests__/__snapshots__/CieIdNotInstalled.test.tsx.snap
  ts/features/cie/__tests__/__snapshots__/CieIdNotInstalledScreen.test.tsx.snap
  ts/features/cie/__tests__/__snapshots__/wizards.test.tsx.snap
  ts/features/cie/__tests__/wizards.test.tsx
  ts/features/cie/components/CieIdNotInstalled.tsx
  ts/features/cie/screens/wizards/CieIdWizard.tsx
  ts/features/cie/screens/wizards/CiePinWizard.tsx
  ts/features/cie/screens/wizards/IDActivationWizard.tsx
  ts/features/cie/screens/wizards/SpidWizard.tsx
  ts/features/cieLogin/__tests__/CieIdLoginScreen.test.tsx
  ts/features/cieLogin/__tests__/CieIdLoginWebView.test.tsx
  ts/features/cieLogin/__tests__/__snapshots__/CieIdLoginScreen.test.tsx.snap
  ts/features/cieLogin/__tests__/__snapshots__/CieIdLoginWebView.test.tsx.snap
  ts/features/cieLogin/components/CieIdLoginWebView.tsx
  ts/hooks/__tests__/useNavigateToLoginMethod.test.tsx
  ts/hooks/useNavigateToLoginMethod.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/OptInScreen.tsx
  ts/screens/authentication/__tests__/LandingScreen.test.tsx
  ts/screens/authentication/__tests__/__snapshots__/LandingScreen.test.tsx.snap
  ts/utils/jest/withStore.tsx
Labels: IO-A&I

#6361 chore: [IOPID-2406] Added handling of errorMessage in login flow
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/LoadingScreenContent.tsx
  ts/components/screens/__tests__/__snapshots__/LoadingScreenContent.test.tsx.snap
  ts/features/cieLogin/__tests__/CieIdLoginWebView.test.tsx
  ts/features/cieLogin/components/CieIdLoginWebView.tsx
  ts/features/ingress/__test__/__snapshots__/IngressScreen.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
  ts/screens/authentication/AuthErrorScreen.tsx
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/__tests__/AuthErrorComponent.test.tsx
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
  ts/screens/authentication/components/AuthErrorComponent.tsx
  ts/screens/authentication/idpAuthSessionHandler.tsx
  ts/screens/profile/__test__/__snapshots__/SecurityScreen.test.tsx.snap
  ts/utils/login.ts
Labels: IO-A&I

#6387 chore: [IOBP-969] New payment checkout outcome mapping
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/___tests___/WalletPaymentOutcomeScreen.test.tsx
  ts/features/payments/checkout/screens/___tests___/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
  ts/features/payments/checkout/types/PaymentOutcomeEnum.ts
  yarn.lock
Labels: IO-Bonus e pagamenti

#6336 feat: [PE-630,PE-758] CGN partner search screen
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/bonus/cgn/api/backendCgnMerchants.ts
  ts/features/bonus/cgn/components/merchants/MerchantSearchResultListItem.tsx
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/cgn/navigation/params.ts
  ts/features/bonus/cgn/navigation/routes.ts
  ts/features/bonus/cgn/saga/index.ts
  ts/features/bonus/cgn/saga/networking/merchants/cgnGetMerchantsCountSaga.ts
  ts/features/bonus/cgn/saga/networking/merchants/cgnMerchantDetail.ts
  ts/features/bonus/cgn/saga/networking/merchants/cgnMerchantsSaga.ts
  ts/features/bonus/cgn/saga/networking/merchants/cgnOfflineMerchantsSaga.ts
  ts/features/bonus/cgn/saga/networking/merchants/cgnOnlineMerchantsSaga.ts
  ts/features/bonus/cgn/saga/networking/merchants/cgnSearchMerchantsSaga.ts
  ts/features/bonus/cgn/screens/__test__/CgnMerchantSearchScreen.test.tsx
  ts/features/bonus/cgn/screens/__test__/highlightText.test.ts
  ts/features/bonus/cgn/screens/merchants/CgnMerchantSearchScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/bonus/cgn/store/actions/merchants.ts
  ts/features/bonus/cgn/store/reducers/merchants.ts
  ts/hooks/useDebouncedValue.ts
  ts/utils/highlightSearchText.tsx
Labels: dont-merge :raised_hand:, Carta Giovani Nazionale, copy review needed ✋🏼 🖊️

#6397 fix: [PE-801] CGN WebView crash error
  ts/components/WebviewComponent.tsx
Labels: Bug 🐞, Carta Giovani Nazionale

#6396 chore: [IOBP-973] Hide receipt analytics events tracking
  ts/features/payments/bizEventsTransaction/analytics/index.ts
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsHideReceiptButton.tsx
  ts/features/payments/bizEventsTransaction/saga/handleDisableBizEventsTransactionReceipt.ts
Labels: IO-Bonus e pagamenti

#6395 feat: [IOCOM-1905] Handling of InApp Browser opening failure for FIMS SSO
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
Labels: IO-Comunicazione

#6393 chore: [IOBP-971] Outcome screen for error 404 from server for pspList
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/checkout/store/actions/networking.ts
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/types/PspPaymentMethodNotAvailableProblemJson.ts
  ts/features/payments/checkout/types/WalletPaymentFailure.ts
Labels: IO-Bonus e pagamenti

#6373 chore(IT Wallet): [SIW-1759] Consider integrity check preparation
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/utils/__tests__/itwStoreUtils.test.ts
  ts/features/itwallet/common/utils/itwIntegrityUtils.ts
  ts/features/itwallet/common/utils/itwStoreUtils.ts
  ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
  ts/features/itwallet/issuance/store/actions/index.ts
  ts/features/itwallet/issuance/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/issuance/store/selectors/index.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/lifecycle/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/lifecycle/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/machine/eid/actors.ts
Labels: IT Wallet

#6389 feat: [IOCOM-1904] Preferred language sent to FIMS provider during Authorisation
  ts/features/fims/history/saga/handleGetFimsHistorySaga.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
Labels: IO-Comunicazione

#6399 chore: [IOBP-688] Adapt `ListItemTransaction` refactor and upgrade `io-app-design-system` to the version `3.0.1`
  package.json
  ts/components/wallet/TransactionsList.tsx
  ts/features/design-system/core/DSListItems.tsx
  ts/features/design-system/core/DSModules.tsx
  ts/features/idpay/details/components/TimelineOperationListItem.tsx
  ts/features/messages/components/MessageDetail/MessagePaymentItem.tsx
  ts/features/payments/barcode/components/PaymentNoticeListItem.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsListItemTransaction.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionCartList.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionLoadingList.tsx
  ts/features/payments/common/utils/index.ts
  ts/features/payments/common/utils/types.ts
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/components/PaymentsListItemTransaction.tsx
  ts/features/payments/transaction/components/PaymentsLegacyListItemTransaction.tsx
  ts/features/payments/transaction/components/WalletTransactionDetailsList.tsx
  ts/features/payments/transaction/screens/PaymentsTransactionListScreen.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/utils/accessibility.ts
  yarn.lock
Labels: Design System, IO-Bonus e pagamenti

#6390 feat: [IOCOM-1916] New FIMS labels for the Consents screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/history/components/FimsHistoryHeaderComponent.tsx
  ts/features/fims/history/screens/HistoryScreen.tsx
  ts/features/fims/singleSignOn/components/FimsFullScreenErrors.tsx
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
Labels: IO-Comunicazione

#6402 fix: [IOCOM-1926] Do not show an error when closing the InApp Browser, for FIMS flow
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
Labels: IO-Comunicazione

#6378 feat(IT Wallet): [SIW-1744] Add ITW feedback banner
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/persistedStore.test.ts
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/common/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/common/components/ItwEidLifecycleAlert.tsx
  ts/features/itwallet/common/components/ItwFeedbackBanner.tsx
  ts/features/itwallet/common/components/ItwUpcomingWalletBanner.tsx
  ts/features/itwallet/common/components/__tests__/ItwFeedbackBanner.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwFeedbackBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerStandalone.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/actions/preferences.ts
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/common/store/selectors/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
  ts/features/newWallet/components/WalletCardsCategoryRetryErrorBanner.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/components/WalletCategoryFilterTabs.tsx
Labels: IT Wallet

#6405 fix: [IOBP-997] Missing success toast on hide receipt
  ts/features/payments/bizEventsTransaction/saga/handleDisableBizEventsTransactionReceipt.ts
Labels: IO-Bonus e pagamenti

#6406 fix(IT Wallet): [SIW-1845] Hide trustmark when a credential is invalid
  ts/features/itwallet/common/utils/itwCredentialUtils.ts
  ts/features/itwallet/presentation/components/ItwCredentialTrustmark.tsx
Labels: IT Wallet

#6403 fix: [IOCOM-1927] Remove error Toast on InApp Browser opening on FIMS
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
Labels: IO-Comunicazione

#6391 feat: [IOBP-870] Add bonus & payments profile and super properties on mixpanel
  ts/features/bonus/cgn/analytics/index.ts
  ts/features/newWallet/saga/index.ts
  ts/features/newWallet/store/selectors/index.ts
  ts/mixpanelConfig/mixpanelPropertyUtils.ts
  ts/mixpanelConfig/profileProperties.ts
  ts/mixpanelConfig/superProperties.ts
Labels: IO-Bonus e pagamenti

#6408 chore(IT Wallet): [SIW-1823] Handle local integrity errors
  ts/features/itwallet/machine/eid/failure.ts
Labels: IT Wallet

#6407 feat: [IOBP-979,IOBP-952] Add more explicit error screen into payments flow
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentCreateTransaction.test.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetDetails.ts
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentFailureScreen.tsx
  ts/features/payments/checkout/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#6401 chore: [IOPID-2427] - CieID user engagement
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/cieLogin/store/actions/index.ts
  ts/features/cieLogin/store/reducers/index.ts
  ts/features/cieLogin/store/selectors/index.ts
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/__tests__/__snapshots__/LandingScreen.test.tsx.snap
  ts/store/reducers/index.ts
  yarn.lock
Labels: IO-A&I

#6413 fix(Cross): [IOAPPX-431] Fix alignment of the dot separator in the `MessageListItem`
  ts/features/messages/components/Home/DS/MessageListItem.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
Labels: Cross

#6410 fix: [IOBP-972] Vision camera functionality has been restricted by the operating system
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
Labels: IO-Bonus e pagamenti

#6419 chore: [IOBP-1013] New copy for card method removal
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
Labels: IO-Bonus e pagamenti

#6424 chore: [IOBP-982] Add outcome 99 screen into payment flow
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/___tests___/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
  ts/features/payments/checkout/types/PaymentOutcomeEnum.ts
Labels: IO-Bonus e pagamenti

#6425 fix: [PE-798] CGN update string for activation pending result
  ts/features/bonus/cgn/screens/activation/CgnActivationTimeoutScreen.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6423 feat: [PE-805] CGN update cta on card remove action
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/components/CgnServiceCTA.tsx
  ts/features/bonus/cgn/hooks/useCgnUnsubscribe.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6415 chore(Cross): [IOAPPX-434] Update the main icon app for iOS + Add support for dark and tinted appearances
  README.md
  img/app-logo.svg
  img/io-app-icon.png
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-dark.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-default.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-tinted.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-1024.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-30.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-57.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-57@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-60@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-60@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-76.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-76@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-83.5@2x.png
Labels: Design System, Cross

#6412 chore: [IOBP-977,IOBP-952] Add more payment explicit error and mixpanel events
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/components/__tests__/WalletPaymentFailureDetail.test.tsx
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentFailureScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/checkout/types/PaymentSlowdownErrorProblemJson.ts
  ts/features/payments/checkout/types/WalletPaymentFailure.ts
Labels: IO-Bonus e pagamenti

#6438 fix: [IOCOM-1947] ProfileAndSystemNotificationPermissions saga and test fix
  ts/features/pushNotifications/sagas/__tests__/profileAndSystemNotificationsPermissions.test.tsx
  ts/features/pushNotifications/sagas/profileAndSystemNotificationsPermissions.ts
Labels: IO-Comunicazione

#6418 chore(IT Wallet): [SIW-1862] Remove transparent header within credential details screen
  ts/features/itwallet/presentation/components/ItwPresentationDetailsHeader.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailsScreenBase.tsx
Labels: IT Wallet

#6421 fix: [IOPID-2490,IOPID-2506] Add logic to validate URLs in Webview and add header to go back on CieID webview screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/cieLogin/__tests__/CieIdAuthUrlError.test.tsx
  ts/features/cieLogin/__tests__/CieIdLoginScreen.test.tsx
  ts/features/cieLogin/__tests__/CieIdLoginWebView.test.tsx
  ts/features/cieLogin/__tests__/__snapshots__/CieIdAuthUrlError.test.tsx.snap
  ts/features/cieLogin/__tests__/__snapshots__/CieIdLoginScreen.test.tsx.snap
  ts/features/cieLogin/__tests__/__snapshots__/CieIdLoginWebView.test.tsx.snap
  ts/features/cieLogin/analytics/index.ts
  ts/features/cieLogin/components/CieIdLoginWebView.tsx
  ts/features/cieLogin/components/screens/CieIdAuthUrlError.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/routes.ts
Labels: IO-A&I

#6436 chore: [IOBP-992] Update analytics body sent to mixpanel for psp not available
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCalculateFees.ts
Labels: IO-Bonus e pagamenti

#6439 chore: [IOBP-985] Add onboarding payment method success mixpanel analytics event
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/onboarding/analytics/index.ts
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
Labels: IO-Bonus e pagamenti

#6398 fix(IT Wallet): [SIW-1726] Fix accessibility issues within credential details screen
  locales/en/index.yml
  locales/it/index.yml
  ts/components/QrCodeImage.tsx
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/FlippableCard.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/index.tsx
  ts/features/itwallet/common/utils/itwAccessibilityUtils.ts
  ts/features/itwallet/presentation/components/ItwCredentialTrustmark.tsx
  ts/features/itwallet/presentation/components/ItwPresentationClaimsSection.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailsHeader.tsx
  ts/features/itwallet/presentation/components/ItwPresentationFiscalCode.tsx
  ts/features/itwallet/presentation/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
Labels: a11y, IT Wallet

#6366 feat: [IOCOM-1821] Tests for actions/reducer/selectors on FIMS' history
  ts/features/fims/history/store/actions/__tests__/index.test.ts
  ts/features/fims/history/store/reducer/__tests__/__snapshots__/index.test.ts.snap
  ts/features/fims/history/store/reducer/__tests__/index.test.ts
  ts/features/fims/history/store/reducer/index.ts
  ts/features/fims/history/store/selectors/__tests__/index.test.ts
  ts/features/fims/history/store/selectors/index.ts
Labels: IO-Comunicazione

#6437 fix(IT Wallet): [SIW-1867] Unsupported device cta onpress action
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
Labels: IT Wallet

#6443 fix: [IOCOM-1948] Proper Authorization header's value for FIMS history
  ts/features/fims/history/saga/handleExportFimsHistorySaga.ts
  ts/features/fims/history/saga/handleGetFimsHistorySaga.ts
Labels: IO-Comunicazione

#6432 chore(IT Wallet): [SIW-1839] Remote ITW feedback banner
  package.json
  ts/features/itwallet/common/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IT Wallet

#6428 chore: [IOPID-2137,IOPID-2479] CieID events integration
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/cie/__tests__/CieIdErrorScreen.test.tsx
  ts/features/cie/__tests__/__snapshots__/wizards.test.tsx.snap
  ts/features/cie/__tests__/wizards.test.tsx
  ts/features/cie/analytics/index.ts
  ts/features/cie/components/CieIdNotInstalled.tsx
  ts/features/cie/screens/CieIdNotInstalledScreen.tsx
  ts/features/cie/screens/errors/CieIdErrorScreen.tsx
  ts/features/cie/screens/wizards/CieIdWizard.tsx
  ts/features/cie/screens/wizards/CiePinWizard.tsx
  ts/features/cie/screens/wizards/IDActivationWizard.tsx
  ts/features/cie/screens/wizards/SpidWizard.tsx
  ts/features/cieLogin/__tests__/CieIdLoginWebView.test.tsx
  ts/features/cieLogin/components/CieIdLoginWebView.tsx
  ts/hooks/useNavigateToLoginMethod.tsx
  ts/sagas/startup/authenticationSaga.ts
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/__tests__/LandingScreen.test.tsx
  ts/screens/authentication/analytics/index.ts
  ts/screens/authentication/analytics/spidAnalytics.ts
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
  ts/screens/authentication/components/AuthErrorComponent.tsx
  ts/utils/login.ts
Labels: IO-A&I

#6431 fix(IT Wallet): [SIW-1834] Refactor date claim parser
  package.json
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardClaim.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardData.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
  ts/utils/__tests__/dates.test.ts
  ts/utils/dates.ts
Labels: IT Wallet

#6451 chore(Cross): [IOAPPX-434] Update `IconApp` iOS assets to remove alpha channel and fix App Store issue
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-dark.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-default.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-tinted.png
Labels: Design System, Cross

#6447 chore(IT Wallet): [SIW-1868] Add full screen skeumorphic card modal
  ts/components/ui/utils/hooks/useScaleAnimation.ts
  ts/features/design-system/core/DSCards.tsx
  ts/features/itwallet/__mocks__/dc.json
  ts/features/itwallet/__mocks__/eid.json
  ts/features/itwallet/__mocks__/mdl.json
  ts/features/itwallet/__mocks__/ts.json
  ts/features/itwallet/common/components/ItwSkeumorphicCard/FlipGestureDetector.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/FlippableCard.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/index.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/types.ts
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/__tests__/itwCredentialStatusUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwCredentialStatusUtils.ts
  ts/features/itwallet/credentials/saga/handleItwCredentialsStoreSaga.ts
  ts/features/itwallet/credentials/saga/handleWalletCredentialsRehydration.ts
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/playgrounds/components/ItwSkeumorphicCredentialSection.tsx
  ts/features/itwallet/presentation/components/ItwPresentationClaimsSection.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCard.tsx
  ts/features/itwallet/presentation/components/ItwPresentationCredentialCardFlipButton.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailsHeader.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialCardModal.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/itwallet/trustmark/components/ItwCredentialTrustmark.tsx
  ts/utils/brightness.ts
Labels: IT Wallet

#6448 fix: [IOBP-1022] Mixpanel analytics properties sent at app opening
  ts/mixpanelConfig/___tests___/mixpanelPropertyUtils.test.tsx
  ts/mixpanelConfig/mixpanelPropertyUtils.ts
  ts/mixpanelConfig/profileProperties.ts
  ts/mixpanelConfig/superProperties.ts
Labels: IO-Bonus e pagamenti

#6449 fix: [IOPID-2490] Add correct check on whitelisted URLs
  ts/features/cieLogin/components/CieIdLoginWebView.tsx
Labels: IO-A&I

#6454 fix: [PE-796] CGN hide percentage badge if value not in range `1-100`
  ts/features/bonus/cgn/components/merchants/CgnDiscountValueBox.tsx
  ts/features/bonus/cgn/components/merchants/CgnModuleDiscount.tsx
  ts/features/bonus/cgn/components/merchants/___tests___/CgnModuleDiscount.test.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountHeader.tsx
  ts/features/bonus/cgn/components/merchants/discount/___tests___/CgnDiscountHeader.test.tsx
  ts/features/bonus/cgn/components/merchants/utils/___tests___/index.test.tsx
  ts/features/bonus/cgn/components/merchants/utils/index.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6458 chore(Cross): [IOAPPX-434] Remove dark mode app icon to fix build rejection
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-dark.png
Labels: Cross

#6459 fix: [IOCOM-1955] Fix message time going out of screen
  ts/features/messages/components/Home/DS/MessageListItem.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
Labels: IO-Comunicazione

#6452 chore(IT Wallet): [SIW-1854] Route every unsupported device error code
  ts/features/itwallet/machine/eid/failure.ts
Labels: IT Wallet

#6450 feat: [IOCOM-1936] Handling of InApp Browser opening failure for FIMS SSO
  ios/Podfile.lock
  package.json
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/lollipop/utils/__tests__/retryAndVerifyRedirectNativeError.test.ts
  ts/features/lollipop/utils/login.ts
  ts/utils/analytics.ts
  yarn.lock
Labels: IO-Comunicazione

#6456 chore(IT Wallet): [SIW-1869] Add fiscal code full screen modal
  locales/en/index.yml
  locales/it/index.yml
  patches/react-native-screen-brightness+2.0.0-alpha.patch
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/presentation/components/ItwPresentationFiscalCode.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialFiscalCodeModal.tsx
  ts/utils/brightness.ts
Labels: IT Wallet

#6462 reverts: Update the main icon app for iOS
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-default.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-tinted.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-1024.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-30.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-57.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-57@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-60@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-60@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-76.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-76@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-83.5@2x.png
Labels: Cross

#6444 chore(Cross): [IOAPPX-439] Enable the iridescent trust mark for all
  ios/Podfile.lock
  package.json
  ts/features/itwallet/trustmark/components/ItwCredentialTrustmark.tsx
  yarn.lock
Labels: IT Wallet, Cross, Experimental lab ✨

#6441 feat(IT Wallet): [SIW-1800,SIW-1801,SIW-1808] Alert for disabled authentication methods, IPZS and Wallet Provider down
  package.json
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/__tests__/ItwIdentificationModeSelectionScreen.test.tsx
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IT Wallet

#6466 fix(IT Wallet): [SIW-1873] Fix `useMaxBrightness` flickering on iOS
  ts/utils/brightness.ts
Labels: IT Wallet

#6455 chore(IT Wallet): [SIW-1830] Wallet errors refactor
  package.json
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/common/utils/itwCredentialStatusAttestationUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwRevocationUtils.ts
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
  ts/features/itwallet/issuance/hooks/useCredentialEventsTracking.ts
  ts/features/itwallet/issuance/hooks/useEidEventsTracking.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/failure.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/failure.ts
  ts/features/itwallet/machine/eid/guards.ts
  ts/features/itwallet/machine/eid/machine.ts
  yarn.lock
Labels: IT Wallet

#6409 fix(IT Wallet): [SIW-1795] Problem with SPID Login Using Custom Tab
  .env.local
  .env.production
  package.json
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwOpenUrlAndListenForRedirect.ts
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
  ts/features/itwallet/identification/screens/spid/ItwSpidIdpLoginScreen.tsx
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/guards.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/eid/selectors.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  yarn.lock
Labels: IT Wallet

#6461 chore: [IOBP-981,IOBP-1002] Add PSP_ERROR outcome screen into payment flow
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/___tests___/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
  ts/features/payments/checkout/types/PaymentOutcomeEnum.ts
Labels: IO-Bonus e pagamenti

#6460 chore: [IOPID-2515] - Add SECURITY_LEVEL_MISMATCH event
  ts/features/cieLogin/analytics/index.ts
  ts/features/cieLogin/sagas/trackLevelSecuritySaga.ts
  ts/features/cieLogin/store/actions/index.ts
  ts/features/cieLogin/store/reducers/index.ts
  ts/features/cieLogin/store/selectors/index.ts
  ts/hooks/useNavigateToLoginMethod.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: IO-A&I
