Repository pagopa/io-app, pull requests merged in 2024-07, with the labels that each got.

#5918 chore: [IOPID-1999] - Change IdentificationModal behavior displayed on PIN change operation
  ts/screens/profile/SecurityScreen.tsx
Labels: IO-A&I

#5906 chore: [IOBP-662] New payment flow tracking implementation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/barcode/analytics/index.ts
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/components/WalletPaymentHeader.tsx
  ts/features/payments/checkout/hooks/useWalletPaymentGoBackHandler.tsx
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentCreateTransaction.test.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentInputFiscalCodeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentInputNoticeNumberScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/checkout/store/actions/orchestration.ts
  ts/features/payments/checkout/types/PaymentAnalytics.ts
  ts/features/payments/checkout/utils/index.ts
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/history/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5895 feat: [IOCOM-1417] Security suggestions bottom sheet, new messages' home
  ts/features/messages/components/Home/SecuritySuggestions.tsx
  ts/features/messages/components/Home/__tests__/SecuritySuggestions.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/SecuritySuggestions.test.tsx.snap
  ts/features/messages/screens/MessagesHomeScreen.tsx
Labels: IO-Comunicazione

#5907 chore: [IOPAE-1284] Update services Mixpanel analytics events
  ts/features/bonus/cgn/components/CgnServiceCTA.tsx
  ts/features/services/common/analytics/index.ts
  ts/features/services/details/components/ServiceDetailsPreferences.tsx
  ts/features/services/details/screens/ServiceDetailsScreen.tsx
  ts/features/services/details/store/reducers/__tests__/servicesById.test.ts
  ts/features/services/details/store/reducers/servicesById.ts
  ts/features/services/details/types/ServiceMetadataInfo.ts
  ts/features/services/home/components/FeaturedInstitutionList.tsx
  ts/features/services/home/components/FeaturedServiceList.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/institution/saga/__tests__/handleFindInstitutionServices.test.ts
  ts/features/services/institution/saga/handleFindInstitutionServices.ts
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
  ts/features/services/institution/store/actions/index.ts
  ts/features/services/institution/store/reducers/__tests__/store.test.ts
  ts/features/services/institution/store/reducers/index.ts
  ts/features/services/search/screens/SearchScreen.tsx
Labels: IO - Enti & Servizi

#5915 feat: [IOPID-1528] Add new DS on profile calendar preferences
  locales/en/index.yml
  locales/it/index.yml
  ts/components/CalendarsListContainer.tsx
  ts/components/SelectCalendarModal.tsx
  ts/screens/profile/CalendarsPreferencesScreen.tsx
Labels: IO-A&I, copy review needed ✋🏼 🖊️

#5925 [IOPID-1552, IOPID-1553] Add new DS on information about IO section and change copy on exit alert
  locales/de/index.yml
  locales/en/index.yml
  locales/en/profile/profile_appinfo_main.md
  locales/it/index.yml
  locales/it/profile/profile_appinfo_main.md
  ts/screens/profile/ProfileAboutApp.tsx
Labels: IO-A&I, copy review needed ✋🏼 🖊️

#5927 chore: [IOCOM-1578] Updated types for FIMS consents, latest Http Client version
  ios/Podfile.lock
  package.json
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/fims/singleSignOn/types/index.ts
  yarn.lock
Labels: IO-Comunicazione

#5910 chore(IT Wallet): [SIW-1287] Update credential preview screens
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/hooks/useItwDismissalDialog.tsx
  ts/features/itwallet/issuance/components/ItwCredentialPreviewScreenContent.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
Labels: IT Wallet

#5901 feat: [IOPID-1938] `withThirdPartyRefreshApiCall`
  ts/features/fastLogin/saga/utils/index.ts
  ts/features/idpay/code/saga/__tests__/handleIdPayGenerateCode.test.ts
  ts/features/idpay/code/saga/handleIdPayGenerateCode.ts
Labels: IO-A&I

#5921 feat: [IOPID-1534] Add new DS on Privacy and ToS screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/PrivacyMainScreen.tsx
Labels: IO-A&I

#5928 fix: [IOPID-1552, IOPID-1553, IOPID-1528] remediation english copy
  locales/en/index.yml
Labels: IO-A&I

#5916 feat: [IOPID-1551] - Integrate new DS in account deletion flow
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/RemoveAccountDetailsScreen.tsx
  ts/screens/profile/RemoveAccountInfoScreen.tsx
  ts/screens/profile/RemoveAccountSuccessScreen.tsx
  ts/store/actions/profile.ts
  ts/store/actions/userDataProcessing.ts
  ts/store/reducers/userDataProcessing.ts
Labels: IO-A&I

#5845 chore(Cross): [IOAPPX-317] Refactor `DeveloperTestEnvironmentSection` to use `FlatList`
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/DeveloperModeSection.tsx
Labels: Cross

#5920 chore: [IOCOM-1561] FIMS history saga
  assets/FimsSwager.yml
  package.json
  ts/features/fims/common/navigation/index.tsx
  ts/features/fims/common/saga/index.ts
  ts/features/fims/common/store/actions.ts
  ts/features/fims/common/store/reducer.ts
  ts/features/fims/history/api/client.ts
  ts/features/fims/history/saga/handleGetFimsHistorySaga.ts
  ts/features/fims/history/saga/index.ts
  ts/features/fims/history/screens/HistoryScreen.tsx
  ts/features/fims/history/store/actions/index.ts
  ts/features/fims/history/store/reducer/index.ts
  ts/features/fims/history/store/selectors/index.ts
  ts/features/fims/singleSignOn/navigation/index.tsx
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/messages/utils/messages.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/screens/profile/PrivacyMainScreen.tsx
Labels: IO-Comunicazione

#5929 chore(IT Wallet): [SIW-1312] IT Wallet playgrounds refactoring
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/profile/DeveloperModeSection.tsx
Labels: IT Wallet

#5912 feat: [IOCOM-840] Preconditions bottom sheet, new DS
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/__tests__/persistedStore.test.ts
  ts/components/services/SpecialServices/LegacySpecialServicesCTA.tsx
  ts/features/messages/components/Home/Preconditions.tsx
  ts/features/messages/components/Home/PreconditionsContent.tsx
  ts/features/messages/components/Home/PreconditionsFeedback.tsx
  ts/features/messages/components/Home/PreconditionsFooter.tsx
  ts/features/messages/components/Home/PreconditionsTitle.tsx
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__mocks__/PagerViewContainer.tsx
  ts/features/messages/components/Home/__mocks__/Preconditions.tsx
  ts/features/messages/components/Home/__mocks__/PreconditionsContent.tsx
  ts/features/messages/components/Home/__mocks__/SecuritySuggestions.tsx
  ts/features/messages/components/Home/__mocks__/TabNavigationContainer.tsx
  ts/features/messages/components/Home/__mocks__/Toasts.tsx
  ts/features/messages/components/Home/__tests__/Preconditions.test.tsx
  ts/features/messages/components/Home/__tests__/PreconditionsContent.test.tsx
  ts/features/messages/components/Home/__tests__/PreconditionsFeedback.test.tsx
  ts/features/messages/components/Home/__tests__/PreconditionsFooter.test.tsx
  ts/features/messages/components/Home/__tests__/PreconditionsTitle.test.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/Preconditions.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/PreconditionsContent.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/PreconditionsFeedback.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/PreconditionsFooter.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/PreconditionsTitle.test.tsx.snap
  ts/features/messages/components/MessageDetail/__mocks__/MessageMarkdown.tsx
  ts/features/messages/components/PreconditionBottomSheet/LegacyPreconditionContent.tsx
  ts/features/messages/components/PreconditionBottomSheet/LegacyPreconditionFooter.tsx
  ts/features/messages/components/PreconditionBottomSheet/LegacyPreconditionHeader.tsx
  ts/features/messages/hooks/useLegacyMessageOpening.tsx
  ts/features/messages/saga/__test__/handleMessagePrecondition.test.ts
  ts/features/messages/saga/handleMessagePrecondition.ts
  ts/features/messages/saga/index.ts
  ts/features/messages/screens/MessagesHomeScreen.tsx
  ts/features/messages/screens/__tests__/MessagesHomeScreen.test.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessagesHomeScreen.test.tsx.snap
  ts/features/messages/screens/legacy/LegacyMessagesHomeScreen.tsx
  ts/features/messages/screens/legacy/MessageListScreen.tsx
  ts/features/messages/store/actions/__tests__/preconditions.test.ts
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/actions/preconditions.ts
  ts/features/messages/store/reducers/__tests__/legacyMessagePrecondition.test.ts
  ts/features/messages/store/reducers/__tests__/messagePrecondition.test.ts
  ts/features/messages/store/reducers/index.ts
  ts/features/messages/store/reducers/legacyMessagePrecondition.ts
  ts/features/messages/store/reducers/messagePrecondition.ts
  ts/features/services/details/components/ServiceSpecialAction.tsx
  ts/store/reducers/__tests__/backendStatus.test.ts
  ts/store/reducers/backendStatus.ts
Labels: IO-Comunicazione

#5923 feat: [IOPID-1550] - Download User Data new DS integration
  locales/de/index.yml
  locales/en/index.yml
  locales/en/profile/profile_download_data.md
  locales/it/index.yml
  locales/it/profile/profile_download_data.md
  ts/components/BulletList.tsx
  ts/screens/profile/DownloadProfileDataScreen.tsx
Labels: IO-A&I

#5941 chore: [IOBP-727] Change label into transaction details error
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#5931 feat: [PE-617] Change labels in CGN Partner detail screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
Labels: Carta Giovani Nazionale

#5942 chore: [IOPAE-1191] Removal of `UserMetadata`
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/api/backend.ts
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/__tests__/persistedStore.test.ts
  ts/boot/configureStoreAndPersistor.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
  ts/sagas/user/userMetadata.ts
  ts/store/actions/types.ts
  ts/store/actions/userMetadata.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/__tests__/userMetadata.test.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
  ts/store/reducers/userMetadata.ts
  ts/store/reducers/utils.ts
Labels: IO - Enti & Servizi

#5935 feat: [IOCOM-1413] Archiving/Restoring of user messages, new Messages Home
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/Home/ArchiveRestoreBar.tsx
  ts/features/messages/components/Home/DS/DoubleAvatar.tsx
  ts/features/messages/components/Home/EmptyList.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/PagerViewContainer.tsx
  ts/features/messages/components/Home/Toasts.tsx
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__mocks__/SecuritySuggestions.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/messages/saga/__test__/handleUpsertMessageStatusAttribues.test.ts
  ts/features/messages/saga/handleUpsertMessageStatusAttribues.ts
  ts/features/messages/saga/handleUpsertMessageStatusAttributes.ts
  ts/features/messages/saga/index.ts
  ts/features/messages/screens/__tests__/MessagesHomeScreen.test.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessagesHomeScreen.test.tsx.snap
  ts/features/messages/store/actions/archiving.ts
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/allPaginated.ts
  ts/features/messages/store/reducers/archiving.ts
  ts/features/messages/store/reducers/index.ts
  ts/features/messages/utils/index.ts
  ts/features/pn/screens/LegacyAttachmentPreviewScreen.tsx
  ts/features/pn/store/reducers/index.ts
  ts/features/pushNotifications/sagas/__tests__/notifications.test.ts
  ts/features/pushNotifications/sagas/notifications.ts
  ts/features/pushNotifications/utils/configurePushNotification.ts
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/navigation/linkingSubscription.ts
  ts/navigation/params/AppParamsList.ts
  ts/screens/profile/__test__/LanguagesPreferencesScreen.test.tsx
  ts/utils/testWrapper.tsx
Labels: IO-Comunicazione

#5922 chore(IT Wallet): [SIW-1159] Add XState issuance machine scaffolding
  package.json
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/discovery/screens/__tests__/ItwDiscoveryInfoScreen.test.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationIdpSelectionScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationNfcInstructionsScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/actors.ts
  ts/features/itwallet/machine/credential/context.ts
  ts/features/itwallet/machine/credential/events.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/provider.tsx
  ts/features/itwallet/machine/tags.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/messages/components/Home/PreconditionsFooter.tsx
  ts/features/messages/components/Home/__tests__/Preconditions.test.tsx
  ts/hooks/useNavigationSwipeBackListener.tsx
  yarn.lock
Labels: IT Wallet

#5930 feat: [PE-615] Change labels in CGN card detail screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
Labels: Carta Giovani Nazionale

#5953 fix: [IOBP-742] Copy improvement
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#5955 fix: [IOBP-741] Copy fixes
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#5964 fix(Cross): I18n imports
  .eslintrc.js
  ts/components/AppVersion.tsx
  ts/components/ContextualInfo.tsx
  ts/components/__tests__/TosWebviewComponent.test.tsx
  ts/components/screens/IdpCustomContextualHelpContent.tsx
  ts/components/ui/LoadingIndicator.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
  ts/features/fastLogin/screens/FastLoginModals.tsx
  ts/features/fci/components/__tests__/__snapshots__/LoadingComponent.test.tsx.snap
  ts/features/lollipop/screens/UnsupportedDeviceScreen.tsx
  ts/features/payments/common/utils/index.ts
  ts/features/pn/components/LegacyMessagePayments.tsx
  ts/features/pn/components/MessagePayments.tsx
  ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx
  ts/screens/profile/playgrounds/MarkdownPlayground.tsx
Labels: Cross

#5932 chore(IT Wallet): [SIW-1313] Add IT Wallet trial system status
  package.json
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/utils/itwTrialUtils.ts
  ts/features/itwallet/playgrounds/components/ItwTrialSystemSection.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/trialSystem/api/client.ts
  ts/features/trialSystem/store/actions/index.ts
  ts/features/trialSystem/store/reducers/index.ts
  ts/screens/profile/TrialSystemPlayground.tsx
Labels: IT Wallet

#5967 chore:(Cross): align hotfix and app version
  CHANGELOG.md
  android/app/build.gradle
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/Info.plist
  ios/ItaliaAppTests/Info.plist
  package.json
  publiccode.yml
  ts/features/payments/checkout/navigation/navigator.tsx
  ts/features/payments/checkout/navigation/params.ts
  ts/features/payments/checkout/navigation/routes.ts
  ts/features/payments/checkout/screens/WalletPaymentFailureScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
Labels: Cross

#5933 chore: [IOPID-2006] Move profile section from Tab Bar to Header First Level
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/EmailForwardingScreen.tsx
  ts/screens/profile/ProfileMainScreen.tsx
  ts/store/reducers/backendStatus.ts
Labels: IO-A&I

#5971 chore: [IOPID-2032] Add fiscal code copy button
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/FiscalCodeScreen.tsx
Labels: IO-A&I

#5939 feat: [IOCOM-842] Local message search, new DS
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/Preconditions.tsx
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Search/EmptyList.tsx
  ts/features/messages/navigation/routes.ts
  ts/features/messages/screens/MessagesSearchScreen.tsx
  ts/features/messages/store/reducers/allPaginated.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/navigation/params/AppParamsList.ts
Labels: IO-Comunicazione

#5861 chore(IT Wallet): [SIW-975,SIW-976] Wallet instance registration and attestation retrieval
  .env.local
  .env.production
  ios/Podfile.lock
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/config.ts
  ts/features/bonus/cgn/saga/orchestration/activation/activationSaga.ts
  ts/features/itwallet/common/components/ItwCredentialClaimList.tsx
  ts/features/itwallet/common/components/ItwPidAssuranceLevel.tsx
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwIntegrityUtils.ts
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/issuance/store/actions/index.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/machine/credential/events.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/provider.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationEidDetailScreen.tsx
  ts/features/newWallet/components/WalletEmptyScreenContent.tsx
  ts/features/newWallet/navigation/index.tsx
  ts/features/newWallet/navigation/params.ts
  ts/features/newWallet/navigation/routes.ts
  ts/features/newWallet/screens/WalletCardOnboardingScreen.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  yarn.lock
Labels: IT Wallet

#5945 feat: [IOCOM-834] Auto refresh on new messages home
  ts/features/messages/components/Home/PagerViewContainer.tsx
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/components/__test__/MessageList.test.tsx
  ts/features/messages/components/__test__/MessagesInbox.test.tsx
  ts/features/messages/screens/__tests__/LegacyMessagesHomeScreen.test.tsx
  ts/features/messages/store/actions/__tests__/index.test.ts
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
Labels: IO-Comunicazione

#5980 fix(IT Wallet): [SIW-1361] Fix wallet onboarding screen
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
Labels: IT Wallet

#5934 chore(IT Wallet): [SIW-1319] Wallet Instance lifecycle reducer
  ts/features/common/store/reducers/index.ts
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/lifecycle/store/actions/index.ts
  ts/features/itwallet/lifecycle/store/reducers/index.ts
  ts/features/itwallet/lifecycle/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/lifecycle/store/selectors/index.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#5984 chore: [IOCOM-1595] New messages flows as default
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/features/euCovidCert/navigation/navigator.tsx
  ts/features/messages/components/Home/ArchiveRestoreBar.tsx
  ts/features/messages/components/Home/DS/MessageListItem.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
  ts/features/messages/components/MessageDetail/MessageMarkdown.tsx
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/navigation/navigator.tsx
  ts/hooks/useBottomTabNavigatorStyle.ts
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IO-Comunicazione

#5979 chore(IT Wallet): [SIW-1360] Add remote config for `it-wallet` feature
  .env.local
  .env.production
  package.json
  ts/config.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus.ts
Labels: IT Wallet

#5948 chore(IT Wallet): [SIW-1284] Add IT Wallet discovery banner for trial users
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/FooterStackButton.tsx
  ts/features/itwallet/common/components/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/__tests__/ItwDiscoveryBanner.test.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/features/newWallet/components/WalletCategoryFilterTabs.tsx
  ts/features/newWallet/components/WalletPaymentsRedirectBanner.tsx
  ts/features/newWallet/screens/WalletHomeScreen.tsx
  ts/features/newWallet/screens/__tests__/WalletHomeScreen.test.tsx
  ts/features/trialSystem/store/reducers/index.ts
Labels: IT Wallet

#5988 chore(IT Wallet): [SIW-1363] Add IT Wallet credential cards in wallet
  ts/features/design-system/core/DSCards.tsx
  ts/features/design-system/core/DSWallet.tsx
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/__tests__/ItwCredentialCard.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationEidDetailScreen.tsx
  ts/features/itwallet/wallet/components/ItwCredentialWalletCard.tsx
  ts/features/newWallet/components/WalletCardsCategoryContainer.tsx
  ts/features/newWallet/types/index.ts
Labels: IT Wallet

#5965 feat(IT Wallet): [SIW-1295] Add eID issuance flow with SPID and CieID
  .env.local
  .env.production
  android/app/src/main/AndroidManifest.xml
  ios/ItaliaApp/Info.plist
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/itwallet/common/components/ItwCredentialClaimList.tsx
  ts/features/itwallet/common/hooks/useItwDismissalDialog.tsx
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAuthScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidRequestScreen.tsx
  ts/features/itwallet/issuance/store/actions/index.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/issuance/store/selectors/index.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/failure.ts
  ts/features/itwallet/machine/eid/guards.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/eid/selectors.ts
  ts/features/itwallet/machine/provider.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/utils/__tests__/assert.test.ts
  ts/utils/assert.ts
Labels: IT Wallet

#5969 chore(IT Wallet): [SIW-1285] Update ITW credential catalog screen
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/onboarding/screens/__tests__/WalletCardOnboardingScreen.test.tsx
Labels: IT Wallet

#5990 fix: [IOCOM-1551] Additional margin for single CTA
  ts/features/messages/components/MessageDetail/MessageDetailsStickyFooter.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsStickyFooter.test.tsx.snap
Labels: IO-Comunicazione

#5995 fix(IT Wallet): [SIW-1369] Fetch function without session token
  ts/features/itwallet/api/client.ts
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/machine/eid/actors.ts
Labels: IT Wallet

#5997 chore: update EIC button scripts
  scripts/check_cie_button_exists/check_cie_button_exists_ios.py
  scripts/check_cie_button_exists/check_cie_button_exists_ios.test.py
Labels: IO-A&I

#5999 fix: [IOBP-776] PSP preselection with onUs attribute
  CHANGELOG.md
  android/app/build.gradle
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/Info.plist
  ios/ItaliaAppTests/Info.plist
  package.json
  publiccode.yml
  ts/features/payments/common/utils/index.ts
Labels: Bug 🐞, IO-Bonus e pagamenti

#5981 feat(IT Wallet): [SIW-1035] Add eID to wallet
  ios/Podfile.lock
  package.json
  ts/features/itwallet/common/components/__tests__/ItwDiscoveryBanner.test.tsx
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/store/storages/itwCredentialsStorage.ts
  ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
  ts/features/itwallet/credentials/saga/handleWalletCredentialsRehydration.ts
  ts/features/itwallet/credentials/store/actions/index.ts
  ts/features/itwallet/credentials/store/reducers/index.ts
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/issuance/store/actions/index.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/lifecycle/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/lifecycle/store/selectors/index.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/onboarding/screens/__tests__/WalletCardOnboardingScreen.test.tsx
  ts/features/itwallet/playgrounds/components/ItwLifecycleSection.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationEidDetailScreen.tsx
  yarn.lock
Labels: IT Wallet

#6000 chore: Bump Android `minSdkVersion` from `23` to `25`
  android/build.gradle
Labels: IO-A&I

#5987 feat: [IOPAE-1310] Reintroduced the status banner in the services home
  ts/features/services/home/screens/ServicesHomeScreen.tsx
Labels: IO - Enti & Servizi

#5998 chore: [IOCOM-1600] Bigger fonts on message list items
  package.json
  ts/features/messages/components/Home/DS/MessageListItem.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
  yarn.lock
Labels: IO-Comunicazione

#5978 chore: align default `tosVersion` to the remote one
  .eslintrc.js
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/tos/store/selectors/index.ts
  ts/features/wallet/onboarding/paypal/screen/__mocks__/psp.ts
  ts/features/wallet/onboarding/paypal/screen/__tests__/PspRadioItem.test.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx
  ts/screens/profile/TosScreen.tsx
  ts/screens/profile/__test__/TosScreen.test.tsx
  ts/screens/profile/components/ShareDataComponent/index.tsx
  ts/screens/profile/components/__test__/ShareDataComponent.test.tsx
  ts/utils/login.ts
Labels: IO-A&I

#6002 [IOCOm-1586] Standard heights for message list items
  ts/features/messages/components/Home/DS/CustomPressableListItemBase.tsx
  ts/features/messages/components/Home/DS/MessageListItem.tsx
  ts/features/messages/components/Home/DS/MessageListItemSkeleton.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/Footer.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
Labels: IO-Comunicazione

#6004 chore: [IOCOM-1549] Double avatar standard message detail
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/components/MessageDetail/OrganizationHeader.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsHeader.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/OrganizationHeader.test.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/pn/components/MessageDetails.tsx
Labels: IO-Comunicazione

#5970 chore(IT Wallet): [SIW-1191] Add wallet instance state check at start up
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/credentials/store/actions/index.ts
  ts/features/itwallet/credentials/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/credentials/store/reducers/index.ts
  ts/features/itwallet/issuance/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/lifecycle/store/actions/index.ts
  ts/features/itwallet/lifecycle/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/lifecycle/store/reducers/index.ts
  ts/features/itwallet/lifecycle/store/selectors/index.ts
  ts/features/itwallet/playgrounds/components/ItwLifecycleSection.tsx
  ts/features/newWallet/store/__tests__/cards.test.ts
  ts/features/newWallet/store/actions/cards.ts
  ts/features/newWallet/store/reducers/cards.ts
Labels: IT Wallet

#5996 feat: [IOPID-92] Add logic to use test login with lollipop
  ts/api/backendPublic.ts
  ts/features/lollipop/saga/index.ts
  ts/sagas/testLoginSaga.ts
  ts/screens/authentication/TestAuthenticationScreen.tsx
Labels: IO-A&I

#5963 feat: [IOPID-2016,IOPID-2017] Error handling during the app startup
  ts/features/startup/analytics/index.ts
  ts/features/startup/sagas/index.ts
  ts/features/startup/screens/errors/GetProfileEndpointTransientError.tsx
  ts/features/startup/screens/errors/GetSessionEndpointTransientError.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
  ts/screens/modal/RootModal.tsx
  ts/store/actions/startup.ts
  ts/store/reducers/startup.ts
Labels: IO-A&I

#6009 [IOCOM-1611] Proper selection feedback for single row message items
  ts/features/messages/components/Home/DS/CustomPressableListItemBase.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
Labels: IO-Comunicazione

#6010 fix: [IOPAE-1315] Fix organizationFiscalCode copy to clipboard value in service details screen
  ts/features/services/details/components/ServiceDetailsMetadata.tsx
Labels: IO - Enti & Servizi

#6013 fix: [IOCOM-1612] BUGFIX: FIMS decode error in iOS
  ts/features/fims/singleSignOn/saga/handleFimsAbortOrCancel.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/singleSignOn/saga/handleFimsResourcesDeallocation.ts
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
  ts/features/fims/singleSignOn/store/reducers/index.ts
Labels: IO-Comunicazione

#6015 chore(IT Wallet): [SIW-1376] Remove `TINIT-` prefix from eID fiscal code check
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/machine/eid/guards.ts
Labels: IT Wallet

#6012 fix(IT Wallet): [SIW-1374] Hang on retry or back action after error in issuance machine
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
Labels: IT Wallet

#5993 chore(IT Wallet): [SIW-1356] Update ToS and Privacy url
  locales/en/index.yml
  locales/it/index.yml
Labels: IT Wallet

#6006 chore(IT Wallet): [SIW-1367] Add credential details screen navigation from wallet
  ts/features/bonus/cgn/components/CgnWalletCard.tsx
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailFooter.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/itwallet/wallet/components/ItwCredentialWalletCard.tsx
  ts/features/newWallet/components/WalletCardPressableBase.tsx
  ts/features/payments/common/components/PaymentCardSmall.tsx
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCardSmall.test.tsx.snap
  ts/features/payments/wallet/components/PaymentWalletCard.tsx
Labels: IT Wallet

#6020 chore(IT Wallet): [SIW-1377] Remove eID issuance flow from ITW Playground
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
Labels: IT Wallet

#6007 chore(IT Wallet): [SIW-1370] Add badges to credential items on the catalog screen if they have already been added
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
Labels: IT Wallet

#5975 feat: [IOPID-2020] - IOMarkdown component
  package.json
  ts/components/IOMarkdown/index.tsx
  ts/components/IOMarkdown/markdownRenderer.ts
  ts/components/IOMarkdown/renderRules.tsx
  ts/components/IOMarkdown/types.ts
  ts/components/__tests__/IOMarkdown.test.tsx
  ts/components/__tests__/__snapshots__/IOMarkdown.test.tsx.snap
  ts/features/design-system/core/DSIOMarkdown.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/playgrounds/IOMarkdownPlayground.tsx
  ts/screens/profile/playgrounds/IOMarkdownSuggestions.tsx
  ts/utils/url.ts
  yarn.lock
Labels: IO-A&I

#6023 chore(IT Wallet): [SIW-1379] Add informational alerts in credential details screens
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwCredentialClaimsSection.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialClaimsSection.test.tsx.snap
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/presentation/components/ItwPresentationAlertsSection.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailFooter.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationAlertsSection.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
Labels: IT Wallet

#5950 feat: [IOBP-723,IOBP-772] Add mixpanel profile properties for the new payment flow
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/checkout/types/PaymentAnalytics.ts
  ts/features/payments/common/analytics/index.ts
  ts/features/payments/common/store/selectors/index.ts
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/wallet/store/selectors/index.ts
  ts/mixpanelConfig/profileProperties.ts
Labels: IO-Bonus e pagamenti

#5982 fix: [IOBP-774] Create transaction error blocking
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentCreateTransaction.test.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/store/actions/networking.ts
  ts/features/payments/checkout/store/reducers/index.ts
Labels: Bug 🐞, IO-Bonus e pagamenti

#6024 fix: remove header from `IdpSuccessfulAuthentication`
  ts/components/IdpSuccessfulAuthentication.tsx
  ts/screens/authentication/IdpLoginScreen.tsx
Labels: IO-A&I

#6025 fix: [IOCOM-1620] FIMS validity checks on flow starting CTA
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
Labels: IO-Comunicazione

#6008 fix: [IOBP-786] Transaction total amount and total amount message
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#5949 chore(Cross): [IOAPPX-341] Add dark mode support to the main `TabNavigator`
  ts/components/ui/IOScrollViewWithLargeHeader.tsx
  ts/hooks/useBottomTabNavigatorStyle.ts
  ts/navigation/TabNavigator.tsx
  ts/screens/profile/ProfileMainScreen.tsx
Labels: Design System, Dark mode 🌝, Cross

#6022 chore(IT Wallet): [SIW-1380] Add decoders for image without url schema and MDL privileges
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwCredentialClaimList.tsx
  ts/features/itwallet/common/components/ItwReleaserName.tsx
  ts/features/itwallet/common/utils/ItwCodecUtils.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
Labels: IT Wallet

#6026 chore(IT Wallet): [SIW-1381] Update `ToS` in preview credential screen
  locales/en/index.yml
  locales/it/index.yml
Labels: IT Wallet

#6011 feat(IT Wallet): [SIW-983,SIW-1292] Add CIE + pin identification method
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/features/itwallet/common/hooks/useItwPreventNavigationEvent.tsx
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwActivateNfcScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieExpiredOrInvalidScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCiePinScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieUnexpectedErrorScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieWrongCardScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieWrongCiePinScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/eid/selectors.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
Labels: IT Wallet

#5944 chore(Cross): [IOAPPX-338] Update the `Modules` docs in the DS section
  ts/features/design-system/core/DSModules.tsx
Labels: Design System, Cross

#5986 chore(Cross): [IOAPPX-348] Fix `VirtualizedLists` warning in the `PrivacyMainScreen`
  ts/screens/profile/PrivacyMainScreen.tsx
Labels: Cross

#6030 chore(IT Wallet): [SIW-1382] Remove TINIT prefix from fiscal code claim visualisation
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
Labels: IT Wallet

#6016 feat: [IOBP-790] Add local toggle to switch on/off the new "Scan" section
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/config.ts
  ts/navigation/TabNavigator.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IO-A&I, IO-Bonus e pagamenti

#6032 chore(IT Wallet): [SIW-1385] Update io-react-native-wallet to version v0.15.3
  package.json
  yarn.lock
Labels: IT Wallet

#5938 chore: Sort onboarded payment methods by creation date
  ts/features/payments/wallet/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5937 fix: [IOBP-739] Edit legacy transactions banner pictogram
  ts/features/payments/transaction/screens/PaymentsTransactionListScreen.tsx
Labels: IO-Bonus e pagamenti

#6021 chore: [IOCOM-1560] Fims history screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/common/utils/hooks.tsx
  ts/features/fims/history/components/FimsHistoryListItem.tsx
  ts/features/fims/history/components/FimsHistoryLoaders.tsx
  ts/features/fims/history/screens/HistoryScreen.tsx
  ts/features/fims/history/store/actions/index.ts
  ts/features/fims/history/store/reducer/index.ts
  ts/features/fims/history/store/selectors/index.ts
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/screens/profile/PrivacyMainScreen.tsx
  ts/utils/pot.ts
Labels: IO-Comunicazione

#6028 fix: [IOCOM-1614] Update iOS product name to "IO" from "ItaliaApp"
  .detoxrc.json
  .github/workflows/release.yml
  .github/workflows/test-e2e.yml
  ios/.gitignore
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp.xcodeproj/xcshareddata/xcschemes/ItaliaApp.xcscheme
Labels: IO-Comunicazione

#6005 chore: [IOBP-787] No payment method screen during payment flow
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentGetUserWallets.test.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetUserWallets.ts
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/store/actions/networking.ts
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
Labels: IO-Bonus e pagamenti

#6003 chore: [IOBP-781] Simplified disclaimer about legacy transactions
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#6031 chore(IT Wallet): [SIW-1384] Remove unique_id claim from eID
  ts/features/itwallet/common/components/ItwCredentialClaimList.tsx
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
Labels: IT Wallet

#6035 chore(IT Wallet): [SIW-1389] Generic error screen during wallet instance creation
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/machine/eid/failure.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6017 chore: [IOBP-788] Update disclaimer on real-time update notice amount
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#6037 chore(IT Wallet): [SIW-1395] Update io-react-native-wallet to version v0.15.4
  package.json
  ts/features/itwallet/common/utils/itwCredentialIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  yarn.lock
Labels: IT Wallet

#6038 chore(IT Wallet): [SIW-1397] Remove disability card
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/onboarding/screens/__tests__/WalletCardOnboardingScreen.test.tsx
Labels: IT Wallet

#5756 feat: [IOPLT-305] Add Sentry Tool for Crash reporting
  .env.local
  .env.production
  .github/workflows/release.yml
  .gitignore
  android/app/build.gradle
  index.js
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/Podfile.lock
  jest-e2e.config.js
  jest.config.js
  jest.config.no.timezone.js
  locales/en/index.yml
  locales/it/index.yml
  metro.config.js
  package.json
  scripts/android-release.sh
  scripts/ios-release-build.sh
  ts/App.tsx
  ts/config.ts
  ts/screens/profile/DeveloperModeSection.tsx
  yarn.lock
Labels: legal-approved ⚖️ ✅

#6019 chore(IT Wallet): [SIW-1359] Add production URLs
  .env.local
  .env.production
  ts/config.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
Labels: IT Wallet

#6040 chore(IT Wallet): [SIW-1399] Remove cta from presentation credential footer
  ts/features/itwallet/presentation/components/ItwPresentationDetailFooter.tsx
Labels: IT Wallet

#6039 chore(IT Wallet): [SIW-1398] Remove local feature flag
  .env.local
  .env.production
  locales/en/index.yml
  locales/it/index.yml
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/config.ts
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/onboarding/screens/__tests__/WalletCardOnboardingScreen.test.tsx
  ts/features/newWallet/components/WalletCardsContainer.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/backendStatus.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IT Wallet

#6044 fix(IT Wallet): [SIW-1403] Check CIE support independently of user authentication
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/identification/saga/handleCieSupportedSaga.ts
  ts/features/itwallet/identification/saga/index.ts
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/store/actions/index.ts
  ts/features/itwallet/identification/store/reducers/index.ts
  ts/features/itwallet/identification/store/selectors/index.ts
Labels: IT Wallet

#6046 chore(IT Wallet): [SIW-1405] Add WI reset button in IT Wallet playgrounds
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
Labels: IT Wallet

#6047 fix(IT Wallet): [SIW-1407] Add spacing in mDL banner text
  locales/en/index.yml
  locales/it/index.yml
Labels: IT Wallet

#6048 chore(IT Wallet): [SIW-1406] Remove gesture navigation in IT Wallet credential issuance screens
  ts/features/itwallet/common/hooks/useItwDisbleGestureNavigation.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
Labels: IT Wallet

#6029 fix: [IOBP-758] Refresh payments session token failure screens
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactionDetails.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactionReceipt.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactions.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetLatestBizEventsTransactions.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentAuthorization.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCreateTransaction.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentDeleteTransaction.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetAllMethods.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetDetails.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetTransactionInfo.ts
  ts/features/payments/checkout/saga/networking/handleWalletPaymentGetUserWallets.ts
  ts/features/payments/common/saga/handlePaymentsSessionToken.ts
  ts/features/payments/common/saga/handleResumePaymentsPendingActions.ts
  ts/features/payments/common/saga/index.ts
  ts/features/payments/common/store/actions/index.ts
  ts/features/payments/common/store/reducers/pagoPaPlatformReducer.ts
  ts/features/payments/common/store/selectors/index.ts
  ts/features/payments/common/utils/withPaymentsSessionToken.ts
  ts/features/payments/details/saga/handleDeleteWalletDetails.ts
  ts/features/payments/details/saga/handleGetWalletDetails.ts
  ts/features/payments/details/saga/handleTogglePagoPaCapability.ts
  ts/features/payments/onboarding/saga/handleGetPaymentMethods.ts
  ts/features/payments/onboarding/saga/handleStartWalletOnboarding.ts
  ts/features/payments/wallet/saga/handleGetPaymentsWalletUserMethods.ts
Labels: Bug 🐞, IO-Bonus e pagamenti

#6051 chore(IT Wallet): [SIW-1410] Update copy in issuer claim bottom sheet
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwReleaserName.tsx
Labels: IT Wallet

#6050 chore(IT Wallet): [SIW-1378] Remove image claim decoding without URL schema
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
Labels: IT Wallet

#6049 chore(IT Wallet): [SIW-1408] Add more info about failure in credential issuance failure screen
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
Labels: IT Wallet

#6058 chore(IT Wallet): [SIW-1416] Remove calendar icon in claim list
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
Labels: IT Wallet

#6045 chore: [IOPID-2050] Add session refresh Feature Flag
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/fastLogin/store/actions/index.ts
  ts/features/fastLogin/store/actions/sessionRefreshActions.ts
  ts/features/fastLogin/store/reducers/index.ts
  ts/features/fastLogin/store/reducers/sessionRefreshReducer.ts
  ts/features/fastLogin/store/selectors/index.ts
  ts/screens/profile/DeveloperModeSection.tsx
Labels: IO-A&I

#6055 chore(IT Wallet): [SIW-1415] Add debug info to IT Wallet screens in debug mode
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/components/DebugInfoOverlay.tsx
  ts/components/DebugPrettyPrint.tsx
  ts/components/debug/DebugDataIndicator.tsx
  ts/components/debug/DebugDataOverlay.tsx
  ts/components/debug/DebugPrettyPrint.tsx
  ts/components/debug/DebugView.tsx
  ts/components/debug/__tests__/DebugPrettyPrint.test.tsx
  ts/components/debug/__tests__/DebugView.test.tsx
  ts/components/debug/withDebugEnabled.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/hooks/useDebugInfo.ts
  ts/store/actions/debug.ts
  ts/store/reducers/debug.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
Labels: IT Wallet

#6066 chore: [IOPID-2077] Add correct title in settings section
  ts/screens/profile/ProfileMainScreen.tsx
Labels: IO-A&I

#6067 fix: regression inside `IdentificationModal` in `validatingTask` mode
  ts/screens/modal/IdentificationModal.tsx
Labels: IO-A&I

#5985 fix: [IOBP-773,IOBP-759] Hide dueDate if not provided in the payment details
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
Labels: dont-merge :raised_hand:, legal-review-needed ⚖️ ⛔, IO-Bonus e pagamenti

#6065 chore(IT Wallet): [SIW-1414] Disable swipe navigation in IT Wallet issuance flows
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidRequestScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
Labels: IT Wallet

#6063 fix(IT Wallet): [SIW-1429] Fix wallet content update after session refresh
  ts/features/newWallet/screens/WalletHomeScreen.tsx
Labels: IT Wallet

#6078 chore: [IOPID-2086] Fix LepidaID
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/store/reducers/authentication.ts
Labels: IO-A&I
