Repository pagopa/io-app, pull requests merged in 2024-02, with the labels that each got.

#5477 chore: [IOBP-526] Fix e2e test for manual input payment flow
  ts/__e2e__/payment.e2e.ts
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
Labels: IO-Bonus e pagamenti

#5475 feat: [IOCOM-676] Prevent Android 14 warning on SCHEDULE_EXACT_ALARM
  patches/patches.md
  patches/react-native-push-notification+7.3.1.patch
  patches/react-native-push-notification+8.1.1.patch
Labels: IO-Comunicazione

#5469 feat: [IOCOM-230] Use auto generated PN client
  package.json
  ts/features/pn/api/backendPn.ts
  ts/features/pn/api/client.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
Labels: IO-Comunicazione

#5473 chore(Firma con IO): [SFEQS-2099] Update`Firma con IO` specs
  CHANGELOG.md
  android/app/build.gradle
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/Info.plist
  ios/ItaliaAppTests/Info.plist
  package.json
  publiccode.yml
Labels: Firma con IO

#5461 feat: [IOCOM-867] Add service info in MessageDetailsScreen
  img/test/logo.png
  ts/features/messages/components/MessageDetail/MessageDetailHeader.tsx
  ts/features/messages/components/MessageDetail/OrganizationHeader.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailHeader.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/OrganizationHeader.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/OrganizationHeader.test.tsx.snap
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
Labels: IO-Comunicazione

#5377 feat(Firma con IO): [SFEQS-2071] Update `Firma con IO` with new DS components
  ts/features/fci/components/DocumentViewer.tsx
  ts/features/fci/components/DocumentWithSignature.tsx
  ts/features/fci/components/DocumentsNavigationBar.tsx
  ts/features/fci/components/ErrorComponent.tsx
  ts/features/fci/components/InfoScreenComponent.tsx
  ts/features/fci/components/LinkedText.tsx
  ts/features/fci/components/LoadingComponent.tsx
  ts/features/fci/components/QtspClauseListItem.tsx
  ts/features/fci/components/SignatureFieldItem.tsx
  ts/features/fci/components/SignatureRequestItem.tsx
  ts/features/fci/components/__tests__/DocumentsNavigationBar.test.tsx
  ts/features/fci/components/__tests__/LoadingComponent.test.tsx
  ts/features/fci/components/__tests__/QtspClauseListItem.test.tsx
  ts/features/fci/components/__tests__/SignatureFieldItem.test.tsx
  ts/features/fci/components/__tests__/__snapshots__/DocumentsNavigationBar.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/LinkedText.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/LoadingComponent.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/QtspClauseListItem.test.tsx.snap
  ts/features/fci/components/__tests__/__snapshots__/SignatureFieldItem.test.tsx.snap
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/fci/hooks/useFciCheckService.tsx
  ts/features/fci/hooks/useFciNoSignatureFields.tsx
  ts/features/fci/navigation/FciStackNavigator.tsx
  ts/features/fci/screens/FciRouterScreen.tsx
  ts/features/fci/screens/__tests__/FciDocumentsScreen.test.tsx
  ts/features/fci/screens/__tests__/FciThankyouScreen.test.tsx
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
  ts/features/fci/screens/valid/FciSignatureRequestsScreen.tsx
  ts/features/fci/screens/valid/FciThankyouScreen.tsx
Labels: Design System, Firma con IO

#5484 fix: [IOPID-1436], [IOPID-1453] Delete helper button and header title on email validate screen and add logic to show support buttons in faq screen
  ts/components/NewRemindEmailValidationOverlay.tsx
  ts/features/zendesk/components/ZendeskSupportComponent.tsx
  ts/store/reducers/assistanceTools.ts
  ts/utils/__tests__/supportAssistance.test.ts
  ts/utils/supportAssistance.ts
Labels: IO-A&I

#5479 chore: [IOBP-529] Retrieve payments methods list from eCommerce client endpoint
  package.json
  ts/features/walletV3/common/saga/index.ts
  ts/features/walletV3/details/types/UIWalletInfoDetails.ts
  ts/features/walletV3/payment/saga/index.ts
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentGetAllMethods.test.ts
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentGetUserWallets.test.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetAllMethods.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetUserWallets.ts
  ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/walletV3/payment/store/actions/networking.ts
  ts/features/walletV3/payment/store/actions/orchestration.ts
  ts/features/walletV3/payment/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#5478 fix: [IOBP-460,IOBP-461,IOBP-463] A11y for list item info components into transaction detail screen
  ts/features/walletV3/transaction/components/WalletTransactionInfoSection.tsx
Labels: a11y, IO-Bonus e pagamenti

#5487 chore: [IOBP-533] Navigation to payment confirm screen if method with only one PSP
  ts/features/walletV3/payment/saga/networking/__tests__/handleWalletPaymentCalculateFees.test.ts
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/walletV3/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/walletV3/payment/screens/WalletPaymentPickPspScreen.tsx
  ts/features/walletV3/payment/store/actions/networking.ts
  ts/features/walletV3/payment/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#5485 feat: [IOCOM-862,IOCOM-863] New DS on the message's attachments list
  locales/en/index.yml
  locales/it/index.yml
  ts/features/design-system/core/DSModules.tsx
  ts/features/messages/__mocks__/attachment.ts
  ts/features/messages/components/MessageAttachment/LegacyMessageAttachmentPreview.tsx
  ts/features/messages/components/MessageAttachment/__test__/LegacyMessageAttachmentPreview.test.tsx
  ts/features/messages/components/MessageDetail/LegacyMessageAttachments.tsx
  ts/features/messages/components/MessageDetail/LegacyModuleAttachment.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsAttachmentItem.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsAttachments.tsx
  ts/features/messages/components/MessageDetail/ModuleAttachment.tsx
  ts/features/messages/components/MessageDetail/__tests__/LegacyMessageAttachments.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsAttachmentItem.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsAttachments.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsAttachmentItem.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsAttachments.test.tsx.snap
  ts/features/messages/components/MessageDetail/index.tsx
  ts/features/messages/hooks/__tests__/useLegacyAttachmentDownload.test.ts
  ts/features/messages/hooks/useAttachmentDownload.tsx
  ts/features/messages/hooks/useLegacyAttachmentDownload.tsx
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/messages/navigation/params.ts
  ts/features/messages/saga/__test__/handleDownloadAttachment.test.ts
  ts/features/messages/saga/__test__/handleRequestInit.test.ts
  ts/features/messages/saga/handleDownloadAttachment.ts
  ts/features/messages/saga/handleRequestInit.ts
  ts/features/messages/screens/LegacyMessageAttachment.tsx
  ts/features/messages/screens/LegacyMessageDetailScreen.tsx
  ts/features/messages/screens/MessageAttachment.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/screens/__tests__/MessageAttachment.test.tsx
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/actions/navigation.ts
  ts/features/messages/store/reducers/__tests__/downloads.test.ts
  ts/features/messages/store/reducers/__tests__/thirdPartyById.test.ts
  ts/features/messages/store/reducers/__tests__/transformers.test.ts
  ts/features/messages/store/reducers/downloads.ts
  ts/features/messages/store/reducers/thirdPartyById.ts
  ts/features/messages/store/reducers/transformers.ts
  ts/features/messages/types/__tests__/digitalInformationUnit.test.ts
  ts/features/messages/types/digitalInformationUnit.ts
  ts/features/messages/types/index.ts
  ts/features/pn/analytics/index.ts
  ts/features/pn/components/LegacyMessageDetails.tsx
  ts/features/pn/components/MessageAttachments.tsx
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageF24.tsx
  ts/features/pn/components/__test__/LegacyMessageDetails.test.tsx
  ts/features/pn/components/__test__/MessageAttachments.test.tsx
  ts/features/pn/components/__test__/MessageF24.test.tsx
  ts/features/pn/hooks/useF24BottomSheet.tsx
  ts/features/pn/screens/AttachmentPreviewScreen.tsx
  ts/features/pn/screens/LegacyMessageDetailsScreen.tsx
  ts/features/pn/store/reducers/index.ts
  ts/features/pn/store/types/transformers.ts
  ts/features/pn/store/types/types.ts
  ts/features/pn/utils/index.ts
  ts/store/hooks.ts
Labels: IO-Comunicazione

#5493 fix: [IABT-1530] Enabled header shown property on Transaction details screens
  ts/features/walletV3/transaction/navigation/navigator.tsx
Labels: Bug 🐞, IO-Bonus e pagamenti

#5495 feat: [IOCOM-849,IOCOM-850] Add `MessageDetailsComponent` in the detail of a message
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/__mocks__/message.ts
  ts/features/messages/components/MessageDetail/MessageDetailHeader.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsTagBox.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailHeader.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsHeader.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/screens/__tests__/MessageDetailsScreen.test.tsx
  ts/features/messages/store/reducers/__tests__/detailsById.test.ts
  ts/features/messages/store/reducers/__tests__/thirdPartyById.test.ts
  ts/features/messages/store/reducers/detailsById.ts
  ts/features/messages/store/reducers/thirdPartyById.ts
  ts/features/messages/utils/index.ts
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/__test__/MessageDetails.test.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
Labels: IO-Comunicazione

#5459 chore(Cross): [IOAPPX-218] Add the new `Titillium Sans Pro` typeface to the codebase
  android/app/src/main/assets/fonts/TitilliumSansPro-Black.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-BlackItalic.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-Bold.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-BoldItalic.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-Italic.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-Light.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-LightItalic.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-Regular.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-Semibold.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-SemiboldItalic.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-Thin.otf
  android/app/src/main/assets/fonts/TitilliumSansPro-ThinItalic.otf
  android/link-assets-manifest.json
  assets/fonts/TitilliumSansPro-OFL.txt
  assets/fonts/TitilliumSansPro/TitilliumSansPro-Black.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-BlackItalic.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-Bold.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-BoldItalic.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-Italic.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-Light.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-LightItalic.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-Regular.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-Semibold.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-SemiboldItalic.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-Thin.otf
  assets/fonts/TitilliumSansPro/TitilliumSansPro-ThinItalic.otf
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/Info.plist
  ios/link-assets-manifest.json
  package.json
  react-native.config.js
  ts/components/core/fonts.ts
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  yarn.lock
Labels: Design System, Cross

#5474 chore: [IOBP-525] Fix payment authorization webview on Android devices
  package.json
  ts/screens/authentication/idpAuthSessionHandler.tsx
  ts/utils/analytics.ts
  yarn.lock
Labels: IO-Bonus e pagamenti

#5494 feat: [IOCOM-1012] Better accessibility on PDF preview with the new DS system
  locales/en/index.yml
  locales/it/index.yml
  ts/features/bonus/cgn/__e2e__/cgn.e2e.ts
  ts/features/messages/components/MessageAttachment/PdfViewer.tsx
  ts/features/messages/components/MessageAttachment/__test__/__snapshots__/PdfViewer.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
Labels: IO-Comunicazione

#5499 chore(Cross): [IOAPPX-246] Update `Podfile.lock` for `io-react-native-login-utils`
  ios/Podfile.lock
Labels: Cross

#5486 chore: [IOPID-1448] Fix double profile upsert
  ts/sagas/startup.ts
  ts/store/reducers/profile.ts
Labels: IO-A&I

#5496 fix: [IOPID-1423,IOPID-1439] Fix double MP event tracking
  ts/features/fastLogin/analytics/optinAnalytics.ts
  ts/screens/authentication/NewOptInScreen.tsx
Labels: IO-A&I

#5491 chore: [IOBP-535] Added german language for iOS app
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/de.lproj/InfoPlist.strings
  ios/ItaliaApp/de.lproj/Localizable.strings
Labels: i18n, Cross

#5454 chore(Cross): [IOAPPX-234] Remove `@react-native-picker/picker` dependency
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: 💀 Dead code, Cross

#5497 feat: [IOCOM-1011] Accessibility on "Includes Attachments"-Icon on the new DS Message Details screen
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/design-system/core/DSModules.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsAttachmentItem.tsx
  ts/features/messages/components/MessageDetail/ModuleAttachment.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsAttachments.test.tsx.snap
  ts/features/messages/screens/MessageAttachment.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  yarn.lock
Labels: IO-Comunicazione

#5502 chore: [IOPID-1416] Fix logic to show toast error
  ts/screens/services/ServicesHomeScreen.tsx
Labels: Bug 🐞, IO-A&I

#5505 fix: [IOPID-1546] Fix services refresh token error
  ts/features/fastLogin/saga/utils/index.ts
  ts/sagas/profile.ts
  ts/sagas/services/servicePreference/handleGetServicePreferenceSaga.ts
  ts/sagas/services/servicePreference/handleUpsertServicePreferenceSaga.ts
  ts/sagas/startup/__tests__/loadServiceDetailRequestHandler.test.ts
  ts/sagas/startup/__tests__/loadVisibleServicesHandler.test.ts
  ts/sagas/startup/loadServiceDetailRequestHandler.ts
  ts/sagas/startup/loadVisibleServicesHandler.ts
  ts/sagas/user/userMetadata.ts
Labels: IO-A&I

#5508 feat: [IOCOM-1029] Add support for multi image in the detail of a message
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/components/MessageDetail/OrganizationHeader.tsx
Labels: IO-Comunicazione

#5470 chore(Cross): [IOAPPX-242] Replace legacy `FooterWithButtons` in the 'Remove account' flow
  ts/navigation/ProfileNavigator.tsx
  ts/screens/profile/RemoveAccountDetailsScreen.tsx
  ts/screens/profile/RemoveAccountInfoScreen.tsx
  ts/screens/profile/RemoveAccountSuccessScreen.tsx
Labels: Design System, Cross

#5500 chore(Cross): [IOAPPX-245] Remove `hound.yml`
  .hound.yml
Labels: Cross

#5472 chore(Cross): [IOAPPX-241] Replace legacy `FooterWithButtons` in the `DownloadProfileData` screen
  ts/navigation/ProfileNavigator.tsx
  ts/screens/profile/DownloadProfileDataScreen.tsx
Labels: Design System, Cross

#5482 chore(Cross): [IOAPPX-243] Remove `native-base` components from private screens + Add new header managed by `react-navigation`
  ts/components/DevScreenButton.tsx
  ts/features/design-system/core/DSLegacyButtons.tsx
  ts/features/design-system/core/DSToastNotifications.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/features/lollipop/playgrounds/LollipopPlayground.tsx
  ts/features/lollipop/playgrounds/LollipopPlaygroundContent.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/development/MarkdownScreen.tsx
  ts/screens/profile/CgnLandingPlayground.tsx
  ts/screens/profile/WebPlayground.tsx
  ts/screens/profile/playgrounds/MarkdownPlayground.tsx
  ts/screens/profile/playgrounds/WalletPlayground.tsx
Labels: Design System, NativeBase dismissal 🥷🏼, Cross

#5501 chore(Cross): [IOAPPX-247] Remove `_editorconfig`
  _editorconfig
Labels: Cross

#5507 feat: [IOCOM-851] Add `Alert` in the detail of a message that contains an expiring payment
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/screens/__tests__/MessageDetailsScreen.test.tsx
Labels: IO-Comunicazione

#5509 fix: [IOCOM-1091] Fix for duplicate message in messages list
  ts/features/messages/components/MessageList/index.tsx
Labels: IO-Comunicazione

#5515 chore: [IOBP-549] Add new wallet payments history tracking
  ts/features/walletV3/common/store/actions/index.ts
  ts/features/walletV3/common/store/reducers/index.ts
  ts/features/walletV3/history/store/__tests__/store.test.ts
  ts/features/walletV3/history/store/actions/index.ts
  ts/features/walletV3/history/store/reducers/index.ts
  ts/features/walletV3/history/store/selectors/index.ts
  ts/features/walletV3/history/types/index.ts
  ts/features/walletV3/payment/hooks/usePaymentFailureSupportModal.tsx
  ts/features/walletV3/payment/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/walletV3/payment/store/__tests__/store.test.ts
  ts/features/walletV3/payment/store/reducers/index.ts
  ts/features/walletV3/payment/types/index.ts
  ts/screens/profile/playgrounds/WalletPaymentPlayground.tsx
  ts/screens/profile/playgrounds/utils.ts
Labels: IO-Bonus e pagamenti

#5511 feat: [IOCOM-851] Removed view reference
  package.json
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  yarn.lock
Labels: IO-Comunicazione

#5451 chore(Cross): [IOAPPX-230] Remove `datetimepicker` and `react-native-modal-datetime-picker` dependencies
  android/app/build.gradle
  android/settings.gradle
  ios/Podfile.lock
  jest-e2e.config.js
  jest.config.js
  jest.config.no.timezone.js
  package.json
  ts/components/ui/DateTimePicker.tsx
  yarn.lock
Labels: 💀 Dead code, Cross

#5523 feat: [IOCOM-1059] Remove 'Open' CTA on Android attachment preview (new DS)
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/components/__tests__/__snapshots__/LoadingSpinnerOverlay.test.tsx.snap
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/features/messages/screens/MessageAttachment.tsx
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  yarn.lock
Labels: IO-Comunicazione

#5522 fix(Cross): [IOAPPX-250] Crash when consuming safe area insets outside of navigation context
  ts/App.tsx
Labels: Cross

#5528 chore: [IOBP-557] Handled 404 response status with empty list from user wallet list
  ts/features/walletV3/payment/saga/networking/handleWalletPaymentGetUserWallets.ts
Labels: IO-Bonus e pagamenti

#5524 feat: [IOCOM-851] Add calendar event for messages with `due_date`
  locales/en/index.yml
  locales/it/index.yml
  ts/components/CalendarList.tsx
  ts/features/messages/components/MessageDetail/CalendarEventButton.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsReminder.tsx
  ts/features/messages/hooks/useMessageCalendar.ts
  ts/features/messages/hooks/useMessageReminder.ts
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/messages/navigation/params.ts
  ts/features/messages/navigation/routes.ts
  ts/features/messages/screens/MessageCalendarScreen.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/store/reducers/entities/calendarEvents/calendarEventsByMessageId.ts
  ts/utils/calendar.ts
Labels: IO-Comunicazione

#5527 chore: [IOBP-555] Add payment outcome screen for the outcome 17 and 15
  locales/en/index.yml
  locales/it/index.yml
  ts/features/walletV3/payment/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/walletV3/payment/types/PaymentOutcomeEnum.ts
Labels: IO-Bonus e pagamenti

#5519 feat: [IOCOM-848] Message content with new DS System
  ts/components/FAQComponent.tsx
  ts/components/RemindEmailValidationOverlay.tsx
  ts/components/cie/CieNotSupported.tsx
  ts/components/markdown/MarkdownBaseScreen.tsx
  ts/components/screens/BaseScreenComponent/utils.tsx
  ts/components/screens/IdpCustomContextualHelpContent.tsx
  ts/components/ui/Accordion.tsx
  ts/components/ui/Markdown/LegacyMarkdown.tsx
  ts/components/ui/Markdown/LoadingSkeleton.tsx
  ts/components/ui/Markdown/Markdown.tsx
  ts/components/ui/Markdown/MarkdownWebviewComponent.tsx
  ts/components/ui/Markdown/utils.ts
  ts/features/bonus/cgn/components/detail/eyca/EycaInformationComponent.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
  ts/features/euCovidCert/components/MarkdownHandleCustomLink.tsx
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/idpay/details/components/InitiativeRulesInfoBox.tsx
  ts/features/idpay/onboarding/components/OnboardingDescriptionMarkdown.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/components/MessageDetail/MessageMarkdown.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/index.tsx
  ts/features/messages/components/PreconditionBottomSheet/PreconditionContent.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/utils/messages.ts
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageDetailsContent.tsx
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageDetailsContent.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/features/wallet/component/features/PagoPaPaymentCapability.tsx
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/cie/CieAuthorizeDataUsageScreen.tsx
  ts/screens/authentication/cie/CiePinLockedTemporarilyScreen.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  ts/screens/authentication/idpAuthSessionHandler.tsx
  ts/screens/modal/RootedDeviceModal.tsx
  ts/screens/profile/DownloadProfileDataScreen.tsx
  ts/screens/profile/ProfileAboutApp.tsx
  ts/screens/profile/components/ShareDataComponent.tsx
  ts/screens/profile/components/services/ManualConfigBottomSheet.tsx
  ts/screens/profile/playgrounds/MarkdownPlayground.tsx
  ts/screens/services/ServiceDetailsScreen.tsx
Labels: IO-Comunicazione

#5537 feat: [IOCOM-881] Update message attachment preview
  ts/features/messages/components/MessageAttachment/MessageAttachment.tsx
  ts/features/messages/components/MessageDetail/index.tsx
  ts/features/messages/hooks/useAttachmentDownload.tsx
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/messages/navigation/params.ts
  ts/features/messages/screens/MessageAttachmentScreen.tsx
  ts/features/messages/screens/MessageCalendarScreen.tsx
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/screens/MessageRouterScreen.tsx
  ts/features/messages/screens/__tests__/MessageAttachment.test.tsx
  ts/features/messages/store/actions/navigation.ts
  ts/features/pn/components/LegacyMessageDetails.tsx
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/navigation/params.ts
  ts/features/pn/screens/LegacyAttachmentPreviewScreen.tsx
  ts/features/pn/screens/MessageAttachmentScreen.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/screens/PaidPaymentScreen.tsx
  ts/features/pn/screens/__test__/PaidPaymentScreen.test.tsx
  ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
Labels: IO-Comunicazione

#5514 chore: [IOPID-1481], [IOPID-1482] Countdown 60 seconds
  .env.local
  locales/en/index.yml
  locales/it/index.yml
  ts/components/NewRemindEmailValidationOverlay.tsx
  ts/components/__tests__/NewRemindEmailValidationOverlay.test.tsx
  ts/components/countdown/CountdownProvider.tsx
  ts/screens/profile/CduEmailInsertScreen.tsx
Labels: IO-A&I

#5540 chore: [IOBP-572] Move currency symbol to the right of the amount
  ts/features/walletV3/payment/screens/WalletPaymentDetailScreen.tsx
  ts/screens/wallet/payment/components/TransactionSummary.tsx
Labels: IO-Bonus e pagamenti

#5539 fix: [IOBP-542] StatusBar background color for Android devices in wallet details screen
  ts/features/wallet/common/BasePaymentMethodScreen.tsx
  ts/features/walletV3/details/components/WalletDetailsPaymentMethodScreen.tsx
Labels: Bug 🐞, IO-Bonus e pagamenti

#5543 fix(Firma con IO): [SFEQS-2124] Wrong margins in FCI flow
  ts/features/fci/components/DocumentWithSignature.tsx
  ts/features/fci/components/ErrorComponent.tsx
  ts/features/fci/components/LoadingComponent.tsx
  ts/features/fci/components/__tests__/__snapshots__/LoadingComponent.test.tsx.snap
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/fci/screens/valid/FciDataSharingScreen.tsx
  ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
  ts/features/fci/screens/valid/FciDocumentsScreen.tsx
  ts/features/fci/screens/valid/FciQtspClausesScreen.tsx
  ts/features/fci/screens/valid/FciSignatureFieldsScreen.tsx
  ts/features/fci/screens/valid/FciSignatureRequestsScreen.tsx
  ts/features/fci/screens/valid/FciThankyouScreen.tsx
Labels: Firma con IO

#5545 fix(Firma con IO): [SFEQS-2123] Loading spinner not following DS toggle
  ts/features/fci/components/LoadingComponent.tsx
  ts/features/fci/components/__tests__/__snapshots__/LoadingComponent.test.tsx.snap
Labels: Firma con IO

#5425 feat(Firma con IO): [SFEQS-2083] Replace abort bottom sheet with alert
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
Labels: Firma con IO

#5525 chore: [IOBP-498] Adds stepper in payment's screens header
  ts/features/payments/payment/components/WalletPaymentConfirmContent.tsx
  ts/features/payments/payment/components/WalletPaymentHeader.tsx
  ts/features/payments/payment/navigation/navigator.tsx
  ts/features/payments/payment/navigation/params.ts
  ts/features/payments/payment/navigation/routes.ts
  ts/features/payments/payment/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/payment/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/payment/screens/WalletPaymentMakeScreen.tsx
  ts/features/payments/payment/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/payment/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/payment/store/__tests__/store.test.ts
  ts/features/payments/payment/store/actions/orchestration.ts
  ts/features/payments/payment/store/reducers/index.ts
  ts/features/payments/payment/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5401 chore: [IOBP-503] Add payment attempts tracking
  ts/boot/configureStoreAndPersistor.ts
  ts/features/payments/history/store/actions/index.ts
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/history/store/selectors/index.ts
  ts/features/payments/history/types/index.ts
  ts/features/payments/payment/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/payments/payment/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/payment/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#5488 chore: [IOBP-530] Removed CTA button in payment confirmation screen with one PSP element
  package.json
  ts/features/payments/payment/components/WalletPaymentConfirmContent.tsx
  yarn.lock
Labels: IO-Bonus e pagamenti

#5550 feat: [IOCOM-1051] Native HTTP client
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IO-Comunicazione

#5536 feat: [IOPID-1501] Adapt LandingScreen to the new DS
  img/landing/01.png
  img/landing/02.png
  img/landing/03.png
  img/landing/04.png
  img/landing/05.png
  img/landing/session_expired.png
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/LandingCardComponent.tsx
  ts/features/design-system/core/DSLegacyIllustrations.tsx
  ts/features/design-system/core/DSLegacyPictograms.tsx
  ts/hooks/useHeaderSecondLevel.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/NewOptInScreen.tsx
  ts/screens/authentication/analytics/carouselAnalytics.ts
  ts/screens/authentication/carousel/Carousel.tsx
  ts/screens/modal/RootedDeviceModal.tsx
Labels: IO-A&I
