Repository pagopa/io-app, pull requests merged in 2024-06, with the labels that each got.

#5791 chore(IT Wallet): [SIW-1153] Add SPID identification flow
  ts/features/itwallet/common/utils/itwErrorsUtils.ts
  ts/features/itwallet/discovery/components/ItwMarkdown.tsx
  ts/features/itwallet/identification/hooks/useItwIdpIdentification.ts
  ts/features/itwallet/identification/screens/ItwIdentificationIdpSelectionScreen.tsx
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
Labels: IT Wallet

#5806 feat: [IOCOM-1335,IOCOM-1421] FIMS flow loading screens
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/saga/index.tsx
  ts/features/fims/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/store/actions/index.ts
  ts/features/fims/store/reducers/index.ts
Labels: IO-Comunicazione

#5807 chore(Cross): [IOAPPX-306] Add deprecation note to `BaseScreenComponent` and its related components
  ts/components/buttons/FooterStackButtons.tsx
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/components/screens/DarkLayout.tsx
  ts/components/screens/TopScreenComponent.tsx
  ts/features/itwallet/common/components/FooterStackButton.tsx
Labels: Cross

#5802 fix: [IOPID-1880] Fix `/logout` api call always in `401`
  ts/components/screens/LogoutScreen.tsx
  ts/features/fastLogin/saga/tokenRefreshSaga.ts
  ts/features/fastLogin/screens/FastLoginModals.tsx
  ts/features/pushNotifications/sagas/__tests__/notifications.test.ts
  ts/sagas/startup/__tests__/watchLogoutSaga.test.ts
  ts/sagas/startup/watchLogoutSaga.ts
  ts/screens/profile/RemoveAccountSuccessScreen.tsx
  ts/store/actions/authentication.ts
  ts/store/reducers/__tests__/persistedPreferences.test.ts
Labels: IO-A&I

#5803 chore: [IOBP-665,IOBP-570] PayPal metadata and latest used payment method adaption
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/payments/checkout/components/CheckoutPaymentMethodsList.tsx
  ts/features/payments/checkout/saga/networking/__tests__/handleWalletPaymentGetUserWallets.test.ts
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
  ts/features/payments/checkout/utils/index.ts
Labels: IO-Bonus e pagamenti

#5737 feat: [IOPID-1507,IOPID-1533] Integrate new DS in Pin Screen flow
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/__e2e__/utils.ts
  ts/components/BulletList.tsx
  ts/components/Carousel.tsx
  ts/components/PinCreationForm.tsx
  ts/components/PinSelectionComponent.tsx
  ts/components/__tests__/PinCreationForm.test.tsx
  ts/components/screens/PinCreation/PinCarouselItem.tsx
  ts/components/screens/PinCreation/PinCreation.tsx
  ts/components/screens/PinCreation/usePinValidationBottomSheet.tsx
  ts/components/screens/__tests__/PinCreation.test.tsx
  ts/hooks/useCreatePin.tsx
  ts/navigation/OnboardingNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/sagas/startup/checkConfiguredPinSaga.ts
  ts/screens/onboarding/OnboardingPinScreen.tsx
  ts/screens/profile/PinScreen.tsx
  ts/utils/hooks/useOnboardingAbortAlert.ts
Labels: IO-A&I

#5818 fix: e2e login when `PosteID` is hidden
  ts/__e2e__/utils.ts
  ts/components/IdpsGrid.tsx
  ts/screens/authentication/IdpSelectionScreen.tsx
Labels: IO-A&I

#5792 feat(IT Wallet): [SIW-1022] Add PIN/biometric authorization for eID store action
  locales/en/index.yml
  locales/it/index.yml
  ts/features/common/store/reducers/index.ts
  ts/features/itwallet/common/hooks/useItwDismissalDialog.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
Labels: IT Wallet

#5815 chore: [IOPAE-1206] Replace `TextInput` with `SearchInput` in the services section
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/design-system/core/DSLayout.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/search/screens/SearchScreen.tsx
  yarn.lock
Labels: IO - Enti & Servizi

#5824 chore: [IOPAE-1212] Added button to navigate the search screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/services/home/hooks/useInstitutionsFetcher.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
Labels: IO - Enti & Servizi

#5828 fix: `pot` import
  ts/features/idpay/details/store/__test__/store.test.ts
  ts/features/idpay/timeline/store/__test__/store.test.ts
  ts/features/messages/components/__test__/MessageList.test.tsx
  ts/features/messages/components/__test__/MessagesInbox.test.tsx
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/__tests__/detailsById.test.ts
  ts/features/messages/store/reducers/__tests__/paginatedById.test.ts
  ts/screens/onboarding/__tests__/OnboardingTosScreen.test.tsx
  ts/screens/profile/LanguagesPreferencesScreen.tsx
  ts/screens/profile/__test__/TosScreen.test.tsx
Labels: Cross

#5829 chore: [IOPAE-1221] Enable new services section by default
  .env.local
  .env.production
  ts/config.ts
  ts/features/services/common/navigation/navigator.tsx
  ts/features/services/common/saga/index.ts
  ts/navigation/TabNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: IO - Enti & Servizi

#5811 chore(Cross): [IOAPPX-309] Add `useFooterActionsMeasurements` hook
  ts/features/design-system/core/DSFooterActions.tsx
  ts/hooks/useFooterActionsMeasurements.ts
  ts/screens/wallet/payment/TransactionSummaryScreen.tsx
Labels: Design System, Cross

#5821 feat: [IOPID-1532] Integrate new DS in Security Screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/SecurityScreen.tsx
  ts/screens/profile/__test__/SecurityScreen.test.tsx
Labels: IO-A&I

#5820 chore: [IOCOM-1422,IOCOM-1425,IOCOM-1426] FIMS Consents screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/components/FimsSuccessBody.tsx
  ts/features/fims/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/store/reducers/index.ts
  ts/features/fims/types/index.ts
Labels: IO-Comunicazione

#5834 chore: [IOBP-635] Removed FF from the new transaction details screen
  ts/screens/wallet/WalletHomeScreen.tsx
Labels: IO-Bonus e pagamenti

#5813 [IOCOM-1404, IOCOM-1405] Empty list and error component
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/components/Home/EmptyList.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/__tests__/EmptyList.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/EmptyList.test.tsx.snap
  ts/features/messages/screens/legacy/MessageListScreen.tsx
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
  ts/features/messages/types/__test__/messageListCategory.test.ts
  ts/features/messages/types/messageListCategory.ts
Labels: IO-Comunicazione

#5839 chore: [IOPAE-1236] Add conditional fontFamily for `OrganizationNameLabel` based on `useIOExperimentalDesign`
  ts/features/services/home/components/OrganizationNameLabel.tsx
Labels: IO - Enti & Servizi

#5840 chore: [IOPAE-1237] Add singular/plural services count locales into `InstitutionServicesScreen`
  locales/en/index.yml
  locales/it/index.yml
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
Labels: IO - Enti & Servizi

#5835 fix: [IOBP-684] Navigation to the payments home when payment success
  ts/features/payments/barcode/screens/PaymentsBarcodeChoiceScreen.tsx
  ts/features/payments/barcode/screens/PaymentsBarcodeScanScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentInputFiscalCodeScreen.tsx
Labels: IO-Bonus e pagamenti

#5844 chore: [IOPAE-1240] Restore scroll to top in the `ServicesHomeScreen`
  ts/features/services/home/screens/ServicesHomeScreen.tsx
Labels: IO - Enti & Servizi

#5804 chore: [IOPAE-1187] Add services Mixpanel analytics events
  ts/features/bonus/cgn/components/CgnServiceCTA.tsx
  ts/features/pn/components/ServiceCTA.tsx
  ts/features/services/common/analytics/index.ts
  ts/features/services/details/components/ServiceDetailsMetadata.tsx
  ts/features/services/details/components/ServiceDetailsPreferences.tsx
  ts/features/services/details/components/ServiceSpecialAction.tsx
  ts/features/services/details/screens/ServiceDetailsScreen.tsx
  ts/features/services/home/components/FeaturedInstitutionList.tsx
  ts/features/services/home/components/FeaturedServiceList.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
  ts/features/services/search/screens/SearchScreen.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/store/middlewares/analytics.ts
  ts/store/middlewares/serviceAnalytics.ts
Labels: IO - Enti & Servizi

#5838 chore: [IOBP-690] Add pre-selection psp logic for payment methods with pspId indicated
  ts/features/payments/checkout/saga/networking/handleWalletPaymentCalculateFees.ts
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/store/actions/networking.ts
Labels: IO-Bonus e pagamenti

#5816 chore: [IOCOM-1498] FIMS InApp Browser's cookie sharing on iOS
  ios/Podfile.lock
  package.json
  ts/features/fims/saga/index.tsx
  yarn.lock
Labels: IO-Comunicazione

#5768 feat: [IOBP-637,IOBP-440] New transactions list and details with biz events integration
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsListItemTransaction.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionCartList.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionTotalAmount.tsx
  ts/features/payments/bizEventsTransaction/navigation/navigator.tsx
  ts/features/payments/bizEventsTransaction/navigation/params.ts
  ts/features/payments/bizEventsTransaction/navigation/routes.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactionDetails.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactions.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetLatestBizEventsTransactions.ts
  ts/features/payments/bizEventsTransaction/saga/index.ts
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsCartItemDetailsScreen.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsDetailsScreen.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
  ts/features/payments/bizEventsTransaction/store/actions/index.ts
  ts/features/payments/bizEventsTransaction/store/reducers/index.ts
  ts/features/payments/bizEventsTransaction/store/selectors/index.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
  ts/features/payments/bizEventsTransaction/utils/types.ts
  ts/features/payments/common/api/client.ts
  ts/features/payments/common/saga/index.ts
  ts/features/payments/common/store/actions/index.ts
  ts/features/payments/common/store/reducers/index.ts
  ts/features/payments/common/utils/index.ts
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/features/payments/home/screens/__tests__/PaymentsHomeScreen.test.tsx
  ts/features/payments/home/store/selectors/index.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  yarn.lock
Labels: IO-Bonus e pagamenti

#5814 [IOCOM-1468,IOCOM-1497] react-native-webview upgraded to lastest
  ios/Podfile.lock
  package.json
  patches/react-native-webview+13.10.3.patch
  patches/react-native-webview+13.8.1.patch
  yarn.lock
Labels: IO-Comunicazione

#5843 chore: [IOCOM-1424,IOCOM-1428] FIMS flow cancelling
  locales/en/index.yml
  locales/it/index.yml
  ts/features/fims/components/FimsSuccessBody.tsx
  ts/features/fims/navigation/index.tsx
  ts/features/fims/saga/handleFimsAbortOrCancel.ts
  ts/features/fims/saga/handleFimsGetConsentsList.ts
  ts/features/fims/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/saga/handleFimsResourcesDeallocation.ts
  ts/features/fims/saga/index.tsx
  ts/features/fims/saga/sagaUtils.ts
  ts/features/fims/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/store/actions/index.ts
  ts/features/fims/store/reducers/index.ts
  ts/features/fims/types/index.ts
Labels: IO-Comunicazione

#5819 chore(IT Wallet): [SIW-1165] Add status banner to warn about iOS version upgrade to 14
  locales/en/index.yml
  locales/it/index.yml
  ts/features/messages/screens/legacy/LegacyMessagesHomeScreen.tsx
Labels: IT Wallet

#5827 fix: [IOCOM-1501] Fixed unresponsive PagerView on Home after fast login
  ts/features/messages/components/Home/PagerViewContainer.tsx
  ts/features/messages/components/Home/TabNavigationContainer.tsx
  ts/features/messages/components/Home/__tests__/PagerViewContainer.test.tsx
  ts/features/messages/components/Home/__tests__/TabNavigationContainer.test.tsx
Labels: IO-Comunicazione

#5837 chore: [IOCOM-1499] All query params are signed with lollipop on RP redirect url
  ts/features/fims/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
Labels: IO-Comunicazione

#5848 chore: [IOPAE-1231] Update mixpanel trackServiceDetailsCtaTapped event props
  ts/features/services/common/analytics/index.ts
  ts/features/services/details/screens/ServiceDetailsScreen.tsx
Labels: IO - Enti & Servizi

#5849 chore: [IOPAE-1249] Fix the endless loop of FlatList's `onEndReached`
  ts/features/services/home/hooks/useInstitutionsFetcher.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
Labels: IO - Enti & Servizi

#5847 chore: [IOCOM-1479] `organization_fiscal_code` from `GET /messages`
  package.json
  ts/features/messages/__mocks__/messages.ts
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
  ts/features/messages/store/reducers/transformers.ts
  ts/features/messages/types/index.ts
Labels: IO-Comunicazione

#5851 fix: Add user feedback when `Locale` changes
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/LanguagesPreferencesScreen.tsx
Labels: IO-A&I

#5836 chore: [IOBP-681] Add PSP details alert into payment method details if provided
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/details/components/PaymentsMethodPspDetailsAlert.tsx
  ts/features/payments/details/components/PaymentsMethodPspDetailsBottomSheet.tsx
  ts/features/payments/details/screens/PaymentsMethodDetailsScreen.tsx
Labels: IO-Bonus e pagamenti

#5796 feat: [IOBP-636,IOBP-646] Add legacy transactions list
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsListScreen.tsx
  ts/features/payments/home/components/PaymentsHomeEmptyScreenContent.tsx
  ts/features/payments/transaction/components/PaymentsLegacyAttachmentBottomSheet.tsx
  ts/features/payments/transaction/components/PaymentsLegacyListItemTransaction.tsx
  ts/features/payments/transaction/components/PaymentsLegacyTransactionsEmptyContent.tsx
  ts/features/payments/transaction/components/WalletTransactionInfoSection.tsx
  ts/features/payments/transaction/navigation/navigator.tsx
  ts/features/payments/transaction/navigation/params.ts
  ts/features/payments/transaction/navigation/routes.ts
  ts/features/payments/transaction/screens/PaymentsTransactionDetailsScreen.tsx
  ts/features/payments/transaction/screens/PaymentsTransactionListScreen.tsx
  ts/features/payments/transaction/screens/PaymentsTransactionOperationDetails.tsx
  ts/features/payments/transaction/store/selectors/index.ts
Labels: IO-Bonus e pagamenti

#5853 chore: [IOPAE-1250] Hide error toasts on refresh session
  package.json
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminder.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpired.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpiring.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageCancelledContent.test.tsx.snap
  ts/features/services/details/saga/handleGetServicePreference.ts
  ts/features/services/details/saga/handleServiceDetails.ts
  ts/features/services/details/saga/handleUpsertServicePreference.ts
  ts/features/services/home/saga/handleFindInstitutions.ts
  ts/features/services/home/saga/handleGetFeaturedInstitutions.ts
  ts/features/services/home/saga/handleGetFeaturedServices.ts
  ts/features/services/institution/saga/handleFindInstitutionServices.ts
  ts/features/services/search/saga/handleFindInstitutions.ts
  yarn.lock
Labels: IO - Enti & Servizi

#5856 chore: [IOPAE-1235] Search screen enhancements
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/services/common/navigation/navigator.tsx
  ts/features/services/common/navigation/params.ts
  ts/features/services/home/components/FeaturedInstitutionList.tsx
  ts/features/services/home/components/FeaturedServiceList.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/search/hooks/useInstitutionsFetcher.tsx
  ts/features/services/search/screens/SearchScreen.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/components/HeaderFirstLevelHandler.tsx
  ts/navigation/params/AppParamsList.ts
  yarn.lock
Labels: IO - Enti & Servizi

#5797 feat: [IOBP-652] Add biz events download PDF receipt
  locales/en/index.yml
  locales/it/index.yml
  patches/patches.md
  patches/react-native+0.70.15.patch
  ts/features/payments/bizEventsTransaction/navigation/navigator.tsx
  ts/features/payments/bizEventsTransaction/navigation/params.ts
  ts/features/payments/bizEventsTransaction/navigation/routes.ts
  ts/features/payments/bizEventsTransaction/saga/handleGetBizEventsTransactionReceipt.ts
  ts/features/payments/bizEventsTransaction/saga/index.ts
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsDetailsScreen.tsx
  ts/features/payments/bizEventsTransaction/screens/PaymentsTransactionBizEventsPreviewScreen.tsx
  ts/features/payments/bizEventsTransaction/store/actions/index.ts
  ts/features/payments/bizEventsTransaction/store/reducers/index.ts
  ts/features/payments/bizEventsTransaction/store/selectors/index.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#5863 fix: [IOPAE-1253] Set `keepCancelVisible` prop to true on SearchInput
  package.json
  ts/features/services/search/screens/SearchScreen.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  yarn.lock
Labels: IO - Enti & Servizi

#5857 chore: [IOPID-1787] Add `TRACKING` Profile Property
  ts/mixpanel.ts
  ts/mixpanelConfig/mixpanelPropertyUtils.ts
  ts/mixpanelConfig/profileProperties.ts
  ts/sagas/mixpanel.ts
  ts/screens/onboarding/OnboardingShareDataScreen.tsx
  ts/screens/profile/ShareDataScreen.tsx
  ts/screens/profile/analytics/mixpanel/mixpanelAnalytics.ts
Labels: IO-A&I

#5801 feat(IT Wallet): [SIW-1036] Add eID detail screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwCredentialClaimList.tsx
  ts/features/itwallet/common/components/ItwCredentialClaimsSection.tsx
  ts/features/itwallet/common/components/ItwPidAssuranceLevel.tsx
  ts/features/itwallet/common/components/ItwReleaserName.tsx
  ts/features/itwallet/common/components/__tests__/ItwCredentialClaimsSection.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialClaimsSection.test.tsx.snap
  ts/features/itwallet/common/utils/__tests__/itwClaimsUtils.test.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwStyleUtils.ts
  ts/features/itwallet/issuance/components/ItwCredentialPreviewScreenContent.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/presentation/components/ItwClaimsSections.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailFooter.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationEidDetailScreen.tsx
  ts/hooks/useHeaderSecondLevel.tsx
  ts/screens/profile/playgrounds/ItwPlayground.tsx
Labels: IT Wallet

#5862 chore: [IOPID-1844] Edit preferences screen
  ts/screens/onboarding/OnboardingServicesPreferenceScreen.tsx
  ts/screens/profile/ServicesPreferenceScreen.tsx
Labels: IO-A&I

#5854 feat: [IOCOM-832] Next message page loading
  ts/features/messages/components/Home/Footer.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/__tests__/Footer.test.tsx
  ts/features/messages/components/Home/__tests__/MessageList.test.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/Footer.test.tsx.snap
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
Labels: IO-Comunicazione

#5874 chore: [IOCOM-1541] Show push notification token in the profile section (dev mode on)
  ts/screens/profile/DeveloperModeSection.tsx
Labels: IO-Comunicazione

#5855 chore: [IOBP-695] Add banner of service to payments home screen
  locales/en/index.yml
  locales/it/index.yml
  package.json
  ts/features/payments/common/utils/index.ts
  ts/features/payments/common/utils/types.ts
  ts/features/payments/home/components/PaymentsAlertStatus.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
Labels: IO-Bonus e pagamenti

#5883 chore(Cross): [IOAPPX-327] Remove NDEF as NFC format for iOS
  ios/ItaliaApp/Info.plist
  ios/ItaliaApp/ItaliaApp.entitlements
Labels: Cross

#5867 feat: [IOCOM-833] Pull to refresh, new messages' home
  ts/features/messages/components/Home/CustomRefreshControl.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/__tests__/CustomRefreshControl.test.tsx
  ts/features/messages/components/Home/__tests__/MessageList.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/CustomRefreshControl.test.tsx.snap
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
  ts/features/pushNotifications/utils/__tests__/appDelegate.test.ts
  ts/features/pushNotifications/utils/configurePushNotification.ts
  ts/utils/__tests__/pot.test.ts
  ts/utils/pot.ts
Labels: IO-Comunicazione

#5872 feat: [IOCOM-1539] Profile screen, Push notification preferences, IOScrollViewLargeHeader instead of RNavScreenWithLargeHeader
  ts/screens/profile/NotificationsPreferencesScreen.tsx
  ts/screens/profile/__test__/__snapshots__/NotificationsPreferencesScreen.test.tsx.snap
Labels: IO-Comunicazione

#5884 chore: [IOCOM-1547] FIMS implicit code flow support
  ts/features/fims/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/saga/sagaUtils.ts
Labels: IO-Comunicazione

#5873 feat: [IOCOM-1412] Support for pagoPA logo above service logo on message cell
  ts/features/messages/components/Home/DS/DoubleAvatar.tsx
  ts/features/messages/components/Home/DS/MessageListItem.tsx
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
Labels: IO-Comunicazione

#5885 feat: [IOPID-1547] New DS on SPID errors
  locales/en/index.yml
  locales/it/index.yml
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/screens/authentication/AuthErrorScreen.tsx
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/__tests__/AuthErrorComponent.test.tsx
  ts/screens/authentication/__tests__/cie/ActivateNfcScreen.test.tsx
  ts/screens/authentication/__tests__/cie/__snapshots__/ActivateNfcScreen.test.tsx.snap
  ts/screens/authentication/cie/CieAuthErrorScreen.tsx
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
  ts/screens/authentication/cie/__test__/AuthErrorScreen.test.tsx
  ts/screens/authentication/cie/components/AuthErrorScreen.tsx
  ts/screens/authentication/components/AuthErrorComponent.tsx
  ts/screens/authentication/idpAuthErrorScreen.tsx
  ts/screens/authentication/idpAuthSessionHandler.tsx
Labels: IO-A&I

#5888 [IOCOm-1553] Proper logic for `getImageState` on `DoubleAvatar`
  ts/features/messages/components/Home/DS/DoubleAvatar.tsx
Labels: IO-Comunicazione

#5871 chore: [IOCOM-1514] Message list scroll on top upon Message Tab tap
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/PagerViewContainer.tsx
Labels: IO-Comunicazione

#5881 fix: [IOBP-706] Payment Method management regression
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/store/actions/networking.ts
Labels: IO-Bonus e pagamenti

#5880 chore: [IOBP-707] Add filters to disabled payment methods
  ts/features/payments/checkout/utils/index.ts
Labels: IO-Bonus e pagamenti

#5887 feat: [IOPID-1526] Add new DS on preferences screen
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/screens/profile/PreferencesScreen.tsx
Labels: IO-A&I

#5897 chore(Cross): [IOAPPX-332] Remove `react-native-sha256` dependency
  android/settings.gradle
  ios/Podfile.lock
  package.json
  ts/@types/react-native-sha256.d.ts
  yarn.lock
Labels: Cross

#5891 feat: [IOPID-1530] Add new DS on profile preferences email forward
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/navigation/ProfileNavigator.tsx
  ts/screens/profile/EmailForwardingScreen.tsx
Labels: IO-A&I

#5876 feat: [IOPID-1549] Revamp `LoadingSpinnerOverlay` and `LogoutScreen`
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/LoadingSpinnerOverlay.tsx
  ts/components/__tests__/__snapshots__/LoadingSpinnerOverlay.test.tsx.snap
  ts/components/__tests__/__snapshots__/WebviewComponent.test.tsx.snap
  ts/components/screens/LogoutScreen.tsx
  ts/components/ui/BoxedRefreshIndicator.tsx
  ts/components/ui/__test__/__snapshots__/BoxedRefreshIndicator.test.tsx.snap
  ts/features/messages/components/MessageAttachment/__test__/__snapshots__/PdfViewer.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/screens/authentication/IdpLoginScreen.tsx
Labels: IO-A&I

#5865 feat: [IOPID-1508] - DS Onboarding biometric activation
  ios/ItaliaApp/Info.plist
  ios/ItaliaApp/de.lproj/InfoPlist.strings
  ios/ItaliaApp/it.lproj/InfoPlist.strings
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/ScreenWithListItems.tsx
  ts/components/screens/__tests__/__snapshots__/ScreenWithListItems.test.tsx.snap
  ts/screens/authentication/__tests__/cie/__snapshots__/ActivateNfcScreen.test.tsx.snap
  ts/screens/onboarding/biometric&securityChecks/FingerprintScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/MissingDeviceBiometricScreen.tsx
  ts/screens/onboarding/biometric&securityChecks/MissingDevicePinScreen.tsx
  yarn.lock
Labels: IO-A&I

#5882 fix: [IOBP-705] Biz events data format
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionHeadingSection.tsx
  ts/features/payments/bizEventsTransaction/components/PaymentsBizEventsTransactionInfoSection.tsx
  ts/features/payments/bizEventsTransaction/utils/__tests__/index.test.ts
  ts/features/payments/bizEventsTransaction/utils/index.ts
Labels: IO-Bonus e pagamenti

#5896 fix: [IOBP-710] First payment onboarding
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
Labels: IO-Bonus e pagamenti

#5822 feat: [IOCOM-1406] Toast handling on new DS's Messages Home
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/Toasts.tsx
  ts/features/messages/components/Home/__tests__/EmptyList.test.tsx
  ts/features/messages/components/Home/__tests__/MessageList.test.tsx
  ts/features/messages/components/Home/__tests__/homeUtils.test.ts
  ts/features/messages/components/Home/homeUtils.ts
  ts/features/messages/components/Home/legacy/index.tsx
  ts/features/messages/components/__test__/MessageList.test.tsx
  ts/features/messages/screens/MessagesHomeScreen.tsx
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
Labels: IO-Comunicazione

#5894 fix: [IOCOM-1556] Fix missing message list on Android, new messages'home
  ts/features/messages/components/Home/CustomRefreshControl.tsx
  ts/features/messages/components/Home/MessageList.tsx
  ts/features/messages/components/Home/__tests__/CustomRefreshControl.test.tsx
  ts/features/messages/components/Home/__tests__/MessageList.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/CustomRefreshControl.test.tsx.snap
Labels: IO-Comunicazione

#5893 chore: [IOBP-709] Add wallet status filter during payment flow
  ts/features/payments/checkout/components/CheckoutPaymentMethodsList.tsx
  ts/features/payments/checkout/screens/WalletPaymentPickMethodScreen.tsx
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
Labels: IO-Bonus e pagamenti

#5899 [IOCOM-1557] New payment flow from a message's details
  ts/features/messages/components/MessageDetail/MessageDetailsPaymentButton.tsx
  ts/features/messages/components/MessageDetail/MessagePaymentItem.tsx
  ts/features/messages/components/MessageDetail/PaymentButton.tsx
  ts/features/messages/utils/__tests__/index.test.ts
  ts/features/messages/utils/index.ts
  ts/features/payments/checkout/tempWorkaround/pagoPaPaymentWorkaround.ts
  ts/features/pn/components/MessageFooter.tsx
  ts/navigation/NavigationService.ts
Labels: IO-Comunicazione, IO-Bonus e pagamenti

#5890 chore(Cross): [IOAPPX-328] Add the new `CircularProgress` component + Remove `react-native-progress-circle` dependency
  package.json
  ts/components/cie/CieCardReadingAnimation.tsx
  ts/components/ui/CircularProgress.tsx
  ts/features/design-system/core/DSLoaders.tsx
  ts/screens/authentication/cie/CieCardReaderScreen.tsx
  yarn.lock
Labels: Design System, Cross

#5892 chore: [IOCOM-1550] New empty archive message
  locales/it/index.yml
Labels: IO-Comunicazione

#5904 fix(Cross): [IOAPPX-335] E2e tests hanging forever
  ts/components/ui/LoadingIndicator.e2e.ts
  ts/components/ui/RefreshIndicator.tsx
Labels: Cross

#5905 chore: [IOCOM-1564] FIMS folder factor refactoring to enable sub-features
  ts/features/common/store/reducers/index.ts
  ts/features/fims/common/saga/index.ts
  ts/features/fims/common/store/actions.ts
  ts/features/fims/common/store/reducer.ts
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/fims/singleSignOn/navigation/index.tsx
  ts/features/fims/singleSignOn/saga/handleFimsAbortOrCancel.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetConsentsList.ts
  ts/features/fims/singleSignOn/saga/handleFimsGetRedirectUrlAndOpenIAB.ts
  ts/features/fims/singleSignOn/saga/handleFimsResourcesDeallocation.ts
  ts/features/fims/singleSignOn/saga/index.tsx
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/singleSignOn/store/actions/index.ts
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/fims/singleSignOn/types/index.ts
  ts/features/messages/utils/messages.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/sagas/startup.ts
  ts/store/actions/types.ts
Labels: IO-Comunicazione

#5877 chore: [IOCOM-1525] PAID badge, new DS
  ts/features/messages/components/Home/DS/MessageListItem.tsx
  ts/features/messages/components/Home/WrappedMessageListItem.tsx
  ts/features/messages/components/Home/__tests__/WrappedMessageListItem.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedMessageListItem.test.tsx.snap
  ts/features/messages/components/Home/legacy/Item.tsx
  ts/features/messages/screens/legacy/LegacyMessageDetailScreen.tsx
  ts/features/messages/store/reducers/__tests__/allPaginated.test.ts
  ts/features/messages/store/reducers/allPaginated.ts
  ts/features/messages/store/reducers/thirdPartyById.ts
  ts/features/messages/utils/__tests__/messageCategory.test.ts
  ts/features/messages/utils/messageCategory.ts
  ts/store/reducers/entities/payments.ts
Labels: IO-Comunicazione

#5889 feat(IT Wallet): [SIW-1025] Add credential issuance auth screen
  img/app/app-logo-inverted.png
  img/app/app-logo-inverted@2x.png
  img/app/app-logo-inverted@3x.png
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwBulletList.tsx
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/discovery/components/ItwMarkdown.tsx
  ts/features/itwallet/issuance/components/ItwRequiredClaimsList.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAuthScreen.tsx
  ts/features/itwallet/issuance/screens/__tests__/ItwIssuanceCredentialAuthScreen.test.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/screens/profile/playgrounds/ItwPlayground.tsx
Labels: IT Wallet

#5902 chore: [IOBP-716] Empty state payment home alignment
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
Labels: IO-Bonus e pagamenti

#5911 chore: remove FL workflows
  .github/workflows/release-fl.yml
  android/fastlane/Fastfile
  ios/fastlane/Fastfile
Labels: Cross

#5817 chore(IT Wallet): [SIW-1159] Add XState issuance machine scaffolding
  package.json
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/discovery/screens/__tests__/ItwDiscoveryInfoScreen.test.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationIdpSelectionScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationNfcInstructionsScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidResultScreen.tsx
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/actors.ts
  ts/features/itwallet/machine/credential/context.ts
  ts/features/itwallet/machine/credential/events.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/provider.tsx
  ts/features/itwallet/machine/tags.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/hooks/useNavigationSwipeBackListener.tsx
  yarn.lock
Labels: IT Wallet

#5908 chore: [IOBP-719] Text of operation error changed
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#5913 chore: [IOBP-721] Fast payment with PayPal label change
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#5842 chore(Cross): [IOAPPX-316] Remove fixed ratio from `FeaturedServiceCard`
  ts/features/services/common/components/CardPressableBase.tsx
  ts/features/services/home/components/FeaturedServiceCard.tsx
  ts/features/services/home/components/__tests__/__snapshots__/FeaturedInstitutionCard.test.tsx.snap
  ts/features/services/home/components/__tests__/__snapshots__/FeaturedServiceCard.test.tsx.snap
Labels: IO - Enti & Servizi, Design System, Cross

#5917 chore(cross): fix CGN e2e tests
  ts/features/bonus/cgn/__e2e__/cgn00.e2e.ts
  ts/features/bonus/cgn/__e2e__/cgn02.e2e.ts
  ts/features/bonus/cgn/__e2e__/utils.ts
  ts/features/bonus/cgn/components/detail/CgnUnsubscribe.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
Labels: Cross

#5914 chore: [IOBP-704] Add payed rptid into state entities on payment success
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/store/actions/orchestration.ts
  ts/store/reducers/entities/payments.ts
Labels: IO-Comunicazione, IO-Bonus e pagamenti

#5903 chore: [IOBP-715] Expired payment methods filtering
  ts/features/payments/checkout/store/selectors/paymentMethods.ts
Labels: IO-Bonus e pagamenti

#5900 chore: [IOPID-1995] Add logic to use ComposedBodyFromArray into IOScrollViewWithLargeHeader
  ts/components/ui/IOScrollViewWithLargeHeader.tsx
  ts/screens/profile/EmailForwardingScreen.tsx
Labels: IO-A&I
