Repository pagopa/io-app, pull requests merged in 2025-02, with the labels that each got.

#6667 refactor: [IOBP-1170] Align IDPay screen to design requirements
  ts/features/idpay/details/components/InitiativeRulesInfoBox.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/idpay/payment/navigation/navigator.tsx
  ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentCodeInputScreen.tsx
  ts/features/idpay/unsubscription/navigation/navigator.tsx
  ts/features/idpay/unsubscription/screens/UnsubscriptionConfirmationScreen.tsx
  ts/features/idpay/unsubscription/screens/UnsubscriptionResultScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#6641 chore(IT Wallet): [SIW-1989] Add dismiss confirmation dialog to IT Wallet identification flows
  ts/features/itwallet/common/hooks/useItwDismissalDialog.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
  ts/features/itwallet/identification/screens/cieId/ItwCieIdLoginScreen.tsx
  ts/features/itwallet/identification/screens/spid/ItwSpidIdpLoginScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/hooks/useHardwareBackButton.ts
Labels: IT Wallet

#6674 fix: [IOBP-1157] Correct `a11y` label in `PAYMENT_NOTICE_SUMMARY`
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
Labels: a11y, IO-Bonus e pagamenti

#6675 chore: [IOBP-1165] Remove transparent header in `PAYMENT_METHOD_DETAILS_SCREEN`
  ts/features/payments/details/components/PaymentsMethodDetailsBaseScreenComponent.tsx
Labels: a11y, IO-Bonus e pagamenti

#6669 fix: [IOBP-1162] Add missing `a11y` label in `PAYMENTS_HOME`
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
Labels: a11y, IO-Bonus e pagamenti

#6655 chore: [IOPLT-946] Update the main icon app for iOS + Add support for dark and tinted appearances
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-dark.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-default.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/iOS-app-icon-tinted.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-1024.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-20@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-29@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-30.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@2x-1.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-40@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-57.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-57@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-60@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-60@3x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-76.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-76@2x.png
  ios/ItaliaApp/Images.xcassets/AppIcon.appiconset/io-launcher-icon-83.5@2x.png
Labels: Design System, :nail_care: Visual tweaks

#6652 fix: [IOCOM-2040] Handling of code and pre html blocks in old markdown
  ts/components/ui/Markdown/utils.ts
Labels: IO-Comunicazione

#6677 test: [IOCOM-1822] fims history export saga tests
  ts/features/fims/history/saga/__tests__/handleExportFimsHistorySaga.test.ts
Labels: IO-Comunicazione

#6668 refactor(IT Wallet): [SIW-1942] Use `Skia` for IT Wallet credential card effects based on credential status
  img/features/itWallet/cards/dc_na.png
  img/features/itWallet/cards/dc_na@2x.png
  img/features/itWallet/cards/dc_na@3x.png
  img/features/itWallet/cards/dc_off.png
  img/features/itWallet/cards/dc_off@2x.png
  img/features/itWallet/cards/dc_off@3x.png
  img/features/itWallet/cards/mdl_na.png
  img/features/itWallet/cards/mdl_na@2x.png
  img/features/itWallet/cards/mdl_na@3x.png
  img/features/itWallet/cards/mdl_off.png
  img/features/itWallet/cards/mdl_off@2x.png
  img/features/itWallet/cards/mdl_off@3x.png
  img/features/itWallet/cards/ts_na.png
  img/features/itWallet/cards/ts_na@2x.png
  img/features/itWallet/cards/ts_na@3x.png
  img/features/itWallet/cards/ts_off.png
  img/features/itWallet/cards/ts_off@2x.png
  img/features/itWallet/cards/ts_off@3x.png
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/CardBackground.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/DigitalVersionBadge.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/__tests__/DigitalVersionBadge.test.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/__tests__/ItwCredentialCard.test.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/__tests__/__snapshots__/DigitalVersionBadge.test.tsx.snap
  ts/features/itwallet/common/components/ItwCredentialCard/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
  ts/features/itwallet/common/components/ItwCredentialCard/index.ts
  ts/features/itwallet/common/components/ItwCredentialCard/types.ts
Labels: IT Wallet

#6609 feat(IT Wallet): [SIW-1946] Add hold to copy for credentials text claims
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/presentation/details/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
Labels: IT Wallet

#6682 chore: [IOBP-1174] Align bottom sheet text with design requirements
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#6681 chore: [IOBP-1171,IOBP-1172,IOBP-1173] Update payment outcome localizations
  locales/en/index.yml
  locales/it/index.yml
Labels: IO-Bonus e pagamenti

#6621 feat(IDPay): [IOBP-1139] Add new IDPay initiative reward type `EXPENSE`
  locales/en/index.yml
  locales/it/index.yml
  scripts/generate-api-models.sh
  ts/components/BonusCard/BonusCard.tsx
  ts/components/BonusCard/BonusCardCounter.tsx
  ts/features/idpay/details/components/BeneficiaryDetailsContent.tsx
  ts/features/idpay/details/components/IdPayInitiativeLastUpdateCounter.tsx
  ts/features/idpay/details/components/InitiativeTimelineComponent.tsx
  ts/features/idpay/details/components/TimelineOperationListItem.tsx
  ts/features/idpay/details/components/__tests__/TimelineOperationListItem.test.tsx
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
  ts/features/idpay/unsubscription/screens/UnsubscriptionConfirmationScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#6653 chore:[IOPID-2162] Remove CieID FF
  locales/en/index.yml
  locales/it/index.yml
  ts/components/cie/CieNotSupported.tsx
  ts/features/cieLogin/store/actions/index.ts
  ts/features/cieLogin/store/reducers/index.ts
  ts/features/cieLogin/store/selectors/index.ts
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/routes.ts
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/__tests__/LandingScreen.test.tsx
  ts/screens/authentication/__tests__/__snapshots__/LandingScreen.test.tsx.snap
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/reducers/index.ts
Labels: IO-A&I

#6676 feat(IDPay): [IOBP-1131] Text input onboarding field
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
  ts/features/idpay/onboarding/machine/actions.ts
  ts/features/idpay/onboarding/machine/actors.ts
  ts/features/idpay/onboarding/machine/context.ts
  ts/features/idpay/onboarding/machine/events.ts
  ts/features/idpay/onboarding/machine/machine.ts
  ts/features/idpay/onboarding/machine/selectors.ts
  ts/features/idpay/onboarding/navigation/navigator.tsx
  ts/features/idpay/onboarding/navigation/params.ts
  ts/features/idpay/onboarding/navigation/routes.ts
  ts/features/idpay/onboarding/screens/InputFormVerificationScreen.tsx
  ts/screens/profile/playgrounds/IdPayOnboardingPlayground.tsx
Labels: IDPay, IO-Bonus e pagamenti

#6679 fix: [IOCOM-2088] Handling of <br /> tags on IOMarkdown
  ts/components/IOMarkdown/markdownRenderer.ts
  ts/components/IOMarkdown/renderRules.tsx
  ts/features/common/components/IOMarkdown/customRules.tsx
  ts/features/messages/components/Home/PreconditionsContent.tsx
Labels: IO-Comunicazione

#6686 chore(IT Wallet): [SIW-2001] Track unknown credential status error
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
Labels: IT Wallet

#6688 test: [IOCOM-1829] fimsHistoryLoaders tests
  ts/features/fims/history/components/__tests__/FimsHistoryLoaders.test.tsx
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryLoaders.test.tsx.snap
Labels: IO-Comunicazione

#6662 chore: [IOPAE-1773] Truncate long national institution names
  ts/features/services/home/screens/ServicesHomeScreen.tsx
Labels: IO-Enti e Servizi

#6622 feat(IDPay): [IOBP-1147] Add request help from IDPay beneficiary details screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/idpay/common/hooks/useIdPaySupportModal.tsx
  ts/features/idpay/details/components/BeneficiaryDetailsContent.tsx
  ts/features/idpay/details/components/__tests__/BeneficiaryDetailsContent.test.tsx
  ts/features/zendesk/store/actions/index.ts
  ts/features/zendesk/utils/index.ts
  ts/hooks/useStartSupportRequest.ts
  ts/utils/supportAssistance.ts
Labels: IDPay, IO-Bonus e pagamenti

#6691 feat(IDPay): [IOBP-1137] Add expense cta with FIMS implementation
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
Labels: IDPay, IO-Bonus e pagamenti

#6693 chore: [IOBP-1180] Add priority to remote feature flag for the IDPay feature
  ts/sagas/startup.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IDPay, IO-Bonus e pagamenti

#6670 feat(IT Wallet): [SIW-1960] Scan QR code for remote presentation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/barcode/types/__tests__/decoders.test.ts
  ts/features/barcode/types/decoders.ts
  ts/features/itwallet/common/utils/itwUrlUtils.ts
  ts/features/itwallet/presentation/remote/Utils/itwRemoteTypeUtils.ts
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
  ts/features/itwallet/presentation/remote/machine/context.ts
  ts/features/itwallet/presentation/remote/machine/events.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/navigation/ItwRemoteParamsList.ts
  ts/features/itwallet/presentation/remote/navigation/ItwRemoteStackNavigator.tsx
  ts/features/itwallet/presentation/remote/navigation/routes.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
Labels: IT Wallet

#6678 feat(IT Wallet): [SIW-2007] Add local FF for offline wallet access
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/features/itwallet/playgrounds/components/ItwLifecycleSection.tsx
  ts/features/itwallet/playgrounds/components/ItwSkeumorphicCredentialSection.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IT Wallet

#6687 fix: [IOAPPX-479] Fix camera permission request on Android devices
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
  ts/features/barcode/components/__tests__/BarcodeScanBaseScreenComponent.test.tsx
  ts/features/barcode/hooks/useCameraPermissionStatus.ts
  ts/features/barcode/hooks/useIOBarcodeCameraScanner.tsx
  ts/features/barcode/index.ts
Labels: Cross

#6701 fix(Cross): [IOAPPX-000] Check for more than one message in linter workflows
  .github/workflows/pr-title-conventional-commit-linter.yml
  .github/workflows/pr-title-linter-and-linker.yml
Labels: Cross

#6699 refactor: [IOBP-1184] Update cta for `PAYMENT_CANCELED`
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/components/__tests__/WalletPaymentFailureDetail.test.tsx
Labels: IO-Bonus e pagamenti

#6696 chore(IT Wallet): [SIW-1966] Selective disclosure screen for remote presentation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/__mocks__/presentationClaims.json
  ts/features/itwallet/common/components/ItwClaimsDisclosure/ItwClaimText.tsx
  ts/features/itwallet/common/components/ItwClaimsDisclosure/ItwOptionalClaim.tsx
  ts/features/itwallet/common/components/ItwClaimsDisclosure/ItwStaticClaim.tsx
  ts/features/itwallet/common/components/ItwClaimsDisclosure/index.tsx
  ts/features/itwallet/common/components/ItwDataExchangeIcons.tsx
  ts/features/itwallet/common/components/__tests__/ItwClaimsDisclosure.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwClaimsDisclosure.test.tsx.snap
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
Labels: IT Wallet

#6694 feat(IT Wallet): [SIW-1962] Remote presentation handle wallet instance presence
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/utils/itwStoreUtils.ts
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
  ts/features/itwallet/presentation/remote/machine/actions.ts
  ts/features/itwallet/presentation/remote/machine/events.ts
  ts/features/itwallet/presentation/remote/machine/failure.ts
  ts/features/itwallet/presentation/remote/machine/guards.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/machine/provider.tsx
  ts/features/itwallet/presentation/remote/machine/selectors.ts
  ts/features/itwallet/presentation/remote/navigation/ItwRemoteParamsList.ts
  ts/features/itwallet/presentation/remote/navigation/ItwRemoteStackNavigator.tsx
  ts/features/itwallet/presentation/remote/navigation/routes.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
Labels: IT Wallet

#6702 chore(IT Wallet): [SIW-1964] Add failure screen for missing credentials in presentation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/presentation/remote/machine/failure.ts
  ts/features/itwallet/presentation/remote/machine/guards.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
Labels: IT Wallet

#6712 fix(IDPay): [IOBP-1203] Show some IDPay features not needed under local feature flag
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/SecurityScreen.tsx
  ts/store/reducers/backendStatus/remoteConfig.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IDPay, IO-Bonus e pagamenti

#6711 refactor: [IOBP-1202] Icon for `PAYMENT_CANCELED` cta
  ts/components/screens/OperationResultScreenContent.tsx
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
Labels: IO-Bonus e pagamenti

#6713 refactor: [IOBP-1204] Add `IUV` to label
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/receipts/screens/ReceiptCartItemDetailsScreen.tsx
Labels: a11y, IO-Bonus e pagamenti

#6719 chore(IDPay): [IOBP-1205] Removed the missing configuration alert for `EXPENSE` initiatives
  ts/features/idpay/details/components/MissingConfigurationAlert.tsx
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
  ts/features/idpay/details/screens/__tests__/IdPayInitiativeDetailsScreen.test.tsx
Labels: IDPay, IO-Bonus e pagamenti

#6709 fix: [PE-959,PE-960,PE-961,PE-962] Remove transparent header in `CGN`
  ts/features/bonus/cgn/screens/discount/CgnDiscountDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6715 test: [IOCOM-1830] fimsHistoryNonEmptyContent tests
  jestSetup.js
  ts/features/fims/history/components/FimsHistoryNonEmptyContent.tsx
  ts/features/fims/history/components/__mocks__/FimsHistoryListItemPicker.tsx
  ts/features/fims/history/components/__mocks__/FimsHistoryLoaders.tsx
  ts/features/fims/history/components/__tests__/FimsHistoryNonEmptyContent.test.tsx
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryNonEmptyContent.test.tsx.snap
  ts/features/fims/history/hooks/__mocks__/useFimsHistoryResultToasts.tsx
  ts/features/fims/history/store/reducer/index.ts
Labels: IO-Comunicazione

#6722 fix: [IOCOM-2097] Special link support removed from IOMarkdown on messages and services
  locales/en/index.yml
  locales/it/index.yml
  ts/components/ui/Markdown/handlers/__test__/link.test.ts
  ts/components/ui/Markdown/handlers/link.ts
  ts/features/common/components/IOMarkdown/__test__/customRules.test.tsx
  ts/features/common/components/IOMarkdown/customRules.tsx
Labels: IO-Comunicazione

#6692 chore: [IOPAE-1744,IOPAE-1749] Remove transparent header to solve accessibility problems
  ts/features/services/common/components/ServicesHeader.tsx
  ts/features/services/common/components/ServicesHeaderSection.tsx
  ts/features/services/common/components/__tests__/__snapshots__/ServicesHeader.test.tsx.snap
  ts/features/services/common/components/__tests__/__snapshots__/ServicesHeaderSection.test.tsx.snap
  ts/features/services/details/components/ServiceDetailsScreenComponent.tsx
  ts/features/services/details/screens/ServiceDetailsScreen.tsx
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
Labels: a11y, IO-Enti e Servizi

#6725 fix: [IOBP-1179] `a11y` banner focus order
  package.json
  ts/features/design-system/core/DSSelection.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwFeedbackBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerOnboarding.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/RemoteContentBanner.test.tsx.snap
  ts/features/pushNotifications/components/__tests__/__snapshots__/PushNotificationsBanner.test.tsx.snap
  ts/screens/authentication/__tests__/__snapshots__/LandingScreen.test.tsx.snap
  ts/screens/profile/__test__/__snapshots__/ProfileMainScreenTopBanner.test.tsx.snap
  ts/screens/profile/components/__test__/__snapshots__/SettingsDiscoveryBanner.test.tsx.snap
  yarn.lock
Labels: a11y, IO-Bonus e pagamenti

#6708 fix: [PE-965] CGN Swipe back gesture to root stack navigator
  ts/features/bonus/cgn/hooks/__tests__/useDisableRootNavigatorGesture.test.tsx
  ts/features/bonus/cgn/hooks/useDisableRootNavigatorGesture.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/screens/merchants/__tests__/CgnMerchantsCategoriesSelectionScreen.test.tsx
  ts/features/bonus/cgn/screens/merchants/__tests__/__snapshots__/CgnMerchantsCategoriesSelectionScreen.test.tsx.snap
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6726 fix: [PE-937] a11y on `CgnCard` expiry date
  ts/features/bonus/cgn/components/CgnCard.tsx
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6721 chore: [IOPID-2690] Support back navigation from `CieIdLoginScreen` and `CieConsentDataUsageScreen`
  ts/features/cieLogin/components/CieIdLoginWebView.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/screens/authentication/cie/CieConsentDataUsageScreen.tsx
  ts/utils/__tests__/hooks/useOnbardingAbortAlert.test.ts
  ts/utils/hooks/useOnboardingAbortAlert.ts
Labels: IO-A&I

#6729 chore: [IOBP-1191] Add a11y description to button inside the barcode scan screen
  locales/en/index.yml
  locales/it/index.yml
Labels: a11y, IO-Bonus e pagamenti

#6730 chore: [IOBP-1164] Add a11y description to the receipt PDF preview page
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
Labels: a11y, IO-Bonus e pagamenti

#6698 fix: [IOPAE-1758,IOPAE-1759,IOPAE-1761,IOPAE-1762] Accessibility improvements
  locales/en/index.yml
  locales/it/index.yml
  ts/features/services/details/components/ServiceDetailsMetadata.tsx
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
Labels: a11y, IO-Enti e Servizi

#6720 chore: [IOPID-2664] Change session expired card component
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/config.ts
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/__tests__/LandingSessionExpiredComponent.test.tsx
  ts/screens/authentication/components/LandingSessionExpiredComponent.tsx
  ts/utils/analytics.ts
Labels: legal-approved ⚖️ ✅, IO-A&I

#6689 feat(IT Wallet): [SIW-1972] Remote presentation same device
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/barcode/types/__tests__/decoders.test.ts
  ts/features/barcode/types/decoders.ts
  ts/features/itwallet/navigation/useItwLinkingOptions.tsx
  ts/features/itwallet/presentation/remote/Utils/itwRemoteTypeUtils.ts
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
  ts/features/itwallet/presentation/remote/machine/actions.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/navigation/ItwRemoteParamsList.ts
  ts/features/itwallet/presentation/remote/navigation/ItwRemoteStackNavigator.tsx
  ts/features/itwallet/presentation/remote/navigation/routes.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteRequestValidationScreen.tsx
  ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteRequestValidation.test.tsx
Labels: IT Wallet

#6736 feat: [IOPID-2666] FastLogin expiration Banner
  locales/en/index.yml
  locales/it/index.yml
  scripts/generate-api-models.sh
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/common/store/reducers/index.ts
  ts/features/landingScreenMultiBanner/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/login/preferences/components/LoginExpirationBanner.tsx
  ts/features/login/preferences/store/__tests__/selectors.test.ts
  ts/features/login/preferences/store/actions/index.ts
  ts/features/login/preferences/store/reducers/index.ts
  ts/features/login/preferences/store/selectors/index.ts
  ts/features/zendesk/utils/index.ts
  ts/store/actions/types.ts
  ts/store/reducers/authentication.ts
  ts/store/reducers/index.ts
Labels: IO-A&I

#6716 feat(IT Wallet): [SIW-1963] Handle eid expired in Remote Presentation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
  ts/features/itwallet/presentation/remote/machine/actions.ts
  ts/features/itwallet/presentation/remote/machine/events.ts
  ts/features/itwallet/presentation/remote/machine/failure.ts
  ts/features/itwallet/presentation/remote/machine/guards.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
  ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteRequestValidation.test.tsx
Labels: IT Wallet

#6727 chore(IT Wallet): [SIW-2012] Notify the user 30 days before credential expiration
  ts/features/itwallet/common/utils/__tests__/itwCredentialStatusUtils.test.ts
  ts/features/itwallet/common/utils/itwCredentialStatusUtils.ts
Labels: IT Wallet

#6732 chore: [IOAPPX-485] Add some additional information to the `Design System` section of the README
  README.md
Labels: Design System

#6714 feat: [IOPID-2634] Implement Zendesk FAQ Banner in the `accesso_a_io` subCategories screen
  ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx
  ts/utils/object.ts
Labels: IO-A&I

#6724 feat(IT Wallet): [SIW-1961] Handle invalid payload in deeplink for Remote presentation
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/hooks/__tests__/useItwFailureSupportModal.test.tsx
  ts/features/itwallet/common/hooks/useItwFailureSupportModal.tsx
  ts/features/itwallet/common/utils/ItwFailureTypes.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/itwallet/presentation/remote/components/ItwRemoteDeepLinkFailure.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteRequestValidationScreen.tsx
Labels: IT Wallet

#6718 fix: [IOCOM-2095] Preconditions scroll
  ts/components/ui/FooterActions.tsx
  ts/features/fims/history/components/FimsHistoryNonEmptyContent.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/presentation/details/screens/ItwPresentationCredentialAttachmentScreen.tsx
  ts/features/messages/components/Home/Preconditions.tsx
  ts/features/messages/components/Home/PreconditionsContent.tsx
  ts/features/messages/components/Home/PreconditionsFooter.tsx
  ts/features/messages/components/Home/__tests__/PreconditionsContent.test.tsx
  ts/features/messages/components/Home/__tests__/PreconditionsFooter.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/PreconditionsContent.test.tsx.snap
  ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
  ts/hooks/useFooterActionsMeasurements.ts
Labels: IO-Comunicazione

#6742 chore(IT Wallet): [SIW-1990] Persist user preference for hiding claim values in credential details
  ts/features/itwallet/common/store/actions/preferences.ts
  ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/itwallet/presentation/details/components/ItwPresentationClaimsSection.tsx
Labels: IT Wallet

#6748 fix: [IOBP-1216] Add missing contextual help properties
  ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
  ts/features/itwallet/presentation/details/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
Labels: IDPay, IO-Bonus e pagamenti

#6737 chore: [IOPLT-973] Improve formatting of `IOMarkdown` for messages/services
  package.json
  ts/components/ui/__test__/__snapshots__/IOScrollViewWithListItems.test.tsx.snap
  ts/features/common/components/IOMarkdown/customRules.tsx
  ts/features/itwallet/issuance/components/__tests__/__snapshots__/ItwCredentialPreviewClaimsList.test.tsx.snap
  ts/features/itwallet/presentation/details/components/__tests__/__snapshots__/ItwPresentationClaimsSection.test.tsx.snap
  ts/features/pushNotifications/screens/__tests__/__snapshots__/OnboardingNotificationsInfoScreenConsent.test.tsx.snap
  ts/screens/authentication/__tests__/cie/__snapshots__/ActivateNfcScreen.test.tsx.snap
  ts/screens/profile/playgrounds/IOMarkdownPlayground.tsx
  yarn.lock
Labels: Design System, :nail_care: Visual tweaks

#6706 chore(IT Wallet): [SIW-2016] Remove remote feature flag from linking options
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/useItwLinkingOptions.tsx
Labels: IT Wallet

#6743 fix: [IOPID-2632] Identification modal regressions
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/screens/modal/IdentificationModal.tsx
  ts/utils/identification/index.tsx
  yarn.lock
Labels: Bug 🐞, IO-A&I

#6723 chore: [IOPID-2612] edit publiccode.yml file
  publiccode.yml
Labels: scheduled

#6573 feat: [IOAPPX-453] Add the new static `Appearance` profile screen
  locales/en/index.json
  locales/it/index.json
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/profile/AppearancePreferenceScreen.tsx
  ts/screens/profile/PreferencesScreen.tsx
Labels: Design System, Dark mode 🌝

#6745 fix: [IOBP-1206,IOBP-1209] Payment checkout accessibility input text
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/checkout/screens/WalletPaymentInputFiscalCodeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentInputNoticeNumberScreen.tsx
  ts/features/payments/checkout/screens/__tests__/WalletPaymentInputFiscalCodeScreen.test.tsx
  ts/features/payments/checkout/screens/__tests__/WalletPaymentInputNoticeNumberScreen.test.tsx
  ts/features/payments/checkout/screens/__tests__/__snapshots__/WalletPaymentInputFiscalCodeScreen.test.tsx.snap
  ts/features/payments/checkout/screens/__tests__/__snapshots__/WalletPaymentInputNoticeNumberScreen.test.tsx.snap
  ts/features/payments/checkout/types/index.ts
Labels: a11y, IO-Bonus e pagamenti

#6695 feat: [IOPLT-951] Add the new typeface selection banner to the `Settings` screen
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/features/appearanceSettings/store/actions/index.ts
  ts/features/appearanceSettings/store/reducers/__test__/index.test.ts
  ts/features/appearanceSettings/store/reducers/index.ts
  ts/features/appearanceSettings/store/selectors/__test__/index.test.ts
  ts/features/appearanceSettings/store/selectors/index.ts
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/common/store/reducers/index.ts
  ts/features/profileSettings/store/actions/index.ts
  ts/features/profileSettings/store/reducers/index.ts
  ts/features/profileSettings/store/selectors/index.ts
  ts/screens/profile/ProfileMainScreenTopBanner.tsx
  ts/screens/profile/__test__/ProfileMainScreenTopBanner.test.tsx
  ts/screens/profile/__test__/__snapshots__/ProfileMainScreenTopBanner.test.tsx.snap
  ts/store/actions/types.ts
  ts/store/reducers/index.ts
Labels: Design System

#6744 feat:[IOPLT-919] Add mixpanel events and updates for App UI Preference
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/common/context/DSTypefaceContext/index.tsx
  ts/mixpanelConfig/profileProperties.ts
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/TabNavigator.tsx
  ts/screens/profile/AppearancePreferenceScreen.tsx
  ts/screens/profile/analytics/index.ts
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/persistedPreferences.ts
Labels: Design System

#6752 chore: [IOBP-1217] Add mixpanel tracking help center CTA on payment checkout failure screen
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/components/__tests__/WalletPaymentFailureDetail.test.tsx
  ts/features/payments/checkout/utils/index.ts
Labels: IO-Bonus e pagamenti

#6756 feat: [IOCOM-2086] addition of SEND activation banner
  locales/en/index.json
  locales/it/index.json
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/landingScreenMultiBanner/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/pn/components/PNActivationReminderBanner.tsx
  ts/features/pn/components/__test__/PNActivationReminderBanner.test.tsx
  ts/features/pn/components/__test__/__snapshots__/PNActivationReminderBanner.test.tsx.snap
Labels: IO-Comunicazione

#6759 chore: [IOBP-1194,IOBP-1196] a11y focus improvements on Barcode scan screen
  package.json
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
  yarn.lock
Labels: a11y, IO-Bonus e pagamenti

#6738 feat: [IOPID-2740] Add support for external campaign tracking
  android/app/src/main/AndroidManifest.xml
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/common/store/reducers/index.ts
  ts/features/utmLink/analytics/index.ts
  ts/features/utmLink/index.ts
  ts/features/utmLink/saga/index.ts
  ts/features/utmLink/store/actions/index.ts
  ts/features/utmLink/store/reducers/index.ts
  ts/features/utmLink/store/selectors/index.ts
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/linkingSubscription.ts
  ts/sagas/index.ts
  ts/store/actions/types.ts
  ts/utils/testWrapper.tsx
Labels: legal-approved ⚖️ ✅, IO-A&I

#6762 fix: [IOAPPX-489] Enable the new typeface in the `ItwCredentialCard`
  ts/features/itwallet/common/components/ItwCredentialCard/DigitalVersionBadge.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/__tests__/DigitalVersionBadge.test.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/__tests__/ItwCredentialCard.test.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/__tests__/__snapshots__/DigitalVersionBadge.test.tsx.snap
  ts/features/itwallet/common/components/ItwCredentialCard/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
Labels: Design System, IT Wallet

#6753 chore: [IOAPPX-487] Latest version of `react-native-device-info`
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/ItaliaApp/PrivacyInfo.xcprivacy
  ios/Podfile.lock
  package.json
  patches/patches.md
  patches/react-native-device-info+14.0.4.patch
  ts/sagas/startup/onboarding/biometric/checkAcknowledgedFingerprintSaga.ts
  ts/screens/authentication/LandingScreen.tsx
  ts/utils/appVersion.ts
  ts/utils/biometrics.ts
  ts/utils/device.ts
  yarn.lock
Labels: dependencies, Cross

#6754 chore: [PE-996] Accessibility for CGN loading component
  ts/features/bonus/cgn/screens/activation/CgnActivationLoadingScreen.tsx
  ts/features/bonus/cgn/screens/activation/__tests__/CgnActivationLoadingScreen.test.tsx
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6769 fix: [IOPLT-996] Enable quick dev access in the `IdentificationLockScreen` with screen reader enabled
  ts/screens/modal/components/IdentificationNumberPad.tsx
Labels: a11y

#6680 chore: [IOAPPX-476] Change `StatusBar` style according to the current color scheme
  ts/RootContainer.tsx
  ts/components/BonusCard/BonusCardScreenComponent.tsx
  ts/components/ui/AppHeader.tsx
  ts/components/ui/FocusAwareStatusBar.tsx
  ts/features/bonus/cgn/components/merchants/ModuleCgnDiscount.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountHeader.tsx
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/discount/CgnDiscountDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantCategoriesListScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/bonus/cgn/utils/filters.ts
  ts/features/design-system/DesignSystem.tsx
  ts/features/design-system/components/DesignSystemScreen.tsx
  ts/features/design-system/core/DSDynamicBackground.tsx
  ts/features/fci/components/ErrorComponent.tsx
  ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/theme/variables.ts
Labels: Dark mode 🌝
