Repository pagopa/io-app, pull requests merged in 2025-01, with the labels that each got.

#6565 [IOPID-2566] Refactor AuthErrorComponent
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/common/store/reducers/index.ts
  ts/features/spidLogin/store/actions/index.ts
  ts/features/spidLogin/store/reducers/index.ts
  ts/features/spidLogin/store/selectors/index.ts
  ts/features/spidLogin/types/index.ts
  ts/screens/authentication/AuthErrorScreen.tsx
  ts/screens/authentication/IdpLoginScreen.tsx
  ts/screens/authentication/idpAuthSessionHandler.tsx
  ts/store/actions/types.ts
Labels: IO-A&I

#6568 chore(IT Wallet): [SIW-1639] Show error banner when wallet instance status check fails
  locales/en/index.yml
  locales/it/index.yml
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/components/ItwWalletNotAvailableBanner.tsx
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/walletInstance/hook/useItwWalletInstanceRevocationAlert.ts
  ts/features/itwallet/walletInstance/store/actions/index.ts
  ts/features/itwallet/walletInstance/store/reducers/index.ts
  ts/features/itwallet/walletInstance/store/selectors/index.ts
  ts/features/wallet/components/WalletCardsContainer.tsx
  ts/features/wallet/components/__tests__/WalletCardsContainer.test.tsx
  ts/features/wallet/store/selectors/index.ts
Labels: IT Wallet

#6558 chore(IT Wallet): [SIW-1933] Handle Trustmark QR code generation failures
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  ts/components/QrCodeImage.tsx
  ts/features/itwallet/trustmark/components/ItwCredentialTrustmark.tsx
  ts/features/itwallet/trustmark/components/ItwTrustmarkExpirationTimer.tsx
  ts/features/itwallet/trustmark/components/ItwTrustmarkQrCode.tsx
  ts/features/itwallet/trustmark/machine/__tests__/machine.test.ts
  ts/features/itwallet/trustmark/machine/actions.ts
  ts/features/itwallet/trustmark/machine/actors.ts
  ts/features/itwallet/trustmark/machine/context.ts
  ts/features/itwallet/trustmark/machine/events.ts
  ts/features/itwallet/trustmark/machine/failure.ts
  ts/features/itwallet/trustmark/machine/machine.ts
  ts/features/itwallet/trustmark/machine/provider.tsx
  ts/features/itwallet/trustmark/machine/selectors.ts
  ts/features/itwallet/trustmark/screens/ItwCredentialTrustmarkScreen.tsx
  ts/features/itwallet/trustmark/utils/__tests__/index.ts
  ts/features/itwallet/trustmark/utils/index.ts
  ts/store/reducers/debug.ts
Labels: IT Wallet

#6579 fix: [IOBP-1100] German FAQ strings
  scripts/generate-api-models.sh
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/payments/checkout/components/WalletPaymentFeedbackBanner.tsx
  ts/features/payments/home/components/PaymentsAlertStatus.tsx
  ts/hooks/useStatusAlertProps.ts
  ts/i18n.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/utils/locale.ts
  ts/utils/payment.ts
Labels: IO-Bonus e pagamenti

#5972 chore(Cross): [IOAPPX-346] Remove manually linked deps
  android/app/build.gradle
  android/settings.gradle
Labels: keep open, Cross

#6587 chore: [IOPID-2575] Bump `rn-keychain` and force `AES_GCM_NO_AUTH`
  ios/Podfile.lock
  package.json
  ts/__mocks__/react-native-keychain.ts
  ts/utils/keychain.ts
  yarn.lock
Labels: IO-A&I

#6574 chore: [IOAPPX-454] Parametrize the use of `Kotlin` and `OkHttp` versions to be used from libraries if needed
  android/app/build.gradle
  android/build.gradle
  package.json
  yarn.lock
Labels: dont-merge :raised_hand:, Cross

#6593 [IOCOM-1823,IOCOM-1826] FIMS history get saga and header component tests
  ts/features/fims/history/components/__tests__/FimsHistoryHeaderComponent.test.tsx
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryHeaderComponent.test.tsx.snap
  ts/features/fims/history/saga/__tests__/handleGetFimsHistorySaga.test.ts
  ts/features/fims/history/saga/handleGetFimsHistorySaga.ts
Labels: IO-Comunicazione

#6600 [IOPID-2592] Fix wrong navigation on first app install
  ts/sagas/installation.ts
Labels: Bug 🐞, IO-A&I

#6592 feat(IT Wallet): [SIW-1944] Remove the ongoing badge when errors occur
  ts/features/itwallet/common/store/selectors/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/guards.ts
  ts/features/itwallet/machine/credential/machine.ts
Labels: IT Wallet

#6583 refactor: [IOBP-1095] Replace legacy headers for IDPay screens
  ts/features/idpay/code/screens/IdPayCodeDisplayScreen.tsx
  ts/features/idpay/code/screens/IdPayCodeRenewScreen.tsx
  ts/features/idpay/code/screens/__tests__/IdPayCodeDisplayScreen.test.tsx
  ts/features/idpay/configuration/screens/IbanConfigurationLandingScreen.tsx
  ts/features/idpay/configuration/screens/IbanEnrollmentScreen.tsx
  ts/features/idpay/configuration/screens/IbanOnboardingScreen.tsx
  ts/features/idpay/configuration/screens/IdPayDiscountInstrumentsScreen.tsx
  ts/features/idpay/configuration/screens/InitiativeConfigurationIntroScreen.tsx
  ts/features/idpay/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/onboarding/screens/CompletionScreen.tsx
  ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentCodeInputScreen.tsx
  ts/features/idpay/unsubscription/screens/UnsubscriptionConfirmationScreen.tsx
  ts/features/idpay/wallet/screens/IdPayInstrumentInitiativesScreen.tsx
  ts/screens/profile/playgrounds/IdPayCodePlayground.tsx
  ts/screens/profile/playgrounds/IdPayOnboardingPlayground.tsx
Labels: IO-Bonus e pagamenti

#6581 fix: [IOBP-1101] Add missing `Mixpanel` events/properties
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/home/analytics/index.ts
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
  ts/features/payments/receipts/analytics/index.ts
  ts/features/payments/receipts/components/HideReceiptButton.tsx
  ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
  ts/features/payments/receipts/screens/ReceiptListScreen.tsx
  ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
Labels: IO-Bonus e pagamenti

#6595 chore(IT Wallet): [SIW-1945] Disable screenshots and recordings on ITW screens
  android/settings.gradle
  ios/Podfile.lock
  package.json
  patches/patches.md
  patches/react-native-flag-secure-android+1.0.3.patch
  ts/@types/react-native-flag-secure-android.d.ts
  ts/RootContainer.tsx
  ts/components/FlagSecure.tsx
  ts/features/itwallet/identification/screens/cie/ItwCiePinScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/issuance/screens/__tests__/ItwIssuanceCredentialAuthScreen.test.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialAttachmentScreen.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialCardModal.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialFiscalCodeModal.tsx
  ts/features/itwallet/trustmark/screens/ItwCredentialTrustmarkScreen.tsx
  ts/features/payments/onboarding/screens/PaymentsOnboardingSelectMethodScreen.tsx
  ts/store/reducers/__tests__/allowedSnapshotScreens.test.ts
  ts/store/reducers/allowedSnapshotScreens.ts
  ts/utils/hooks/__tests__/usePreventScreenCapture.test.tsx
  ts/utils/hooks/usePreventScreenCapture.ts
  yarn.lock
Labels: IT Wallet

#6577 feat(IT Wallet): [SIW-1918] Add iPatente CTA in MDL details screen
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/itwallet/common/store/selectors/remoteConfig.ts
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/navigation/useItwLinkingOptions.tsx
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/presentation/components/ItwPresentationDetailsFooter.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationDetailFooter.test.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/itwallet/trustmark/components/ItwCredentialTrustmark.tsx
  ts/features/wallet/store/selectors/index.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IT Wallet

#6585 refactor: [IOBP-1096] Replace legacy markdown component for IDPay
  ts/features/idpay/details/components/InitiativeRulesInfoBox.tsx
  ts/features/idpay/onboarding/components/OnboardingDescriptionMarkdown.tsx
  ts/features/idpay/onboarding/screens/InitiativeDetailsScreen.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
Labels: IO-Bonus e pagamenti

#6586 refactor: [IOBP-1115] Replace deprecated components and functions for IDPay
  ts/features/idpay/barcode/navigation/navigator.tsx
  ts/features/idpay/barcode/screens/IdPayBarcodeResultScreen.tsx
  ts/features/idpay/code/navigation/navigator.tsx
  ts/features/idpay/code/screens/IdPayCodeDisplayScreen.tsx
  ts/features/idpay/code/screens/IdPayCodeRenewScreen.tsx
  ts/features/idpay/code/screens/__tests__/IdPayCodeDisplayScreen.test.tsx
  ts/features/idpay/code/screens/__tests__/IdPayCodeOnboardingScreen.test.tsx
  ts/features/idpay/configuration/navigation/navigator.tsx
  ts/features/idpay/configuration/screens/ConfigurationSuccessScreen.tsx
  ts/features/idpay/configuration/screens/IbanConfigurationLandingScreen.tsx
  ts/features/idpay/configuration/screens/IbanEnrollmentScreen.tsx
  ts/features/idpay/configuration/screens/IbanOnboardingScreen.tsx
  ts/features/idpay/configuration/screens/IdPayDiscountInstrumentsScreen.tsx
  ts/features/idpay/configuration/screens/InitiativeConfigurationIntroScreen.tsx
  ts/features/idpay/configuration/screens/InstrumentsEnrollmentScreen.tsx
  ts/features/idpay/details/components/__tests__/TimelineOperationListItem.test.tsx
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
  ts/features/idpay/details/screens/IdPayOperationsListScreen.tsx
  ts/features/idpay/details/screens/__tests__/IdPayInitiativeDetailsScreen.test.tsx
  ts/features/idpay/onboarding/navigation/navigator.tsx
  ts/features/idpay/onboarding/screens/BoolValuePrerequisitesScreen.tsx
  ts/features/idpay/onboarding/screens/CompletionScreen.tsx
  ts/features/idpay/onboarding/screens/InitiativeDetailsScreen.tsx
  ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
Labels: IO-Bonus e pagamenti

#6598 [IOCOM-1848] Analytics for Push Notifications Engagement
  ts/features/landingScreenMultiBanner/components/LandingScreenBannerPicker.tsx
  ts/features/landingScreenMultiBanner/components/__tests__/LandingScreenBannerPicker.test.tsx
  ts/features/pushNotifications/analytics/__tests__/index.test.ts
  ts/features/pushNotifications/analytics/index.ts
  ts/features/pushNotifications/components/PushNotificationsBanner.tsx
  ts/features/pushNotifications/components/__tests__/PushNotificationsBanner.test.tsx
  ts/features/pushNotifications/components/__tests__/__snapshots__/PushNotificationsBanner.test.tsx.snap
  ts/features/pushNotifications/hooks/__tests__/usePushNotificationsBannerTracking.test.tsx
  ts/features/pushNotifications/hooks/usePushNotificationsBannerTracking.tsx
  ts/features/pushNotifications/sagas/__tests__/profileAndSystemNotificationsPermissions.test.tsx
  ts/features/pushNotifications/sagas/profileAndSystemNotificationsPermissions.ts
  ts/features/pushNotifications/store/selectors/__tests__/notificationsBannerDismissed.test.ts
  ts/features/pushNotifications/store/selectors/notificationsBannerDismissed.ts
  ts/screens/profile/ProfileMainScreenTopBanner.tsx
  ts/screens/profile/__test__/ProfileMainScreenTopBanner.test.tsx
  ts/screens/profile/analytics/__test__/index.test.ts
  ts/screens/profile/analytics/index.ts
  ts/screens/profile/components/SettingsDiscoveryBanner.tsx
  ts/screens/profile/components/__test__/SettingsDiscoveryBanner.test.tsx
  ts/screens/profile/components/__test__/__snapshots__/SettingsDiscoveryBanner.test.tsx.snap
Labels: IO-Comunicazione

#6606 [IOPID-2598] Tracking offline event
  ts/features/ingress/analytics/index.ts
  ts/features/ingress/screens/IngressScreen.tsx
Labels: IO-A&I

#6597 refactor[IOBP-1119]: Adapt IDPay custom table and list to design system components
  ts/features/idpay/common/components/Table.tsx
  ts/features/idpay/details/components/BeneficiaryDetailsContent.tsx
  ts/features/idpay/details/components/InitiativeDiscountSettingsComponent.tsx
  ts/features/idpay/details/components/InitiativeRefundSettingsComponent.tsx
  ts/features/idpay/details/components/InitiativeTimelineComponent.tsx
  ts/features/idpay/details/screens/IdPayInitiativeDetailsScreen.tsx
  ts/features/idpay/timeline/components/TimelineDiscountTransactionDetailsComponent.tsx
  ts/features/idpay/timeline/components/TimelineRefundDetailsComponent.tsx
  ts/features/idpay/timeline/components/TimelineTransactionDetailsComponent.tsx
Labels: IO-Bonus e pagamenti

#6610 [IOCOM-1914] Paid payment badge from message details
  ts/store/reducers/entities/__tests__/payments.test.ts
  ts/store/reducers/entities/payments.ts
Labels: IO-Comunicazione

#6607 feat: [PE-882] CGN new discounts count
  scripts/generate-api-models.sh
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
Labels: Carta Giovani Nazionale

#6612 chore: [IOBP-1122] Remove PSP preselection logic based on the onUs field
  locales/en/index.yml
  locales/it/index.yml
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
  ts/features/payments/checkout/screens/__tests__/WalletPaymentPickPspScreen.test.tsx
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/common/utils/__tests__/index.test.ts
  ts/features/payments/common/utils/index.ts
Labels: IO-Bonus e pagamenti

#6613 fix: [IOPAE-1688] Fix infinite scroll on the services home page
  ts/features/services/home/hooks/useInstitutionsFetcher.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/home/store/reducers/__tests__/store.test.ts
  ts/features/services/home/store/reducers/index.ts
Labels: IO-Enti e Servizi

#6608 chore [IOPID-2600] Add new content on carousel
  locales/de/index.yml
  locales/en/index.yml
  locales/it/index.yml
  locales/it/markdown_reference.md
  ts/screens/authentication/LandingScreen.tsx
  ts/screens/authentication/__tests__/__snapshots__/LandingScreen.test.tsx.snap
Labels: IO-A&I

#6616 chore: [IOBP-1141] Added `psp_selected` mixpanel property for the payment flow
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
Labels: IO-Bonus e pagamenti

#6601 [SIW-1953] Mixpanel tracking of new ITWallet feature
  scripts/generate-api-models.sh
  ts/features/fims/common/analytics/__tests__/index.test.ts
  ts/features/fims/common/analytics/index.ts
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/common/store/selectors/remoteConfig.ts
  ts/features/itwallet/credentials/saga/checkCredentialsStatusAttestation.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/presentation/components/ItwPresentationDetailsFooter.tsx
  ts/features/itwallet/presentation/components/__tests__/ItwPresentationDetailFooter.test.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialCardModal.tsx
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialFiscalCodeModal.tsx
  ts/features/itwallet/trustmark/machine/machine.ts
  ts/store/reducers/__mock__/backendStatus.ts
Labels: IT Wallet

#6614 test:[IOCOM-1828] fims history list items tests
  ts/features/fims/history/components/FimsHistoryListItemPicker.tsx
  ts/features/fims/history/components/FimsHistoryListItems.tsx
  ts/features/fims/history/components/FimsHistoryNonEmptyContent.tsx
  ts/features/fims/history/components/__mocks__/FimsHistoryListItems.tsx
  ts/features/fims/history/components/__mocks__/FimsHistoryLoaders.tsx
  ts/features/fims/history/components/__tests__/FimsHistoryListItemPicker.test.tsx
  ts/features/fims/history/components/__tests__/FimsHistoryListItems.test.tsx
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryListItemPicker.test.tsx.snap
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryListItems.test.tsx.snap
Labels: IO-Comunicazione

#6620 fix(IT Wallet): [SIW-1959] Remove ITW credentials placeholders from wallet
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerStandalone.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
  ts/features/itwallet/lifecycle/saga/handleWalletInstanceResetSaga.ts
  ts/features/itwallet/wallet/components/ItwWalletCardsContainer.tsx
  ts/features/wallet/components/WalletCardsContainer.tsx
  ts/features/wallet/store/actions/cards.ts
  ts/features/wallet/store/reducers/__tests__/cards.test.ts
  ts/features/wallet/store/reducers/cards.ts
  ts/features/wallet/store/selectors/index.ts
Labels: IT Wallet

#6619 fix(IT Wallet): [SIW-1986] Persist ITW store after logout
  ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/store/reducers/index.ts
Labels: IT Wallet

#6628 feat(privacy): [IOPID-2609] Disable screenshots and recordings in PinCreation and CiePinScreen components
  package.json
  ts/components/screens/PinCreation/PinCreation.tsx
  ts/components/screens/__tests__/PinCreation.test.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  yarn.lock
Labels: IO-A&I

#6629 chore: [IOBP-1149] Hide download receipt button if the transaction is of cart type
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/receipts/components/ReceiptInfoSection.tsx
  ts/features/payments/receipts/components/___tests___/ReceiptInfoSection.test.tsx
  ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
  ts/features/payments/receipts/screens/ReceiptListScreen.tsx
Labels: IO-Bonus e pagamenti

#6611 fix(ITWallet): [SIW-1985] Fix "ladybug" debugging tool issues
  ts/hooks/useDebugInfo.ts
  ts/store/actions/debug.ts
  ts/store/reducers/__tests__/debug.test.ts
  ts/store/reducers/debug.ts
Labels: IT Wallet

#6605 feat(IT Wallet): [SIW-1958,SIW-1974] Issuance failure support bottom sheet with Zendesk integration
  locales/en/index.yml
  locales/it/index.yml
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/features/barcode/components/BarcodeScanBaseScreenComponent.tsx
  ts/features/fci/components/ErrorComponent.tsx
  ts/features/fci/screens/valid/FciSignatureRequestsScreen.tsx
  ts/features/itwallet/common/hooks/__tests__/useItwFailureSupportModal.test.tsx
  ts/features/itwallet/common/hooks/useItwFailureSupportModal.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialFailureScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidFailureScreen.tsx
  ts/features/payments/checkout/hooks/usePaymentFailureSupportModal.tsx
  ts/features/zendesk/analytics/index.ts
  ts/features/zendesk/components/__tests__/ZendeskSupportComponent.test.tsx
  ts/features/zendesk/saga/orchestration/index.ts
  ts/features/zendesk/screens/ZendeskAskPermissions.tsx
  ts/features/zendesk/screens/ZendeskAskSeeReportsPermissions.tsx
  ts/features/zendesk/screens/ZendeskChooseCategory.tsx
  ts/features/zendesk/screens/ZendeskChooseSubCategory.tsx
  ts/features/zendesk/screens/ZendeskSeeReportsRouters.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/features/zendesk/screens/__tests__/ZendeskAskPermissions.test.tsx
  ts/features/zendesk/store/actions/index.ts
  ts/features/zendesk/store/reducers/__tests__/index.test.ts
  ts/features/zendesk/utils/index.ts
  ts/hooks/useStartSupportRequest.ts
  ts/utils/supportAssistance.ts
Labels: IT Wallet

#6580 feat(ITWallet): [SIW-1455] Reissuing expired or expiring eID
  locales/en/index.yml
  locales/it/index.yml
  ts/features/itwallet/common/components/ItwEidInfoBottomSheetContent.tsx
  ts/features/itwallet/common/components/ItwEidLifecycleAlert.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/__tests__/ItwIdentificationModeSelectionScreen.test.tsx
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/guards.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/machine/provider.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/presentation/screens/ItwPresentationEidVerificationExpiredScreen.tsx
  ts/features/itwallet/wallet/components/ItwWalletCardsContainer.tsx
Labels: IT Wallet

#6630 chore(CDC): [IOBP-1010] Remove CDC Bonus files and related functions
  assets/CdcSwagger.yml
  locales/en/index.yml
  locales/it/index.yml
  scripts/generate-api-models.sh
  ts/components/core/selection/RadioButtonList.tsx
  ts/features/bonus/cdc/analytics/index.ts
  ts/features/bonus/cdc/api/backendCdc.ts
  ts/features/bonus/cdc/components/CdcGenericError.tsx
  ts/features/bonus/cdc/components/CdcRequestCompleted.tsx
  ts/features/bonus/cdc/components/CdcRequestPartiallySuccess.tsx
  ts/features/bonus/cdc/components/CdcRequirementsError.tsx
  ts/features/bonus/cdc/components/CdcServiceCTA.tsx
  ts/features/bonus/cdc/components/CdcWrongFormat.tsx
  ts/features/bonus/cdc/components/__test__/CdcGenericError.test.ts
  ts/features/bonus/cdc/components/__test__/CdcRequestCompleted.test.ts
  ts/features/bonus/cdc/components/__test__/CdcRequestPartiallySuccess.test.ts
  ts/features/bonus/cdc/components/__test__/CdcRequirementsError.test.ts
  ts/features/bonus/cdc/components/__test__/CdcServiceCTA.test.ts
  ts/features/bonus/cdc/components/__test__/CdcWrongFormat.test.ts
  ts/features/bonus/cdc/navigation/CdcStackNavigator.tsx
  ts/features/bonus/cdc/navigation/params.ts
  ts/features/bonus/cdc/navigation/routes.ts
  ts/features/bonus/cdc/saga/index.ts
  ts/features/bonus/cdc/saga/networking/__test__/handleGetStatoBeneficiario.test.ts
  ts/features/bonus/cdc/saga/networking/__test__/handlePostRegistraBeneficiario.test.ts
  ts/features/bonus/cdc/saga/networking/handleGetStatoBeneficiario.ts
  ts/features/bonus/cdc/saga/networking/handlePostRegistraBeneficiario.ts
  ts/features/bonus/cdc/screens/CdcBonusRequestBonusRequested.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestInformationTos.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectResidence.tsx
  ts/features/bonus/cdc/screens/CdcBonusRequestSelectYear.tsx
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestBonusRequested.test.ts
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectResidence.test.ts
  ts/features/bonus/cdc/screens/__test__/CdcBonusRequestSelectYear.test.ts
  ts/features/bonus/cdc/store/actions/cdcBonusRequest.ts
  ts/features/bonus/cdc/store/actions/index.ts
  ts/features/bonus/cdc/store/reducers/__test__/cdcBonusRequest.test.ts
  ts/features/bonus/cdc/store/reducers/cdcBonusRequest.ts
  ts/features/bonus/cdc/store/reducers/index.ts
  ts/features/bonus/cdc/types/CdcBonusRequest.ts
  ts/features/bonus/cdc/utils/__tests__/bonusRequest.test.ts
  ts/features/bonus/cdc/utils/bonusRequest.ts
  ts/features/bonus/common/store/actions/index.ts
  ts/features/bonus/common/store/reducers/index.ts
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/sagas/startup.ts
  ts/store/middlewares/analytics.ts
Labels: Carta della cultura, IO-Bonus e pagamenti

#6634 refactor: [IOBP-1099] Pass language to checkout webview api
  ts/features/payments/checkout/saga/networking/handleWalletPaymentAuthorization.ts
  ts/utils/locale.ts
Labels: IO-Bonus e pagamenti

#6637 fix(Payments): [IOBP-1153,IOBP-1154] Payments mixpanel properties mapping
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/payments/history/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#6623 chore(IT Wallet): [SIW-1975] Request app review after first viewing of driving license detail screen
  ts/features/itwallet/common/hooks/useItwPendingReviewRequest.ts
  ts/features/itwallet/common/store/actions/preferences.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/itwallet/presentation/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/itwallet/wallet/components/ItwWalletCardsContainer.tsx
  ts/features/wallet/components/__tests__/WalletCardsContainer.test.tsx
Labels: IT Wallet

#6627 refactor(Cross): [IOAPPX-466] replace `peter-evans` action with `gh`
  .github/workflows/pr-title-conventional-commit-linter.yml
  .github/workflows/pr-title-linter-and-linker.yml
Labels: Cross

#6615 chore: [IOPID-2615] Add specific action to clear the session state
  ts/sagas/installation.ts
  ts/store/actions/authentication.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/authentication.ts
Labels: dont-merge :raised_hand:, legal-approved ⚖️ ✅, IO-A&I

#6636 refactor: [IOBP-1152] Replace legacy `BaseScreenComponent`
  ts/features/payments/barcode/navigation/navigator.tsx
  ts/features/payments/barcode/screens/PaymentsBarcodeChoiceScreen.tsx
  ts/features/payments/checkout/navigation/navigator.tsx
  ts/features/payments/checkout/screens/WalletPaymentInputFiscalCodeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentInputNoticeNumberScreen.tsx
Labels: IO-Bonus e pagamenti

#6642 refactor: [PE-921] CGN remove legacy and deprecated code
  ts/components/ui/RNavScreenWithLargeHeader.tsx
  ts/features/bonus/cgn/components/merchants/CgnMerchantsFilters.tsx
  ts/features/bonus/cgn/components/merchants/search/CategoryCheckbox.tsx
  ts/features/bonus/cgn/components/merchants/search/DistanceSlider.tsx
  ts/features/bonus/cgn/navigation/navigator.tsx
  ts/features/bonus/cgn/navigation/params.ts
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/discount/CgnDiscountDetailScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsTabsScreen.tsx
Labels: Carta Giovani Nazionale, Dark mode 🌝, IO-Bonus e pagamenti, 💀 Dead matter

#6645 style: [IOAPPX-473] Add dark mode support to the `ItwCredentialCard` component
  ts/features/itwallet/common/components/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/index.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwCredentialCard.test.tsx.snap
  ts/features/itwallet/common/utils/itwCredentialUtils.ts
  ts/features/payments/common/components/PaymentCard.tsx
  ts/features/payments/common/components/__tests__/__snapshots__/PaymentCard.test.tsx.snap
Labels: Design System, Dark mode 🌝, IT Wallet

#6643 test: [IOCOM-1820] useFimsHistoryResultToast tests
  ts/features/fims/history/hooks/__tests__/useFimsHistoryResultToast.test.tsx
Labels: IO-Comunicazione

#6646 chore: [IOAPPX-474] Add haptic feedback to the main cards in the `Services` section
  ts/features/services/common/components/CardPressableBase.tsx
Labels: Design System

#6640 chore(Cross): [IOAPPX-471] Add `prepare` to `setup` script
  README.md
  package.json
Labels: Cross

#6647 chore: [PE-786] CGN update support fields optional
  scripts/generate-api-models.sh
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6650 refactor: [PE-923] CGN adjust list item element spacing
  ts/features/bonus/cgn/components/merchants/CgnMerchantsListView.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6603 fix: [IOAPPX-462] Fix flickering behaviour in the search screens (Messages, Services) on iOS
  package.json
  ts/features/design-system/core/DSListItems.tsx
  yarn.lock
Labels: Bug 🐞, Design System

#6445 chore(Cross):[IOAPPX-422,IOCOM-2065] Replace the legacy markdown renderer with IOMarkdown
  scripts/generate-api-models.sh
  ts/RootContainer.tsx
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/configureStoreAndPersistor.ts
  ts/components/IOMarkdown/index.tsx
  ts/components/IOMarkdown/markdownRenderer.ts
  ts/components/IOMarkdown/renderRules.tsx
  ts/components/IOMarkdown/types.ts
  ts/components/__tests__/IOMarkdown.test.tsx
  ts/components/__tests__/__snapshots__/IOMarkdown.test.tsx.snap
  ts/components/ui/LoadingSkeleton.tsx
  ts/components/ui/Markdown/Markdown.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaInformationComponent.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
  ts/features/common/components/IOMarkdown/customRules.tsx
  ts/features/common/store/reducers/index.ts
  ts/features/fci/hooks/useFciAbortSignatureFlow.tsx
  ts/features/fims/singleSignOn/components/FimsPrivacyInfo.tsx
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/idpay/details/components/InitiativeRulesInfoBox.tsx
  ts/features/idpay/onboarding/components/OnboardingDescriptionMarkdown.tsx
  ts/features/idpay/onboarding/screens/PDNDPrerequisitesScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCiePinScreen.tsx
  ts/features/messages/components/Home/PreconditionsContent.tsx
  ts/features/messages/components/Home/__tests__/PreconditionsContent.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/PreconditionsContent.test.tsx.snap
  ts/features/messages/components/MessageDetail/MessageMarkdown.tsx
  ts/features/messages/components/MessageDetail/__mocks__/MessageMarkdown.tsx
  ts/features/messages/saga/handleMessagePrecondition.ts
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/store/actions/__tests__/preconditions.test.ts
  ts/features/messages/store/actions/preconditions.ts
  ts/features/messages/store/reducers/__tests__/messagePrecondition.test.ts
  ts/features/messages/store/reducers/messagePrecondition.ts
  ts/features/services/details/components/CardWithMarkdownContent.tsx
  ts/navigation/AuthenticationNavigator.tsx
  ts/navigation/ProfileNavigator.tsx
  ts/navigation/params/AuthenticationParamsList.ts
  ts/navigation/params/ProfileParamsList.ts
  ts/navigation/routes.ts
  ts/screens/authentication/cie/CieAuthorizeDataUsageScreen.tsx
  ts/screens/authentication/cie/CiePinScreen.tsx
  ts/screens/modal/RootedDeviceModal.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/screens/profile/components/ShareDataComponent/ShareDataFeatureInfos.tsx
  ts/screens/profile/components/services/ManualConfigBottomSheet.tsx
  ts/screens/profile/playgrounds/MarkdownPlayground.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/actions/preferences.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
  ts/store/reducers/persistedPreferences.ts
  ts/store/reducers/preferences.ts
Labels: enhancement, Design System, Cross

#6654 test: [IOCOM-1824,IOCOM-1825] fims history emptyContent and index saga tests
  ts/features/fims/history/components/__mocks__/FimsHistoryHeaderComponent.tsx
  ts/features/fims/history/components/__tests__/FimsHistoryEmptyContent.test.tsx
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryEmptyContent.test.tsx.snap
  ts/features/fims/history/saga/__tests__/index.test.ts
Labels: IO-Comunicazione

#6657 test: [IOCOM-1827] FimsHistoryKoScreen tests
  ts/features/fims/history/components/FimsHistoryKoScreen.tsx
  ts/features/fims/history/components/__tests__/FimsHistoryKoScreen.test.tsx
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryKoScreen.test.tsx.snap
Labels: IO-Comunicazione

#6658 fix: [IOBP-1169] Psp order logic
  ts/features/payments/common/utils/index.ts
Labels: Bug 🐞, IO-Bonus e pagamenti

#6656 refactor: [IOBP-1168] Replaced `GradientScrollView` with `IOScrollView` into PSP selection screen
  ts/features/payments/checkout/screens/WalletPaymentPickPspScreen.tsx
Labels: IO-Bonus e pagamenti

#6651 test: [PE-917] CGN `WebviewComponent` additional test
  ts/components/WebviewComponent.tsx
  ts/components/__tests__/WebviewComponent.test.tsx
  ts/components/__tests__/__snapshots__/WebviewComponent.test.tsx.snap
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6659 feat: [IOCOM-1921] FIMS - Back navigation upon InApp Browser closing
  ts/features/fims/singleSignOn/saga/__tests__/handleFimsAuthorizationOrImplicitCodeFlow.test.ts
  ts/features/fims/singleSignOn/saga/handleFimsAbortOrCancel.ts
  ts/features/fims/singleSignOn/saga/handleFimsAuthorizationOrImplicitCodeFlow.ts
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
Labels: IO-Comunicazione
