Repository pagopa/io-app, pull requests merged in 2025-05, with the labels that each got.

#6921 feat(IT Wallet): [SIW-2306] Add `ItwHighlightBanner` component
  img/features/itWallet/l3/highlight.svg
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/common/components/ItwHighlightBanner.tsx
  ts/features/itwallet/common/components/__tests__/ItwHighlightBanner.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwHighlightBanner.test.tsx.snap
  ts/features/itwallet/playgrounds/components/ItwBannerSection.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
Labels: IT Wallet

#6918 feat(IT Wallet): [SIW-1965,SIW-2257] Display missing credentials for presentation
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/__mocks__/presentationClaims.json
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/presentation/remote/machine/failure.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
Labels: IT Wallet

#6931 chore(IT Wallet): [SIW-2305] Add remote presentation machine tests
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
Labels: IT Wallet

#6937 fix: [SIW-2312] Fix visual glitches in some remote presentation's screens transitions
  ts/features/itwallet/presentation/remote/machine/selectors.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteAuthResponseScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
Labels: IT Wallet

#6943 chore: [IOBP-1616] Add payment webview mixpanel tracking events
  ts/features/payments/checkout/analytics/__tests__/index.test.ts
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentWebViewScreen.tsx
  ts/features/payments/common/types/PaymentAnalytics.ts
  ts/features/payments/history/store/actions/index.ts
  ts/features/payments/history/store/reducers/index.ts
Labels: IO-Bonus e pagamenti

#6936 fix: [IOPID-2689] edit offline wallet bottomsheet button copy
  locales/en/index.json
  locales/it/index.json
Labels: Bug 🐞, IO-A&I

#6948 style: [IOBP-1623] Update hide receipt button color
  ts/features/payments/receipts/components/HideReceiptButton.tsx
Labels: IO-Bonus e pagamenti

#6935 fix(IT Wallet): [SIW-2313] Fix `flex` style on screens using `ForceScrollDownView`
  ts/features/itwallet/issuance/components/ItwCredentialPreviewClaimsList.tsx
  ts/features/itwallet/issuance/components/__tests__/__snapshots__/ItwCredentialPreviewClaimsList.test.tsx.snap
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
Labels: IT Wallet

#6914 refactor: [IOBP-1600] Update payment checkout tos
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
Labels: IO-Bonus e pagamenti

#6950 fix(IT Wallet): [SIW-2339] Disable status alert for offline mini-app
  ts/hooks/useStatusAlertProps.tsx
Labels: Bug 🐞, IT Wallet

#6951 chore: [IOBP-1612] Add payments receipt copy items with long press gesture
  ts/features/payments/common/components/PaymentListItemInfo.tsx
  ts/features/payments/common/components/__tests__/PaymentListItemInfo.test.tsx
  ts/features/payments/receipts/components/ReceiptInfoSection.tsx
  ts/features/payments/receipts/screens/ReceiptCartItemDetailsScreen.tsx
Labels: IO-Bonus e pagamenti

#6953 chore: [IOBP-1600] Adjust payment checkout tos EN text
  locales/en/index.json
Labels: IO-Bonus e pagamenti

#6957 fix:[IOPLT-1102] Warning logs on `LandingScreenComponent`
  package.json
  yarn.lock
Labels: Cross

#6949 chore: [IOAPPX-495] Automatically configure Reactotron host with the local machine's IP
  ts/boot/configureRectotron.ts
Labels: Cross

#6961 refactor: [IOBP-1624] Add extra bottom padding to CGN merchants list
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6929 feat(IT Wallet): [SIW-2211,SIW-2273] Add IT Wallet upgrade banner
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/common/components/ItwHighlightBanner.tsx
  ts/features/itwallet/common/components/ItwUpgradeBanner.tsx
  ts/features/itwallet/common/components/__tests__/ItwUpgradeBanner.test.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerStandalone.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
  ts/features/itwallet/common/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/wallet/components/WalletCardsCategoryContainer.tsx
  ts/features/wallet/components/WalletCardsContainer.tsx
  ts/features/wallet/components/WalletCategoryFilterTabs.tsx
Labels: IT Wallet

#6903 feat(IT Wallet): [SIW-2254] Remote presentation add not trusted RP failure case
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/presentation/remote/hooks/useItwRemoteUntrustedRPBottomSheet.tsx
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
  ts/features/itwallet/presentation/remote/machine/failure.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
Labels: IT Wallet

#6967 chore: [IOBP-1636] Copy and the privacy policy URL text update for payment summary page
  locales/de/index.json
Labels: IO-Bonus e pagamenti

#6958 fix(ToS): [IOPID-2989] Fix onboarding ToS scrolling
  ts/features/settings/privacy/shared/components/TosWebviewComponent.tsx
  ts/features/settings/privacy/shared/components/__test__/__snapshots__/TosWebviewComponent.test.tsx.snap
Labels: Bug 🐞, IO-A&I

#6966 chore: [IOBP-1634] Mixpanel events for hide receipt swipe action
  ts/features/payments/receipts/analytics/index.ts
  ts/features/payments/receipts/analytics/utils.ts
  ts/features/payments/receipts/components/HideReceiptButton.tsx
  ts/features/payments/receipts/components/ReceiptListItemTransaction.tsx
  ts/features/payments/receipts/components/___tests___/ReceiptListItemTransaction.test.tsx
  ts/features/payments/receipts/saga/handleDisableReceipt.ts
  ts/features/payments/receipts/store/actions/index.ts
Labels: IO-Bonus e pagamenti

#6945 fix(IT Wallet): [SIW-2317] Discovery banner not displayed when leaving eID issuance flow
  ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkCurrentWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkCurrentWalletInstanceStateSaga.ts
Labels: IT Wallet

#6960 feat: [IOCOM-2336] SEND preferences update refactor
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/pn/hooks/__tests__/useSpecialCtaPn.test.tsx
  ts/features/pn/hooks/useSpecialCtaPn.ts
  ts/features/pn/reminderBanner/screens/__test__/PnReminderBannerFlow.test.tsx
  ts/features/pn/store/actions/__tests__/index.test.ts
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/reducers/__test__/activation.test.ts
  ts/features/pn/store/reducers/activation.ts
  ts/features/pn/store/sagas/__tests__/watchPnSaga.test.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
Labels: IO-Comunicazione

#6969 fix: [IOPID-2806] Add `maxFontSizeMultiplier` to `EmailInsertScreen`
  ts/features/settings/userData/shared/screens/EmailInsertScreen.tsx
Labels: IO-A&I

#6972 feat(IT Wallet): [SIW-2309] Add link to offline FAQ on click of offline banner
  ts/features/itwallet/common/components/ItwOfflineWalletBanner.tsx
Labels: IT Wallet

#6974 fix: [IOAPPX-496] update design system version
  package.json
  yarn.lock
Labels: Bug 🐞, Design System

#6913 feat(IT Wallet): [SIW-2301] Track exception on sentry
  ts/App.tsx
  ts/features/itwallet/common/store/storages/itwSecureStorage.ts
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwRevocationUtils.ts
  ts/features/itwallet/credentials/saga/handleItwCredentialsRemoveSaga.ts
  ts/features/itwallet/lifecycle/saga/checkIntegrityServiceReadySaga.ts
  ts/features/itwallet/lifecycle/saga/handleWalletInstanceResetSaga.ts
  ts/mixpanelConfig/profileProperties.ts
  ts/mixpanelConfig/superProperties.ts
  ts/utils/sentryUtils.ts
Labels: IT Wallet

#6975 chore: [IOCOM-2364] add `reason` to `PN_SERVICE_STATUS_CHANGE_ERROR`
  ts/features/pn/analytics/index.ts
  ts/features/pn/store/sagas/__tests__/watchPnSaga.test.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
Labels: IO-Comunicazione

#6971 feat: [IOCOM-2335] addition of SEND preferences request to startupSaga
  ts/features/pn/store/sagas/__tests__/watchPnSaga.test.ts
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/services/details/saga/__tests__/handleGetServicePreference.test.ts
  ts/features/services/details/saga/handleGetServicePreference.ts
  ts/sagas/startup.ts
Labels: IO-Comunicazione

#6970 feat(IT Wallet): [SIW-2281] Add same device presentation
  locales/en/index.json
  locales/it/index.json
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
  ts/features/itwallet/presentation/remote/machine/guards.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/machine/selectors.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteAuthResponseScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteRequestValidationScreen.tsx
  ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteAuthResponseScreen.test.tsx
  ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteRequestValidation.test.tsx
  ts/features/itwallet/presentation/remote/screens/__tests__/__snapshots__/ItwRemoteAuthResponseScreen.test.tsx.snap
Labels: IT Wallet

#6976 feat: [IOCOM-2343] SEND banner i18n update
  locales/en/index.json
  locales/it/index.json
  ts/features/pn/reminderBanner/components/__test__/__snapshots__/PNActivationReminderBanner.test.tsx.snap
Labels: IO-Comunicazione

#6954 feat(IT Wallet): [SIW-2349] Add `ItwPaywallComponent`
  img/features/itWallet/l3/itw_hero.svg
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/common/components/ItwUpgradeBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerOnboarding.tsx
  ts/features/itwallet/discovery/components/ItwDiscoveryInfoComponent.tsx
  ts/features/itwallet/discovery/components/ItwPaywallComponent.tsx
  ts/features/itwallet/discovery/screens/ItwDiscoveryInfoScreen.tsx
  ts/features/itwallet/discovery/screens/__tests__/ItwDiscoveryInfoScreen.test.tsx
  ts/features/itwallet/discovery/screens/__tests__/__snapshots__/ItwDiscoveryInfoScreen.test.tsx.snap
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/events.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/playgrounds/components/ItwL3Section.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/remote/machine/actions.ts
Labels: IT Wallet

#6979 chore: [IOBP-1646] Track MyBank PSP banner on mixpanel
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/components/WalletPaymentPspBanner.tsx
Labels: IO-Bonus e pagamenti

#6920 feat(IT Wallet): [SIW-2224] Implement wallet offline Mixpanel tracking
  locales/en/index.json
  locales/it/index.json
  ts/components/error/OfflineFailure.tsx
  ts/features/ingress/store/reducer/index.ts
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/lifecycle/screens/ItwLifecycleWalletRevocationScreen.tsx
  ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationDetailsFooter.tsx
  ts/features/itwallet/presentation/details/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/itwallet/trustmark/screens/ItwCredentialTrustmarkScreen.tsx
  ts/features/itwallet/wallet/screens/ItwOfflineWalletScreen.tsx
  ts/features/itwallet/wallet/utils/withOfflineAlert.tsx
  ts/features/itwallet/wallet/utils/withOfflineFailureScreen.tsx
  ts/features/zendesk/screens/ZendeskSupportHelpCenter.tsx
  ts/hooks/__tests__/useOfflineToastGuard.test.ts
  ts/hooks/useHeaderSecondLevel.tsx
  ts/hooks/useOfflineGuard.ts
  ts/hooks/useOfflineToastGuard.ts
  ts/mixpanelConfig/___tests___/superProperties.test.ts
  ts/mixpanelConfig/superProperties.ts
  ts/utils/analytics.ts
Labels: IT Wallet

#6917 feat: [SIW-1971,SIW-2255,SIW-2258] Remote presentation error handling
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/features/itwallet/common/hooks/useItwFailureSupportModal.tsx
  ts/features/itwallet/presentation/remote/machine/actions.ts
  ts/features/itwallet/presentation/remote/machine/events.ts
  ts/features/itwallet/presentation/remote/machine/failure.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
  yarn.lock
Labels: IT Wallet

#6750 chore: [IOPLT-981] Add dark mode version to some IDP logos
  img/spid-idp-etnaid-dark.png
  img/spid-idp-infocertid-dark.png
  img/spid-idp-infocertid.png
  img/spid-idp-lepidaid-dark.png
  img/spid-idp-namirialid-dark.png
  img/spid-idp-posteid-dark.png
  img/spid-idp-sielteid-dark.png
  img/spid-idp-spiditalia-dark.png
  ts/boot/__tests__/configureStoreAndPersistor.test.ts
  ts/boot/configureStoreAndPersistor.ts
  ts/features/authentication/common/saga/__test__/authenticationSaga.test.ts
  ts/features/authentication/common/store/actions/index.ts
  ts/features/authentication/common/store/models/index.ts
  ts/features/authentication/common/store/selectors/index.ts
  ts/features/authentication/login/cie/components/__test__/CieIdLoginWebView.test.tsx
  ts/features/authentication/login/hooks/useNavigateToLoginMethod.tsx
  ts/features/authentication/login/idp/components/IdpsGrid.tsx
  ts/features/authentication/login/idp/components/__test__/IdpsGrid.test.tsx
  ts/features/authentication/login/idp/hooks/__test__/usePosteIDApp2AppEducational.test.tsx
  ts/features/authentication/login/idp/hooks/usePosteIDApp2AppEducational.tsx
  ts/features/authentication/login/idp/screens/IdpSelectionScreen.tsx
  ts/features/authentication/login/idp/screens/__test__/IdpLoginScreen.test.tsx
  ts/features/authentication/login/idp/screens/__test__/IdpSelectionScreen.test.tsx
  ts/features/authentication/login/landing/hooks/useInfoBottomsheetComponent.tsx
  ts/features/design-system/core/DSModules.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationIdpSelectionScreen.tsx
  ts/features/itwallet/machine/eid/events.ts
  ts/features/zendesk/screens/__tests__/ZendeskAskPermissions.test.tsx
  ts/store/middlewares/__tests__/analytics.test.ts
  ts/store/reducers/__mock__/idps.ts
  ts/store/reducers/__tests__/content.test.ts
  ts/store/reducers/content.ts
  ts/utils/__tests__/idps.test.ts
  ts/utils/idps.ts
Labels: Dark mode 🌝

#6988 fix: [IOCOM-2361] Support for HTTP on messages and services IOMarkdown
  ts/components/ui/Markdown/handlers/__test__/link.test.ts
  ts/components/ui/Markdown/handlers/link.ts
  ts/features/common/components/IOMarkdown/__test__/customRules.test.tsx
  ts/features/common/components/IOMarkdown/customRules.tsx
Labels: IO-Comunicazione

#6965 feat: [IOCOM-2315] Automatic pdf extension on messages' attachments
  ts/features/messages/saga/__test__/handleDownloadAttachment.test.ts
  ts/features/messages/saga/handleDownloadAttachment.ts
Labels: IO-Comunicazione

#6947 fix: [IOPLT-1118] Disable the iridescent effect on `ItwCredentialTrustmark` if `reduceMotion` is enabled
  ts/features/itwallet/trustmark/components/ItwCredentialTrustmark.tsx
Labels: a11y

#6984 feat: [IOCOM-2145,IOCOM-2297] Announce selected message when archiving
  ts/features/messages/components/Home/WrappedListItemMessage.tsx
  ts/features/messages/components/Home/__tests__/WrappedListItemMessage.test.tsx
Labels: IO-Comunicazione

#6987 feat: [IOPID-2958] add MP tracking on 404 error page
  ts/features/pageNotFound/analytics/index.ts
  ts/features/pageNotFound/screens/index.tsx
Labels: legal-approved ⚖️ ✅, IO-A&I

#6977 docs: [IOPID-2990] startup saga analysis
  ts/features/settings/common/sagas/profile.ts
  ts/sagas/startup.diagram.README.md
  ts/sagas/startup.ts
Labels: IO-A&I

#6982 chore: [IOBP-1556] Add analytics for delete wallet payment method event
  ts/features/payments/details/analytics/index.ts
  ts/features/payments/details/components/PaymentsMethodDetailsDeleteButton.tsx
Labels: legal-approved ⚖️ ✅, IO-Bonus e pagamenti

#6993 chore: [IOCOM-2337] services selectors rename
  ts/features/bonus/common/store/selectors/index.ts
  ts/features/fims/common/analytics/__tests__/index.test.ts
  ts/features/fims/common/analytics/index.ts
  ts/features/fims/common/hooks/index.tsx
  ts/features/fims/singleSignOn/saga/handleFimsAuthorizationOrImplicitCodeFlow.ts
  ts/features/fims/singleSignOn/saga/sagaUtils.ts
  ts/features/idpay/onboarding/screens/IdPayPDNDPrerequisitesScreen.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/components/MessageDetail/detailsUtils.ts
  ts/features/messages/navigation/MessagesNavigator.tsx
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/messages/saga/handleLoadMessageData.ts
  ts/features/messages/saga/handlePaymentStatusForAnalyticsTracking.ts
  ts/features/messages/saga/handleThirdPartyMessage.ts
  ts/features/pn/hooks/__tests__/useSpecialCtaPn.test.tsx
  ts/features/pn/hooks/useSpecialCtaPn.ts
  ts/features/pn/reminderBanner/reducer/__test__/bannerDismiss.test.ts
  ts/features/pn/reminderBanner/reducer/bannerDismiss.ts
  ts/features/services/details/screens/ServiceDetailsScreen.tsx
  ts/features/services/details/store/reducers/__tests__/servicesById.test.ts
  ts/features/services/details/store/reducers/index.ts
  ts/sagas/startup.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IO-Comunicazione

#6983 feat: [IOCOM-2337] SEND banner visibility logic refactor
  ts/features/pn/reminderBanner/components/PnBannerFlowComponents.tsx
  ts/features/pn/reminderBanner/components/__test__/PnBannerFlowComponents.test.tsx
  ts/features/pn/reminderBanner/components/__test__/__snapshots__/PnBannerFlowComponents.test.tsx.snap
  ts/features/pn/reminderBanner/reducer/__test__/bannerDismiss.test.ts
  ts/features/pn/reminderBanner/reducer/bannerDismiss.ts
Labels: IO-Comunicazione

#6996 fix(IT Wallet): [SIW-2408] Show dismissal dialog in missing credentials failure screen
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
Labels: IT Wallet

#6985 feat(IT Wallet): [SIW-2407] Add reducer, saga, and selector to detect NFC support
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/identification/saga/__tests__/checkHasNfcFeatureSaga.test.ts
  ts/features/itwallet/identification/saga/index.ts
  ts/features/itwallet/identification/store/actions/index.ts
  ts/features/itwallet/identification/store/reducers/index.ts
  ts/features/itwallet/identification/store/selectors/index.ts
Labels: IT Wallet

#6995 feat(IT Wallet): [SIW-2347] Enable attestation generation with fallback over TEE
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: IT Wallet

#7000 chore(IT Wallet): [SIW-2424] Remove banners within offline app
  ts/features/itwallet/common/helpers/withOfflineAlert.tsx
  ts/features/itwallet/common/helpers/withOfflineFailureScreen.tsx
  ts/features/itwallet/common/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/trustmark/screens/ItwCredentialTrustmarkScreen.tsx
  ts/features/itwallet/wallet/components/ItwWalletCardsContainer.tsx
  ts/features/itwallet/wallet/screens/ItwOfflineWalletScreen.tsx
  ts/features/wallet/components/WalletCardsCategoryContainer.tsx
Labels: IT Wallet

#7003 feat(IT Wallet): [SIW-2411] Track banner and tap events in offline banner
  ts/features/itwallet/common/components/ItwOfflineWalletBanner.tsx
Labels: IT Wallet

#7005 chore(IT Wallet): [SIW-2439] Add missing test for store migration (43→44)
  ts/boot/__tests__/configureStoreAndPersistor.test.ts
Labels: IT Wallet

#7002 fix(IT Wallet): [SIW-2366] Display image claims in the presentation disclosure screen
  ts/features/itwallet/presentation/remote/components/ItwRemotePresentationDetails.tsx
Labels: IT Wallet

#7001 fix: [IOPID-2953] Lollipop key generation tracking
  ts/features/lollipop/saga/index.ts
  ts/features/onboarding/screens/OnboardingCompletedScreen.tsx
Labels: IO-A&I

#7011 fix(IT Wallet): [SIW-2410] Unrecognized attribute in presentation disclosures screen
  ts/features/itwallet/presentation/remote/utils/__tests__/itwRemotePresentationUtils.test.ts
  ts/features/itwallet/presentation/remote/utils/itwRemotePresentationUtils.ts
Labels: IT Wallet

#7009 fix: [IOCOM-2378] Continuos registration of push notification's token
  ts/features/pushNotifications/store/reducers/__tests__/installation.test.ts
  ts/features/pushNotifications/store/reducers/installation.ts
Labels: IO-Comunicazione

#7019 feat(IT Wallet): [SIW-2376] Add FAQ link for devices that do not support NFC
  ts/features/itwallet/discovery/components/ItwNfcNotSupportedComponent.tsx
Labels: IT Wallet

#7025 fix: [IOBP-1700] Payment webview alert flow closed
  ts/features/payments/checkout/components/WalletPaymentWebView.tsx
  ts/features/payments/checkout/components/__tests__/WalletPaymentWebView.test.tsx
Labels: IO-Bonus e pagamenti

#7032 chore: [IOPLT-1149] Normalise threshold used to hide elements on smaller screens
  ts/components/BonusCard/BonusCardScreenComponent.tsx
  ts/features/authentication/login/optIn/screens/OptInScreen.tsx
  ts/features/settings/security/shared/components/PinCreation.tsx
  ts/hooks/useDetectSmallScreen.ts
Labels: Design System

#7030 fix(IT Wallet): [SIW-2445] Infinite loading screen when starting presentation after full authentication
  ts/features/itwallet/presentation/remote/screens/ItwRemoteRequestValidationScreen.tsx
  ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteRequestValidation.test.tsx
Labels: IT Wallet

#7036 fix(IT Wallet): [SIW-2349] Fix double header glitch in offline wallet screen
  ts/features/onboarding/screens/__tests__/OnboardingShareDataScreen.test.tsx
  ts/features/onboarding/screens/biometric&securityChecks/__test__/FingerprintScreen.test.tsx
  ts/features/onboarding/screens/biometric&securityChecks/__test__/MissingDeviceBiometricScreen.test.tsx
  ts/features/onboarding/screens/biometric&securityChecks/__test__/MissingDevicePinScreen.test.tsx
  ts/hooks/useStatusAlertProps.tsx
Labels: Bug 🐞, android, IT Wallet

#7039 fix: [IOBP-1722] CGN Barcode width scale
  ts/features/bonus/cgn/screens/discount/CgnDiscountCodeScreen.tsx
Labels: Bug 🐞, IO-Bonus e pagamenti

#7040 chore: [IOBP-1723] Disable pagoPA UAT toggle if app is in local env
  locales/en/index.json
  locales/it/index.json
  ts/features/settings/common/navigation/__test__/__snapshots__/SettingsNavigator.test.tsx.snap
  ts/features/settings/devMode/components/DeveloperModeSection.tsx
Labels: IO-Bonus e pagamenti
