Repository pagopa/io-app, pull requests merged in 2025-06, with the labels that each got.

#7010 refactor: [IOPID-3051,IOAS-42] Disable `autofocus` in `EmailInsertScreen` if the screen is zoomed (iOS only).
  ts/features/authentication/common/screens/__test__/TestAuthenticationScreen.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsBody.test.tsx
  ts/features/services/details/components/__tests__/ServiceDetailsScreenPn.test.tsx
  ts/features/settings/userData/shared/screens/EmailInsertScreen.tsx
  ts/utils/device.ts
Labels: IO-A&I

#7031 chore: [IOPID-2962]: add logout events and fix logout logic
  ts/features/authentication/common/saga/__test__/watchLogoutSaga.test.ts
  ts/features/authentication/common/saga/watchLogoutSaga.ts
  ts/features/settings/common/analytics/index.ts
  ts/features/settings/common/screens/ProfileMainScreen.tsx
  ts/features/settings/common/screens/__tests__/ProfileMainScreen.test.tsx
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: Bug 🐞, IO-A&I

#7052 chore: [IOCOM-2398,IOCOM-2373] update i18n and color for SEND engagement banner
  locales/en/index.json
  locales/it/index.json
  ts/features/pn/reminderBanner/components/PNActivationReminderBanner.tsx
  ts/features/pn/reminderBanner/components/__test__/__snapshots__/PNActivationReminderBanner.test.tsx.snap
  ts/features/pn/reminderBanner/components/__test__/__snapshots__/PnBannerFlowComponents.test.tsx.snap
Labels: IO-Comunicazione

#6911 feat: [IOBP-1598] Listitem swipe action component
  ts/components/ListItemSwipeAction.tsx
  ts/components/__tests__/ListItemSwipeAction.test.tsx
  ts/features/payments/home/components/PaymentsHomeTransactionsList.tsx
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
  ts/features/payments/receipts/analytics/index.ts
  ts/features/payments/receipts/analytics/utils.ts
  ts/features/payments/receipts/components/HideReceiptButton.tsx
  ts/features/payments/receipts/components/ReceiptFadeInOutAnimationView.tsx
  ts/features/payments/receipts/components/ReceiptListItemTransaction.tsx
  ts/features/payments/receipts/components/___tests___/HideReceiptButton.test.tsx
  ts/features/payments/receipts/components/___tests___/ReceiptListItemTransaction.test.tsx
  ts/features/payments/receipts/saga/handleDisableReceipt.ts
  ts/features/payments/receipts/screens/ReceiptListScreen.tsx
  ts/features/payments/receipts/store/actions/index.ts
Labels: enhancement, IO-Bonus e pagamenti

#7042 fix(IT Wallet): [SIW-2492] Infinite loading when starting a presentation while another one is pending
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
  ts/features/itwallet/presentation/remote/machine/events.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteRequestValidationScreen.tsx
  ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteRequestValidation.test.tsx
Labels: IT Wallet

#7056 chore: [IOCOM-2412] Remove Roboto
  ios/ItaliaApp/Info.plist
Labels: Cross

#6989 feat(IT Wallet): [SIW-2259,SIW-2473] New driving license details
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/__mocks__/L3/dcL3.json
  ts/features/itwallet/__mocks__/L3/mdlL3.json
  ts/features/itwallet/__mocks__/L3/tsL3.json
  ts/features/itwallet/common/components/ItwBadge.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwHighlightBanner.tsx
  ts/features/itwallet/common/utils/constants.ts
  ts/features/itwallet/common/utils/itwCredentialUtils.ts
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/common/utils/itwStyleUtils.ts
  ts/features/itwallet/discovery/components/ItwPaywallComponent.tsx
  ts/features/itwallet/navigation/ItwParamsList.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/navigation/routes.ts
  ts/features/itwallet/playgrounds/components/ItwL3Section.tsx
  ts/features/itwallet/playgrounds/components/ItwSkeumorphicCredentialSection.tsx
  ts/features/itwallet/playgrounds/navigation/ItwPlaygroundParamsList.ts
  ts/features/itwallet/playgrounds/navigation/ItwPlaygroundStackNavigator.tsx
  ts/features/itwallet/playgrounds/navigation/routes.ts
  ts/features/itwallet/playgrounds/screens/ItwL3CredentialDetailScreen.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationCredentialCard.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationCredentialInfoAlert.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationDetailsHeader.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationDetailsScreenBase.tsx
  ts/features/itwallet/presentation/details/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/settings/devMode/components/DeveloperModeSection.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
Labels: IT Wallet

#6986 feat(IT Wallet): [SIW-2298] Elimination local FF for L3
  ts/features/itwallet/common/store/actions/preferences.ts
  ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/itwallet/playgrounds/components/ItwL3Section.tsx
Labels: IT Wallet

#7060 chore: [IOBP-1734] Add CdC mixpanel tracking events
  ts/features/bonus/cdc/activation/screens/CdcBonusRequestInformationTos.tsx
  ts/features/bonus/cdc/analytics/index.ts
  ts/features/bonus/cdc/hooks/useSpecialCtaCdc.tsx
Labels: IO-Bonus e pagamenti

#7058 refactor: [IOBP-1733] Apply animated `Pictogram`
  ts/features/bonus/cgn/screens/CgnDetailScreen.tsx
  ts/features/bonus/cgn/screens/activation/CgnActivationCompletedScreen.tsx
  ts/features/bonus/cgn/screens/activation/CgnActivationIneligibleScreen.tsx
  ts/features/bonus/cgn/screens/activation/CgnActivationLoadingScreen.tsx
  ts/features/bonus/cgn/screens/discount/CGNDiscountExpiredScreen.tsx
  ts/features/bonus/cgn/screens/discount/___tests___/__snapshots__/CGNDiscountExpiredScreen.test.tsx.snap
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListByCategory.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  ts/features/idpay/barcode/screens/IdPayBarcodeResultScreen.tsx
  ts/features/idpay/code/screens/IdPayCodeResultScreen.tsx
  ts/features/idpay/configuration/screens/IdPayConfigurationSuccessScreen.tsx
  ts/features/idpay/onboarding/screens/IdPayCompletionScreen.tsx
  ts/features/idpay/onboarding/screens/IdPayFailureScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentResultScreen.tsx
  ts/features/idpay/unsubscription/screens/IdPayUnsubscriptionResultScreen.tsx
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/__tests__/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
  ts/features/payments/details/components/PaymentsMethodDetailsErrorContent.tsx
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
  ts/features/payments/onboarding/screens/PaymentsOnboardingSelectMethodScreen.tsx
  ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
  ts/features/payments/receipts/screens/ReceiptListScreen.tsx
  ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
Labels: Design System, IO-Bonus e pagamenti

#7063 refactor: [IOBP-1740] Update CAC for card onboarding auth error
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
  ts/features/payments/onboarding/screens/__tests__/PaymentsOnboardingFeedbackScreen.test.tsx
Labels: IO-Bonus e pagamenti

#7065 refactor: [IOBP-1743] Change text of help center CTA from PAYMENT_CANCELED error
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/checkout/components/WalletPaymentFailureDetail.tsx
Labels: IO-Bonus e pagamenti

#7054 feat: [IOCOM-2301,IOCOM-2414] Message payments V2
  scripts/api-config.json
  scripts/generate-api-models.sh
  ts/api/backend.ts
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/__tests__/configureStoreAndPersistor.test.ts
  ts/boot/configureStoreAndPersistor.ts
  ts/features/messages/components/MessageDetail/MessageDetailsPaymentButton.tsx
  ts/features/messages/components/MessageDetail/MessagePaymentItem.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessagePaymentItem.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/detailsUtils.test.ts
  ts/features/messages/components/MessageDetail/detailsUtils.ts
  ts/features/messages/saga/__test__/handlePaymentStatusForAnalyticsTracking.test.ts
  ts/features/messages/saga/__test__/handlePaymentUpdateRequests.test.ts
  ts/features/messages/saga/handlePaymentStatusForAnalyticsTracking.ts
  ts/features/messages/saga/handlePaymentUpdateRequests.ts
  ts/features/messages/saga/index.ts
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/messages/store/actions/__tests__/index.test.ts
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/__tests__/payments.test.ts
  ts/features/messages/store/reducers/payments.ts
  ts/features/messages/utils/__tests__/index.test.ts
  ts/features/messages/utils/index.ts
  ts/features/pn/analytics/index.ts
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageFooter.tsx
  ts/features/pn/components/MessagePaymentBottomSheet.tsx
  ts/features/pn/components/__test__/MessagePaymentBottomSheet.test.tsx
  ts/features/pn/components/__test__/MessagePayments.test.tsx
  ts/features/pn/screens/MessageDetailsScreen.tsx
  ts/features/pn/store/actions/__tests__/index.test.ts
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/reducers/__test__/payments.test.ts
  ts/features/pn/store/reducers/payments.ts
  ts/features/pn/store/sagas/__tests__/watchPaymentStatusSaga.test.ts
  ts/features/pn/store/sagas/watchPaymentStatusSaga.ts
  ts/features/pn/utils/__tests__/index.test.ts
  ts/features/pn/utils/index.ts
  ts/features/settings/common/navigation/__test__/__snapshots__/SettingsNavigator.test.tsx.snap
  ts/features/settings/devMode/components/DeveloperModeSection.tsx
  ts/sagas/legacyWallet/pagopaApis.ts
  ts/store/actions/__tests__/persistedPreferences.test.ts
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/__tests__/persistedPreferences.test.ts
  ts/store/reducers/entities/__tests__/payments.test.ts
  ts/store/reducers/entities/payments.ts
  ts/store/reducers/persistedPreferences.ts
  ts/utils/errors.ts
Labels: IO-Comunicazione

#7053 feat(IT Wallet): [SIW-2498] Add IT Wallet environments
  .env.local
  .env.production
  locales/en/index.json
  locales/it/index.json
  ts/components/DebugInfoOverlay.tsx
  ts/config.ts
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/api/client.ts
  ts/features/itwallet/common/components/ItwEnvironmentAlert.tsx
  ts/features/itwallet/common/components/__tests__/ItwEnvironmentAlert.test.tsx
  ts/features/itwallet/common/saga/environment.ts
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/actions/environment.ts
  ts/features/itwallet/common/store/actions/index.ts
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/reducers/__tests__/environment.test.ts
  ts/features/itwallet/common/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/common/store/reducers/environment.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/common/store/selectors/__tests__/environment.test.ts
  ts/features/itwallet/common/store/selectors/environment.ts
  ts/features/itwallet/common/utils/environment.ts
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwCredentialIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwIntegrityUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwRevocationUtils.ts
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
  ts/features/itwallet/identification/screens/cieId/ItwCieIdLoginScreen.tsx
  ts/features/itwallet/identification/screens/spid/ItwSpidIdpLoginScreen.tsx
  ts/features/itwallet/lifecycle/saga/__tests__/checkIntegrityServiceReadySaga.test.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkCurrentWalletInstanceStateSaga.ts
  ts/features/itwallet/lifecycle/saga/checkIntegrityServiceReadySaga.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/actors.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/provider.tsx
  ts/features/itwallet/playgrounds/components/ItwEnvironmentSection.tsx
  ts/features/itwallet/playgrounds/components/ItwL3Section.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/trialSystem/saga/checkFiscalCodeIsEnabledSaga.ts
  ts/features/itwallet/trustmark/machine/actors.ts
  ts/features/itwallet/trustmark/machine/provider.tsx
  ts/features/itwallet/trustmark/utils/__tests__/index.ts
  ts/features/itwallet/trustmark/utils/index.ts
  ts/features/wallet/components/WalletCardsContainer.tsx
Labels: IT Wallet

#7071 chore: [IOPLT-1169] Add static version to `AnimatedPictogram` when `reduceMotion` is enabled
  ts/components/ui/AnimatedPictogram.tsx
  ts/features/bonus/cgn/screens/discount/___tests___/__snapshots__/CGNDiscountExpiredScreen.test.tsx.snap
  ts/features/payments/checkout/screens/__tests__/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
Labels: a11y, Design System

#7072 chore: [IOBP-1746] Update cdc TOS
  ts/features/bonus/cdc/activation/screens/CdcBonusRequestInformationTos.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
Labels: Carta della cultura, IO-Bonus e pagamenti

#7080 chore: [IOBP-1739] Add refetch latest receipts delay after closing the payment flow
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/__tests__/WalletPaymentOutcomeScreen.test.tsx
Labels: IO-Bonus e pagamenti

#7082 fix: [IOBP-1695] PAYMENT_HOME mixpanel event dispatched too many times
  ts/features/payments/home/screens/PaymentsHomeScreen.tsx
Labels: IO-Bonus e pagamenti

#7075 feat: [IOCOM-2353] SEND service status profile property
  ts/features/pn/analytics/__test__/index.test.ts
  ts/features/pn/analytics/index.ts
  ts/features/pn/reminderBanner/reducer/__test__/bannerDismiss.test.ts
  ts/features/pn/reminderBanner/reducer/bannerDismiss.ts
  ts/features/services/common/saga/__tests__/index.test.ts
  ts/features/services/common/saga/__tests__/specialServicePreferencesSaga.test.ts
  ts/features/services/common/saga/index.ts
  ts/features/services/common/saga/specialServicePreferencesSaga.ts
  ts/mixpanelConfig/___tests___/profileProperties.test.ts
  ts/mixpanelConfig/profileProperties.ts
Labels: IO-Comunicazione

#7067 chore(IT Wallet): [SIW-2535] Add tests for `credentials` reducer migrations
  ts/features/itwallet/credentials/store/reducers/__tests__/migrations.test.ts
Labels: IT Wallet

#7087 fix: [IOCOM-2439] Message's eCommerce API
  ts/api/backend.ts
  ts/features/messages/analytics/__test__/index.test.ts
  ts/features/messages/analytics/index.ts
  ts/features/messages/saga/__test__/handlePaymentUpdateRequests.test.ts
  ts/features/messages/saga/handlePaymentUpdateRequests.ts
Labels: IO-Comunicazione

#7074 feat: [IOBP-1744] Add the possibility to disable FIMS iOS cookie sharing
  scripts/generate-api-models.sh
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/fims/common/analytics/__tests__/index.test.ts
  ts/features/fims/common/analytics/index.ts
  ts/features/fims/common/hooks/__test__/index.test.tsx
  ts/features/fims/common/hooks/index.tsx
  ts/features/fims/common/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/fims/singleSignOn/saga/__tests__/handleFimsAuthorizationOrImplicitCodeFlow.test.ts
  ts/features/fims/singleSignOn/saga/handleFimsAuthorizationOrImplicitCodeFlow.ts
  ts/features/fims/singleSignOn/saga/index.ts
  ts/features/fims/singleSignOn/screens/FimsFlowHandlerScreen.tsx
  ts/features/fims/singleSignOn/screens/__test__/FimsFlowHandlerScreen.test.tsx
  ts/features/fims/singleSignOn/store/actions/index.ts
  ts/features/fims/singleSignOn/store/reducers/index.ts
  ts/features/fims/singleSignOn/store/selectors/index.ts
  ts/store/reducers/backendStatus/__tests__/remoteConfig.test.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IO-Comunicazione, IO-Bonus e pagamenti

#7091 fix(iOS): [SIW-2558] Restore `Images.xcassets` reference in `project.pbxproj`
  ios/ItaliaApp.xcodeproj/project.pbxproj
  ios/Podfile.lock
Labels: Bug 🐞, IT Wallet

#7077 feat(IT Wallet): [SIW-2395] Store Wallet Attestation in multiple formats
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwIoReactNativeWalletProxy.ts
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/lifecycle/store/selectors/index.ts
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/context.ts
  ts/features/itwallet/machine/credential/guards.ts
  ts/features/itwallet/machine/credential/machine.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/guards.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/playgrounds/components/ItwEnvironmentSection.tsx
  ts/features/itwallet/playgrounds/components/ItwL3Section.tsx
  ts/features/itwallet/trustmark/machine/__tests__/guards.test.ts
  ts/features/itwallet/trustmark/machine/__tests__/machine.test.ts
  ts/features/itwallet/trustmark/machine/context.ts
  ts/features/itwallet/trustmark/machine/guards.ts
  ts/features/itwallet/trustmark/machine/machine.ts
  ts/features/itwallet/walletInstance/store/actions/index.ts
  ts/features/itwallet/walletInstance/store/reducers/__tests__/migrations.test.ts
  ts/features/itwallet/walletInstance/store/reducers/index.ts
  ts/features/itwallet/walletInstance/store/selectors/index.ts
  yarn.lock
Labels: IT Wallet

#7095 chore(IT Wallet): [SIW-2493] New failure screen for unexpected errors in remote presentation flow
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
Labels: IT Wallet

#7076 chore: [IOAPP-007] bump vision camera to `4.7.0` to have 16k page size support
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: Cross

#7097 refactor: [IOPID-3155] This PR retrieves the login URL from the remote config
  scripts/generate-api-models.sh
  ts/features/authentication/common/utils/login.ts
  ts/features/authentication/login/cie/components/CieIdLoginWebView.tsx
  ts/features/authentication/login/cie/components/CieRequestAuthenticationOverlay.tsx
  ts/features/authentication/login/cie/screens/CiePinScreen.tsx
  ts/features/authentication/login/cie/screens/__test__/__snapshots__/CieIdLoginScreen.test.tsx.snap
  ts/features/authentication/login/cie/utils/index.ts
  ts/features/authentication/login/idp/screens/IdpLoginScreen.tsx
  ts/features/authentication/login/idp/screens/idpAuthSessionHandler.tsx
  ts/features/authentication/loginPreferences/store/__tests__/selectors.test.ts
  ts/features/authentication/loginPreferences/store/selectors/index.ts
Labels: IO-A&I

#6991 feat: [SIW-2221] New Wallet L3 design
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/common/components/ItwBadge.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/ItwCardValidityCheckMark.tsx
  ts/features/itwallet/common/components/ItwCredentialCard/ItwCredentialCard.tsx
  ts/features/itwallet/common/components/ItwEidDetail.tsx
  ts/features/itwallet/common/components/ItwEidLifecycleAlert.tsx
  ts/features/itwallet/common/components/ItwWalletCardsWrapper.tsx
  ts/features/itwallet/common/components/ItwWalletReadyBanner.tsx
  ts/features/itwallet/common/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/common/store/selectors/index.ts
  ts/features/itwallet/common/utils/constants.ts
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/wallet/components/ItwWalletCardsContainer.tsx
  ts/features/wallet/components/WalletCardsContainer.tsx
  ts/features/wallet/screens/WalletHomeScreen.tsx
Labels: IT Wallet

#7109 fix: [IOCOM-2451] payment reminder alert empty focus
  ts/features/messages/hooks/useMessageReminder.ts
Labels: a11y, IO-Comunicazione

#7107 fix: [IOCOM-2450] SEND banner optimistic render fix
  ts/features/pn/reminderBanner/components/PNActivationReminderBanner.tsx
  ts/features/pn/reminderBanner/components/__test__/PNActivationReminderBanner.test.tsx
  ts/features/pn/reminderBanner/reducer/__test__/bannerDismiss.test.ts
  ts/features/pn/reminderBanner/reducer/bannerDismiss.ts
Labels: IO-Comunicazione

#7086 feat(IT Wallet): [SIW-2429,SIW-2594] Add user authorization via PIN/biometric for presenting requested data
  ts/features/itwallet/presentation/proximity/machine/actors.ts
  ts/features/itwallet/presentation/proximity/machine/events.ts
  ts/features/itwallet/presentation/proximity/machine/failure.ts
  ts/features/itwallet/presentation/proximity/machine/machine.ts
  ts/features/itwallet/presentation/proximity/navigation/routes.ts
  ts/features/itwallet/presentation/proximity/screens/ItwProximityClaimsDisclosureScreen.tsx
  ts/features/itwallet/presentation/proximity/screens/ItwProximityFailureScreen.tsx
  ts/features/itwallet/presentation/proximity/screens/__tests__/ItwProximityFailureScreen.test.tsx
  ts/features/itwallet/presentation/proximity/screens/__tests__/__snapshots__/ItwProximityFailureScreen.test.tsx.snap
  ts/features/itwallet/presentation/proximity/utils/__tests__/itwProximityPresentationUtils.test.ts
  ts/features/itwallet/presentation/proximity/utils/itwProximityPresentationUtils.ts
Labels: IT Wallet

#7092 fix: [IOPID-2998,IOPID-3000,IOPID-3001,IOPID-3002,IOPID-3008,IOPID-3009,IOPID-3016]: accessibility issues
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/settings/preferences/screens/PreferencesScreen.tsx
  ts/features/settings/privacy/screens/PrivacyMainScreen.tsx
  ts/features/settings/userData/screens/FiscalCodeScreen.tsx
  ts/features/settings/userData/screens/__tests__/__snapshots__/FiscalCodeScreen.test.tsx.snap
  ts/features/settings/userData/shared/screens/EmailInsertScreen.tsx
Labels: IO-A&I

#7119 test: [IOBP-1786] Add test suite for CGN screens
  ts/features/bonus/cgn/screens/activation/__tests__/CgnActivationCompletedScreen.test.tsx
  ts/features/bonus/cgn/screens/activation/__tests__/CgnActivationIneligibleScreen.test.tsx
  ts/features/bonus/cgn/screens/activation/__tests__/CgnActivationPendingScreen.test.tsx
  ts/features/bonus/cgn/screens/activation/__tests__/CgnActivationTimeoutScreen.test.tsx
  ts/features/bonus/cgn/screens/activation/__tests__/CgnAlreadyActiveScreen.test.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#7124 fix: [IOPID-3209,IOPID-3228] Connectivity edge case
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: IO-A&I

#7123 test: [IOBP-1788] Add missing bonus common test suite
  ts/features/bonus/common/components/__tests__/AvailableBonusItem.test.tsx
  ts/features/bonus/common/components/__tests__/ProgressBar.test.tsx
  ts/features/bonus/common/components/alert/__tests__/ActionWithAlert.test.ts
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#7125 fix: [IOPID-3227] Cannot update a component (CountdownProvider) while rendering
  ts/features/settings/privacy/shared/hooks/useConfirmOptOutBottomSheet.tsx
  ts/features/settings/userData/components/CountdownComponent.tsx
Labels: IO-A&I

#7128 refactor: [IOBP-1789] Removed CGN deprecated function/component
  ts/features/bonus/cgn/navigation/actions.ts
  ts/features/bonus/cgn/saga/__tests__/orchestration/activation/handleActivationSaga.test.ts
  ts/features/bonus/cgn/saga/__tests__/orchestration/eyca/activation/eycaActivationSaga.test.ts
  ts/features/bonus/cgn/saga/networking/activation/getBonusActivationSaga.ts
  ts/features/bonus/cgn/saga/networking/eyca/activation/getEycaActivationSaga.ts
  ts/features/bonus/cgn/saga/orchestration/activation/activationSaga.ts
  ts/features/bonus/cgn/saga/orchestration/activation/handleActivationSaga.ts
  ts/features/bonus/cgn/saga/orchestration/eyca/eycaActivationSaga.ts
  ts/features/bonus/cgn/saga/orchestration/navigation/actions.ts
  ts/features/bonus/cgn/screens/eyca/activation/EycaActivationLoading.tsx
  ts/features/bonus/cgn/screens/eyca/activation/__tests__/EycaActivationLoading.test.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
  ts/features/bonus/cgn/utils/filters.ts
  ts/features/bonus/common/components/alert/ActionWithAlert.ts
  ts/features/bonus/common/navigation/navigator.tsx
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/bonus/common/store/reducers/availableBonusesTypes.ts
  ts/navigation/params/WalletParamsList.ts
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#7134 feat: [IOCOM-2465] Global mocks for `react-native-screenshot-prevent`
  jestSetup.js
  ts/features/messages/components/Home/__tests__/Toast.test.tsx
  ts/features/messages/components/Home/__tests__/WrappedListItemMessage.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsBody.test.tsx
  ts/features/pn/components/__test__/MessageBottomMenu.test.tsx
  ts/features/pn/components/__test__/MessageDetails.test.tsx
  ts/features/pn/components/__test__/MessagePaymentBottomSheet.test.tsx
  ts/features/pn/components/__test__/MessagePayments.test.tsx
  ts/features/pn/components/__test__/Timeline.test.tsx
  ts/features/pn/components/__test__/TimelineListItem.test.tsx
  ts/features/pn/screens/__test__/MessageDetailsScreen.test.tsx
Labels: IO-Comunicazione, Cross

#7130 fix: [IOCOM-2163] Accessibility focus on reminder
  docs/messages/add-remove-reminder.png
  docs/messages/add-remove-reminder.puml
  docs/messages/load-next-page-message-list.png
  docs/messages/load-next-page-message-list.puml
  docs/messages/messages-autorefresh.png
  docs/messages/messages-autorefresh.puml
  docs/messages/view-message-list.png
  docs/messages/view-message-list.puml
  ts/features/messages/components/MessageDetail/MessageDetailsReminderExpiring.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsReminderExpiring.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpiring.test.tsx.snap
  ts/features/messages/utils/__tests__/testUtils.test.tsx
  ts/features/pn/reminderBanner/components/__test__/PNActivationReminderBanner.test.tsx
Labels: IO-Comunicazione

#7079 chore: [IOPLT-1170] Extend dark mode to the `MessageDetails…` components
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/components/MessageDetail/MessageDetailsTagBox.tsx
  ts/features/messages/components/MessageDetail/OrganizationHeader.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/OrganizationHeader.test.tsx.snap
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/pn/components/F24Section.tsx
  ts/features/pn/components/MessageBottomMenu.tsx
  ts/features/pn/components/MessageDetails.tsx
  ts/features/pn/components/MessageDetailsContent.tsx
  ts/features/pn/components/__test__/__snapshots__/F24Section.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageBottomMenu.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageDetailsContent.test.tsx.snap
Labels: a11y, Dark mode 🌝

#7139 chore: [IOBP-1800] Update wallet card categories order
  ts/features/wallet/types/index.ts
Labels: IO-Bonus e pagamenti
