Repository pagopa/io-app, pull requests merged in 2025-04, with the labels that each got.

#6857 chore: [IOBP-1530] Update locales for Receipt screen tab and outcome text
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
Labels: IO-Bonus e pagamenti

#6859 chore: [IOBP-1516] Add CGN webview landing page debug error logger
  ts/components/WebviewComponent.tsx
  ts/screens/profile/CgnLandingPlayground.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6841 chore: [IOBP-1443] Adjust accessibility for `CGN` and `EYCA` status label
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/bonus/cgn/components/detail/CgnStatusDetail.tsx
  ts/features/bonus/cgn/components/detail/eyca/EycaStatusDetailsComponent.tsx
  ts/features/bonus/cgn/utils/dates.ts
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6839 feat: [IOPAE-1865] Display the total search result count
  locales/en/index.json
  locales/it/index.json
  ts/features/services/common/components/EmptyState.tsx
  ts/features/services/common/components/InstitutionListSkeleton.tsx
  ts/features/services/common/components/ServiceListSkeleton.tsx
  ts/features/services/common/components/ServicesHeader.tsx
  ts/features/services/common/components/__tests__/__snapshots__/ServicesHeaderSection.test.tsx.snap
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/institution/components/ServiceListSkeleton.tsx
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
  ts/features/services/institution/screens/__tests__/InstitutionServicesScreen.test.tsx
  ts/features/services/search/screens/SearchScreen.tsx
Labels: IO-Enti e Servizi

#6866 chore: [IOPAE-1950]: Revert keyExtractor in the services search
  ts/features/services/search/screens/SearchScreen.tsx
Labels: IO-Enti e Servizi

#6861 chore: [IOBP-1542] Adapt receipt preview PDF background color for the dark mode
  ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
Labels: Dark mode 🌝, IO-Bonus e pagamenti

#6863 chore: [IOBP-1545] CGN information tos dark mode action button
  ts/features/bonus/cgn/screens/activation/CgnActivationLoadingScreen.tsx
  ts/features/bonus/common/components/BonusInformationComponent.tsx
Labels: Carta Giovani Nazionale, Dark mode 🌝, IO-Bonus e pagamenti

#6846 chore(IT Wallet): [SIW-2174] Remove lifecycle state
  ts/components/SectionStatus/__tests__/index.test.tsx
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerOnboarding.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerOnboarding.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
  ts/features/itwallet/common/hooks/useItwDiscoveryBannerType.ts
  ts/features/itwallet/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/itwallet/common/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/common/store/reducers/index.ts
  ts/features/itwallet/credentials/saga/__tests__/handleWalletCredentialsRehydration.test.ts
  ts/features/itwallet/credentials/store/selectors/index.ts
  ts/features/itwallet/identification/screens/__tests__/ItwIdentificationModeSelectionScreen.test.tsx
  ts/features/itwallet/issuance/screens/__tests__/ItwIssuanceCredentialAsyncContinuationScreen.test.tsx
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/store/actions/index.ts
  ts/features/itwallet/lifecycle/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/lifecycle/store/reducers/index.ts
  ts/features/itwallet/lifecycle/store/selectors/__tests__/index.test.ts
  ts/features/itwallet/lifecycle/store/selectors/index.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/machine.ts
  ts/features/itwallet/onboarding/screens/__tests__/WalletCardOnboardingScreen.test.tsx
  ts/features/wallet/store/selectors/__tests__/index.test.ts
Labels: IT Wallet

#6868 chore: [IOBP-1551] Replace `GradientScrollView` with `IOScrollView`
  ts/features/bonus/cgn/screens/merchants/CgnMerchantDetailScreen.tsx
Labels: Carta Giovani Nazionale, Dark mode 🌝, IO-Bonus e pagamenti

#6858 chore(IT Wallet): [SIW-2169] Add temporary local FF for L3 features
  ts/features/itwallet/common/store/actions/preferences.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/itwallet/playgrounds/components/ItwL3Section.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
Labels: IT Wallet

#6862 chore: [IOPLT-965] Add dark mode support to `AlertModal`
  ts/components/__tests__/__snapshots__/LoadingSpinnerOverlay.test.tsx.snap
  ts/components/__tests__/__snapshots__/WebviewComponent.test.tsx.snap
  ts/components/ui/AlertModal.tsx
  ts/components/ui/Overlay.tsx
  ts/components/ui/__test__/__snapshots__/Overlay.test.tsx.snap
  ts/features/authentication/login/cie/__tests__/__snapshots__/CieIdLoginScreen.test.tsx.snap
  ts/features/messages/components/MessageAttachment/__test__/__snapshots__/PdfViewer.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/screens/profile/__test__/__snapshots__/LanguagesPreferencesScreen.test.tsx.snap
  ts/utils/hooks/bottomSheet.tsx
  ts/utils/hooks/useModalStyle.tsx
Labels: Dark mode 🌝

#6864 chore: [IOBP-1550] Align `CGN_MERCHANTS_DETAIL` screen with dark mode
  ts/features/bonus/cgn/screens/discount/CgnDiscountDetailScreen.tsx
Labels: Carta Giovani Nazionale, Dark mode 🌝, IO-Bonus e pagamenti

#6872 chore: [IOBP-1559] `payment_status` always set to `paid` – removed from analytics
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/receipts/components/HideReceiptButton.tsx
  ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
  ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
Labels: IO-Bonus e pagamenti

#6870 chore(IT Wallet): [SIW-2198] Improve serializeFailureReason for Mixpanel tracking
  ts/features/itwallet/common/utils/itwStoreUtils.ts
Labels: IT Wallet

#6836 refactor:[IOPLT-1074] Changes the connectivity check endpoint and library attribute for real connectivity status feedback
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/connectivity/saga/index.ts
  ts/features/connectivity/store/reducers/index.ts
  ts/features/connectivity/utils/index.ts
  ts/features/ingress/saga/index.ts
  ts/features/ingress/screens/IngressScreen.tsx
Labels: backend-block

#6877 chore: [IOBP-1561] Adjust `payment_method_selected` mixpanel property
  ts/features/payments/home/components/PaymentsHomeUserMethodsList.tsx
Labels: IO-Bonus e pagamenti

#6873 fix: [IOBP-1560] Mixpanel `organization_fiscal_code` property
  ts/features/payments/receipts/components/HideReceiptButton.tsx
  ts/features/payments/receipts/saga/handleDisableReceipt.ts
  ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
Labels: IO-Bonus e pagamenti

#6880 fix: [IOPLT-965] Fix `Overlay` visual regression
  ts/components/__tests__/__snapshots__/LoadingSpinnerOverlay.test.tsx.snap
  ts/components/__tests__/__snapshots__/WebviewComponent.test.tsx.snap
  ts/components/ui/AlertModal.tsx
  ts/components/ui/AlertModalOverlay.tsx
  ts/components/ui/Overlay.tsx
  ts/components/ui/__test__/__snapshots__/Overlay.test.tsx.snap
  ts/features/authentication/login/cie/__tests__/__snapshots__/CieIdLoginScreen.test.tsx.snap
  ts/features/messages/components/MessageAttachment/__test__/__snapshots__/PdfViewer.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/settings/preferences/screens/__tests__/__snapshots__/LanguagesPreferencesScreen.test.tsx.snap
Labels: Bug 🐞

#6881 refactor(authentication): [IOPID-2907] Move remaining files related to authentication feature
  ts/features/authentication/common/__tests__/TestAuthenticationScreen.test.tsx
  ts/features/authentication/common/__tests__/loadSessionInformationSaga.test.ts
  ts/features/authentication/common/__tests__/watchCheckSessionSaga.test.ts
  ts/features/authentication/common/__tests__/watchLogoutSaga.test.ts
  ts/features/authentication/common/saga/loadSessionInformationSaga.ts
  ts/features/authentication/common/saga/watchCheckSessionSaga.ts
  ts/features/authentication/common/saga/watchLogoutSaga.ts
  ts/features/authentication/common/saga/watchSessionExpiredSaga.ts
  ts/features/authentication/common/screens/TestAuthenticationScreen.tsx
  ts/features/authentication/common/store/reducers/testLogin.ts
  ts/features/authentication/common/utils/__tests__/login.test.ts
  ts/features/authentication/common/utils/login.ts
  ts/features/authentication/login/cie/__tests__/ActivateNfcScreen.test.tsx
  ts/features/authentication/login/cie/components/CieCardReadingAnimation.tsx
  ts/features/authentication/login/cie/components/CieIdLoginWebView.tsx
  ts/features/authentication/login/cie/components/CieRequestAuthenticationOverlay.tsx
  ts/features/authentication/login/cie/screens/ActivateNfcScreen.tsx
  ts/features/authentication/login/cie/screens/CieCardReaderScreen.tsx
  ts/features/authentication/login/cie/screens/CieConsentDataUsageScreen.tsx
  ts/features/authentication/login/cie/screens/CieLoginConfigScreenContent.tsx
  ts/features/authentication/login/cie/screens/CiePinScreen.tsx
  ts/features/authentication/login/cie/utils/cie.ts
  ts/features/authentication/login/idp/components/IdpsGrid.tsx
  ts/features/authentication/login/idp/screens/IdpLoginScreen.tsx
  ts/features/authentication/login/idp/screens/IdpSelectionScreen.tsx
  ts/features/authentication/login/idp/screens/idpAuthSessionHandler.tsx
  ts/features/authentication/login/idp/utils/spidErrorCode.ts
  ts/features/common/store/reducers/index.ts
  ts/features/itwallet/identification/hooks/useCieIdApp.ts
  ts/features/itwallet/identification/screens/ItwIdentificationIdpSelectionScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwActivateNfcScreen.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
  ts/features/itwallet/identification/screens/spid/ItwSpidIdpLoginScreen.tsx
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/zendesk/saga/index.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: IO-A&I

#6876 fix(IT Wallet): [SIW-2204] Fix crash in credential detail with a dynamic error when the language is not italian
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/presentation/details/components/ItwPresentationCredentialStatusAlert.tsx
  ts/features/itwallet/presentation/details/components/__tests__/ItwPresentationCredentialStatusAlert.test.tsx
  ts/features/itwallet/presentation/details/components/__tests__/__snapshots__/ItwPresentationCredentialStatusAlert.test.tsx.snap
Labels: IT Wallet

#6875 chore(IT Wallet): [SIW-2164] Update PID machine for L3 Wallet
  package.json
  ts/features/itwallet/common/store/reducers/__tests__/preferences.test.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actions.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/machine.ts
  yarn.lock
Labels: IT Wallet

#6848 feat: [IOBP-1419] CDC activation screen
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  scripts/generate-api-models.sh
  ts/features/bonus/cdc/activation/screens/CdcBonusRequestInformationTos.tsx
  ts/features/bonus/cdc/activation/screens/__tests__/CdcBonusRequestInformationTos.test.tsx
  ts/features/bonus/cdc/hooks/useSpecialCtaCdc.tsx
  ts/features/bonus/cdc/navigation/navigator.tsx
  ts/features/bonus/cdc/navigation/params.ts
  ts/features/bonus/cdc/navigation/routes.ts
  ts/features/bonus/common/screens/AvailableBonusScreen.tsx
  ts/features/services/details/components/ServiceDetailsScreenCdc.tsx
  ts/features/services/details/components/ServiceDetailsScreenComponent.tsx
  ts/features/services/details/components/__tests__/ServiceDetailsScreenCdc.test.tsx
  ts/features/services/details/components/__tests__/__snapshots__/ServiceDetailsScreenCdc.test.tsx.snap
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/store/reducers/__mock__/backendStatus.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: Carta della cultura, IO-Bonus e pagamenti

#6889 feat(IT Wallet): [SIW-2048,SIW-2192] Implement reactivation banner
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerOnboarding.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/ItwDiscoveryBanner.test.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/ItwDiscoveryBannerOnboarding.test.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerOnboarding.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
  ts/features/itwallet/common/hooks/__tests__/useItwDiscoveryBannerType.test.tsx
  ts/features/itwallet/common/hooks/useItwDiscoveryBannerType.ts
  ts/features/itwallet/lifecycle/saga/checkCurrentWalletInstanceStateSaga.ts
  ts/features/itwallet/lifecycle/saga/handleWalletInstanceResetSaga.ts
Labels: IT Wallet

#6890 fix: [IOBP-1552] Saved payment methods profile property with right value
  ts/features/payments/details/components/PaymentsMethodDetailsDeleteButton.tsx
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
  ts/mixpanelConfig/___tests___/mixpanelPropertyUtils.test.tsx
  ts/mixpanelConfig/___tests___/profileProperties.test.ts
  ts/mixpanelConfig/___tests___/superProperties.test.ts
  ts/mixpanelConfig/mixpanelPropertyUtils.ts
  ts/mixpanelConfig/profileProperties.ts
Labels: IO-Bonus e pagamenti

#6885 chore: [IOPLT-1078] Add dark mode support for `ListItemMessage`
  ts/features/messages/components/Home/DS/ListItemMessage.tsx
Labels: Dark mode 🌝

#6874 chore: [IOPLT-1076] Add dark mode support for CGN screens and modules
  ts/features/bonus/cgn/components/merchants/CgnModuleDiscount.tsx
  ts/features/bonus/cgn/components/merchants/ModuleCgnDiscount.tsx
  ts/features/bonus/cgn/components/merchants/__tests__/ModuleCgnDiscount.test.tsx
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountHeader.tsx
  ts/features/bonus/cgn/components/merchants/discount/___tests___/CgnDiscountHeader.test.tsx
  ts/features/bonus/cgn/hooks/useCgnStyle.tsx
  ts/features/bonus/cgn/screens/discount/CgnDiscountDetailScreen.tsx
Labels: Carta Giovani Nazionale, Design System, Dark mode 🌝

#6893 chore(IT Wallet): [SIW-2250] Track Wi revocation reason and attestation failure on Mixpanel
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
Labels: IT Wallet

#6895 chore: [IOBP-1577] Add remote feature flag to enable the payment webview flow
  scripts/generate-api-models.sh
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IO-Bonus e pagamenti

#6901 feat(IT Wallet): [SIW-2208] Remote presentation, update copy eID expired screen
  locales/en/index.json
  locales/it/index.json
Labels: IT Wallet

#6900 feat(IT Wallet): [SIW-2207] Remote presentation, inactive IT-Wallet failure screen
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/common/hooks/useItwDismissalDialog.tsx
  ts/features/itwallet/identification/screens/cie/ItwCieCardReaderScreen.tsx
  ts/features/itwallet/identification/screens/cieId/ItwCieIdLoginScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteFailureScreen.tsx
Labels: IT Wallet

#6878 fix: [IOCOM-2224] Proper tracking of the push notification opening analytics event
  ts/__tests__/mixpanel.test.ts
  ts/features/bonus/cgn/analytics/__tests__/index.test.ts
  ts/features/bonus/cgn/analytics/index.ts
  ts/features/fci/analytics/__tests__/index.test.ts
  ts/features/fci/analytics/index.ts
  ts/features/messages/analytics/__test__/index.test.ts
  ts/features/messages/analytics/index.ts
  ts/features/mixpanel/store/actions/__tests__/index.test.ts
  ts/features/mixpanel/store/reducer/__tests__/index.test.ts
  ts/features/payments/checkout/analytics/__tests__/index.test.ts
  ts/features/payments/checkout/analytics/index.ts
  ts/features/pushNotifications/analytics/__tests__/index.test.ts
  ts/features/pushNotifications/analytics/index.ts
  ts/features/pushNotifications/sagas/__tests__/common.test.ts
  ts/features/pushNotifications/sagas/common.ts
  ts/features/pushNotifications/store/actions/__tests__/pendingMessage.test.ts
  ts/features/pushNotifications/store/reducers/pendingMessage.ts
  ts/features/pushNotifications/utils/__tests__/configurePushNotification.test.ts
  ts/features/pushNotifications/utils/configurePushNotification.ts
  ts/features/services/common/analytics/__tests__/index.test.ts
  ts/features/services/common/analytics/index.ts
  ts/features/zendesk/analytics/__tests__/index.test.ts
  ts/features/zendesk/analytics/__tests__/indexNoZendesk.test.ts
  ts/features/zendesk/analytics/index.ts
  ts/mixpanel.ts
  ts/mixpanelConfig/___tests___/profileProperties.test.ts
  ts/mixpanelConfig/___tests___/superProperties.test.ts
  ts/mixpanelConfig/profileProperties.ts
  ts/mixpanelConfig/superProperties.ts
  ts/sagas/__tests__/mixpanel.test.ts
  ts/sagas/mixpanel.ts
  ts/store/middlewares/__tests__/analytics.test.ts
  ts/store/middlewares/__tests__/contentAnalytics.test.ts
  ts/store/middlewares/analytics.ts
  ts/store/middlewares/contentAnalytics.ts
  ts/store/reducers/__tests__/index.test.ts
Labels: IO-Comunicazione

#6905 chore(IT Wallet): [SIW-228] Track wallet bad state
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
Labels: IT Wallet

#6894 fix: [IOCOM-2142] Fix external keyboard focus on message logo
  package.json
  ts/features/messages/components/Home/DS/ListItemMessage.tsx
  ts/features/messages/components/Home/__tests__/WrappedListItemMessage.test.tsx
  ts/features/messages/components/Home/__tests__/__snapshots__/WrappedListItemMessage.test.tsx.snap
  yarn.lock
Labels: IO-Comunicazione

#6899 feat: [IOBP-1578] Payment webview flow
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/payments/checkout/components/WalletPaymentHeader.tsx
  ts/features/payments/checkout/components/WalletPaymentWebView.tsx
  ts/features/payments/checkout/components/__tests__/WalletPaymentHeader.test.tsx
  ts/features/payments/checkout/components/__tests__/WalletPaymentWebView.test.tsx
  ts/features/payments/checkout/hooks/__tests__/useWalletPaymentAuthorizationModal.test.tsx
  ts/features/payments/checkout/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/payments/checkout/navigation/navigator.tsx
  ts/features/payments/checkout/navigation/params.ts
  ts/features/payments/checkout/navigation/routes.ts
  ts/features/payments/checkout/screens/WalletPaymentWebViewScreen.tsx
  ts/features/payments/checkout/screens/__tests__/WalletPaymentWebViewScreen.test.tsx
  ts/features/payments/checkout/screens/__tests__/__snapshots__/WalletPaymentWebViewScreen.test.tsx.snap
  ts/features/payments/checkout/store/__tests__/reducer.test.ts
  ts/features/payments/checkout/store/__tests__/store.test.ts
  ts/features/payments/checkout/store/actions/orchestration.ts
  ts/features/payments/checkout/store/reducers/index.ts
  ts/features/payments/checkout/store/selectors/index.ts
Labels: enhancement, IO-Bonus e pagamenti

#6897 fix: [IOCOM-2296] Accessibility header role for IO-COM sections
  ts/components/screens/OperationResultScreenContent.tsx
  ts/components/screens/__tests__/__snapshots__/OperationResultScreenContent.test.tsx.snap
  ts/components/ui/IOScrollViewCentredContent.tsx
  ts/components/ui/__test__/__snapshots__/IOScrollViewCentredContent.test.tsx.snap
  ts/features/authentication/login/cie/__tests__/__snapshots__/CieIdAuthUrlError.test.tsx.snap
  ts/features/authentication/login/cie/__tests__/__snapshots__/CieIdErrorScreen.test.tsx.snap
  ts/features/authentication/login/cie/__tests__/__snapshots__/CieIdNotInstalled.test.tsx.snap
  ts/features/authentication/login/cie/__tests__/__snapshots__/CieIdNotInstalledScreen.test.tsx.snap
  ts/features/bonus/cgn/screens/discount/___tests___/__snapshots__/CGNDiscountExpiredScreen.test.tsx.snap
  ts/features/bonus/cgn/screens/discount/___tests___/__snapshots__/CgnDiscountCodeScreen.test.tsx.snap
  ts/features/fims/common/components/__tests__/__snapshots__/FimsUpdateAppAlert.test.tsx.snap
  ts/features/fims/history/components/FimsHistoryHeaderComponent.tsx
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryHeaderComponent.test.tsx.snap
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryKoScreen.test.tsx.snap
  ts/features/fims/history/components/__tests__/__snapshots__/FimsHistoryNonEmptyContent.test.tsx.snap
  ts/features/fims/singleSignOn/components/FimsSuccessBody.tsx
  ts/features/itwallet/issuance/screens/__tests__/__snapshots__/ItwIssuanceCredentialAsyncContinuationScreen.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/EmptyList.test.tsx.snap
  ts/features/messages/components/MessageDetail/MessageDetailsHeader.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsHeader.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageAttachment.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageGreenPassScreen.test.tsx.snap
  ts/features/messages/screens/__tests__/__snapshots__/MessageRouterScreen.test.tsx.snap
  ts/features/pageNotFound/__tests__/__snapshots__/index.tsx.snap
  ts/features/payments/checkout/screens/__tests__/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
  ts/features/pn/components/__test__/__snapshots__/MessageDetails.test.tsx.snap
  ts/features/pn/reminderBanner/components/PnBannerFlowComponents.tsx
  ts/features/pn/reminderBanner/components/__test__/__snapshots__/PnBannerFlowComponents.test.tsx.snap
  ts/features/pn/reminderBanner/screens/__test__/__snapshots__/PnReminderBannerFlow.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/MessageDetailsScreen.test.tsx.snap
  ts/features/pn/screens/__test__/__snapshots__/PaidPaymentScreen.test.tsx.snap
  ts/features/pushNotifications/screens/OnboardingNotificationsInfoScreenConsent.tsx
  ts/features/pushNotifications/screens/OnboardingNotificationsPreferencesScreen.tsx
  ts/features/pushNotifications/screens/__tests__/__snapshots__/OnboardingNotificationsInfoScreenConsent.test.tsx.snap
  ts/features/pushNotifications/screens/__tests__/__snapshots__/OnboardingNotificationsPreferencesScreen.test.tsx.snap
  ts/features/pushNotifications/screens/__tests__/__snapshots__/SystemNotificationPermissionsScreen.test.tsx.snap
Labels: IO-Comunicazione

#6906 feat: [IOBP-1593] Add header payment webview
  ts/features/payments/checkout/hooks/useWalletPaymentAuthorizationModal.tsx
  ts/features/payments/checkout/navigation/navigator.tsx
  ts/features/payments/checkout/screens/WalletPaymentWebViewScreen.tsx
  ts/features/payments/checkout/screens/__tests__/WalletPaymentWebViewScreen.test.tsx
  ts/features/payments/checkout/screens/__tests__/__snapshots__/WalletPaymentWebViewScreen.test.tsx.snap
Labels: IO-Bonus e pagamenti

#6886 chore(IT Wallet): [SIW-2055] Update iPatente cta url with saved driving license number
  ts/features/itwallet/presentation/details/components/ItwPresentationDetailsFooter.tsx
Labels: IT Wallet

#6892 refactor(identification): [IOPID-2875,IOPID-2887] Group all `identification` files under `features/identification` folder
  ts/features/authentication/fastLogin/saga/tokenRefreshSaga.ts
  ts/features/fci/saga/index.ts
  ts/features/identification/README.md
  ts/features/identification/analytics/__tests__/index.test.ts
  ts/features/identification/analytics/index.ts
  ts/features/identification/components/IdentificationNumberPad.tsx
  ts/features/identification/components/__tests__/IdentificationNumberPad.test.tsx
  ts/features/identification/sagas/__tests__/identificationSaga.test.ts
  ts/features/identification/sagas/index.ts
  ts/features/identification/screens/IdentificationLockModal.tsx
  ts/features/identification/screens/IdentificationModal.tsx
  ts/features/identification/screens/__tests__/IdentificationModal.test.tsx
  ts/features/identification/store/actions/__tests__/index.test.ts
  ts/features/identification/store/actions/index.ts
  ts/features/identification/store/reducers/__tests__/identification.test.ts
  ts/features/identification/store/reducers/__tests__/identificationStateMigration.test.ts
  ts/features/identification/store/reducers/index.ts
  ts/features/identification/store/selectors/__tests__/index.test.ts
  ts/features/identification/store/selectors/index.ts
  ts/features/identification/utils/__tests__/index.test.tsx
  ts/features/identification/utils/index.tsx
  ts/features/idpay/code/screens/IdPayCodeOnboardingScreen.tsx
  ts/features/idpay/code/screens/IdPayCodeRenewScreen.tsx
  ts/features/idpay/payment/screens/IDPayPaymentAuthorizationScreen.tsx
  ts/features/ingress/__test__/IngressScreen.test.tsx
  ts/features/ingress/screens/IngressScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialPreviewScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceEidPreviewScreen.tsx
  ts/features/itwallet/presentation/details/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/settings/privacy/screens/RemoveAccountDetailsScreen.tsx
  ts/features/settings/security/screens/SecurityScreen.tsx
  ts/features/settings/security/screens/__tests__/SecurityScreen.test.tsx
  ts/features/zendesk/saga/index.ts
  ts/sagas/index.ts
  ts/sagas/startup.ts
  ts/sagas/startup/watchApplicationActivitySaga.ts
  ts/screens/modal/RootModal.tsx
  ts/store/actions/types.ts
  ts/store/middlewares/__tests__/analytics.test.ts
  ts/store/middlewares/analytics.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
Labels: IO-A&I

#6904 feat: [IOPID-2814,IOPID-2759] add helpful resources bottomsheet on LandingScreen and refactor test login
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/features/authentication/common/analytics/index.ts
  ts/features/authentication/common/navigation/__test__/__snapshots__/AuthenticationNavigator.test.tsx.snap
  ts/features/authentication/login/idp/screens/IdpSelectionScreen.tsx
  ts/features/authentication/login/landing/__tests__/__snapshots__/LandingScreen.test.tsx.snap
  ts/features/authentication/login/landing/__tests__/useInfoBottomsheetComponent.test.tsx
  ts/features/authentication/login/landing/hooks/useInfoBottomsheetComponent.tsx
  ts/features/authentication/login/landing/screens/LandingScreen.tsx
  ts/features/authentication/login/optIn/screens/OptInScreen.tsx
  ts/features/services/details/components/ServiceDetailsMetadata.tsx
  yarn.lock
Labels: legal-approved ⚖️ ✅, IO-A&I

#6909 fix: [IOCOM-2327] Global mock for I18n
  jestSetup.js
  ts/__mocks__/react-native-i18n.ts
  ts/boot/__tests__/configureStoreAndPersistor.test.ts
  ts/features/bonus/cgn/analytics/__tests__/index.test.ts
  ts/features/fci/analytics/__tests__/index.test.ts
  ts/features/messages/analytics/__test__/index.test.ts
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsBody.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsBody.test.tsx.snap
  ts/features/payments/checkout/analytics/__tests__/index.test.ts
  ts/features/pushNotifications/analytics/__tests__/index.test.ts
  ts/features/pushNotifications/utils/__tests__/configurePushNotification.test.ts
  ts/mixpanelConfig/___tests___/profileProperties.test.ts
  ts/mixpanelConfig/___tests___/superProperties.test.ts
  ts/sagas/__tests__/mixpanel.test.ts
  ts/store/middlewares/__tests__/analytics.test.ts
Labels: IO-Comunicazione, Cross

#6912 fix: [IOPID-2949] keep `cie` and `connectivityStatus` after logout
  ts/store/reducers/index.ts
Labels: Bug 🐞, IO-A&I

#6915 refactor: [IOPID-2663] Change EIC and SPID banner copy
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/config.ts
  ts/features/authentication/login/cie/screens/CiePinScreen.tsx
  ts/features/authentication/login/cie/screens/__test__/CiePinScreen.test.tsx
  ts/features/authentication/login/cie/screens/__test__/__snapshots__/CiePinScreen.test.tsx.snap
  ts/features/authentication/login/idp/screens/IdpSelectionScreen.tsx
  ts/features/authentication/login/idp/screens/__test__/IdpSelectionScreen.test.tsx
Labels: IO-A&I

#6925 chore: [IOBP-1581] Add more metadata to track inside the CGN debug mode
  ts/components/WebviewComponent.tsx
  ts/features/settings/devMode/playgrounds/CgnLandingPlayground.tsx
Labels: Carta Giovani Nazionale

#6923 refactor(onboarding): [IOPID-2875] Group all `onboarding` files under `ts/features/onboarding` folder
  ts/features/authentication/login/cie/components/CieIdLoginWebView.tsx
  ts/features/authentication/login/cie/screens/CieConsentDataUsageScreen.tsx
  ts/features/authentication/login/cie/screens/__test__/CieConsentDataUsageScreen.test.tsx
  ts/features/mailCheck/sagas/checkAcknowledgedEmailSaga.ts
  ts/features/mailCheck/sagas/checkEmailSaga.ts
  ts/features/onboarding/README.md
  ts/features/onboarding/hooks/useOnboardingAbortAlert.ts
  ts/features/onboarding/navigation/OnboardingNavigator.tsx
  ts/features/onboarding/navigation/params/OnboardingParamsList.ts
  ts/features/onboarding/saga/biometric/biometricStateSagas.ts
  ts/features/onboarding/saga/biometric/checkAcknowledgedFingerprintSaga.ts
  ts/features/onboarding/saga/completeOnboardingSaga.ts
  ts/features/onboarding/saga/watchAbortOnboardingSaga.ts
  ts/features/onboarding/screens/OnboardingCompletedScreen.tsx
  ts/features/onboarding/screens/OnboardingPinScreen.tsx
  ts/features/onboarding/screens/OnboardingServicesPreferenceScreen.tsx
  ts/features/onboarding/screens/OnboardingShareDataScreen.tsx
  ts/features/onboarding/screens/OnboardingTosScreen.tsx
  ts/features/onboarding/screens/ServicePreferenceCompleteScreen.tsx
  ts/features/onboarding/screens/__tests__/EmailInsertScreen.test.tsx
  ts/features/onboarding/screens/__tests__/OnboardingCompletedScreen.test.tsx
  ts/features/onboarding/screens/__tests__/OnboardingTosScreen.test.tsx
  ts/features/onboarding/screens/biometric&securityChecks/FingerprintScreen.tsx
  ts/features/onboarding/screens/biometric&securityChecks/MissingDeviceBiometricScreen.tsx
  ts/features/onboarding/screens/biometric&securityChecks/MissingDevicePinScreen.tsx
  ts/features/onboarding/screens/biometric&securityChecks/analytics/index.ts
  ts/features/onboarding/store/actions/index.ts
  ts/features/onboarding/store/reducers/index.ts
  ts/features/onboarding/store/selectors/index.ts
  ts/features/pushNotifications/screens/OnboardingNotificationsPreferencesScreen.tsx
  ts/features/settings/security/shared/components/PinCreation.tsx
  ts/features/settings/userData/shared/screens/EmailInsertScreen.tsx
  ts/features/settings/userData/shared/screens/EmailValidationSendEmailScreen.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/sagas/services/servicesOptinSaga.ts
  ts/sagas/startup.ts
  ts/sagas/startup/__tests__/checkAcceptedTosSaga.test.tsx
  ts/sagas/startup/checkAcceptedTosSaga.ts
  ts/sagas/startup/watchAbortOnboardingSaga.ts
  ts/store/actions/navigation.ts
  ts/store/actions/types.ts
  ts/store/reducers/index.ts
  ts/store/reducers/types.ts
  ts/utils/__tests__/hooks/useOnbardingAbortAlert.test.ts
Labels: IO-A&I

#6927 chore: [IOPID-2663]: Track help center links
  ts/features/authentication/login/cie/screens/CiePinScreen.tsx
  ts/features/authentication/login/idp/screens/IdpSelectionScreen.tsx
  ts/features/authentication/login/optIn/screens/OptInScreen.tsx
Labels: IO-A&I

#6916 feat: [IOPID-2968] offline wallet: session expired scenario
  locales/en/index.json
  locales/it/index.json
  ts/features/authentication/login/landing/screens/LandingScreen.tsx
  ts/features/identification/utils/index.tsx
  ts/features/itwallet/wallet/utils/withOfflineAlert.tsx
  ts/store/reducers/index.ts
Labels: IO-A&I

#6879 feat(IT Wallet): [SIW-2157] Add remote presentation
  ios/Podfile.lock
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/features/barcode/screens/BarcodeScanScreen.tsx
  ts/features/barcode/types/__tests__/decoders.test.ts
  ts/features/barcode/types/decoders.ts
  ts/features/itwallet/common/components/ItwDataExchangeIcons.tsx
  ts/features/itwallet/common/hooks/useItwFailureSupportModal.tsx
  ts/features/itwallet/common/utils/ItwFailureTypes.ts
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwTypesUtils.ts
  ts/features/itwallet/issuance/components/ItwRequestedClaimsList.tsx
  ts/features/itwallet/machine/credential/context.ts
  ts/features/itwallet/playgrounds/components/ItwRemotePresentationSection.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/remote/Utils/itwRemoteTypeUtils.ts
  ts/features/itwallet/presentation/remote/components/ItwRemoteDeepLinkFailure.tsx
  ts/features/itwallet/presentation/remote/components/ItwRemoteLoadingScreen.tsx
  ts/features/itwallet/presentation/remote/components/ItwRemotePresentationDetails.tsx
  ts/features/itwallet/presentation/remote/machine/__tests__/machine.test.ts
  ts/features/itwallet/presentation/remote/machine/actions.ts
  ts/features/itwallet/presentation/remote/machine/actors.ts
  ts/features/itwallet/presentation/remote/machine/context.ts
  ts/features/itwallet/presentation/remote/machine/events.ts
  ts/features/itwallet/presentation/remote/machine/machine.ts
  ts/features/itwallet/presentation/remote/machine/provider.tsx
  ts/features/itwallet/presentation/remote/machine/selectors.ts
  ts/features/itwallet/presentation/remote/machine/tags.ts
  ts/features/itwallet/presentation/remote/navigation/ItwRemoteParamsList.ts
  ts/features/itwallet/presentation/remote/navigation/ItwRemoteStackNavigator.tsx
  ts/features/itwallet/presentation/remote/navigation/routes.ts
  ts/features/itwallet/presentation/remote/screens/ItwRemoteAuthResponseScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteRequestValidationScreen.tsx
  ts/features/itwallet/presentation/remote/screens/__tests__/ItwRemoteRequestValidation.test.tsx
  ts/features/itwallet/presentation/remote/utils/__tests__/itwRemotePresentationUtils.test.ts
  ts/features/itwallet/presentation/remote/utils/itwRemotePresentationUtils.ts
  ts/features/itwallet/presentation/remote/utils/itwRemoteTypeUtils.ts
  yarn.lock
Labels: IT Wallet

#6902 feat(IT Wallet): [SIW-2213] add L3 identification mode
  img/features/itWallet/identification/itw_cie_pin_placeholder.png
  img/features/itWallet/identification/itw_cie_placeholder.png
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/common/hooks/useItwIdentificationBottomSheet.tsx
  ts/features/itwallet/identification/components/DefaultIdentificationView.tsx
  ts/features/itwallet/identification/components/L3IdentificationView.tsx
  ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
  ts/features/itwallet/identification/screens/__tests__/ItwIdentificationModeSelectionScreen.test.tsx
  ts/features/itwallet/machine/eid/context.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6898 chore: [IOPLT-1092] Add dark mode support for the `ItwCredentialTrustmark`
  ts/features/itwallet/trustmark/components/ItwCredentialTrustmark.tsx
Labels: Dark mode 🌝, Experimental lab ✨

#6933 fix:[IOCOM-2344] `APPLICATION_ERROR` not being reported
  index.js
Labels: IO-Comunicazione, Cross
