Repository pagopa/io-app, pull requests merged in 2025-03, with the labels that each got.

#6768 feat(IT Wallet): [SIW-2042] Use IOMarkdown when displaying a remote message inside credential presentation
  ts/features/itwallet/presentation/details/components/ItwPresentationCredentialStatusAlert.tsx
Labels: IT Wallet

#6760 refactor: [IOPID-2671] Updated `landingScreenBannerMap` config
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/landingScreenMultiBanner/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/landingScreenMultiBanner/store/__tests__/selectors.test.tsx
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/profileSettings/store/actions/index.ts
  ts/features/profileSettings/store/reducers/index.ts
  ts/features/profileSettings/store/selectors/index.ts
  ts/screens/profile/components/SettingsDiscoveryBanner.tsx
  ts/screens/profile/components/__test__/SettingsDiscoveryBanner.test.tsx
  ts/screens/profile/components/__test__/__snapshots__/SettingsDiscoveryBanner.test.tsx.snap
  ts/store/actions/types.ts
  ts/store/reducers/index.ts
Labels: IO-A&I

#6766 fix: [IOPID-2484] Fix `MIXPANEL_SET_ENABLED` event tracking in the onBoarding flow
  ts/screens/onboarding/OnboardingShareDataScreen.tsx
Labels: Bug 🐞, IO-A&I

#6746 chore(IT Wallet): [SIW-2019] Improve integrity service warm up and availability check
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/issuance/store/actions/index.ts
  ts/features/itwallet/issuance/store/reducers/__tests__/index.test.ts
  ts/features/itwallet/issuance/store/reducers/index.ts
  ts/features/itwallet/issuance/store/selectors/index.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkIntegrityServiceReadySaga.test.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkIntegrityServiceReadySaga.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/actors.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6771 chore: [IOBP-1231] Removed total amount from IdPayCard if reward type is `EXPENSE`
  scripts/generate-api-models.sh
  ts/features/idpay/wallet/components/IdPayCard.tsx
  ts/features/idpay/wallet/components/__tests__/IdPayCard.test.tsx
  ts/features/idpay/wallet/components/__tests__/__snapshots__/IdPayCard.test.tsx.snap
Labels: IDPay, IO-Bonus e pagamenti

#6749 chore(IT Wallet): [SIW-2032] Add collapsible credential claims in RP trust screen
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/common/components/ItwClaimsDisclosure/ItwOptionalClaim.tsx
  ts/features/itwallet/common/components/ItwClaimsDisclosure/ItwStaticClaim.tsx
  ts/features/itwallet/common/components/ItwClaimsDisclosure/index.tsx
  ts/features/itwallet/common/components/__tests__/ItwClaimsDisclosure.test.tsx
  ts/features/itwallet/common/components/__tests__/__snapshots__/ItwClaimsDisclosure.test.tsx.snap
  ts/features/itwallet/common/utils/itwClaimsUtils.ts
  ts/features/itwallet/common/utils/itwMocksUtils.ts
  ts/features/itwallet/issuance/components/ItwRequestedClaimsList.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/playgrounds/components/ItwRemotePresentationSection.tsx
  ts/features/itwallet/playgrounds/screens/ItwPlayground.tsx
  ts/features/itwallet/presentation/remote/screens/ItwRemoteClaimsDisclosureScreen.tsx
Labels: IT Wallet

#6781 chore: [IOPLT-999] Update iOS/Android splash screens to new UI
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/values/styles.xml
  ios/ItaliaApp/Images.xcassets/sfondo.imageset/Contents.json
  ios/ItaliaApp/Images.xcassets/sfondo.imageset/gra1.png
  ios/ItaliaApp/Images.xcassets/sfondo.imageset/gra2.png
  ios/ItaliaApp/Images.xcassets/sfondo.imageset/gra3.png
  ios/ItaliaApp/LaunchScreen.storyboard
Labels: Design System

#6757 chore(IT Wallet): [SIW-2055] Update Mixpanel events ITW_DATA_SHARE and ITW_DATA_SHARE_ACCEPTED for async driving license flow
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialAsyncContinuationScreen.tsx
  ts/features/itwallet/issuance/screens/ItwIssuanceCredentialTrustIssuerScreen.tsx
  ts/features/itwallet/machine/credential/__tests__/machine.test.ts
  ts/features/itwallet/machine/credential/actions.ts
  ts/features/itwallet/machine/credential/context.ts
  ts/features/itwallet/machine/credential/events.ts
  ts/features/itwallet/machine/credential/machine.ts
Labels: IT Wallet

#6783 feat: [IOCOM-2096] New lines on messages' IOMarkdown, when a `br` tag is encountered
  ts/components/IOMarkdown/index.tsx
  ts/components/IOMarkdown/renderRules.tsx
  ts/features/common/components/IOMarkdown/__test__/customRules.test.tsx
  ts/features/common/components/IOMarkdown/customRules.tsx
  ts/features/messages/components/Home/PreconditionsContent.tsx
Labels: IO-Comunicazione

#6785 chore: [IOPLT-940] Bumps @pagopa/react-native-zendesk to 0.3.30 to upgrade dependency on android
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: dependencies, Cross

#6784 chore: [IOPLT-989] Remove local `ForceScrollDownView` from the codebase
  ts/components/ForceScrollDownView.tsx
  ts/components/__tests__/ForceScrollDownView.test.tsx
  ts/features/idpay/onboarding/screens/InitiativeDetailsScreen.tsx
Labels: 💀 Dead matter

#6786 feat: [IOPID-2797] Add `LoginExpirationBanner` events
  ts/features/login/preferences/analytics/index.ts
  ts/features/login/preferences/components/LoginExpirationBanner.tsx
Labels: IO-A&I

#6773 fix: [PE-998,PE-999,PE-1000,PE-1001] CGN list item `a11y`
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/features/bonus/cgn/screens/merchants/CgnMerchantCategoriesListScreen.tsx
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsListScreen.tsx
  yarn.lock
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6776 chore: [IOBP-1190] Add a11y announcement inside the payment method details screen
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/details/components/PaymentsMethodDetailsBaseScreenComponent.tsx
  ts/hooks/useHeaderSecondLevel.tsx
Labels: a11y, IO-Bonus e pagamenti

#6780 fix: [IOBP-1238] a11y label to the ReceiptListItemTransaction component
  package.json
  ts/features/bonus/cgn/screens/merchants/__tests__/__snapshots__/CgnMerchantsCategoriesSelectionScreen.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/TabNavigationContainer.test.tsx.snap
  ts/features/payments/receipts/components/ReceiptListItemTransaction.tsx
  ts/features/payments/receipts/components/___tests___/ReceiptFilterTabs.test.tsx
  yarn.lock
Labels: a11y, IO-Bonus e pagamenti

#6790 chore: [IOBP-1185,IOBP-1188] Announce title for screens with no header title
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/checkout/screens/WalletPaymentConfirmScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
Labels: a11y, IO-Bonus e pagamenti

#6779 chore: [IOBP-1243,IOBP-1244,IOBP-1241] a11y improvements on payment method details card preview
  ts/features/payments/common/components/PaymentCard.tsx
  ts/features/payments/details/components/PaymentsMethodDetailsBaseScreenComponent.tsx
Labels: a11y, IO-Bonus e pagamenti

#6775 chore: [IOBP-1186,IOBP-1187] Add a11y announcement when sorting the PSP list
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/checkout/hooks/useSortPspBottomSheet.tsx
  ts/features/payments/checkout/screens/WalletPaymentMakeScreen.tsx
Labels: a11y, IO-Bonus e pagamenti

#6791 fix: [IOBP-1361] CGN webview referer unused header
  ts/features/bonus/cgn/screens/merchants/CgnMerchantLandingWebview.tsx
Labels: Carta Giovani Nazionale, IO-Bonus e pagamenti

#6792 chore: [IOBP-1236] Adjust `a11y` RadioGroup item price label
  package.json
  ts/features/bonus/cgn/screens/merchants/__tests__/__snapshots__/CgnMerchantsCategoriesSelectionScreen.test.tsx.snap
  ts/features/messages/components/Home/__tests__/__snapshots__/TabNavigationContainer.test.tsx.snap
  yarn.lock
Labels: a11y, IO-Bonus e pagamenti

#6795 fix: [IOBP-1360] Banner error state text align
  ts/components/ui/BannerErrorState.tsx
Labels: IO-Bonus e pagamenti

#6796 refactor: [IOBP-1362] Removed self declaration DPR link text into IDPay prerequisites screen
  locales/en/index.json
  locales/it/index.json
  ts/features/idpay/onboarding/screens/BoolValuePrerequisitesScreen.tsx
  ts/features/idpay/onboarding/screens/InputFormVerificationScreen.tsx
  ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
  ts/urls.ts
Labels: IDPay, IO-Bonus e pagamenti

#6789 feat: [IOAPPX-491] New remote feature flag for IOMarkdown
  jestSetup.js
  scripts/generate-api-models.sh
  ts/boot/__tests__/__snapshots__/persistedStore.test.ts.snap
  ts/boot/__tests__/configureStoreAndPersistor.test.ts
  ts/boot/configureStoreAndPersistor.ts
  ts/features/common/store/reducers/index.ts
  ts/features/messages/components/Home/PreconditionsContent.tsx
  ts/features/messages/saga/__test__/handleMessagePrecondition.test.ts
  ts/features/messages/saga/handleMessagePrecondition.ts
  ts/features/messages/screens/MessageDetailsScreen.tsx
  ts/features/pushNotifications/utils/__tests__/index.test.ts
  ts/features/services/details/components/CardWithMarkdownContent.tsx
  ts/screens/profile/DeveloperModeSection.tsx
  ts/store/actions/persistedPreferences.ts
  ts/store/reducers/__tests__/persistedPreferences.test.ts
  ts/store/reducers/backendStatus/__tests__/remoteConfig.test.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
  ts/store/reducers/persistedPreferences.ts
Labels: IO-Comunicazione

#6798 fix: [IOBP-1363] IDPay multi value prerequisites value mapping
  ts/features/idpay/onboarding/screens/MultiValuePrerequisitesScreen.tsx
Labels: Bug 🐞, IDPay, IO-Bonus e pagamenti

#6767 feat: [IOPID-2687] Offline wallet: no internet connection scenario
  locales/en/index.json
  locales/it/index.json
  ts/features/ingress/__test__/IngressScreen.test.tsx
  ts/features/ingress/screens/IngressScreen.tsx
  ts/features/ingress/store/actions/index.ts
  ts/features/ingress/store/reducer/index.ts
  ts/features/ingress/store/selectors/index.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/wallet/utils/withOfflineAlert.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/OfflineStackNavigator.tsx
  ts/navigation/__test__/AppStackNavigator.test.tsx
  ts/navigation/__test__/__snapshots__/AppStackNavigator.test.tsx.snap
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
  ts/screens/modal/IdentificationModal.tsx
  ts/store/reducers/startup.ts
Labels: scheduled, IO-A&I

#6797 chore: [IOBP-1218] `mixpanel` success download receipt event
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/payments/common/types/PaymentAnalytics.ts
  ts/features/payments/history/store/__tests__/store.test.ts
  ts/features/payments/history/store/reducers/index.ts
  ts/features/payments/receipts/analytics/index.ts
  ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
Labels: IO-Bonus e pagamenti

#6778 chore(IT Wallet): [SIW-2072] Ensure ITW is ready when app enters offline mode
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/selectors/remoteConfig.ts
  ts/features/itwallet/navigation/ItwStackNavigator.tsx
  ts/features/itwallet/wallet/utils/withOfflineAlert.tsx
  ts/features/wallet/store/selectors/__tests__/index.test.ts
  ts/features/wallet/store/selectors/index.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: IT Wallet

#6697 fix: [IOCOM-2099] Fix a runtime crash when receiving invalid front matter
  ts/features/messages/utils/__tests__/ctas.test.ts
  ts/features/messages/utils/ctas.ts
Labels: IO-Comunicazione

#6801 chore(IT Wallet): [SIW-2073] Add ITW_CREDENTIAL_COPY_LIST_ITEM event
  ts/features/itwallet/analytics/enum.ts
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationClaimsSection.tsx
Labels: IT Wallet

#6804 chore(IT Wallet): [SIW-2109] Add phases to ITW_DATA_SHARE and ITW_DATA_SHARE_ACCEPTED events
  ts/features/itwallet/analytics/index.ts
  ts/features/itwallet/machine/credential/actions.ts
Labels: IT Wallet

#6794 chore(IT Wallet): [SIW-2063] Hidden values on the skeumorphic cards
  ts/features/design-system/core/DSCards.tsx
  ts/features/itwallet/common/components/ItwCredentialClaim.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardClaim.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/CardData.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimImage.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/ClaimLabel.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/CardData.test.tsx
  ts/features/itwallet/common/components/ItwSkeumorphicCard/__tests__/__snapshots__/CardData.test.tsx.snap
  ts/features/itwallet/common/components/ItwSkeumorphicCard/index.tsx
  ts/features/itwallet/common/utils/constants.ts
  ts/features/itwallet/playgrounds/components/ItwSkeumorphicCredentialSection.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationCredentialCard.tsx
  ts/features/itwallet/presentation/details/screens/ItwPresentationCredentialCardModal.tsx
Labels: IT Wallet

#6802 chore: [IOBP-1299] CGN discount screen `a11y` focus on title
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountHeader.tsx
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6782 chore(IT Wallet): [SIW-2036] Prevent user interactions with components requiring internet access
  locales/en/index.json
  locales/it/index.json
  ts/components/error/OfflineFailure.tsx
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/lifecycle/screens/ItwLifecycleWalletRevocationScreen.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationDetailsFooter.tsx
  ts/features/itwallet/presentation/details/screens/ItwPresentationCredentialDetailScreen.tsx
  ts/features/itwallet/trustmark/components/ItwCredentialTrustmark.tsx
  ts/features/itwallet/wallet/utils/withOfflineAlert.tsx
  ts/hooks/__tests__/useOfflineGuard.test.ts
  ts/hooks/useHeaderSecondLevel.tsx
  ts/hooks/useOfflineGuard.ts
  ts/navigation/OfflineStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/navigation/routes.ts
  ts/sagas/__tests__/initializeApplicationSaga.test.ts
  ts/sagas/startup.ts
Labels: IT Wallet

#6808 chore: [IOBP-1302] CGN adjust `a11y` module discount label
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/bonus/cgn/components/merchants/ModuleCgnDiscount.tsx
  ts/features/bonus/cgn/components/merchants/utils/___tests___/index.test.tsx
  ts/features/bonus/cgn/components/merchants/utils/index.tsx
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6806 chore: [IOBP-1384] Track organization full name inside the CGN discount details page
  scripts/generate-api-models.sh
  ts/features/bonus/cgn/screens/discount/CgnDiscountDetailScreen.tsx
Labels: IO-Bonus e pagamenti

#6809 feat: [IOBP-1257,IOBP-1258] Add outcome screen when all payment methods are expired
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/checkout/analytics/index.ts
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
  ts/features/payments/checkout/screens/WalletPaymentOutcomeScreen.tsx
  ts/features/payments/checkout/screens/__tests__/__snapshots__/WalletPaymentOutcomeScreen.test.tsx.snap
  ts/features/payments/checkout/types/PaymentOutcomeEnum.ts
  ts/features/payments/onboarding/screens/PaymentsOnboardingFeedbackScreen.tsx
Labels: IO-Bonus e pagamenti

#6788 feat:[IOCOM-2205] PN engagement banner logic
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/pn/components/PNActivationReminderBanner.tsx
  ts/features/pn/components/__test__/PNActivationReminderBanner.test.tsx
  ts/features/pn/components/__test__/__snapshots__/PNActivationReminderBanner.test.tsx.snap
  ts/features/pn/hooks/__tests__/usePnPreferencesFetcher.test.tsx
  ts/features/pn/hooks/usePnPreferencesFetcher.ts
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/navigation/params.ts
  ts/features/pn/navigation/routes.ts
  ts/features/pn/screens/PnReminderBannerFlow.tsx
  ts/features/pn/screens/__test__/PnReminderBannerFlow.test.tsx
  ts/features/pn/screens/__test__/__snapshots__/PnReminderBannerFlow.test.tsx.snap
  ts/features/pn/store/sagas/watchPnSaga.ts
  ts/features/services/details/store/reducers/__tests__/servicePreference.test.ts
  ts/store/reducers/backendStatus/__tests__/remoteConfig.test.ts
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IO-Comunicazione

#6817 fix: [IOBP-1379,IOBP-IOBP-1380] Disable CGN header transparency when screen reader is enabled
  ts/components/BonusCard/BonusCard.tsx
  ts/components/BonusCard/BonusCardScreenComponent.tsx
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6821 feat: [IOCOM-2184] addition of loading and result UI for SEND banner flow
  locales/en/index.json
  locales/it/index.json
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/screens/PnReminderBannerFlow.tsx
  ts/features/pn/screens/__test__/__snapshots__/PnReminderBannerFlow.test.tsx.snap
Labels: IO-Comunicazione

#6777 chore: [IOPLT-998] Remove legacy components from the codebase
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/components/LabelledItem/LabelledItemIconOrImage.tsx
  ts/components/LabelledItem/__tests__/LabelledItem.test.tsx
  ts/components/LabelledItem/index.tsx
  ts/components/screens/BaseHeader.tsx
  ts/components/screens/BaseScreenComponent/index.tsx
  ts/components/screens/ListItemComponent.tsx
  ts/components/screens/TopScreenComponent.tsx
  ts/components/search/SearchButton.tsx
  ts/features/bonus/cgn/components/merchants/search/OrderOption.tsx
  ts/features/design-system/core/DSLegacyListItems.tsx
  ts/features/design-system/core/DSLegacyTextFields.tsx
  ts/features/design-system/navigation/navigator.tsx
  ts/features/design-system/navigation/params.ts
  ts/features/design-system/navigation/routes.ts
  ts/features/idpay/configuration/screens/IbanOnboardingScreen.tsx
  ts/screens/profile/playgrounds/IdPayCodePlayground.tsx
  ts/screens/profile/playgrounds/IdPayOnboardingPlayground.tsx
  yarn.lock
Labels: Design System, 💀 Dead matter

#6818 chore: [IOBP-1211,IOBP-1207] Payment checkout screen `TextInputValidation` focus
  ts/features/payments/checkout/screens/WalletPaymentInputFiscalCodeScreen.tsx
Labels: a11y, IO-Bonus e pagamenti

#6810 chore(IT Wallet): [SIW-2108] Added hide values action in full screen view of skeuomorphic card
  locales/en/index.json
  locales/it/index.json
  ts/features/itwallet/presentation/details/components/ItwPresentationCredentialCardFlipButton.tsx
  ts/features/itwallet/presentation/details/components/ItwPresentationCredentialCardHideValuesButton.tsx
  ts/features/itwallet/presentation/details/screens/ItwPresentationCredentialCardModal.tsx
Labels: IT Wallet

#6825 chore: [IOBP-1414] Adjust a11y discount validity dates label
  ts/features/bonus/cgn/components/merchants/discount/CgnDiscountContent.tsx
Labels: a11y, Carta Giovani Nazionale, IO-Bonus e pagamenti

#6827 feat:[IOCOM-2223] persisted dismiss logic for SEND banner
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/landingScreenMultiBanner/components/LandingScreenBannerPicker.tsx
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/pn/components/PNActivationReminderBanner.tsx
  ts/features/pn/screens/PnReminderBannerFlow.tsx
  ts/features/pn/store/actions/index.ts
  ts/features/pn/store/reducers/bannerDismiss.ts
  ts/features/pn/store/reducers/index.ts
  ts/store/reducers/index.ts
Labels: IO-Comunicazione

#6829 feat: [IOCOM-2183] SEND banner mixpanel events
  ts/features/pn/analytics/activationReminderBanner.ts
  ts/features/pn/components/PNActivationReminderBanner.tsx
  ts/features/pn/screens/PnReminderBannerFlow.tsx
Labels: IO-Comunicazione

#6813 fix: [IOPID-2102] Change Carousel dots style
  ts/screens/authentication/__tests__/__snapshots__/LandingScreen.test.tsx.snap
  ts/screens/authentication/carousel/Carousel.tsx
  ts/utils/hooks/theme/index.ts
Labels: a11y, IO-A&I

#6812 fix: [IOPID-2100] Adjust wrong accessibility focus on modal closure in iOS devices
  ts/screens/authentication/cie/CiePinScreen.tsx
Labels: a11y, IO-A&I

#6819 feat: [IOPID-595] Add new 404 page
  locales/en/index.json
  locales/it/index.json
  ts/features/pageNotFound/__tests__/__snapshots__/index.tsx.snap
  ts/features/pageNotFound/__tests__/index.tsx
  ts/features/pageNotFound/screens/index.tsx
  ts/navigation/AppStackNavigator.tsx
  ts/navigation/AuthenticatedStackNavigator.tsx
  ts/navigation/params/AppParamsList.ts
  ts/navigation/routes.ts
  ts/screens/modal/UpdateAppModal.tsx
Labels: Cross

#6834 feat: [IOCOM-2185] SEND reminder banner landing UI and banner activation
  img/features/pn/activationLandingHero.png
  locales/en/index.json
  locales/it/index.json
  scripts/generate-api-models.sh
  ts/features/common/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/landingScreenMultiBanner/store/__tests__/__snapshots__/reducer.test.ts.snap
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/pn/navigation/navigator.tsx
  ts/features/pn/reminderBanner/components/PNActivationReminderBanner.tsx
  ts/features/pn/reminderBanner/components/PnBannerFlowComponents.tsx
  ts/features/pn/reminderBanner/components/__test__/PNActivationReminderBanner.test.tsx
  ts/features/pn/reminderBanner/components/__test__/__snapshots__/PNActivationReminderBanner.test.tsx.snap
  ts/features/pn/reminderBanner/screens/PnReminderBannerFlow.tsx
  ts/features/pn/reminderBanner/screens/__test__/PnReminderBannerFlow.test.tsx
  ts/features/pn/reminderBanner/screens/__test__/__snapshots__/PnReminderBannerFlow.test.tsx.snap
  ts/features/pn/screens/PnReminderBannerFlow.tsx
  ts/store/reducers/backendStatus/remoteConfig.ts
Labels: IO-Comunicazione

#6765 chore: [IOCOM-2187] Remove unused code for payments on messages
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/__mocks__/paymentPayloads.ts
  ts/utils/__tests__/payment.test.ts
  ts/utils/payment.ts
  ts/utils/testFaker.ts
Labels: IO-Comunicazione

#6800 fix: [IOPAE-1727] Fixed accessibility issue in services search
  ts/features/services/details/components/ServiceDetailsMetadata.tsx
  ts/features/services/home/screens/ServicesHomeScreen.tsx
  ts/features/services/institution/screens/InstitutionServicesScreen.tsx
  ts/features/services/search/hooks/useInstitutionsFetcher.tsx
  ts/features/services/search/screens/SearchScreen.tsx
Labels: a11y, IO-Enti e Servizi

#6774 feat: [IOCOM-2174] Delayed push token registration attempt
  ts/RootContainer.tsx
  ts/boot/configureStoreAndPersistor.ts
  ts/features/pushNotifications/sagas/__tests__/pushNotificationTokenUpload.test.ts
  ts/features/pushNotifications/sagas/pushNotificationTokenUpload.ts
  ts/features/pushNotifications/store/reducers/__tests__/__snapshots__/index.test.ts.snap
  ts/features/pushNotifications/store/reducers/__tests__/index.test.ts
  ts/features/pushNotifications/store/reducers/__tests__/installation.test.ts
  ts/features/pushNotifications/store/reducers/index.ts
  ts/features/pushNotifications/store/reducers/installation.ts
  ts/features/pushNotifications/utils/__tests__/configurePushNotification.test.ts
  ts/features/pushNotifications/utils/__tests__/index.test.ts
  ts/features/pushNotifications/utils/configurePushNotification.ts
  ts/features/pushNotifications/utils/index.ts
  ts/store/reducers/__tests__/index.test.ts
  ts/store/reducers/index.ts
Labels: IO-Comunicazione

#6811 feat: [IOCOM-2211] Add `date_sent` parameter on `OPEN_MESSAGE` event
  ts/features/messages/analytics/__test__/index.test.ts
  ts/features/messages/analytics/index.ts
  ts/features/messages/saga/__test__/handleLoadMessageData.test.ts
  ts/features/messages/saga/handleLoadMessageData.ts
  ts/features/messages/screens/MessageRouterScreen.tsx
  ts/features/messages/screens/__tests__/MessageRouterScreen.test.tsx
  ts/features/messages/store/actions/__tests__/index.test.ts
  ts/features/messages/store/actions/index.ts
  ts/features/messages/store/reducers/__tests__/messageGetStatus.test.ts
  ts/features/pn/__mocks__/pnMessage.ts
  ts/features/pn/components/__test__/MessageDetails.test.tsx
  ts/features/pn/screens/__test__/MessageDetailsScreen.test.tsx
  ts/utils/__tests__/analytics.test.ts
  ts/utils/analytics.ts
Labels: IO-Comunicazione

#6761 chore: [IOCOM-2087] Show reminder (on message details) ignoring payment status
  ts/features/messages/components/MessageDetail/MessageDetailsReminder.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsReminder.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/MessageDetailsReminderExpired.test.tsx
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminder.test.tsx.snap
  ts/features/messages/components/MessageDetail/__tests__/__snapshots__/MessageDetailsReminderExpired.test.tsx.snap
  ts/features/messages/screens/__tests__/MessageDetailsScreen.test.tsx
  ts/features/messages/store/reducers/__tests__/payments.test.ts
  ts/features/messages/store/reducers/payments.ts
Labels: IO-Comunicazione

#6838 refactor: [IOBP-1451] Update payment summary bottom sheet text
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/features/payments/checkout/screens/WalletPaymentDetailScreen.tsx
Labels: IO-Bonus e pagamenti

#6843 chore: [IOBP-1487] Enhance Mixpanel analytics for payment events
  ts/features/payments/receipts/saga/handleDisableReceipt.ts
  ts/features/payments/receipts/screens/ReceiptDetailsScreen.tsx
  ts/features/payments/receipts/screens/ReceiptPreviewScreen.tsx
Labels: IO-Bonus e pagamenti

#6832 chore: [IOBP-1445] Update locales for `WAITING_CONFIRMATION_EMAIL` outcome
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
Labels: IO-Bonus e pagamenti

#6837 chore: [IOBP-1242] Announce `Tab` role and position for screen readers
  locales/de/index.json
  locales/en/index.json
  locales/it/index.json
  ts/components/screens/BaseHeader.tsx
  ts/features/payments/checkout/components/WalletPaymentFeedbackBanner.tsx
  ts/features/payments/receipts/components/ReceiptFilterTabs.tsx
Labels: a11y, IO-Bonus e pagamenti

#6815 feat: [IOCOM-2235,IOCOM-2240] Push token absence tracking and fix for missing token on iOS
  google-services-dev.json
  ts/App.tsx
  ts/RootContainer.tsx
  ts/boot/configureStoreAndPersistor.ts
  ts/features/pushNotifications/sagas/__tests__/profileAndSystemNotificationsPermissions.test.tsx
  ts/features/pushNotifications/sagas/profileAndSystemNotificationsPermissions.ts
  ts/features/pushNotifications/utils/__tests__/configurePushNotification.test.ts
  ts/features/pushNotifications/utils/configurePushNotification.ts
  ts/mixpanelConfig/___tests___/profileProperties.test.ts
  ts/mixpanelConfig/___tests___/superProperties.test.ts
  ts/mixpanelConfig/profileProperties.ts
  ts/screens/profile/analytics/__test__/index.test.ts
  ts/screens/profile/analytics/index.ts
Labels: IO-Comunicazione

#6845 feat: [IOCOM-2282] New copy for denied calendar permission popup
  locales/en/index.json
  locales/it/index.json
  ts/features/messages/hooks/useMessageReminder.ts
  ts/screens/profile/PreferencesScreen.tsx
Labels: IO-Comunicazione

#6849 chore: [IOBP-1305] Adjust a11y tab filters into CGN category list screen
  locales/en/index.json
  locales/it/index.json
  ts/features/bonus/cgn/screens/merchants/CgnMerchantsCategoriesSelectionScreen.tsx
  ts/features/bonus/cgn/screens/merchants/__tests__/__snapshots__/CgnMerchantsCategoriesSelectionScreen.test.tsx.snap
Labels: a11y, IO-Bonus e pagamenti

#6851 test: [IOCOM-2287] addition of missing tests for the SEND banner flow
  ts/features/landingScreenMultiBanner/utils/landingScreenBannerMap.tsx
  ts/features/pn/analytics/__test__/activationReminderBanner.test.ts
  ts/features/pn/reminderBanner/components/PnBannerFlowComponents.tsx
  ts/features/pn/reminderBanner/components/__test__/PNActivationReminderBanner.test.tsx
  ts/features/pn/reminderBanner/components/__test__/PnBannerFlowComponents.test.tsx
  ts/features/pn/reminderBanner/components/__test__/__snapshots__/PnBannerFlowComponents.test.tsx.snap
  ts/features/pn/reminderBanner/reducer/__test__/__snapshots__/bannerDismiss.test.ts.snap
  ts/features/pn/reminderBanner/reducer/__test__/bannerDismiss.test.ts
  ts/features/pn/reminderBanner/reducer/bannerDismiss.ts
  ts/features/pn/reminderBanner/screens/__test__/PnReminderBannerFlow.test.tsx
  ts/features/pn/reminderBanner/screens/__test__/__snapshots__/PnReminderBannerFlow.test.tsx.snap
  ts/features/pn/store/reducers/index.ts
  ts/store/reducers/backendStatus/__tests__/remoteConfig.test.ts
Labels: IO-Comunicazione

#6833 feat(IT Wallet): [SIW-2048] Add new device re-enable itw banner
  jest.config.js
  locales/en/index.json
  locales/it/index.json
  package.json
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBanner.tsx
  ts/features/itwallet/common/components/discoveryBanner/ItwDiscoveryBannerOnboarding.tsx
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBanner.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerOnboarding.test.tsx.snap
  ts/features/itwallet/common/components/discoveryBanner/__tests__/__snapshots__/ItwDiscoveryBannerStandalone.test.tsx.snap
  ts/features/itwallet/common/hooks/useItwDiscoveryBannerType.ts
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/common/store/actions/preferences.ts
  ts/features/itwallet/common/store/reducers/preferences.ts
  ts/features/itwallet/common/store/selectors/preferences.ts
  ts/features/itwallet/common/utils/itwAttestationUtils.ts
  ts/features/itwallet/common/utils/itwCredentialIssuanceUtils.ts
  ts/features/itwallet/common/utils/itwIntegrityUtils.ts
  ts/features/itwallet/common/utils/itwIssuanceUtils.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkCurrentWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkCurrentWalletInstanceStateSaga.ts
  ts/utils/hooks/usePreventScreenCapture.ts
  yarn.lock
Labels: IT Wallet

#6852 chore(IT Wallet): [SIW-2081] Handle inconsistent wallet instance states, eID present and integrity key missing
  ts/features/itwallet/common/saga/index.ts
  ts/features/itwallet/lifecycle/saga/__tests__/checkWalletInstanceStateSaga.test.ts
  ts/features/itwallet/lifecycle/saga/checkWalletInstanceStateSaga.ts
  ts/features/itwallet/machine/eid/__tests__/machine.test.ts
  ts/features/itwallet/machine/eid/machine.ts
Labels: IT Wallet

#6854 fix: [IOCOM-2279] logout misbehaviour for SEND banner dismissal
  ts/features/pn/reminderBanner/reducer/__test__/bannerDismiss.test.ts
  ts/features/pn/reminderBanner/reducer/bannerDismiss.ts
  ts/store/reducers/index.ts
Labels: IO-Comunicazione
